### ISSUE TITLE
Game crashes when launching map on iPad with iOS 15.6

### ISSUE THREAD

**Issue by staafl** [vcmi/vcmi#1026]
Trying to run any map or campaign causes the game to crash during loading screen.

Attaching logs - the error seems to be in VCMI_Client_log:

ERROR global [0x16d75b000] - Cannot open dynamic library (/private/var/containers/Bundle/Application/B4F2B840-A45D-4C92-A00C-B16A9F9316AE/vcmiclient.app/Frameworks/AI/libVCAI.dylib). Throwing...

I'm using the GOG version data files (French resources). iPad Pro 12.9, 3rd generation, MTFL2HC/A

Installed the app using Sideloadly 0.27, Launcher says it's latest version as of today

[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/9687537/VCMI_Launcher_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/9687527/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/9687539/VCMI_Server_log.txt)

Thanks for your help!

**Comment by misiokles** [comment]
I guess this is the cause "Error: Unknown entry found: allowedTerrain" but I don't know why this entry is unknown.

**Comment by misiokles** [comment]
Also all creature sounds are missing. And Unknown effect type 'core:dispel'. - are you sure you've installed vcmi ver 1.00, not 0.99?

**Comment by kambala-decapitator** [comment]
@staafl could you upload your signed ipa (i.e. what Sideloadly produced)?

@misiokles VCMI 1.1.0.4205701f96a872dface1504e4d7f2e7be81a67f4

**Comment by staafl** [comment]
@misiokles I installed the daily iOS build from here: https://builds.vcmi.download/branch/develop/iOS/VCMI-branch-develop-4205701.ipa

@kambala-decapitator I had to run Sideloadly again, this is what I managed to grab from my temp folder while it was installing: https://drive.google.com/file/d/1WcGkEpzqQJnVQJ1vLzPEyExjlKqn--Zm/view?usp=sharing

**Comment by kambala-decapitator** [comment]
thanks a lot. Yeah, Sideloadly signs nested dylibs incorrectly :(

```
> for f in /Users/kambala/Downloads/Payload/vcmiclient.app/Frameworks/AI/*
  codesign --verify --verbose=4 "$f"
end
/Users/kambala/Downloads/Payload/vcmiclient.app/Frameworks/AI/libBattleAI.dylib: code object is not signed at all
In architecture: armv7
/Users/kambala/Downloads/Payload/vcmiclient.app/Frameworks/AI/libNullkiller.dylib: code object is not signed at all
In architecture: armv7
/Users/kambala/Downloads/Payload/vcmiclient.app/Frameworks/AI/libStupidAI.dylib: code object is not signed at all
In architecture: armv7
/Users/kambala/Downloads/Payload/vcmiclient.app/Frameworks/AI/libVCAI.dylib: code object is not signed at all
In architecture: armv7
```

could you try AltStore / iOS App Signer manual signing? I know for sure that iOS App Signer does everything correctly, with AltStore there _might_ be issues.

**Comment by staafl** [comment]
Thanks a lot, using iOS App Signer IPA works. Feel free to close this if appropriate.

**Comment by kambala-decapitator** [comment]
I'd rather fix it, as I'm pretty sure Sideloadly is widely used
