### ISSUE TITLE
Scrolling (advmap) via Touch

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#1037]
Scrolling via touch should not be limited to ios and android devices.

For example, there are also windows/linux touch devices. Or even the Steam Deck.

**Comment by kambala-decapitator** [comment]
do you have such device to test? none of the devs do afaik.

**Comment by Laserlicht** [comment]
> do you have such device to test? none of the devs do afaik.

Yes, I have a steam deck.

**Comment by kambala-decapitator** [comment]
probably this needs to be implemented: https://github.com/libsdl-org/SDL/blob/main/docs/README-touch.md

**Comment by nullkiller** [comment]
For windows it should be possible to emulate touch with UWP emulator.

**Comment by nullkiller** [comment]
There is "general/swipe" settings key which enables swiping map with just any mouse button. But logic is surrounded by #ifdef Android or iOS. SDL allows to detect if mouse move is caused by touch by special TouchDeviceID. This may be easier to implement now.

**Comment by nullkiller** [comment]
Actually this ticket is about map scrolling, not scrolling in general

**Comment by Laserlicht** [comment]
@nullkiller  Yes, I have already looked a bit into the code.

The question is whether one does not implement this as in fheroes2: https://github.com/ihhub/fheroes2/pull/5878
So that always with the left button (and thus also touch) the map section can be moved. Would have the advantage that it works on all touch devices and with mouse and you do not have to include touch-specific code.

In fact, we would then not use the middle button on the pc, but the left one for scrolling. Which I personally find much more pleasant.

Along with that, however, this should also be addressed to provide a good user experience: https://github.com/vcmi/vcmi/issues/1036
