### ISSUE TITLE
http://download.vcmi.eu/core.zip is 404

### ISSUE THREAD

**Issue by josch** [vcmi/vcmi#1038]
Hi,

http://download.vcmi.eu/core.zip as referenced from vcmibuilder is 404: https://github.com/vcmi/vcmi/blob/develop/vcmibuilder#L241

Did the URL change and vcmibuilder needs to be adjusted? Or was the file accidentally deleted?

**Comment by nullkiller** [comment]
I expect it is downloads server misconfiguration. So I am afraid it might be hard to fix. What is core.zip?

**Comment by josch** [comment]
According to https://slackbuilds.org/repository/14.1/games/vcmi-core/ it should have the md5sum 18170b8d757074a462f8a2b6fa646ed9 which matches the core.zip I have: [core.zip](https://github.com/vcmi/vcmi/files/9695450/core.zip)

**Comment by nullkiller** [comment]
Ok. Maybe we can add it to vcmi mods as a separate repository. Only still it is not clear to me what is it. The structure looks like a data from original heroes but it is not. It contains some defs. Why vcmi builder needs it?

**Comment by nullkiller** [comment]
The problem is that there is no mention about this core.zip in vcmi installation guides. So it might be some outdated form of vcmi essentials which is included as a part of vcmi itself. Another version is that some installations of HOMM3 lack some specific files which we need. I would try to exclude this core.zip from vcmi-builder and see if it works without it

**Comment by josch** [comment]
According to @IvanSavenko in https://forum.vcmi.eu/t/vcmi-0-96b/886/2 is no longer needed.

**Comment by kambala-decapitator** [comment]
well, download option is disabled in the script explicitly: https://github.com/vcmi/vcmi/blob/3600d09ece165268171d1882f46edd1691342e75/vcmibuilder#L32

core.zip will never be downloaded (unless you define `download=1` in your env).

but removing it from the script completely would be better I think.
