### ISSUE TITLE
"this spell will affect nobody!" dialog doesn't appear

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1049]
example: my hero has amulet that protects from Berserk, human enemy tries to cast Berserk. When you click Berserk in the spell book window, simply nothing happens.

In oh3 spell book is closed and the dialog appears.

The error is here: https://github.com/vcmi/vcmi/blob/3600d09ece165268171d1882f46edd1691342e75/client/windows/CSpellWindow.cpp#L562-L565

`showInfoDialog()` doesn't show the dialog.

**Comment by kambala-decapitator** [comment]
after the battle is over, lots of the dialog is displayed as many times as you try to cast the spell

**Comment by dydzio0614** [comment]
Seems to work for me now in latest develop...
![obraz](https://user-images.githubusercontent.com/9436577/214061127-f2573267-0288-4189-afc5-3a7f5a087f6a.png)

**Comment by IvanSavenko** [comment]
I saw similar issue on Mantis that was referring specifically to *second* player in hotseat
(and potentially - to AI-initiated battles in singleplayer)

**Comment by kambala-decapitator** [comment]
I faced this bug exactly in hot seat game
