### ISSUE TITLE
Wrong version on iOS

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1053]
We have already incremented version on develop branch to 1.1

![image](https://user-images.githubusercontent.com/9308612/193719285-5a29963c-6040-4f93-8d39-63a5ed15623c.jpeg)

**Comment by kambala-decapitator** [comment]
the version was changed in code but not in CMakeLists

**Comment by Nordsoft91** [comment]
Shouldn't it be only one place?

**Comment by kambala-decapitator** [comment]
ideally - yes
