### ISSUE TITLE
Game crash in quick recruit dialog

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1054]
1. Open quick recruitment dialog in any castle
2. Press button minimizing amount for some creature
3. Observe crash

**Comment by kambala-decapitator** [comment]
reverting #944 fixes the crash. @AgostonSzepessy FYI

**Comment by kambala-decapitator** [comment]
funny, but #944 functionality doesn't work either

**Comment by kambala-decapitator** [comment]
fixed it locally, but considering the above not sure if it's worth to push fix or better simply to revert that PR

**Comment by Nordsoft91** [comment]
agree, for such cases should be revert and then author can push again with the fix
