### ISSUE TITLE
Hangs on loading the list of saves

### ISSUE THREAD

**Issue by nullkiller** [vcmi/vcmi#1057]
New game -> Single scenario or Load game -> Single scenario
Before loading a list of possible scenarios/saves game hangs a bit and in MSVC debugger I observe huge memory usage spike (up to 2 Gb). After the list is displayed the memory usage gets back to normal. This needs to be investigated

**Comment by nullkiller** [comment]
This might be due to we do not always bump serialization version in develop.

**Comment by Nordsoft91** [comment]
It make sense to cleanup saves folder

**Comment by nullkiller** [comment]
Now it works fast enough. Clearing old saves seams to help
