### ISSUE TITLE
Quick exchange additional buttons

### ISSUE THREAD

**Issue by nullkiller** [vcmi/vcmi#1062]
For Android devices and other touch oriented we need a way to split stacks using ctrl+click, shift+click and alt+click but with UI buttons.
Ideas:
* Add UI switchers for Alt/Shift/Ctrl - a bit weird UX but sequential ctrl+click will be easier.
* Add dropdown on clicking stack icon. Dropdown will give some split options.
* Add switcher somewhere which will change regular click behavior (same as the first option but buttons will represent exact actions like split 1 or split equally)

**Comment by kambala-decapitator** [comment]
I didn't even know about these shortcuts :)

**Comment by nullkiller** [comment]
As far as I remember there are some shortcuts for arts but not sure if we implemented them or not

**Comment by tianmaster** [comment]
So do you have this plan now? As a player who often plays on small screens, I really need this feature! If the subsequent development plan will include this, thank you very much!

**Comment by tianmaster** [comment]
Can these hotkeys be made into buttons through mod?

**Comment by IvanSavenko** [comment]
Closing, implemented as radial menu
