### ISSUE TITLE
Non finishable battles with mass spells under specific conditions.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#1063]
Bug was described here:
https://forum.vcmi.eu/t/special-artifacts/5761/10

**Comment by nullkiller** [comment]
Draw should be possible so this is a very special case which obviously needs a mod to test it.

**Comment by nullkiller** [comment]
So how about a mod for testing? I do not think anybody will try to fix it without a mod in question

**Comment by nullkiller** [comment]
@misiokles?

**Comment by misiokles** [comment]
I copied infos from the forum, I'll ask author to provide save/mod.
