### ISSUE TITLE
[FEATURE] Possibility to use HD textures

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#1070]
It would be great to be able to use HD textures. Which are already available through the official HD version. Or through mods then.

In my opinion, this would be a great advantage that vcmi would bring over other possibilities.

One possibility would be if you could specify to render the game for example in 2x. And then upscale each texture before output (different modes: linear, cubic, xbrz, etc.).
Except of course the HD textures. Those would be scaled up / down with a different scaling factor (we could specify that in config.json).

But the better way would be complete prescaled textures (for slow upscaling algorithm).

See also here for similar approch in fheroes2: https://github.com/ihhub/fheroes2/discussions/5016 / https://github.com/ihhub/fheroes2/pull/6438 (also hardcoded coordinates)

Some example with ESRGAN (Textures must be upscaled before, regardless of the game -> ESRGAN is slow, and for good results every texture should upscaled seperatly). Please see in Fullscreen, not in the tiny Github Preview.

Left part of the picture is scaled, right the original:
![4x_BSRGAN_town](https://user-images.githubusercontent.com/13953785/211052258-8c50eafb-5307-4942-8db6-49e5fec42b97.jpg)
![4x_BSRGAN_town2](https://user-images.githubusercontent.com/13953785/211054986-e18bfe82-3bd4-4de8-84c1-4924e08ed19a.jpg)

angel in different variants:
![comp_angel](https://user-images.githubusercontent.com/13953785/212484403-8c8571cf-e6e2-4cfe-a772-44fa85fce177.png)

town image original and ESRGAN 
![town_image](https://user-images.githubusercontent.com/13953785/211059775-588904b7-5293-488f-98fb-488ba0ab6bc0.png)

**Comment by misiokles** [comment]
HD graphics are minor problem in this case. What about new values for coordinates and cursor positions almost in every aspects in the game? They are hardcoded and vary when resolution is changed.

**Comment by Laserlicht** [comment]
Yes, this is probably not an easy task. The biggest problem is not even the hardcoded coordinates, I think, but that there is no abstraction layer to sdl.

Otherwise you could extend the render functions: For Scale factor 2 multiply all coordinates (and non hd-textures with filter) by 2. Of course, for hd textures it must be specified by which factor they are larger than the original textures.

But it would be great if heroes iii would get a decent hd version.

**Comment by Laserlicht** [comment]
Here's an idea of how this could be implemented:

![Unbenanntes Diagramm drawio](https://user-images.githubusercontent.com/13953785/212479495-64fa3d08-b0a9-4737-869c-a2ac805dff7a.svg)

This way you could provide scripts (for legal reasons no mods directly) which provide a mod with high resolution textures (nn-upscaling, extract from official hd version, etc.).

User generated content could be available in a higher resolution directly.

The biggest effort here is probably to pass all hardcoded coordinates through a scale function first.

**Comment by Gagert** [comment]
This would be great! Just having the ability to use the high res sprites from the official HD version of Heroes 3 in VCMI could open up possibilities. Even though the official HD version of Heroes 3 doesn't cover the expansions for that game (thereby a lot of "repainted art" is going to be missing), there's a slight possibility that the "missing" sprites and artwork from the expansions could be unofficially remade in high definition by the community itself later on.

On an other note (as some of you might know), the missing source code of Heroes 3 Complete was indeed recovered & FTP'd to UbiSoft by a guy that was originally porting the game to the Mac back in the day. This guy goes under the twitter name DiskBlitz and it was back in 2017 when he announced this on Twitter ([thread here](https://twitter.com/DiskBlitz/status/920801845349466113)).

The reason for me mentioning this is that there's a slight possibility UbiSoft actually repaints all the missing expansion art for an official HD version of Heroes 3 Complete, but given that UbiSoft still hasn't announced anything after all those years, I doubt it. I just wanted to mention this because there's a slight possibility that if VCMI added support for all the HD art from the official HD version of Heroes 3, and artists from the community actually made unofficial HD art for all the missing expansion content, there could indeed be an official HD version of Heroes 3 Complete that makes all of the custom repainted art obsolete.

**Comment by Laserlicht** [comment]
I've made a small hacky script to extract & upscale all images from h3 with brz or esrgan (if you have an nasa pc) and copy it into a mod structure.
https://github.com/Laserlicht/vcmi_upscaler

@IvanSavenko Also looked through the vcmi source a bit. If I understood correctly, not all sdl commands are abstracted yet, right?
Then this is still the step before?

Had a look at the official hd files as well. Interestingly as far as I have seen different scaling levels are used. That means we might need to be able to give each image a scale level as well (from json in mod) so that it can be calculated correctly again.

**Comment by IvanSavenko** [comment]
> If I understood correctly, not all sdl commands are abstracted yet, right? Then this is still the step before?

Yep.
My current goal is to localize all image rendering code to IImage -> SDLImage and Canvas classes and for all input to pass through new classes (see open PR).

If both are implemented, we'll be able to (relatively) easy change rendering method - whether it is render via SDL_Texture (aka hardware acceleration) or whether it is larger target resolution (aka use HD data).

There are still some cases that needs to be dealt with, most notably - some palette animation that H3 has (player-colored UI, terrain animations, selection highlight in battles). Will probably need to look how HD Edition handles those.

Nothing too complex, but needs time to investigate & implement.

**Comment by Laserlicht** [comment]
I was able to create a image extractor for the hd images: https://github.com/Laserlicht/heroes3_image_extractor

And created a comparsion between h3 complete and h3 hd: https://github.com/Laserlicht/heroes3_image_extractor/releases/download/compare/compare.html.zip
I think the most of differences are from the fact that one is roe while the other is complete.

**Comment by Gagert** [comment]
I checked the comparison of h3 complete and h3 hd html-file, and just wow; I had no idea that h3 complete had that many different sprites compared to h3 hd or roe.

There seems to be missing many sprites from h3 hd in the html-file, for instance town buildings, artifacts and the spells from the spell book. All those sprites may have got other filenames h3 complete as well.

The most puzzling part for me is the "colored cardboard cutouts" that takes a lot of space in the h3 complete sprite section; I'm don't even know what purpose those sprites serve in h3 complete.

The battle unit sprites of h3 complete seems to have duplicates or something in the html-fil, it's easy to spot is you compare the h3 complete sprite sheet with the h3 hd sprite sheet, let's say the avwmedx0 battle unit sprites.

If vcmi could seamlessly handle the combination of h3 hd & the low res hd complete 2D sprites, this could be a start of something big. An artist (or artist wannabe) could just take one sprite at the time and HD-ify it, put it in the correct folder and then see the result after starting up a new instance of vcmi.

**Comment by Laserlicht** [comment]
Yes, I was also surprised that some things are different.

Nevertheless, I would find it great in any case, if you could load these sprites and the rest ingame are scaled up for the time being.

When I look at the Heroes artwork and modding world, there are some capable people who could create high-resolution replacements if given the possibility.

Also, it would be a great feature that might be able to entice away some more HoMM3 HD mod users (with the exception of the competitive players).

I think in HD the "colored cardboard cutouts" are recolored via an algorithm.

But of course no guarantee of completeness. I think the extract should fit though. The other already existing converters/scripts I found could not read many graphics, because they lacked the possibility to read multiple DDS-sheets per "object".

**Comment by Gagert** [comment]
I just saw a different project/engine than vcmi called ERA 3 getting a HD Edition mod, which use some (if not all) of the HD Edition assets ([YouTube video here](https://www.youtube.com/watch?v=t2taLE-2rAM)).

I just wanted to mention this, even though this might be old news.

**Comment by misiokles** [comment]
But those assets are downscalled and prepared in photoshop manually to fit h3/era resolutions. This mod can be ported to VCMI by any patient modder anytime. So it's not a subject od this issue.

**Comment by Gagert** [comment]
Any plans of adding sprite upscaling features such as ESRGAN or competing upscaling methods such as the one in BatPio's reply just above to VCMI as well?

I've used xbrz on my 1080p TV (interface scaling 180%) in VCMI 1.6.1, and from a distance xbrz actually looks quite decent. However, I suppose upscaling features such as ESRGAN could make Heroes 3 look even better compared to screen filters such as xbrz.

**Comment by Laserlicht** [comment]
@Gagert 

It is already possible. But not on the fly. It's possible to export all images and upscale the images in a mod by hand. No matter which algorithm is used. See here: https://vcmi.eu/modders/HD_Graphics/

But an really easy way to get most of the graphics in HD is https://store.steampowered.com/app/297000/Heroes_of_Might__Magic_III__HD_Edition (on sale right now)
The textures can be converted (but still experimential): https://github.com/Laserlicht/vcmi_hd_mod
