### ISSUE TITLE
[macOS] no version numbers and no bundle identifier

### ISSUE THREAD

**Issue by core-code** [vcmi/vcmi#1077]
congrats on the 1.0 release!

all macOS apps are supposed to have a bundle identifier and have embedded version numbers. both are missing from VCMI:

<img width="443" alt="Screenshot 2022-10-20 at 15 40 26" src="https://user-images.githubusercontent.com/1261954/196965115-35e16e83-5d6c-4665-a127-423adf295c3b.png">
<img width="251" alt="Screenshot 2022-10-20 at 15 38 43" src="https://user-images.githubusercontent.com/1261954/196965123-988b841b-31b2-4400-a7ee-5305d1b4a04e.png">

**Comment by core-code** [comment]
<img width="443" alt="Screenshot 2022-10-20 at 15 40 26" src="https://user-images.githubusercontent.com/1261954/196965186-268762d0-8fe5-47d2-8085-d4c58f64aa0a.png">

CFBundleIdentifier, CFBundleShortVersionString and CFBundleVersion should be filled out in the Info.plist file. probably the NSHumanReadableCopyright too

CFBundleGetInfoString & CFBundleLongVersionString should be removed, both have been deprecated for more than a decade

**Comment by kambala-decapitator** [comment]
thanks! this has already been partially fixed by #1022

actually, all those fields are not strictly required. Wouldn't hurt to add bundle ID though.

**Comment by core-code** [comment]
awesome thanks
