### ISSUE TITLE
hero graphics are cut near town

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1088]
This is Dungeon, haven't tested other towns
![Screenshot 2022-10-24 at 10 21 58](https://user-images.githubusercontent.com/1557784/197486710-fbb5439c-497c-412a-9b63-2d4a3a981eae.png) ![Screenshot 2022-10-24 at 10 25 57](https://user-images.githubusercontent.com/1557784/197486716-e48b3e7f-70e8-4d56-8d49-32ab42a6606c.png) ![Screenshot 2022-10-24 at 10 26 04](https://user-images.githubusercontent.com/1557784/197486719-33afa52d-dd7a-4319-8ecf-9c8ea7629ef1.png)

**Comment by misiokles** [comment]
I guess heroes "V" masks is under town "B" mask squares.

**Comment by Nordsoft91** [comment]
Observed this issue too
