### ISSUE TITLE
当时用USB声卡的时候, 游戏会卡死; When USB audio device is used as default desktop sound output, game would freeze at start up;

### ISSUE THREAD

**Issue by evolighting** [vcmi/vcmi#1092]
WIndows 11, VMCI version 1.0 (download in release page), MMoH3 from GOG galaxy, leasted version. Original game works fine.
No ohter Error spoted in the terminal when start vcmiclient directly; Switch to DP audio output would fix it.

如果使用 USB声卡作为默认桌面音频, 那么游戏会在打开的时候卡在黑屏, 切换到 DP音频输出, 使用显示器播放声音就能正常游玩.

实际上, 我觉得这个可能是某些底层的库的bug, 因为Firefox浏览器有时候也会遇到类似的卡顿, 不过会很快恢复. 

My USB sound device is Sound Blaster PLAY! 3

**Comment by kambala-decapitator** [comment]
looks it's the same bug report on the forums: https://forum.vcmi.eu/t/game-freeze-at-start-up-when-usb-sound-card-is-used-as-audio-output/5798

**Comment by evolighting** [comment]
I just bought yet another USB sound card, And this one works well with VCMI;

It seems to be that this is a bug about certain device;
