### ISSUE TITLE
Ranger heroes being offered to learn Fire Magic when levelling up

### ISSUE THREAD

**Issue by adorbabble** [vcmi/vcmi#1096]
Playing with VCMI 1.0.0 – no mods except for VCMI extras – and the Rampart, my Ranger hero has already got Fire Magic twice as a choice when levelling up. In my experience, this never happens in the original game because Rangers don’t have any chance of learning that secondary skill : https://heroes.thelazy.net/index.php/Fire_Magic (However, I don’t see these probabilities in the original manual)

**Comment by rilian-la-te** [comment]
Do you got Fire Magic by other means like witch hut? Or it is Basic Fire Magic?

**Comment by kambala-decapitator** [comment]
FizMig has probabilities. Ranger should have 0% indeed.
![Screenshot 2022-11-02 at 12 38 01](https://user-images.githubusercontent.com/1557784/199455871-ad013f1d-0c84-4731-95e0-6593dda9d724.png)

**Comment by adorbabble** [comment]
> Do you got Fire Magic by other means like witch hut? Or it is Basic Fire Magic?

Just basic Fire Magic when having to choose between two skills when you level up
