### ISSUE TITLE
Fail to compile on Pi4

### ISSUE THREAD

**Issue by Exarkuniv** [vcmi/vcmi#1097]
I have a Pi4 running buster 10/RetroPie 
and im working on getting this running on it. 

i follow the WiKi on how to compile from source and it just ends up failing

https://pastebin.com/Tsm05RjA

any pointers on what i need to do to get this going would be great. 
i know at somepoint someone on the RetroPie fourm got it to work, but it was a few years ago. so it was a different verion

i did try building from the master branch and that also fails to compile, it almost makes it but stops at 97%

**Comment by kambala-decapitator** [comment]
configure with `-D ENABLE_TEST=OFF`

**Comment by Exarkuniv** [comment]
@kambala-decapitator thank you 
i will give that a try

**Comment by Exarkuniv** [comment]
i ran this 
```
git clone -b develop --depth 1 --recursive https://github.com/vcmi/vcmi.git
mkdir build && cd build
cmake ../vcmi -D ENABLE_TEST=OFF
cmake --build . -- -j2
``` 
and it still failed
```
/usr/include/arm-linux-gnueabihf/qt5/QtCore/qregularexpression.h:85:14: note:                                             conversion of argument 1 would be ill-formed:
/usr/include/arm-linux-gnueabihf/qt5/QtCore/qregularexpression.h:84:5: note: can                                          didate: ‘QRegularExpression::QRegularExpression()’
     QRegularExpression();
     ^~~~~~~~~~~~~~~~~~
/usr/include/arm-linux-gnueabihf/qt5/QtCore/qregularexpression.h:84:5: note:   c                                          andidate expects 0 arguments, 2 provided
/home/pi/vcmi/launcher/modManager/cmodlistview_moc.cpp:404:15: error: ‘class CMo                                          dFilterModel’ has no member named ‘setFilterRegularExpression’; did you mean ‘se                                          tFilterRegExp’?
  filterModel->setFilterRegularExpression(regExp);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~
               setFilterRegExp
make[2]: *** [launcher/CMakeFiles/vcmilauncher.dir/build.make:174: launcher/CMak                                          eFiles/vcmilauncher.dir/modManager/cmodlistview_moc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:431: launcher/CMakeFiles/vcmilauncher.dir/all                                          ] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 77%] Building CXX object AI/VCAI/CMakeFiles/VCAI.dir/Goals/DigAtTile.cpp.o
[ 78%] Building CXX object AI/VCAI/CMakeFiles/VCAI.dir/Goals/GetArtOfType.cpp.o
[ 78%] Building CXX object AI/VCAI/CMakeFiles/VCAI.dir/Goals/FindObj.cpp.o
[ 78%] Building CXX object AI/VCAI/CMakeFiles/VCAI.dir/Goals/CompleteQuest.cpp.o
[ 78%] Building CXX object AI/VCAI/CMakeFiles/VCAI.dir/main.cpp.o
[ 78%] Building CXX object AI/VCAI/CMakeFiles/VCAI.dir/VCAI.cpp.o
[ 79%] Linking CXX shared library ../../bin/AI/libVCAI.so
[ 79%] Built target VCAI
make: *** [Makefile:152: all] Error 2
```

when i did run 
``cmake ../vcmi -D ENABLE_TEST=OFF``
i saw this 
```
-- Could NOT find TBB (missing: TBB_DIR)
``` 
and 
```
-- Configuring done
CMake Warning (dev) at AI/FuzzyLite/fuzzylite/CMakeLists.txt:175 (add_library):
  Policy CMP0063 is not set: Honor visibility properties for all target
  types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "fl-static" of type "STATIC_LIBRARY" has the following visibility
  properties set for CXX:

    CXX_VISIBILITY_PRESET
    VISIBILITY_INLINES_HIDDEN

  For compatibility CMake is not honoring them for this target.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at AI/FuzzyLite/fuzzylite/CMakeLists.txt:164 (add_library):
  Policy CMP0063 is not set: Honor visibility properties for all target
  types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "fl-obj" of type "OBJECT_LIBRARY" has the following visibility
  properties set for CXX:

    CXX_VISIBILITY_PRESET
    VISIBILITY_INLINES_HIDDEN

  For compatibility CMake is not honoring them for this target.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

not sure if this is also part of the problem

**Comment by rilian-la-te** [comment]
Which Qt Version are you using? You should be at least  5.12.

**Comment by rilian-la-te** [comment]
On buster there is 5.11 only, so you need to update to bullseye (stable). If you want, you can download source qt5 package from  bullseye, and then build it with buster-backports enabled.

**Comment by kambala-decapitator** [comment]
> -- Could NOT find TBB (missing: TBB_DIR)

not sure why cmake configure didn't fail because of this. Anyway, you need TBB if you want to play with Nullkiller AI

the other warning can be ignored

**Comment by kambala-decapitator** [comment]
or just build Qt from source :)

**Comment by Exarkuniv** [comment]
i will see what i can do to get a newer version of QT installed, 
sometimes its above me on figuring out how to install somethings, but im learning 

thanks for helping out so far

**Comment by Exarkuniv** [comment]
is there a commit version that does not use qt 5.12. 
i was able to figure out how to get it to install, but my god did it take forever.

the main reason is that im trying to make a install script so anyone that is running RetroPie can easily install this. but compiling QT5.12 takes a bit too long, lol
(once bullseye is supported i will switch over)

**Comment by kambala-decapitator** [comment]
You can simply create a local patch for vcmi to not use 5.12+ functions.

You don't need to compile full Qt 5, only qtbase is sufficient.

**Comment by Exarkuniv** [comment]
hmm, thank you. i will see what i can figure out with what you said

**Comment by kambala-decapitator** [comment]
I can't say for sure if this combination of options would work for linux / rpi - you should just try :) You can also do `./configure -h` to see all available options.

just make sure that you call this from inside `qtbase` directory, not from the top-level Qt sources (if you downloaded full source package). Btw to make it easier, better call `configure` from a dedicated build directory, for example:

```
cd qtbase
mkdir build
cd build
../configure ...
```

**Comment by Exarkuniv** [comment]
ok thanks

**Comment by Exarkuniv** [comment]
well i cant get it to work, 
i think for now this might just have to wait till bullseye is supported by Retropie. 
i just cant figure out how to get qt5.12 to install right. I think i followed how to do it, 
but when i build vcmi it stops at 37%.

I will do more looking around to figure out what im doing wrong with installing qt5.12.
i would try the whole patch thing, but i dont know where to start with that. 

thank you for all your help with this. 
i dont really want to be much more of a bother

**Comment by Nordsoft91** [comment]
@Exarkuniv , if you disable launcher and editor, qt is not needed at all.
Try to disable them with -DENABLE_LAUNCHER=OFF -DENABLE_EDITOR=OFF

**Comment by rilian-la-te** [comment]
> You can simply create a local patch for vcmi to not use 5.12+ functions.
> 
> You don't need to compile full Qt 5, only qtbase is sufficient. Here's an example (although it's for iOS): https://github.com/vcmi/vcmi-ios-deps/blob/main/deps/qt.sh Check the `qtConfigure` variable - it's the Qt configure call.

Then it disables Qt6 compatibility for anything new.

**Comment by kambala-decapitator** [comment]
> Then it disables Qt6 compatibility for anything new.

"local patch" means that OP will apply it manually, it won't be submitted as PR

**Comment by Exarkuniv** [comment]
so i ran it with this 
``cmake ../vcmi -DENABLE_LAUNCHER=OFF -DENABLE_EDITOR=OFF -D ENABLE_TEST=OFF`` 
and this time it did go finish and i see
```
vcmiserver
vcmiclient
libvcmi.so
libminizip.so
```
but in the read me on how to compile it say i should also have ``vcmilauncher `` and 4.so files.
any thoughts on what i missed

**Comment by kambala-decapitator** [comment]
you have no vcmilauncher because you disabled building the launcher with -DENABLE_LAUNCHER=OFF

there should also be `AI` directory with so files somewhere

**Comment by Exarkuniv** [comment]
ahh ok, 
well since i need ``vcmilauncher`` to play, having it off, does not help. and when i have it on it fails, 
so looks like my options are to get the right version of QT installed, or just wait for bullseye to be support from RetroPie

**Comment by kambala-decapitator** [comment]
you can override that via `XDG_DATA_HOME` environment variable, expected location would be `$XDG_DATA_HOME/vcmi`

or just make a symlink.

see here for locations that are searched: https://github.com/vcmi/vcmi/blob/55914290ca481f1483b2c0d81ed01f6c7bd43c10/lib/VCMIDirs.cpp#L538-L548

**Comment by Exarkuniv** [comment]
cool. 
think a symlink is the way to go. 
no real need to make it more complicated then it needs to be.
thanks to all for all your help with this.
