### ISSUE TITLE
NKAI assertion

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1098]
const CGHeroInstance * HeroPtr::get(bool doWeExpectNull) const (AIUtility.cpp)
assert(obj);

Unstable reproducing, what I did (all steps ion same turn):
1. Kill one of AI heros
2. Remove majority of your amy so hero should be weak
3. Stand close to strong AI hero so it should attack next turn

**Comment by kambala-decapitator** [comment]
same assert as in #1330, will close this one as duplicate
