### ISSUE TITLE
Library of enlightenment suggests same options

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1101]
Visit library of enlightenment by hero with diplomacy skill. Hero level should allow visit.
Expected result: +2 to each primary skill
Actual result: game suggests to select one of options which are the same

<img width="476" alt="Снимок экрана 2022-11-03 в 20 20 07" src="https://user-images.githubusercontent.com/9308612/199781268-8fd1703f-0f86-40e8-9694-3cdbcd388119.png">

**Comment by nullkiller** [comment]
library of enlightenment should give +2 to everything without choice. And I checked it works on my local build. Such case might be due to some mod probably.

**Comment by Nordsoft91** [comment]
Reproduced without mods. Prerequisite is to have diplomacy skill. Save is attached

**Comment by IvanSavenko** [comment]
I think you're getting a choice between 2 to all primary skills, 2 to all primary skills, 2 to all primary skills and 2 to all primary skills.

Will fix.
