### ISSUE TITLE
NKAI - Wrong priorities - They interfere with bringing the game to its logical conclusion.

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#1106]
Наверное эта игра могла бы продолжаться вечно. Коричневый имея под контролем почти всю карту, только и делает то что посещает золотые мельницы. Если бы он так посещал палатки, то смог бы уже пойти убить фиолетового, который сидит за пограничными воротами.
Похоже что кроме мельниц и камней опыта его особо больше ничего не интересует. А ведь можно пойти через водоворот и убить зеленого. Городов у него больше, нужно собрать армию и покончить с ним.
Кстати зеленый то и делает что из хода в ход открывает ящик пандоры и погибает. Но это проблема известная и старая. Можно ли как-то промаркировать такие места, как события с охраной или ящики пандоры? 

Очевидно что надо смещать акценты на освоение новых территорий и пробитие охран. Особенно палаток. 
Мельницы и повышалки это хорошо, но у них слишком высокий приоритет.

This game could probably go on forever. Brown, having almost the entire map under control, does nothing but visit gold mills. If he visited the tents like that, he could already go and kill the purple one, who is sitting outside the border gate.
It seems that apart from mills and stones of experience, he is not particularly interested in anything else. But you can go through the whirlpool and kill the green. He has more cities, gather an army and put an end to him.
By the way, green then does that from move to move opens Pandora's box and dies. But this is a well-known and old problem. Is it possible to somehow mark places such as security events or pandora's boxes?

It is obvious that it is necessary to shift the emphasis on the development of new territories and breaking through the guards. Especially the tents.
mills and boosters are good, but they have too high a priority.

**Comment by Povelitelh3** [comment]
[NKAI.zip](https://github.com/vcmi/vcmi/files/9938757/NKAI.zip)

**Comment by nullkiller** [comment]
This thing is old and mostly addressed
