### ISSUE TITLE
Cannot hire more than 2 heroes

### ISSUE THREAD

**Issue by janostik** [vcmi/vcmi#1107]
When trying to hire more than 2 heroes, game tells me that I already have 8 and cannot hire more.

**Comment by misiokles** [comment]
Disable "AI speed up - limit on map heroes" submod  in Resourcefull AI mod (or edit number of players manually) in
Resourceful AI/ModsAI speed up - limit on map heroes/content/config/defaultMods.json

```
	"hardcodedFeatures" :
	{

		"MAX_HEROES_AVAILABLE_PER_PLAYER" : 2,
		"MAX_HEROES_ON_MAP_PER_PLAYER" : 2,

	}

```

**Comment by nullkiller** [comment]
We should not enable Resourcefull AI by default so. Could we move it out of vcmi extras?

**Comment by Nordsoft91** [comment]
Agree, done

**Comment by misiokles** [comment]
For me, mod should be in vcmi extras but disabled by default` "keepDisabled" : "true",`
