### ISSUE TITLE
VCMI H3 original archives extractor

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1118]
Original H3 files are grouped into archives. They should be extracted to appropriate folders and consumed from there.

_Images will be extracted to separate PNGs
Sprites will remain in .defs
Resource names will not change_

- [x] Run Archives Extractor code from within VCMI_MapEditor as command line options (Intermediary step until VCMI installer)
- [x] Extract all resources to separate folders. Images, Misc, Sound, Sprites, Video
- [x] Split mixed up resources like: CPRSMALL, FLAGPORT, ITPA, ITPT, TWCRPORT, UN32, UN44, into separate files.
- [x] PCX images will be converted to PNG
- [ ] Split other .defs _(Images not multiple frame Sprites)_ into separate image files. (EG: spell icons, artifacts)

_Once everything is up and running, the Archives Extractor functionality will be incorporated into VCMI Installer_

:: ORIGINAL ::
```
<USER_DATA_PATH>/Data/
    H3ab_ahd.snd
    H3ab_ahd.vid
    H3ab_bmp.lod
    H3ab_spr.lod
    H3bitmap.lod
    H3sprite.lod
    Heroes3.snd
    VIDEO.VID
```

:: EXTRACTED ::
```
<USER_DATA_PATH>/extracted/
    Images
    Misc
    Sound
    Sprites
    Video
    Sprites
        \CPRSMALL
        \FLAGPORT
        \ITPA
        \ITPT
        \TWCRPORT
        \UN32
        \UN44
```

_This is an intermediary step for having a full SoD mod. In the final form all extracted data will be moved to SoD mod folder._

Drawbacks of original approach with archives in DATA/:
- Loading only a subset of resources via mods is not possible, 
- modding is harder than it needs to be, because everything is clumped together. 
- Resources for different factions are clumped together in same file.

Drawbacks of this approach:
- Mods will not be 1 to 1 compatible with other Heroes III distributions. (Different file structure)

**Comment by krs0** [comment]
First working draft in #1119

**Comment by krs0** [comment]
After consulting with Nordsoft, I have moved the functionality to MapEditor. (Perhaps final place is its own project dependent on Animation or only QImage, but that beats me how to do it).
I've also changed saving format for icons to PNG (as per Ivan's suggestion)

**Comment by krs0** [comment]
FLAGPORT PNG;s show some artefacts... will investigate.

![FLAGPORT_0_13](https://user-images.githubusercontent.com/15194321/201787578-7860b582-6a26-4f81-b044-9d8cb46c556c.png)
![FLAGPORT_0_68](https://user-images.githubusercontent.com/15194321/201787581-80888ca3-9b55-430d-99ec-e70bfe80e9cf.png)

**Comment by krs0** [comment]
Ivan helped and now FLAGPORT exports are ok.

**Comment by krs0** [comment]
Next step would be to convert all single image .pcx to .png
Unfortunately same offsetting errors appear on save (see pics) :(. Am I saving the right way?
I want to go through all .pcx in the extracted/Images folder, loadBitmap(pcx_file) and then QImage->Save(filename, "PNG")
```
// converts all pcx files from /Images into PNG
void convertPcxToPng()
{
	bfs::path imagesPath = VCMIDirs::get().userCachePath() / "extracted" / "Images";
	bfs::directory_iterator end_iter;

	for ( bfs::directory_iterator dir_itr(imagesPath); dir_itr != end_iter; ++dir_itr )
	{
		try
		{
			if (!bfs::is_regular_file(dir_itr->status()))
				return;

			std::string filePath = dir_itr->path().string();
			std::string fileStem = dir_itr->path().stem().string();
			std::string filename = dir_itr->path().filename().string();
			filename = boost::locale::to_lower(filename);

			if(filename.find(".pcx") != std::string::npos)
			{
				QImage img = BitmapHandler::loadBitmap(filename);
				bfs::path pngFilePath = imagesPath / (fileStem + ".png");
				img.save(QStringFromPath(pngFilePath), "PNG");

				if (delete_source_files)
					bfs::remove(filePath);
			}
		}
		catch ( const std::exception & ex )
		{
			logGlobal->info(dir_itr->path().filename().string() + " " + ex.what() + "\n");
		}
	}
}
```
![ADOPBPNL](https://user-images.githubusercontent.com/15194321/202582376-9fe8b804-368f-415e-a877-ed373fc26315.png)
![ADOPFLGB](https://user-images.githubusercontent.com/15194321/202582436-0a612af0-bb30-479b-b668-a2cf466b2c5c.png)

**Comment by krs0** [comment]
Waiting for https://github.com/vcmi/vcmi/pull/1151 to be merged / closed.

**Comment by krs0** [comment]
All done. No more image artefacts!
The Extract Archives functionality is enabled by command line options in map editor (for now).
VCMI_mapeditor.exe [map_path] -e -s -c -d

	// command line options
	QString mapFilePath;			// FilePath to the H3 or VCMI map to open
	bool extractArchives = false;	// extract original H3 archives into a separate folder
	bool splitDefs = false;			// splits TwCrPort, CPRSMALL, FlagPort, ITPA, ITPt, Un32 and Un44 into individual PNG's
	bool convertPcxToPng = false;	// converts single Images (found in Images folder) from .pcx to png.
	bool deleteOriginals = false;	// delete original files, for the ones splitted / converted.

**Comment by Nordsoft91** [comment]
It doesn't work well, have following result:
```
Exported 151 frames to /Users/admin/Library/Application Support/vcmi/extracted/SPRITES/TWCRPORT
Exported 151 frames to /Users/admin/Library/Application Support/vcmi/extracted/SPRITES/CPRSMALL
Exported 88 frames to /Users/admin/Library/Application Support/vcmi/extracted/SPRITES/FLAGPORT
Exported 39 frames to /Users/admin/Library/Application Support/vcmi/extracted/SPRITES/ITPA
Exported 36 frames to /Users/admin/Library/Application Support/vcmi/extracted/SPRITES/ITPT
Exported 156 frames to /Users/admin/Library/Application Support/vcmi/extracted/SPRITES/UN32
Exported 156 frames to /Users/admin/Library/Application Support/vcmi/extracted/SPRITES/UN44
NiD_EnRe.pcx std::bad_cast

TZELSilo.pcx std::bad_cast

SgFrWa63.pcx std::bad_cast

NiB_CoVi.pcx std::bad_cast

actually a very long list of same errors
```

**Comment by Nordsoft91** [comment]
most of sounds were extracted without extension (for example ABvoAB1.)

**Comment by krs0** [comment]
Only several defs are needed to be converted into pngs (see logs in a previous comment). Others (multiple frame ones) are still defs"

```
static void splitDefFiles(bool deleteOriginals);
	// splits def files (TwCrPort, CPRSMALL, FlagPort, ITPA, ITPt, Un32 and Un44) so that faction resources are independent
	// (town creature portraits, hero army creature portraits, adventure map dwellings, small town icons, big town icons, 
	// hero speciality small icons, hero speciality large icons)
```

**Comment by krs0** [comment]
"- all text files contain only zeros, same for campaigns .h3c"

This is an issue on my side as well :(. Will try to see what is wrong there. The names are correct and sizes differ but the contents are NULL.

**Comment by krs0** [comment]
> * all text files contain only zeros, same for campaigns .h3c

This bug was introduces with the modification of:
` void CArchiveLoader::extractToFolder(const std::string& outputSubFolder, const std::string& mountPoint, ArchiveEntry entry)`
to internally make use of:
`void CArchiveLoader::extractToFolder(const std::string & outputSubFolder, CInputStream & fileStream, ArchiveEntry entry)`

Will revert that change.

**Comment by krs0** [comment]
"pcx were not converted (I used -c flag)"

This should be solved by: PCX file conversion in Resource Extractor throws exception on IOS (boost::locale stuff) #1205
