### ISSUE TITLE
Stack retaliate on attack after blinding

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1139]
1. Attack some stack with unicorns
2. Unicorns should cast blind on target
3. Stack retaliates on attack but shouldn't

**Comment by kambala-decapitator** [comment]
I don't think I noticed this🤔

was it a random stack, not someone like Royal Gryphons?

**Comment by Nordsoft91** [comment]
Don't remember exactly, but some of shooters, perhaps litches

**Comment by Alucard648** [comment]
Same issue with Scorpicores and his paralyzing attack.

**Comment by Povelitelh3** [comment]
And after casting expert blindness from the book, the unit should not respond to the attack
