### ISSUE TITLE
2 hex units are sometimes frozen during combat

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#1144]
[battle.zip](https://github.com/vcmi/vcmi/files/10011534/battle.zip)
https://youtu.be/0t98rExJlSg
Just look at the video. Either this is an interaction with the terrain, or it just happened
![2hexUnit](https://user-images.githubusercontent.com/36762538/201892860-2c0d36c0-ad26-4533-8a1e-4d4769fb534c.png)

**Comment by Povelitelh3** [comment]
probably related https://bugs.vcmi.eu/view.php?id=1735

**Comment by nullkiller** [comment]
Looks quite old. Hardly possible to do anything now. Most likely is fixed in latest builds.
