### ISSUE TITLE
iPad, iOS 15.6 - game crashes on second campaign mission

### ISSUE THREAD

**Issue by staafl** [vcmi/vcmi#1147]
So far it seems to be the case for every campaign. The first mission in the campaign works, then you win, get to the campaign map where you choose your starting bonus for the second mission, then you watch the video before the mission, then "BAM", the game crashes.

Attaching logs:

[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/10036304/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/10036305/VCMI_Launcher_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/10036306/VCMI_Server_log.txt)

I'm using the GOG version data files (French resources). iPad Pro 12.9, 3rd generation, MTFL2HC/A

Using a build of the app with the iOS App Signer web service, from the 1st of October, attaching my signed IPA:

https://drive.google.com/file/d/1OKl_Um12wtaAtsTTX0I21q2EdWUEr41E/view?usp=share_link

If the error isn't obvious from the logs and you'd like me to check if it reproduces a newer build or signed with a different tool, I can do that.

Thanks for your help!

**Comment by Nordsoft91** [comment]
Duplicates https://github.com/vcmi/vcmi/issues/919 and https://bugs.vcmi.eu/view.php?id=3245
