### ISSUE TITLE
NKAI is stuck doing nothing

### ISSUE THREAD

**Issue by val-gaav** [vcmi/vcmi#1150]
In this game AI got stuck probably for many weeks.  It doesn't move heroes, doesn't buy creatures in town. 

Save and logs are included. Cove town was taken from AI, and even though AI should fully know that it should buy more creatures to defend as my hero has landed on AI island,  still plenty of creatures in town are available.  Resourceful mod is on so AI has plenty of resources and gold to do so. 

Furthermore AI heroes are stuck on one island doing nothing. 
[vcmi_nkai_stuck.zip](https://github.com/vcmi/vcmi/files/10040045/vcmi_nkai_stuck.zip)
[Saves_2.zip](https://github.com/vcmi/vcmi/files/10040053/Saves_2.zip)

This happened in quick_combat branch (my own debug linux build) not in main develop, but I think changes made for quick combat should most likely have zero impact for AI .

**Comment by Povelitelh3** [comment]
Most likely related to https://github.com/vcmi/vcmi/issues/1102

**Comment by val-gaav** [comment]
Thanks I will try to compile the fix and check after the weekend. Certainly the fix for 1102 was not included in my build.

**Comment by val-gaav** [comment]
Well, I cannot check as it seems saves are not compatible between latest develop and quick combat branch and I am not even seeing that save file on the list to load. If I ever get to have this error again I will report it.

**Comment by Nordsoft91** [comment]
@val-gaav you need to open this save from beta branch, not develop. For me they don't work for some other reason (maybe you used some mods)

**Comment by nullkiller** [comment]
No way to test this save unfortunately so treat it as fixed according to #1102
