### ISSUE TITLE
linux build fails due to macro of major/minor/version

### ISSUE THREAD

**Issue by nickhuang99** [vcmi/vcmi#1165]
In Linux(ubuntu-18.04/gcc-7.5), build with error
/home/nick/Downloads/vcmi/vcmi-ssh/lib/mapObjects/../CModHandler.h:190:35: error: class ‘CModInfo::Version’ does not have any field named ‘gnu_dev_major’
   Version(int mj, int mi, int p): major(mj), minor(mi), patch(p) {}
                                   ^
/home/nick/Downloads/vcmi/vcmi-ssh/lib/mapObjects/../CModHandler.h:190:46: error: class ‘CModInfo::Version’ does not have any field named ‘gnu_dev_minor’
   Version(int mj, int mi, int p): major(mj), minor(mi), patch(p) {}

This is because GNU marco conflict:
 warning: In the GNU C Library, "major" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "major", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "major", you should undefine it after including <sys/types.h>.

This fix is simple to undef these three macro

diff --git a/lib/CModHandler.h b/lib/CModHandler.h
index aee7704..9974356 100644
--- a/lib/CModHandler.h
+++ b/lib/CModHandler.h
@@ -14,6 +14,14 @@
 #include "VCMI_Lib.h"
 #include "JsonNode.h"
 
+#ifdef  major
+#undef major
+#endif
+
+#ifdef minor
+#undef minor
+#endif
+
 VCMI_LIB_NAMESPACE_BEGIN
 
 class CModHandler;

**Comment by IvanSavenko** [comment]
Personally I'd call this compiler bug (well, C library bug but whatever). 
glibc maintainters agree that this is a bug:
https://sourceware.org/bugzilla/show_bug.cgi?id=19239
It also has been fixed 4 years ago and Ubuntu 18.04 is approaching end-of-support...

**Comment by nickhuang99** [comment]
Right! After I switch ubuntu 20.04, building goes correctly.
Please close this ticket and thanks for prompt response.

Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by danfe** [comment]
> Personally I'd call this compiler bug [...] glibc maintainers agree that this is a bug

Apparently it depends on the particular standard library implementation: in commit de33eb44 these macros had been guarded with `#ifdef __UCLIBC__`.  FreeBSD also suffers from this:
```
error: member initializer '__major' does not name a non-static data member or base class
        CModVersion(int mj, int mi, int p): major(mj), minor(mi), patch(p) {}
                                            ^~~~~~~~~
/usr/include/sys/types.h:389:18: note: expanded from macro 'major'
#define major(d)        __major(d)
                        ^~~~~~~~~~
```
I'm not proposing the patch right now because these files had been moved around recently and I'd rather wait a bit until the dust settles; this comment is more of a reminder to myself.

**Comment by danfe** [comment]
Okay, now that version 1.4.0 is out I can confirm that the following patch fixes the build on FreeBSD, please commit:
```patch
--- lib/modding/CModVersion.h.orig
+++ lib/modding/CModVersion.h
@@ -10,7 +10,7 @@
 
 #pragma once
 
-#ifdef __UCLIBC__
+#if defined(__UCLIBC__) || defined(__FreeBSD__)
 #undef major
 #undef minor
 #undef patch
```

**Comment by kambala-decapitator** [comment]
@danfe please create pull request

**Comment by IvanSavenko** [comment]
Will make commit with this change
