### ISSUE TITLE
[MSVC] Client build fails beause of AI/tbb12.dll instead of AI/tbb.dll

### ISSUE THREAD

**Issue by KlbmnbddAtGH** [vcmi/vcmi#1166]
I built all dependencies with vcpkg with VS 2022 Community (x64-windows-v143 on Windows 10 Pro) and exported them into an archive (release versions of the libraries only). I followed the instructions to build the project files from the current git sources for "Visual Studio 17 2022". The build inside Visual Studio failed because AI/tbb.dll was not found. tbb12.dll was copied into the folder AI instead of tbb.dll.

**Comment by nullkiller** [comment]
No guarantee that freshly built vcpkg libs will work. We provide our own prebuilt, you can try them. This is the easiest way to start with.

**Comment by nullkiller** [comment]
Also in case there is dll name mismatch should not it be runtime error?

**Comment by nullkiller** [comment]
And finally VS puts tbb.dll to AI folder while game will try to lad it from root folder where vcmiclient.exe resides. You can try to copy/move all non AI dlls from AI folder to the parent one
