### ISSUE TITLE
Authenticity campaign bugs with the original

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#1167]
I tested PR 1163 and found the following:

- [ ] Campaign Sod Birth of the Barbarian 3 mission Difficult start - the hero Yogi appears WITHOUT an alliance of angels.
- [x] Ascension of the Necromancer - Finneas Wilmar - (mission 3) - Finneas is given by the first level, in the original 7th.
- [x] Ascension of the Necromancer - Duke Alyaris - artifacts did not pass (components of the cloak of the king of evil spirits and the armor of the damned)
- [x] Unholy Alliance - the final peace - Jam and Clancy from dirty slots, but the first level. Should be on the 25th. (201000 experience)
- [x] Unholy alliance - invasion - there was no undead king's cloak and armor of the damned. Here is a clarification: in the previous mission, the original had prefabricated artifacts and sets from which it was possible to assemble another pair of prefabricated artifacts.
- [ ] Return to Brakada - there was a glitch with the text in the last mission
- [x] A hero's spellbook is also not transferred if that hero is initially without a spellbook. But spells appear if you buy it again in the castle

Fully tested SOD campaign.

***

Кампания Сод Рождение Варвара 3 миссия Трудное начало - герой Йог появляется БЕЗ альянса ангелов.

Восхождение некроманта - Финнеас Вилмар - (миссия3) - Финнеас дается первым уровнем,  в оригинале 7й.

Восхождение некроманта -- Дюк Алярис - не перешли артефакты (составные части плаща короля нечисти и доспех проклятых)

Нечистый Альянс - финальный мир - Джем и Кланси из засраными слотами, но первого уровня. Должны быть 25го. (201000 опыта)

Нечистый альянс - нашествие -  не было плаща короля нежити и доспех проклятого. Тут уточнение: в предыдущей миссии в оригинале были сборные артефакты и комплекты из которых можно было собрать еще одну пару сборных артефактов.

Возвращение в Бракаду - был глюк с текстом в последней миссии

Книга заклинаний у героя так же не переносится, если этот герой изначально без книги. Но заклинания появляются если ее заново купишь в замке

Протестирована полностью СОД кампания.

**Comment by Alucard648** [comment]
Неплохо бы потестить ещё кампании Возрождения Эрафии и Клинка Армагеддона.

**Comment by IvanSavenko** [comment]
> Campaign Sod Birth of the Barbarian 3 mission Difficult start - the hero Yogi appears WITHOUT an alliance of angels

Not a bug? Starting from this mission, Yog is supposed to collect Angelic Alliance pieces, He does not have it neither at the start of this mission, nor in the end of this or any other mission in this campaign

> Return to Brakada - there was a glitch with the text in the last mission

Unable to reproduce. Either needs more information or already resolved.
