### ISSUE TITLE
Confusing error messages in console.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#1174]
![image](https://user-images.githubusercontent.com/29593042/204379498-0753c64d-5157-4388-8cf1-a3ab85adc04c.png)
There are mods thar add variant graphics to the existing objects. Console gives such false errors, because those new graphics are placed on the maps correctly.
Problem is that modders can't observe in console real errors (typos, missing graphics, wrong filenames) during making mods.

**Comment by IvanSavenko** [comment]
Hi. Can you explain in more details at to what's wrong here? Example of such mod?

Does vcmi tests wrong file path for existence? 
Or does vcmi generates error for a file that should be optional?
Or is this because of missing .msk file?

**Comment by IvanSavenko** [comment]
Ah, bug confirmed.
Since you're editing object from "core" vcmi incorrectly checks for these files in core filesystem, meaning - only H3 files.
So yeah, there is nothing wrong in the mod, will look into fixing validation
