### ISSUE TITLE
VCMI Installer

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1188]
Create a stand alone installer project that will perform all actions necessary for VCMI to run on a machine.

Once SoD Mod is in place we will need an installer to Copy, Extract and Relocate original resources to their proper location in SoD MoD.

_Maybe other things should be handled by installer, will detail them here when discovered._

_Since it will need to Extract and Relocate the original resources the installer will need to make use of parts of VCMI libs, CArchiveLoader for loading and extracting the archives, CAnimation for splitting defs. A substantial refactoring will be needed in this area._

_Installer will probably be a Qt GUI._

**Comment by kambala-decapitator** [comment]
> Installer will probably be a Qt GUI.

if so, you could try using Qt Installer Framework

**Comment by krs0** [comment]
This idea is abandoned :(. SoD as mod not wanted in VCMI.

**Comment by kambala-decapitator** [comment]
> This idea is abandoned :(. SoD as mod not wanted in VCMI.

let's close then?
