### ISSUE TITLE
Visiting hero incorrect placement

### ISSUE THREAD

**Issue by nullkiller** [vcmi/vcmi#1192]
If a map is configured to have visiting hero in town it is incorrectly placed 1 tile to the right. This even can be outside of map
[Dragon's Nest (CHI).zip](https://github.com/vcmi/vcmi/files/10148155/Dragon.s.Nest.CHI.zip)

**Comment by nullkiller** [comment]
Still crashing unfortunately

**Comment by nullkiller** [comment]
There is a town with entrance near right map border. Hero spawns 1 tile to the right - not in the map

**Comment by IvanSavenko** [comment]
Confirmed, looking into it
