### ISSUE TITLE
Tower icons are not overwritten

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1199]
vcmi-extras contains mod with tower icons but tower icons are default in game 
https://github.com/vcmi-mods/vcmi-extras
![image](https://user-images.githubusercontent.com/9308612/205664176-f823e3ec-613b-4537-956a-64dd0fff5eb3.jpeg)

**Comment by misiokles** [comment]
I guess Arrow Tower mod should be changed to suit new format. I'll look into it.

**Comment by misiokles** [comment]
Mod Arrow Tower Icons was updated to the new format (in beta repo). But still small icon is shown.
![image](https://user-images.githubusercontent.com/29593042/205993044-746423b7-ca94-4759-942a-e01162e5cc47.png)

**Comment by IvanSavenko** [comment]
Huh, wasn't aware of that icon. 
Assuming that small battle queue (in 800x600 resolution) works then this is not issue with mod, but with engine. 

I don't think that we should add towers to casualties - H3 does not and it does not makes much sense - towers will respawn anyway. (same can be said for the catapult though...)

Should I add proper icon there or should I remove towers from casualties?

**Comment by misiokles** [comment]
You can remove it without hesitation!
