### ISSUE TITLE
Hero is standing at inaccessible tile

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1210]
Use flight and attack monster from the obstacle
After combat hero is still standing at obstacle
<img width="296" alt="Снимок экрана 2022-12-06 в 16 49 26" src="https://user-images.githubusercontent.com/9308612/205917513-5e874afe-503e-4cd5-b1c7-abc7f65d0bfa.png">

**Comment by IvanSavenko** [comment]
What was behavior in H3? I think that H3 does not allows hero to attack from such tile - you need to find tile to land on first.

**Comment by dydzio0614** [comment]
yep, this is probably pathfinder bug
