### ISSUE TITLE
assertion in mod loading

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1212]
1. Enable mod attached (or activate from launcher `Andruids Expansion Mods / Power bond` )
[powerbond.zip](https://github.com/vcmi/vcmi/files/10167065/powerbond.zip)
2. Run game
3. Observe assertion from CModHandler.cpp 322 `assert(errorsFound == false);`
From logs:
```
0m[1;31mUnknown identifier!
[0m[1;31mRequest for skill.powerbond from mod andruids-expansion.powerbond
```
As I understand, it's because of mismatch between localScope and RemoteScope
```
localScope	std::string	"andruids-expansion.powerbond"
remoteScope	std::string	"andruids expansion.powerbond"
```

Probably related to this but not sure https://github.com/vcmi/vcmi/pull/1177

**Comment by IvanSavenko** [comment]
Bug with mod unless I am missing something.
Base mod is named "andruids-expansion", while mod is trying to use object from non-existing mod "andruids expansion".

If this worked before then this was a bug

**Comment by IvanSavenko** [comment]
Can be fixed either by replacing that space with '-' or by using only ID in that place, e.g:
a) "andruids expansion.powerbond" -> "andruids-expansion.powerbond"
b) "andruids expansion.powerbond" -> "powerbond"

Mods can access their own content and their own dependencies without explicitly specifying mod name

**Comment by misiokles** [comment]
Should be evverything ok in mod folder names right-now.

**Comment by Nordsoft91** [comment]
Fixed by mod update
