### ISSUE TITLE
[1.0.0] libvcmi.so not found

### ISSUE THREAD

**Issue by farmboy0** [vcmi/vcmi#1216]
When I build and install VCMI 1.0.0 libvcmi.so ends up as /usr/lib64/vcmi/libvcmi.so. Of course this path is not a standard library search path so the lib isnt found when I run VCMI.

System: Gentoo

This seems to come from https://github.com/vcmi/vcmi/blob/cedc9a92ede66b3f9fff079022ea287a012330a5/CMakeLists.txt#L322

**Comment by IvanSavenko** [comment]
Hi. can you try re-running cmake with additional key:
`cmake -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON ../vcmi`
And then rebuild & reinstall.
This should add correct library search path to vcmi binaries, fixing this issue.

Not sure why we don't have this by default...

**Comment by IvanSavenko** [comment]
UPDATE:
correct cmake command for workaround will be
`cmake -DCMAKE_INSTALL_RPATH=/usr/lib64/vcmi ../vcmi`

Will be fixed in vcmi 1.1

**Comment by farmboy0** [comment]
Setting CMAKE_INSTALL_RPATH to "${CMAKE_INSTALL_PREFIX}/${LIB_DIR}" works around the problem.
I uses this patch to CMakeLists.txt:

diff --git a/CMakeLists.txt b/CMakeLists.txt
index c1c5a963f..bb38de414 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -275,6 +275,7 @@ else()
 		if(NOT DATA_DIR)
 			set(DATA_DIR "share/vcmi" CACHE STRING "Where to install data files")
 		endif()
+		set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/${LIB_DIR}")
 	endif()
 
 	# following constants only used for platforms using XDG (Linux, BSD, etc)

**Comment by IvanSavenko** [comment]
Yeah.
Thanks for confirmation, identical change is already planned for 1.1 release.
