### ISSUE TITLE
[1.0] undefined symbol when starting campaign

### ISSUE THREAD

**Issue by farmboy0** [vcmi/vcmi#1224]
When I start a campaign with New Game -> Campaign -> Restoration of Erathia -> Dungeons and Devils vcmi crashes with the following error:
/usr/bin/vcmiclient: symbol lookup error: /usr/lib64/vcmi/AI/libVCAI.so: undefined symbol: _ZN2fl13InputVariableC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEdd

System: Gentoo
Build parameters:
	local mycmakeargs=(
		-DENABLE_ERM=ON
		-DENABLE_LAUNCHER=ON
		-DENABLE_PCH=ON
		-DENABLE_MONOLITHIC_INSTALL=OFF
		-DENABLE_TEST=OFF
		-DFORCE_BUNDLED_FL=OFF
	)

**Comment by rilian-la-te** [comment]
What libstdc++ or libc++ do you have? What compiler are you using as system one? What libc and binutils? 

Did you tried to rebuild world via emerge?

**Comment by farmboy0** [comment]
GCC 12.2.1_p20221203
Binutils 2.38
Glibc 2.36
libc++ comes from GGC

**Comment by rilian-la-te** [comment]
So, this is libstdc++ thing. What version of libstdc++ do you have?

**Comment by farmboy0** [comment]
libstdc++.so.6.0.30

**Comment by IvanSavenko** [comment]
> -DFORCE_BUNDLED_FL=OFF
- You do have fuzzylite library installed, correct?
- Can you check libfuzzylite.so location & version?
- Are you building vcmi 1.0 release or current beta?

**Comment by farmboy0** [comment]
I use fuzzylite release 6.0
Location is /usr/lib64/libfuzzylite.so.6.0
I am building the released vcmi 1.0 tarball.

**Comment by rilian-la-te** [comment]
@farmboy0 is fuzzylite rebuild with new libstdc++?

**Comment by IvanSavenko** [comment]
Can you dump this data from libraries and post commands output here?
```
ldd /usr/lib64/vcmi/AI/libVCAI.so
objdump -T /usr/lib64/libfuzzylite.so.6.0 | grep InputVariable
objdump -T /usr/lib64/vcmi/AI/libVCAI.so | grep InputVariable
```

**Comment by farmboy0** [comment]
@rilian-la-te Itwas never built with anything else.

**Comment by farmboy0** [comment]
ldd /usr/lib64/vcmi/AI/libVCAI.so
        linux-vdso.so.1 (0x00007ffd911b2000)
        libvcmi.so => /usr/lib64/vcmi/libvcmi.so (0x00007f19aba00000)
        libfuzzylite.so.6.0 => /usr/lib64/libfuzzylite.so.6.0 (0x00007f19ab855000)
        libboost_thread.so.1.80.0 => /usr/lib64/libboost_thread.so.1.80.0 (0x00007f19ac4ff000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6 (0x00007f19ab600000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f19ab524000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/12/libgcc_s.so.1 (0x00007f19ab835000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f19ab34c000)
        libminizip.so.1 => /usr/lib64/libminizip.so.1 (0x00007f19ab828000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f19ab332000)
        libboost_filesystem.so.1.80.0 => /usr/lib64/libboost_filesystem.so.1.80.0 (0x00007f19ab30f000)
        libboost_locale.so.1.80.0 => /usr/lib64/libboost_locale.so.1.80.0 (0x00007f19ab244000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f19ac6ed000)
        libboost_atomic.so.1.80.0 => /usr/lib64/libboost_atomic.so.1.80.0 (0x00007f19ab23a000)
        libboost_chrono.so.1.80.0 => /usr/lib64/libboost_chrono.so.1.80.0 (0x00007f19ab22f000)
        libicudata.so.72 => /usr/lib64/libicudata.so.72 (0x00007f19a9400000)
        libicui18n.so.72 => /usr/lib64/libicui18n.so.72 (0x00007f19a9000000)
        libicuuc.so.72 => /usr/lib64/libicuuc.so.72 (0x00007f19a8c00000)

**Comment by farmboy0** [comment]
objdump -T /usr/lib64/libfuzzylite.so.6.0 | grep InputVariable
00000000000738e0  w   DO .rodata        0000000000000015  Base        _ZTSN2fl13InputVariableE
0000000000122d10 g    DF .text  0000000000000aed  Base        _ZNK2fl12JavaExporter8toStringB5cxx11EPKNS_13InputVariableEPKNS_6EngineE
000000000010c4f0 g    DF .text  0000000000000300  Base        _ZNK2fl11FldExporter8toStringB5cxx11EPNS_6EngineEiNS0_13ScopeOfValuesERKSt6vectorIPNS_13InputVariableESaIS6_EE
00000000000b0de0 g    DF .text  0000000000000049  Base        _ZNK2fl6Engine22numberOfInputVariablesEv
0000000000168ef0 g    DF .text  0000000000000041  Base        _ZNK2fl13InputVariable5cloneEv
0000000000169020 g    DF .text  0000000000000104  Base        _ZNK2fl13InputVariable8toStringB5cxx11Ev
0000000000112450 g    DF .text  0000000000000133  Base        _ZNK2fl11FllExporter8toStringB5cxx11ERKSt6vectorIPNS_13InputVariableESaIS3_EE
0000000000168e40 g    DF .text  0000000000000056  Base        _ZNK2fl13InputVariable15fuzzyInputValueB5cxx11Ev
00000000000b85c0 g    DF .text  0000000000000238  Base        _ZN2fl6Engine19removeInputVariableERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
0000000000129f70 g    DF .text  000000000000032f  Base        _ZNK2fl15RScriptExporter8toStringB5cxx11EPNS_6EngineEPNS_13InputVariableES4_iNS_11FldExporter13ScopeOfValuesERKSt6vectorIPNS_14OutputVariableESaIS9_EE
0000000000168eb0 g    DF .text  0000000000000013  Base        _ZN2fl13InputVariableD2Ev
00000000000b8070 g    DF .text  00000000000001b8  Base        _ZNK2fl6Engine16getInputVariableERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
000000000012bb30 g    DF .text  00000000000002d3  Base        _ZNK2fl15RScriptExporter6toFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6EngineEPNS_13InputVariableESC_iNS_11FldExporter13ScopeOfValuesERKSt6vectorIPNS_14OutputVariableESaISH_EE
000000000012c0f0 g    DF .text  0000000000000252  Base        _ZNK2fl15RScriptExporter29writeScriptExportingDataFrameEPNS_6EngineERSoPNS_13InputVariableES5_iNS_11FldExporter13ScopeOfValuesERKSt6vectorIPNS_14OutputVariableESaISA_EE
000000000010dc50 g    DF .text  0000000000000723  Base        _ZNK2fl11FldExporter5writeEPNS_6EngineERSoRKSt6vectorIfSaIfEERKS4_IPNS_13InputVariableESaISA_EE
0000000000118eb0 g    DF .text  0000000000000b0f  Base        _ZNK2fl11FllImporter20processInputVariableERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6EngineE
00000000000bb2b0  w   DF .text  0000000000000167  Base        _ZNSt6vectorIPN2fl13InputVariableESaIS2_EE17_M_realloc_insertIJS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_
00000000000b2010 g    DF .text  00000000000000da  Base        _ZN2fl6Engine16setInputVariableEPNS_13InputVariableEm
0000000000089770 g    DF .text  00000000000000b1  Base        _ZNK2fl10Complexity7computeERKSt6vectorIPNS_13InputVariableESaIS3_EE
0000000000129b50 g    DF .text  0000000000000106  Base        _ZNK2fl15RScriptExporter29writeScriptImportingDataFrameEPKNS_6EngineERSoPNS_13InputVariableES6_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIPNS_14OutputVariableESaISH_EE
0000000000168eb0 g    DF .text  0000000000000013  Base        _ZN2fl13InputVariableD1Ev
000000000012a5d0 g    DF .text  0000000000001552  Base        _ZNK2fl15RScriptExporter16writeScriptPlotsERSoPNS_13InputVariableES3_RKSt6vectorIPNS_14OutputVariableESaIS6_EE
000000000012c350 g    DF .text  000000000000013e  Base        _ZNK2fl15RScriptExporter29writeScriptExportingDataFrameEPNS_6EngineERSoPNS_13InputVariableES5_RSiRKSt6vectorIPNS_14OutputVariableESaIS9_EE
00000000000b8df0 g    DF .text  000000000000006e  Base        _ZN2fl6Engine16addInputVariableEPNS_13InputVariableE
0000000000168ed0 g    DF .text  0000000000000012  Base        _ZN2fl13InputVariableD0Ev
00000000000b20f0 g    DF .text  00000000000000db  Base        _ZN2fl6Engine19removeInputVariableEm
00000000000e0fc0 g    DF .text  0000000000000646  Base        _ZNK2fl11FclExporter8toStringB5cxx11EPKNS_13InputVariableE
0000000000088a70 g    DF .text  0000000000000040  Base        _ZNK2fl10Complexity7computeEPKNS_13InputVariableE
000000000010d990 g    DF .text  00000000000002b4  Base        _ZNK2fl11FldExporter6toFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6EngineEiNS0_13ScopeOfValuesERKSt6vectorIPNS_13InputVariableESaISE_EE
000000000012be10 g    DF .text  00000000000002d3  Base        _ZNK2fl15RScriptExporter6toFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6EngineEPNS_13InputVariableESC_RSiRKSt6vectorIPNS_14OutputVariableESaISG_EE
0000000000172a78  w   DO .data.rel.ro   0000000000000130  Base        _ZTVN2fl13InputVariableE
000000000010e9c0 g    DF .text  000000000000094c  Base        _ZNK2fl11FldExporter5writeEPNS_6EngineERSoiNS0_13ScopeOfValuesERKSt6vectorIPNS_13InputVariableESaIS7_EE
00000000000d6450 g    DF .text  0000000000000d21  Base        _ZNK2fl11CppExporter8toStringB5cxx11EPKNS_13InputVariableEPKNS_6EngineE
0000000000113600 g    DF .text  0000000000000dea  Base        _ZNK2fl11FllExporter8toStringB5cxx11EPKNS_13InputVariableE
00000000000b0bc0 g    DF .text  0000000000000155  Base        _ZN2fl6Engine17setInputVariablesERKSt6vectorIPNS_13InputVariableESaIS3_EE
000000000012a2a0 g    DF .text  000000000000032f  Base        _ZNK2fl15RScriptExporter8toStringB5cxx11EPNS_6EngineEPNS_13InputVariableES4_RSiRKSt6vectorIPNS_14OutputVariableESaIS8_EE
0000000000168ea0 g    DF .text  0000000000000006  Base        _ZNK2fl13InputVariable4typeEv
00000000000b1c80 g    DF .text  0000000000000058  Base        _ZNK2fl6Engine16getInputVariableEm
0000000000169000 g    DF .text  0000000000000019  Base        _ZN2fl13InputVariableC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEff
0000000000172a60  w   DO .data.rel.ro   0000000000000018  Base        _ZTIN2fl13InputVariableE
00000000000b8e60 g    DF .text  00000000000000f4  Base        _ZN2fl6Engine19insertInputVariableEPNS_13InputVariableEm
0000000000169000 g    DF .text  0000000000000019  Base        _ZN2fl13InputVariableC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEff
00000000000b1830 g    DF .text  000000000000016d  Base        _ZNK2fl6Engine16hasInputVariableERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
00000000000bafd0  w   DF .text  0000000000000167  Base        _ZNSt6vectorIPN2fl13InputVariableESaIS2_EE17_M_realloc_insertIJRKS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_

**Comment by farmboy0** [comment]
```
objdump -T /usr/lib64/vcmi/AI/libVCAI.so | grep InputVariable
0000000000000000      DF *UND*  0000000000000000  Base        _ZN2fl6Engine16addInputVariableEPNS_13InputVariableE
0000000000000000      D  *UND*  0000000000000000  Base        _ZN2fl13InputVariableC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEdd
```

**Comment by IvanSavenko** [comment]
Demangled version of problematic symbol:
```
fl::InputVariable::InputVariable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double, double)
fl::InputVariable::InputVariable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, float)
```
libVCAI.so requires method that receives double
libfuzzylite contains method that receives float

Investigating where this difference is coming from...

**Comment by IvanSavenko** [comment]
Not familiar with Gentoo, @farmboy0 where I can find package/build script/etc that you've used to install libfuzzylite?

**Comment by farmboy0** [comment]
I havent published it yet.
It comes down to this:


```
PATCHES=(
	"${FILESDIR}/${P}-no-warnings-as-errors.patch"
)

src_configure() {
	local mycmakeargs=(
		-DFL_BUILD_STATIC=$(usex static-libs)
		-DFL_USE_FLOAT=ON
		-DFL_BACKTRACE=ON
		-DFL_BUILD_TESTS=OFF
		-DFL_CPP11=$(usex c++11)
	)
	cmake_src_configure
}

```

**Comment by IvanSavenko** [comment]
Ah, that explains it.
option a:
- in your fuzzylite package remove or switch to OFF this option: `-DFL_USE_FLOAT=ON`

option b:
 - in vcmi sources open file AI/CMakeLists.txt
 - find line `find_package(fuzzylite)` and add line `add_definitions(-DFL_USE_FLOAT)` after it in the same if block
(yes, this is workaround, if we go with this approach I'll make it as an option)

I think that option A is better one, unless there is specific reason to build fuzzylite with float?

**Comment by farmboy0** [comment]
Its onl< used as dependency for vcmi so np, but why would that option break anything?

**Comment by IvanSavenko** [comment]
From [fl/variable/InputVariable.h](https://github.com/fuzzylite/fuzzylite/blob/9751a751a17c0682ed5d02e583c6a0cda8bc88e5/fuzzylite/fl/variable/InputVariable.h#L36):
`explicit InputVariable(const std::string& name = "", scalar minimum = -fl::inf, scalar maximum = fl::inf);`
Fuzzylite contains method that receives 3 parameters (std::string, scalar, scalar).
"scalar" is defined as either float or double, depending on that option.

Normally, when compiling c++ code compiler can make double<=>float conversions implicitly.
However, you ended up having:
- libfuzzylite.so with method that expects floats as input
- fuzzylite headers used by vcmi that have scalar defined as double
- when compiling libVCAI.so, compiler made assumption that this method receives doubles (since this is what was defined in headers) and converted all calls to that method to use double's
- as result, compiled libVCAI.so expects method that receives double's as input.
- dynamic linker that attempts to load libVCAI.so fails because linker requires exact match - it won't attempt to convert floats to doubles or vice versa - this is job for compiler.

**Comment by farmboy0** [comment]
Shouldn't creating libVCAI.so fail in such a case when methods can't be resolved?

**Comment by IvanSavenko** [comment]
Hmm... good point. 
I think gcc does not requires all symbols to be resolved in order to build shared library.
Not 100% sure but I do remember something like that...

If you were to build vcmi statically (not possible right now, so just an example) you would end up with linker error, but with dynamic linkage this situation is possible.

**Comment by farmboy0** [comment]
And there is no option to tell the linker to resolve all symbols?

**Comment by IvanSavenko** [comment]
Not that I know of

**Comment by farmboy0** [comment]
OK, the error is gone without FL_USE_FLOAT.
