### ISSUE TITLE
Lobby doesn't show allies

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1230]
1) Enter random map tab
2) Select amount of players > 3
3) Select amount of player teams > 1

Expected: Show allies
Actual: allies aren't shown
<img width="623" alt="Снимок экрана 2022-12-14 в 05 42 59" src="https://user-images.githubusercontent.com/9308612/207484700-6868327f-b19a-4836-bdae-9354696f8c8f.png">

**Comment by kambala-decapitator** [comment]
probably related to #1001
