### ISSUE TITLE
Player doesn't participate in game

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1233]
1) Open random map menu
3) Keep all map settings random
4) Open additional settings
5) Select pink flag (the last one) for human player
6) Start game

Expected: game is started - player has pink flag
Actual: game is started between AI players only - they are playing in background

Note: if RMG will generate map for 8 players issue will not be reproduced, so it's better to generate M+U or L map

**Comment by mikeiit** [comment]
Saw this issue today. It happens if we pick any flag below the green one (including green). I will try take a look.

**Comment by DjWarmonger** [comment]
Confirmed, will fix.

**Comment by DjWarmonger** [comment]
...or not. Unfortunately server (which controls player setup) does not have a simple way to inform client (random map options) about changes in player order.
The information only flows from client (CMapgenOptions) to server (CMapInfo) as far as I see :/

**Comment by IvanSavenko** [comment]
Perhaps we can completely reset player options if template / number of players has been changed?
I think this is how H3 work - changing map parameters resets everything in "advanced options" - starting town/hero & color

**Comment by krs0** [comment]
So what should be the behavior of advanced options when random template is selected?

Do we need to keep template a secret before game starts?

One possible behaviour would be to have the template already randomly selected when you enter Advanced Options. So correct number of players is shown, template info could be shown.This way you will not choose banned towns or heroes for that template.

Plus if you do not like the template you can randomly select another one.
