### ISSUE TITLE
iPad, iOS 15.6 - game hangs the second time you enter a lobby

### ISSUE THREAD

**Issue by staafl** [vcmi/vcmi#1239]
Repro: start game, go to new game, go to Scenario (the top button, I'm playing in French so I don't remember the name in English), go back, then click Scenario again. Game hangs immediately when you click the button (music is still playing). Same if you try to load a game, the second time you try to enter the list of saved games, the game hangs. Same if you try to launch a campaign (hangs the after you click the picture of the campaign). Or you can mix them, launch the game, start new scenario, then from the game menu try to go to the load game list.

I'm using the GOG version data files (French resources). iPad Pro 12.9, 3rd generation, MTFL2HC/A

Using a build of the app with the iOS App Signer web service, from the 17th of December, attaching my signed IPA:

Original build: https://builds.vcmi.download/branch/develop/iOS/VCMI-branch-develop-19105d1.ipa
My signed IPA: https://drive.google.com/file/d/1KVXwkS2b8MCiOxN-GgfPQwnl0J2VJw4C/view?usp=sharing

If the error isn't obvious from the logs and you'd like me to check if it reproduces with another build or signed with a different tool, I can do that.

Logs (grabbed while the game was in a hung state):
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/10252743/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/10252744/VCMI_Launcher_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/10252745/VCMI_Server_log.txt)

Thanks for your help!

**Comment by kambala-decapitator** [comment]
please re-test with `beta` (1.1 pre-release) branch, should've been fixed there: https://builds.vcmi.download/branch/beta/iOS/

**Comment by Nordsoft91** [comment]
@kambala-decapitator reproduced on beta, duplicates #1202

**Comment by Nordsoft91** [comment]
@staafl fixed in build from 18 dec

https://builds.vcmi.download/branch/beta/iOS/

**Comment by staafl** [comment]
Thanks, I can confirm it now works for me.
