### ISSUE TITLE
Regression: custom maps cannot be started

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1254]
1. Create any custom map in editor, using hero from mods
2. Launch this map

Expected result: map is started ok (as in 1.0)
Actual result: server crashes

Beta branch has this problem from the beggining
Develop branch first appears on fd21f9e

Assuming root cause is #1777

**Comment by misiokles** [comment]
[all1_test.zip](https://github.com/vcmi/vcmi/files/10274803/all1_test.zip)
Test map (needs Courtyard mod to be enabled)
Map name: All for One test

**Comment by IvanSavenko** [comment]
Investigating...

**Comment by IvanSavenko** [comment]
FYI: this map is broken - it has hero inside main town AND player has "generate hero in main town" option checked. Not sure what should be done in such case.
H3 editor does not permits such case, by blocking invalid actions, but vcmi editor does not performs any checks.
Will probably create an issue about this.
