### ISSUE TITLE
Support .h3m maps HoTA format

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1259]
I have a branch doing some byte hunting while reading hota map. Basically it already supports new terrains from hota.
https://github.com/Nordsoft91/vcmi/tree/hota-maps-support
But it's really hard to do such development using macOS, because I cannot quickly change something in hota map editor.

So it's better to do this feature for windows-based developer or if hota crew can share description of their data format.

**Comment by kambala-decapitator** [comment]
> But it's really hard to do such development using macOS, because I cannot quickly change something in hota map editor.

does it not work under wine? at least original editor works perfectly for me.

**Comment by dydzio0614** [comment]
Funny thing - the maintainer https://github.com/mapron/FreeHeroes asked me if hota map format is planned for VCMI, and said he is fine with peeking at his code, since he got hota map format fully cracked and working so we don't have to do manual labor

**Comment by IvanSavenko** [comment]
Looks like his code is more complete than in Nordsoft branch.
But I think larger problem is ID's. We have no guarantee that HotA objects will get same numeric ID as in HotA. Probably needs some ID remapper: hota ID -> vcmi string ID -> vcmi numeric ID.

**Comment by nullkiller** [comment]
I remember that objects in json config has magic index property where you can specify h3m index, but not sure it will work for hota. We can add some h3mIndex property in mod object definition so that we can build such map internally.

**Comment by IvanSavenko** [comment]
"index" property is primary designed towards H3 object - those that may have hardcoded logic in vcmi & have data in h3 txt's.
We can go two ways here:
a) field named "hotaMapIndex" in objects (I'd prefer clearly specifying hota - in theory we may support WoG maps at some point, which had own new objects)
b) file that contains all mappings for hota objects, to be used as input for h3mhota parser.

Nothing too complex, but still should probably be a first step.
