### ISSUE TITLE
Connect button doesn't change to Disconnect after connection

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1270]
1. open launcher
2. go to lobby
3. press Connect
4. observe that the button doesn't change its title, although pressing it again disconnects you

**Comment by Nordsoft91** [comment]
It's not a bug, because it's toggle button, which can have 2 states-checked or unchecked

**Comment by kambala-decapitator** [comment]
> It's not a bug, because it's toggle button, which can have 2 states-checked or unchecked

well, it's not obvious in the UI at all
