### ISSUE TITLE
No templates found for item.... warnings in console log

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1274]
For Items like idolOfFortune the following warnings appear in console log:

```
No templates found for 38:1
No templates found for 49:1
No templates found for 79:7
No templates found for 90:1
No templates found for 100:1
No templates found for 103:1
No templates found for 113:1
No templates found for 172:0
No templates found for 186:0
No templates found for 189:0
        Handlers post-load finalization: 260186 ms
```

**Comment by Alexander-Wilms** [comment]
I can reproduce this when starting the editor, without even having created or opened a map.

Also, in the "Create new map" dialog, the Template drop-down has no entries, but /app/share/vcmi/config/schemas/template.json does exist.

It seems the issue stems from 

https://github.com/vcmi/vcmi/blob/f073c676f9a63461eb780f0ef6ecedcf98e9efac/lib/mapObjects/CObjectClassesHandler.cpp#L379
and
https://github.com/vcmi/vcmi/blob/a7f521cbd9000a22249ae593447a7c34a2625db1/lib/rmg/CRmgTemplateStorage.cpp#L66

**Comment by IvanSavenko** [comment]
Known issue, safe to ignore - I don't see any dangerous cases. Will fix warnings by 1.2 release

**Comment by IvanSavenko** [comment]
Should be already fixed in develop branch

**Comment by krs0** [comment]
Cannot reproduce it anymore with Client or Map Editor.
