### ISSUE TITLE
Multiplayer lobby: colon (:) doesn't work in chat, horizontal scrollbar seems to be useless

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#1278]

**Comment by Nordsoft91** [comment]
> horizontal scrollbar seems to be useless
What do you mean?

**Comment by dydzio0614** [comment]
![obraz](https://user-images.githubusercontent.com/9436577/209402474-f3b6e0eb-b40c-43c5-8648-d328e32e4690.png)
Scrollbar at the bottom of chat window

**Comment by dydzio0614** [comment]
Okay, on proper linux build i dont have bottom scrollbar - if it doens't appear on Windows / macOS as well then i guess the problem is irrelevant anymore
