### ISSUE TITLE
Add map editor launch button to VCMI launcher

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#1284]
There is at least one problem related to how we package builds related to map editor - one of them is that flatpak linux build is only able to run single executable, so there is no way to run map editor there. Adding this button would workaround any corner cases for using VCMI map editor.

**Comment by IvanSavenko** [comment]
Yeah, was planning to do that (among some other changes to Launcher) soon

**Comment by Nordsoft91** [comment]
I'm going to support it after editor will be available for iOS

**Comment by dydzio0614** [comment]
Sure, if ETA for iOS editor is not going to be very long, since button can be made invisible for iOS while editor is not ready for it anyway.

**Comment by IvanSavenko** [comment]
Closing as fixed in #1293
