### ISSUE TITLE
Android: Savegames from 1.0.0 not visible in 1.1.0

### ISSUE THREAD

**Issue by lje** [vcmi/vcmi#1285]
I just upgraded VCMI Androud from 1.0.0 to 1.1.0, when trying to load a single player save game, no save games are visible

Android 13 on Samsung Galaxy Tab S8+

**Comment by kambala-decapitator** [comment]
1.0 saves are incompatible with 1.1, it's mentioned in https://vcmi.eu/news/vcmi-1.1.0-release/

**Comment by lje** [comment]
Thanks for the link. I kindly ask to add that to the Github release notes (https://github.com/vcmi/vcmi/releases/tag/1.1.0) as well, as it isn't mentioned there.

**Comment by kambala-decapitator** [comment]
good idea, thanks! Just added.

**Comment by lje** [comment]
Same issue again with 1.1.0 ->1.2.0: the [release notes on Github](https://github.com/vcmi/vcmi/blob/master/ChangeLog.md#111---120) again don't state savegame incompatibility, while https://vcmi.eu/ does.

**Comment by IvanSavenko** [comment]
I can add that statement, but generally expect that *all* major releases (e.g. 1.X) are not save-compatible with each other.
