### ISSUE TITLE
cursor image jumps on click when hero can no longer move

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1298]
In the video I click on the pikemen tower and the "horse" cursor suddenly jumps to the right. However, mouse cursor itself doesn't change the position (here the OS black arrow is visible), and slight mouse movement fixes the "horse" cursor position.

https://user-images.githubusercontent.com/1557784/209476461-f5a524d9-efac-4535-8801-da0c9b204011.mov

**Comment by dydzio0614** [comment]
Can you recall if you were using fullscreen without "real fullscreen mode", with non-native resolution set?

**Comment by kambala-decapitator** [comment]
> Can you recall if you were using fullscreen without "real fullscreen mode", with non-native resolution set?

Exactly

**Comment by dydzio0614** [comment]
The deal is I talked to devs that use SDL back in the day and if I remember correctly for aspect ratio other than default one mouse position should be recalculated on every move to adjust its position... and there are some other things to be wary about. The real solution would be disabling ability to run "non-real fullscreen" for resolution other than screen native, as 99% of games do. Also IDK if related but somebody told me that he has alt-tab behavior problem on windows when running VCMI on multiple monitor setup.

**Comment by IvanSavenko** [comment]
Most likely will be fixed by #2076

**Comment by IvanSavenko** [comment]
Closing, presumably fixed

**Comment by dydzio0614** [comment]
definitely fixed if borderless windowed fullscreen doesn't use resolution with aspect ratio different than screen native
