### ISSUE TITLE
"high morale" animation not visible when creature is poisoned

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1299]
Steps:
1. a creature is poisoned, e.g. by Wyvern Monarch
2. the creature receives additional turn (high morale)
3. the "yellow bird" animation isn't seen/heard - seems that poison animation/sound overwrites it

probably related to #1048

**Comment by IvanSavenko** [comment]
Was this on develop or 1.1 release?

**Comment by kambala-decapitator** [comment]
1.1 release

**Comment by IvanSavenko** [comment]
Should be fixed in #1229
