### ISSUE TITLE
underground cartographer doesn't reveal underground map

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1303]
this guy took thousand gold and cheated me! But his surface colleague was honest.

![Screenshot 2022-12-26 at 01 14 45](https://user-images.githubusercontent.com/1557784/209483723-d2cee7bc-ba41-43ac-9dcd-32b3c4e142b3.png)

**Comment by IvanSavenko** [comment]
Huh, looks like our cartographer works not like in H3.

Cartographer should not work by levels but rather by terrain types. So underground cartographer should reveal all underground tiles (and not underground layer)

**Comment by kambala-decapitator** [comment]
based on FizMig it seems that it kinda worked correctly as this is the surface cartographer (based on the image). But:
- it seems strange that surface cartographer is located underground - RMG issue?
- one more visit to surface cartographer shouldn't have taken money from me

![Screenshot 2022-12-26 at 11 39 28](https://user-images.githubusercontent.com/1557784/209526330-bdbd42ff-9c53-4cff-a005-5a91c572a5f3.png)

P.S. You can find save here: #1301

**Comment by IvanSavenko** [comment]
Your image also says about "terrain types". Not levels. And currently vcmi checks for levels.
Water Cartographer does works correctly (judging from code), but surface/subterra versions don't

**Comment by kambala-decapitator** [comment]
> And currently vcmi checks for levels

it can be considered a related issue, as it seems that this one is not about that

> Water Cartographer does works correctly (judging from code)

it used to work correctly in 1.0 indeed, this time didn't stumble on it to test

**Comment by kambala-decapitator** [comment]
> it seems strange that surface cartographer is located underground - RMG issue?

based on FizMig this is RMG bug indeed:

![Screenshot 2022-12-29 at 11 21 24](https://user-images.githubusercontent.com/1557784/209924137-0a1a67d4-0e96-4406-a25f-f9fd5c65c91a.png)

I'll open separate issues for everything that was discovered here and will close this one.
