### ISSUE TITLE
killed creature wasn't actually killed

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1304]
During the battle enemy hero killed 1 Archangel with Magic Arrow (also visible in the battle log). But then I noticed that the amount of Archangels in stack didn't decrease, I also couldn't resurrect him with my other Archangel. And then in the battle results it said no casualties.

![Screenshot 2022-12-25 at 23 27 51](https://user-images.githubusercontent.com/1557784/209483820-be3ccad5-6015-4d38-94da-4d30c64b4069.png)
![Screenshot 2022-12-25 at 23 28 11](https://user-images.githubusercontent.com/1557784/209483825-19f37b16-afd7-42f4-a04a-f3392a805d38.png)

Logs: [Archive.zip](https://github.com/vcmi/vcmi/files/10300721/Archive.zip)

**Comment by kambala-decapitator** [comment]
had this issue again, and again because of Magic Arrow. This was the very first damage in the battle, and 110 damage simply couldn't kill one Behemoth.

![Screen Shot 2023-01-07 at 17 11 07](https://user-images.githubusercontent.com/1557784/211155732-581ce2d3-3611-4559-b747-c1f7cb5960b3.png)

**Comment by IvanSavenko** [comment]
- was there anything in common between these cases? E.g. same save or same map?
- can you reproduce it, e.g. from loaded autosave & starting the same battle?
- can you make screenshot of hero window? To show his stats, skills, equipped artifacts.

**Comment by kambala-decapitator** [comment]
- completely different maps, and RMG templates too I think
- yes, could reproduce. Attack the nearby hero, wait with melee creatures, attack Pixies with Cyclops, after that enemy casts Magic Arrow on Behemoths. [save.tar.gz](https://github.com/vcmi/vcmi/files/10366524/save.tar.gz)

![Screen Shot 2023-01-07 at 17 43 10](https://user-images.githubusercontent.com/1557784/211156717-f1ce4297-4d58-43a9-8e7d-0ab8e155371f.png) ![Screen Shot 2023-01-07 at 17 45 50](https://user-images.githubusercontent.com/1557784/211156718-77ae352c-4443-4cdd-806f-389a97ecd56e.png)

mods I have:

![Screen Shot 2023-01-07 at 17 48 36](https://user-images.githubusercontent.com/1557784/211156721-9e26191e-fdf4-445f-b2a0-c201116c0a8f.png)

**Comment by IvanSavenko** [comment]
Damn... I though that this is some complex synchronization bug where incorrect information ends up on a client...
Only to find out that this is simply incorrect battle log formatting. Will push fix soon.
