### ISSUE TITLE
effect of Boots of Levitation/Angel Wings isn't applied immediately

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1320]
My actions were:
1. approached water
2. put Boots of Levitation on
3. couldn't cross water, thought I don't have enough movement points any more
4. switched back to the boots that give extra movement points, waited till next day
5. put Boots of Levitation on, still couldn't cross water

Pretty sure that I had enough points at the beginning of a day: hero had 3 `+` marks and water distance was small enough.

Then I loaded the save again to re-test, but this time all worked correctly...

https://bugs.vcmi.eu/view.php?id=2098

**Comment by kambala-decapitator** [comment]
same issue with Angel Wings: Fly effect appears only on the next day

**Comment by kambala-decapitator** [comment]
Making a step in any direction makes considering Angel Wings again on next route planning

**Comment by IvanSavenko** [comment]
I guess that changing artifact does not triggers pathfinder cache update.
I see there is `CPlayerInterface::heroBonusChanged` which (I assume) should have handled this case, but didn't for some reason.

**Comment by kambala-decapitator** [comment]
existing bug report: https://bugs.vcmi.eu/view.php?id=2098
