### ISSUE TITLE
Max resolution that can be set from Client on Windows is 1366x768

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1321]
**Describe the bug**
From client the max resolution I can set is 1366x768
From Launcher I can set way higher.

**To Reproduce**
![image](https://user-images.githubusercontent.com/15194321/209660161-ca0555b6-30e2-4a5f-a1d4-249128f942cf.png)

**Version**
 - OS: Windows 10
 - Version: 1.1.0

Hmmm.... I tried 1680 x 1050 seems that "higher resolutions are not available"?

[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/10307880/VCMI_Client_log.txt)

**Comment by kambala-decapitator** [comment]
issue template was created for a reason, please fill it

**Comment by krs0** [comment]
> A clear and concise description of what the bug is.


> issue template was created for a reason, please fill it

I know... my pinky finger hit Enter Key by mistake :)

**Comment by IvanSavenko** [comment]
Make sure you have this thing set at 100%

Hey, Windows devs, find a way to attach `DPIaware.manifest` we already have in client dir to vcmiclient.exe during build

![зображення](https://user-images.githubusercontent.com/1576820/209660741-c2f324f3-9363-4d0d-9f4a-8df81b8cb6e3.png)

**Comment by krs0** [comment]
Yup that did the trick!

**Comment by krs0** [comment]
Original problem solved. DPI Aware request moved to separate issue.
https://github.com/vcmi/vcmi/issues/1649
