### ISSUE TITLE
Incorrect information for skills in hero exchange window

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1324]
In hero exchange window, when I click any primary skill icon, I should not get any numbers, let alone negative ones!

![image](https://user-images.githubusercontent.com/15194321/209671023-18dca453-22c4-426c-b8ff-2a49351ea505.png)

When fixing, Hero Info screen should be checked as well.

 - Version: VCMI 1.1.0

**Comment by krs0** [comment]
negative bonuses were fixed, but now instead of actual value... only bonus appears
Below actual value is 1, but bonus of +0 appears.

![image](https://github.com/vcmi/vcmi/assets/15194321/07a75250-bb2d-4afc-8f14-0b72d6c581c0)

**Comment by rilian-la-te** [comment]
How you checked than actual value is 1?

**Comment by IvanSavenko** [comment]
I can confirm this bug.
We currently don't provide skill values in exchange screen since that icon is shared between two heroes. As result, component takes placeholder value (-1 or 0) resulting in this bug.

**Comment by krs0** [comment]
> 

by lòkin very intensly at it :)
