### ISSUE TITLE
Creature specialist heroes do not work like in Original H3

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1325]
Creature specialist heroes should increase the speed of the unit they specialize in by 1. This should affect hero movement calculation as well if applicable.
The attack and defense bonuses should increase starting at level 1. Detailed example: https://heroes.thelazy.net/index.php/Drakon

![image](https://user-images.githubusercontent.com/15194321/209673287-e88cd132-cca6-457f-aa80-c4c3360506f0.png)

VCMI 1.1.0

**Comment by rilian-la-te** [comment]
@krs0 latest develop, all seems to working.

![изображение](https://user-images.githubusercontent.com/1329638/227795567-f603bd65-da44-4ace-9b84-127e54058b4a.png)

**Comment by IvanSavenko** [comment]
Might have been fixed already - there were a few bugs with creature specialists that got fixed in 1.2.
So closing I guess?

**Comment by krs0** [comment]
Looks good. Hero movement points also correctly updated.
