### ISSUE TITLE
Allow player to start battle,  while battle intro music plays in background

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1327]
Play the start battle music in background always and let the player do its stuff.
Additionaly add a global option to completely disable battle start music as well.

**Comment by IvanSavenko** [comment]
Press ESC.
We should also add message about ESC in combat log
Global option to toggle it off - sure, but by default game should work as it is now.

**Comment by krs0** [comment]
Whats is the porpuse of forcing the player to wait a few seconds, every battle? Or make him hit a key in the other case?

Some play with sounds turned off.
Some play with mouse only.

VCMI is slow enough as it is for the moment, no need to artificially add dead times.

**Comment by kambala-decapitator** [comment]
> Whats is the porpuse of forcing the player to wait a few seconds, every battle?

this is the behavior of the original game

**Comment by misiokles** [comment]
silent wav mod does this job.

**Comment by IvanSavenko** [comment]
> Whats is the porpuse of forcing the player to wait a few seconds, every battle? Or make him hit a key in the other case?
Time to prepare and evaluate starting situation, instead of suddenly ending up in the middle of battle if enemy got the first turn. Especially - if battle was initiated by enemy during enemy turn.

**Comment by krs0** [comment]
Ok, some want it some not. Looks like perfect candidate for an option.

**Comment by DjWarmonger** [comment]
Turning off the music is one thing, but I don't see why the interface should ever be blocked while it's playing.
