### ISSUE TITLE
buttons are disabled for the first creature in Tactics phase

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1331]
**Describe the bug**
in Tactics phase you can't switch to next creature or start battle with button/hotkey until you either move the first creature or select another one with mouse click.

**Game logs**
Irrelevant

**To Reproduce**
1. get a hero with Tactics
2. fight someone
3. observe disabled Tactics buttons

**Expected behavior**
Buttons shouldn't be disabled and hotkeys should work

**Actual behavior**
Buttons are disabled and hotkeys don't work

**Did it work earlier?**
Works in 1.1 release

**Screenshots**
![Screenshot 2022-12-28 at 11 18 16](https://user-images.githubusercontent.com/1557784/209783106-be4d4478-eb4b-4ef5-8796-feeaf3ed808b.png)

**Version**
 - OS: macOS Intel
 - Version: latest develop

**Comment by IvanSavenko** [comment]
Already fixed in PR #1229
(found exactly same bug there myself)
