### ISSUE TITLE
no yellow outline on creature when selected by mouse in Tactics phase

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1332]
**Describe the bug**
Normally current creature has yellow outline in Tactics phase, but if you select creature with mouse instead of button/hotkey, then there's no outline (but creature is selected properly).

**Game logs**
Irrelevant

**To Reproduce**
1. get a hero with Tactics
2. fight someone
3. click another creature during Tactics phase 
4. observe no outline on the creature

**Expected behavior**
the selected creature has yellow outline

**Actual behavior**
the selected creature has no outline at all

**Did it work earlier?**
IIRC same behavior in 1.1 release

**Version**
 - OS: macOS Intel
 - Version: latest develop

**Comment by IvanSavenko** [comment]
Can confirmed to be fixed in #1229
