### ISSUE TITLE
Invisible mouse pointer

### ISSUE THREAD

**Issue by VortexAcherontic** [vcmi/vcmi#1334]
**Describe the bug**
The mouse pointer is not visible as soon as the mouse enters the game window after launching the game.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install VCMI via flatpak
2. Start the game
3. Move mouse over the game

**Expected behavior**
Pointer to be visible

**Actual behavior**
Invisible pointer

**Did it work earlier?**
No broken since (at least) 0.99

**Screenshots**
[Screen cast](https://user-images.githubusercontent.com/11244092/209818577-72b81c67-e25b-49b1-b525-f4cdd363984a.webm)

**Version**
 - OS: Linux (openSUSE MicroOS)
 - Version: 1.1.0

**Additional context**
Maybe this is somehow related:
Display server: Wayland
GPU Driver: nVidia 525.60.11
Dual monitor setup: Yes
Desktop environment: Gnome 43.2

**Comment by dydzio0614** [comment]
@VortexAcherontic could you just in case also test if bug happens on xorg or with toggled "real fullscreen mode" in launcher settings?

**Comment by orowith2os** [comment]
Test this on AMD/Intel as well, NVIDIA with Wayland can be weird.

Also, how does VCMI handle display+input? SDL?

**Comment by IvanSavenko** [comment]
Yes, SDL, for display, window and input

**Comment by orowith2os** [comment]
Alright then, maybe the flatpak should update to using the shared-module for SDL2 (with libdecor). As of now, the SDL2 shipped by freedesktop is a bit out of date and might not work the best.

**Comment by dydzio0614** [comment]
@Alexander-Wilms could you help with this?

**Comment by IvanSavenko** [comment]
Link to said module: https://github.com/flathub/shared-modules/tree/master/SDL2

Sorry, not familiar with flatpak. I believe @Alexander-Wilms is the one who manages vcmi on flatpak.
@Alexander-Wilms, is it possible for you to make such changes?
Or, if he is not available, how should we proceed with this?

**Comment by dydzio0614** [comment]
he might be available soon, he upvoted our release on github IIRC :P

**Comment by dydzio0614** [comment]
@IvanSavenko in case he is inavailable afaik it's possible to deal with flathub directly to invalidate his flatpak manifest but it's last resort

**Comment by VortexAcherontic** [comment]
> @VortexAcherontic could you just in case also test if bug happens on xorg or with toggled "real fullscreen mode" in launcher settings?

Forcing VCMI to run via XWaylnd via flatseal solved the issue.

Sorry that I didn't tried this prior to reporting this issue :/

**Comment by orowith2os** [comment]
Even if write access to the flathub repo isn't possible, you can still make a merge request to the package and it'll provide you a bundle to test.

Thanks for trying that @VortexAcherontic, hopefully the issue is just with NVIDIA, or an SDL2 upgrade does the job.

**Comment by Alexander-Wilms** [comment]
I created a PR to update SDL: https://github.com/flathub/eu.vcmi.VCMI/pull/97

Right now I don't have access to my Linux machine, can you test the build once its done, @VortexAcherontic ?

Also, if someone from the VCMI team wants write access to the Flathub repo, they can contact the admins, e.g. on https://matrix.to/#/#flatpak:matrix.org (Or via other means listed on https://flatpak.org/about/) and they'll add you.

**Comment by orowith2os** [comment]
@VortexAcherontic the flatpak should have an update available in an hour or less, can you give it one more try then?

**Comment by VortexAcherontic** [comment]
Updated SDL worked. The pointer is now shown also on true Wayland. Many thanks all ❤️
