### ISSUE TITLE
H3 for VCMI englisation crash

### ISSUE THREAD

**Issue by luk3ZPL** [vcmi/vcmi#1337]
**Describe the bug**
Game hang up (black screen) and then crash after clicking Start game button.

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**

**Expected behavior**
Start the game.

**Actual behavior**
Hang up

**Did it work earlier?**
First start.

**Screenshots**

**Version**
 - OS: W7 x64
 - Version: VCMI-1.1.0-Windows
 - 
**Additional context**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/10316074/VCMI_Client_log.txt)
[VCMI_client.exe_crashinfo.zip](https://github.com/vcmi/vcmi/files/10316076/VCMI_client.exe_crashinfo.zip)

**Comment by dydzio0614** [comment]
Mod "H3 for VCMI englisation" triggers assert:

Client crash: vcmiclient: ./lib/CHeroHandler.cpp:819: void CHeroHandler::loadBallistics(): Assertion `bli.noDmg + bli.oneDmg + bli.twoDmg == 100 && bli.sum == 100' failed.

**Comment by IvanSavenko** [comment]
Hmm... It is possible that downloading mods via github export breaks mods that come with H3 txt's
These files have rather tricky line endings usage & git likely overwrites all of that with own settings

**Comment by misiokles** [comment]
VCMI can read zipped 'content' folders so maybe uploading mod as content.zip will avoid breaking?

**Comment by IvanSavenko** [comment]
Yes. Provided that said .zip includes original/unmodified text, and not exported from github.
In 1.2 release we'll likely have better localization tools, that won't be affected by such issues.

FYI - vcmi mod can have Content.zip AND Content directory in the same time, you can move all .txt's to zip and keep rest files as it. Choice is up to you though.
