### ISSUE TITLE
set artifact not assembled after capturing missing pieces from enemy

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1341]
save: https://github.com/vcmi/vcmi/files/10300591/Archive.tar.gz

after capturing town I'm asked if I want to assemble AotD, I say yes, but in fact it's not assembled in the backpack. I also see the following logs:

> Ranged attack animation is over
> Unrecognized trigger effect type 5
> Unrecognized trigger effect type 5
> assembleArtifacts: there is no such artifact instance!
> Got false in applying 17AssembleArtifacts... that request must have been fishy!
> Stopping music file MUSIC/COMBAT03 at 60.742001
> Stopping music file Music/Win Battle at 0.704000
> Warning: IntObject re-activated with mismatching used and active
> System message: Server encountered a problem: assembleArtifacts: there is no such artifact instance!
> System message: Server encountered a problem: Got false in applying 17AssembleArtifacts... that request must have been fishy!

initially discovered in #1313

**Comment by SoundSSGood** [comment]
Will take a look

**Comment by SoundSSGood** [comment]
@kambala-decapitator Unfortunately, I can't load your save file. VCMI extras mod incompatibility. I have a latest one.
If you update your mod and catch this bug again, please upload more saves.

**Comment by kambala-decapitator** [comment]
@SoundSSGood simply edit `mod.json` of the mods that game complains about and set version to what the game wants in there. For example, you can comment the existing version field and add the "right" one, and revert afterwards.
