### ISSUE TITLE
Navigations skill should be banned on water-less RMG maps

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#1352]
**Useless Navigations skill**
At non-water maps navigation skill shouldn't be offered in any ways.

**Game logs**
N/A.

**To Reproduce**
Generate random map without water. Sometimes hero can learn Navigation skill which is useless in such maps.

**Expected behavior**
Naviagtion skill at non-water maps shouldn't be offered.

**Actual behavior**
Naviagtion skill at non-water maps is offered.

**Did it work earlier?**
Idk

**Screenshots**
![image](https://user-images.githubusercontent.com/29593042/210094810-4e630ad3-ae77-4ed0-bf29-fd495cd6ecc8.png)

**Version**
 - OS: Windows
 - Version: VCMI 1.2.0.1345bdb901aaeb36676252468fa996b49d20166c

**Comment by misiokles** [comment]
![image](https://user-images.githubusercontent.com/29593042/210095020-d46c5821-9622-4268-9aeb-e0e37cd5f814.png)

**Comment by IvanSavenko** [comment]
Seems to be a HotA feature.
HotA also replaces heroes who have Navigation as starting skill on such maps.

**Comment by misiokles** [comment]
But HotA doesn't affect Scholars who offered me useless in this case navigation.

**Comment by DjWarmonger** [comment]
Should be handled along with related spells and artifacts, which need to have additional configurable property. Something like `"onlyWaterMaps"`.

**Comment by Alucard648** [comment]
I think, it`s RMG issue. If it generates non-water map, it should auto-ban the following artifacts,skill and spells that has the following properties:

- Everything that grants sea movement points
- Everything that grants bonuses limited to water terrain. Like Mast Cap artifact that grants combat bonuses, but works only when fightning on sea.
- Bonuses that works only on objects that cannot exist outside water (ship manipulation spells and protection from losing troops when going through whirlpools).

HotA also replaces heroes that has Navigation specialization with different heroes, on case per case basis.
