### ISSUE TITLE
Introduce chess-like time limits

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#1364]
Competitive MP community uses more complex scheme of timers than available in H3 Complete:

**Base timer**
- counts down only when turn timer runs out, 
- never resets
- by default, set to 12:00
- if timer expires, player ends his turn

**Turn timer**
- counts down when player is making his turn on adventure map, 
- resets every turn
- any unspent time should be added to base timer
- by default, set to 6:00
- if timer expires, "base timer" starts counting down

**Battle timer**
- counts down during battles when creature timer runs out
- resets every battle
- any unspent time is lost
- by default, set to 2:00
- timer is paused during creatures' animation playback
- (pvp) if timer expires, currently acting creature will defend
- (pve) if timer expires, "turn timer" starts counting down

**Creature timer**
- counts down when player is choosing action in battle
- only active in pvp battles
- resets after each creature turn
- by default, set to 0:30
- if timer expires, "battle timer" starts counting down

Partially resolved by https://github.com/vcmi/vcmi/pull/2576, https://github.com/vcmi/vcmi/pull/2674, https://github.com/vcmi/vcmi/pull/2698

- [x] UI to specify new timers
- [x] (pve) if timer expires, "turn timer" starts counting down
- [x] creature timer only active in pvp battles
- [x] Timer pausing when turn is passed in HotSeat mode (potential solution - accept turn message or query)
- [x] Define logic for tactics
- [x] FPS counter overlaps with timer
- [ ] Query auto-answer
- [x] Fix potential concurrency issues - CGameHandler::run can run concurrently with incoming pack processing 
- [x] Fix timer drifting in CGameHandler::run - sleep for 100 ms is not guaranteed to be 100 ms and usually will be slightly longer
- [x] Fix hero getting stuck on water / in obstacles if he was moving with Flight when timer runs out
- [x] Fix hero getting stuck on water if he was moving with Water Walk when timer runs out (should be resolved by https://github.com/vcmi/vcmi/issues/2678)

**Comment by krs0** [comment]
Is this slider for timers needed? On PC it has no function.

![image](https://github.com/vcmi/vcmi/assets/15194321/5c679e50-372f-402f-a04d-fbfcb28c7f7e)

**Comment by krs0** [comment]
Base time is not conveying any meaning.
Extra time? Or Reserve time?

Also why by default unspent turn time is added to this?
Time limitations are there to shorten the game. Why would you make it longer by adding unspent time?
Would be nice as option if anyone asks for it, but by default it should not increase.

First few turns always take longer. Add an additional turn time buffer to turns 1-3? You should not consume extra time in first turns. The purpose of that is to safeguard for outstanding conditions.

**Comment by IvanSavenko** [comment]
@krs0 
Base time - feel free to propose better names here: https://github.com/vcmi/vcmi/pull/2698#discussion_r1309959699

Unspent time addition  - this is how it was requested by MP guys. Not sure who exactly requested this, might be part of initial task description from Dydzio I think? If this is mistake then yes, should be changed.

**Comment by dydzio0614** [comment]
unspent time addition is how it works by default in hota if non-classic timer is chosen (99% of multiplayer games)

**Comment by IvanSavenko** [comment]
> > Is this slider for timers needed? On PC it has no function.
> 
> I'm not good in making assets and created mod for reference purpose. You can modify it directly in mod if you want.

So what? Neither am I. Nor is dydzio / krs. Does not justifies leaving programmer art as it.

HD Mod which you love using as reference does not have this ingenious slider either.

**Comment by krs0** [comment]
Ok got my answer on Discord (useful thing!).
Time accumulation is a much needed feature. So that players can use skill to juggle how fast / safe they play at begining  vs late game.

**Comment by IvanSavenko** [comment]
Closing, implemented in 1.4
