### ISSUE TITLE
Version 1.1.0 fails to build with scripting enabled

### ISSUE THREAD

**Issue by danfe** [vcmi/vcmi#1366]
Building with `-DENABLE_ERM:BOOL=ON -DENABLE_LUA:BOOL=ON` results in the following error:
```
.../vcmi-1.1.0/lib/ScriptHandler.cpp:245:77: error: incomplete type 'CModHandler' named in nested name specifier
        auto object = loadFromJson(logMod, scope, data, normalizeIdentifier(scope, CModHandler::scopeBuiltin(), name));
                                                                                   ^~~~~~~~~~~~~
.../vcmi-1.1.0/lib/VCMI_Lib.h:27:7: note: forward declaration of 'CModHandler'
class CModHandler;
```
There've been a few commits after 1.1.0 got tagged, so apologies if it's already fixed by some commit (in this case, which one?).

**Comment by IvanSavenko** [comment]
don't think that such commit exists.
You can fix it by adding line
`#include "CModHandler.h"`
At line 20 of lib/ScriptHandler.cpp

However keep in mind that scripting support is far from "production ready" and not something that should be enabled in normal builds

**Comment by danfe** [comment]
> You can fix it by adding line `#include "CModHandler.h"` at line 20 of `lib/ScriptHandler.cpp`

Right, I already did exactly that (also in `scripting/lua/LuaScriptingContext.cpp`).

> However keep in mind that scripting support is far from "production ready" and not something that should be enabled in normal builds

I understand, I was just testing the build with all available knobs enabled.  Should I even offer this option to the FreeBSD ports users?

**Comment by IvanSavenko** [comment]
>  Should I even offer this option to the FreeBSD ports users?

Don't see any point in that.
You can give option to turn off ENABLE_LAUNCHER & ENABLE_EDITOR to remove Qt dependency (but default should be ON)
Also check FORCE_BUNDLED_FL & FORCE_BUNDLED_MINIZIP, you may want to have them OFF if FreeBSD has these libraries separately.

Other than that - don't see any options that can be of use to end-users

**Comment by danfe** [comment]
Thanks, the port already does all those things you mentioned (I'm not forcing minizip as CMake finds it correctly).  I guess I'll just leave scripting support out for the time being.  Keeping the issue open as it's still technically a build bug.
