### ISSUE TITLE
selection behavior issues in the Save dialog

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1371]
**Describe the bug**
- when you click on a save, its name is set in the bottom correctly, but selection highlight changes only on next click
- timestamp in the top right corner never changes on selection. Seems it changes only after double-click.

**To Reproduce**
See video

**Expected behavior**
- selected save is highlighted immediately
- timestamp changes according to the selected save

**Actual behavior**
wrote in description

**Did it work earlier?**
at least same issue in 1.0 release

**Screenshots**

https://user-images.githubusercontent.com/1557784/210742849-63121736-296b-4e1c-b062-3f1a6ceb7a6a.mov

**Version**
 - OS: macOS Intel
 - Version: 1.1 release

**Comment by mikeiit** [comment]
Happened to reproduce this one today, I will take a look.
