### ISSUE TITLE
Switch all animation effect to time-based approach with H3 timings

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#1376]
Currently most of vcmi code uses frame counts for animating.
However this can easily graphical artifacts if client is unable to maintain target refresh rate on low-end devices. Another potential issue is high-refresh monitor displays - increasing refresh rate to match display refresh rate will lead to animation speed up.

And even existing timings are likely off and don't match H3. Meaning that all H3 animations should be rechecked and where necessary - converted into time-based animations.

List of effects that needs addressing:
- [x] Video playback speed: H3 videos use 15 fps, however proper solution is to use value supplied by video decoder
- [x] Adventure map - scrolling speed
- [ ] Adventure map - hero movement speed
- [x] Adventure map - objects animation
- [x] Adventure map - fade-in / fade-out of objects
- [x] Adventure map - map reveal via Eye of the Magi
- [x] Adventure map - hourglass in infobox during enemy turn
- [x] Adventure map - new day animation
- [x] Town screen - buildings animation
- [x] Town screen - new building fade-in
- [x] Creature window - creature animation speed
- [x] Cursor - animation speed of spell selection cursor
- [x] Battles - all animations: All animations are time-based now but speed is likely different from H3

**Comment by dydzio0614** [comment]
heroes 3 Tides of War and WoG main menu screens have animated elements and they seem to be affected as well

**Comment by IvanSavenko** [comment]
Those fall under "video playback speed". This animation is a video file
