### ISSUE TITLE
add more hotkeys

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1382]
Currently still a lot of frequent actions can be done only with mouse. I suggest the following new hotkeys:

### town
- town hall (where buildings are purchased), especially since tavern already has T hotkey
- "purchase buildings" screen can also receive hotkeys, e.g. 1-7 keys to build/upgrade respective dwelling
- "buy all creatures"
- mage guild
- market
- switch to prev/next town, as an additional way here - mouse wheel when hovered on the town list

### adventure map
- choice dialogs (new level, arena, etc.) - left/right arrows

Ideally, all hotkeys should be configurable via json.

**Comment by kambala-decapitator** [comment]
in HD mod:
- `B` - market
- `G` - thieves' guild

**Comment by krs0** [comment]
Merged in https://github.com/vcmi/vcmi/issues/1834

Can be deleted!!
