### ISSUE TITLE
sleep hero state isn't restored on loading game

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1383]
steps:
1. set a hero as sleeping
2. save game
3. load game
4. the hero is awake

**Comment by Povelitelh3** [comment]
related https://bugs.vcmi.eu/view.php?id=1017

**Comment by Adriankhl** [comment]
I am trying to dig into this issue. In principle, it seems like the functionality should have been implemented - the `CPlayerInterface::serializeTempl` function should serialize and store the `sleepingHeroes` data. When I save a game, `CPlayerInterface::saveGame` is called to serialize something, but the counterpart `CPlayerInterface::loadGame` is not being called when I load the game. That's probably the cause of this issue.

However, I must say the binary serializer and the server-client architecture are somewhat cryptic to me so it is quite hard to narrow down the exact location of the problem. Is there anyone who are more familiar with these pieces of code?

**Comment by kambala-decapitator** [comment]
doesn't work in 1.5

**Comment by IvanSavenko** [comment]
Yeah, that PR got effectively reverted. Same goes to #797

**Comment by Laserlicht** [comment]
@IvanSavenko Would it be possible to fix this for 1.6?

Because this would fix multiple issues at once.

**Comment by IvanSavenko** [comment]
Not too much work, mostly a question of priorities.
Also not 100% about how to implement it. Considering several potential approaches, but not sure which one would be the best option.

Will add to my 1.6 todo list, but no promises for now.
