### ISSUE TITLE
Scholar spell transfer window oversized, can't dismiss it

### ISSUE THREAD

**Issue by lje** [vcmi/vcmi#1385]
**Describe the bug**
When a hero with a lot of learned spells transfers them to another hero by using the "Scholar" skill, a window with a list of transferred spells will be shown. If the transfer involves a lot of spells, the window will be larger than the screen, hiding the button at the bottom. At least on Android, there is now way to close this window and continue the game, meaning the player has to avoid the affected heroes from ever meeting.

**To Reproduce**
Have a hero with expert Scholar skill and a lot of spells (in my case coming from the Conflux Grail building). Have that hero meet another hero with at least advanced Wisdom skill but only a few known spells. This will trigger a transfer of a lot of spells.

**Expected behavior**
I'd like a scroll bar on the window or some other means of reaching the dismiss-button or closing it.

**Did it work earlier?**
No, it might even be a bug in the original game. I assume on PC versions the window can be closed by pressing Enter.

**Screenshots**
![Screenshot_20230106_222754_VCMI](https://user-images.githubusercontent.com/357743/211146271-6da226bd-c97b-4620-aa0f-2123420b56b0.png)

**Version**
 - OS: Android 13
 - Version: [VCMI-branch-develop-faccad7-a13dc5c.apk](https://builds.vcmi.download/branch/develop/Android/VCMI-branch-develop-faccad7-a13dc5c.apk) since VCMI 1.1.0 [doesn't work](https://github.com/vcmi/vcmi/issues/1286) on Android

**Comment by Alucard648** [comment]
Better use multiple sequentional windows for rendering transferring large number of spells. 7 spells per window so 8th icon is Scholarship SS icon.

**Comment by nullkiller** [comment]
Yes, well known bug. No workaround so far except moving saves to desktop and there Enter will work

**Comment by nullkiller** [comment]
Btw just restricting the number of spells to show might be a good temporary solution
