### ISSUE TITLE
advmap spell effect is propagated to units

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1403]
**Describe the bug**
when a hero casts an advmap spell, then it's visible on the units in a battle as well

**To Reproduce**
1. cast Fly
2. fight someone during this turn

**Expected behavior**
unit count bar is blue, Fly icon doesn't appear in unit details

**Actual behavior**
all units have yellow count bar (as if under negative spell) as well as Fly icon is visible in unit details

**Did it work earlier?**
no idea

**Screenshots**
![Screenshot 2023-01-10 at 10 40 11](https://user-images.githubusercontent.com/1557784/211496511-b2384ed4-2633-489e-b983-266d546e4223.png)

**Version**
 - OS: macOS Intel
 - Version: the latest develop

**Additional context**
Fly doesn't seem to have any effect on the units

**Comment by IvanSavenko** [comment]
Old bug: https://bugs.vcmi.eu/view.php?id=2290
