### ISSUE TITLE
Dragon Utopia obscures monster

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1405]
Dragon Utopia obscures a nearby monster 

![Screenshot 2023-01-10 at 13 36 56](https://user-images.githubusercontent.com/1557784/211543435-4c0d3e30-fdca-4b25-841b-de204396f874.png) ![Screenshot 2023-01-10 at 13 37 04](https://user-images.githubusercontent.com/1557784/211543439-d0e77d4a-1f2f-450e-8799-2b2d520a64b6.png)

Version: latest develop

**Comment by IvanSavenko** [comment]
And just in case - rechecked H3, where rendering order is indeed (mostly) correct:
(One obscured tile in right-most column)
So can confirm that this is bug with VCMI and not issue with Dragon Utopia .def file
![зображення](https://user-images.githubusercontent.com/1576820/211552321-5966c496-6bed-4262-9e44-ab2025fc5058.png)

**Comment by Povelitelh3** [comment]
related https://bugs.vcmi.eu/view.php?id=285

**Comment by IvanSavenko** [comment]
Should be fixed in #1581
