### ISSUE TITLE
Feature: conan instead of MXE (also build on Linux as before)

### ISSUE THREAD

**Issue by rilian-la-te** [vcmi/vcmi#1406]
**Describe your proposal**
Use Conan for cross-compile Windows VCMI on Linux hosts as now done for iOS on Mac hosts, use Ubuntu-provided mingw toolchain. 
Bump cmake version to 3.20 and use presets everywhere.
Drop old MXE builds.

**Additional context**
@IvanSavenko  @kambala-decapitator

**Comment by IvanSavenko** [comment]
Do we need 3.**20**?
Ubuntu 20.04 has 3.16: https://packages.ubuntu.com/focal/cmake
Debian stable has 3.18: https://packages.debian.org/bullseye/cmake

**Comment by rilian-la-te** [comment]
@IvanSavenko for CI - yes, becaue CMakePresets.json version 2 requires CMake 3.20 (https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html). Without presets - I do not think so. So, I propose to use Conan for building VCMI windows binaries on Ubuntu 22.04 instead on now-dead MXE.

**Comment by IvanSavenko** [comment]
Ah, okay then. It seems that github's CMake is good enough even on Ubuntu-20.04 (3.25 according to logs).
So as long as non-preset builds are still possible on 3.16 I am fine with this.

By the way, since you're clearly know more than I do - is it possible to setup mingw + conan on Windows CI host instead of cross-compile? 
If yes it can also serve as test of potential non-msvc based setup for Windows development.

**Comment by rilian-la-te** [comment]
@IvanSavenko yes, and even easier than on Linux hosts) But my personal preference is than all development is easier on Linux, and we already have MSVC for windows devs - Linux devs will be glad to have a way to build and test Windows VCMI without Windows itself, so, for me Linux host is preferred.

**Comment by IvanSavenko** [comment]
Well, if it that easy then perhaps set up both then? It is not like we pay for Github CI.
Extra bonus is that if one of them won't be suitable for some reason we can remove it and still keep mingw CI.

I do agree that Linux has more comfortable setup for development (even though VS is an amazing IDE). But at least personally have no need to setup Windows builds on my machine - if I need Windows build I can use CI artifacts.

**Comment by rilian-la-te** [comment]
@IvanSavenko we can, if we have some time (I do not, sorry((( ), about removal - it is not good.

About VS - it is a holy war (I honestly do not like it at all), about artifacts - it is unusable for checking local branches. 

Agree, we can do both, it is only a matter of 2 conan profiles and build presets instead of one.

**Comment by rilian-la-te** [comment]
Closed as completed via #1498
