### ISSUE TITLE
Statue of Legion growth display issue

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1410]
should be +50 **%**, but even better is to display flat value, which would be (1+1) * 50% = 1 in this case

![Screenshot 2023-01-11 at 04 49 57](https://user-images.githubusercontent.com/1557784/211706341-ad4c4995-5403-4aef-8d4d-2286f1a412f7.png)

**Comment by krs0** [comment]
Yeh, just display as: **Statue of Legion +1** and explain the formula on Statue of Legion artifact description.

**Comment by DjWarmonger** [comment]
> Yeh, just display as: **Statue of Legion +1** and explain the formula on Statue of Legion artifact description.

It used to work correctly first time it was implemented.
