### ISSUE TITLE
all "bring artifact" quests say "defeat <artifact>"

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1411]
![Screenshot 2023-01-11 at 07 29 21](https://user-images.githubusercontent.com/1557784/211718470-503e46ca-a0a6-48a9-9431-bd263ab038e1.png)

**Comment by IvanSavenko** [comment]
Yeah, "off-by-one" error with quest texts, will be fixed as part of another PR later today.
