### ISSUE TITLE
strange flying path choice

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1412]
This is a Fortress hero, he has Angel Wings. Why not a straight path was chosen?

![Screenshot 2023-01-11 at 07 54 03](https://user-images.githubusercontent.com/1557784/211721523-76d21cd1-bb6a-4048-915a-c97ca6012043.png)

maybe related to https://bugs.vcmi.eu/view.php?id=2650?

**Comment by kambala-decapitator** [comment]
might be correct, I don't understand much in terrains and their penalties. https://heroes.thelazy.net/index.php/Fly

**Comment by IvanSavenko** [comment]
Looks like Angel Wings is broken.
thelazy: Angel Wings - gives expert Fly while equipped.
vcmi:  type" : "FLYING_MOVEMENT", "val" : 0, 

It looks like Angel Wings in vcmi give Fly on the same level as without Air magic (instead of Expert)

**Comment by kambala-decapitator** [comment]
looks like expert Fly itself (I mean the spell) is broken or there's a bug in path finder: either with wings or via spell VCMI offers the following path

![Screenshot 2023-01-21 at 18 25 11](https://user-images.githubusercontent.com/1557784/213874490-c562fba3-ff38-47be-b968-5efcd461c473.png)

while oh3 correctly offers straight path.

test map: [angel-wings.h3m.zip](https://github.com/vcmi/vcmi/files/10472457/angel-wings.h3m.zip) Hero has Wings equipped and also has expert Fly.

**Comment by dydzio0614** [comment]
there is pathfinder bug

**Comment by kambala-decapitator** [comment]
my calculations were wrong: they didn't take into account capturing the chest. The last "capture" move requires 100 for fly and 40 for road making the non-fly option better, so VCMI is correct here (also checked cost with hd mod). And oh3 actually has some calculation bug which is easy to see in the video:

https://user-images.githubusercontent.com/1557784/215260349-c3323bdd-a54f-477b-8438-2186c59d51aa.mov

need to prepare a better test map.

**Comment by kambala-decapitator** [comment]
any idea what could be so special about the next tile? straight path is definitely the best.

![Screenshot 2023-01-28 at 15 09 41](https://user-images.githubusercontent.com/1557784/215265959-ee2ec4c3-f740-4ec1-95a9-b81eb4c0639c.png) ![Screenshot 2023-01-28 at 15 09 58](https://user-images.githubusercontent.com/1557784/215265966-fec48582-d957-4605-b69a-cf41fe5d5648.png)

**Comment by dydzio0614** [comment]
I repeat - there is bug :P
just see TODO in pathfinder code

**Comment by kambala-decapitator** [comment]
> just see TODO in pathfinder code

thanks, at least now it's clear where to look in
