### ISSUE TITLE
glitched movement range and path display for flying hero

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1413]
Had this in develop / 1.1 / 1.0

![Screenshot 2023-01-11 at 08 20 18](https://user-images.githubusercontent.com/1557784/211724365-61e219ac-824a-4efd-89e6-f4df72e49905.png)

https://bugs.vcmi.eu/view.php?id=3128

**Comment by IvanSavenko** [comment]
But this *is* the most optimal path to reach your destination 🤣

**Comment by kambala-decapitator** [comment]
true :) but green arrow is definitely wrong.

**Comment by IvanSavenko** [comment]
I doubt that H3 has arrows for U-turn. So should probably block pathfinder from revisiting tiles

**Comment by kambala-decapitator** [comment]
more examples:

![Screenshot 2023-01-14 at 11 03 47](https://user-images.githubusercontent.com/1557784/212463520-9b357366-dbab-44fb-a6a8-5e21635f7018.png) ![Screenshot 2023-01-14 at 11 13 12](https://user-images.githubusercontent.com/1557784/212463521-a5b7bfc6-627b-4d5c-84f5-1617312c1a5b.png)

no strange bottom arrow in the second case

**Comment by kambala-decapitator** [comment]
SS from oh3:
![Screenshot 2023-01-15 at 17 12 57](https://user-images.githubusercontent.com/1557784/212546027-e2e69fc0-0988-4149-8ab5-40dfa2884f37.png)

**Comment by kambala-decapitator** [comment]
another example:

![Screenshot 2023-01-16 at 14 18 48](https://user-images.githubusercontent.com/1557784/212700837-254ce2e6-a143-466f-b231-d9cf81d76fb8.png)

Titans block the road, without Fly hero needs to take a detour. Going to the tile to the left of destination would initiate battle, to the right - no arrows visual bug.
