### ISSUE TITLE
Tactics buttons don't have text

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1414]
Tactics itself work fine, just button text is missing

![Screenshot 2023-01-11 at 09 09 11](https://user-images.githubusercontent.com/1557784/211731733-506531ae-eb2e-46d2-8d6c-2eaab685f20f.png)

version: develop from 1 day ago

**Comment by kambala-decapitator** [comment]
@IvanSavenko was it maybe also fixed by #1404?

**Comment by IvanSavenko** [comment]
Not related to #1404 - text on these buttons is pre-rendered and is not managed by the game.
Looks like rendering order issue. Will check it out.
