### ISSUE TITLE
"boat" cursor image has quite big offset

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1415]
on the video it's clearly seen where the actual cursor is compared to the boat image

https://user-images.githubusercontent.com/1557784/211740299-09b39f67-81a7-4fd5-9a89-f60105b309d1.mov

This is develop version. Don't remember how it was in 1.1 / 1.0.

**Comment by IvanSavenko** [comment]
Rechecked and fixed offsets of all in-game cursors in PR #1374 , for both hardware & software cursors
