### ISSUE TITLE
unit's movement range not displayed on hover

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1418]
**Describe the bug**
On rare occasions hovering a unit doesn't display its movement range

**To Reproduce**
No reliable steps. However, based on situations it seems that standing near (or on top of) a corpse is involved.

**Expected behavior**
Unit's movement range is always displayed

**Actual behavior**
Sometimes unit's movement range isn't displayed

**Did it work earlier?**
First noticed while testing #1229, can't say if it occurs in 1.1

**Screenshots**
video of first time I stumbled on it: https://github.com/vcmi/vcmi/pull/1229#issuecomment-1371968280

reproduced once more with today's develop build:

https://user-images.githubusercontent.com/1557784/211804632-b5c486fc-e424-4020-866e-691baf4d21a7.mov

actual range of Behemoths:

![Screenshot 2023-01-11 at 13 03 23](https://user-images.githubusercontent.com/1557784/211804787-c74f0304-e8eb-4e33-8eeb-4fb7f98da05e.png)

**Version**
 - OS: macOS Intel
 - Version: today's develop

**Additional context**
In the first video Swordsmen are standing next to Cavalier's corpse.

In the second one the 43 Giants are standing on a corpse of a Giant. There're also Basilisks behind Begemoths. If you'd like the [save game](https://github.com/vcmi/vcmi/files/10390627/Archive.tar.gz): attack Giants standing near the Library of Enlightenment with the first hero.

**Comment by IvanSavenko** [comment]
Could be related to having corpse on the same tile?

**Comment by kambala-decapitator** [comment]
> Could be related to having corpse on the same tile?

could be.

btw just noticed on the video that for Behemoths correct range is displayed (at first I thought they're also affected), and they're definitely not standing on a corpse.

**Comment by kambala-decapitator** [comment]
reproduced again, Pegasi are standing on a corpse


https://user-images.githubusercontent.com/1557784/212533448-07ce682e-85c7-4802-9a77-a6a14011424b.mov
