### ISSUE TITLE
show unit's real movement range in Tactics phase

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1420]
Currently in Tactics phase only available Tactics movement is shown

**Comment by IvanSavenko** [comment]
@krs0 Fixed I think?

**Comment by krs0** [comment]
Did not knew there was an issue :)

Yes fixed in develop by https://github.com/vcmi/vcmi/pull/1874

![image](https://user-images.githubusercontent.com/15194321/231273185-f8952ff0-2fc1-4bba-b394-3712763c0634.png)

**Comment by IvanSavenko** [comment]
Wasn't aware of it either - just going through old stuff

**Comment by krs0** [comment]
https://github.com/vcmi/vcmi/issues/1666
