### ISSUE TITLE
View Air/Earth spells have reversed icons

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1441]
![Screenshot 2023-01-16 at 13 52 56](https://user-images.githubusercontent.com/1557784/212663145-ecc2f71d-4c90-4d99-a252-4e5b0bd44049.png)

https://bugs.vcmi.eu/view.php?id=2382

**Comment by Povelitelh3** [comment]
It's bug from original h3 ^^
like sulfur in nagabank and many other

**Comment by kambala-decapitator** [comment]
would be good to fix anyway
