### ISSUE TITLE
Rust Dragon doesn't have Breath ability

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1447]
it hits only 1 hex instead of 2. Tested by hitting 2 units standing in a straight line as well as diagonally (video for the latter):

https://user-images.githubusercontent.com/1557784/212760990-7a944803-dea4-452d-adf6-54893a5c5d3c.mov

can't say if it worked before

**Comment by IvanSavenko** [comment]
develop or beta/1.1?

**Comment by kambala-decapitator** [comment]
develop

**Comment by kambala-decapitator** [comment]
https://bugs.vcmi.eu/view.php?id=2886 was fixed some years ago in #418, seems broke again

**Comment by kambala-decapitator** [comment]
works in 1.1

**Comment by kambala-decapitator** [comment]
test map: [rust.vmap.zip](https://github.com/vcmi/vcmi/files/10435483/rust.vmap.zip)

use hot seat to place units in a row
