### ISSUE TITLE
unit numbers over 1000 are displayed in short form in battle

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1448]
e.g. 1k instead of 1045, creature details shows full number though. I don't think it's wise to do so and it differs from oh3 behavior. Could be a toggleable option.

![Screenshot 2023-01-16 at 14 32 06](https://user-images.githubusercontent.com/1557784/212761406-f8f1f59d-7736-43c1-8af9-4956fdcd6bb4.png)
![Screenshot 2023-01-16 at 14 35 12](https://user-images.githubusercontent.com/1557784/212761422-7f8e3f19-5960-43ef-a478-90f27f95b9aa.png)

**Comment by IvanSavenko** [comment]
Due to size of that label, using such form makes sense for numbers over 10 000 (and needed for numbers over 100 000). 

Definitely not needed for 1000 though. There is a huge difference between stack of 1000 and 1999 units.

**Comment by kambala-decapitator** [comment]
btw I haven't seen numbers >= 1100. If they say `1.1k`, then no fix needed.

**Comment by DjWarmonger** [comment]
This was added just exactly because stacks can get very large (easily in 5 digits) and VCMI has to support it all the way to 32-bit capacity (2 billlions+).

I agree that something like `1.1k` would be ok - just keep it down to 4 digits.

**Comment by Alucard648** [comment]
What about expanding label size accordingly to fit number, if it exceeds 99999? And turn order label can easily fit 7 digit number, so shortcomings are needed, if there are 10M creatures in single stack.

**Comment by DjWarmonger** [comment]
I'm afraid that displaying 7 digits would be actually less readable than just a short string. It's really not that important if the opponent has 1459836 or 1459386 units...

**Comment by kambala-decapitator** [comment]
what do you think about:
- for 1000 <= n <= 9999 display 1 digit from the fractional part, or even just the raw number
- for n >= 10000 no fractions (i.e. use current approach)
- for n < 1000 display full number

**Comment by IvanSavenko** [comment]
I also prefer this approach ^
for 1000 <= n <= 9999 we should display full number instead of fractions

**Comment by kambala-decapitator** [comment]
seems good?
![Screenshot 2023-01-20 at 20 05 01](https://user-images.githubusercontent.com/1557784/213760538-a444b499-3bcd-4d1b-b26a-90550f61b757.png)

discovered another place that requires shortening:
![Screenshot 2023-01-20 at 20 05 52](https://user-images.githubusercontent.com/1557784/213760588-f1bf705b-cfbc-41bd-b3bd-1f92770ee34f.png)

**Comment by IvanSavenko** [comment]
Looks good to me
