### ISSUE TITLE
town window becomes non-modal after buying a building

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1464]
**Describe the bug**
After buying a building, you can interact with the list of towns of the advmap.

**To Reproduce**
1. buy a building
2. click on a town from the advmap's list
3. the town is selected on advmap (camera shifts), currently opened town doesn't change

**Expected behavior**
click outside of town window is ignored

**Actual behavior**
the click is not ignored

**Did it work earlier?**
iirc same in 1.1

**Screenshots**

https://user-images.githubusercontent.com/1557784/213227916-7b444a89-c84e-4516-8a5c-21eb217afaea.mov

**Version**
 - OS: macOS Intel
 - Version: develop

**Additional context**
If you simply open town window and try to click on a town from the advmap's list, then nothing happens (which is correct)

**Comment by misiokles** [comment]
If such click outside window shows Tower townscreen - it's very usefull and comfortable option.

**Comment by IvanSavenko** [comment]
Looks to be general bug when adventure map gets reactivated somehow
I think this is the same bug: https://bugs.vcmi.eu/view.php?id=3052
(broken UI after scenario restart which @dydzio0614 reported could also be the same one as this)

Good to have steps to reproduce though

**Comment by kambala-decapitator** [comment]
> If such click outside window shows Tower townscreen - it's very usefull and comfortable option.

no it's not, as you can see from the video and step 3
