### ISSUE TITLE
Leadership morale string not displayed

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1479]
latest develop

![Screenshot 2023-01-21 at 12 54 13](https://user-images.githubusercontent.com/1557784/213861775-f3c0e248-5b93-451d-96a8-629e5339bb32.png)

**Comment by misiokles** [comment]
![image](https://user-images.githubusercontent.com/29593042/213863031-6af75b71-fac9-4689-8e73-62a4ea745150.png)
The same with map dwellings from mods.

**Comment by misiokles** [comment]
Artifacts description strings are missing too.
![image](https://user-images.githubusercontent.com/29593042/213863100-0081421a-7298-461f-885b-56738f377168.png)

**Comment by IvanSavenko** [comment]
@misiokles 
dwellings - fixed in #1466 
artifacts - looking into it, will fix
