### ISSUE TITLE
army morale calculation differs from oh3

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1480]
same in 1.1 and develop

map: [morale.h3m.zip](https://github.com/vcmi/vcmi/files/10471970/morale.h3m.zip)

oh3:
![Screenshot 2023-01-21 at 13 18 14](https://user-images.githubusercontent.com/1557784/213862932-f6facf2e-ef1e-4ef0-b6b4-b68f2c971a77.png)

vcmi:
![Screenshot 2023-01-21 at 13 16 30](https://user-images.githubusercontent.com/1557784/213862938-00a3d26b-59be-4f39-aa8a-701ff4f7ce62.png)

**Comment by dydzio0614** [comment]
hmm wtf... i am pretty sure it should be as in lower screen...

**Comment by kambala-decapitator** [comment]
I'm also puzzled

**Comment by kambala-decapitator** [comment]
btw the hero had Leadership by default, I deleted it in the oh3 editor

**Comment by krs0** [comment]
Poor screenshots....

What is the problem exactly? 4 factions -2 morale. 

![image](https://user-images.githubusercontent.com/15194321/213882622-73134ebf-fc35-48aa-b0e6-13776959a080.png)

From https://homm-utopia.com/en/guides/morale-guide/

**Comment by IvanSavenko** [comment]
@krs0  Apparently, H3 does not shows effect of factions number on morale in hero window, I think H3 shows it only in creature stats.

Should be kept as it IMO. Other than broken text that is 
1) clipped
2) is different from H3, where I think it says "Troops from X alignments" in this case

**Comment by kambala-decapitator** [comment]
> we do not see hero moral modifiers

zero, you can check the test map

> Apparently, H3 does not shows effect of factions number on morale in hero window, I think H3 shows it only in creature stats.

btw in battle it also shows the neutral icon in hero stats

> clipped

there's a dedicated issue for that

**Comment by kambala-decapitator** [comment]
yes, looks like h3 bug, as even adding undead to the army still shows neutral morale. However, creature stats shows correct morale icon.

![Screenshot 2023-01-22 at 11 58 24](https://user-images.githubusercontent.com/1557784/213907950-34a19ced-19ce-47b0-befa-80dbab137148.png)

**Comment by kambala-decapitator** [comment]
> is different from H3, where I think it says "Troops from X alignments" in this case

yes, correct
