### ISSUE TITLE
RMG doesn't place all possible objects

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1482]
I'm not quite sure if it's a bug (maybe templates are fully responsible for available objects), but I've never seen Abandoned Mine / Whirlpool / One-Way Monolith on random maps so far.

**Comment by DjWarmonger** [comment]
This is correct, original RMG didn't have them either and we want to preserve its balance. Besides, we don't quite know the rules for placing such objects.

**Comment by kambala-decapitator** [comment]
thank you for the confirmation
