### ISSUE TITLE
[feature] show current battle losses

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1490]
could be a separate dialog (if impossible to fit on the battle screen) showing initial and dead count for each unit for both sides, e.g. `5 / 20` meaning 5 dead, initial 20. Could use small unit icons like those on the "battle finished" screen.

**Comment by Alucard648** [comment]
It`s also needed for bonuses like "disintegration" that directly affect initial creature count.

**Comment by IvanSavenko** [comment]
I think easiest way is to display that in creature info box that pops up to the sides of screen (not implemented in vcmi right now)

**Comment by Laserlicht** [comment]
included in #3366
