### ISSUE TITLE
Two-hex creature spellcaster should have only one hex darkened on mouse hover after pressing F button for casting mode

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#1503]
**Describe the bug**
When two hex unit is caster in battle, toggling casting mode (F keyboard button) should change mouse-hovered highlight mode to one hex

**To Reproduce**
1. Use vcmiainur cheat to get some archangels in army
2. Start any battle
3. Toggle on hex highlighting stuff in battle setting etc.
4. Press F during archangel's turn
5. Two hexes are still highlighted, which is good for movement logic but normal spell target is one hex in general

**Expected behavior**
One hex under cursor is highlighted in F mode

**Actual behavior**
Two hexes are highlighted

**Did it work earlier?**
I dont remember

**Screenshots**
![obraz](https://user-images.githubusercontent.com/9436577/214067069-34c933d5-2ba3-4389-884e-8411608ae78f.png)

**Version**
 - OS: Kubuntu 22.04
 - Version: current develop

**Comment by kambala-decapitator** [comment]
yeah, also noticed that in develop
