### ISSUE TITLE
[Launcher] Sort mods by type - language independent

### ISSUE THREAD

**Issue by heroesiiifan** [vcmi/vcmi#1526]
**Describe the bug**
Only a small thing: Better sorting of the mods.

**To Reproduce**
Change language (e.g. german)

**Expected behavior**
Mods of the same category should be sorted together, independent from language.
Use for sorting the english language.

**Actual behavior**
![grafik](https://user-images.githubusercontent.com/77574150/215590384-3133dc03-e633-45b0-a9d4-fa919f42673b.png)

**Did it work earlier?**
Localization is a new feature

**Comment by DjWarmonger** [comment]
I agree, with so many mods it gets out of hand.

However, these "categories" are not restricted or normalized, so anyone can type in this field whatever one pleases and it will slip trough sorting. We could think aboout defining a limited set of possible categories.

**Comment by IvanSavenko** [comment]
Yeah, we should probably switch to a fixed set of categories.
And also add "other" category for anything that won't fit into existing ones.

**Comment by heroesiiifan** [comment]
Yes, I think fixed categories would be a better solution.
