### ISSUE TITLE
RFC: Reduce boost usage and bump min compiler version

### ISSUE THREAD

**Issue by rilian-la-te** [vcmi/vcmi#1538]
**Describe your proposal**
In extreme - remove Boost dependency. And make possible to play video without ffmpeg (at lease on Windows).

**Additional context**
I want a collection of opinions about this change (bump CXX_STANDARD to 17 or 20, check GCC and Clang version at least to GCC10 and clang maybe 11, and try to remove boost usage. But there is a problem - MSVC stdlib is much worse than libstdc++ or libc++.

**Comment by IvanSavenko** [comment]
Potential requirements change from my point of view:
- only up to c++17 (and without filesystem - macos limitation according to @kambala-decapitator )
- gcc version: up to 9.3 (Ubuntu-20.04)
- clang version: up to 10.0 preferably, higher version might be OK if this gives us something
- reduce boost usage - OK
- msvc stdlib - don't expect issues with c++17

**Comment by rilian-la-te** [comment]
@IvanSavenko What is a limitation on MacOS? @kambala-decapitator can you explain?

Ubuntu 20.04 can compile with clang AFAIK, there is clang 10.0.

**Comment by IvanSavenko** [comment]
@rilian-la-te 
Filesystem: search for "filesystem" on slack, not sure if link would work: https://app.slack.com/client/T2JA4F4CX/C2J9QFUDS/thread/C2J9QFUDS-1673940613.469879

Compiling with clang on Ubuntu would certainly work, but I'd prefer to use default compiler. gcc 9 should also have complete or almost complete c++17 support, so don't see problems here.

And if we want to even consider upgrading codebase to c++20 standard, I think we should first adopt c++11... We use boost even for features that were added back in c++11. More than enough stuff to do as it is.

**Comment by rilian-la-te** [comment]
@IvanSavenko we request c++14 in CMake. So, we can safely use feature from C++14 in any code. I think than after https://github.com/vcmi/vcmi/pull/1535 is good move to remove some boost features which present in C++11.

**Comment by kambala-decapitator** [comment]
> And make possible to play video without ffmpeg (at lease on Windows).

what would you use for that? platform code?

> @IvanSavenko What is a limitation on MacOS? @kambala-decapitator can you explain?

every macOS and iOS version have system libc++ that can't be updated by user at random time (possible only with OS update). while current deployment targets (min OS version where app can run, we have macOS 10.13 and iOS 12 and I don't wish to change that) allow most of C++17 usage, the filesystem library is available only since macOS 10.15 and iOS 13.

other platforms can use `std::filesystem` if desired, then it would be just a matter of a proper `using` expression.

**Comment by rilian-la-te** [comment]
@IvanSavenko this lib: https://github.com/ihhub/fheroes2/tree/master/src/thirdparty/libsmacker

1. Why? (With boost fallbacks on MacOS sometimes)?
2. Agree
3. I think first is better
4. Agree
5. Agree
6. About asio (not high-priority) - maybe use this (https://github.com/skypjack/uvw)? About program_options - I do not know alternatives yet (only getopt_long or GLib one, but this is pure C and Linux specific. I am a Linux programmer after all)
7. Maybe, if we want better stacktraces without gdb attach.

**Comment by kambala-decapitator** [comment]
> program_options

there're plenty of alternatives, see e.g. https://github.com/fffaraz/awesome-cpp#cli

**Comment by IvanSavenko** [comment]
@rilian-la-te from what I see, libsmacker only handles .smk files? H3 also uses .bik video's. And while *some* versions of H3 have both .smk and .bik files, some only have one or another. So we can't use something that only supports .smk

@kambala-decapitator 
I am not against replacing asio or program options, but don't see what it gives us other than replacing boost dependency with another one. If somebody want to do it - sure, but don't see any need to change it. Especially when we have quite long list of more important stuff.

**Comment by Laserlicht** [comment]
> @rilian-la-te from what I see, libsmacker only handles .smk files? H3 also uses .bik video's. And while _some_ versions of H3 have both .smk and .bik files, some only have one or another. So we can't use something that only supports .smk

Maybe additionally [libbinkdec](http://homepage.eircom.net/~duncandsl/avp/) (see "Compiling the source code"->"Requirements")? Some open-source projects seem to use it.

**Comment by IvanSavenko** [comment]
I think that library won't work. H3 uses some weird, very old version of bink video format, which most decoders don't support. Even ffmpeg added support for it way later than other bink types.
From your link:
```
	// check the file signature
	signature = file.ReadUint32BE();
	if ((signature != kBIKfID) 
		&& (signature != kBIKgID)
		&& (signature != kBIKhID)
		&& (signature != kBIKiID))
	{
		BinkCommon::LogError("Unknown Bink signature");
		return false;
	}
```
Problem is, signature of H3 .bik file I have is `BIKb`, so it will not work with this lib.

**Comment by Laserlicht** [comment]
> I think that library won't work. H3 uses some weird, very old version of bink video format, which most decoders don't support. Even ffmpeg added support for it way later than other bink types. From your link:

Okay, too bad. I thought that since the library is derived from ffmpeg, it would work. But is also a somewhat older version.

**Comment by IvanSavenko** [comment]
> Maybe this one? (kBIKbID is included here) https://github.com/xoreos/xoreos/blob/master/src/video/bink.cpp

And only usage of kBIKbID is this one:
```
	if ((id == kBIKbID) || (id == kBIKkID))
		throw Common::Exception("Untested Bink version %s", Common::debugTag(id).c_str());
```
Besides, personally see no reason to replace ffmpeg which completely covers our needs
