### ISSUE TITLE
[vcmi 1.1.1] Launcher layout is broken on macOS

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1556]
1) there is no button to hide additional info (reproduced on develop only)
2) icons/size columns are corrupted (reproduced on both develop and vcmi-1.1.1)

<img width="989" alt="Снимок экрана 2023-02-05 в 02 58 57" src="https://user-images.githubusercontent.com/9308612/216793099-65601147-e0b6-42ff-956e-19e7e202d3e2.png">

**Comment by IvanSavenko** [comment]
> 1. there is no button to hide additional info (reproduced on develop only)

Deliberate. Multiple reports from players who could not find a button to show info.

> 2. icons/size columns are corrupted (reproduced on both develop and vcmi-1.1.1)

OK, will fix. Looks like icons have some sort of offset/margin on the left side.

**Comment by Nordsoft91** [comment]
Reproduced in 1.1

**Comment by Nordsoft91** [comment]
>who could not find a button to show info.

Suggest to think on better solution (making button bigger with icon for instance)

**Comment by DjWarmonger** [comment]
I suppose that the column size could be the result of hiogh-DPI scaling, while default sizes are hardcoded. At least I've got these with 150% scaling.

However, the Launcher should remember column widths once you stretch them manually.
