### ISSUE TITLE
Flatpak "Update runtime to version 6.4" result in hang with black screen on start

### ISSUE THREAD

**Issue by powerman** [vcmi/vcmi#1564]
**Describe the bug**
I'm using Debian 11 with Cinnamon and NVidia GeForce GTX 1060 with nvidia-driver, VCMI installed using Flatpak.
Few days ago after auto-update VCMI became broken: after clicking "start" button in addon manager window I get black screen.
Downgrade to previous flatpak commit "Update 1.1.0.tar.gz to 1.1.1" fixed the issue.

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/10702758/VCMI_Client_log.txt)
Console output:
```
murzik@chaoshouse:~/ > flatpak run eu.vcmi.VCMI 
QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
Gtk-Message: 02:23:23.817: Failed to load module "xapp-gtk3-module"
Qt: Session management error: None of the authentication protocols specified are supported
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_comboBoxPlayerAI_currentIndexChanged(QString)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_comboBoxFriendlyAI_currentIndexChanged(QString)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_comboBoxNeutralAI_currentIndexChanged(QString)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_comboBoxEnemyAI_currentIndexChanged(QString)

Starting game with the arguments: 
murzik@chaoshouse:~/ > 
murzik@chaoshouse:~/ > Starting... 
VCMI 1.1.1 (client)
Creating console and configuring logger: 0 ms
The log file will be saved to "/home/murzik/.var/app/eu.vcmi.VCMI/cache/vcmi/VCMI_Client_log.txt"
	Initialization: 3 ms
	Data loading: 31 ms
	Mod handler: 0 ms
	Mod filesystems: 13 ms
Basic initialization: 47 ms
Initialized logging system based on settings successfully.
[log level] ai => not set
[log level] animation => not set
[log level] bonus => not set
[log level] global => trace
[log level] mod => not set
[log level] network => not set
Error: campaign movies was not found!
Error: campaign music was not found!
Loading settings: 49 ms
Found 3 render drivers
	opengl (active)
	opengles2
	software
Check display mode: requested 800 x 600; available up to 1920 x 1200 
Set logical rendering resolution to 800x600
Created renderer opengl
	Initializing screen: 63 ms
	Initializing video: 0 ms
Initializing screen and sound handling: 1 ms
		 Bonus type handler: 1 ms
		 Terrain handler: 0 ms
		 General text handler: 7 ms
		 Hero handler: 0 ms
		 Artifact handler: 0 ms
		 Creature handler: 0 ms
		 Town handler: 0 ms
		 Object handler: 0 ms
		 Object types information handler: 0 ms
		 Spell handler: 0 ms
		 Skill handler: 0 ms
		 Terrain view pattern handler: 3 ms
		 Template handler: 0 ms
		 Battlefields handler: 0 ms
		 Obstacles handler: 0 ms
	Initializing handlers: 13 ms
	Initializing content handler: 0 ms
		[2d9cc6da]Original game files
		[83c0b9d1]VCMI essential files
	Parsing mod data: 385 ms
		[SKIP] Original game files
		[SKIP] VCMI essential files
	Loading mod data: 74 ms
	Resolving identifiers: 14 ms
No templates found for 38:1
No templates found for 49:1
No templates found for 79:7
No templates found for 90:1
No templates found for 100:1
No templates found for 103:1
No templates found for 113:1
No templates found for 172:0
No templates found for 186:0
No templates found for 189:0
	Handlers post-load finalization: 11 ms 
	All game content loaded in 486 ms
Initializing VCMI_Lib: 499 ms

murzik@chaoshouse:~/ > 
```

**To Reproduce**
1. Update to latest flatpak commit (0ca50f20c392e68077e6800eb50bd684b167e8c4096fc7b21d9be34dcdf8a6be).
2. `flatpak run eu.vcmi.VCMI`
3. Click on 'Start game'
4. See black screen

**Expected behavior**
Game should work.

**Actual behavior**
I get black screen instead of game.

**Did it work earlier?**
Yes, previous flatpak commit (ebd618bfc5c59cff7c41b3985cdc667864b30f9267b167aab26ad349ceef01c5) works just fine.

**Version**
 - OS: Debian Linux 11
 - Version: VCMI 1.1.1

**Comment by IvanSavenko** [comment]
@powerman Can you try opening settings in Launcher (aka "addon manager") and toggling "show intro" to "off"?

@Alexander-Wilms any ideas what has changed?

**Comment by Alexander-Wilms** [comment]
All the dependencies in the KDE runtime were updated. I'll revert it for now and try to investigate it.

See also https://github.com/flathub/eu.vcmi.VCMI/issues/108

**Comment by rilian-la-te** [comment]
It seems than ffmpeg in this runtime is 5.0.2.
In previous runtime it was 4.3.3

We need to look why VCMI is not working correctly on ffmpeg 5.0 (while it was when I first submitted ffmpeg/5.0 support).

**Comment by powerman** [comment]
> @powerman Can you try opening settings in Launcher (aka "addon manager") and toggling "show intro" to "off"?

Thanks, this solves the issue!

It may worth to note while "show intro" previous was set to "on" I never actually seen the intro - maybe because it somehow wasn't copied from original game resources or maybe because of some other bug.

P.S. It looks like you may have something else to do related to this issue, so I'll leave it open for now, but feel free to close anytime.

**Comment by powerman** [comment]
One more issue on latest flatpak version: it hangs when I'm trying to enter Tavern. This happens on any map, including old saves, without any extra mods. Previous flatpak version doesn't have this issue.

**Comment by powerman** [comment]
I'm not 100% sure, but I believe last time I've seen video working was on vcmi-0.99+dfsg+git20190113.f06c8a87-2+b1 (standard Debian 11 package).
Since I've switch to flatpak/vcmi-1.x there was no video (but until latest flatpak version it wasn't hang).
```
$ ls -l ~/.local/share/vcmi/Data/VIDEO.VID 
-rw-r--r-- 1 murzik murzik 25592444 Sep 24  2018 /home/murzik/.local/share/vcmi/Data/VIDEO.VID
$ md5sum ~/.local/share/vcmi/Data/VIDEO.VID 
3ed4d0e3c9c2435129c8383464ca77d4  /home/murzik/.local/share/vcmi/Data/VIDEO.VID
```

**Comment by powerman** [comment]
Actually, looks like file shown in previous comment was from debian package, but flatpak file is the same:
```
$ ls -l ~/.var/app/eu.vcmi.VCMI/data/vcmi/Data/VIDEO.VID 
-rw-r--r-- 1 murzik murzik 25592444 Jan  4 18:30 /home/murzik/.var/app/eu.vcmi.VCMI/data/vcmi/Data/VIDEO.VID
$ md5sum ~/.var/app/eu.vcmi.VCMI/data/vcmi/Data/VIDEO.VID
3ed4d0e3c9c2435129c8383464ca77d4  /home/murzik/.var/app/eu.vcmi.VCMI/data/vcmi/Data/VIDEO.VID
```

**Comment by rilian-la-te** [comment]
This file is from your H3 data, not from flatpak or debian installation of VCMI.

**Comment by powerman** [comment]
Yes, I know. I listed it just in case there is some problem with file itself.
