### ISSUE TITLE
After campaign has been completed player is kicked to main menu

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1565]
**Describe the bug**
After capturing the 7th tower in Griffin Cliff mission, I get the small text dialog that I won, but then am thrown out into the main menu (load game submenu)

**Game logs**
[mission-complete-vcmi-logs.zip](https://github.com/vcmi/vcmi/files/10704479/mission-complete-vcmi-logs.zip)

**To Reproduce**
1. Start any H3 (non-custom) campaign
2. Complete campaign, e.g. via instant-win cheat.

**Expected behavior**
Game returns to campaign selection screen. Completed campaign is marked with greek checkmark

**Actual behavior**
Game returns to main menu

**Did it work earlier?**
No

**Version**
 - OS: macOS
 - Version: 1.1.1 release

**Additional context**
- originally reported in https://forum.vcmi.eu/t/victory-in-a-campaign-mission-exits-into-main-menu/

**Comment by nullkiller** [comment]
Griffin Cliff is the third and last scenario of the campaign [Long Live the Queen](https://mightandmagic.fandom.com/wiki/Long_Live_the_Queen)
So yes our engine works this way for now. All campaigns are open by default and there is no link between them. This is a deviation from original HoMM3.

**Comment by misiokles** [comment]
There's no link between campaigns in original H3. Game says that our heroes will move to other campaigns, but it's not true. In last campaign 'our' heroes are renerated with random stats and skills.

**Comment by IvanSavenko** [comment]
Updated issue with more relevant info
