### ISSUE TITLE
Network code is too ugly

### ISSUE THREAD

**Issue by heretic13** [vcmi/vcmi#1578]
Hello.
I review your network code periodically.
For several years, it has remained virtually unchanged.
He's too ugly.

Remember one simple rule. If you are using boost::asio, there should be no mutexes in your code!!!
This greatly simplifies programming.

My recommendation: rewrite the netcode correctly!

**Comment by kambala-decapitator** [comment]
it would be great if you could make a PR for that

**Comment by heretic13** [comment]
> it would be great if you could make a PR for that
Возможно в будущем я так и сделаю. 

Пока могу только советами помочь.

**Comment by IvanSavenko** [comment]
*checks todo list*
I think I might find some time for this... next year perhaps?

Yes, VCMI code is far from high-quality, but we don't really have resources to improve it.
Yes, it is ugly. But it works. We have more than enough things that either don't work properly or require improvements.

So see no reason to touch networking code right now. And even if I do - I would rather consider swapping TCP+asio for UDP+ENet.

**Comment by heretic13** [comment]
So no one forbids you to replace TCP + asio with UDP + asio.

Don't forget that asio is in draft form in the C++ committee.
Asio is not only network programming, it is also timers, the correct implementation of multithreading, and so on.

Now think. Is it really necessary to change the code "close to the standard" (asio) to a third-party library (ENet).

**Comment by IvanSavenko** [comment]
> So no one forbids you to replace TCP + asio with UDP + asio.

Not really. ENet is not *just* UDP, but also a lot of functionality on top of it, to make it more suitable for online games usage

> Don't forget that asio is in draft form in the C++ committee.

From what I remember, it was under consideration back when c++11 was called c++0x...
And it won't bring ENet functionality, just raw udp access

**Comment by heretic13** [comment]
> Not really. ENet is not _just_ UDP, but also a lot of functionality on top of it, to make it more suitable for online games usage

I took a quick look at the documentation.
ENet is a very specific library.
Are you sure that you really need such a solution (Enet UDP)?
You have a turn-based strategy. Delays are second. The convenience of programming clients in various programming languages and various operating systems comes first.

You are more suited to GRPC.
If you don't want GRPC, use protobuf messages over TCP.

**Comment by IvanSavenko** [comment]
> Delays are second

Yeah, sure... 
#1133 
And this is after we already abusing TCP protocol with every possible hack available

This is only one example that is immediately noticeable for any player. We have huge number of similar delays specifically because of ping to server.

**Comment by heretic13** [comment]
#1133
Specifically, this problem is related to programming and it can be solved programmatically. I repeat once again - this is a turn-based strategy !!.

**Comment by Nordsoft91** [comment]
Non-actionable issue. Suggest to close
