### ISSUE TITLE
Fort Noxis map, starting hero superposition bug

### ISSUE THREAD

**Issue by storageer** [vcmi/vcmi#1579]
**Describe the bug**
One of the starting heroes in the vanilla map "Fort Noxis" is able to access both towns at the start of the game.

**Game logs**
[server_log.txt](https://github.com/vcmi/vcmi/files/10734535/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/10734537/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/10734538/VCMI_Launcher_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/10734539/VCMI_Server_log.txt)

**To Reproduce**
1. Start the map "Fort Noxis"
2. bug is visible and reproducible in the very beginning of the game

**Expected behavior**
The starting visiting hero in Fort Noxis should not be shown as a visiting hero for the Overworld Town.

**Actual behavior**
The visiting hero of Fort Noxis is shown as a visiting hero in both Towns:
- Noxis Visitor is unable to learn spells from the Overworld Towns' Mage Guild
- Noxis Visitor is able to take units recruited in the Overworld Town, both before and after moving out of Noxis
- Noxis Visitor is unable to upgrade his/her basic units while "visiting" the Overworld Town
- The bug is persistent across days, ending the turn does not fix it
- Visiting the Overworld Town with a different hero appears to end the bug

**Did it work earlier?**
Unknown

**Screenshots**
[Video Recording](https://mega.nz/file/hNVGkbqY#VuanIHGyj9G39Gtz8fOAMZu-2t9e3eWmRdl1GJ5NNtA) (mega.nz, length 0:02:33)

**Version**
 - OS: Windows 10
 - Version: VCMI 1.1.1 Release version

**Additional context**
I tried to hastily reproduce it on a handmade map, but did not succeed. It might be a bug with the map itself and not VCMI, but I will leave the judgement to those more knowledgeable than me.

**Comment by nullkiller** [comment]
I see that towns have exactly same visitable pos except layer. This is interesting

**Comment by IvanSavenko** [comment]
@nullkiller 
I think this might be the cause:
https://github.com/vcmi/vcmi/pull/1196/files#diff-22e45c7b25b21d60ca508ef4fa6011439ec16f69422dbd6354b9db8f0c717263R1876

Variables `heroOnTownBlockableTile` and `heroOnTownVisitableTile` don't check for layer
