### ISSUE TITLE
Magical Fields can cover up Gem Pond and Ore Pit

### ISSUE THREAD

**Issue by storageer** [vcmi/vcmi#1589]
**Describe the bug**
The Ore Pit and Gem Pond mines can be visually covered up by various Fields (such as Cursed Field, Elemental Fields) on the adventure map.

**Game logs**
[server_log.txt](https://github.com/vcmi/vcmi/files/10767151/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/10767152/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/10767153/VCMI_Launcher_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/10767155/VCMI_Server_log.txt)
[Testing Mines n Fields v2.zip](https://github.com/vcmi/vcmi/files/10767156/Testing.Mines.n.Fields.v2.zip)

**To Reproduce**
In the Map Editor, place the fields on top of the Ore Pit or the Gem Stone, after the two mines are already put down.

**Expected behavior**
The Ore Pit and Gem Pond mines should stay above the various fields, similar to how the other mines behave, both for consistency and gameplay reasons.

**Actual behavior**
The Ore Pit and Gem Pond mines get hidden under the Fields, and while it is possible to interact with them, they're easily missed if the player does not cross-check the adventure map with the minimap or notice the cursor change by accident.

- Based on my test map, the position of the Field and the flat mines relative to each other decide if and how the mines get covered up
- Occupied and unoccupied mines do not seem to show any difference.
- all the fields appear to have the same mine covering effect (Cursed Fields, Elemental Fields, etc)
- all the various biome mines are affected in the same way.
- The order of placement does not seem to effect the result: placing the mine down before or after the field

**Did it work earlier?**
Unknown.

**Screenshots**
Screenshot recorded on the Vanilla map "Freedom"
![Ore Pit Field bug](https://user-images.githubusercontent.com/121976640/219664577-12dc84ef-80b9-4cba-ad84-8fb4726a7c0b.png)

**Version**
 - OS: Windows 10
 - Version: VCMI 1.1.1 release version

**Additional context**
Test map created with the Original H3maped. I did not test if opening and saving it in the VCMI map editor would get the same results or not.

**Comment by DjWarmonger** [comment]
I saw objects being deliberately hidden this way on some custom maps for OH3, so it's not unexpected.

**Comment by storageer** [comment]
I have been having second thoughts about this too, though more along the lines of scenic mapmaking. Trying to address this might mean no more extra vegetation on the two flat mines with landscaping purposes.

**Comment by nullkiller** [comment]
In original game this mine is visible
![image](https://user-images.githubusercontent.com/5644734/219868881-b1129e62-03cb-46fb-9961-734d747ee0f0.png)

**Comment by IvanSavenko** [comment]
Object render priority should now match H3 in PR #1581
Confirmed for this map as well.
