### ISSUE TITLE
Was not able to pass through the open gate during siege.

### ISSUE THREAD

**Issue by nullkiller** [vcmi/vcmi#1612]
**Describe the bug**
Was not able to pass through the open gate during siege. Troglodytes got morale on the first turn and moved through the gate, it opened and they stopped on it. Killed them by a stack of centaurs while they were standing on the opened gate. Afterwards I was attacked by a stack of griffins, they also landed on the gate. Killed them with counterattack. Animation left the gate opened but I was not able to pass through it.

**Expected behavior**
When a stack is killed on an opened gate it has to stay opened till the end of the siege

**Actual behavior**
Was not able to pass through the opened gate. Had to spend a few more turns until I killed enemies.

**Did it work earlier?**
Worked fine at least in 1.0

**Version**
 - latest develop, platform windows, msvc
 
[Saves.zip](https://github.com/vcmi/vcmi/files/10831320/Saves.zip)

**Comment by DjWarmonger** [comment]
I think that precisely gate should not close **while** there's dead stack body on it. The stack can be later raised or removed altogether (the latter not in OH3).

**Comment by IvanSavenko** [comment]
Reproduced:
- can only happen in Fortress (which has slightly different rules for both gates and moat)
- you need to kill unit standing on lowered drawbridge tile

This is not bug with gates but more related to moat - killed stack is located on part of moat covered by drawbridge.
This hex is somewhat special - such behavior exists only in Fortress - it should act as moat while drawbridge is closed, but if drawbridge is open it will be covered by it, disabling moat effect

Gate is actually open and you can go through it, but only after moving into tile covered by moat.

@rilian-la-te perhaps better to handle this in your moats PR?

Here how battlefield looks like in this state:
Tile with corpse is the one in question
![Fortress](https://user-images.githubusercontent.com/1576820/227725278-0ec69ba5-48d8-48c4-90c8-9894e0c27dd5.png)

**Comment by IvanSavenko** [comment]
Update: we actually have code that should've handled this case - inside `CBattleInfoCallback::getAllAffectedObstaclesByStack` there is check for this scenario. Investigating why it does not works here.

**Comment by IvanSavenko** [comment]
Wrong method, this is about stopping movement so `CBattleInfoCallback::getStoppers`
And that class was missing a check for such scenario.

Will fix.
