### ISSUE TITLE
CArchiveLoader::CArchiveLoader param "extractArchives" is masked by typo

### ISSUE THREAD

**Issue by nickhuang99** [vcmi/vcmi#1619]
Parameter "extractArchives" can NEVER take effect
<pre><code>
CArchiveLoader::CArchiveLoader(std::string mountPoint, bfs::path archive, bool extractArchives = false);
</code></pre>
because the member variable is initialized by itself instead of input parameter.

Currently there is only one used occasion for "extractArchives" which is default value. So, it is now harmless unless in future it is actually playing a role.
A simple patch shows why it is a typo because the "input" parameter is never used to init member CArchiveLoader::extractArchives. 

<pre><code>
diff --git a/lib/filesystem/CArchiveLoader.cpp b/lib/filesystem/CArchiveLoader.cpp
index b58fe2b02..ad1d59a9b 100644
--- a/lib/filesystem/CArchiveLoader.cpp
+++ b/lib/filesystem/CArchiveLoader.cpp
@@ -24,10 +24,10 @@ ArchiveEntry::ArchiveEntry()
 
 }
 
-CArchiveLoader::CArchiveLoader(std::string _mountPoint, bfs::path _archive, bool extractArchives) :
+CArchiveLoader::CArchiveLoader(std::string _mountPoint, bfs::path _archive, bool _extractArchives) :
     archive(std::move(_archive)),
     mountPoint(std::move(_mountPoint)),
-       extractArchives(extractArchives)
+       extractArchives(_extractArchives)
 {
        // Open archive file(.snd, .vid, .lod)
        CFileInputStream fileStream(archive);
<code></pre>

**Comment by krs0** [comment]
Having same parameter name as member variable is legal (at least on windows and linux). Perhaps a matter of taste?
Nevertheless I will change it, to conform with the rest of constructor parameter names.

**Comment by IvanSavenko** [comment]
It is legal, and sometimes used in vcmi code. So I am OK with diff in bug report (but not insisting on it)

**Comment by nickhuang99** [comment]
it is legal, just usually it is supposedly initiated by input parameter. otherwise there is no use of parameter.

Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by krs0** [comment]
Changed in https://github.com/vcmi/vcmi/pull/1622

**Comment by krs0** [comment]
To clarify the usage of ExtractArchives... this is intended for extracting all H3 archives (at the moment via comand line parameters (-e -s -c -d) from MapEditor)
see here: https://github.com/vcmi/vcmi/issues/1118
