### ISSUE TITLE
Champions can strike catapult from behind (BattleAI)

### ISSUE THREAD

**Issue by rilian-la-te** [vcmi/vcmi#1621]
**Describe the bug**
self explanatory - champions can stand on tile near the keep and beat the catapult.

**To Reproduce**
1. Attack castle on cursed ground

Savegame is from #1518, but I do nothing about catapult placement.

**Expected behavior**
Champions should not be able to strike catapult from behind

**Actual behavior**
They can

**Did it work earlier?**
Do not know

**Screenshots**
![bug-champions](https://user-images.githubusercontent.com/1329638/221904586-45de9200-7e61-4855-b658-9e7ff3651b81.png)

Champions stand in place where they stand on screen and can damage catapult in melee without move, it is not good.

**Version**
 - OS: Linux
 - Version: #1518 

**Additional context**
[Saves.zip](https://github.com/vcmi/vcmi/files/10852144/Saves.zip)

You can just use same cheats on Freedom map to reproduce this behaviour on develop.

**Comment by rilian-la-te** [comment]
@IvanSavenko how this can be? Is hexes something warped?

**Comment by IvanSavenko** [comment]
@rilian-la-te 
Kind of. Each hex has own ID, ranging from 0 to battlefield width * height.
Also, game has hidden column of hexes on each side - use for example by war machines.

Probably some routines simply check hex ID instead of checking row & column for adjacency checks

**Comment by rilian-la-te** [comment]
@IvanSavenko and champions stand somewhat weird - its second part (behind a keep) actually not on battlefield.

**Comment by rilian-la-te** [comment]
AFAIK, user cannot place unit to that hidden column at all. AI-only issue?

**Comment by krs0** [comment]
Side question... what is standing in the gate? :)

**Comment by rilian-la-te** [comment]
Pikemen)

**Comment by rilian-la-te** [comment]
![Screenshot_20230301_004701](https://user-images.githubusercontent.com/1329638/221988528-86a9a7f7-48d2-4534-bb0d-8ae044b310e8.png)
New screen of bug - this time with griffins. And I placed them myself)

**Comment by nullkiller** [comment]
My 5 cents. Obviously 2-hex units back hex can be put outside battlefield while one-hex are treated correctly.
![image](https://user-images.githubusercontent.com/5644734/222193278-96a9dbf1-de44-49b5-97b2-33410362ba09.png)

Also hovering second hex with spell-cast cursor causes game to crash

**Comment by nullkiller** [comment]
![image](https://user-images.githubusercontent.com/5644734/222194760-f72f9122-6dca-45cc-a070-f4ca49bc9e8e.png)
And here is an error. otherHex should be used in the second case

**Comment by rilian-la-te** [comment]
@nullkiller sorry, I missed this when converted to method.

**Comment by nullkiller** [comment]
No problem.
