### ISSUE TITLE
When playing campaign and receiving quest artifact, it doesn't go to the next mission with me. When I start next mission my hero has nothing in inventory. 

### ISSUE THREAD

**Issue by AlexKap1905** [vcmi/vcmi#1625]
**Describe the bug**

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/10864561/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/10864563/VCMI_Server_log.txt)

**Expected behavior**

**Actual behavior**
A clear description what is currently happening 

**Did it work earlier?**
If this something which worked well some time ago, please let us know about version where it works or at date when it worked.

**Screenshots**

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: [VCMI version]

**Additional context**

**Comment by rilian-la-te** [comment]
@AlexKap1905 please, fill a template.

**Comment by AlexKap1905** [comment]
MacOS Monterey 12.6.2
VCMI 1.1.1

**Comment by Nordsoft91** [comment]
@AlexKap1905 , could you please help to understand, which campaign and which mission?
Also, which hero and what the artefact you try to carry?

**Comment by IvanSavenko** [comment]
Fixed in 1.3
