### ISSUE TITLE
"Marathon" RMG template has too long name

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1634]
**Describe the bug**
I understand that the long name is coming from https://github.com/vcmi-mods/vcmi-extras/blob/master/Mods/defaultTemplates/Mods/HDmod%20RMG%20Templates/Content/config/defaultTemplates/marathon.JSON but maybe client should show ellipsis for long strings? And full name can be shown in scenario description for example.

**To Reproduce**
new scenario - random map - template selector on top

**Expected behavior**
Strings don't go out of bounds

**Actual behavior**
strings are displayed as is

**Did it work earlier?**
no

**Screenshots**
![Screenshot 2023-03-05 at 10 56 34](https://user-images.githubusercontent.com/1557784/222949088-dd8b7088-6072-4dbd-886e-e92c312eb249.png)
![Screenshot 2023-03-05 at 10 56 42](https://user-images.githubusercontent.com/1557784/222949096-0c22a285-4929-426a-b295-6cdb4a11ff4d.png)

**Version**
 - OS: macOS Intel
 - Version: latest develop, latest Extras mod

**Additional context**
A bit unusual but the `default` template also has long name (first in the list on the first SS), although when you select it it shows `default` and not the long string. Maybe same approach can be used in the Marathon config?

**Comment by IvanSavenko** [comment]
Also, related bug - this template has invalid encoding - Win-1251 string in template name (all json's should use UTF-8)
`File CONFIG/DEFAULTTEMPLATES/SPEED2 M-U is not a valid JSON file!`

**Comment by DjWarmonger** [comment]
I suppose for now this description should go to the mod description field, but not in a mod that contains a variety of different templates.

As to where to put the template description in GUI is a whole different question.

**Comment by DjWarmonger** [comment]
Fixed this and all similiar cases: https://github.com/vcmi-mods/vcmi-extras/pull/10
