### ISSUE TITLE
Crash on loading of Titan's Winter vanilla map.

### ISSUE THREAD

**Issue by rilian-la-te** [vcmi/vcmi#1637]
**Describe the bug**
Self-explanatory

**Game logs**
Error: signal 11 :
/usr/local/bin/vcmiserver(+0x123af2) [0x55946ba6faf2]
/usr/lib/libc.so.6(+0x38f50) [0x7f7435251f50]
/usr/local/lib/vcmi/libvcmi.so(_ZNK21CObjectClassesHandler15knownSubObjectsEi+0x49) [0x7f7435b54409]
/usr/local/lib/vcmi/libvcmi.so(_ZN13CMapLoaderH3M11readObjectsEv+0xb29) [0x7f7435be0c59]
/usr/local/lib/vcmi/libvcmi.so(_ZN13CMapLoaderH3M4initEv+0xa1a) [0x7f7435bddaea]
/usr/local/lib/vcmi/libvcmi.so(_ZN13CMapLoaderH3M7loadMapEv+0x3f) [0x7f7435bdd07f]
/usr/local/lib/vcmi/libvcmi.so(_ZNK11CMapService7loadMapERK10ResourceID+0x53) [0x7f7435bd5873]
/usr/local/lib/vcmi/libvcmi.so(_ZN10CGameState11initNewGameEPK11IMapServiceb+0x39c) [0x7f7435f642dc]
/usr/local/lib/vcmi/libvcmi.so(_ZN10CGameState4initEPK11IMapServiceP9StartInfob+0x11e) [0x7f7435f638be]
/usr/local/bin/vcmiserver(+0x601be) [0x55946b9ac1be]
/usr/local/bin/vcmiserver(+0x11fc15) [0x55946ba6bc15]
/usr/local/bin/vcmiserver(+0x16aac9) [0x55946bab6ac9]
/usr/local/bin/vcmiserver(+0x144f69) [0x55946ba90f69]
/usr/local/bin/vcmiserver(+0x1203c3) [0x55946ba6c3c3]
/usr/local/bin/vcmiserver(+0x12d7b3) [0x55946ba797b3]
/usr/local/lib/vcmi/libvcmi.so(_ZN5CPack5visitER13ICPackVisitor+0x10) [0x7f743604e2b0]
/usr/local/bin/vcmiserver(+0x11ee1f) [0x55946ba6ae1f]
/usr/local/bin/vcmiserver(+0x15ce7f) [0x55946baa8e7f]
/usr/local/bin/vcmiserver(+0x15cd82) [0x55946baa8d82]
/usr/local/bin/vcmiserver(+0x15cd0c) [0x55946baa8d0c]
/usr/lib/libboost_thread.so.1.81.0(+0xfcbb) [0x7f74362a7cbb]
/usr/lib/libc.so.6(+0x85bb5) [0x7f743529ebb5]
/usr/lib/libc.so.6(+0x107d90) [0x7f7435320d90]
Lost connection to server, ending listening thread!
read_some: End of file [asio.misc:2]
Error: server failed to close correctly or crashed!
Check /home/rilian/.cache/vcmi/server_log.txt for more info

**To Reproduce**
Load attached map
[map.zip](https://github.com/vcmi/vcmi/files/10892500/map.zip)

**Expected behavior**
Map loads

**Actual behavior**
Crash, our map editor crashes too

**Did it work earlier?**
Do not know

**Screenshots**
Object under cursor cause both crashes:
![изображение](https://user-images.githubusercontent.com/1329638/222978676-18798213-2bc5-454c-940a-d6aa4d2a6bd7.png)

**Version**
 - OS: Linux
 - Version: develop

**Additional context**
There is unknown object on map, and it causes a crash (checked in vanilla editor).

**Comment by IvanSavenko** [comment]
Please recheck current develop - should be fixed in my PR from today.
This is "Market of Time" - unfinished object found on some RoE maps.

**Comment by rilian-la-te** [comment]
@IvanSavenko it crashes after I try to click on it, but not on load. #1518 with latest develop (with all your PRs applied).

**Comment by IvanSavenko** [comment]
Hey, progress!
Understood, will fix.

**Comment by rilian-la-te** [comment]
@IvanSavenko stacktrace from click crash:

```
CObjectClassesHandler::getObjectName[abi:cxx11](int, int) const (this=0x7fff94143790, type=<optimized out>, subtype=<optimized out>) at /home/rilian/Projects/vcmi/lib/mapObjects/CObjectClassesHandler.cpp:407
407             if (handler->hasNameTextID())
(gdb) bt
#0  CObjectClassesHandler::getObjectName[abi:cxx11](int, int) const (this=0x7fff94143790, type=<optimized out>, subtype=<optimized out>) at /home/rilian/Projects/vcmi/lib/mapObjects/CObjectClassesHandler.cpp:407
#1  0x00007ffff77669f0 in CGObjectInstance::getObjectName[abi:cxx11]() const (this=<optimized out>) at /home/rilian/Projects/vcmi/lib/mapObjects/CObjectHandler.cpp:294
#2  0x00007ffff7767038 in CGObjectInstance::getHoverText[abi:cxx11](PlayerColor) const (this=0x0, player=...) at /home/rilian/Projects/vcmi/lib/mapObjects/CObjectHandler.cpp:326
#3  0x00007ffff77671c9 in CGObjectInstance::getHoverText[abi:cxx11](CGHeroInstance const*) const (this=0x0, hero=<optimized out>) at /home/rilian/Projects/vcmi/lib/mapObjects/CObjectHandler.cpp:334
#4  0x0000555555690400 in CAdvMapInt::onTileHovered(int3 const&) (this=0x7fff94cd5950, mapPos=...) at /home/rilian/Projects/vcmi/client/adventureMap/../../lib/mapping/../GameConstants.h:354
#5  0x000055555577058e in MapViewActions::handleHover(Point const&) (this=<optimized out>, cursorPosition=<optimized out>) at /home/rilian/Projects/vcmi/client/mapView/MapViewActions.cpp:161
#6  0x00005555557704bf in MapViewActions::mouseMoved(Point const&) (this=0x7fffffffcab0, cursorPosition=...) at /home/rilian/Projects/vcmi/client/mapView/MapViewActions.cpp:99
#7  0x00005555556ff03a in CGuiHandler::handleMoveInterested(SDL_MouseMotionEvent const&) (this=this@entry=0x555555b20bd8 <GH>, motion=...) at /home/rilian/Projects/vcmi/client/gui/CGuiHandler.cpp:637
#8  0x00005555556feb85 in CGuiHandler::handleMouseMotion(SDL_Event const&) (this=this@entry=0x555555b20bd8 <GH>, current=...) at /home/rilian/Projects/vcmi/client/gui/CGuiHandler.cpp:617
#9  0x00005555556fd1b5 in CGuiHandler::handleCurrentEvent(SDL_Event&) (this=this@entry=0x555555b20bd8 <GH>, current=...) at /home/rilian/Projects/vcmi/client/gui/CGuiHandler.cpp:428
#10 0x00005555556fd0d4 in CGuiHandler::handleEvents() (this=0x555555b20bd8 <GH>) at /home/rilian/Projects/vcmi/client/gui/CGuiHandler.cpp:224
#11 0x00005555558cc8d6 in CPlayerInterface::update() (this=0x7fff94dd1990) at /home/rilian/Projects/vcmi/client/CPlayerInterface.cpp:1559
#12 0x00005555556ff249 in CGuiHandler::renderFrame() (this=0x555555b20bd8 <GH>) at /home/rilian/Projects/vcmi/client/gui/CGuiHandler.cpp:661
#13 0x00005555558a44e2 in mainLoop() () at /home/rilian/Projects/vcmi/client/CMT.cpp:1061
#14 main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/rilian/Projects/vcmi/client/CMT.cpp:560

```
