### ISSUE TITLE
AI is not prioritizing mines flagging

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#1644]
**Describe the bug**
Even after playing for 7 days, 2 out of 3 AI's have not flagged neither Sawmill nor Ore Pit next to their starting towns.
While I don't expect AI to optimize movement to a point of capturing all reachable mines & dwellings on day 1, objects like unguarded mines in movement range should have fairly high priority.

Especially noticeable with guarded mines - AI is capable of defeating guards, but not capable of flagging mine right behind the guards.

**To Reproduce**
1. Start map "Dragon's Pass"
2. Wait for 7 days
3. Observe AI

**Expected behavior**
AI captures unguarded mines next to their towns within first few days of the game.

**Actual behavior**
- Day 3: Blue captures Ore Pit
- Day 5: Green defeats guards of Alchemist and flags it
- Day 6: Brown defeats guards of Sulfur mine, but does not flags the mine
- Day 8: Blue captures Sawmill
- Day 9: Brown captures Sawmill
- Day 9: Green captures Sawmill

**Version**
 - develop branch

[VCMI_Client_log.zip](https://github.com/vcmi/vcmi/files/10897202/VCMI_Client_log.zip)

**Comment by kambala-decapitator** [comment]
maybe AI simply has lots of resources and doesn't consider wood/ore important at that point? (resourceful mod)

**Comment by IvanSavenko** [comment]
Nope. No mods.

**Comment by dydzio0614** [comment]
I did not exaggerate when I said AI is underperforming :P

**Comment by DjWarmonger** [comment]
VCAI prioritizes capturing any flaggable objects, and you didn't like it either :P

**Comment by IvanSavenko** [comment]
Did I?
In any case, current NKAI behavior is rather weird. It goes for objects that are quite far away (treasure chests?), but ignores anything that he can gather nearby.
These unflagged mines were often left with untouched resource piles.

AI did eventually flagged these mines on week 2, probably due to running out of more important goals.

**Comment by DjWarmonger** [comment]
NKAI goes for gold in first place. And this is pretty much what competetive players also do.

But maybe @nullkiller can explain it in detail.

**Comment by dydzio0614** [comment]
competitive strategy doesnt work in normal maps and vice versa

**Comment by IvanSavenko** [comment]
> NKAI goes for gold in first place. And this is pretty much what competetive players also do.
> 
> But maybe @nullkiller can explain it in detail.

Maybe. But as result this "competitive AI" has whooping army of 50 Imps and 40 Gog, while I at the same time have around 200 Centaurs, 50 Elves, 20 Pegasi and 10 Unicorns.

Because I don't run for gold pile 3 turns away from my current position ignoring everything on my way.
I also collected everything in my home area faster than AI. Despite me having 2 heroes during week 1 and 3 heroes on week 2. While AI had twice as many heroes.

**Comment by IvanSavenko** [comment]
Second map (Deluge) was even worse by the way.
Blue AI stuck till 2nd month doing nothing because he was unable to breach either stack of Observers nor stack of... somebody else of Tier 2 that were blocking rest of his area.

**Comment by dydzio0614** [comment]
Yeah, we need to let nullkiller finally get back to focus on AI (apparently he wants to)

Anyway, I noticed that without resource cheats AI seems to just deplete its economy, so it is poor and barely progressing in town development and troops buildings - AI state can be checked by controlai command

**Comment by IvanSavenko** [comment]
If nullkiller wants (and have time to) focus on AI - the sure. I think I can handle rest of bugs from 1.2 milestone. At most we'll have to delay 1.2 for a week or two, but if we get better AI in result then this is great.

Also - on resources: if AI can't manage its economy well then perhaps we should boost its starting resources a bit?
Not absurdly high amounts like in that mod, but we can always give AI resources similar to those of human player at lowest difficulty (30 wood/ore, 15 rare, 30k gold). Not some sort of unfair advantage but might improve perception of AI performance.

**Comment by dydzio0614** [comment]
current values should be probably available by default anyway, since they match original H3 values. On the other side H3 AI gets free gold every turn...

**Comment by DjWarmonger** [comment]
You know, trying to understand and fix AI just by peeking its movement won't cut it.

**Comment by dydzio0614** [comment]
I saw MR and it seems to fix 2nd side of the problem, aka town defending, but it's not about properly picking attack target unless I am wrong

**Comment by DjWarmonger** [comment]
One thing at a time. Change of a single priority can alter whole AI strategy.

Do you guys actually check AI logs / code to see what it's really up to?

**Comment by nullkiller** [comment]
AI can postpone mine capturing if it can pick enough resources from map. It actually prefer instant resources rather than mines. And more interested in gold yes. Also it try to analyze what resources it will need. I may change this later so. mage guilds need a lot of resources and thus mines become more priority things. But now AI does not directly consider mage guilds as important buildings

**Comment by nullkiller** [comment]
Also latest changes to defense made some difference in terms of capturing resources. Also sometimes AI can kill guard but not exactly for mine capturing.

**Comment by nullkiller** [comment]
And do not try to compare AI and human. Battle loses for AI are way bigger and until it is solved no way to get competitive AI without heavy cheating.

**Comment by rilian-la-te** [comment]
@nullkiller why AI is lose way too much battles?

**Comment by rilian-la-te** [comment]
He is using BattleAI to fight?

**Comment by nullkiller** [comment]
I mean creatures killed. AI can not for instance play archers protection

**Comment by nullkiller** [comment]
So can not effectively operate archers stacks without loses.

**Comment by rilian-la-te** [comment]
@nullkiller but why it cannot? It is BattleAI flaw?

**Comment by nullkiller** [comment]
Too stupid ha-ha. As more clever AI is as more it gets slower unfortunately. At least with my approaches which usually are expressed with some exponential ideas)
