### ISSUE TITLE
Speed2 is invalid RMG template

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1646]
**Describe the bug**
```
                [94061e26]HD Mod RMGs
File CONFIG/DEFAULTTEMPLATES/SPEED2 M-U is not a valid JSON file!
At line 1, position 0 error: Not a valid UTF-8 file
```
![image](https://user-images.githubusercontent.com/15194321/223175470-f86887a8-e83d-4924-af6f-6d7aecec644c.png)

**Version**
 - OS: Windows,
 - Version: develop

**Comment by DjWarmonger** [comment]
Fixed in https://github.com/vcmi-mods/vcmi-extras/pull/8
