### ISSUE TITLE
Map editor can't be launched from launcher.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#1661]
**Describe the bug**
Map editor can't be launched from launcher in Windows version

**Game logs**
N/A

**To Reproduce**
1. Start launcher.
2. Click Map Editor icon
![image](https://user-images.githubusercontent.com/29593042/223943707-ae74b002-00cc-493c-926b-6beaceed7638.png)

**Expected behavior**
Map editor should start
**Actual behavior**
Map editor doesn't start

**Did it work earlier?**
No

**Version**
 - OS: Windows
 - Version: [VCMI daily builds]

**Comment by kambala-decapitator** [comment]
does it start directly (without launcher)?

can't reproduce on macOS, seems Windows-specific

**Comment by misiokles** [comment]
Yes, start directly from exe without problems. I guess it's problem with shortcuts

**Comment by DjWarmonger** [comment]
On WIndows the binary is called `VCMI_**map**editor.exe`, not `VCMI_editor.exe`.
