### ISSUE TITLE
New turn takes a long time to start at new month

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#1683]
**Describe the bug**
When switching from last player at week 4 day to week 1 day 1 of next month there is a long pause (>30 seconds? on my beefy CPU) when nothing happens and the game seemingly freezes.

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
Wait for a new month preferably on an XL+U map

**Expected behavior**
New turn would come quickly, without noticeable delay

**Actual behavior**
Delay is long and can be interpreted by player as a complete freeze. 

**Did it work earlier?**
Didn't notice that before..

**Version**
 - OS: Windows 11, fresh install
 - Version: 14-Mar-2023

**Additional context**
Might be caused by wandering stacks spawning on a new month. Hypothesis: stacks get added one by one and Pathfinder iis recalculated every time.

**Comment by IvanSavenko** [comment]
Not reproducible for me.
XL standard map (non-rmg) with multiple AI's.
Zero/close to zero delay between end of turn of last AI and start of my turn.

**Comment by DjWarmonger** [comment]
Maybe that was caused by the fact I watched at autoskip anyway, so effectively didn't get my turn. Used NKAI.

**Comment by DjWarmonger** [comment]
This was likely fixed by disabling object removal / spawn animation.

**Comment by Alucard648** [comment]
Will it be possible to optimize applying animation for spawning map objects? For instance, process monster spawning only if:
1. Monster/objects to be spawned is visible in player`s view.
2. Monster/objects to be spawned is in scouted area of map. 
 
Unless even with optimizations it lags on spawn in large maps...
