### ISSUE TITLE
Infobar polishing

### ISSUE THREAD

**Issue by rilian-la-te** [vcmi/vcmi#1688]
**Describe the bug**
@krs0  found some issues with infobars in English version.

Issues:
- Text not centered for Source of Reward (EG: witch hut) - fixed by #1690
- Text for shrines is below border - fixed by #1690
- Many objects show no info when nothing is to gain (Experience stones, Idol of fortune, Skeleton, Library, etc), it is a little confusing when you expect something to happen and you get no feedback. Shrines show a no you get nothing text.
@rilian-la-te says than it is works for me (see screenshots).
- When I visit another object, the window should reset even if nothing is will be shown. (edited) - @rilian-la-te AFAIK, it resets on latest develop.

Enhancements:
- Variable display time? 4.5 seconds of 1000 Gold is too much... for Sphynx or Obelysc 4.5 seconds is too less...
- Show Scholar title when you receive something from Scholar (Like witch hut)
- Creature Joining do not appear in Info Panel... would be useful
- Rally flag does not mention movement points.

**Game logs**
Not applicable.

**To Reproduce**
1. Turn on infobar pickup

**Expected behavior**
It should work.

**Actual behavior**
Issues above

**Did it work earlier?**
It is a new feature.

**Screenshots**
![image](https://user-images.githubusercontent.com/1329638/225246628-8f7b8190-202e-4750-b756-8f56ac1380ce.png)
![image](https://user-images.githubusercontent.com/1329638/225246657-1d7572a5-d541-485c-a602-b204b4226fed.png)
![image](https://user-images.githubusercontent.com/1329638/225246690-e4c212d8-c3c2-4738-af80-f268cbf377cd.png)
![image](https://user-images.githubusercontent.com/1329638/225246724-28331517-05a5-40e1-a42d-67fb5a2868a0.png)
![image](https://user-images.githubusercontent.com/1329638/225246779-c1ec669d-388d-40a4-b9b6-b60bb5eba347.png)

**Version**
 - OS:I do not know, @krs0 should write. Most likely not Linux
 - Version: develop

**Additional context**

**Comment by rilian-la-te** [comment]
@krs0 feel free to add some info.

**Comment by rilian-la-te** [comment]
@krs0 for resources display is 3 seconds, not 4.5

**Comment by rilian-la-te** [comment]
English version of visited learning stone:

![image](https://user-images.githubusercontent.com/1329638/225259284-7500f544-fd1b-429b-8222-06366bc35aae.png)

**Comment by krs0** [comment]
This is what I get for most of already visitable objects. Below for visited Temple.

![image](https://user-images.githubusercontent.com/15194321/225356465-442a25dc-2db5-456d-956a-eb0b00f7d118.png)

**Comment by rilian-la-te** [comment]
@krs0 does not see same message, just tried temple. Do you have installed H3 data? What operating system do you use? What version?

**Comment by rilian-la-te** [comment]
@krs0 it seems than your config is broken somehow for most rewardables.

**Comment by krs0** [comment]
Objects show no info when nothing is to gain Is fixed by:
Rewardable: always initialize numbers #1699

**Comment by krs0** [comment]
<img src="https://user-images.githubusercontent.com/15194321/226000470-c98a0bc5-f909-497a-9f67-842206bb04d1.png" width=50% height=50%>
