### ISSUE TITLE
Translation - only one mod translated

### ISSUE THREAD

**Issue by heroesiiifan** [vcmi/vcmi#1692]
**Describe the bug**
Only one mod translated

**To Reproduce**
1. Set to german
2. Load multiple mods (e.g. abyss-town, fairy-town and asylum-town (1.2 branch))
3. Go to town selection

**Expected behavior**
All towns are translated

**Actual behavior**
Only the last town is translated

**Did it work earlier?**
I don't know

**Version**
 - OS: Ubuntu
 - Version: https://github.com/vcmi/vcmi/pull/1682

**Additional context**
It seems that the problem only occures if the different mods have the same path to the translated json (e.g. `translation/german.json`). Mods with other paths are independend from this bug.

**Comment by IvanSavenko** [comment]
>It seems that the problem only occures if the different mods have the same path to the translated json (e.g. translation/german.json). 

That's the problem unfortunately with current mods system...
Please use paths like `config/[modname]/translation/german.json` to prevent conflicts.

This is not specific to translations, all other files are also affected by such potential conflicts at the moment. I may be able to find time to resolve this by 1.3, but not set at stone right now and definitely not for 1.2

**Comment by heroesiiifan** [comment]
Okay, thanks. I've adjusted the paths.
