### ISSUE TITLE
Friendly units deal 1 point of damage while enemy units deal normal damage

### ISSUE THREAD

**Issue by 4zm0d4n666** [vcmi/vcmi#1695]
**Describe the bug**

 - After a while of playing (roughly couple weeks/months in-game time) when fighting against other heros, any stack of friendly units will deal 1 damage to any stack of enemy units, this applies to all units no matter how powerful they are, in the screenshot below - a powerful stack of my units deals 1 damage, while a weak stack of enemy units with a much weaker hero deals 16, so the AI is not affected by this bug and does normal amount of damage to your units.

**Game logs**

[Logs.zip](https://github.com/vcmi/vcmi/files/10990310/Logs.zip)

**Expected behavior**

- Units should deal normal amount of damage defined by whatever stats they have as well as their heros and skills/stats/artifacts they possess.

**Actual behavior**

- All friendly units deal 1 point of damage to any enemy units while enemy units deal normal amounts of damage.

**Did it work earlier?**

- I tried multiple versions of VCMI with different mods and without mods and always stumbled upon this bug sooner or later, it makes battles essentially impossible or would make every fight last probably weeks real time if you were to play it.

**Screenshots**
![Screenshot_20230316_124314_VCMI](https://user-images.githubusercontent.com/64220148/225610069-2de7a94b-ca22-47a3-a8c8-957141959857.jpg)

**Version**

 - OS: Android
 - Version: 1.1 (however, same bug occured on multiple daily builds before)

**Additional context**

I'm using a lot of mods at the same time, however this is pretty much the only significant bug that I've ever encountered and as described above, it occured multiple times, on multiple version of VCMI, with different setups and mods I've used, I have no idea how to replicate it or what is causing it, the game works perfectly fine for a few in game weeks/months and then, suddenly it becomes unplayable as this bug occurs out of nowhere.

**Comment by kambala-decapitator** [comment]
once you can reproduce, then save and load, is it also reproducible? Or you need to play for a few weeks again?

anyway attaching saves might also help

**Comment by 4zm0d4n666** [comment]
> once you can reproduce, then save and load, is it also reproducible? Or you need to play for a few weeks again?
> 
> anyway attaching saves might also help

[Saves.zip](https://github.com/vcmi/vcmi/files/10990627/Saves.zip)

This save should be right before the battle with a pink player where the screenshot is from.

Funnily enough, on this same map, just up to the north there is a teleporter that leads to three different teleporters at the same time, and the only way to choose which way you want to go is to select a destination on the other side so that the game automatically choses which one out of 3 different portals to go. It's a bit confusing.

**Comment by 4zm0d4n666** [comment]
Also, additional note - the enemy hero that I'm fighting against has not moved for a couple of turns and before that, they just fought against some enemy guarding the Damned Utopia (but not the damned utopia itself) after which they stopped moving.

**Comment by nullkiller** [comment]
What a weird bug. At least we should take a look on it before 1.2 goes out

**Comment by rilian-la-te** [comment]
@4zm0d4n666 maybe defender is a level 20+ armorer specialist? If there is, then damage will be always 1, it is why Tazar is very powerful.

**Comment by DjWarmonger** [comment]
> @4zm0d4n666 maybe defender is a level 20+ armorer specialist? If there is, then damage will be always 1, it is why Tazar is very powerful.

Nope. Expert Armorer gives 15% damage reduction. At level 20 Tazar gets 100% bonus to this specialty, so will have 30% damage reduction in total.
This is how you coded recent secondary skill rework, right?

**Comment by rilian-la-te** [comment]
Yes, it is. But he says than bug occurs in 1.1 too.

**Comment by nullkiller** [comment]
Feels like mods in save files are a bit outdated and there are too much of them. VCMI does not encourage using a lot of mods as they may be incompatible and cause random crashes. I suggest to download a smaller set of mods using our launcher.

**Comment by nullkiller** [comment]
If the problem persists please attach a new save file. Preferably from 1.2 release.
