### ISSUE TITLE
Deprecated bonus converter doesn't like Scouting skill.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#1704]
**Describe the bug**
Game crashes with heroes with scouting specialisation (come from Mods, like Haven)

**Game logs**
![image](https://user-images.githubusercontent.com/29593042/225947062-4bd833c2-c836-4a20-9857-dbe731b333db.png)

**To Reproduce**
1. Download and enable Haven mod
2. Launch game

**Expected behavior**
Game should launch, and scouting specialties should work with new bonus system.

**Actual behavior**
Game crashes

**Did it work earlier?**
Yes

**Version**
 - OS: Windows
 - Version: develop 02b5edd

**Comment by rilian-la-te** [comment]
@misiokles but scouting spec in this form was not working even in 1.1, because SECONDARY_SKILL_PREMY does not had place into counting sight radius. In [master](https://github.com/vcmi/vcmi/blob/master/lib/mapObjects/CGHeroInstance.cpp#L921):
```c++
 int CGHeroInstance::getSightRadius() const
 {
       return 5 + valOfBonuses(Bonus::SIGHT_RADIOUS); // scouting gives SIGHT_RADIUS bonus
 }
```

**Comment by rilian-la-te** [comment]
But my PR will converted it anyway correctly.

**Comment by misiokles** [comment]
Maybe, I didni't test this for a while.
