### ISSUE TITLE
In-game chat errors from Hero Info window (Opened from hero meetup)

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1708]
**Describe the bug**
Clicking in Hero Info Window raises some system related chat errors.

**To Reproduce**
0. Meet 2 heroes.
1. Open hero info window by clicking on first hero portrait image
2. Click set formation to loose
3. Right click any primary skill icon
4. See error in chat

**Screenshots**
![image](https://user-images.githubusercontent.com/15194321/225989180-6322de92-5731-4a89-83c4-53ef605dc1e2.png)

**Version**
 - OS: Windows
 - Version: develop

**Comment by IvanSavenko** [comment]
Unable to reproduce

**Comment by krs0** [comment]
@IvanSavenko Looks like you need to open the hero info window when 2 heroes meet.
