### ISSUE TITLE
Admiral's Hat is seriously broken

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1723]
see video:

https://user-images.githubusercontent.com/1557784/226181222-dd1ce3d4-4297-49ab-aaee-a6e7251c0d94.mov

land <-> water MP re-computation looks correct though.

test map from video: https://github.com/vcmi/vcmi/files/11008302/ah-aw.vmap.zip

**Comment by dydzio0614** [comment]
ithink its not just admirals hat, check how vcminahar cheat works in develop

**Comment by kambala-decapitator** [comment]
> i think its not just admirals hat, check how vcminahar cheat works in develop

not sure what you mean... the cheat works as it should it seems

**Comment by dydzio0614** [comment]
path selection with other boats near you is funny while you are sailing etc.

**Comment by kambala-decapitator** [comment]
thanks. so basically some issue related to (dis)embarking without losing turn.

**Comment by dydzio0614** [comment]
the level of nonsense embark chains differs depending on how far the target tile is IIRC
