### ISSUE TITLE
RMG template Marathon is not valid

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1724]
**Describe the bug**
I get this message in client console:` File CONFIG/DEFAULTTEMPLATES/MARATHON is not a valid JSON file!`

**Version**
 - OS: Windows
 - Version: debug

**Additional context**
there are 2 entries named Marathon in json file:
```
	"Marathon" :
	// (ban fly/DD, 2 player, 31-May-03, midnight design)"
```
and
```
	"Marathon":
	//(ban fly/DD, 2 player, 31-May-03, midnight design) xlu+"
```

**Comment by DjWarmonger** [comment]
Solved in https://github.com/vcmi-mods/vcmi-extras/pull/11

**Comment by DjWarmonger** [comment]
Merged in VCMI Extras.
