### ISSUE TITLE
Warning messages in client console on missing bonuses

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1725]
**Describe the bug**
Message in client console on missing bonuses

**Screenshots**
```
Unrecognized bonus name! (DAEMON_SUMMONING)
Unrecognized bonus name! (FULL_HP_REGENERATION)
Unrecognized bonus name! (KING1)
Unrecognized bonus name! (KING2)
Unrecognized bonus name! (KING3)
Unrecognized bonus name! (SECONDARY_SKILL_PREMY)
Unrecognized bonus name! (SELF_LUCK)
Unrecognized bonus name! (SELF_MORALE)
```

**Version**
 - OS: Windows
 - debug

**Comment by rilian-la-te** [comment]
Look to your mods, it is errors clearly from mods.

**Comment by misiokles** [comment]
These warnings come from Andruids Bonus Icons submod (part of vcmi-extras). This mod should be re-arranged also due to latest bonus system changes.
