### ISSUE TITLE
Errors in client console when starting a map

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1727]
**Describe the bug**
When I start a map the following errors appear
```
Animation  failed to load
Animation  failed to load
Animation  failed to load
Animation  failed to load
Animation  failed to load
Animation  failed to load
Animation  failed to load
Animation  failed to load
```

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Open map All for one
2. Errors in client console

**Version**
 - OS: [Windows
 - Version: debug

**Comment by IvanSavenko** [comment]
@krs0 should be fixed now, please recheck

**Comment by krs0** [comment]
Fixed
