### ISSUE TITLE
Specialty bonuses are not transferred to 3rd upgraded units. 

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#1732]
**Describe the bug**
In OHC we don't have 3rd upgrades. But in Hota mod - yes. Pirates can be upgraded to Corsairs, Corsairs can be upgraded to Seadogs. Anabel's specialty are pirates, so for example, pirates should gain +1 to speed. But it works only for Pirates and Corsairs, but not for Sea Dogs. 
```
		"speed" : {
			"limiters" : { "parameters" : [ "hota.cove:pirate", true ] },
			"type" : "STACKS_SPEED",
			"val" : 1
		} 
```

**Game logs**
N/A

**To Reproduce**
1. Enable Hota mod
2. Choose any scenario with Anabel as starting hero.
3. Build Gunpowders Warehouses (3rd pirate upgrade building)

**Expected behavior**
Sea Dogs should gain +1 speed.

**Actual behavior**
Sea Dogs don't gain +1 speed.

**Did it work earlier?**
I guess not.

**Screenshots**
![image](https://user-images.githubusercontent.com/29593042/226467440-5171671a-99ae-441d-b4b7-40669c5f8a49.png)
![image](https://user-images.githubusercontent.com/29593042/226467549-40338246-91b8-44e0-882c-909e17f7b1a0.png)
![image](https://user-images.githubusercontent.com/29593042/226467668-c617d8e0-f8fa-4bce-98a9-36d42caa38a2.png)

**Version**
 - OS: [ Windows]
 - Version: [daily builds]

**Additional context**
Possible workaround. Edit Anabel's specialty by using new bonus system, like:
```
		"speed" : {
			"limiters" : { "parameters" : [ "hota.cove:pirate", true ] },
			"type" : "STACKS_SPEED",
			"val" : 1
		},
			"speed2" : {
			"limiters" : { "parameters" : [ "hota.cove:seadog", false ] },
			"type" : "STACKS_SPEED",
			"val" : 1
		}
```

**Comment by misiokles** [comment]
Working Anabel's specialty full code (for modders)

```
		"specialty" : {
			"base" : {
				"duration" : [ "PERMANENT" ],
				"limiters" : { "type" : "CREATURE_TYPE_LIMITER" },
				"sourceID" : 177,
				"sourceType" : "HERO_SPECIAL",
				"targetSourceType" : "ARTIFACT"
			},
			"bonuses" : {
				"attack" : {
					"limiters" : { "parameters" : [ "hota.cove:pirate", false ] },
					"subtype" : "primSkill.attack",
					"type" : "PRIMARY_SKILL",
					"updater" : {
						"parameters" : [ 8, 3 ],
						"type" : "GROWS_WITH_LEVEL"
					}
				},
				"attack2" : {
					"limiters" : { "parameters" : [ "hota.cove:corsair", false ] },
					"subtype" : "primSkill.attack",
					"type" : "PRIMARY_SKILL",
					"updater" : {
						"parameters" : [ 10, 3 ],
						"type" : "GROWS_WITH_LEVEL"
					}
				},
				"attack3" : {
					"limiters" : { "parameters" : [ "hota.cove:seadog", false ] },
					"subtype" : "primSkill.attack",
					"type" : "PRIMARY_SKILL",
					"updater" : {
						"parameters" : [ 12, 3 ],
						"type" : "GROWS_WITH_LEVEL"
					}
				},
				"defence" : {
					"limiters" : { "parameters" : [ "hota.cove:pirate", false ] },
					"subtype" : "primSkill.defence",
					"type" : "PRIMARY_SKILL",
					"updater" : {
						"parameters" : [ 6, 3 ],
						"type" : "GROWS_WITH_LEVEL"
					}
				},
				"defence2" : {
					"limiters" : { "parameters" : [ "hota.cove:corsair", false ] },
					"subtype" : "primSkill.defence",
					"type" : "PRIMARY_SKILL",
					"updater" : {
						"parameters" : [ 8, 3 ],
						"type" : "GROWS_WITH_LEVEL"
					}
				},
				"defence3" : {
					"limiters" : { "parameters" : [ "hota.cove:seadog", false ] },
					"subtype" : "primSkill.defence",
					"type" : "PRIMARY_SKILL",
					"updater" : {
						"parameters" : [ 10, 3 ],
						"type" : "GROWS_WITH_LEVEL"
					}
				},
				"speed" : {
					"limiters" : { "parameters" : [ "hota.cove:pirate", true ] },
					"type" : "STACKS_SPEED",
					"val" : 1
				},
				"speed2" : {
					"limiters" : { "parameters" : [ "hota.cove:seadog", false ] },
					"type" : "STACKS_SPEED",
					"val" : 1
				}					
			}
		},
```

**Comment by IvanSavenko** [comment]
Can confirm. From what I see, specialty is propagated only to direct upgrades and not to upgrades of upgrades. 
So alternative upgrades would work, but not 3rd upgrade.

Also, when fixing this, we should make sure that Sharpshooters/Enchanters won't get specialty bonus of Elf/Magi specialists

**Comment by kambala-decapitator** [comment]
In oh3 Gelu is able to upgrade Elves to Sharpshooters

**Comment by misiokles** [comment]
Luckily his specialty doesn't need to use 'true/false' parameter, so he's not part of this issue.
