### ISSUE TITLE
Something wrong with the settings window on Linux

### ISSUE THREAD

**Issue by SoundSSGood** [vcmi/vcmi#1745]
**Describe the bug**
The settings window looks a bit different than on Windows

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11040300/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11040301/VCMI_Server_log.txt)

**To Reproduce**
Open settings window

**Did it work earlier?**
Don't know

**Screenshots**
![settings_linux](https://user-images.githubusercontent.com/87084363/226916717-be6b4c78-f210-45a8-97d5-e09182666cf3.png)

**Version**
 - OS: Kubuntu 22.04
 - Version: [VCMI version] last develop

**Comment by IvanSavenko** [comment]
`"language" : "russian",`
VCMI attempts to use localized texts but fonts from English copy of H3 don't support cyrillic character set.
Workaround 1: install localization mod
Workaround 2: switch language in Launcher to English

Proper solution (for 1.2.1 release perhaps?) would be to reintroduce true type fonts that support most/all needed languages & use them as fallback for when H3 font can't render text.

**Comment by SoundSSGood** [comment]
Checked the second workround. This fixed the issue.
I don’t know if it’s necessary to close the ticket before the full fix in 1.2.1

**Comment by IvanSavenko** [comment]
Added True Type Fonts submod for vcmi-extra, to be used in cases like this.
Nicer / better solution that looks more in line with H3 fonts might be possible, but probably not in near future
