### ISSUE TITLE
Cannot access shipwreck

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1747]
**Describe the bug**
Shipwreck tile is not accessible. 

**To Reproduce**
1. Open map All for one
2. go to top left corner.
3. Try to access shipwreck

**Expected behavior**
Like in OH3 this should be accessible

**Screenshots**
![image](https://user-images.githubusercontent.com/15194321/227007624-0749ea28-fb55-4f18-a973-cfc546f3bbce.png)

**Version**
 - OS: windows]
 - Version: develop

**Comment by IvanSavenko** [comment]
WTF...
Wasn't aware that this is a thing.

What about other water-based objects that are adjacent to land?

**Comment by IvanSavenko** [comment]
Update:
Looks like only shipwreck (two visual versions) are accessible from coast.
All other sea objects can only be accessed from boat

**Comment by kambala-decapitator** [comment]
I also thought that shipwrecks can be accessed only by boat :)

**Comment by nullkiller** [comment]
Checked. Really accessible) Battle happens on ship battleground

**Comment by rilian-la-te** [comment]
@kambala-decapitator @nullkiller @IvanSavenko there is a TheLazy info about shipwreck: https://heroes.thelazy.net/index.php/Shipwreck

FizMig - no mention about that.
