### ISSUE TITLE
Error in client console because of missing animations from battlefield actions mod

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1748]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15194321/227027069-dfb7d407-d254-4bfd-8873-97daf0bf97c0.png)

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Start a fight with army that has both normal and alternate actions (EG: dungeon with troglodytes and harpies)
2. After defend on troglodytes the error appears. Or after clicking on alternate action not available icon.

There is only 1 frame in `icmalt00.json`?
```
{
    "sequences" :
    [
        {
            "group" : 0,
            "frames" :
            [
                "icmalt000.bmp"
            ]
        }
    ]
}
```

Graphic for alternative action disabled button has also some issues... dots from background?
![image](https://user-images.githubusercontent.com/15194321/227028406-b9fb01cc-b689-43b0-9fa2-3cf5e2236d69.png)

**Version**
 - OS: windows
 - Version: debug

**Comment by IvanSavenko** [comment]
Bug with vcmi-extras, will fix in mod repo

**Comment by IvanSavenko** [comment]
Fixed in vcmi-extras, including graphical artifacts
