### ISSUE TITLE
effect range ONLY_ENEMY_ARMY doesn't work?

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#1750]
**Describe the bug**
In HotA mod we have few artifacts that gives negative bonus only for enemy army. For example Demon's Horseshoe decreases enemy's Luck by 1.
Code is simple :
`"bonuses" : [ { "effectRange" : "ONLY_ENEMY_ARMY", "type" : "LUCK", "val" : -1 } ],`
but game/console still says that:

`Error: invalid effect range ONLY_ENEMY_ARMY.`
And bonus is applied only for... player!
There's new bonus/code to replace? 

**To Reproduce**
1. Load attached save (attack.vcgm1)
2. Fight with nearest creature.
3. Click at creature info to see that morale and luck penalties are applied to player units insted of enemy units.

**Expected behavior**
Morale and luck penalties should be applied to enemy units.

**Actual behavior**
oMrale and luck penalties are applied to player units.
**Did it work earlier?**
Yes, but long ago.

**Screenshots**
[Saves.zip](https://github.com/vcmi/vcmi/files/11048453/Saves.zip)

**Version**
 - OS: Windows
 - Version: daily builds

**Comment by rilian-la-te** [comment]
@misiokles yes, there is.

Sorry, ONLY_ENEMY_ARMY cannot handled by the converter. It should be replaced manually to this:

```json
				"propagator": "BATTLE_WIDE",
				"propagationUpdater" : "BONUS_OWNER_UPDATER",
				"limiters" : [ "OPPOSITE_SIDE" ]
```

It is what ONLY_ENEMY_ARMY supposed to do actually. Just short form is replaced by long one.

**Comment by rilian-la-te** [comment]
Does json above working for you?

**Comment by misiokles** [comment]
Seems to work now!

**Comment by rilian-la-te** [comment]
@misiokles if you have other limiters, please, add OPPOSITE_SIDE first, because it was a part of ONLY_ENEMY_ARMY range.
