### ISSUE TITLE
Add retaliation information to attack tooltip in battle

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#1760]
**Describe your proposal**
In addition to damage & kills, we could show information about potential counter-attack in attack tooltip in battle:
- Whether creature is capable of retaliating (e.g. Will retaliate / No retaliations)
- Potential damage dealt to our creature by retaliation
- Potential kills dealt to our creature by retaliation

However this might not be trivial and should account for multiple potential cases:
- ranged units generally don't retaliate, however mods might use RANGED_RETALIATION bonus, allowing retaliation in ranged attacks
- blinded or othervice disabled unit will not be able to retaliate even if he has not spent his retaliations
- if our creature has "no retaliation" bonus, or has a way to guarantee disabling target (e.g. 100% blind)
- if entire enemy unit is destroyed by our attack, it won't be able to retaliate - we might display message like "May retaliate", to account for potential bad luck roll.

**Additional context**
Split from #857

**Comment by dydzio0614** [comment]
simpligyin it to this point is not very helpful - tracking if creature already retaliated + tracking retaliation mechanics that beginners may be unaware of etc. would be main point of feature

**Comment by rilian-la-te** [comment]
@dydzio0614 We need to check, how heroes 5 tracks retaliations. I do not think than we need something more complex than there.

**Comment by krs0** [comment]
Showing not only retaliation damage, but number of potentially killed creatures by retaliation would be nice as well.
In log it is a little lengthy... on interface directly above creatures would be a lot simpler.
