### ISSUE TITLE
Horde Buildings are not built in VCMI when they're marked built in the map editor

### ISSUE THREAD

**Issue by storageer** [vcmi/vcmi#1763]
**Describe the bug**
Horde Buildings do not seem to get built in VCMI, despite them being marked as built in the Homm3 map editor.

**Game logs**
[server_log.txt](https://github.com/vcmi/vcmi/files/11065015/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11065016/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/11065017/VCMI_Launcher_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11065018/VCMI_Server_log.txt)
[Testing Horde Buildings.zip](https://github.com/vcmi/vcmi/files/11065010/Testing.Horde.Buildings.zip)

**To Reproduce**
1. Create a map where one or more Towns have their Horde building built in the map editor
2. Open the map in VCMI
3. Horde buildings are missing for all Town types

**Expected behavior**
Horde building are expected to be built and functioning.

**Actual behavior**
Horde buildings are left unbuilt in all nine Town types.

**Did it work earlier?**
Unknown.

**Screenshots**
Griffin Bastion marked as built in the HoMM3 Map Editor
![Griffin01-maped](https://user-images.githubusercontent.com/121976640/227599735-0ab7f244-69f0-4f56-8550-542731ad51f8.png)

Griffin Bastion missing when opening the map in VCMI 1.1.1
![Griffin02-VCMI](https://user-images.githubusercontent.com/121976640/227599744-797c1a38-8afa-4886-aa1b-7eee6ad8d0de.png)

Griffin Bastion built correctly when opening the test map in the GOG version of HoMM3 Complete
![Griffin03-HoMM3-GOG](https://user-images.githubusercontent.com/121976640/227599748-27094b88-c635-4c36-b9d8-fede03ebe839.png)

**Version**
 - OS: Windows 10
 - Version: VCMI 1.1.1 release version

**Additional context**
1. I call them Horde buildings after this fan wiki, don't know if they have any other names: https://heroes.thelazy.net/index.php/Horde_building
2. I looked for possible duplicates but did not see any
3. Meh context: noticed this while testing for bug 1761

**Comment by DjWarmonger** [comment]
Fixed in [PR](https://github.com/vcmi/vcmi/pull/1765)
