### ISSUE TITLE
Wrong affinities of Dungeon classes.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#1791]
**Describe the bug**
Overlords are might heroes, Warlocks are magic heroes. In VCMI they are opposite.

**Game logs**
N/A

**To Reproduce**
Open heroClasses.json

**Expected behavior**
Overlords should be might heroes, Warlocks should be magic heroes.

**Actual behavior**
Overlords are magic heroes, Warlocks are might heroes.

**Did it work earlier?**
Yes.

**Screenshots**
![image](https://user-images.githubusercontent.com/29593042/228292124-bc87b7ba-adf6-45aa-b0b6-d1e9320a74eb.png)

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: [VCMI version]

**Additional context**

**Comment by misiokles** [comment]
Still something is wrong. Particular heroes have wrong descriptions.
![image](https://github.com/vcmi/vcmi/assets/29593042/426c9517-9e84-41a9-8552-ba2daf3c9bfe)

**Comment by misiokles** [comment]
I guess error is somewhere in oh3 indexes, because for example Lorelei starts with Overlods stats.

**Comment by IvanSavenko** [comment]
Unable to reproduce in current beta. Presumably fixed Please reopen if needed.
