### ISSUE TITLE
At each start of turn AI player uses vcmieagles

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1800]
**Describe the bug**
At each start of AI player turn, it will do a vcmieagle. Can be seen in chat.

**To Reproduce**
1. Start a battle
2. end turn
3. look in chat

**Screenshots**
![image](https://user-images.githubusercontent.com/15194321/228864675-4e90e76c-e637-4ec3-9f11-1e1285cdc4e3.png)

**Version**
 - OS: windows
 - Version: beta

**Comment by rilian-la-te** [comment]
@DjWarmonger do we can add some setting to NKAI to disable eagles for friendly/enemy?

**Comment by DjWarmonger** [comment]
It's not the problem on AI side, just the way allies work.

**Comment by dydzio0614** [comment]
i think nullkiller ai may crash without full map vibisibility, it doesn;t have exploration at all

**Comment by Laserlicht** [comment]
Shouldn't the PR do just that? https://github.com/vcmi/vcmi/pull/1532

**Comment by dydzio0614** [comment]
no, it was hiding "CHEATER!!!!!!" message only

**Comment by krs0** [comment]
@Laserlicht VCMI developers use Slack for communication, if you want to join...
https://slack.vcmi.eu/

**Comment by nullkiller** [comment]
AI will work without vcmieagles. But it will mostly do nothing because it has no routines to explore the map. Maybe it is time to port this thing from VCAI as well)
