### ISSUE TITLE
Map path doesn't disappear after battle, when target hex is the hex where monster was standing

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1807]
**Describe the bug**
Map path doesn't disappear after battle, when target hex is the hex where monster was standing

**Screenshots**
![obraz](https://user-images.githubusercontent.com/15194321/229181731-22cd87a2-98f2-4e96-8c33-899f0186a30e.png)
![obraz (1)](https://user-images.githubusercontent.com/15194321/229181741-c76c4a18-0d5e-48b3-8398-f46017e9e4fa.png)

**Version**
 - Version: beta?

Reported by dydzio

**Comment by dydzio0614** [comment]
Maybe should also work like that for pandoras, prisons, water buoy and other objects that you visit from hex outside object... needs recheck
