### ISSUE TITLE
Magog attack affects not immediately adjacent units

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1808]
**Describe the bug**
When targeting the back of a 2hex unit with maggog attack, it should not affect a unit 2 hex away.

In the screenshot below the 5mil maggogs got hurt!

**Screenshots**
![obraz (2)](https://user-images.githubusercontent.com/15194321/229182462-21a78f78-1651-4ef1-a0c2-16803cf4f7ef.png)

**Version**
 - Version: beta?

reported by dydzio

**Comment by rilian-la-te** [comment]
@krs0 how to reproduce it?

**Comment by krs0** [comment]
Attack griffin's but? :)

**Comment by rilian-la-te** [comment]
@dydzio0614 where fireball visually appear?

**Comment by rilian-la-te** [comment]
Looks like mechanical bug, not targeting bug.

**Comment by storageer** [comment]
Hope I'm not intruding, but Liches' Death Cloud has the same problem: when targeting the "butt", the hit area seems to be still applied on and around the first hex of the unit and not the second hex.

**Comment by rilian-la-te** [comment]
It is logical, I plan to look to this bug today or tomorrow (after a dentist).

**Comment by krs0** [comment]
@storageer VCMI developers use Slack for communication, if you want to join...
https://slack.vcmi.eu/

**Comment by rilian-la-te** [comment]
@krs0 fixes by #1820, please, close.
