### ISSUE TITLE
Teleport bugged - can click more than 1x on creature

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#1809]
**Describe the bug**
You can select creature target mroe than once, and then when clicking destination hex spell doesn't work

**To Reproduce**
1. Start battle while having teleport spell and multiple creature
2. Cast teleport
3. click on creature 1, then on creature 2 (probably also works with clicking same creature 2x) then on empty tile

**Expected behavior**

**Actual behavior**
A clear description what is currently happening 

**Did it work earlier?**
Yes

**Screenshots**

**Version**
 - beta

**Aditional info**
More spells may be bugged as well

**Comment by rilian-la-te** [comment]
I am planning to rework a spell mechanic, and teleport spell too. 

But this bug may have client part, which I do not know currently.

**Comment by dydzio0614** [comment]
this probably needs fix for 1.2 - rework will not help in that

**Comment by dydzio0614** [comment]
and i would be cautious about spell rework so scripting spell stuff + battle AI spellcasting do not get broken

**Comment by rilian-la-te** [comment]
@dydzio0614 I want to rework only deviating spells (adventure ones, teleport, sacrifice) + fix all mechanical bugs which are present (like orb of vulnerability).
