### ISSUE TITLE
Darkness Dragon moves much slower than other units

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#1810]
**Describe the bug**
Darkness Dragon moves over battlefield muchn slower than other units, though it's animation is at least as fast as normal. This looks bad.

Maybe it's caused by the problem that it doesn't fly over obstacles.

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
Install WoG for 1.2, get Darkness Dragonm somewhere. A rich random map with Dungeon fraction can spawn their dwellings. Try Coldshadown's Fantasy or Marathon.

**Did it work earlier?**
No idea, didn't see Darkness Dragons in years.

**Version**
Beta

**Comment by IvanSavenko** [comment]
WOG mod bug?
https://github.com/vcmi-mods/wake-of-gods/blob/vcmi-1.2/content/config/creatures.json#L1088
For comparison, H3 Black Dragon has 0.6 animation time

**Comment by dydzio0614** [comment]
hmmmm do these animation times for OH3 creatures match in VCMI?

**Comment by IvanSavenko** [comment]
"These"?
animation time for Black Dragon comes from H3 files, specifically - CRANIM.TXT.
From my tests their handling in VCMI should match H3.

**Comment by rilian-la-te** [comment]
Looks like mod bug.

**Comment by DjWarmonger** [comment]
Red Dragon does this as well. But WoG has some extra modded red dragon for the purpose of Dragon Heart? Might be complex issue.

I didn't notice it with Black Dragon, though.

**Comment by DjWarmonger** [comment]
The issue was actually that Dragons didn't fly and thus moved slower than they should.
