### ISSUE TITLE
Hero Placeholder bug in Campaign

### ISSUE THREAD

**Issue by storageer** [vcmi/vcmi#1814]
**Describe the bug**
A "Hero Placeholder" gets left behind on the first campaign's second map (Guardian Angels) of RoE after the start of it, which hinders hero pathfinding.

**Game logs**
[server_log.txt](https://github.com/vcmi/vcmi/files/11125618/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11125619/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/11125620/VCMI_Launcher_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11125621/VCMI_Server_log.txt)
[Hero_Placeholder_bug_savefiles.zip](https://github.com/vcmi/vcmi/files/11125615/Hero_Placeholder_bug_savefiles.zip)

**To Reproduce**
1. Get loaded into the map
2. Select hero number 1 (Adela in save file)
3. Move one block to either West or East direction
4. Select path to two blocks in the opposite direction
5. Pathfinding problem should be now visible

**Expected behavior**
"Hero Placeholder" should not affect pathfinding, possibly it should not even be visible with mouseover.

**Actual behavior**
The heroes do not want to walk through the placeholder area, unless they're moved onto it first

**Did it work earlier?**
Unknown.

**Screenshots**
![Hero_Placeholder_01](https://user-images.githubusercontent.com/121976640/229220946-25b99fac-da2e-4c0f-929f-2affb87e7667.png)
![Hero_Placeholder_02](https://user-images.githubusercontent.com/121976640/229220949-46927555-573c-4c20-ba6e-9a5a34f761ee.png)
![Hero_Placeholder_03](https://user-images.githubusercontent.com/121976640/229220956-5af48d69-7b39-44db-b604-6520c4a6998d.png)

**Version**
 - OS: Windows 10
 - Version: VCMI 1.1.1 release version

**Additional context**
Checked for duplicates but found nothing.

**Comment by IvanSavenko** [comment]
Actually might also be a duplicate: https://github.com/vcmi/vcmi/pull/1598

Rechecking to make sure that this bug is also fixed...

**Comment by IvanSavenko** [comment]
Can confirm that this one is fixed in current build, most likely - by #1598
