### ISSUE TITLE
Crash when trying to resurrect Hell Baron

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#1824]
**Describe the bug**
Crash when I hovered "cast spell" cursor over his dead body. Had enough SP to do so.

**To Reproduce**
Hell Baron comes from WoG mod., it's the 8-tier unit.

**Actual behavior**
Hard crash

**Did it work earlier?**
No idea.

**Screenshots**
<img width="1127" alt="Crash Resurrect Hell Baron" src="https://user-images.githubusercontent.com/2566990/229272502-287170fe-543f-4a44-b9b7-ace8a7a16b17.png">

**Version**
Beta

**Comment by DjWarmonger** [comment]
I also got freeze when Hell Baron tried to teleport backwards (rotating?), so it might be something with WoG new graphics submod.

**Comment by IvanSavenko** [comment]
Unable to reproduce. Might be related to / fixed by #1883
