### ISSUE TITLE
Tight formations in towns

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#1825]
**Describe the bug**
Monsters appear in strange (tight?) formations in fort. happened both for AI-player controlled and neutral town.

**To Reproduce**
Attack any town without fort.

**Expected behavior**
Spread formation, as default. Monsters spread apart evenly.

**Actual behavior**
Strange tight formation.

**Did it work earlier?**
Yes it did.

**Screenshots**
<img width="599" alt="Weird formation at fort 2" src="https://user-images.githubusercontent.com/2566990/229274244-cf51e9fd-0374-4cf5-853e-772473dffd34.png">
<img width="604" alt="Weird formation during siege" src="https://user-images.githubusercontent.com/2566990/229274245-22ad51c7-5f33-419b-bc55-a990e818d8d7.png">

**Version**
Beta

**Comment by dydzio0614** [comment]
tbh picking formation would be nice feature - loose, tight, random
