### ISSUE TITLE
When hitting LOAD middle of battle, game crashes when you start next map

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1828]
**Describe the bug**
something is not cleaned on server side when I quit a game mid battle

**To Reproduce**
Start a map 
start a battle
hit load button during battle
start a new map
crash 

various error appear in different trials... example below.

**Screenshots**
![image](https://user-images.githubusercontent.com/15194321/229286716-c9f75937-0f80-44b3-b290-0e886ff5686e.png)

**Version**
 - OS: windows
 - Version: PR moats-landmines

**Comment by rilian-la-te** [comment]
@krs0 please, try beta. Moats-landmines is 1.3 branch, not 1.2, some beta fixes is not present there yet.

**Comment by IvanSavenko** [comment]
Unable to reproduce on current beta

**Comment by krs0** [comment]
Retested in beta. Its fixed!
