### ISSUE TITLE
Game crash at start with forge mod

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1838]
1. Enable mod Forge 2.1.0
2. Launch game
3. Observe crash after video. 

Tested on 1.3.0.4d6b88f10df860f8ffaeb7208c471a36f5db767e

[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11130759/VCMI_Client_log.txt)

**Comment by misiokles** [comment]
Many mods compatible with 1.1 crash 1.2 daily builds. Converting for compatible versions is in progress.
