### ISSUE TITLE
Spells set in commanders.json can't be registered and lead to crash.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#1843]
**Describe the bug**
In commanders.json file we can set diffirent bonuses as ability requirements. In Reworked Commanders we can see:
```
	"abilityRequirements":
	[
		{"ability": ["NO_MELEE_PENALTY", 0, 0, 0 ], "skills": [0,0]},
		//attack + health
		{"ability": ["FEAR", 0, 0, 0 ], "skills": [0, 2]},
		//attack + damage
		{"ability": ["ENCHANTED", 1, "reworked-commanders:spell.attackEnchant", 0 ], "skills": [0, 3]},
		//attack + speed
		{"ability": ["ENCHANTED", 1, "reworked-commanders:spell.preemptiveEnchant", 0 ], "skills": [0, 4]},
		//attack + magic
		{"ability": ["BLOCKS_RETALIATION", 0, 1, 0 ], "skills": [0,5]},
```
Problem is that game doesn't recognize these two spells. And when commander gains f.e. master Attack and Master Damage - game crashes.

**Game logs**
[logs.zip](https://github.com/vcmi/vcmi/files/11131636/logs.zip)

**To Reproduce**
1. Download and enable Reworked Commander mod from beta repo.
2. Launch any map
3. Type vcmiexp 100000 to level quickly
4. Choose in commander leveling window Attack and Damage skills to master them
6. See crash

**Expected behavior**
Commander should learn new perk.

**Actual behavior**
Game crashes

**Did it work earlier?**
No, even in 1.1

**Screenshots**
![image](https://user-images.githubusercontent.com/29593042/229341782-63703854-bbba-482e-850b-8e4a8b49f790.png)

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: [VCMI version]

**Additional context**
Similar issue is in old Stack Experience code. In these modules game doesn't recognize string Id only numericals.
```
				"bonus" :
				{
					"type" : "ENCHANTED", 
					"subtype" : 55 //"spell.slayer"
				},
				"values" : [ 0, 0, 0, 0, 0, 0, 1, 2, 3, 3 ]
```

**Comment by IvanSavenko** [comment]
Identifiers in "abilityRequirements" - found bug, will be fixed
Stack experience - unable to confirm. Can you give me an example? Code is fine from what I see and WoG mod uses identifiers successfully in there.

**Comment by misiokles** [comment]
1. Go to the wake-of-gods/Mods/StackExp/Content/config folder
2. Open conflux_exp.json
3. Rename airElemental bonus into:
```
				"bonus" :
				{
					"type" : "ENCHANTED",
					"subtype" : "spell.airShield"
				},
				"values" : [ 1, 1, 1, 2, 2, 2, 2, 3, 3, 3 ]
			},
```
3. save file and start any map with air elementals in army.
4. Win few fight to level Air Elementals to level 1 in experience.
5. Click at the creature experience icon
6. Observe crash.

Using format 
```
				"bonus" :
				{
					"type" : "ENCHANTED",
					"subtype" : 28 //"spell.airShield"
				},
```
game works as expected
![image](https://user-images.githubusercontent.com/29593042/229579279-fcde06c0-6e72-4e0f-b70a-e0a507c958d9.png)
