### ISSUE TITLE
Bad launcher UX on iOS

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1911]
I suggest to return button which hides mo details.
Currently on iOS I need to scroll mod left and right to see if they are enabled or disabled. I don't see whole picture, what's is installed and what is not.

Also, mod details window and settings tab cannot be scrolled by touch, so I have to touch tiny scrollbar.
One more cosmetic defect is in red on the screenshot

![IMG_2107](https://user-images.githubusercontent.com/9308612/230734467-d6cd4919-4319-4f31-970c-b5c7c5de13ef.jpg)

**Comment by krs0** [comment]
I'm of same opinion. On big screens its ok to have them side by side, but on small screen not really.
Also from usability point of view... the information the user is interested is mod name. Details is extra information that should be hidden until needed.

**Comment by IvanSavenko** [comment]
Even if we were to return hiding of mod details it won't fix too small mod details tab.

I think for such screens we need switch between two and show *either* mod list or mod details, not both.

**Comment by IvanSavenko** [comment]
By the way, @Nordsoft91 what are those large empty areas in layout to left & right?

Is this our bug or those zones are reserved on ios for OS controls (e.g. back/home buttons)

**Comment by kambala-decapitator** [comment]
> By the way, @Nordsoft91 what are those large empty areas in layout to left & right?
> 
> Is this our bug or those zones are reserved on ios for OS controls (e.g. back/home buttons)

reserved zones, I guess Qt handles them by default

**Comment by Nordsoft91** [comment]
@IvanSavenko , those grey zones are from screenshot. On the screen they seem smaller

**Comment by Nordsoft91** [comment]
@IvanSavenko , that's how it looks in 1.1
Are you sure in not fixing that in 1.2? It'll be first what iOS users will see...

![IMG_2154](https://user-images.githubusercontent.com/9308612/230811351-30d1dd1a-9c17-4e75-beb8-ec344730ec90.PNG)

**Comment by IvanSavenko** [comment]
@Nordsoft91 Now double-click on any mod to see details in 1.1.
Same barely usable mod description window.
Both 1.1 and 1.2 work poorly on small screens.

If you can make redesign that will work well on any display, both in mod list mod and mod description modes and do it like today or tomorrow - then sure, go ahead.

I might look into it for 1.2.1 if there won't be constant stream of bugs to fix like we have now (thanks for testing/reporting by the way).

By the way, @Nordsoft91 can you post how settings screen looks at this resolution? Everything OK and fits well I hope?

**Comment by Nordsoft91** [comment]
yes, it works poor but MUCH better than in 1.2, because I can control it by hiding/showing details. In vcmi-1.2 I just don't have control over it.
I don't suggest to make brilliant solution in one day, but rollback this single button
![IMG_2157](https://user-images.githubusercontent.com/9308612/230909370-e14612a2-a61f-4bf3-81dd-827d127642b4.jpg)

**Comment by Nordsoft91** [comment]
Setting is opposite: much better in 1.2. Couple minor items
 - I cannot scroll settings by swipe. I need to touch tiny scroll bar
 - I think better to move cursor to the beginning in version field to see VCMI-x.x.x.hash instead of hash ending
![IMG_2158](https://user-images.githubusercontent.com/9308612/230910768-81bb932b-7020-487e-9ccd-3297665282c3.jpg)

**Comment by Nordsoft91** [comment]
To be fair 20% of downloads from 1.1.1 launcher-having platforms [are ios](https://tooomm.github.io/github-release-stats/?username=vcmi&repository=vcmi),so it's significant number with high potential to growth and definitely not 0.1%

Also, it's not a degradation. Why my suggestion is degradation if I suggest to rollback?

**Comment by kambala-decapitator** [comment]
> To be fair 20% of downloads from 1.1.1 launcher-having platforms [are ios](https://tooomm.github.io/github-release-stats/?username=vcmi&repository=vcmi),so it's significant number with high potential to growth and definitely not 0.1%

doesn't mean it's played on iPhones ;)

**Comment by dydzio0614** [comment]
so far every single polish player I know who downloaded to play on iOS.... has failed to properly follow installation instructions :P

**Comment by IvanSavenko** [comment]
I've never heard about anyone from our playerbase using iPhone for vcmi.
Going purely from issues/discord activity I'd say that ordering is likely:
- Android (not affected by this issue)
- Windows
- Linux
- Mac
- iPhone

Download number are likely to be *very* incomplete - Linux has its own repositories, Windows releases are often copied to third-party sites. And Android has Google Play.

**Comment by dydzio0614** [comment]
well, inability to install contributes to lack of players even if real number of users interested is higher...

**Comment by Nordsoft91** [comment]
@kambala-decapitator , I'm not arguing with order, but I'm arguing with 0.1%/99.9% distribution
