### ISSUE TITLE
[Android]Artifact has no effect!

### ISSUE THREAD

**Issue by tianmaster** [vcmi/vcmi#1920]
Describe the bug

Android, new est daily builds ([VCMI-branch-develop-148cc0b.apk)
The Artifact purchased from Artifact Merchants has no actual effect after equipping the hero. (It must happen)
Sometimes, there is a probability that the Artifact obtained will not produce any effect (probabilistic)

Game logs
Not applicable

To Reproduce

Choose Tower, build Artifact Merchants, and then purchase an Artifact that will no longer have any effect.
The starter comes with an Artifact that can work normally

Did it work earlier?
It seems that it worked properly in previous versions

Screenshots
![IMG_20230409_210836](https://user-images.githubusercontent.com/51704354/230775901-96e76961-3b08-44b9-9a81-ce7d69a28759.jpg)
![IMG_20230409_213529](https://user-images.githubusercontent.com/51704354/230775906-9eb2a233-9115-4f58-8f48-787d87071d18.jpg)

Version

OS: Android MIUI 14.0.3
Version: VCMI-branch-develop-148cc0b
Additional context

**Comment by kambala-decapitator** [comment]
it seems your screenshot wasn't uploaded

**Comment by IvanSavenko** [comment]
Not reproducible on beta. Or at the very least, they work in hero screen.
Another android-specific / single-process bug? Or something broken in develop branch? Or I needed more attempts to repro?

**Comment by tianmaster** [comment]
> 您的屏幕截图似乎未上传

Edited, sorry!

**Comment by IvanSavenko** [comment]
Most likely bug somewhere within these commits: https://github.com/vcmi/vcmi/compare/1.2.1...148cc0b
Perhaps #1706 ? @rilian-la-te made some changes to bonus system in there.

**Comment by rilian-la-te** [comment]
Only one change for bonus system in #1706 - uint64_t version + update bonus tree when unit is moved on battle. Will check for sure.

**Comment by IvanSavenko** [comment]
Hmm... backpack limit from #1717 by @SoundSSGood then?

**Comment by rilian-la-te** [comment]
We can just revert #1706 and check.

**Comment by SoundSSGood** [comment]
> We can just revert #1706 and check.

It is not so easy. The bug is reproduced very rarely.


> Hmm... backpack limit from #1717 by @SoundSSGood then?

I guess the root of the problem is not in the artifacts code. Perhaps somewhere in the bonus system.

**Comment by rilian-la-te** [comment]
@SoundSSGood on develop I see than artifact from forgeotnoldorking has no effect. And picked up artifact has effect. Maybe we miss an attachment of artifacts somewhere?

**Comment by SoundSSGood** [comment]
> Maybe we miss an attachment of artifacts somewhere?

Maybe. But this is a completely different bug.
I mean the bug from this issue when Blackshard of the Dead Knight and Helm of Chaos stopped working.
And from here https://github.com/vcmi/vcmi/issues/2128 where all artifacts stop working for some reason.

**Comment by IvanSavenko** [comment]
Can confirm - regression from PR #1717 
Bug somewhere between these commits:
https://github.com/vcmi/vcmi/compare/9287d1b837eb62f874a8e72e993976c345f48b41...b875da
In other words, commits from this PR

**Comment by IvanSavenko** [comment]
Localized regression to this commit: https://github.com/vcmi/vcmi/commit/9f8aa252977b7f56514363c31071a6f4c3adab3a
