### ISSUE TITLE
hotaWateringPlace game crash

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1924]
HotA configurable objects file 
[mod.json.txt](https://github.com/vcmi/vcmi/files/11186191/mod.json.txt)

test map
[hotatestobjects.vmap.zip](https://github.com/vcmi/vcmi/files/11186197/hotatestobjects.vmap.zip)

**Game logs**
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11186188/VCMI_Server_log.txt)

**To Reproduce**
1. Download hota mod 1.5.10
2. Go to mods/hota/mods/HotA configurable objects
3. Override mod.json with one attached above
4. Copy attached map to maps folder
5. Start scenario map called `hota test objects`
6. Hire hero, vcminahar, vcmieagles
7. Visit Watering place

Steps 2-6 are optional if it's convenient to visit watering place in other map

**Expected behavior**
Movement points reward

**Actual behavior**
Crash

**Did it work earlier?**
It's a new hota object, but I suppose it worked when it was made

**Version**
 - Version: beta (1.2), develop (1.3)

**Comment by IvanSavenko** [comment]
1.3 specific, fix is already in beta branch, will be fixed once beta gets merged into develop

**Comment by Nordsoft91** [comment]
Confirm fix in 1.2
