### ISSUE TITLE
You can see the reward of seers hut if AI visited it.

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1952]
**Describe the bug**
When you hover on map a seers hut visited by AI, you will see the reward.

**To Reproduce**
1. Start All for One as Blue!!!
3. vcmieagles
4. End 1-2 turns
5. Hoover on Reds seers hut left or red mains castle

**Screenshots**
![image](https://user-images.githubusercontent.com/15194321/231516293-5bf6cf19-a62e-47fa-8645-bfbd44fcf842.png)

Reported here: https://bugs.vcmi.eu/view.php?id=2856

**Comment by IvanSavenko** [comment]
- Will fix tooltip for 1.2 (core.seerhut.names and defeating rings)
- AI visiting fix goes to 1.3

**Comment by krs0** [comment]
Splitted the UI part.
https://github.com/vcmi/vcmi/issues/1972

**Comment by krs0** [comment]
In this particular case that's the enemies seers hut quest. But good point, allies should see your quests.
