### ISSUE TITLE
When AI completes a quest player gets reward from seers hut

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1953]
**Describe the bug**
AI completes a quest, players visits seers hut and gets reward. That's communism :)

**To Reproduce**
1. Try attached map
2. Visit seers hut after Solmyr is defeated by AI

[2856_Kill Hero.zip](https://github.com/vcmi/vcmi/files/11213566/2856_Kill.Hero.zip)

Described here: https://bugs.vcmi.eu/view.php?id=2856

**Comment by dydzio0614** [comment]
:rofl:

**Comment by IvanSavenko** [comment]
Interesting, is this not how H3 works? H3 actually tracks who killed the hero/monster?

**Comment by dydzio0614** [comment]
IIRC H3 does track that, but not sure

**Comment by DjWarmonger** [comment]
Yep, I'd double-check it. Most likely some custom maps depend on it.
