### ISSUE TITLE
Siege battle not starting. Towers do not shoot.

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1955]
**Describe the bug**
In a specific map siege battle is not starting. Only autocombat works.
Simple test map with a castle fully built.

@Nordsoft91 Seems to be from tactics hero!

**To Reproduce**
Open Test map
Attack Rampart castle

https://user-images.githubusercontent.com/15194321/231538333-c5faa7f6-f34a-4ed4-8997-010ff28e7fe9.mp4

**Version**
[A Capitol Test.zip](https://github.com/vcmi/vcmi/files/11214213/A.Capitol.Test.zip)

 - OS: Windows
 - Version: develop

**Comment by rilian-la-te** [comment]
@krs, just tested on linux on #1932 - all is working.

**Comment by krs0** [comment]
with a hero without tactics it works!

**Comment by rilian-la-te** [comment]
@krs I tried with tactics, it also works.

**Comment by rilian-la-te** [comment]
@krs0 reproduced with Isra on All for One map.

**Comment by IvanSavenko** [comment]
Still relevant? Or has been fixed?

**Comment by rilian-la-te** [comment]
I think I fixed it already.

**Comment by rilian-la-te** [comment]
but need futher testing.

**Comment by IvanSavenko** [comment]
Seems to be fixed now
