### ISSUE TITLE
UI is not active during siege with tactics

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1960]
**Describe the bug**
Not sure, what exactly is root cause, but assuming that battle
[A Capitol Test.h3m.zip](https://github.com/vcmi/vcmi/files/11214641/A.Capitol.Test.h3m.zip)

**To Reproduce**
1. Install build from https://github.com/vcmi/vcmi/actions/runs/4569392274
2. Start map attached (called "A capitol test")
3. Move hero to the right and attack rampart castle

**Expected behavior**
Tactics buttons and actions are available

**Actual behavior**
All actions except auto-battle are not available

**Did it work earlier?**
yes, before https://github.com/vcmi/vcmi/pull/1706

**Screenshots**
(https://h3vcmi.slack.com/files/U049Y8UPH4Z/F052H8HQHLP/untitled_video_-_made_with_clipchamp.mp4)

**Version**
Bisect:
e1c3550 - bad
4d6b88f - good
4d6b88f + PR1706

**Additional context**
Theoretically can be broken in one of those PRs, but it's barely possible:
#1854, #1852, #1848, #1853

**Comment by rilian-la-te** [comment]
@Nordsoft91 cannot reproduce it with neutrals on my Linux develop build. Only if AI hero with tactics stands - can see this sort of bug. Will provide a screen cast later.
