### ISSUE TITLE
Cannot Open map in game or OH3 map editor.

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1963]
**Describe the bug**
A specific map cannot be opened in OH3 map editor or Hota map editor, and is not listed in game.
But! VMCI editor opens it!

**Screenshots**
![image](https://user-images.githubusercontent.com/15194321/231557782-70d4919c-0ea7-4616-ac84-4b719254bb52.png)

[2977_Quest test.zip](https://github.com/vcmi/vcmi/files/11214945/2977_Quest.test.zip)

**Comment by misiokles** [comment]
Version 51 is WoG map. With current WoG mod structure, vcmi doesn't open wog maps. With old wog mod (version 8.x.x), vcmi opens them.
