### ISSUE TITLE
Player shouldn't be able to control defending units, when his external dwellings are attacked

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1965]
**Describe the bug**
If a player owns an external dwelling and another player tries to take it, AI should fight not dwelling owner.

Needs to be fixed like in OH3, but this is a very nice VCMI feature, that should be made an option that can be activated via mod.

**To Reproduce**
1. Start attached map in hotseat
2. take dwelling
3. end turn until new week
4. take dwelling with Blue player
5. in fight red controls the angel!!!

[A Dwelling Guards Test.zip](https://github.com/vcmi/vcmi/files/11215065/A.Dwelling.Guards.Test.zip)

Mantis: https://bugs.vcmi.eu/view.php?id=2564

**Comment by nullkiller** [comment]
It is not AI related if I understood it correctly. Human can control defending creatures of 5+ dwelling levels.
Checked the map. With controlai cheat you can control both attacker and defender. It may be very old bug actually.

**Comment by nullkiller** [comment]
Looks like we need to treat defender of dwelling as a neutral player always
