### ISSUE TITLE
Windmill pallets are drawn behind some objects

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1966]
Seems more of a RMG problem since in map editor, creator can decide order placement.

**Screenshots**
![image](https://user-images.githubusercontent.com/15194321/231571771-c972e665-7759-444f-954f-5e7193174f4e.png)
![image](https://user-images.githubusercontent.com/15194321/231573432-9729fe28-b1d2-4f24-b0c8-94eb04aced3b.png)

**Version**
 - OS: Windows 
 - Version: develop

**Comment by IvanSavenko** [comment]
Not a bug. H3 behavior.

**Comment by IvanSavenko** [comment]
Depends on h3m to be precise.
- if windmill was placed first, it will appear behind trees
- if trees were placed first, they will appear behind windmill.

H3 being H3...

**Comment by krs0** [comment]
I would correct it.... Its very ugly in some places...
![image](https://user-images.githubusercontent.com/15194321/231573359-82a7603f-e45e-4fa3-a949-2272458fdd99.png)

**Comment by krs0** [comment]
then fix only for RMG? like this one?

**Comment by IvanSavenko** [comment]
Yes. RMG need to place such objects after obstacles (or reorder objects)

**Comment by DjWarmonger** [comment]
Well, for now all the interactive objects in RMG are placed first and the obstacles come at the end.

**Comment by IvanSavenko** [comment]
Reindex - also possible, as long as there are no objectID's stored somewhere.
