### ISSUE TITLE
Description window of artifacts

### ISSUE THREAD

**Issue by SoundSSGood** [vcmi/vcmi#1967]
I am refactoring code related to artifacts windows. And is needed to decide how the description box will look like.
VCMI supports more than one combined artifact per simple one. Although it is not currently used in any of the mods, but I want to know what to do with this code. 
So, at the minimum screen resolution is 800x600, as I see we have several options.

1. First option - it may be limited to two.
![artDesc0](https://user-images.githubusercontent.com/87084363/231577632-fcd72b6b-80dd-4aef-8458-38255b3b9ee3.png)

2. The second - the list of components may be moved somewhere else. This will free up enough space.
![artDesc1](https://user-images.githubusercontent.com/87084363/231577666-df5b3d66-5126-4065-ab5a-1de180b69dbf.png)

3. Scroll bar. But in this case, the description should remain on the screen after right click.

**Comment by IvanSavenko** [comment]
What about:
- If multiple combined artifacts are possible only show names of such artifacts (option 2). 
- If only single artifact is possible, show all components (option 1)

**Comment by SoundSSGood** [comment]
> * If multiple combined artifacts are possible only show names of such artifacts (option 2).
> * If only single artifact is possible, show all components (option 1)

That sounds good.
Well, if not displaying the components is okay. I will follow your suggestion.

**Comment by krs0** [comment]
Would it not look better if the icon would be moved below title? and without listing a second time its name?

**Comment by dydzio0614** [comment]
i would keep current layout if it resembles h3 original layout more

**Comment by krs0** [comment]
Can constituent parts be listed with small icon?
![image](https://user-images.githubusercontent.com/15194321/231590753-9e065f08-6525-4a94-ae36-152efff28aa6.png)
Combined artifact should have image as well.

**Comment by rilian-la-te** [comment]
@krs0 the problem than artifacts only have one icon. And I do not know if we support downscaling.

**Comment by misiokles** [comment]
`VCMI supports more than one combined artifact per simple one. Although it is not currently used in any of the mods`
I don't know if I understand correctly, but WoG needs some artifacts to create Barbarian Lords Axe Of Ferocity and HotA uses the same set of artifacts to combine Ironfist Of The Ogre.

**Comment by krs0** [comment]
Ok. But these will not affect window. The artifact will be part of 2 separate combined artifacts.... that also happen to have same components.

**Comment by IvanSavenko** [comment]
Those are of the same size.

Smaller icons do exists - for pickable objects on adventure map

**Comment by rilian-la-te** [comment]
@IvanSavenko why they is not used inside CComponent then?

**Comment by SoundSSGood** [comment]
I'm going to implement without small icons. As suggested here.
> * If multiple combined artifacts are possible only show names of such artifacts (option 2).
> * If only single artifact is possible, show all components (option 1)

> Would it not look better if the icon would be moved below title? and without listing a second time its name?

And will try to move the icon below title. I think it is a good point.
