### ISSUE TITLE
Map can be scrolled during enemy turn

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#1976]
**To Reproduce**
1. Start game
2. Use vcmieagles to see enemy turn
3. End turn
4. Try scrolling map via window edge scrolling

**Expected behavior**
Map can not be scrolled during enemy turn

**Actual behavior**
Map can be scrolled during enemy turn, interfering with AI hero movement animation

**Did it work earlier?**
Most likely worked in 1.1

**Version**
 - VCMI 1.2

**Comment by krs0** [comment]
I say expected behaviour is: map scrolls ok and does not interfere with enemy hero movement animation.
Default behaviour is center on hero... this should be an option. And if this centering is off everything is fine.

We have now a prototype for spectator mode, where this option is implemented.

**Comment by DjWarmonger** [comment]
I believe it should be possible to toggle hero following with a hotkey, people will want it.
