### ISSUE TITLE
Launcher fails to display download progress

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#1978]
**Describe the bug**
When installing mods via Launcher, vcmi fails to display current download progress, progress bar stays at "unknown" for the entire time of download

**To Reproduce**
1. Start Launcher
2. Install any mod, preferably big one, e.g. WoG or HotA
3. Look at download progress bar at the bottom

**Expected behavior**
Launcher should display progress bar with text like "Downloading file, %d out of %d kbytes downloaded"

**Actual behavior**
Progress bar never initializes with download size

**Did it work earlier?**
Definitely worked originally, may have been broken when mods hosting was moved to github

**Version**
 - VCMI 1.2

**Comment by krs0** [comment]
I can add that sometimes download just blocks. And you need to abort and retry. Definitely happening for bigger mods like WoG or HotA.

**Comment by IvanSavenko** [comment]
Presumably fixed in linked PR.

*Some* cases are not fixed, due to Github not reporting total size, but even in such cases Launcher will display downloaded size instead of showing broken progress bar.
