### ISSUE TITLE
Thunder Helmet does not reduce Spell Power when SP is 1

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1987]
> Edit: OH3 SP and Knowledge cannot be decreased lower than 1

**Describe the bug**
It does not work for 2 SP, it only works if power is higher than 2
![image](https://user-images.githubusercontent.com/15194321/232119485-e3b240a1-6016-4c44-9fb0-f9ea009a9d16.png)

On a hero with 1 SP Thunder Helmet does not reduce it to 0 (-2 SP bonus from artifact)
![image](https://user-images.githubusercontent.com/15194321/232119425-6e2ee4e0-f88c-400b-bfb6-4c5ab42278cc.png)

**To Reproduce**
1. Wear Thunder Helmet
2. Wear Breast Plate of Petrified Wood
3. See spell power not substracting

**Comment by rilian-la-te** [comment]
@krs0 it should not work for 1 sp, but it should substract 2 sp to 1 sp. Will look in my bonus redesign.

**Comment by krs0** [comment]
What do you mean? 
There should not be negative bonuses, but it should decrease to 0.

**Comment by IvanSavenko** [comment]
@krs0 Check H3
Attack and Defence can be decreased to 0
Spellpower and Knowledge can be only decreased to 1 (and NOT to 0)

**Comment by krs0** [comment]
Wrong report -> closed.

**Comment by kambala-decapitator** [comment]
@krs0 wrong reports should be closed as "not planned"

**Comment by krs0** [comment]
Super intuitive :)
But if thats the rule... :)
