### ISSUE TITLE
Campaign prolog voice output

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#1992]
**Describe the bug**
Currently the voice output for the campaign prolog isn't played.

**To Reproduce**
Start Campaign

**Expected behavior**
In OH3: There is a voice output next to the video.

**Actual behavior**
No voice

**Comment by rilian-la-te** [comment]
We does not have voice output in all video, in 3D0 in prolog too.

**Comment by IvanSavenko** [comment]
Campaign videos actually don't have sound. Instead they have separate music track and separate voice-over track.
Missing feature since we don't use that info right now.

**Comment by IvanSavenko** [comment]
More details:
- we already have (presumable) correct list of voice files in campaignMedia.json
- in H3 this mapping is hard-linked to campaign files - audio will play only when playing H3 campaings. 
- in H3 launching *any* custom campaign (even if this is extracted, unmodified h3c file) will play without audio

So we need to add some flag to H3 campaigns and play them with audio. Or add "campaign overrides" similar to our "map overrides" and inject required data into parsed h3c on loading.

**Comment by peterpaulis** [comment]
i hope this makes it into some build as it breaks the campaign experience

**Comment by IvanSavenko** [comment]
Eventually - yes. We still have a lot of stuff to do unfortunately.

**Comment by peterpaulis** [comment]
could this be released to 1.3.2 instead of 1.4.0?

**Comment by IvanSavenko** [comment]
> could this be released to 1.3.2 instead of 1.4.0?

Probably no.
1) 1.3.2 is already finalized, no more new changes
2) This change can not be backported to 1.3 branch as it and needs adjustments
