### ISSUE TITLE
HD executable icon for windows

### ISSUE THREAD

**Issue by tytannial** [vcmi/vcmi#1993]
**Describe your proposal**
Draw a HD executable icon for windows :D

**Additional context**
![image](https://user-images.githubusercontent.com/11215623/232187628-114f94b8-542a-483f-b9f7-1d6d4534c7fc.png)

icon not feet the modern system hd icon

**Comment by IvanSavenko** [comment]
We actually have one, but no idea how to attach it to executable on Windows:
https://github.com/vcmi/vcmi/blob/develop/client/icons/vcmiclient.512x512.png

**Comment by tytannial** [comment]
OK...i will have try to make one 😊

**Comment by Laserlicht** [comment]
I've created one (see pull request):

![grafik](https://user-images.githubusercontent.com/13953785/232211591-f9f318a7-8727-4c8b-9d7b-bd2d26542065.png)

**Comment by krs0** [comment]
Am I the only one who dislikes the VCMI logo?

here the VCMI logo
![image](https://user-images.githubusercontent.com/15194321/232307432-11c7d1d8-6fdf-4abc-95e1-df49cffcaed3.png)

Here various H3 shield logos...
![image](https://user-images.githubusercontent.com/15194321/232307376-a3c4a50c-6277-442a-b0a0-ee4ee64b494f.png)

Here an automaker logo
![image](https://user-images.githubusercontent.com/15194321/232307407-ab291020-0e4f-4d9c-9043-306291164290.png)

**Comment by IvanSavenko** [comment]
Can't say that I am huge fan of our current icon, but I do associate it with VCMI, so not sure if we should significantly change it.

If we have someone interested in redesign then go ahead I guess, but IMO icon should stay similar to how it is now - yellow pixelated "VCMI" text on brown shield

**Comment by Alexander-Wilms** [comment]
I've experimented with [craiyon.ai](https://www.craiyon.com/). If one tries a few prompts and gets a nice result, it could then be recreated manually as a SVG.

![image](https://github.com/vcmi/vcmi/assets/3226457/204657eb-0267-47ec-9069-ab06b08dfd3a)

**Comment by krs0** [comment]
To me something like the first one looks great. But I would have VCMI written in the shield in some old font and keep original colors.

**Comment by DjWarmonger** [comment]
I'd like to take this style: 
![image](https://github.com/vcmi/vcmi/assets/2566990/88c4f535-0752-42ef-9884-58b50bda1d92)
Then recolor the shield and add teh font similiar to current VCMI icon.

**Comment by IvanSavenko** [comment]
Not against some experimenting but not sure if we should stray too far from current icon / H3 icon. So perhaps:
- use same shield shape as in H3 - e.g. that spiky notch on top of the shield, wide metal framing, nails / rivets on perimeter.
- probably remove griffin to avoid having it too similar to H3 and use 2x2 checkerboard instead. Probably recolored to brown & white instead of blue & white to make it somewhat similar to current icon
- Keep pixelated VCMI text on top of shield

These are just my suggestions, feel free to experiment with other approaches, but keep in mind that players should be able to recognize vcmi icon even after the change

**Comment by Alexander-Wilms** [comment]
A result I got using https://text2img.org/generator with this prompt:
`game icon showing a medieval shield, azure blue medieval heater shield showing a golden heraldic lion with a silver border with rivets, white background, trending on ArtStation, simple background, 3d render, icon for a fantasy game`

![image](https://github.com/vcmi/vcmi/assets/3226457/2c3078ba-0520-4c28-b1e6-622c2eff6ac8)

**Comment by misiokles** [comment]
Looks quite good.

**Comment by jcialkowski** [comment]
In my opinion, it's a little too inspired by World of Warcraft's Alliance/Horde theme.

**Comment by Alexander-Wilms** [comment]
I wouldn't keep this split lion's head either. This image just turned out quite fitting in regard to @IvanSavenko 's suggestions.

So perhaps we could
* recolor the metal strip to silver (or keep it gold?)
* use a 2x2 checkerboard pattern, which would also be more recognizable at smaller sizes

![image](https://github.com/vcmi/vcmi/assets/3226457/d4c31aaf-df23-430f-8229-6d22bbcc4180)

**Comment by Laserlicht** [comment]
Wouldn't a vector logo be more modern compared to a 3d style logo?

If I look on my app list on the smartphone there are almost none not vector logo.

**Comment by madaosoul** [comment]
My proposition - "Morale Eagle" on a crest fitted with brown H3-leather style texture, with some stars. Keeps the VCMI logo's color scheme and is very universal imho. Another idea I just had would be ingame icon showing knight's helmet when you hover mouse cursor over your hero (again, on the same texture, but without stars). 
![image](https://github.com/vcmi/vcmi/assets/12452528/a5090ef5-5581-4e83-8f1d-deb666793865)

**Comment by DjWarmonger** [comment]
^More or less the style I meant, but replace the Eagle with a text "VCMI", as it is now. And remove the stars - icon needs to be simple, clear and recognizable.

Complains about current icon was that it hardly resembles any Heroes artwork at all.

**Comment by IvanSavenko** [comment]
I'd use 1st icon from here:
![image](https://github.com/vcmi/vcmi/assets/3226457/817189f0-3180-4c98-b5ef-159089d57515)

Possibly with VCMI text on top. (depending on how it will look).
Another option is solid brown instead of checkerboard - e.g. like on @madaosoul image, but without eagle/stars.

**Comment by Alexander-Wilms** [comment]
Two more options

![image](https://github.com/vcmi/vcmi/assets/3226457/5318c1c2-b279-4f29-b66e-57461dad3baa)

**Comment by DjWarmonger** [comment]
Nice, but can't you just leave the colors and font size as current, only use new shield graphics?
Because the main problem with existing icon is that it barely looks like a shield at all.

**Comment by Alexander-Wilms** [comment]
![image](https://github.com/vcmi/vcmi/assets/3226457/f15dda59-44d5-43f2-b0a9-0adda45ab60c)

**Comment by IvanSavenko** [comment]
11-13 feel like "generic mobile strategy game number 12345"

Can you show text from 15th with shield from 2nd?
Can you reduce/remove shading from 15th? Right now left and right side have very high contrast.

**Comment by DjWarmonger** [comment]
Let me do this myself:
![VCMI logo new](https://github.com/vcmi/vcmi/assets/2566990/9a1471cc-837e-407d-9f0f-507bf6b9a636)

**Comment by dydzio0614** [comment]
@madaosoul still got some more:

![obraz](https://github.com/vcmi/vcmi/assets/9436577/060d594f-e81f-4f9f-ac96-c0ac17ffa772)
![obraz](https://github.com/vcmi/vcmi/assets/9436577/39f350e2-4505-4fe6-af7e-e983112b0789)

I like new VCMI text, original feels fitting minecraft-like game

**Comment by rilian-la-te** [comment]
@dydzio0614 I like last icons, with eagle and star and VCMI text)

**Comment by IvanSavenko** [comment]
@dydzio0614 
Now downscale those to ~48x48 or even 32x32 because this is what most players will see.

**Comment by Alexander-Wilms** [comment]
![image](https://github.com/vcmi/vcmi/assets/3226457/0cb48cce-225f-4df5-9ca9-57723763ca45)

**Comment by dydzio0614** [comment]
![obraz](https://github.com/vcmi/vcmi/assets/9436577/060d01ff-e070-4f3e-9e0a-a4fb8706e003)

**Comment by IvanSavenko** [comment]
From my point of view, 17 & 20 are best options. 

Don't mind playing with font a bit (since I assume dydzio is not fan of pixelated text?). However text should probably stay larger than shield, not embedded into it.

**Comment by DjWarmonger** [comment]
We could try to combine checked board from #17 and silver frame from #20, too.

**Comment by krs0** [comment]
Ahhhh... the eagle dropper icon :)

+1 vote for #20

**Comment by DjWarmonger** [comment]
It's clear and visible. Eagle is a detail no one will see in a tiny icon. Also it's hard to tell what it really represents - we must somehow  connect obscure name "VCMI" with Heroes of Might & Magic, and clear text helps.

Besides, we have already a number of votes for #17 (followed up by #20) on Discord.

**Comment by luk3ZPL** [comment]
Checkerboard is more obvious than not so obvious "eagle". Eagle could means everything, so it is bad idea.

**Comment by Alexander-Wilms** [comment]
![image](https://github.com/vcmi/vcmi/assets/3226457/c8b1d574-4fc9-474a-b908-f9e9327d4433)

![image](https://github.com/vcmi/vcmi/assets/3226457/6e2413d1-ed78-4f76-a0d5-23f1bbdfc7b5)

![image](https://github.com/vcmi/vcmi/assets/3226457/08792e10-d6be-4276-907e-c2c88f7408cc)

**Comment by jcialkowski** [comment]
I  can't shake off the feeling that the shape of the icons is similar to an antivirus icon (like Windows Defender), especially with the checkerboard pattern :D In my opinion (that in fact doesn't matter :D) the icon's shape should closely resemble the OH3 icon, while incorporating different content

**Comment by DjWarmonger** [comment]
![image](https://github.com/vcmi/vcmi/assets/2566990/9e06cb1b-a12d-4526-b4fd-383a19be8fe2)
Looks like we have a clear winner here.

**Comment by IvanSavenko** [comment]
@jcialkowski 
But that's exactly how H3 icon looks? 
- AB/SoD icons are different (which use AB blade and Sandro portrait)
- H3:RoE and H3:Complete use shield, with very similar shape to suggested here, but with Erathia griffin on blue background as coat of arms.
- HD Edition icon is similar, but blue background was replaced with blue-and-white checkerboard.

**Comment by dydzio0614** [comment]
BTW H3 streamer asks if he can have icons 2 and 16 in higher resolution for non-VCMI use

**Comment by GraionDilach** [comment]
As a lurker who did vote on Discord, I find all three proposals more internally consistent than the current version (although the greenish shadows on the golden rim looks weird). The current shield is overly stylized especially with the shadow gradient and the pixel font doesn't match stylistically to it.

**Comment by Alexander-Wilms** [comment]
Here are the source files of all the VCMI icons shown above: [vcmi_icons.zip](https://github.com/vcmi/vcmi/files/12438834/vcmi_icons.zip)

Do you require all the sizes listed here?

https://github.com/vcmi/vcmi/tree/develop/client/icons

And should the 22px and 16px versions omit the VCMI text, since it's too small to recognize anyway?

**Comment by DjWarmonger** [comment]
Thank you, Alexander :)

Suprisingly, the large version of #22 is re-paint of some older versions and when zoomed, glitches are visible.

**Comment by Alexander-Wilms** [comment]
Yes, I'll create a clean version for the PR

**Comment by IvanSavenko** [comment]
> Do you require all the sizes listed here?

Don't know actually. Those are only used by OS / file manager, not by vcmi itself.
Might be better to provide all of them, but don't see any need to bother with nice downscaling of tiny icons. They should be used rarely anyway. So keeping text is probably OK.

> Yes, I'll create a clean version for the PR

Thanks :)

**Comment by jcialkowski** [comment]
> @jcialkowski But that's exactly how H3 icon looks?
> 
> * AB/SoD icons are different (which use AB blade and Sandro portrait)
> * H3:RoE and H3:Complete use shield, with very similar shape to suggested here, but with Erathia griffin on blue background as coat of arms.
> * HD Edition icon is similar, but blue background was replaced with blue-and-white checkerboard.

Other than the fact that it resembles a shield, I don't see many similarities (I'm talking about the shape/outline only). If you take a look at this shield:
https://github.com/vcmi/vcmi/issues/1993#issuecomment-1685207413 and compare it with the one that's been chosen, you should notice the differences. In my opinion, the shield proposed by @madaosoul (https://github.com/vcmi/vcmi/issues/1993#issuecomment-1687184980), after some improvements (it could have the same content as the selected logo), would be the best option. but it's not to me to decide :)
