### ISSUE TITLE
1.2.0 doesn't see saves from 1.1.1

### ISSUE THREAD

**Issue by Adewi** [vcmi/vcmi#1995]
I just updated the iOS version of the game. I copied backed up Saves folder with ~80 files. Game only sees saves made on 1.2.0

1. Copy game saves from 1.1.1 into Saves folder
2. Try to load it in game Load game -> Single (or multi) player
3. There will be only saves made on 1.2.0

**Expected behavior**
The game should read saves from older versions, since they use same file format

**Actual behavior**
The game doesn't read older saves

**Version**
 - OS: iOS
 - Version: 1.2.0 (saves from 1.1.1)

**Additional context**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11238930/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/11238932/VCMI_Launcher_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11238933/VCMI_Server_log.txt)

**Comment by nullkiller** [comment]
I feel like it is intentional. Save compatibility blocks development. Some features may be postponed (and eventually abandoned) just because developers can not maintain save compatibility (too expensive in terms of time). I afraid next release it will be the same

**Comment by nullkiller** [comment]
From vcmi.eu
Please note that save games from v1.1 are incompatible with v1.2!

**Comment by Adewi** [comment]
Oh right, thanks :)
