### ISSUE TITLE
Neutral towns use different logic for creature growth in H3

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2000]
Wasn't actually aware that this is a thing, might need verification in case if I misunderstood something

Neutral towns need separate logic for creature growth. After quick test in H3 this is what I found:
- In neutral towns, creature growth is multiplied by 50% (TODO: check how this stacks with other modifiers, e.g. Castle or prebuilt hordes)
- If town garrison on new week grows and dwelling for new creature is build, recruited creatures should be substracted from accumulated growth

**To Reproduce**
1. Start on Arrogance
2. Go to town neutral to south-east from starting location
3. Wait for new week

**Expected behavior**
Exact logic should be checked in H3

**Actual behavior**
Creatures in neutral towns accumulate using their unmodified base growth.

**Did it work earlier?**
Very unlikely

**Version**
 - VCMI 1.2

**Comment by krs0** [comment]
Can you please clarify a little what seems to be the problem?

Is this bug? present only when town should remains neutral?
Is base creature growth not correct?

**Comment by dydzio0614** [comment]
there is complex logic for H3 for this, part of it is described here (I auto translated from polish)

Generally, in 1 week it randomizes whether there is to be defense of this city (50%), if so, it randomizes whether there is to be tier 1, then whether there is to be t2, t3 and finally t4, with regardless of the city the ranges of these units are:
t1: 8-15
t2: 5-7
t3: 3-5
t4: 1-3

The lotteries are separate for each tier. 

In the new week there are further lotteries. First, whether there is to be a new unit - then its increment (not the value above) is added - again there are 4 lotteries. In addition, there are lotteries whether to upgrade a unit.
After two months of playing there are additional lotteries for new tiers
I even observed t7 in 411

**Comment by IvanSavenko** [comment]
@krs0 Well, basically what I need is expanded version of @dydzio0614 comment above.
Specifically (using info from dydzio and info that I've found)

Day 1:
- what is the probability to get any garrison at all? (looks 50% according to dydzio)
- what is probability and amount of troops of each tier?
- - Tier 1: 8-15, around 30% chance
- - Tier 2: 5-7, around 30% chance
- - Tier 3: 3-5, around 25% chance
- - Tier 4: 1-3, around 10% chance
- can town get multiple creatures on day one?
- can you get unit for which there is not prebuilt dwelling in town?
- will game substract recruited garrison from available creatures in dwellings?

Garrison every new week:
- what's probability to get new units? (80% from what I gather)
- what are the probabilities to get each tier?
- - Tier 1: ???
- - Tier 2: ???
- - Tier 3: ???
- - Tier 4: ???
- - Tier 5: ??? (seems to be only present since week 6)
- - Tier 6: ??? (seems to be only present since week 7)
- - Tier 7: ??? (seems to be only present since week 19)
- how many units will be added on new week? (seems to be basic growth)
- will game subtract recruited amount from dwelling, if built?
- what's the probability for a creature to upgrade? (Seems to be 10% and only triggered when corresponding creature is recruited)

Troop growth every new week:
- how many creatures accumulate in dwellings each week (seems to be 50%)
- does presence of citadel/castle affects creature growth for neutral towns?
- does presence of creature horde affects creature growth?

**Comment by krs0** [comment]
Nice growth information in this video... screenshots saved below
https://www.youtube.com/watch?v=AX9uzQHnB4U


![image](https://github.com/vcmi/vcmi/assets/15194321/8e9b7aca-888e-4be4-982d-55396061059f)
![image](https://github.com/vcmi/vcmi/assets/15194321/e39f884b-3886-4bb0-b55b-059abbc34a2c)
![image](https://github.com/vcmi/vcmi/assets/15194321/31924a62-6e46-4c31-add8-91709b899ed9)

**Comment by IvanSavenko** [comment]
This info is about owned towns. Neutral towns have (apparently) somewhat different logic

**Comment by krs0** [comment]
I know ... is for the future :)

**Comment by krs0** [comment]
I am a little stuck with this one. I do not know where to get those values. Any suggestions are welcomed.

**Comment by IvanSavenko** [comment]
Experiment I guess? 
Unless somebody can reverse-engineer them.
Create map with multiple neutral town and see what happens over time

**Comment by krs0** [comment]
I have tried that... but no way to get accurate % out of that :(
I can just observe that maybe in week x creature tier y is added / upgraded.
[A Creature Growth Test.zip](https://github.com/vcmi/vcmi/files/12188274/A.Creature.Growth.Test.zip)

**Comment by rilian-la-te** [comment]
Is FizMig have those info?

**Comment by dydzio0614** [comment]
no

**Comment by rilian-la-te** [comment]
FizMig about neutral growth logic (in Russian):

> Количество существ в отрядах охраны не увеличивается в начале новой недели с вероятностью 20%. В
остальных случаях к охране добавляется 1 отряд существ, в количестве базового недельного прироста этих
существ в городе. Из наблюдений, с большей вероятностью добавляются существа 3 уровня, существа 2 и 4
уровней приходят реже, а существа 1 уровня – очень редко. Например, для нейтрального Замка в начале
недели может добавиться 14 Копейщиков, 9 Арбалетчиков, 7 Грифонов или 4 Рыцаря.
Добавляемые отряды одного типа с имеющимися сливаются в один отряд. Примерно с шансом 10%
добавляемый отряд может оказаться улучшенным. В этом случае имеющиеся отряды этого же типа также
улучшаются и сливаются с добавляемым.
Начиная с 6 недели, в охрану города могут добавляться отряды 6 уровня, с 7 недели – 6 уровня, а с 10 недели
– отряды 7 уровня. Месяцы существ и Чумы никак не влияют на численность охраны и её прирост.

**Comment by IvanSavenko** [comment]
"rarely" and "very rarely" is not something I can write in code.
I also got 8 creatures of 2nd tier on game start as guards, which is outside of "5..7" range

Chances to increase on new week heavily depends on week number - on week 2 mostly tiers 1& 2 were added, while on week 7 it is mostly tier 3&4. Going further into the game will probably shift this range to higher tiers

This also does not says anything about dwelling & their growth

**Comment by rilian-la-te** [comment]
@IvanSavenko AFAIK, if we capture neutral town with dwellings, we always have basic growth, but need testing.

**Comment by IvanSavenko** [comment]
Nope.
Here is newly captured town on week 2. Nothing has been recruited by me.
![зображення](https://github.com/vcmi/vcmi/assets/1576820/6c092125-cd9e-40df-9580-480f5a3f9671)

**Comment by rilian-la-te** [comment]
version? HD Mod? Hota? Normal SoD?

**Comment by IvanSavenko** [comment]
sod with butchered hd mod to allow H3 to start in a window.
Haven't checked hota and not planning to.

**Comment by IvanSavenko** [comment]
After running a quick test in SoD:
### On day 1:
- All dwellings will have basic growth
- Having citadel/castle/creature horde has no effect on growth
- Initial garrison can have 1-4 tiers as guards, with independent roll of:
- - Tier 1: chance ~30%, 8-15 units
- - Tier 2: chance ~30%, 5-8 (7?) units
- - Tier 3: chance ~30%, 3-5 units
- - Tier 4: chance ~10%, 1-3 units

### On new week
- All dwellings have 50% growth multiplier to *final* value. After citadel/castle/horde
- Having citadel/castle/creature horde *does* affects growth
- There is ~80% chance for a creature to be recruited
- Creature amount to be recruited is always basic growth
- There is ~10% chance that stack with recruited creature will be upgraded (in addition to recruitment) 
- If recruited creature has a dwelling, amount of available creatures will be subtracted by recruited amount
- Creature tier is selected using weighted random, depending on current week (TODO: chances)
- High-level creatures can only appear later in game:
- - Tier 4: week 4+
- - Tier 5: week 5+
- - Tier 6: week 7+?
- - Tier 7: week 19+?

**Comment by rilian-la-te** [comment]
@IvanSavenko FizMig says than Tier 6 is week 6+ and Tier 7 is week 10+
