### ISSUE TITLE
Adventure map spells like Disguise / Visions affect color of stack amount boxes in battle

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2001]
Having adventure map spells that provide bonuses leads to creatures in battle having yellow stack amount boxes, as if under effect of a spell.

https://bugs.vcmi.eu/view.php?id=2290

**Comment by IvanSavenko** [comment]
@rilian-la-te Sounds similar to effect from moat (spell that should not be visible in creature info). What would be the best way to fix it considering latest changes?

**Comment by rilian-la-te** [comment]
@IvanSavenko for moat - I change it to battlefield enchantment instead. About some spells - maybe I will add some property like "adventure-only".
