### ISSUE TITLE
Unit placed on the same tile as the Catapult during siege

### ISSUE THREAD

**Issue by storageer** [vcmi/vcmi#2003]
**Describe the bug**
Units get placed on the same hex as the catapult during a siege, if the player attacks the town while 

**Game logs**
[server_log.txt](https://github.com/vcmi/vcmi/files/11240515/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11240516/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/11240517/VCMI_Launcher_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11240518/VCMI_Server_log.txt)
[catapult_unit_siege_bug.zip](https://github.com/vcmi/vcmi/files/11240521/catapult_unit_siege_bug.zip)

**To Reproduce**
Attack a walled town with a hero that has 4 or more unit stacks, and has the combat formation set to "Tight"

**Expected behavior**
No unit stack should be placed on the hex occupied by the Catapult.

**Actual behavior**
One of the units gets placed on/overlaps with the front part of the Catapult. 

**Did it work earlier?**
Unknown.

**Screenshots**
![Screenshot 2023-04-15 20-57-51](https://user-images.githubusercontent.com/121976640/232249283-3c5342c2-e3ac-488b-a356-0793b4ba87a1.png)

**Version**
 - OS: Windows 10
 - Version: VCMI 1.2.0 release version

**Additional context**
Tried looking for duplicates, no matches.

**Comment by IvanSavenko** [comment]
How this gets handled in H3?

**Comment by storageer** [comment]
Unfortunately, I cannot tell.
I tried to test this in my GOG version, but I could not start any fights with Tight formation, neither sieges nor Hero vs Hero engagements. It just places all units in Loose formation, unless the hero comes with Tactics.
