### ISSUE TITLE
RMG should handle better order of placement for objects

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2004]
**Describe the bug**
Sometimes the order of placement is wrong. Or some objects are 100% obstructed by others.

There is Ore placed behind 2'nd store of Wolf rider Picket!
![image](https://user-images.githubusercontent.com/15194321/232252209-007fdf58-c925-42e4-b59b-a5985fe23113.png)

Box should be behind windmill pallets
![image](https://user-images.githubusercontent.com/15194321/232252126-6bec5ab6-d77b-48ee-b3fb-41724b20e776.png)

Lamp or other 1 tile stuff, should not allowed in that spot behind prison
![image](https://user-images.githubusercontent.com/15194321/232252152-48a3d48b-c1b0-4bf9-9843-1d6ea7fda6fc.png)

**Comment by DjWarmonger** [comment]
Order of rendering object is fixed in #3711 , however that doesn't stop RMG from placing small objects behind tall ones. It's a completely separate thing, and I'm not convinced to do it.
