### ISSUE TITLE
Headless mode is broken in 1.2

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2006]
**Game logs**
[server_log.txt](https://github.com/vcmi/vcmi/files/11242006/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11242007/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11242008/VCMI_Server_log.txt)

**To Reproduce**
1. Disable all mods (except extras and essentials) for clear results
2. 
Mac: `/Applications/VCMI-1.2.0.app/Contents/MacOS/vcmiclient --testmap "MAPS/All for One" --onlyAI --headless`
Win: `VCMI_client.exe --testmap MAPS/"Monolits" --onlyAI --headless`

**Expected behavior**
Headless game started

**Actual behavior**
```
Player 0 (red) starting turn, day 1
Segmentation fault: 11
Network error receiving a pack. Connection Connection with VCMI 1.2.0 (server) (ID: 1 UUID: 211ef495-e264-4cdf-8ea7-4b0e56d982d0) dies. What happened: read_some: Connection reset by peer [system:54]
```

**Did it work earlier?**
Works perfectly in 1.1

**Version**
 - OS: MacOS/Windows
 - Version 1.2 (release)

**Comment by Alexander-Wilms** [comment]
Cf. https://github.com/vcmi/vcmi/pull/3409

**Comment by Alexander-Wilms** [comment]
Can this issue be closed?

**Comment by Povelitelh3** [comment]
I have crash in 1.4.4 under windows

**Comment by IvanSavenko** [comment]
@Povelitelh3 
What about 1.5 / develop?

Fix for this bug should be in daily build. 
Closing, if this still happens in daily builds / develop - please reopen
