### ISSUE TITLE
Icon for Cannon war machine is too small in Hero Info Window

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2011]
**Describe the bug**
Icon for Cannon war machine is too small in Hero Info Window

**To Reproduce**
1. Use HotA mod
2. Select hero Jeremy
3. Open hero info window

**Screenshots**
![image](https://user-images.githubusercontent.com/15194321/232323248-73e497f5-3ece-48a5-bf66-98783f23c2f5.png)

**Comment by Nordsoft91** [comment]
Worked earlier, regression

**Comment by krs0** [comment]
Fixed for a long time.
