### ISSUE TITLE
Wrong encoding when loading text in mods

### ISSUE THREAD

**Issue by tytannial** [vcmi/vcmi#2020]
**Describe the bug**
Loading locale txt files in mods. getting incorrect encoding.

**To Reproduce**
1. Put Simplified Chinese locale txt files(encoding with GBK/GB18030) to mods data folder and maps to maps folder.
2. Enable ture type font.
3. Load mod
4. Select game language Chinese
5. Run game

**Expected behavior**
Loading files with selected language setting, use GBK/GB18030 encoding

**Actual behavior**
Error encoding 

**Screenshots**

**Version**
 - OS: Windows 11 non utf8 encoding
 - Version: 1.2.0

**Comment by tytannial** [comment]
#1300

**Comment by IvanSavenko** [comment]
If mod contains non-english files make sure to add
`"language" : "chinese"`
in mod.json

This will force vcmi to use Chinese encoding (GBK) when loading text files, fonts, maps & campaigns from this mod

**Comment by IvanSavenko** [comment]
Closing, works as designed, solution is to update mod
