### ISSUE TITLE
Artifacts start disappearing when 2 heroes with same name are on map

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2038]
**Describe the bug**
Artifacts disappear when you have 2 copies of same hero. Even if different players.

**To Reproduce**
1. Load Attached map
2. Pick artifact
3. look in hero info

[A 2 hero clones test.zip](https://github.com/vcmi/vcmi/files/11275907/A.2.hero.clones.test.zip)

**Version**
 - OS: [e.g. Windows
 - Version: develop

**Comment by IvanSavenko** [comment]
Probably "won't fix"
This is illegal situation to begin with - vcmi does not allows/support having copies of the same hero

**Comment by krs0** [comment]
Yes... wont fix is ok... but code area should be reviewed!

**Comment by krs0** [comment]
Prob idèntical same heroes. I drag and dropped in map editor same hero.

**Comment by DjWarmonger** [comment]
It is the same situation as with infamous Orrin bug, and it's illegal as Ivan said.

**Comment by IvanSavenko** [comment]
Closing, not planned - corrupted map.

@krs0 feel free to open editor bug since same hero should not be placeable on map
