### ISSUE TITLE
Hotseat crashes game after player battle

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2039]
**Describe the bug**
Hotseat crashes the game after player wins final battle

**To Reproduce**
1. start in hotseat A Warm and Familiar Place.h3m
2. vcmimove, vcmiglaurung, vcmieagles
3. attack player 2 on surface
4. crash when battle ends

**Version**
 - OS: [e.g. Windows,
 - develop

**Comment by Nordsoft91** [comment]
@krs0 , could be related to my quickbattle changes, is it possible to verify on 1.2.0?

**Comment by Nordsoft91** [comment]
@krs0, cannot reproduce - neither on 1.2 nor on 1.3.

**Comment by IvanSavenko** [comment]
Not reproducible for me either on 1.2

**Comment by krs0** [comment]
I think it is because I use autocombat for both sides.
If I fight manually it does not crash.
Just reproduced it in all for one... just go attack one player in his castle.

**Comment by IvanSavenko** [comment]
Checked current beta/1.3.1 and works fine. 
Started map Elbow Room in hotseat, attacked 2nd player on day one, won battle, no crash.

There are some popup messages shenanigans going on, with game switching between red & blue perspectives, but no crashes. Will look into popup messages in 1.4 alongside multiplayer, but game seems to be stable.
