### ISSUE TITLE
Duplicate artifact image on mouse drag in map editor

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2040]
**Describe the bug**
Dragging an artifact 1 tile down creates a duplicate... maybe only image

![VideoCapture_20230419-223819](https://user-images.githubusercontent.com/15194321/233182510-a4a629b3-8683-43c3-a5de-48c6a2dce997.jpg)

**Version**
 - OS: [e.g. Windows
 - Version: develop

**Comment by Nordsoft91** [comment]
Visual-only, non-functional.
The problem is in hota artefact config: for some reason is has size 2x2.
Certainly bug, but minor then
