### ISSUE TITLE
When going to Main Menu from within combat crash occurs

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2044]
**Describe the bug**
When going to Main Menu from within combat crash occurs

**To Reproduce**
0. Have Movement Shadowes Enabled !!!!
1. Start a battle
2. click options -> Man Menu
3. Crash visible in console

**Screenshots**
![image](https://user-images.githubusercontent.com/15194321/233493136-28abf3b6-e4e5-42a0-8a76-b320096d746c.png)

![image](https://user-images.githubusercontent.com/15194321/233493170-af0c7b7d-4aa4-41c7-94ee-41b0de41be4a.png)

**Version**
 - OS: [e.g. Windows, 
 - Version: develop

**Comment by krs0** [comment]
This is solved in latest develop. Can be closed?

**Comment by krs0** [comment]
Found how to reproduce it. Quit a battle with enable movement shadows option on. Crash occurs.

**Comment by dydzio0614** [comment]
Does not reproduce for me at the moment...

**Comment by nullkiller** [comment]
I can confirm. It crashes on my custom build as well

**Comment by nullkiller** [comment]
Changed order of destructors and it works now
