### ISSUE TITLE
Crash when clicking on "Show Available Scenarios" on load game screen

### ISSUE THREAD

**Issue by godric3** [vcmi/vcmi#2045]
**Describe the bug**
Clicking on  "Show Available Scenarios" button on load game screen, while save from random map is selected, results in crash

**Game logs**
[server_log.txt](https://github.com/vcmi/vcmi/files/11297832/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11297833/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11297835/VCMI_Server_log.txt)

**To Reproduce**
1. Start game from random map template
2. Save game
3. Go to load save game screen
4. Select previosuly created save
5. Click "Show Available Scenarios"
6. Crash

**Version**
 - OS: Windows 7
 - Version: 1.2

**Comment by IvanSavenko** [comment]
Fixed in #2041
