### ISSUE TITLE
Invisible boats

### ISSUE THREAD

**Issue by nullkiller** [vcmi/vcmi#2050]
**Describe the bug**
AI uses invisible boat

**To Reproduce**
1. Load attached map
2. Wait next turn 2 times
3. AI will first build a boat and embark it and afterwards sail to your town
4. While AI sails and after disembark boat is invisible

**Expected behavior**
Boat should be visible while AI sails in it and after disembark

**Actual behavior**
Boat is invisible

**Did it work earlier?**
If this something which worked well some time ago, please let us know about version where it works or at date when it worked.

**Screenshots**
![image](https://user-images.githubusercontent.com/5644734/233795219-036a115c-2f86-4105-b0f2-93d60e53b259.png)

**Version**
 - OS: Windows, MSVC
 - Version: latest develop
 
**Attached map**
[allied-shipyard.zip](https://github.com/vcmi/vcmi/files/11301755/allied-shipyard.zip)

**Comment by Nordsoft91** [comment]
90% broken after my changes. Will review
