### ISSUE TITLE
Puzzle Map shows grall location on minimap

### ISSUE THREAD

**Issue by edeksumo** [vcmi/vcmi#2063]
**Describe the bug**
While visiting obelisk or opening puzzle map from button minimap jumps into location of grall.

**To Reproduce**
1. Go to obelisk on random map.
2. Now you know where to look for grall, profit.

**Comment by Alucard648** [comment]
I think, this bug should be ascended into QoL feature, if player had visited all obelisks on map.

**Comment by IvanSavenko** [comment]
Fixed in #2041
