### ISSUE TITLE
Show mod sizes in launcher

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2068]
Consists from 2 parts:
 - Specify size attribute on remote side per mod (at least approximately as mods frequently changed) - will work from the box
 - Measure mod folder size locally

Also, need to restore size column in mod view

1) Allows better mod management, especially on mobile devices where space is critical.
2) Allows to see download progress

**Comment by IvanSavenko** [comment]
Implemented in 1.4
