### ISSUE TITLE
Different icons for resources

### ISSUE THREAD

**Issue by psyhlo** [vcmi/vcmi#2069]
It bothers me for some time.
Is there a reason the icons to be different in town screen?
![image](https://user-images.githubusercontent.com/1803170/234193782-6400e8ed-e1ba-4909-b8e4-5d21db1b4ddd.png)
I thought this was from the mods, but i disable all expect VCMI Extras

**Comment by IvanSavenko** [comment]
VCMI extras "bug"
Additional resolutions were made back when wog was still part of vcmi so resource icons were taken from wog.

Likely to be "fixed" in 1.3 since I am planning to create autogeneration for high-res UI and deprecate extra resolutions mdo.

**Comment by psyhlo** [comment]
after disable VCMI extras everything as it should be
close the issue if you want
