### ISSUE TITLE
the lastest app can't use the lanuage mod to switch language 

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#2071]
I create a mod "Chinese translation", the "Content" folder contains "data" and "Maps" folder which is relative with chinese language. And then we load the mod, but the game language will be always english. 
In 0.99.0 we can use this way to switch the language. Please fix this.
I use the lastest app on Android. I am not sure whether this problem occurs on other platform.

**Comment by IvanSavenko** [comment]
Make sure to set in your mod.json
`"language" : "chinese"`
This will force game to load all files from your mod (text files and maps) using Chinese encoding

**Comment by IvanSavenko** [comment]
Oh, and set language to "Chinese" in Launcher

**Comment by lishaoxia1985** [comment]
@IvanSavenko Can't add "language" : "Chinese" into mod.json. If you do this it will show the error "can't load the mod xxx".
I change the mod type "Translation" to "Graphical", the app can load the mod, but it show messy code.
I have no idea how to solve this.
By the way, I have add a "Chinese true type font" mod.

**Comment by lishaoxia1985** [comment]
@IvanSavenko the 0.99.0 branch, we can set the app "CodePage" to "GBK" or "GB2312", we can't find this settings in the latest one.
Maybe the problem is relative with this settings.

**Comment by lishaoxia1985** [comment]
@IvanSavenko Thank you. I add "language" : "chinese", and modtype is "Translation".
![Chinese Translation.zip](https://github.com/vcmi/vcmi/files/11322461/Chinese.Translation.zip)

**Comment by heroesiiifan** [comment]
@misiokles I've converted this to the new translation format. And added images from [this mod](https://www.bilibili.com/video/BV1ZW4y1579s/?zw&spm_id_from=888.80996.embed_old) Only buttons/newgame in main menu is missing).

I think we should add it to the repository to make it easy for the chinese players to start with vcmi.

[chinese-translation.zip](https://github.com/vcmi/vcmi/files/11359433/chinese-translation.zip)

**Comment by tytannial** [comment]
> @misiokles I've converted this to the new translation format. And added images from [this mod](https://www.bilibili.com/video/BV1ZW4y1579s/?zw&spm_id_from=888.80996.embed_old) Only buttons/newgame in main menu is missing).
> 
> I think we should add it to the repository to make it easy for the chinese players to start with vcmi.
> 
> [chinese-translation.zip](https://github.com/vcmi/vcmi/files/11359433/chinese-translation.zip)
> 
> @lishaoxia1985 @tytannial Okay from your side?

no....im indie...

**Comment by heroesiiifan** [comment]
@tytannial The best solution would be a repository under: https://github.com/vcmi-mods (can be supported also from vcmi-team)

No, I've only the information from @lishaoxia1985 zip file. And from the mod mentioned above. But I don't understand chinese.

**Comment by tytannial** [comment]
> @IvanSavenko Thank you. I add "language" : "chinese", and modtype is "Translation". ![Chinese Translation.zip](https://github.com/vcmi/vcmi/files/11322461/Chinese.Translation.zip)

@lishaoxia1985 创建一个仓库把本地化上传吧，这样就能一起维护了。

**Comment by lishaoxia1985** [comment]
@tytannial I have do as you wish. It has more job to do.
By the way, the mod doesn't contain true type font.

**Comment by dydzio0614** [comment]
@IvanSavenko should chinese font be:
1. new font in our true type font submod
2. another true type font in chinese translation mod?

**Comment by IvanSavenko** [comment]
> @IvanSavenko should chinese font be:
> 
>     1. new font in our true type font submod
> 
>     2. another true type font in chinese translation mod?

Another true type font in Chinese translation. At least for now. We don't support multiple fonts at the moment and Chinese fonts (well, CJK in general) have rather poor typography for western alphabets.

**Comment by lishaoxia1985** [comment]
@IvanSavenko I hope it can support the native font like the project UnCiv. If this, we don't need any font in app.

**Comment by dydzio0614** [comment]
@IvanSavenko have you checked https://chinesefonts.org/fonts/wenquanyi-micro-hei-regular font recommended by @lishaoxia1985 in another issue?

**Comment by IvanSavenko** [comment]
As I said - CJK fonts generally have rather poor typography for western alphabets. 

That being said, perhaps replacing our current font in true type fonts with this one is not a bad idea. That mod is supposed to be used as fallback anyway, so better coverage is more important than better glyphs.

So I think replacing our current font (Liberation Sans/Serif) with this font is not a bad idea
