### ISSUE TITLE
RMG: Few empty zones are generated

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2081]
Template 3SM3d
Seed: 1682627278
72x72x1
players: 2, cpus: 0
water: none, monsters: strong
red: Forge, blue: random

Mods
<img width="455" alt="Снимок экрана 2023-04-28 в 00 33 09" src="https://user-images.githubusercontent.com/9308612/234984281-7866590f-531c-4e7a-b516-548cd113e450.png">

**Did it work earlier?**
**Screenshots**
<img width="853" alt="Снимок экрана 2023-04-28 в 00 29 59" src="https://user-images.githubusercontent.com/9308612/234983676-77e0fc07-120f-4315-93b3-68399048272b.png">

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: VCMI-1.2

**Additional context**
[rmg_issue_save.zip](https://github.com/vcmi/vcmi/files/11347657/rmg_issue_save.zip)

**Comment by DjWarmonger** [comment]
Not s suprise...
```
			"11" :
			{
				"type" : "junction",
				"size" : 25,
				"monsters" : "normal",
				"matchTerrainToTown" : false,
				"treasure" :
				[
					{ "min" : 0, "max" : 0, "density" : 1 },
					{ "min" : 0, "max" : 0, "density" : 1 },
					{ "min" : 0, "max" : 0, "density" : 1 }
				]
			},
```

**Comment by DjWarmonger** [comment]
Even funnier - these values **are** actually 0 in original rmg.txt file. Not sure what to do about it - won't fix, or remove the template.
[Rmg.txt](https://github.com/vcmi/vcmi/files/11358800/Rmg.txt)

Still, editor RMG crashes for me when I try to generate this template.

**Comment by IvanSavenko** [comment]
Personally I'd rather fix it in some way - since this can be viewed as H3 bug

**Comment by DjWarmonger** [comment]
Alright, added some minimal-value treasures.

**Comment by Nordsoft91** [comment]
@DjWarmonger ,how junctions look in OH3?
