### ISSUE TITLE
No save description shown

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2082]
**To Reproduce**
1. Start game
2. Open "save game" menu

**Expected behavior**
Scenario info is shows for saves

**Actual behavior**
Empty scenario info

**Screenshots**
<img width="762" alt="Снимок экрана 2023-04-28 в 00 35 45" src="https://user-images.githubusercontent.com/9308612/234985000-e8ba63ed-39c7-482e-a031-616ffc9bee2c.png">

**Version**
 - Version: VCMI-1.2.0

**Comment by godric3** [comment]
related or even duplicate: https://github.com/vcmi/vcmi/issues/1371
