### ISSUE TITLE
The order of mod loading may has some problem in latest branch

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#2084]
For example, if we have a Chinese translation mod, the order of mod loading is this:
 1. Loading the Chinese translation mod
2. Loading /data/user/0/is.xyz.vcmi.daily/files/vcmi-data/Mods/vcmi/config/vcmi/chinese.json, this is inside the app (Android)

That means if some text both exits in  Chinese translation mod and insided translation mod, the text can't be changed by loading the Chinese mod.
I found this problem because that the insided Chinese translation mod has some errors.
In 0.99.0, I don't find this problem.

**Comment by lishaoxia1985** [comment]
Ok, I have solve this by add some words in mod.json:
"depends" : [
		"vcmi",
	],
I'm not sure whether it is a problem.

**Comment by IvanSavenko** [comment]
Hi. Your solution is fine.
However if our Chinese translation has errors, can you provide your fixed version?

**Comment by lishaoxia1985** [comment]
@IvanSavenko Ok, I will have a plan. Thank you.

**Comment by dydzio0614** [comment]
personally I am curious about chinese H3 scene, including feedback about VCMI but there is language barrier that I am personally unable to jump... and chinese players seem to stay in their own communities. I saw https://www.bilibili.com/video/BV1ZW4y1579s/?zw&spm_id_from=888.80996.embed_old and while I do not exactly understand it and chinese VCMI community, it looks interesting as some decent effort was put to create this

**Comment by lishaoxia1985** [comment]
@IvanSavenko Now I have upgrade 1.2.1, the fix method have no effects.
 mod.json:
"depends" : [
"vcmi",
]

**Comment by IvanSavenko** [comment]
This is strange. Changes in 1.2.1 were very limited and should not have such effect

**Comment by lishaoxia1985** [comment]
@IvanSavenko the log shows that:
- ERROR global [c1ffc230] - /storage/emulated/0/Android/data/is.xyz.vcmi.daily/files/vcmi-data/Mods/TrueTypeFonts/Content.zip failed to open

**Comment by IvanSavenko** [comment]
How are you creating such zip? 
Can you create one with zero compression and test it too?
Can you upload your zip archive here?

**Comment by lishaoxia1985** [comment]
In huawei mobile phone, i use mixplorer to zip the folder. 
I create one with zero compression and test it. IT DOES VERY WELL.

**Comment by lishaoxia1985** [comment]
@IvanSavenko Have you test it?

**Comment by IvanSavenko** [comment]
Your mod works fine for me, using Content.zip and mod.json

If you have "failed to open" error with this Content.zip then it is possible that this is a bug in our Android version
