### ISSUE TITLE
Lighthouse gives bonus on land

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2093]
<img width="464" alt="Снимок экрана 2023-04-29 в 05 08 03" src="https://user-images.githubusercontent.com/9308612/235274737-24548fad-f723-4f6d-ba17-9fedb19cab5d.png">
<img width="430" alt="Снимок экрана 2023-04-29 в 05 06 56" src="https://user-images.githubusercontent.com/9308612/235274740-a2cd82a5-fa07-4e60-92f7-683f9725d950.png">

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: VCMI-1.2.0

**Additional context**
MiscObjects.cpp void CGLighthouse::giveBonusTo(...)
gb.bonus.subtype = 1; => gb.bonus.subtype = 0;

**Comment by krs0** [comment]
Error avoidable if using proper naming instead of cryptic 0 or 1 :(

**Comment by IvanSavenko** [comment]
@krs0 
true, although we have quite a lot such bonuses. Proper fix for that should be more general than just land/sea string ID's

**Comment by dydzio0614** [comment]
add to develop and if 5+ such bugs get found then create 1.2.2

**Comment by IvanSavenko** [comment]
@dydzio0614 Not against 1.2.2 if necessary, but bugs like this one are relatively minor:
- does not leads to a game crash
- does not leads to a game block / game lock
- not something majority of players are going to notice (no lighthouses on RMG and uncommon on hand-made maps)

**Comment by rilian-la-te** [comment]
Fixed by b29fc1a, I suggest to close this.

**Comment by rilian-la-te** [comment]
@IvanSavenko @Nordsoft91
