### ISSUE TITLE
Android Launcher does not installs mod dependencies

### ISSUE THREAD

**Issue by Makshuvalov** [vcmi/vcmi#2095]
On android version doesn't work some mods: forge town, forge 2000, asylum town, megapack rus. Towns not showing in a game, when I'm adding they

Version 1.2.1

**Comment by Nordsoft91** [comment]
@Makshuvalov , forge2000 and Asylum have dependencies: can you confirm that you also have installed mods Asphalt terrain and Stardust terrain?

**Comment by IvanSavenko** [comment]
Might be related to having comments in mod.json?
Android Launcher does not works well with them.

**Comment by nullkiller** [comment]
It might be possible that android does not install dependencies automatically. Its launcher is pure comparing with our standard one.

**Comment by IvanSavenko** [comment]
Implemented in #3817
