### ISSUE TITLE
core.bonus.KING.description in 1.2 is different with 0.99 KING1, KING2,KING3

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#2096]
@IvanSavenko In 1.2:

- core.bonus.KING.description is "Vulnerable to SLAYER level ${val} or higher"

Compare to the branch before 1.2 core.bonus.KING1.description, core.bonus.KING2.description, core.bonus.KING3.description ,  core.bonus.KING.description should be "Vulnerable to ${val} SLAYER", val will be "Basic", "Advanced" and "Expert". But now val is "1" "2" and "3".

**Comment by tytannial** [comment]
这个修正已经在我提交的最新的本地化配置改动里了
https://github.com/vcmi/vcmi/commit/57399b5b320485131f77078a3676038a936c5872

目前根据英文文本提供的格式，改为了“受${val}级或更高级屠戮成性影响”，可能缺少了对“弱点”的修饰。

**Comment by lishaoxia1985** [comment]
@tytannial 问题是这种描述不对，英文也不对，val应当为basic advened expert而不是数字

**Comment by tytannial** [comment]
是吧，突然就改成了数值表示，是有点怪。

**Comment by lishaoxia1985** [comment]
@tytannial 准备把英化mod全部翻译成中文，发现工程量确实太大了
现在通常的应该是只翻译game.json文件，战役和地图直接使用中文版的地图，累

**Comment by tytannial** [comment]
> @tytannial 准备把英化mod全部翻译成中文，发现工程量确实太大了 现在通常的应该是只翻译game.json文件，战役和地图直接使用中文版的地图，累

翻译好本体即可，战役和地图通过语言选择器来选择就好吧。

**Comment by lishaoxia1985** [comment]
@tytannial 兄弟 我给出了你几个翻译可能存在的问题，救市你给我的链接里面的

**Comment by tytannial** [comment]
> @tytannial 兄弟 我给出了你几个翻译可能存在的问题，救市你给我的链接里面的

我是根据最新的英文文本进行的校对，关于生物特质这块，我已经测试过原版所有生物的特性文本，还是比较准确的。新版本引擎已经将所有生物的具体数值标准化和具象化了，将所有相似特质已经合并了，所以有些技能翻译可能对于生物A是一个效果，对于生物B是另一个效果，但是一个特质。另外我加你微信了，有问题直接微信联系吧。
