### ISSUE TITLE
Spirit of oppression doesn't work

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2102]
**Describe the bug**
Subj. see screenshots

Bug reported by user

**Screenshots**
![image](https://user-images.githubusercontent.com/9308612/235340654-69756fa6-eca7-4145-a40a-1878bd4b8b26.png)

![image](https://user-images.githubusercontent.com/9308612/235340672-ea4ee1c1-74ad-4ae1-ab08-31221fa2f2a2.png)

![image](https://user-images.githubusercontent.com/9308612/235340679-15127963-611e-44c4-90d2-fde4ef2812f3.png)

**Version**
 - OS: Android
 - Version: VCMI-1.2.1

**Additional context**

**Comment by rilian-la-te** [comment]
@Nordsoft91 spirit of oppression should block only if morale is above 0, according to FizMig. 

And please, check in battle.

**Comment by rilian-la-te** [comment]
TheLazy says it too: https://heroes.thelazy.net/index.php/Spirit_of_Oppression

**Comment by Nordsoft91** [comment]
It's a report from user. If won't fix, then ok

**Comment by IvanSavenko** [comment]
In that case - closing. 
Works as designed. Behavior matches H3 and is not viewed by anybody as a bug.

**Comment by rilian-la-te** [comment]
@IvanSavenko visual bug exists, I tested it. Mechanically it is okay.

**Comment by rilian-la-te** [comment]
@IvanSavenko but visual bug exists from all artifacts, not only from Spirit Of Oppression. Will create a new issue.
