### ISSUE TITLE
RMG - It is possible to create map with a single team

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2104]
**Describe the bug**
It seems that VCMI allows placing all players in a single team, leading to a situation where map is instantly won without clear reason why.

**To Reproduce (confirmed steps)**
1. Enable extended RMG mod
2. Open RMG settings
3. Select 2+ players in match
4. Open "Team settings" window and place all players into same team
5. Attempt to start the game

**To Reproduce (unconfirmed, as per player report)**
1. Enable extended RMG mod
2. Open RMG settings
3. Select 2+ players in match
4. DO NOT touch "Team settings" button, keeping teams randomly selected
5. Attempt to start the game

**Expected behavior**
- Option A: Team settings dialog should block attempts to place all players into a single team
- Option B: If all players are in a single team, clicking "Begin Game" should show understandable error message to player

**Actual behavior**
RMG generates map, but before map starts player receives notification "You are victorious. All enemies have been eliminated" while on loading screen

**Version**
 - Version: 1.2

**Comment by krs0** [comment]
For RMG could we select other victory conditions?
Like in editor?
Ifmso same team could be allowed, but with different victory conditions

**Comment by Nordsoft91** [comment]
Confirmed scenario:
- not a bug, just lack of requirements.
- how does it work in hota/hdmod?
- could be used in future if we support no AI maps in rmg

Unconfirmed scenario:
- bug
- let's disable teams if they aren't configured explicitly in RMG extensions

**Comment by IvanSavenko** [comment]
> * not a bug, just lack of requirements.

Still a bug from player point of view

> * how does it work in hota/hdmod?

Allowed for some reason, with instant win on end of day 1

> * could be used in future if we support no AI maps in rmg

In future - maybe. But right now we don't support such maps in RMG
