### ISSUE TITLE
Rename "default" template to "random" template.

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#2106]
**Describe the bug**
Players tend to select "default" option from template and get suprised that weird templates are selected, as they are completely random.

**To Reproduce**
Open random map view in either VCMI or map editor, see default options.

**Expected behavior**
- Rename "default" to "random"
- Think about most common language translation

**Comment by IvanSavenko** [comment]
Another option is one I described in #1998 

Add "recommended templates" group that contains small set of hand-picked, high quality templates that is selected by default in place of current default/random option

**Comment by Nordsoft91** [comment]
- not a bug
- feature is ported from hota/hdmod, should be same as there

**Comment by IvanSavenko** [comment]
> * feature is ported from hota/hdmod, should be same as there

Poor argument IMO. Don't see any need to port poor decisions of HDMod/HotA to vcmi
