### ISSUE TITLE
Crash on building boat after loading game

### ISSUE THREAD

**Issue by godric3** [vcmi/vcmi#2112]
**Describe the bug**
Game crashes when I try to build a boat after loading game.
While trying to reproduce it become a bit random:

First when game was started with vcmi_client.exe, save & load, it crashed consistently.
Next I started with launcher, loaded save(made in previously in vcmi_client), no crash. Still in game by launcher I started new game, save & loaded, build boat, works. 
Start with vcmi_client.exe again, load second save, works, load first save works.
Start with vcmi_client.exe again, load frist save, crash.

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11382742/VCMI_Client_log.txt)
[server_log.txt](https://github.com/vcmi/vcmi/files/11382743/server_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11382744/VCMI_Server_log.txt)

**To Reproduce**
1. Start game with`VCMI_client.exe` (not 100% sure if relevant)
2. Start map with water and shipyard (Arrogance will work)
3. Save game
4. Load game
5. Try to build a boat
Save:
[boat_crash.zip](https://github.com/vcmi/vcmi/files/11382740/boat_crash.zip)

**Version**
 - OS: Windows 7
 - Version: 1.2.1

**Comment by misiokles** [comment]
Cannot confirm.

**Comment by nullkiller** [comment]
In 1.2 I am able to reproduce it from save. 1.2.1 will check

**Comment by godric3** [comment]
I managed to reproduce it with debugger attached, my findings so far:
https://github.com/vcmi/vcmi/blob/develop/lib/NetPacksLib.cpp#L1505
```cpp
void NewObject::applyGs(CGameState *gs){
...
o->appearance = handler->getTemplates(terrainType).front();
```
`handler->getTemplates(terrainType)` return empty list.
Inside of getTemplates `templates` get one element which have `anyTerrain` set to true (this is difference between crashing and not crashing scenario). This causes `ObjectTemplate::canBePlacedAt(TerrainId terrainID)` to return false, and filtered list is empty.
Don't know how to fix that but hope it can help somebody

**Comment by IvanSavenko** [comment]
Bug found - `anyTerrain` field is not serialized, so likely to not have correct value after game load. Will be fixed.
