### ISSUE TITLE
AI doesn't escape from battles

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#2113]
Moved to #2423 #2424

**Comment by by003** [comment]
For Battle AI, creature spells are never used. I suppose damage spells and rising spells can be set into priority. In 0.99, creatures can use damage and rising, but no longer in 1.2 and higher version.

**Comment by by003** [comment]
For neutral AI, it needs to use spells as well, for example, faerie dragons can only use melee attack which make their threat level being decreased.

**Comment by rilian-la-te** [comment]
@by003 what AI type is used by neutrals?

**Comment by by003** [comment]
> @by003 what AI type is used by neutrals?

Neutral AI is stupid AI, Battle AI is not suitable while I use it to battle with neutral troops.

**Comment by rilian-la-te** [comment]
@by003 why battle AI is not suitable? it is a matter of switching.

**Comment by Alucard648** [comment]
> @by003 why battle AI is not suitable? it is a matter of switching.

If you have only slow units, while neutrals are fast, they can run away around battlefield, leaving you unable to kill enemy, unless you have fast unit, shooter or direct damage magic. Which forces you to time out a and lose. Imagine if path further is blocked by fast neutrals, while your faction does not have either fast unit or shooter early and no luck with spells. SOL! In multiplayer game with high stakes. Setting Battle AI to neutrals renders all towns without early fast unit and shooter at huge competitive disadvantage in random maps, especialy in resource deprived games.

**Comment by dydzio0614** [comment]
stupidAI is kinda in same state in VCAI - currently if it has some advantage then it exists by accident. In my opinion battle AI should probably be default for neutrals.
@Alucard648 if I understand correctly AI can dodge fight when playing melee vs melee units?

**Comment by Alucard648** [comment]
> @Alucard648 if I understand correctly AI can dodge fight when playing melee vs melee units?
Yes, and he abuses it, especially, if HotA 100 round limit is in his favour.

**Comment by by003** [comment]
> @by003 why battle AI is not suitable? it is a matter of switching.

You know neutral AI should not be complicated because at the beginning of game, and we just need a simple AI while battle with neutral troops. However, stupid AI is not satisfied to become a 'simple' opponent either, simply because it will be easily distracted by low level creatures with a little quantities. 

From neutral AI, I just suggest that it should have a definite target to eliminate more quantities of creatures, it doesn't need to  focus on war machines or troops with small quantities. For example, If I have 50 goblins and one gnoll, of course one gnoll will be attacked by neutral AI first, even its damage can kill 49 goblins. 

I suggest that stupid AI should not be replaced by battle AI, they need to be developed dividually.

**Comment by nullkiller** [comment]
Our Battle AI can not escape enemies for now or am I missing something? Sure later it may learn this behavior but it is not like very simple thing

**Comment by DjWarmonger** [comment]
> Our Battle AI can not escape enemies for now or am I missing something? Sure later it may learn this behavior but it is not like very simple thing

It should since 1.1.0:
https://github.com/vcmi/vcmi/labels/nullkillerai

However, I'm not sure what NKAI has to do with battles?

**Comment by nullkiller** [comment]
> It should since 1.1.0
No, it can avoid attacking stronger creatures (much stronger then AI ones) but this is more likely due to logic mistake. 
1.1 improved handling of 1 units, AI now tends to ignore them and attack stacks where it can yield the most damage even if it can not rich them in 1 turn.

**Comment by nullkiller** [comment]
But eventually it can learn this trick as well)

**Comment by by003** [comment]
Faerie Dragons can cast spells while in an auto battle, but other creatures cannot, especially new creatures from mod.

**Comment by DjWarmonger** [comment]
> > It should since 1.1.0
> 
> No, it can avoid attacking stronger creatures (much stronger then AI ones) but this is more likely due to logic mistake. 1.1 improved handling of 1 units, AI now tends to ignore them and attack stacks where it can yield the most damage even if it can not rich them in 1 turn.

I meant running from battle during battle, not related to NKAI as far as I know.

**Comment by nullkiller** [comment]
Now it is not clear what this bug is about and what is the expected result. Adventure AI do retreat but quite seldom so you have a chance to kill him

**Comment by nullkiller** [comment]
Closing it as stale issue. Not clear what is the expected result.
