### ISSUE TITLE
VCAI and NullKiller have undefined symbols on Gentoo Linux

### ISSUE THREAD

**Issue by ghost** [vcmi/vcmi#2117]
**Describe the bug**
VCAI and NullKiller AI have unknown symbols on Gentoo Linux.

**Game logs**
This is what happens when NullKiller is selected as the Adventure AI: [nullkiller_log.txt](https://github.com/vcmi/vcmi/files/11398981/nullkiller_log.txt)
And this is what happens when VCAI is selected as the Adventure AI: [vcai_log.txt](https://github.com/vcmi/vcmi/files/11398989/vcai_log.txt)
The common denominator for both errors is undefined symbols.
NullKiller:
```
./vcmiclient: symbol lookup error: ./AI/libNullkiller.so: undefined symbol: _ZN2fl13InputVariableC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEdd
```
VCAI:
```
./vcmiclient: symbol lookup error: ./AI/libVCAI.so: undefined symbol: _ZN2fl13InputVariableC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEdd
```

**To Reproduce**
1. Install Gentoo
2. Download and extract VCMI 1.2.1 source code: `curl -L https://github.com/vcmi/vcmi/archive/refs/tags/1.2.1.tar.gz | tar -zxf -`
3. Go to a quiet place where you can compile the source code: `mkdir vcmi-1.2.1/build && cd vcmi-1.2.1/build`
4. Configure the source code the way that actually works on Gentoo:
```
cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_ERM=no -DENABLE_LUA=no -DENABLE_LAUNCHER=yes -DENABLE_EDITOR=yes -DENABLE_TRANSLATIONS=yes -DENABLE_PCH=yes -DENABLE_NULLKILLER_AI=yes -DENABLE_MONOLITHIC_INSTALL=OFF -DFORCE_BUNDLED_FL=OFF -DFORCE_BUNDLED_MINIZIP=OFF -DCMAKE_BUILD_TYPE=GentooRelease ..
```
5. Build VCMI: `ninja -v` (add -l and -j flags as you see fit)

**Expected behavior**
VCMI should have no problem starting a single player game with AI.

**Actual behavior**
VCMI crashes because AI libraries have undefined symbols.

**Did it work earlier?**
Some 3 years ago I had VCMI 0.9.9 from vortex overlay and it worked. When GCC 12 came out, it came out with breaking changes for fuzzylite and when at some point fuzzylite required a recompile, I've noticed that things are broken. This has been left broken for some time until I had enough of excluding fuzzylite in global system updates, and decided to intervene. One thing lead to another, and here we are - I'm filing this bug, because I'd like to invest some of my time to fix or help fix these issues.

**Version**
 - OS: Gentoo Linux
 - Version: 1.2.1

**Comment by rilian-la-te** [comment]
Or just use bundled fuzzylite)
