### ISSUE TITLE
Artifacts does not display its bonuses

### ISSUE THREAD

**Issue by rilian-la-te** [vcmi/vcmi#2128]
**Describe the bug**
Self-explanatory

**Game logs**
Not applicable

**To Reproduce**
1. use vcmiforgeofnoldorking
2. observe stats

**Expected behavior**
Stats should be changed

**Actual behavior**
It is not

**Did it work earlier?**
Yes, before 1.3

**Screenshots**
![image](https://user-images.githubusercontent.com/1329638/236504105-a9f04a72-1d67-4a2e-8d7f-90facd033c17.png)

**Version**
 - OS: Linux
 - Version: develop

**Additional context**

**Comment by krs0** [comment]
can someone give more priority to this please?
Other things depend on this basic stuff working.

**Comment by IvanSavenko** [comment]
Might be related to recent PR's by @SoundSSGood

**Comment by SoundSSGood** [comment]
> Might be related to recent PR's by @SoundSSGood

No. This has been previously reported https://github.com/vcmi/vcmi/issues/1920.

**Comment by IvanSavenko** [comment]
Might be cheat code bug - artifacts acquired normally (e.g. starting artifact, picked up artifact) work as expected

**Comment by rilian-la-te** [comment]
When I bought an artifact from a merchant - this is also not showing all bonuses.
