### ISSUE TITLE
Pressing SPACE to skip music crashes game because of tactics

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2129]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15194321/236542274-0e2b1c4e-b19b-4c1f-be22-be0b373842e2.png)

**To Reproduce**
1. Start a battle and quicly press SAPACE

**Version**
 - OS: [e.g. Windows,
 - Version: develop

**Comment by IvanSavenko** [comment]
Will recheck later when I am on develop, but not reproducible for me on my PR branch.

**Comment by krs0** [comment]
On your PR branch looks like its working, but the behavior's may be not the expected one.
Actual behaviour: Shortcuts start functioning right away, like SPACE for next creature, C for cast ... etc...
Expected behaviour: only music is skipped no other actions.

**Comment by IvanSavenko** [comment]
Yeah, that's wrong, will fix
