### ISSUE TITLE
Permanent bonus from idol of fortune 

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2131]
**Describe the bug**

**Game logs**
[logs.zip](https://github.com/vcmi/vcmi/files/11412195/logs.zip)

**To Reproduce**
1. Start map
2. Visit idol of fortune
3. Receive +1 morale till next battle bonus
4. Start and win any battle 

**Expected behavior**
Bonus from idol of fortune disappeared

**Actual behavior**
Bonus from idol of furtine is kept

**Did it work earlier?**
Broken in 1.2

**Screenshots**

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: 1.2.1

**Additional context**

**Comment by rilian-la-te** [comment]
Can you post a logs? Will look for it.

**Comment by IvanSavenko** [comment]
Not reproducible for me on latest develop. Fixed by #1822?
