### ISSUE TITLE
Campaign hero starts without quest artifacts

### ISSUE THREAD

**Issue by peterpaulis** [vcmi/vcmi#2134]
**Describe the bug**

In Armagedons blade 1 campaign Maker Of Sorrows, the main hero Xeron starts without quest artifacts making impossible the campaign to complete
http://bloggingheroes3.blogspot.com/2011/07/maker-of-sorrows.html

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
Go to Armagedons blade campaign Maker Of Sorrows and you will start without artifacts

**Expected behavior**
The hero Xeron should have 4 quest artifacts equipt from the start

**Actual behavior**
Hero starts without artifacts

**Did it work earlier?**
If this something which worked well some time ago, please let us know about version where it works or at date when it worked.
Dont know

**Screenshots**

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: [VCMI version]
Vcmi 1.2, ipad

**Additional context**

**Comment by peterpaulis** [comment]
also the same problem on the last campaing of Armagedons blade, where the hero has no Armagedons blade :)

**Comment by ViaFerrata** [comment]
+1 on Android.
