### ISSUE TITLE
Enter shortcut doesn't work in save screen

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2136]
**Describe the bug**

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Start any scenario
2. Press menu -> save game
3. Select any game slot
4. Press enter

**Expected behavior**
Save happened, window closed

**Actual behavior**
Nothing happens

**Did it work earlier?**
Yes

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: develop

**Additional context**

**Comment by kambala-decapitator** [comment]
the "traditional" enter (aka Return) or the keypad enter?
