### ISSUE TITLE
Language auto select first start

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#2140]
**Describe the bug**
Just one little thing that would be nice: When you start VCMI for the first time, the "FirstLaunch" dialog appears. It would be nice if the system language of the operating system would be preselected there. If language not exists in vcmi, then english.

**Comment by IvanSavenko** [comment]
Note to self:
Qt offers this for OS language detection
https://doc.qt.io/qt-5/qlocale.html#uiLanguages

**Comment by yellius** [comment]
I'm having the same issue and it seems to block the launcher from allowing to click "next" to step 3 of 3 Mods Preset

**Comment by IvanSavenko** [comment]
Not the same issue.

Can you confirm that you have 1.2.1? This issue was in 1.2 and should have been fixed in 1.2.1
Can you show screenshot of Launcher on a step at which you've stuck?

**Comment by yellius** [comment]
you're right, it wasn't the same issue - fixed
