### ISSUE TITLE
During the siege, AI controlled units are unable to move

### ISSUE THREAD

**Issue by tianmaster** [vcmi/vcmi#2141]
Describe the bug

During the siege, if the defending party has a defensive tower, they will not be able to take any action when it comes to the AI controlled Stack operation. The game cannot continue normally.
Even during automatic battles between two AI's, such anomalies can cause the player to get stuck after the end of the turn, and the AI cannot complete the siege they should have completed.

Game logs
[VCMI_Client_log(4).txt](https://github.com/vcmi/vcmi/files/11427856/VCMI_Client_log.4.txt)
[VCMI_Server_log(4).txt](https://github.com/vcmi/vcmi/files/11427905/VCMI_Server_log.4.txt)

To Reproduce

A normal attack on an AI town with a garrison can trigger this bug, but seems to have conditions? It seems like a town with a defense tower is necessary

Actual behavior
Because AI does not control its units for any actions, players are also unable to perform any actions. However, it was not frozen during the process, and it was not possible to press the menu button.

Did it work earlier?
Frequent occurrences in the 1.3 development version，Normal performance in 1.2.1

Screenshots
![1683610772070](https://user-images.githubusercontent.com/51704354/237009022-7b329d88-95e4-4d30-90d8-f9ad95c7aa22.jpg)

Version

OS: Android MIUI 14.0.3
Version: [VCMI-branch-develop-c21d312]
Additional context

**Comment by IvanSavenko** [comment]
Most likely will be fixed by #2144

**Comment by nullkiller** [comment]
Fix merged, Can you still reproduce the issue?

**Comment by tianmaster** [comment]
> Fix merged, Can you still reproduce the issue?

I cannot reproduce this issue in the new development version, I think it should be resolved
