### ISSUE TITLE
Size filter in save game window do not work

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2148]
**Describe the bug**
Clicking a size filter in save game window does not hide filtered out maps.

Weird behaviour... if any sorting is clicked (like number of players), the filter applies.

Also seeing if filter is enabled or not is not noticeable. 

**To Reproduce**
1. Go to save game window
2. click on size filters
3. maps are not filtered out even if wrong size

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/15194321/f2a98452-61f2-4bc4-9725-53d598a52549)

**Version**
 - OS: [e.g. Windows,
 - Version: debug

**Comment by IvanSavenko** [comment]
Not reproducible, presumably - fixed by PR #2324
