### ISSUE TITLE
Game freeze due to 'vcmiarmenelos' (build all) cheat

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2150]
**Describe the bug**
Seems to be caused by #2107 

Now, if new structure is built in town vcmi will always open town window. In normal scenario (building via town hall) this is harmless since town window is already open, but when using cheat that builds every structure or, potentially - town events, vcmi will now open town screen if there is a visiting hero, leading to freeze for unknown reason (dialogs due to visiting newly built buildings?)

**To Reproduce**
1. Start any map, select Fortress as starting town (although probably any town with hero-bonusing building will work)
2. Make sure that there is a visiting hero in selected town
3. Open console and use `vcmiarmenelos` (build all) cheat
4. Exit town and try to move hero

**Expected behavior**
Nothing. All town buildings are built, but no visual changes in UI, aside of potential changes of town appearance / town description in info box

**Actual behavior**
VCMI attempts to open town screen, animate all newly constructed buildings one at a time, and then freezes for unknown reason - game still "responds", but any action, e.g. hero movement has no effect.

**Did it work earlier?**
Definitely worked before, most likely OK in 1.2.

**Version**
 - current develop branch

**Comment by IvanSavenko** [comment]
Another side effect - town theme restarts when you buy a hero in tavern. Don't remember this happening before.

**Comment by dydzio0614** [comment]
well, this is only partially fixed since for towns with multiple popup buildings (dungeon) this is broken for longer time
