### ISSUE TITLE
Fort level icon is missing from info box

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2158]
**Describe the bug**
When selecting a town, fort icon is never present in infobox. It does not matters whether your town has fort/citadel or castle - icon never appears. Same issue with right click popup when clicking on town (they use shared code AFAIK)

Other places that show fortifications (town screen and kingdom overview) work fine

**To Reproduce**
1. Start any map
2. Select town or right click on town
3. Look at infobox 

**Expected behavior**
Infobox should show hall level, fortifications level and income

**Actual behavior**
Infobox shows hall level and income. Fortifications icon is always missing

**Did it work earlier?**
Definitely worked before, but no idea when

**Screenshots**
![зображення](https://github.com/vcmi/vcmi/assets/1576820/ea871a3d-61c5-401c-a411-514461b856ac)

**Version**
 - develop branch

**Comment by rilian-la-te** [comment]
I did not any change inside this function of infobox.

**Comment by mikeiit** [comment]
This actually happened to me today, I can take a look.
