### ISSUE TITLE
In Battle buttons are not responding

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2162]
**Describe the bug**
With latest nightly build the in battle buttons are not working
 
![image](https://github.com/vcmi/vcmi/assets/15194321/d26a5407-6b26-4beb-85b7-95d3bed12c7f)

![image](https://github.com/vcmi/vcmi/assets/15194321/d2b4a2ff-5a2e-458a-84f8-d3bfc986634e)

**Version**
 - OS: [e.g. Windows,
 - Version: nighlty

**Comment by IvanSavenko** [comment]
Battlefield actions submod enabled? Are you sure that vcmi-extras up-to-date?

**Comment by krs0** [comment]
vcmi extras strikes again... sorry for report.
