### ISSUE TITLE
Black colour is lost in town at the adventure map

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#2170]
**Describe the bug**
Some towns in new model lost their black colour border.

**To Reproduce**
1. At least a new town mod was installed;
2. Enter a map

**Expected behavior**
Black colour can be normally showed.

**Actual behavior**
This colour becomes a transparent one and obvious in snow terrian.

**Did it work earlier?**
No problem in 1.2.1 version

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/127420617/c79dc60b-d694-4fe4-abd2-9e340541c04e)
![image](https://github.com/vcmi/vcmi/assets/127420617/06474ddb-672f-4eb1-839e-4a3387b87c5c)

**Version**
 - OS: Windows
 - Version: Latest build in 1.3.0

**Comment by by003** [comment]
Still exists in latest build

**Comment by IvanSavenko** [comment]
Should be fixed in next build tomorrow.

Let me know if something else is still wrong

**Comment by by003** [comment]
Please mention about cheat code 'vcmiarmenelos' as well. It will cause crash when click on a town-visited hero.

**Comment by IvanSavenko** [comment]
Cheat - likely same issue as #2150

**Comment by by003** [comment]
OK, maybe just for AI improvement.
Did you have the plan to change the menu? or let map locked to prevent scale up and down？

**Comment by IvanSavenko** [comment]
AI improvements - up to Nullkiller aka Danylchenko

Menu changes - likely low-priority, not yet sure how to make such menu that will work well on any systems

Prevent scaling up and down - perhaps can be made into an option for those who don't like it. We do have an undocumented hotkey - "backspace" that will reset scaling to default.
