### ISSUE TITLE
Better touchscreen UI support

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2172]
Note: all of this refers to "standard" mode, relative pointer mode (aka touchpad emulation) should probably stay as it.

Considering (at the moment) open PR's that:
1) Allow zoomable adventure map that needs some access for mobile systems
2) Refactor of input system that simplifies changes to touch input

We can now, with relatively low difficulty implement better management of touchscreen systems (e.g. Android) using gestures common in mobile UI use. Since SDL does not provides gesture recognition, this code will have to be done on VCMI side. Proposed list of gestures and their in-game usage:

Tap: (already supported)
- method: quick touch and release on approximately same location
- usage: generates left-click down + up events in game

Swipe:
- method: touch and move in horizontal or vertical direction (but not both)
- usage: generates swipe gesture event, acts similar to mouse wheel in most cases - scrolls underlying list
- usage: potentially, can be used in battles - swipe from attack position to enemy position to select attack direction
- usage: potentially, can be used to implement quick army management shortcuts

Pan:
- method: touch and move in *any* direction. Can be merged with swipe?
- usage: generates pan gesture event, acts to move adventure map view

Pinch:
- method: double-finger gesture, move two fingers closer / further away
- usage: generates pinch gesture event, acts to zoom adventure map view

Touch and hold: (iOS uses slightly different behavior)
- method: touch and keep finger at approximately same point for certain time
- usage: generates right-click down event to show popup window
- next tap gesture will be generate double-click up event to hide popup window

Current two finger-tap that is used to emulate right-click on Android will be removed

**Comment by Nordsoft91** [comment]
Currently pinch is used for spacebar action. I'd advice triple touch for spacebar instead.
