### ISSUE TITLE
During the siege, the arrow tower was unable to function, causing the game to freeze

### ISSUE THREAD

**Issue by tianmaster** [vcmi/vcmi#2174]
Describe the bug

During the siege, the arrow tower was unable to function, causing the game to freeze。

Game logs
[VCMI_Server_log(1).txt](https://github.com/vcmi/vcmi/files/11521353/VCMI_Server_log.1.txt)

To Reproduce

Attack any town with an arrow tower

Actual behavior
At the beginning of the battle, the game freezes when it's time for the Arrow Tower operation

Did it work earlier?
In the VCMI brand development 0a874cd version, the Arrow Tower still works properly.
VCMI brand development ddf22a7, the arrow tower will no longer work

Screenshots
No images

Version

OS: Android MIUI 14.0.3
Version: [VCMI-branch-develop-9817aaa](https://download.vcmi.eu/branch/develop/Android/arm64-v8a/VCMI-branch-develop-9817aaa.apk)
Additional context
[VCMI_Client_log(1).txt](https://github.com/vcmi/vcmi/files/11521355/VCMI_Client_log.1.txt)

**Comment by IvanSavenko** [comment]
Already fixed
