### ISSUE TITLE
Interface scaling doesn't give options > 70%

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2179]
**Did it work earlier?**
new feature

**Version**
 - OS: iOS
 - Version: vcmi-1.3.0 (develop)

![IMG_2700](https://github.com/vcmi/vcmi/assets/9308612/af982f13-75bc-471c-a41b-6bfe70c2137d)
![IMG_2701](https://github.com/vcmi/vcmi/assets/9308612/faa9c2f8-c967-459f-834f-cd4f6911f245)

**Comment by IvanSavenko** [comment]
What's the resolution of your device?
If height is below 600px - then works as designed, you need at least 800x600 display to use 100% scale.
If not - might be some issues with retina display. I believe SDL uses some hints to define whether app is highDPI-aware, and if not - will return adjusted values for display size and such.

Can try to search for them, but hard to do so without such device.

**Comment by IvanSavenko** [comment]
This should be handled inside `ScreenHandler::getPreferredRenderingResolution` method. On mobiles this method needs to return native resolution of the device.

Currently it uses `SDL_GetDisplayBounds` call to get screen size.
Perhaps we should use `SDL_GetDesktopDisplayMode` instead? Can check on desktop, but no idea what this method will return on ios.

**Comment by Nordsoft91** [comment]
iPhone XR has 1792 x 828

**Comment by Nordsoft91** [comment]
I can download and test builds from PRs

**Comment by IvanSavenko** [comment]
So, in total we need:
- get actual resolution size, accounting retina to compute "real" interface scaling percentage
- add a way to control size of reserved areas to left & right of the screen for those iphone cutouts (not sure how SDL on Android works here, so we might need this not just on ios)
- check computation of starting interface scaling percentage to avoid main menu not fitting the screen

Is all of this correct? Anything I missed?

**Comment by Nordsoft91** [comment]
Ideally, give some flexibility on scaling UI up - only side and bottom bar, because buttons are small.

> add a way to control size of reserved areas to left & right of the screen for those iphone cutouts

OR give option: fit full content or fit full screen

**Comment by Nordsoft91** [comment]
maybe this one https://github.com/openfl/lime/issues/1606 is what we need

**Comment by IvanSavenko** [comment]
> OR give option: fit full content or fit full screen

Don't see much point in a *toggle* when one of values of that toggle is basically broken game.

In any case main problem here is that SDL API currently does not provides way to detect size of those cutouts. If you can provide this value to c++ via some native method call - I can make automatic adjustment to ignore cutouts.

For now I'm leaning to a mobile-only option that allow player to adjust width of unused side areas, with non-zero default value on ios

**Comment by kambala-decapitator** [comment]
"Reserved areas" on iOS: yes, the "safe area api" is the right approach
