### ISSUE TITLE
Launcher crash when press hota

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2187]
**To Reproduce**
1. Open launcher
2. press "download & refresh repositories"
3. Find horn of the abyss mod
4. Select it

**Expected behavior**
Hota mod info is shown

**Actual behavior**
Crash

**Version**
 - OS: MacOs
 - Version: 1.2.1, 1.3

**Comment by IvanSavenko** [comment]
Not reproducible for me

**Comment by Nordsoft91** [comment]
1) make sure hota mod isn't installed previously
2) check repository https://raw.githubusercontent.com/vcmi/vcmi-mods-repository/develop/vcmi-1.3.json

I have same issue even after downloading hota 1.6.0 manually

**Comment by IvanSavenko** [comment]
vcmi-1.2 - everything OK
vcmi-1.3 - hota is missing for some reason (will investigate), but no crashes

**Comment by IvanSavenko** [comment]
Tested both 1.2.1 and 1.3. Hota not installed

Both versions work fine with their corresponding repository (vcmi-1.2.json and vcmi-1.3.json).

**Comment by Nordsoft91** [comment]
Crash happens in CModListView::genChangelogText from cmodlistview_moc.cpp in std::sort somewhere in qt stuff while arrays are fine. 
I was able to fix by replacing std::sort with qSort but it's marked as deprecated

**Comment by IvanSavenko** [comment]
Noted.
Not sure if we even need sorting in there.

Feel free to submit PR, if not - will fix it myself for 1.3
