### ISSUE TITLE
Overlapped text in options

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2189]
**To Reproduce**
1. Open in-game menu
2. Adventure map tab
3. Adjust hero speed/map speed

**Expected behavior**
Numbers are shown properly

**Actual behavior**
Numbers are overlapped

**Screenshots**
<img width="152" alt="Снимок экрана 2023-05-28 в 04 27 54" src="https://github.com/vcmi/vcmi/assets/9308612/1ca9420a-1c1b-48dc-8c35-b5f7c5b01a53">

**Version**
 - Version: develop

**Additional context**
Windowed mode, if important

**Comment by mikeiit** [comment]
Please ignore the status change I made to this bug, I was just trying something out in my own fork's projects. I happened to see this issue earlier while running release version of the code locally. I might look into this issue. 

But feel free to let other folks jump in if this needs to be solved sooner than later. Thanks.

**Comment by IvanSavenko** [comment]
@mikeiit feel free to look into this issue if you wish to. If it turns to be too hard for somebody not familiar with vcmi code - you can try to check #2165 or #2158 instead.

As for this one - most likely related to REDRAW_PARENT flag not applied somewhere.
