### ISSUE TITLE
Some shortcuts doesn't work in game menu

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2190]
Several scenarios
1. Main menu -> Network game -> join2 -> expected return and escape shortcuts, but doesn't work
2. Same as above -> "enter address" window ->  expected return and escape shortcuts, but doesn't work
3. Single player -> map selection -> double click at any map -> expected map start
4. Save game -> same scenarios (doublick at save, return, escape)

**Comment by IvanSavenko** [comment]
Same issue with creature split dialog - hotkeys don't work (Enter, Escape, left/right)

(I think I know the cause, noting this to recheck fix)

**Comment by IvanSavenko** [comment]
Double click - unable to reproduce.
Others - confirmed, will fix
