### ISSUE TITLE
Need to press key twice

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2193]
Start any scenario with welcome message (e.g. day 0 message)
Press return to close window

**Expected behavior**
Window is closed

**Actual behavior**
Window is not closed - need to press enter again.

**Comment by IvanSavenko** [comment]
I *might* have found this but seems to be happening only when activating a window and only with mouse click, not with keyboard.

If this is same scenario as yours - then will be fixed soon - default SDL behavior, but can be changed.

**Comment by IvanSavenko** [comment]
Very unstable reproducibility. Happens only *sometimes*, but not idea what's the trigger.

Will fix if manage to reproduce it again or if somebody manages to find more reliable repro
