### ISSUE TITLE
Warning message isn't shown

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2194]
**To Reproduce**
1. Start game in windowed mode - make sure you have hero with MP
2. Switch to fullscreen (borderless)
3. Switch to another window (aka alt-tab)
4. Switch back to game
5. Press E - nothing happens
6. Click at end turn

**Expected behavior**
Warning message appears (your heroes still have movement points)

**Actual behavior**
End turn 

**Screenshots**

https://github.com/vcmi/vcmi/assets/9308612/feca86f3-cc4e-46ad-8890-2b4014a86943

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: [VCMI version]

**Additional context**

**Comment by IvanSavenko** [comment]
Unable to reproduce on my branch, probably fixed
