### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#2196]
**Describe your proposal**
Only a small less important issue:
In OH3 it is possible to change your name in singleplayer player-selection. VCMI doesn't allow this.

![Peek 2023-05-28 15-52](https://github.com/vcmi/vcmi/assets/13953785/3185abda-d8ea-46c3-a3ae-3e67f3af2ffc)

**Additional context**
Same functionality as OH3 should be supported

**Comment by IvanSavenko** [comment]
For reference - it is also possible in vcmi, but only in hotseat dialog. Name of first player will be saved as player name for singleplayer.

(But yeah, we also need more intuitive editing from here)
