### ISSUE TITLE
Random Map Generator - Persistent map settings between game sessions (selected template, selected map, difficulty)

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#2197]

**Comment by krs0** [comment]
So in the end it would be possible to fully set up a RMG -> start a game -> go to Main Menu -> press only Start Game and a similar map to be generated?

**Comment by DjWarmonger** [comment]
This ticket is a part of HoTA improvements, so should work at least as good as HoTA.

**Comment by DjWarmonger** [comment]
I just recalled that Map Editor also saves map settings between sessions. Should I try to reload settings from MapEditor in Lobby and the other way round? Does it make sense from user's point of view?

It is not a simple thing to do, as Editor settings are stored via Qt and we don't have in in lib. So can't reuse that code.
