### ISSUE TITLE
A test for existing rate of Fire Magic 

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#2198]
**Describe the bug**
In OH3, all heroes will learn a faction of magic skills every 3 or 4 levels, but in current version, heroes will easily learn fire magic in their upgrades. We have tested it with a black box method, and find that:
1. If a hero can learn fire magic, he/she will get fire magic certainly after 3 or 4 levels.
2. If a hero cannot learn fire magic, like a beastmaster, he/she will not get another faction of magic skills after 3 or 4 levels.
3. If a hero already has fire magic skill, he/she will not get another faction of magic skills either.

**To Reproduce**
1. Go to any maps.
2. Make a hero to upgrade for 3 or 4 levels. (Generally might hero for 3 and magic for 4)
3. See the skills which he/she will learn.

**Expected behavior**
After 3 or 4 levels, at least a faction of magic skills will exist.

**Actual behavior**
See in 'Describe the bug'.

**Did it work earlier?**
Maybe work in 0.99.

**Version**
 - OS: Windows
 - Version: 1.2.1

**Comment by rilian-la-te** [comment]
Will look for it.

**Comment by Alucard648** [comment]
It`s supposed to be Wisdom, instead of Fire Magic.

**Comment by IvanSavenko** [comment]
It is both.
1) Wisdom (every 6 levels for might classes, every 3 levels for magic classes)
2) Random magic school (every 4 levels for might, every 3 level for magic classes)

**Comment by rilian-la-te** [comment]
This look like than random selection from obligatory skills need to be checked. Will do in weekend.
