### ISSUE TITLE
In Rise of the Necromancer campaign, Sandro can not bring cloak of the undead Lord to next scenario

### ISSUE THREAD

**Issue by lf2653** [vcmi/vcmi#2204]
**Describe the bug**

I complete the first scenario Target, and make sure Sandro dress cloak of the undead Lord and armor of the Damned. But when I arrive next scenario, l lose these two. strange thing~

**Game logs**

[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11642927/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11642930/VCMI_Server_log.txt)

And this is the save, you can test it~

[battle_save.zip](https://github.com/vcmi/vcmi/files/11642931/battle_save.zip)

**Version**
 - OS: Windows, iOS
 - Version: 1.2.1

**Comment by peterpaulis** [comment]
Looks like in the campaigns the starting campaign artifacts are ignored

https://github.com/vcmi/vcmi/issues/2134
