### ISSUE TITLE
Add a way to revisit current object on Android

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2205]
**Describe your proposal**
Currently, VCMI provides no way to revisit object hero is standing on for Android:
- Mobile platforms have no keyboard to press space key
- Pinch gesture is/was used on iOS, but now same gesture is used for zooming adventure map

We need to consider a way to access such action, for example via gesture and/or via additional button on adventure map screen. Possible options:
- double-tap
- two-fingers tap
- three-fingers tap
- new button near existing adventure map buttons
- new button at the bottom of the screen, similar to HD Mod chat button
- more radical redesign of adventure map for mobile devices, potentially - increasing size of existing buttons
- radial menu to provide access to most common actions

Potential problems of these approaches:
- touch gesture is the most convenient option, but player will need a way to discover such gesture without asking for help in community.
- button is the most easy to find option, but requires UI design and graphical assets. Also, button must be notably larger than existing UI elements. From my tests ~64x64px-sized UI element is smallest option that avoids misclicks. Less of an issue on larger devices or tablets. 
- radial menu might be the most suitable option, but also most complex to implement. Perhaps consider after army management? (#2199)

**Additional context**
Unfinished part of PR #2185

**Comment by SoundSSGood** [comment]
> * touch gesture is the most convenient option, but player will need a way to discover such gesture without asking for help in community.

May be made gestures and hotkeys customizable? For example, by adding another tab to the launcher. In this case, the player will not have any questions for community.
Of course, for this the player needs to be shown a list of supported gestures.

**Comment by SoundSSGood** [comment]
It looks like the Hota crew decided to add a button to the interface for this purpose. This was seen on the latest screenshots posted by Hota crew.
<img width="61" alt="1" src="https://github.com/vcmi/vcmi/assets/87084363/b4cf88be-7e15-4886-9f2d-c1fd0ae72092">

**Comment by Laserlicht** [comment]
Is now possible :)

related #2663

**Comment by stuart135** [comment]
> Is now possible :)
> 
> related #2663

How ist it possible?

**Comment by IvanSavenko** [comment]
> How ist it possible?

Install (or reinstall) VCMI extras mod.
This should give you additional button in UI, to the right from "next hero" button, above "end turn" button.

**Comment by stuart135** [comment]
> > How ist it possible?
> 
> Install (or reinstall) VCMI extras mod. This should give you additional button in UI, to the right from "next hero" button, above "end turn" button.

Thank you very much. This makes the Android version a lot better.

**Comment by IvanSavenko** [comment]
Closing, implemented in vcmi-extras mod
