### ISSUE TITLE
Sliders sensitivity is broken

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2212]
IOS
See videos, it's (almost) impossible to control sliders

https://github.com/vcmi/vcmi/assets/9308612/808b8110-5b1a-4586-ad73-ceb6b62ce68e

https://github.com/vcmi/vcmi/assets/9308612/950d7091-1e4e-4e1f-b4ca-5428981dfe9c

**Comment by IvanSavenko** [comment]
It is not like sliders were usable on mobile before, with that tiny line that you had to hit correctly with a finger....

Noted, will adjust slider movement speed, seems to be too low in these cases (and likely in some other cases, e.g. recruitment screen)

**Comment by IvanSavenko** [comment]
And what was success rate of clicking that... ~1.5 mm-wide line with a finger that's like 10 times wider?

Might have been usable on tablet, but not on phones

**Comment by Nordsoft91** [comment]
I don't have tablet, only iphone xr.Never had any problems with tapping them.

**Comment by IvanSavenko** [comment]
Hmm... Perhaps iphone's have better sensor / better detection for touch point?

They are definitely too narrow to click for me & I've seen complains about other UI elements with similar size, so it is not just me/just my device.

Well, in any case, will look into this soon.

**Comment by Nordsoft91** [comment]
I suggest to take YouTube/Spotify app as reference and not trying reinvent ux. Those have sliders to navigate over video/audio.
If those sliders are hard to hunt either, then it's device-specific I believe.

**Comment by IvanSavenko** [comment]
Checked youtube app
They use small, circular "slider" button. However area that activates dragging mode is noticeably larger than visual circle. Looks to be semicircular area with around x2 radius than slider itself
