### ISSUE TITLE
Uncolntrolled zoom with pitch

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2213]
IOS
Apply two fingers and move them to any directions (pan or pitch)
See video 

https://github.com/vcmi/vcmi/assets/9308612/c730a9ca-7540-49ae-aeea-a83300277920

**Comment by IvanSavenko** [comment]
Probably ios-specific pinch handling interfering with common input handling. 
How can it be disabled? I think it is somewhere in objective-c wrapper code?

**Comment by kambala-decapitator** [comment]
It's here in the first method: https://github.com/vcmi/vcmi/blob/develop/client/ios/startSDL.mm

**Comment by kambala-decapitator** [comment]
Lines 31-105 and 116-122
