### ISSUE TITLE
Swift programming language welcome?

### ISSUE THREAD

**Issue by Sajjon** [vcmi/vcmi#2219]
Hello dear HoMM3 lovers and programmers (addressing the VCMI authors and primary maintainers)!

Do you all LOVE C++ or is it something you like/accept or even find somewhat cumbersome sometimes - compared to modern programming languages like Swift?

I'm a HoMM lover since 1997, and programmer in love with Swift (since beta). [Very Recently Swift has got great C++ interrop](https://forums.swift.org/t/c-interoperability-in-swift-5-9/65369), it is both possible to call Swift from C++ and calling C++ from Swift. Without any performance loss. Swift can be compiled with CMake. 

I think this would be an excellent way of upgrading VCMI, to the modern age of Swift. 

The advantage of using Swift (over C++) are:
1. Memory safety 
2. Swifts amazing actor model with protection against data races
3. Type safety
4. Do more with less code
5. Easier to read and maintain
6. Standardized 
7. More attractive and appealing for new developers, resulting in more contributors/maintainers of VCMI

I lack the expertise of HoMM3 development that the VCMI team has, but I am not clueless, I've written [Makt](https://github.com/Sajjon/Makt) (backend) and [Tritium](https://github.com/Sajjon/Tritium) (frontend) in Swift, which parses Lod, Def, H3M files and converts to JSON and managed to render maps using SwiftUI. I appreciate that this is ofc only 0.1% of what makes up HoMM3...and Ive not been developing on these project in over a year.

Since Swift C++ interop was presented recently, I've regain my hope of developing HoMM3 in Swift by gradually introducing and converting VCMI to Swift.

What are your thoughts? If you are all avid C++ lovers and Swift opponents I guess I'll will have to do with working in a fork... 

Thank you for an amazing project btw, it was helpful during my work last year!

Best regards 
Alex

**Comment by dydzio0614** [comment]
I agree with @IvanSavenko - also I am not sure if Swift wouldn't limit ability to run code on multiple platforms, for example VCMI is able to run on Android, HaikuOS, AmigaOS (incomplete port), can be theoretically ported to Nintendo Switch etc.

**Comment by rilian-la-te** [comment]
Swift is good only for Mac and iOS, so, I agree with @IvanSavenko , please, no Swift here. Only C++ and, if you wish to improve scripting, Lua.
