### ISSUE TITLE
Resurrected army is not alive after battle

### ISSUE THREAD

**Issue by peterpaulis** [vcmi/vcmi#2220]
**Describe the bug**
If i resurrect troops with the resurrection spells in battle, after the won battle they are dead / removed

**Game logs**

**To Reproduce**
1. Go to campaigns -> armagedons blade -> dragon slayer -> choose book of earth magic as bonus -> at the begging of map are earth elementals -> loose troops and resurrect them -> after battle the resurrected troops are lost

**Expected behavior**
In H3 resurrected troops stayed after the battle ended

**Actual behavior**
troops are los

**Did it work earlier?**
Dont know been playng only 1.2

**Screenshots**

**Version**
 - OS: ios 16
 - Version: 1.2

**Additional context**
![851790BD-C9D8-4401-BBF8-1499FCBD887E](https://github.com/vcmi/vcmi/assets/1956972/868fca63-a7fe-4b89-ab38-8e76dabc65d2)
![455219E8-4BD7-4D5A-A320-ED0496D8DAEE](https://github.com/vcmi/vcmi/assets/1956972/a5c4d1fb-dfd9-4921-9cb0-c92b2ede6fcc)

**Comment by dydzio0614** [comment]
did you hero have advanced+ earth magic skill?

**Comment by peterpaulis** [comment]
no he doesnt

**Comment by IvanSavenko** [comment]
Not a bug then. You need advanced or expert Earth magic for creatures to be resurrected permanently:
https://heroes.thelazy.net//index.php/Resurrection
> Target, allied troop with dead creatures has (40 + (power x 50)) health worth of creatures restored to life *for the duration of the current battle*

**Comment by peterpaulis** [comment]
My fault sorry never realized that
