### ISSUE TITLE
keyboard input on iPad for save gave doesnt mostly work

### ISSUE THREAD

**Issue by peterpaulis** [vcmi/vcmi#2221]
**Describe the bug**
on iPad when i try to save a game with new name, the keyboard is shown but no input is received in the text field and the input cursor is not shown on the input field
i can type but nothing is in the field and pressing save does nothing
occasianaly i was able to activate the input, not sure how, repeating save game and making sure to select the input fast, but getting it to work was mostly random with a 5% chance of working
so i ended up resaving ober my existing saves.... the save game name display is also weird

tried also changing different keyboard options but didnt help

same on iOS and iPadOS

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Go to Save game and activate input field

**Expected behavior**
normal input behavior

**Actual behavior**
keyboard is shown but no input is posssible, i can press the keys but nothing happens, even switching to floating keyboard

**Did it work earlier?**
dont know been playing only 1.2 where it was like this all the time

**Screenshots**
![29370EBB-ED78-4562-8DA9-E784FC5C778E](https://github.com/vcmi/vcmi/assets/1956972/86785912-ec2c-4ee1-a6fe-7d71850f0716)
![2CB27382-9DFF-4693-9467-3A2DF34AC69F](https://github.com/vcmi/vcmi/assets/1956972/a53b46c2-3a43-4e95-9591-09c256d1c01b)

**Version**
 - OS: iPadOS 16 and tryied also on iPhone iOS16
 - Version: 1.2

**Additional context**

**Comment by peterpaulis** [comment]
For entering hotseat player names the keyboard works fine all the time

**Comment by peterpaulis** [comment]
bigger size screenshot

![F2B1F196-A60B-4942-8B37-E1B5FD3014E9](https://github.com/vcmi/vcmi/assets/1956972/5ba71b5f-1e04-4d32-8856-3400952f77b4)

**Comment by peterpaulis** [comment]
this looks fixed on 1.3

**Comment by IvanSavenko** [comment]
Closing then? Feel free to reopen if something is still broken.

**Comment by peterpaulis** [comment]
i can confirm its working in 1.3 and not working in 1.2, not sure what changed in that way in the source
