### ISSUE TITLE
Tab chatting doesn't work in multiplayer, at least if it's not your turn

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#2224]
**Expected behavior**
using tab button and typing text, then confirming with enter should work

**Actual behavior**
Only relaying info from other players testing game but apparently it's broken

**Did it work earlier?**
Works in 1.2

**Version**
 - OS: Windows 10
 - Version: 1.3 recent develop

**Comment by IvanSavenko** [comment]
Seems to be "working" in current beta.
Hard to call anything related to MP working in 1.3 but at least chatting technically works
