### ISSUE TITLE
map reveals after first turn

### ISSUE THREAD

**Issue by psyhlo** [vcmi/vcmi#2228]
**Describe the bug**
After ending first turn the whole map reveals 

**To Reproduce**
1. Start new game from random map with team AI
2. End your turn
3. Map is revealed 

**Did it work earlier?**
last month worked and/or in 1.2 version

**Version**
latest dev build

**Comment by kambala-decapitator** [comment]
it has been like this with NKAI since forever, not a bug

**Comment by psyhlo** [comment]
how can be "not a bug"?

**Comment by rilian-la-te** [comment]
@psyhlo change NKAI to VCAI for "Friendly" in launcher. NKAI reveals a map is a feature of NKAI for being more challenging for a player.

**Comment by rilian-la-te** [comment]
Because AI reveals map for themself, and by rules of H3 you get shared vision for allies. So, if AI ally reveals map for himself, you share his map vision.

**Comment by psyhlo** [comment]
ok i get it, "nice" feature

**Comment by IvanSavenko** [comment]
@psyhlo Right now I am planning to add "Allied AI" option in Launcher, set to VCAI by default.

This will allow you to play against (relatively) good NullkillerAI, but allies will use VCAI which is weaker but does not reveals the map
