### ISSUE TITLE
Empty Pandora's box with a creature bonus

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#2233]
**Describe the bug**
In random map, Pandora's boxes are often empty, if their bonus are creatures.

**To Reproduce**
1. Go to any map with a creature bonus Pandora's box
2. Try to open it

**Expected behavior**
Creatures can be acquired.

**Actual behavior**
Show the message of empty box.

**Did it work earlier?**
Normal in 1.2.

**Version**
 - OS: Windows
 - Version: 1.3

**Comment by DjWarmonger** [comment]
Nevermind, I found it.

**Comment by dydzio0614** [comment]
Maybe he tried checking maps generated from map editor?

**Comment by DjWarmonger** [comment]
NVM, just found it and fixed it. No idea how it ever worked, though.
