### ISSUE TITLE
For of war uncovering area wrong calculation

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#2248]
Uncovered tiles mismatch between VCMI and original H3, screenshots show difference between revealed tiles - tested only towns and heroes without scouting range boosts

1. Start some map with generic "no scouting" hero, no random telescope artifact bonus etc.
2. Town's starting revealed tiles
3. Move hero via same path away from town in VCMI and H3, see that visible tiles from target destination are different in H3 and VCMI

**Expected behavior**
Same tiles should be revealed in H3 and VCMI

**Actual behavior**
There are differences on diagonal directions

**Did it work earlier?**
No

**Screenshots**
![Heroes 3](https://github.com/vcmi/vcmi/assets/9436577/77767e8d-cb57-4d74-a183-818e965a2fc7)
![VCMI](https://github.com/vcmi/vcmi/assets/9436577/0f900663-310d-41a9-a0f5-66bed1ac8074)
![Heroes 3](https://github.com/vcmi/vcmi/assets/9436577/4fd21a08-c7c3-434a-8a4a-268605274fbb)
![VCMI](https://github.com/vcmi/vcmi/assets/9436577/24c65331-4501-4535-b240-00ea01ea56ae)

**Version**
 - Kubuntu 22.04, current develop version of VCMI

Additional info: maybe the bug also affects FoW reveal of mine/dwellings/garrisons belonging to hero from day 1 and eye of magi

**Comment by rilian-la-te** [comment]
@dydzio0614 can you try to reduce SIGHT_RADIUS in json?

**Comment by dydzio0614** [comment]
this bug already happens for years, just nobody reported it

**Comment by dydzio0614** [comment]
![obraz](https://github.com/vcmi/vcmi/assets/9436577/591d9651-e087-4e05-bcee-2534b03b7651)
anyway here is sight radius 4:
