### ISSUE TITLE
Battle obstacles are rendered in front of the creatures

### ISSUE THREAD

**Issue by boctavian96** [vcmi/vcmi#2253]
**Describe the bug**
In battles some of the obstacles are rendered in front of the creatures.

**Game logs**
NA

**To Reproduce**
Note: I think this is kind of hard to reproduce :( 
1. Start a battle.
2. Move your unit near the obstacle (See the attached picture)
3. See the overlap

**Did it work earlier?**
Not sure

**Screenshots**
<img width="1728" alt="Screenshot 2023-06-24 at 19 33 58" src="https://github.com/vcmi/vcmi/assets/22297065/e539c567-8fcc-4d00-a4b0-620c71be270e">

**Version**
 - OS: macOS
 - Version: 1.2.1

**Comment by IvanSavenko** [comment]
Most likely - already fixed for 1.3

**Comment by IvanSavenko** [comment]
Same as in H3:
![зображення](https://github.com/vcmi/vcmi/assets/1576820/19e4383b-1c63-4905-a56a-92c169445fa6)

**Comment by cewbdex** [comment]
Well, for me it's a bug, not a feature to preserve, as it does not make much sense, but it's your choice.

**Comment by IvanSavenko** [comment]
Feel free to open new issue about that
