### ISSUE TITLE
Chronicles campaigns

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#2258]
**Describe your proposal**
VCMI should allow to load the official chronicles campaigns. Currently, these cause VCMI to crash.

**Additional context**
Someone was able to convert these campaigns to Heroes III V6-format (Chronicles uses V7). https://heroes3wog.net/all-heroes-chronicles-campaigns-chapters-for-heroes-3-complete-with-hd-mod/
These files can be loaded without problems.

You can use a HEX-Editor to see the differences.

But we should able to load the original GOG-Versions of the H3C's, instead of the "hacked" ones.

**Comment by dydzio0614** [comment]
Based on current VCMI state and needs, if this feature takes more than let's say 15 hours to be done then I think progress should be made elsewhere and priority of this feature should be low for now.

**Comment by IvanSavenko** [comment]
@dydzio0614 
Probably yeah.

If somebody can do research as to what must be done in vcmi codebase to support that AND such list turns out very small - we can consider such support. But that requires person familiar with vcmi code & capable of reverse-engineering chronicles h3c format as well as searching through chronicles data files to find new stuff (Tarnum portraits, campaign backgrounds, etc)

Might be better to postpone till we can support different data sources - roe demo, sod demo, roe...

**Comment by Laserlicht** [comment]
Yes - of course - it's low priority. But it would be good to support this in (far?) future. To support all official H3C/H3M-Formats.

**Comment by Laserlicht** [comment]
I've made some hex comparision between original h3c and "hacked" one, which is loadable. But for me it's hard to understand what differences are relevant or not relevant. The only way is to go through the source code step by step?

[Chapter 8 - The Sword of Frost.zip](https://github.com/vcmi/vcmi/files/11871465/Chapter.8.-.The.Sword.of.Frost.zip)

**Comment by misiokles** [comment]
Yeah, I've read many times at HC forum, that changes are only in headers.

**Comment by IvanSavenko** [comment]
Parsing chronicles h3c is trivial.
Problem would be with changes to executable / data files.

- H3 campaigns don't have campaign "map" for chronicles (one where you select scenario to play). Looks like in chronicles executable / data files one of campaigns was changed to have required number of scenarios. (and all related graphical assets were replaced). So we need to adapt to this change.
- H3 does not have portraits for Tarnum. And H3 does not provides a way to add new portrait (without hero). So we need to investigate how Tarnum portrait has been implemented in chronicles and adapt to this change

There may be other changes that I am not aware of.

Another issue is that I'd rather avoid distributing Chronicles as mod and instead setup some sort of import where we can copy required data from installed game / from gog installer.

**Comment by Laserlicht** [comment]
Tarnum-Portraits: I think they have used the easy way. If you download the hacked files: There is also an folder `Tarnum` with PCX-files. These files replace some other Portraits.
They used resource names from other heroes as tarnum.

**Comment by Alucard648** [comment]
> * H3 campaigns don't have campaign "map" for chronicles (one where you select scenario to play). Looks like in chronicles executable / data files one of campaigns was changed to have required number of scenarios. (and all related graphical assets were replaced). So we need to adapt to this change.

What about implementing support for H2 styled campaigns with no overworld maps?

**Comment by dydzio0614** [comment]
> Tarnum-Portraits: I think they have used the easy way. If you download the hacked files: There is also an folder `Tarnum` with PCX-files. These files replace some other Portraits. They used resource names from other heroes as tarnum.

it is possible that dragon clash tarnum replaces gelu, wastelands tarnum replaces crag hack / kilgor (i dont remember specialty) etc...

Anyway this is not something that should be prioritized currently, unless some additional developer wants to work specifically on this.
