### ISSUE TITLE
Resource cost should be displayed 2-pixels lower in Blacksmith window.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#2265]
**Describe the bug**
Resource cost should be displayed 2-pixels lower in Blacksmith window.

**Game logs**
![image](https://github.com/vcmi/vcmi/assets/29593042/63b9b9ca-cfc4-4966-9369-11ad29734a50)

**Version**
 - OS: Windows
 - Version: [1.2.1]

**Comment by mikeiit** [comment]
I will take a look.
