### ISSUE TITLE
In campaigns, some artifacts should can be bring to next scenario.

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#2272]
In campaigns, some artifacts should can be bring to next scenario, but in vcmi the artifact will disappear in next scenario.
For example, in Armageddon's Blade campaigns, the 4th scenario Maker of Sorrow needs 3 artifacts which we get in 3rd scenario Seeking Armageddon, but we can't get victory because that 3 artifacts disappear in 4th scenario.

**Comment by IvanSavenko** [comment]
Duplicate of #2134 
Already fixed for 1.3

**Comment by lishaoxia1985** [comment]
@IvanSavenko Maybe there are other problems, for example: Some building in town can add hero's attack skill or power skill, but the effect also disappears in next scenario.
