### ISSUE TITLE
Refugee Town siege screen almost completely blank

### ISSUE THREAD

**Issue by cinnamon189** [vcmi/vcmi#2273]
Once so far, I was the defender of a besieged Refugee Town. At the start of the battle, the screen became almost completely blank; you could only see the menu bar (?) and lower half of the lower arrow tower. I had to resolve the combat by using the auto-combat feature.

VCMI 1.2.1 is the first version I'm playing, so I don't know whether it works correctly in earlier versions.

I'm on Windows 10 and used the English "Purple Hills" edition of HoMM III Complete to get VCMI running. I was using the mods for the German translation, WoG, High-res Menu, Resourceful AI and most of the "Town" mods.

**Comment by misiokles** [comment]
Confirm. It seems that all siege graphics have 800x556 px dimensions in png format and engine doesn't display them properly... (incorect sRGB profile - what does it means? What is proper profile?)

**Comment by Fabrice-TIERCELIN** [comment]
I also saw it for pavilion town but only few graphics were missing. It occurs on VCMI 1.2.1 but now, VCMI won't start with this mod.

**Comment by IvanSavenko** [comment]
Can somebody other than me check this on develop/daily builds?
Looks OK for me right now

**Comment by misiokles** [comment]
Looks ok, because it was fixed about week ago.
https://github.com/vcmi-mods/refugee-town/pull/5

**Comment by IvanSavenko** [comment]
Ah, thanks, wasn't aware of fix.
Will recheck older version to see what caused it.

**Comment by IvanSavenko** [comment]
Not fixable looks like. And definitely not vcmi bug.

Either libSDL or libpng can not load such files correctly. Not sure whether this is due to sRGB profile or due to using indexed palette (or possibly both), but in the end loaded image has no alpha channel information leading to such bug.

So the only solution for now is to avoid using sRGB profile that leads to such issues.

**Comment by Fabrice-TIERCELIN** [comment]
To avoid the bug, the images should not use indexed palette and should be converted into RVB.
