### ISSUE TITLE
On android, the buttons in battle screen do nothing when you touch them

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#2280]
This bug appears in the latest daily build (arm64):
 VCMI-branch-develop-7aef0f4.apk

**Comment by IvanSavenko** [comment]
Do you have "VCMI extras" mod up to date? 
What version do you have?
This issue should have been fixed in "3.4.0" update of VCMI extras

**Comment by lishaoxia1985** [comment]
@IvanSavenko thank you, it is solved. By the way, on android, we can't get the update message of mod.
