### ISSUE TITLE
It should be possible to dismiss the visiting hero and garrisoned hero

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#2287]
**Describe the bug**
Heroes can't be dismissed from town screen view.
There is no reason to forbid it, just makes hero management slower and more complex.

**To Reproduce**
1. Buy a hero in town
2. Try to dismiss the hero - dismiss button is blocked
3. Walk hero outside the town
4. Now dismiss button is enabled

**Expected behavior**
It should always be possibel to dismiss a hero in town. The only exception is if the hero is in the middle of exchange between allied heroes.

**Actual behavior**
Hero visiting town or garrisoned in it can't be dismissed.

**Did it work earlier?**
It is blocked in SoD, but available in HoTA

**Comment by IvanSavenko** [comment]
Similar case - dismissal of hero from kingdom overview screen is also blocked at the moment from what I remember
