### ISSUE TITLE
German Translation: Bombardiers in Forge2000 Town screen inconsistently referred to as "Kononier-Offiziere"

### ISSUE THREAD

**Issue by cinnamon189** [vcmi/vcmi#2309]
When clicking the Ugd. Stingers' Post in the Forge2000 town screen, it says that it serves for the recruitment of "Kanonier-Offizieren" (nominative: Kanonier-Offiziere). It should probably be EDIT: "Bombardieren" (nominative: Bombardiere) /EDIT instead, because that's how they are referred to in the units bar. 

EDIT2: Wait, something seems to be messed up here: At least in the description of Rengust's speciality, the basic unit is referred to as "Kanoniere" while the upgraded unit is referred to as "Kanonier-Offiziere" again. Could someone share a link to the Style Guide so I can look up which term is the correct one?

**Comment by cinnamon189** [comment]
Better to move this to the German Translation mod repository, right?

**Comment by IvanSavenko** [comment]
@cinnamon189 
Translations for mods are part of corresponding mod, so issue should probably be in Forge2000 mod repository.
