### ISSUE TITLE
When deactivating the German Translation mod, custom content remains German

### ISSUE THREAD

**Issue by cinnamon189** [vcmi/vcmi#2311]
Whenever I deactivate the German Translation mod and activate the English Translation mod instead, seemingly all the content from mods remains German. This applies at least to spells (in the spellbook) from mods and the Forge2000 town screen, though I'm almost sure I've seen it with other custom content as well. Switching to the German translation again does not cause any issues.

I used the Purple Hills edition of Heroes III Complete to get VCMI 1.2.1 running. Whether the issue turned up in earlier versions I don't know.

Repro Steps
1. Start the launcher, activate the German Translation mod and start playing.
2. End the game and return to the launcher.
3. Deactivate the German Translation mod and activate the English Translation mod.
4. Start another game and compare the text of original content with the content from mods.

**Comment by IvanSavenko** [comment]
Translations should be activated or deactivated via "VCMI Language" option in game settings.

VCMI will automatically pick corresponding mod (if downloaded and active), no need to activate/deactivate them manually.

**Comment by cinnamon189** [comment]
@IvanSavenko  Indeed, thank you :) Feel free to close.
