### ISSUE TITLE
[Courtyard] Reconstruction spell not affected by Air Magic skill

### ISSUE THREAD

**Issue by cinnamon189** [vcmi/vcmi#2312]
Even at Master level, the Reconstruction spell seems to remain as powerful as it is when the Hero has no Air Magic skill at all. Furthermore, the Reconstruction icon in the spellbook will always be surrounded by only one ornament, regardless of skill level. Also, if you set the spellbook to display Air spells only, the Reconstruction spell won't show up. You have to display all spells for Reconstruction to appear in the spellbook. Please fix.

**Comment by IvanSavenko** [comment]
Reconstruction? Translation issue? There is no such spell in H3.

List of spells with their English names here:
https://heroes.thelazy.net/index.php/List_of_spells

**Comment by cinnamon189** [comment]
I'm sorry, I should have added that I was playing with the WoG mod enabled, so I strongly assume this is a WoG-only spell...

**Comment by misiokles** [comment]
Reconstruction is spell from Courtyard mod.

**Comment by cinnamon189** [comment]
I'm sorry again, I didn't know Town mods can also include new spells. Thank you for the clarification.

**Comment by cinnamon189** [comment]
As far as I can tell, Trith is the maintainer, but is neither reachable through the mod overview in the launcher nor on the VCMI forum. If so, could someone tell me what to do about (supposed) issues with mods the maintainers of which are not reachable?

**Comment by misiokles** [comment]
Trith is unreachable, but rumors said he's working on new version of Courtyard. As you can see in other Courtyard's spells configs, some other spells are not connected to any magic schools. 
If you have good idea which spell should be connected to which schools, maybe someone prepare a patch for this.

**Comment by krs0** [comment]
Why not transfer this issue to: https://github.com/vcmi-mods/courtyard

**Comment by cinnamon189** [comment]
Yes, makes sense. I didn't know this mod has its own repository. Thank you for pointing out, both Github and HoMM III modding are still fairly new for me.

Could someone tell me whether there is a way to actually move a bug report to another repository? Or is it good old copy and paste?

**Comment by misiokles** [comment]
I use still good old copy/paste (I also learn github:)

**Comment by krs0** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository
Someone with rights could do it. The advantage over copy/paste is retaining comments.

**Comment by IvanSavenko** [comment]
No, not possible I think:
> Note: You can only transfer issues between repositories owned by the same user or organization account

**Comment by cinnamon189** [comment]
Alright, I copied the report over to the appropriate repository. Shall I now "Close as not planned"?

**Comment by misiokles** [comment]
Yes.
