### ISSUE TITLE
controlai command broken

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#2316]
Whether argument is specified to command does not matter - it is broken and interface gets mix of my current player color and one of AI player colors after typing command.

Pressing end turn button crashes game at this state.
Worked in VCMI 1.2

**Comment by nullkiller** [comment]
Worked more or less ok today without parameters

**Comment by nullkiller** [comment]
I think better to attach a map and exact steps to reproduce. Btw don't we have issue template?

**Comment by dydzio0614** [comment]
it seems to be more reliable than before, but UI color is messed up - it is also messed up for multiplayer spectator mode etc.

**Comment by nullkiller** [comment]
Does it affect hotsit? How about regular multiplayer?

**Comment by dydzio0614** [comment]
multiplayer is a mess - you an check one of my archived stream videos from HOMM3 category or download before they get autoremoved: https://www.twitch.tv/dydzio_linux/videos

**Comment by dydzio0614** [comment]
from half of videos onwards there are generally working games, but it is easy to get UI glitch for example by minimizing & restoring game in standard fullscreen mode during opponent turn etc.
