### ISSUE TITLE
Jebus Cross template shows "underground on" icon in lobby

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#2317]
**Describe the bug**
Jebus Cross template shows "underground on" icon in lobby, The icon cannot be disabled, though has no effect on actual map generation.

**To Reproduce**
- Go to RMG GUI
- Choose Jebus Cross from template list
- Observe "Underground" icon is highlighted
- Generate map. In game it has no underground, as defined in template

**Expected behavior**
When selecting Jebus, Underground icon should toggle off

**Comment by IvanSavenko** [comment]
Issue with vcmi-extras, will fix

**Comment by IvanSavenko** [comment]
Fixed in vcmi-extras
