### ISSUE TITLE
Display hero info outside of battlefield area

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#2319]
Now: 
![image](https://github.com/vcmi/vcmi/assets/2566990/486d68f2-1c66-43fe-a7a2-fea032036bcd)

How it should be preferably, if there's enough space:
![image](https://github.com/vcmi/vcmi/assets/2566990/a4f470df-6864-42d3-86d5-fc2f43c9d2e8)xt about the problem here.

**Comment by misiokles** [comment]
This is hd-mod solution. Maybe some other? More unique? Semi-transparent after pointing mouse/finger at hero?

**Comment by dydzio0614** [comment]
@misiokles I do not see reason to reinvent the wheel for something that is supposed to be primarily practical feature, unless somebody else comes with functionally better design

**Comment by Laserlicht** [comment]
@DjWarmonger can be closed...
