### ISSUE TITLE
Cheat vcmiformenos gives 10k gold instead of 100k

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#2354]
**Describe the bug**
According to wiki https://wiki.vcmi.eu/Cheat_codes cheat `vcmiformenos` shoudl give 100.000 gold, but gives only 10.000.

**Comment by IvanSavenko** [comment]
Will fix.
FYI - if you want more resources you can now use "vcmiformenos 1000" form.
It will give 1000 of all resources and 1000x100 gold
