### ISSUE TITLE
Fix issues with custom battlefields

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#2368]
**Describe the bug**
Not all the custom batlefields work correctly: https://forum.vcmi.eu/t/help-with-mods-questions/912/194

- [x] Make new battlefields not disable vanilla battlefields (unless specified explicitely)
- [ ] Terrain overlays (lucid pools, fiery fields, cursed ground etc.) do not use modded battlefields
- [x] Crash at `sand_shore` fight

**Comment by DjWarmonger** [comment]
New and old battlefields work fine to me, just need to have a number of fights and that's ok.

**Comment by IvanSavenko** [comment]
@DjWarmonger issue can be closed?

(Github does not automatically closes linked issues for PR's into beta branch)

**Comment by DjWarmonger** [comment]
I'd like Misiokles to re-check the current state of beta, as he said old battlefields no longer work while for me they do fine.

**Comment by misiokles** [comment]
I've said something else, that in that beta mod vallina battlefiels didn't show up. But it was before 'fixes' :p And yes, re-check it, even today.

**Comment by misiokles** [comment]
Issue can be closed!
