### ISSUE TITLE
Simultaneous turns support

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2370]
Description:
- Only present in online multiplayer
- Enabled by default, with option to disable it in UI (as part of drop-down box to select date to abort simturns)

While simultaneous turns are active:
- All human players start making turn simultaneously
- AI players are not affected by this option and will be making turns after human players, one after another
- All player timers start counting from turn start and until player ends turn, irregardless of other players
- After end of turn, and before all other human players end turn, player should be able to do all actions that don't modify gamestate, such as setting heroes' paths, opening town/hero window (and any other windows other than object visits)
- (advanced/optional) Allow preparing actions to be executed on next turn, potentially even displaying state to be expected on next turn, such as growth on new week and resources income

Simultaneous turns will end if:
- Certain date has been reached: configured in game startup settings. Primary designed towards tournaments where tournament organizers might want to provide commentary for all players. By default set to unlimited.
- If on start of a turn a hero of one player can reach owned object of non-allied player
- If on start of a turn two heroes of two hostile player can reach each other

Handling of edge cases:
- Pathfinding should account for all possible means of transportation, including presence of Town Portal and Dimension Door in heroes' spellbooks or scrolls, Town Gates map object, One-Way Monoliths, etc.
- Simturns ending check will be only performed on turn start.
- If players still manage to reach each other during simturns, interactions between players should be blocked till next turn, on which simturns will be disabled:
- - Player can not capture town (or any other map object) of another human player while simturns are active
- - Players can not attack heroes of another human players while simturns are active
- - Players can not interact with map object that is used by another player, e.g. you can't attack same wandering monsters

Things to consider:
- Handle a ways to extend reachability *during* turn one way or another
- - Capturing town allows TP into it / recruitment of new heroes
- - Prisons & Taverns can give hero with full movement points
- - DD/TP/Fly can be acquired during turn (new Mages Guild, Angel Wings, Scroll, Tome of Air) and immediately used
- Strong guards between zones - as long as players' army is too weak to defeat them, strong guards can be viewed as obstacle for pathfinding even if players can theoretically reach each other and don't abort simturns

**Comment by dydzio0614** [comment]
Did you think about influence of taverns (both towns and map objects) for breaking turns? Especially after we fix bug with minimum movement points depending on slowest unit - nobody forbids making level 1 unit with 20 speed in mods... or buying beaten heroes with boots of speed
I am not sure if area around tavern should always assume most pessimistic scenario for purpose of simultaneous turns, since it may result in notable amount of early breaks of simultaneous turns

**Comment by kodobi** [comment]
Another thing to consider are spells like DD, Fly. For example on Nostalgia template Starting Zones of two players are adjacent to each other (guerded with strong 45K guard) and the exact moment player gets acess to those spells/artifacts(Angel Wings, Tome of Air) attack is possible.

**Comment by IvanSavenko** [comment]
@dydzio0614 
Same question arises with prisons. Should we account for them or not? 

For now I will probably take easier route and won't account edge cases like this ones and will only block players' interaction and abort simturns on next day. But yeah, this is something that we might need to consider at some point

@kodobi 
How should this be handled in your opinion? 

Currently I am leaning to accounting for such possibility and abort simturns on *next* day. So once player has Angel Wings / Scroll of Fly / Tome of Air we should view all heroes of said player as being able to use Fly and abort simturns if players can reach one another.

**Comment by kodobi** [comment]
I was not thinking about any specific solution to that, just giving food for thought. Hovever listing every cornercase is good, You  can decide later how to approach them.

**Comment by dydzio0614** [comment]
makes sense, though "next day" will probably create a lot of situation when somebody with expert air magic gets DD access and uses it 4x in a row, moving many tiles further than movement points allow

**Comment by kodobi** [comment]
If i recall correctly Tournament Rules applied in HoTA allows max 2x DD on maps > L with an expert Air Magic and 1x DD on <=L even with expert Air Magic

**Comment by dydzio0614** [comment]
yep, but non tournament rules mode should be supported as well... + situations specific to VCMI related to mods

**Comment by kodobi** [comment]
One step at the time :)

**Comment by Jon25250** [comment]
> Description:
> 
> * Only present in online multiplayer
> * Enabled by default, with option to disable it in UI (as part of drop-down box to select date to abort simturns)
> 
> While simultaneous turns are active:
> 
> * All human players start making turn simultaneously
> * AI players are not affected by this option and will be making turns after human players, one after another
> * All player timers start counting from turn start and until player ends turn, irregardless of other players
> * After end of turn, and before all other human players end turn, player should be able to do all actions that don't modify gamestate, such as setting heroes' paths, opening town/hero window (and any other windows other than object visits)
> * (advanced/optional) Allow preparing actions to be executed on next turn, potentially even displaying state to be expected on next turn, such as growth on new week and resources income
> 
> Simultaneous turns will end if:
> 
> * Certain date has been reached: configured in game startup settings. Primary designed towards tournaments where tournament organizers might want to provide commentary for all players. By default set to unlimited.
> * If on start of a turn a hero of one player can reach owned object of non-allied player
> * If on start of a turn two heroes of two hostile player can reach each other
> 
> Handling of edge cases:
> 
> * Pathfinding should account for all possible means of transportation, including presence of Town Portal and Dimension Door in heroes' spellbooks or scrolls, Town Gates map object, One-Way Monoliths, etc.
> * Simturns ending check will be only performed on turn start.
> * If players still manage to reach each other during simturns, interactions between players should be blocked till next turn, on which simturns will be disabled:
> * * Player can not capture town (or any other map object) of another human player while simturns are active
> * * Players can not attack heroes of another human players while simturns are active
> * * Players can not interact with map object that is used by another player, e.g. you can't attack same wandering monsters
> 
> Things to consider:
> 
> * Handle a ways to extend reachability _during_ turn one way or another
> * * Capturing town allows TP into it / recruitment of new heroes
> * * Prisons & Taverns can give hero with full movement points
> * * DD/TP/Fly can be acquired during turn (new Mages Guild, Angel Wings, Scroll, Tome of Air) and immediately used
> * Strong guards between zones - as long as players' army is too weak to defeat them, strong guards can be viewed as obstacle for pathfinding even if players can theoretically reach each other and don't abort simturns

Hello, is there any chance simultaneous turns will be ever added as a mod for the vcmi launcher or wog in general?!

**Comment by IvanSavenko** [comment]
Closing, implemented in 1.4
