### ISSUE TITLE
Annoying underscore in the creature exchange popup

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [vcmi/vcmi#2373]
**Describe the bug**
On the popup at the right of the amount of the right, an annoying underscore appears.

**To Reproduce**
1. Get two heroes
2. Make one hero go to the other hero to exchange creatures; you get [this](https://i.imgur.com/ZqmiFQN.png)
4. Select creatures
5. Click on "Split army"; a popup appears
On the popup at the right of the amount of the right, an annoying underscore appears.

**Expected behavior**
On the popup at the right of the amount of the right, only the amount appears.

**Actual behavior**
On the popup at the right of the amount of the right, an annoying underscore appears.

**Did it work earlier?**
I don't know

**Screenshots**
The print screen doesn't work for me on VCMI

**Version**
 - OS: Windows 10
 - Version: Daily build 2023-07-20

**Comment by kodobi** [comment]
I think this is not a bug but a feature. If You have a huge stack of creature and You want to split them acurately You do not have to use slider, just type amount You want to split. Underscore suggests that value is editable - just like in Word editor for example.

**Comment by IvanSavenko** [comment]
Yep. Not a bug, but an editing indicator. Similar to one you get in game console on pressing Tab key

**Comment by Fabrice-TIERCELIN** [comment]
OK, closed
