### ISSUE TITLE
Missing comma in gameConfig.json

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#2377]
**Describe the bug**
At launch, console warns about missing coma in gameConfig.json file.

**Game logs**
![image](https://github.com/vcmi/vcmi/assets/29593042/0a32540d-df48-4ebb-b613-804610b9ab37)
![image](https://github.com/vcmi/vcmi/assets/29593042/9417a738-6662-484b-b249-1c0bee3b78f9)

**To Reproduce**
1. Launche game
2. Study console warnings

**Expected behavior**
There's should be comma after `"accumulateWhenOwned" : false`

**Actual behavior**
Missing coma

**Version**
 - OS: Windows
 - Version: [ pre VCMI-1.3 daily builds]

**Comment by DjWarmonger** [comment]
Looks (and works) OK on my side.

**Comment by IvanSavenko** [comment]
Was already fixed
