### ISSUE TITLE
Window mode bug

### ISSUE THREAD

**Issue by SoundSSGood** [vcmi/vcmi#2380]
**Describe the bug**
The image becomes small and does not fit the window size.
I don't know if the maximize window button should be enabled. But it's enabled.

**To Reproduce**
EDITED
1. Start game in windowed mode
2. Click maximize window button
3. Click minimize button
4. Put back

**Expected behavior**
The image size should fit the window size

**Screenshots**
![window_bug](https://github.com/vcmi/vcmi/assets/87084363/db7bdc75-b0c6-4e41-996d-a964b5d58a77)

**Version**
Kubuntu 22.04
develop

**Comment by IvanSavenko** [comment]
Unable to confirm. For me maximizing window & ending turn works as expected: window is resized, game screen is upscaled, game area is not changes. Potentially with black borders on the sides, depending on game/screen resolution.

**Comment by SoundSSGood** [comment]
> Unable to confirm

Yes you are right. Just checked. It is also needed to minimize the window and put it back.

**Comment by dydzio0614** [comment]
I confirm the bug, should we disallow resizing window to arbitrary size? :p

**Comment by IvanSavenko** [comment]
Resizing (mostly) works other than this bug, so see no reason to block it

**Comment by SoundSSGood** [comment]
no longer reproducible
