### ISSUE TITLE
The hero on land can't move after battle when you attack the hero on a boat sometime.

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#2381]
Sometimes the hero on land can't move after battle when you attack the hero on a bost.
THE REASON:Maybe when you win the battle, the place where your hero is will change to water, but your hero isn't on a boat. That leads to that your hero can't move.
My advice: when you win the battle, don't change the place where your hero is.
ANOTHER REASON: When you are on the beach and attack the enemy on the boat, the battlefield is boat. When you win the battle, PC think you are on the boat, so the terrain where you are is water, but in fact you have no boat. That leads to that you can't move.
---
Another bug: when you attack enemy which is visiting some buildings, you will be in the place where the enemy is after battle. Maybe this bug is related to the bug above.

**Comment by IvanSavenko** [comment]
Might be related to that "hero can move onto another hero" bug we got recently. Investigating...

**Comment by lishaoxia1985** [comment]
@IvanSavenko If you touch Creature's Skill button, it will switch to  Ø, I think it should be different with the button when Creature doesn't have a skill.
