### ISSUE TITLE
The whole map is revealed to the human player when playing in one team with computer player (Nullkiller AI)

### ISSUE THREAD

**Issue by pppbb** [vcmi/vcmi#2389]
As i wrote player(human) in one team with computer player is seeing the whole map after computer's turn either in single player and multiplayer games. Observed only with Nullkiller AI.

1. Start single scenario or multiplayer games choosing Nullkiller AI as Adventure map AI.
2. Place yourself in a team with computer 
3. Run random map.
4. Wait until computer makes his turn.
The whole map should be visible to the team.

**Did it work earlier?**
I don't know.

**Version**
 - OS: Arch Linux, Windows, Android 
 - Version: 1.2 -1.3

**Comment by IvanSavenko** [comment]
Known issue.
Unfortunately Nullkiller AI currently requires map reveal to properly function.

In 1.3 we've added option to set AI of allied players to a different AI, which by default set to VCAI

**Comment by paddotk** [comment]
@IvanSavenko Is that a temporary solution? As far as I know, the VCAI doesn't work well (mostly idle heroes), so it's not an ideal permanent solution.

**Comment by IvanSavenko** [comment]
Depends on time & priorities of our AI developer.

From what he told me, proper support for exploration of NKAI is not trivial and relatively low on priority list.
