### ISSUE TITLE
All of the creatures may appear in the Refugee Camp

### ISSUE THREAD

**Issue by kodobi** [vcmi/vcmi#2402]
**Describe the bug**
All of the creatures may appear in the Refugee Camp while according to the https://heroes.thelazy.net//index.php/Refugee_Camp 

> _It is not possible to find Sharpshooter, Enchanter, Azure Dragon, Crystal Dragon, Rust Dragon or Faerie Dragon in a Refugee Camp._

**Game logs**
N/a

**To Reproduce**
1. Visit as many Refugee Camps until forbiden creature appears for hire

**Expected behavior**
It is not possible to find Sharpshooter, Enchanter, Azure Dragon, Crystal Dragon, Rust Dragon or Faerie Dragon in a Refugee Camp.

**Actual behavior**
It is possible to find Sharpshooter, Enchanter, Azure Dragon, Crystal Dragon, Rust Dragon or Faerie Dragon in a Refugee Camp.

**Did it work earlier?**
I do not know, probably not as Ivan mentioned on Discord: 

> Might be worth reporting it on Github so it won't be lost, but yeah - missing feature. Right now all creatures may appear in there

**Screenshots**
![Screenshot_2023-07-24-15-53-17-25_41d7730817d4f0f666b5cd2eca25c7fd](https://github.com/vcmi/vcmi/assets/37045566/200989ee-381e-44be-b219-e41821e78226)

**Version**
 - OS: Android
 - Version: 1.2.1

**Additional context**
N/a

**Comment by rilian-la-te** [comment]
@IvanSavenko is this bug or feature? Should we have creatures than cannot appear in Refugee Camp?

**Comment by IvanSavenko** [comment]
Why not? This is how H3 works anyway.

Although should probably be a property of refugee camp (list of banned creatures), and not property of a creature
