### ISSUE TITLE
Replay opponent turn

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#2410]
**Describe your proposal**
Another low prio OH3 thing: The "Replay Opponent Turn" (Sub menu on adventure map, accessible with adventure options button) is without function.

![grafik](https://github.com/vcmi/vcmi/assets/13953785/d8167651-b7c5-4353-9934-cd2e108853c5)

**Comment by IvanSavenko** [comment]
Duplicate of #818

**Comment by Laserlicht** [comment]
Sorry, I missed it :)
