### ISSUE TITLE
The new added button of creatures is not very good when you move the creatures to another cell in the list.

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#2415]
![Screenshot_20230726_004606_is.xyz.vcmi.daily.jpg](https://github.com/vcmi/vcmi/assets/49801619/9980b559-0e36-44db-8112-eb1469f70315)

When you want to move the creatures to another cell in the list, it's a hard work. In early branch we only need to touch the creatures and the target cell.
Another problem: we should drag the icon, touching the icon directly may be a better way.
Maybe we can do this: 
1. When the creature info panel shows, the button appears.
2. Add a setting to close these buttons.

**Comment by nullkiller** [comment]
What should be the 6th button here? I thought it will be exactly a button to move which just closes these buttons and allow to tap any other cell.

**Comment by IvanSavenko** [comment]
@nullkiller 6th button is present, but only when two armies are present (hero exchange & town screen with visiting hero). It moves creature to a different army.

@lishaoxia1985 
Are you using latest 'beta' build?
Checked latest build and everything works as intended:
- to move creature, touch creature and then touch slot you want to move it to.
- menu will only show up on swiping screen

Have not noticed any inconveniences or unintended activation of new menu on my phone.
