### ISSUE TITLE
AI doesn't build high-level mage guild

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#2423]
**Describe the bug**

> Nullkiller AI never build a mage guild and their heroes only have at most level 3 spells. They can hardly use level 5 spells.
> 
> It is a suggstion to improve it, just change the sequence of buildings:
> 
> dwellings--castle--capitol--mage guild--other buildings.

**Expected behavior**
AI should eventually build all availabe buildings.

**Version**
Copy of a ticket from 5th May: https://github.com/vcmi/vcmi/issues/2113 , might be outdated

**Comment by nullkiller** [comment]
This one and horde1/2 support will be included in the next AI patch.
