### ISSUE TITLE
Unholy Alliance campaign - problem with winnning scenario.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#2429]
**Describe the bug**
Bug reported at FB page. Campaign Unholy Aliance, map 11 - Union. Player defeated Sandro but after pressing Next turn, nothing happened and guy wasn't unable to pass to final scenario.

**Game logs**
N/A

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/29593042/ccb1a99e-5619-4364-81ce-4f71fc83f600)

**Version**
 - OS: ??
 - Version: Unknown, guy pasted only this screen.

**Comment by IvanSavenko** [comment]
Most likely fixed in 1.3. There were several issue with moving to next scenario. Can't remember exactly this one, but likely to be one of already fixed issues.

**Comment by misiokles** [comment]
Using cheats I got to this map. Yes, in beta builds there's no this bug and map can be finished.
I observed only one issue.
![image](https://github.com/vcmi/vcmi/assets/29593042/93bd895e-7994-4298-ad8e-542ce2a94dc5)
