### ISSUE TITLE
[Touchscreen] Tolerance for touch

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#2439]
**Describe your proposal**
VCMI should have some tolerance with buttons. Since some controls on smartphones are quite small.

Idea would be that if the user does not hit any element (red), that then the closest button would be pressed (green). But only to a certain tolerance of distance (in pixels).

![grafik](https://github.com/vcmi/vcmi/assets/13953785/e7df232c-5beb-4c5b-bad9-9d3cdcf18ee1)

**Comment by IvanSavenko** [comment]
Good idea. Somehow haven't though about it. And might be actually quite easy to implement

**Comment by lishaoxia1985** [comment]
It can be hardly implemented because that you should consider of all the buttons with the different shape. I don't think it can come true.
