### ISSUE TITLE
Some problem about  the cursor when you attack the enemy's creature in battlefield

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#2440]
The problem is that:
https://github.com/vcmi/vcmi/assets/49801619/522a3d0a-7394-440d-ad60-e023e6c6ac22

When you click the enemy's creature and drag the cursor without releasing, you will find:
1. If the dragging position is  in the moving range of the enemy's creature, a sword shaped cursor will appear on the enemy's creature, and you can change the direction of the cursor by changing the dragging position. By this way you can decide our creature attacking position becuse sometimes your finger will cover the cursor.
2. If the dragging position is out of the moving range of the enemy's creature, the sword shaped cursor will disappear.

Point 2 will produce a problem:
the moving range of the enemy's creature is too small （e.g. 2, the zombie be slowed） to decide our creature attacking position.
--
My advice is only using the way of Point 1:
If the dragging position is out of the moving range of the enemy's creature, the sword shaped cursor will always show.

**Comment by lishaoxia1985** [comment]
@IvanSavenko If the dragging position is out of the moving range of the enemy's creature, the sword shaped cursor will disappear. Then if you release the cusor your attacking will be cancel. We can use this way to cancel the command.
If you accept my advice, we should also consider that how to cancel the command. I have no idea.

**Comment by IvanSavenko** [comment]
Not a bug I believe?

Attack cancelling is not based on enemy movement range. 
Attack canceling range is fixed (around 200-300 pixels) and does not depends on anything

**Comment by lishaoxia1985** [comment]
@IvanSavenko if you think it has been fixed, you can close this issue.
