### ISSUE TITLE
Colliding heroes

### ISSUE THREAD

**Issue by petekos-math** [vcmi/vcmi#2442]
**Describe the bug**
Two allied heroes collide when trading with each other.

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Start a map
2. Hire at least two heroes
3. Make them trade with each other
4. After you close the trading window, the heroes occupy the same tile.

**Expected behavior**
Two heroes should stay on the same tiles.

**Actual behavior**
As seen in the screenshot, 
![vcmicollide](https://github.com/vcmi/vcmi/assets/65818946/c9f1849b-c466-4a7d-ae3a-b226e6022cbe)
the heroes are standing on the same tile. 

**Did it work earlier?**
Not sure, but I think heroes don't collide in the current release version.

**Version**
 - OS: Arch Linux x86_64 Linux 6.4.6-arch1-1
 - Version: VCMI 1.3.0.c3584f7f91b5122dcc6ab57d83a27c99f519faec
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12208335/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12208336/VCMI_Server_log.txt)

**Comment by IvanSavenko** [comment]
Already fixed in latest develop/beta
