### ISSUE TITLE
Game crashes in recruiting hero from water tavern 

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#2451]
**Describe the bug**
I tried several times to recruit hero from water tavern, it crashes. But it works in visiting a water prison.

**Did it work earlier?**
In the lastest version it doesn't work. 

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/127420617/a8399138-dc0f-47de-94d8-013d26c52d0f)
![image](https://github.com/vcmi/vcmi/assets/127420617/9f7bf2c1-ae9e-45fe-8cdb-e8de826ba432)

**Version**
 - OS: Windows
 - Version: 1.3

**Additional context**

**Comment by DjWarmonger** [comment]
Any specific mods beyond HoTA?

**Comment by by003** [comment]
It is a random map. I deleted all mod except hota.

**Comment by nullkiller** [comment]
Probably can be tested with our vmap editor easely. Maps are generally better then saves as we tend to break compatibility often
