### ISSUE TITLE
Add creature portrait for r-click popup on adventure map

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#2459]
**Describe your proposal**
Add creature portrait to this pop-up to make it a little bit clearer.
![image](https://github.com/vcmi/vcmi/assets/2566990/406dc822-7b3c-4224-b732-9f54b5bc96e7)

Right now the popup completely covers the creature in question, which can be confusing with many creatures added via mods.

**Comment by krs0** [comment]
Since vcmi has tons of mods with new or modified creatures.... in addition to this, showing full creature info would also help.
Alt + right click or something like that.

**Comment by Laserlicht** [comment]
> Since vcmi has tons of mods with new or modified creatures.... in addition to this, showing full creature info would also help. Alt + right click or something like that.

I would not like an additional button to press. That would lock out mobile players.

More information wouldn't hurt, would it? Otherwise a "Pro" mode, where more information is displayed in various fields?

**Comment by IvanSavenko** [comment]
IMO there is no need for information overload.

Might make sense to display some basic info about creatures in addition to portrait, e.g. "Master Gremlin, Level 1 of Tower faction", to give player basic idea of unit strength, but detailed stats are not exactly needed IMO.

**Comment by krs0** [comment]
Well... one of the most important basic info I would ike to know is speed.
For abilities... consider you encounter a completely new level 1 creature with Luna.... you would very much like to know if itbis immune to fire :D

**Comment by krs0** [comment]
Closed by mistake :(
