### ISSUE TITLE
Warnings from HotA main menu buttons

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2472]
**Describe the bug**
With HotA enabled whenever hovering over a main menu button these warnings appear
`libpng warning: iCCP: known incorrect sRGB profile`

**To Reproduce**
1. Enable HotA mod

**Version**
 - OS: [e.g. Windows, 
 - Version: [daily

**Comment by IvanSavenko** [comment]
Fixed in https://github.com/vcmi-mods/horn-of-the-abyss/pull/40
