### ISSUE TITLE
When you are playing with VCAI in union game has freeze sometimes

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#2475]
**Describe the bug**
A bug appears when you press end turn.

**To Reproduce**
Press end turn and blue AI will stuck

**Version**
 - OS: [Windows]
 - Version: [1.3]

**Additional context**
[Autosave_4.zip](https://github.com/vcmi/vcmi/files/12266147/Autosave_4.zip)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12266149/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12266150/VCMI_Server_log.txt)

**Comment by nullkiller** [comment]
Likely it will be workarounded in #2484

**Comment by dydzio0614** [comment]
needs re-check, i won't do it right now

**Comment by Povelitelh3** [comment]
Looks like fixed
