### ISSUE TITLE
sometimes an unreproducible crash occurs

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#2476]
**Describe the bug**
Sometimes an unreproducible crash occurs while the AI is running. The reasons are not clear to me.

**Version**
 - OS: [Windows 10]
 - Version: [1.3 release]
[save&logs.zip](https://github.com/vcmi/vcmi/files/12266267/save.logs.zip)

**Comment by IvanSavenko** [comment]
Judging from description - sounds like #2490 
Might be fixed in 1.3.1 / beta.

Closing, please reopen if this happens again.
