### ISSUE TITLE
Horn of the Abyss mod causes UI slowness

### ISSUE THREAD

**Issue by tmysik** [vcmi/vcmi#2478]
Horn of the Abyss mod causes UI slowness, this is clearly visible in the hero movement in a map.

Disabling its "Graphical fixes" (sub)mod resolved this issue.

**Version**
 - OS: Android
 - Version: 1.3.0

**Comment by tmysik** [comment]
Hmm, today my VCMI Android version was updated and it seems that this issue is resolved (I enabled this submod and the game feels OK; even without it, the game seems to be faster). Thanks!

**Comment by IvanSavenko** [comment]
Closing, fixed in beta branch & in Android hotfix

**Comment by tmysik** [comment]
@IvanSavenko Thanks a lot, amazing!
