### ISSUE TITLE
Right click stopped working in 1.3

### ISSUE THREAD

**Issue by jakobsn** [vcmi/vcmi#2483]
**Describe the bug**

I cannot right click anymore after version 1.3. I used to apply to fingers to the screen (like a Mac touch pad), and it doesnt work anymore.

No error message.

**To Reproduce**
1. Start game.
2. Right click a tree, a pond, or whatever.

**Expected behavior**

Expect to see info on creatures, items, objects, heroes.

**Actual behavior**

Nothing happens. If I lift my fingers it will be like a left click.

**Did it work earlier?**

It worked yesterday. Before 1.3

**Version**
 - Android 11 Galaxy S10+ edge
 - VCMI 1.3

**Comment by IvanSavenko** [comment]
HI. In 1.3 right-click is triggered by long touch, in line with other apps on mobile systems.

**Comment by jakobsn** [comment]
Ah awesome thanks. I was suspecting I was doing something wrong.
