### ISSUE TITLE
Maps within subfolders

### ISSUE THREAD

**Issue by heroesiiifan** [vcmi/vcmi#2489]
**Describe your proposal**
It should be possible to use folders for maps (and custom campaigns). Like the HD mod.

**Additional context**
With this we can avoid a mix up between maps from different map packs from mods (example: [Mighty Heroes III](https://github.com/vcmi-mods/mighty-heroes-iii/tree/vcmi-1.3)). Also the user can sort his maps in folders.

Maybe also for save games (autosave; see HD mod).

**Comment by krs0** [comment]
Yup! I have mines in HotA sorted based on categories, and it is a lot easier to manage

**Comment by Laserlicht** [comment]
I also think it's relatively important.

Have tried a little bit around. But my C++ knowledge is not good enough to implement this cleanly. In principle it seems that not even that much has to be changed.

We have to enable VCMI to read from subdirectories and to create folders on save: https://github.com/Laserlicht/vcmi/commit/a9e895c08f19f12a912ad6176c7f486e57aa0ce9

Besides that, it's theoretically just a GUI change. But there I don't really know how to implement it in the cleanest way... https://github.com/Laserlicht/vcmi/commit/e5627b4bb7d144a1e0e5e7a97272b0dc1e9b5676 (hacky not complete test)

If someone would like to take this up: with pleasure
