### ISSUE TITLE
Haptic feedback crash

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2493]
**Describe the bug**
Looks like haptic feedback causes crash on some devices and/or some Android versions.

So far only happens on one system:
- Device: "samsung dreamlte"
- Android 9 (SDK 28)

**Version**
 - OS: Android
 - Version: vcmi 1.3

**Error message**
`No pending exception expected: java.lang.NoSuchMethodError: No static method createPredefined(I)Landroid/os/VibrationEffect; in class Landroid/os/VibrationEffect; or its super classes (declaration of 'android.os.VibrationEffect' appears in /system/framework/framework.jar!classes2.dex)`

**backtrace**
(abort+124)
(art::Runtime::Abort(char const*)+1320)
(android::base::LogMessage::~LogMessage()+724)
(art::Thread::AssertNoPendingException() const+1144)
(art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>)+64)
(art::JNI::FindClass(_JNIEnv*, char const*)+1272)
(LIB_CLIENT::CAndroidVMHelper::callStaticVoidMethod()+72)
libvcmiclient.so (InputSourceTouch::hapticFeedback()+314)
libvcmiclient.so (InputSourceTouch::handleUpdate()+237)
libvcmiclient.so (InputHandler::processEvents()+89)
libvcmiclient.so (CMainMenu::update()+339)
libvcmiclient.so (CGuiHandler::renderFrame()+123)

**Comment by Laserlicht** [comment]
Interesting...

This Line is only for SDK-Version >= 26: https://github.com/vcmi/vcmi/blob/ad8695ac91a71193c7cd423cdc6d735c0803daf8/android/vcmi-app/src/main/java/eu/vcmi/vcmi/NativeMethods.java#L150C110-L150C125

But I think I found the problem. According to Android docu:
- VibrationEffect is SDK 26
but:
- createPredefined is SDK 29

So maybe we only have to set it to 29. But I don't have such old device to test...

**Comment by IvanSavenko** [comment]
Thanks for info.
Looks like `vibrate(30);` version is deprecated in SDK 26, but still available - don't see any removals. 
So I'll switch that block to SDK 29

**Comment by IvanSavenko** [comment]
Closing, fixed in hotfix
