### ISSUE TITLE
RMG: incorrect placement of guards

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2500]
**Describe the bug**
In some cases guards for map objects are incorrectly placed.

**Screenshots**
![image-4](https://github.com/vcmi/vcmi/assets/15194321/42215d7f-55dd-4c76-a85b-57bdfecfa8ac)

**Version**
 - OS: [e.g.
 - Version: 1.3

**Comment by DjWarmonger** [comment]
I'd need some more reports to see a pattern. Is HoTA mod enabled? Does it happen only for OH3 units maybe?
