### ISSUE TITLE
Hero skills have different order in campaigns

### ISSUE THREAD

**Issue by jcialkowski** [vcmi/vcmi#2507]
**Describe the bug**
A relatively minor bug, but still a bug :) the hero has a different skill order in the second map of a campaign than in the first one.

**To Reproduce**
1. Finish a campaign's map

**Expected behavior**
Skills should have the same order regardless map

**Actual behavior**
Skills have a different order

**Did it work earlier?**
don't think so

**Screenshots**
first map
![Screenshot_20230807_171654](https://github.com/vcmi/vcmi/assets/33762148/8beba91f-e367-437f-a4c5-c51c598c5366)

second map
![Screenshot_20230807_171734](https://github.com/vcmi/vcmi/assets/33762148/2c3d6024-8572-4c5c-b985-961d901728cc)

**Version**
 - OS: Linux
 - Version: 1.3

**Comment by IvanSavenko** [comment]
Already fixed
