### ISSUE TITLE
Double event message

### ISSUE THREAD

**Issue by jcialkowski** [vcmi/vcmi#2514]
**Describe the bug**
An event activation shows a message twice. The first one includes the message with a reward icon, while the second one only displays the message.

**To Reproduce**
1. Step onto event with a reward

**Expected behavior**
only on message should be displayed

**Actual behavior**
the message is shown twice

**Did it work earlier?**
I think so

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/33762148/577cb002-b486-4223-b564-dca583895958)
![image](https://github.com/vcmi/vcmi/assets/33762148/8012dd2f-aad2-4b84-8549-e2080a91cee5)

**Version**
 - OS: Linux
 - Version: 1.3

**Comment by Nordsoft91** [comment]
@jcialkowski , can you please attach map?

**Comment by jcialkowski** [comment]
sure, this is the map. just move to the right (there are a couple of events placed)
[test.zip](https://github.com/vcmi/vcmi/files/12507588/test.zip)
