### ISSUE TITLE
Incorrect screen aspect ratio on iPad Mini 5

### ISSUE THREAD

**Issue by oldfoz** [vcmi/vcmi#2519]
First of all, thank you for the opportunity to play this awesome game on iOS devices.
This is something i've been waiting for a long time.

**Bug description**
With the new v1.3.0 I catch an issue with incorrect aspect ratio of game screen on my device. 
It has blank unfilled black spaces on the left and right sides, around 5mm each I guess.
With top and bottom borders all is ok.  
And I have no option to change it because now we have only scaling parameter in settings. 
With previous v1.2.1 no such problems raised, aspect ratio was perfect with 800x600 and 1024x768 resolutions.

**Did it work earlier?**
This issue not happened with v1.2.1

**Version**
 - OS: iOS, iPad Mini 5
 - Version: v1.3.0

**Comment by kambala-decapitator** [comment]
indeed, same on iPad Air 2

**Comment by IvanSavenko** [comment]
Semi-intended, because some Apple devices have camera cutout that is excluded from available area by SDL.

Right now the only way to change this is to open file Documents/vcmi/settings.json and add
```
"video" : {
    "reservedWidth" : 0
}
```
(if video section does not exists then add it, othervice - add "reservedWidth" to existing section)

**Comment by oldfoz** [comment]
@IvanSavenko, thanks for the advise with settings.json,
works on my machine
