### ISSUE TITLE
Enemy Hero picking up empty Pandora's Boxes

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2533]
**Describe the bug**
In OH enemy hero will never pick up empty Pandora's Boxes. It can in vcmi, as shown below

**To Reproduce**
1.Place Pandora's Box on a map close to an enemy hero
2.Watch him pickinng it up

**Expected behavior**
AI doesn't pick up Pandora's Box even if close the only way out, even if Angelic Alliance is behind it, even when AI has no towns

**Actual behavior**
It will pick it up

**Version**
 - Windows
 - Version: 1.3, probably
![Sakrby](https://github.com/vcmi/vcmi/assets/141812373/5719210e-f0a8-4221-9ffa-25ca97961fb3)

**Comment by DjWarmonger** [comment]
AI doesn't know what's inside Pandora Box.

Besides, I don't quite see why AI should remain blocked ¯\_(ツ)_/¯ If that's mapmaker's design, there are other ways to achieve this.

**Comment by HarkUhm** [comment]
Well, it does know. It won't pick up Pandora's box that has too strong guards. It will also won't pick up Pandora's Box that has only text, but no guards and no rewards.

**Comment by dydzio0614** [comment]
personally I would not implement it at all...

**Comment by nullkiller** [comment]
If you need AI to not move there is patrolling which we support an respect. Another stright-forward option is to use quest guard or border guard
