### ISSUE TITLE
Creatures deals less damage to a monsters standing in the gate during sieges

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2538]
**Describe the bug**
Creatures deals less damage to monsters standing in the gate during sieges:
![imaasdfsafge](https://github.com/vcmi/vcmi/assets/141812373/ed491389-3351-465a-b7a5-0cab77e8bfb5)
Everywhere else:
![imagsafe](https://github.com/vcmi/vcmi/assets/141812373/b5d60ab3-5cfb-48b7-a731-9d03cbfd41da)
Bug not present in OH with HDMod.

**Version**
 - OS: Windows 10
 - Version: [VCMI version]

**Comment by IvanSavenko** [comment]
- Can you confirm that actual dealt damage matches tooltip?
- Which amount is correct?

**Comment by HarkUhm** [comment]
I recall, now I investigated further and in vanilla SoD without HDmod it works the same as in vcmi, in HoTA too. Only in SoD + HD mod the number of damage dealt is the same everywhere, Baratorch for some reason changed it

**Comment by HarkUhm** [comment]
I replayed one more time, the same save, but this time in SoD without HDmod dealt damage was the same for the whole battlefield. I have no idea when this bug occurs.

**Comment by HarkUhm** [comment]
OK, I guess that I am just stupid, because I was clicking defence when Archangels had morale and didn't notice. Ecchhh, sorry

**Comment by IvanSavenko** [comment]
Closing then
