### ISSUE TITLE
After opening "save game" menu, one of the saves is lighted, but not picked in a textbox

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2540]
**Describe your proposal**
In OH the latest save that was used is lighted and a player simply  has to click the "save" button. In vcmi the save is lighted, but it's name doesn't appear in a textbox at the bottom and save have to be clicked, otherwise clicking "save" will does nothing:

![vcm](https://github.com/vcmi/vcmi/assets/141812373/e6f4b9d1-2ffa-4a9f-9f22-303f8f38845f)

**Comment by Laserlicht** [comment]
@IvanSavenko can be closed
