### ISSUE TITLE
RMG: Sometimes a zone is not filled with all objects

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2542]
**Describe the bug**
Sometimes a zone is filled only with towns, mines, and then nothing.

**Game logs**
[server_log.txt](https://github.com/vcmi/vcmi/files/12304611/server_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12304612/VCMI_Server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12304613/VCMI_Client_log.txt)

**To Reproduce**
1 RMG jebus Cross (only one i've tried)
2 start game and look at zones.

HotA mod installed if it matters.

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/15194321/8e705961-3edb-4df4-bd7e-965b2c10b7ec)

**Version**
 - OS: [e.g. Windows,
 - Version: develop

**Comment by DjWarmonger** [comment]
It may happen in any case that RMG encounters exception during object placement. Then filling the zone is interrupted. But this should not happen on its own.

**Comment by DjWarmonger** [comment]
Fail in TreasurePlacer:
`ERROR global - Modificator TreasurePlacer, exception: Tile (108 21 0) is outside the map`
