### ISSUE TITLE
Crashes at launch

### ISSUE THREAD

**Issue by Belweder** [vcmi/vcmi#2548]
**Describe the bug**
Crashes at lunch when the starting video with 3do logo is playing.

**Did it work earlier?**
Started crashing after MacOS was updated to Ventura 13.5, worked fine before the update. 

**Version**
 - OS: macOS Intel, Ventura 13.5
 - MacBook Pro 2017, i7, radeon pro 560 
 - Version: tried both VCMI version 1.2.1 & 1.3.0

[VCMI.txt](https://github.com/vcmi/vcmi/files/12313579/VCMI.txt)

**Comment by IvanSavenko** [comment]
Hi. Do you have any mods active? If yes - can you try disabling them and check whether this issue will persist?

Also - can you check whether latest beta from here works or not?
https://download.vcmi.eu/branch/beta/macOS/intel/

**Comment by Belweder** [comment]
Hi! I've installed the latest beta, it launched fine, but crashed then I quit the game. I relaunched it and it started crashing the same way as before.

I'll try to disable some mods and comment later. 

Thank you!

**Comment by Belweder** [comment]
settings.json is in data folder/config/schemas/settings.json

				"reconnect" : {
					"type" : "boolean",
					"default" : false
				},
				"uuid" : {
					"type" : "string",
					"default" : ""

There are no such file at  data folder/config/settings.json

Didn't have time to try to disable plugins, sorry. I'll comment about it later.

**Comment by Belweder** [comment]
I've turned off all the plugins and updated the wake of gods and horn of abyss. Starts fine. I guess the issue was with one of the plugins. Thank you!
