### ISSUE TITLE
Crash on main menu video playback

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2553]
**Describe the bug**
According to our crash reporter on Android, playing video file in main menu in some cases leads to a crash. Not reproducible on my phone, even after testing all mods with such video.

Unfortunately, stack trace is the only information that is available.
Other than than:
- likely related to mods. Our default main menu config does not have video configured in it since it is based on H3:Complete
- may not be system-specific, but no confirmation whether this happens on platforms other than Android
- not sure whether this is first entry to main menu (and first video to play) or some "interference" from (for example) in-game video and then - returning to main menu
- happens on multiple different phones, so this is unlikely to be corrupted install

**To Reproduce**
Unknown

**Did it work earlier?**
Unknown

**Version**
 - OS: Android
 - Version: 1.3.0

**backtrace**
```
(avcodec_send_packet+208)
(CVideoPlayer::nextFrame()+269)
(CVideoPlayer::update(int, int, SDL_Surface*, bool, bool)+364)
(CMenuScreen::show(Canvas&)+112)
(WindowHandler::simpleRedrawImpl()+136)
(WindowHandler::simpleRedraw()+122)
(CMainMenu::update()+340)
(CGuiHandler::renderFrame()+123)
(SDL_main+444)
```

**Comment by Laserlicht** [comment]
I can confirm this bug on Ubuntu. During my debugging for the folders this error was also triggered in my debugging session.

Using german with RoE theme (submod) - with the burning sword.

But only in rare cases and not reproducible.

**Comment by IvanSavenko** [comment]
When exactly did this happen?
Immediately on launching the game?
Or after staying in main menu for some time?
Or after returning to main menu after some actions, e.g. playing game?

Can you remember whether you had opening movies (e.g. 3DO logo) enabled?
