### ISSUE TITLE
Improve Start Game speed

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2560]
**Describe your proposal**
Game start is an order of magnitudes slower than HotA. Screen just lags at connecting to local host even for single player. (which happens to also be confusing by itself)
![image](https://github.com/vcmi/vcmi/assets/15194321/3fb3f4ec-8fa9-4689-98e3-c7589bc76cc1)

**Comment by IvanSavenko** [comment]
We probably need to load game data in multiple threads. Mod handler should be able to load towns/heroes/creatures/etc in parallel (and this is what takes most of time during loading)

And possibly look for a way to optimize game loading itself. I think we spend most of time interacting with json. Couldn't think of anything to improve in there, but it was 10 years ago.

**Comment by krs0** [comment]
But only this connecting... takes 5 seconds on my machine!

**Comment by DjWarmonger** [comment]
Okay, I give it to you. Takes more than 3 seconds in total, most of which is launching Server of course.

```
[2023-Aug-11 17:20:14.264916] INFO network - Found endpoints:
[2023-Aug-11 17:20:14.264916] INFO network - 	0:127.0.0.1:3030
[2023-Aug-11 17:20:14.264916] INFO network - Trying connection to 127.0.0.1:3030(0)
[2023-Aug-11 17:20:16.290604] TRACE network - Setting up thread calling server: 2026 ms
[2023-Aug-11 17:20:16.290604] INFO global - Server command line: .\VCMI_server.exe --port=3030 --run-by-client --uuid=7cd9da09-0e0a-4dd9-b52d-e7c3d2695ebf --enable-shm > "C:\Users\tomas\Dokumenty\My Games\vcmi\server_log.txt"
[2023-Aug-11 17:20:17.437440] TRACE network - Waiting for server: 1146 ms
[2023-Aug-11 17:20:17.437440] INFO network - Establishing connection...
[2023-Aug-11 17:20:17.437440] INFO network - Found endpoints:
[2023-Aug-11 17:20:17.437440] INFO network - 	0:127.0.0.1:3030
[2023-Aug-11 17:20:17.437440] INFO network - Trying connection to 127.0.0.1:3030(0)
[2023-Aug-11 17:20:17.498690] INFO network - Established connection with VCMI 1.3.1.83d97626fe9c193ff6c2f341b7443e53773da638 (server). UUID: d393c55c-bd94-4dbe-b879-9425b21a45ba
[2023-Aug-11 17:20:17.498690] TRACE network - 	Connecting to the server: 62 ms
```

**Comment by IvanSavenko** [comment]
> But only this connecting... takes 5 seconds on my machine!

This is not just "connecting" but also server startup. And server performs almost full loading, identically to client (except some GUI info)

Yes, that's a lot, but optimizing loading procedure will also reduce connection time.

**Comment by IvanSavenko** [comment]
Removed. In develop only.
Didn't want to break something on accident in release build.

**Comment by nullkiller** [comment]
Can we convert JSON files in something more quickly readable? We can serialize our handlers to some cache file for instance if their version does not change.

**Comment by nullkiller** [comment]
Also single process with shared VLC can be an option, again it is hard to implement.

**Comment by DjWarmonger** [comment]
Parallel parsing in different handlers sounds like a simple solution, as long as the process is bottlenecked by CPU and not file loading. Which I doubt.

**Comment by nullkiller** [comment]
Caching can improve both JSON parsing by avoiding part of it and reduce the amount of small file access. Also we support mods in zip files. Is it faster to read it directly from zip file?
P.S. we ha parallel loading which was eventually disabled likely because of some issues

**Comment by IvanSavenko** [comment]
> Can we convert JSON files in something more quickly readable? We can serialize our handlers to some cache file for instance if their version does not change.

In theory we could try creating "save" from VLC using our standard serializer. However problem is that we need to detect all changes in mods. We do have per-mod checksum but in order to compute it we need to load every json from mod anyway.

> Also we support mods in zip files. Is it faster to read it directly from zip file? 

Yes and no. It is faster when archive is not compressed - zip allows "store" compression level where files are simply stored as it. I actually used it for first mods back when system was added - Launcher would download compressed zip and then decompress mod.json and Content.zip from it that used "store" compression for faster loading

However probably requires too much manual work for every mod & effect is less noticeable since most people use ssd's now.

> P.S. we had parallel loading which was eventually disabled likely because of some issues

Yes, but only for some graphical assets used by client. Worth looking into, but probably secondary compared to parallel handlers.
We could also try to speedup battle loading by implementing lazy loading for creature animation - we don't really need every creature animation the very moment battle starts.

**Comment by krs0** [comment]
Ok but could 2x mod validation be skipped for players starters?

**Comment by luk3ZPL** [comment]
What do you think about starting server just after starting the client ? What are the pros & cons ?

**Comment by IvanSavenko** [comment]
@luk3ZPL 
This is also an option, however we'll need to shut down server or somehow deactivate/stop using it if client is connecting to a MP game (in this case only host uses server).

**Comment by IvanSavenko** [comment]
Another option to consider - instead of persistent cached loaded save, have host-client send VLC to server on startup, allowing server to skip loading process.

Of course, in this case VLC transfer must be faster than loading. Not sure how fast that thing is now.

**Comment by dydzio0614** [comment]
IMO multithreaded loading sounds like good option to try, before evaluating other solutions

**Comment by IvanSavenko** [comment]
@dydzio0614 True.
Mostly thinking about other options, in case if multithreaded loading turns out to be not enough. Or if it turns out to be problematic for some reason.

For example I already suspect that *logging* might become a bottleneck - we print a lot and logging is protected by mutex, shared by all threads.

**Comment by dydzio0614** [comment]
What about this: is there any good reason why we split to two executables by default in first place? Two points that raise my suspicion in this regard:
1. Confusing windows players with firewall blocking VCMI
2. I do not see this approach in commercial games - even some pretty good game design examples like quake 3 have support for creating local server "from client executable" and separate executable only exists for dedicated server

**Comment by IvanSavenko** [comment]
@dydzio0614 Don't see any short-term solution here unfortunately
Problems:
- Game expects to have separate VLC for client and server. We have hack-ish solution to enable 2 VLC's in single binary on Android and (I think) iOS, but it does not eliminates network - Single-app mode still uses network to communicate with itself.
- We can try to replace network with some other communication method, e.g. events queue for self-connections, but this requires work. I've been thinking about making swappable interfaces alongside with UDP support (TCP/UDP/self-connect), but this is not trivial task.

> Also any downsides of single executable are already forced on platforms that require it (iOS?)
All of them. Android (and probably iOS) don't have firewall popup but other than that single process is basically trick to package 2 executables into one. Single-process vcmi works identically to dual-process.


In long-term I'd like to have some alternative solution that won't have our current issues, but probably not for 1.4
