### ISSUE TITLE
minimap is revealed when turn is passed

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2573]
**Describe the bug**
Minimap is not hidden when turn is passed to another player in hotseat mode. Thus, player can see opponent's location.

**Did it work earlier?**
IDK

**Screenshots**
<img width="677" alt="Снимок экрана 2023-08-13 в 01 32 32" src="https://github.com/vcmi/vcmi/assets/9308612/594674a8-81ea-431f-90bf-97f7744609a9">

**Version**
 - Version: 1.3

**Additional context**

**Comment by peterpaulis** [comment]
this is a big problem in hot seat, where the next opponent sees the previous map

**Comment by krs0** [comment]
I think there are bigger problems than that. IiRC he sees your heroes too.
