### ISSUE TITLE
On player side, disable validation of mods.

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2578]
Edit: following Ivan's input, whole validation could be disabled by default (not only translation) and enabled via some launcher option.

**Describe your proposal**
Right now all languages are validated, which is a waste of time. Only preferred language should be validated. Because that is the only one that will be used in the session.

**Additional context**
CModHandler::validateTranslations() should have an alternative CModHandler::validateTranslationForPreferredLanguage() ?
and validateTranslations() should be called only via a setting?

**Comment by IvanSavenko** [comment]
You are not wrong, but keep in mind that right now we don't differentiate between "player side" and "modder side".
Generally, there is no point in validating mods in general on player sides. But makes point to validate mods if game is used by modder.

**Comment by krs0** [comment]
Even better! Disable validation completely unless enabled by player, via launcher.

**Comment by krs0** [comment]
translation validation (maybe mod also) are even done twice! Once at game load and second at map start!

**Comment by IvanSavenko** [comment]
Implemented as option in launcher
