### ISSUE TITLE
For combined artifacts not all artifacts are counted

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2581]
**Describe the bug**
I have all components for a combined artifact. 1 is equipped on hero, 2 are in the backpack. GUI reports I have only 1 component. (Probably the one on the hero).

![image](https://github.com/vcmi/vcmi/assets/15194321/857a447d-bbfc-487f-96dc-389603e9bda2)

![image](https://github.com/vcmi/vcmi/assets/15194321/97f48674-e1d9-44e2-9d21-935f9e357b24)

**To Reproduce**
1. vcmiartifacts
2. Equiop Vampire's cowl on hero
3. Rightclick any component 
4. 1/3 components are shown as available.

**Expected behavior**
All components should be accounted for.

**Comment by SoundSSGood** [comment]
Any ideas how to fix this?

**Comment by krs0** [comment]
Should list all components that you have, equipped or in backpack.

**Comment by SoundSSGood** [comment]
In this case, a situation may occur when the counter will show 3/3 but the artifact cannot be assembled. Since some items will be in the backpack. And this will be another bugreport

**Comment by krs0** [comment]
If you have all required parts (on you or in backpack) the usual: do you want to combine should appear and artifact will be combined in backpack on first position.

Right now this detection is done separately for equipped and backpack, iirc.

**Comment by SoundSSGood** [comment]
> asks too much

what do you mean?

**Comment by krs0** [comment]
Every time you move a component of a combined artifact you are asked if you want to combine it or not.

Sometimes it is too much asking (at least my opinion)
