### ISSUE TITLE
Hero has 0 movement, but bar still has some green

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2586]
**Describe the bug**
Hero portrait still shows some green even if movement points are 0
![image](https://github.com/vcmi/vcmi/assets/15194321/13a5e454-27a1-4f2d-9ec5-fa28dc511df3)

**Expected behavior**
Bar has no green

**Comment by Nordsoft91** [comment]
you cannot walk down, but can you walk along road right or left? actually same behavior observed in OH3

**Comment by krs0** [comment]
I did not check :(. Will reopen if that is the case.

**Comment by luk3ZPL** [comment]
There is a bug related with hero movement points. See: #2591
