### ISSUE TITLE
Even if I visited a creature bank, no guards info is shown on right click

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2588]
**Describe the bug**
I visited the griffin conservatory with a secondary hero like a pro player. After that the conservatory still shows as not visited.

![image](https://github.com/vcmi/vcmi/assets/15194321/db00fdef-1efe-4ff2-b2bb-b1abd1f6a4d6)

**To Reproduce**
1. Go to griffin conserrvatory
2. See how many griffins inside (no fight)
3. No visited still appears afterwards

**Comment by Nordsoft91** [comment]
What is expected behavior? If no fight, then it should be not visited. All creature banks become "visited" after winning their reward

**Comment by krs0** [comment]
The info on guards numbers should be known.
Once I visit the bank with a hero, from then on, when I right click, the info on guards should be shown.

**Comment by IvanSavenko** [comment]
Implemented in #2988
