### ISSUE TITLE
Left mouse map scrolling not working correctly

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2589]
**Describe the bug**
I can move the mouse out of the window on the left side and scrolling proceeds to the right!!!

**To Reproduce**
1. Run VCMI in window mode, maximize
2. Use My settings from screenshot
3. Move mouse to left window edge
4. it scrolls to the right!

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/15194321/e91f0adb-e849-4a19-9642-8382451d2a2d)

**Version**
 - OS: [e.g. Windows, 
 - Version: [develop

**Comment by krs0** [comment]
On Win 10 as well.
Run VCMI in wondow mode, maximize then scroll left. 
Setup looks like this:
![image](https://github.com/vcmi/vcmi/assets/15194321/61ba97ea-964e-4f16-8793-eec31b38ec90)

**Comment by IvanSavenko** [comment]
> Run VCMI in window mode, maximize 

Reproduced, after maximizing window
