### ISSUE TITLE
Map validation unusable

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2590]
**Describe the bug**
Cannot see the information from map validation

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/15194321/817e2326-7cd6-4a17-b186-b3fdb3754f54)

**Version**
 - OS: [e.g. Windows, 
 - Version: [beta

**Comment by krs0** [comment]
Player 1 dose'nt have any means in fact player 2 does not have any castles!

**Comment by DjWarmonger** [comment]
Another issue arising due to lack of GUI scaling in Editor.

**Comment by Nordsoft91** [comment]
@krs0 , this window is stretchable, isn't it?

**Comment by krs0** [comment]
Did not had an indicator in lower right so did not think of that :(.... so its not a blocker... but gui is still awful :(
EG: when I move mouse over text:
![image](https://github.com/vcmi/vcmi/assets/15194321/45a4a6b9-3a19-4755-9b1c-0046e9418ccd)

**Comment by Nordsoft91** [comment]
I cannot reproduce

**Comment by Povelitelh3** [comment]
It's windows related problem. I had it long time ago

**Comment by krs0** [comment]
Maybe there are multiple problems on windows...
Preview pane is too small, no way to make larger
right object selection pane cannot be made wider

![image](https://github.com/vcmi/vcmi/assets/15194321/46f2a959-81d5-407d-b45d-fd5eebd0cc50)
