### ISSUE TITLE
Adventure map zoom reset on touch devices

### ISSUE THREAD

**Issue by peterpaulis** [vcmi/vcmi#2594]
**Describe your proposal**
Playing on iPad it's great to pinch zoom in / out the adventure map, but there should be a way to "reset" the zoom... like double tap with one or two fingers, or to use the settings - be able to set the zoom also there - there is no ingame setting currently

[Optional future feature addition] as an addition for consideration, the zoom should be for each hot-seat player individual and possibly saved in the save game?

**Comment by krs0** [comment]
On windows there is Backspace

**Comment by peterpaulis** [comment]
@krs0 ok, so this goes probably to iPad / Android

**Comment by Nordsoft91** [comment]
Implementation suggestion:
When zoom in/zoom out, game should stuck for a moment at 1:1 level with slight vibro touch.
So player will know when to remove fingers
