### ISSUE TITLE
RMG often fails to find a template when "Computer players" option is used

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2596]
**Describe the bug**
IF you try to generate random map and select "CPU only" players to value other than zero, rmg quite often fails to find template for such map, failing to generate a map

**To Reproduce**
1. Open RMG screen
2. Select 1 "Human or CPU player" and 1 "CPU player"
3. Try to generate random map

**Expected behavior**
Game should select any template that allows either 1 human and 1 CPU player or one that allows 2 human players

(this is also H3 behavior)

**Actual behavior**
Game attempts to select template that allows 1 human and 1 CPU player and fails since there are no such template

**Version**
 - Version: 1.3.0

**Comment by Nordsoft91** [comment]
reason is in strange template design - players (while could be both human and cpu) and cpuPlayers are 2 different independent parameters

**Comment by IvanSavenko** [comment]
Maybe, but:
1) This is not how H3 does things
2) This often confuses players leading to reports about "broken RMG"

**Comment by krs0** [comment]
HD uses 2 variables
one for player or cpu
another for cpu only
![image](https://github.com/vcmi/vcmi/assets/15194321/da3eba1b-adb0-4f9f-bcab-da9c325826bd)
![image](https://github.com/vcmi/vcmi/assets/15194321/76f3432a-354e-491c-8f31-94b0678ea18f)

**Comment by krs0** [comment]
This was reported for the n'th time on Discord. Needs a higher priority.

**Comment by DjWarmonger** [comment]
Well, this is messed up. This template does not have "cpu" player setting at all, and it defaults to 0. Looks like an issue with template conversion, as in original rmg.txt it does.

And HoTA doesn't have this exact template either to compare.

**Comment by krs0** [comment]
Why not redisign these 2 not so intuitive settings?

Total number of players
Reserved for AI players, or Locked for AI
Or Reserved for computer players

If AI is to be replaced, CPU players might not mean much nowadays. Computer players would have more meaning.

**Comment by DjWarmonger** [comment]
From the original rmg.txt it looks like there is a global player limit (obviosuly) and human player limit, and all the remaining players are replaced by AI.

We'd have to change the labels in RMG gui as well to reflect that:
<img width="251" alt="image" src="https://github.com/vcmi/vcmi/assets/2566990/3a4513f3-ffa0-416c-9bcc-3b7360668ca8">

**Comment by IvanSavenko** [comment]
Still reproducible:

(same with 1 human or CPU + 7 CPU only)
![зображення](https://github.com/vcmi/vcmi/assets/1576820/f867a73a-8337-42a7-afe8-3aa5b89880f1)

**Comment by DjWarmonger** [comment]
Ahh. These bars are not even present with updated interface:

<img width="263" alt="image" src="https://github.com/vcmi/vcmi/assets/2566990/25d6390c-c9b8-4d81-865c-d45f77304dc1">
