### ISSUE TITLE
 Show full mod hierarchy in mod dependencies

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2599]
**Describe your proposal**
Right now hunting the submods that keep a mod from being uninstalled is quite hard. Displaying full submod hierarchy would help.

In the example below HotA neutral heroes is a submod of Netureal Heroes mod.
![image](https://github.com/vcmi/vcmi/assets/15194321/521c2624-f81c-4529-abb8-0c2b9a29f8fb)

Additionally there are 2 lines there. One listing only one mod and the second that lists 2 mods!
One line with all dependencies would be enough.

**Comment by IvanSavenko** [comment]
Implemented in #4787
