### ISSUE TITLE
Compiling vcmi 1.3.0 fails with gcc11 because missing includes?

### ISSUE THREAD

**Issue by Kieltux** [vcmi/vcmi#2602]
**Describe the bug**
Hello, I am a vcmi package maintainer at [openSUSE](https://build.opensuse.org/package/show/games/vcmi).
Compile fails with gcc11 because of missing includes after the switch from boost to standard c++17 functions in vcmi 1.3.0.

```
   74s]       |                            ^~~~~~~~
[   74s] /home/abuild/rpmbuild/BUILD/vcmi-1.3.0/lib/battle/BattleHex.h:1:1: note: 'std::optional' is defined in header '<optional>'; did you forget to '#include <optional>'?
[   74s]   +++ |+#include <optional>
[   74s]     1 | /*
[   74s] In file included from /home/abuild/rpmbuild/BUILD/vcmi-1.3.0/lib/battle/Unit.h:16,
[   74s]                  from /home/abuild/rpmbuild/BUILD/vcmi-1.3.0/lib/battle/AccessibilityInfo.cpp:13:
[   74s] /home/abuild/rpmbuild/BUILD/vcmi-1.3.0/lib/battle/../bonuses/Bonus.h:181:33: error: 'std::optional' has not been declared
[   74s]   181 |         std::string Description(std::optional<si32> customValue = {}) const;
[   74s]       |                                 ^~~
[   74s] /home/abuild/rpmbuild/BUILD/vcmi-1.3.0/lib/battle/../bonuses/Bonus.h:181:46: error: expected ',' or '...' before '<' token
[   74s]   181 |         std::string Description(std::optional<si32> customValue = {}) const;
```

**Game logs**
*/*

**To Reproduce**
*/*

**Expected behavior**
*/*

**Actual behavior**
*/*

**Did it work earlier?**
*/*

**Screenshots**
*/*

**Version**
*/*

**Additional context**
I made then a patch with all missing includes, and vcmi 1.3.0 builds [fine](https://build.opensuse.org/package/show/home:Kieltux:branches:games/vcmi).

For example

```
diff -Nur vcmi-1.3.0-orig/lib/battle/BattleHex.h vcmi-1.3.0/lib/battle/BattleHex.h
--- vcmi-1.3.0-orig/lib/battle/BattleHex.h	2023-08-04 10:19:09.000000000 +0200
+++ vcmi-1.3.0/lib/battle/BattleHex.h	2023-08-08 17:17:09.553391510 +0200
@@ -7,6 +7,7 @@
  * Full text of license available in license.txt file, in main folder
  *
  */
+#include <optional>
 #pragma once
```
[vcmi-fix-missing-include.patch.txt](https://github.com/vcmi/vcmi/files/12361508/vcmi-fix-missing-include.patch.txt)

Is gcc11 the problem or are these includes are really missing (not a real programmer).

Thank you.

**Comment by IvanSavenko** [comment]
Yes, missing include. Thanks for heads up.

Should be added in `global.h`, around line 120

Will fix for 1.3.1, on this Friday

**Comment by Kieltux** [comment]
Wow! Thank you very much for this super quick response!
Did you take a look into https://github.com/vcmi/vcmi/files/12361508/vcmi-fix-missing-include.patch.txt?
There are some more (maybe because of boost-1.66 - not sure).

For example:
```
diff -Nur vcmi-1.3.0-orig/client/CServerHandler.cpp vcmi-1.3.0/client/CServerHandler.cpp
--- vcmi-1.3.0-orig/client/CServerHandler.cpp	2023-08-04 10:19:09.000000000 +0200
+++ vcmi-1.3.0/client/CServerHandler.cpp	2023-08-10 20:20:43.062111880 +0200
@@ -51,6 +51,7 @@
 #include "../lib/serializer/Connection.h"
 #include "../lib/serializer/CMemorySerializer.h"
 
+#include <boost/asio.hpp>
 #include <boost/uuid/uuid.hpp>
 #include <boost/uuid/uuid_io.hpp>
 #include <boost/uuid/uuid_generators.hpp>

```
Thank you for taking your time.

**Comment by IvanSavenko** [comment]
Looks like we miss both `optional` and `variant` include in global.h. Don't see anything from boost. Might be related to boost version or to version of libstdc++ / libc++ (whatever openSUSE uses).

In any case this is bug with vcmi, not with libraries. Will fix.

**Comment by Kieltux** [comment]
Thank you very much. Could drop the patch vcmi 1.3.1 is building fine.
