### ISSUE TITLE
Hiring hero corner cases

### ISSUE THREAD

**Issue by nullkiller** [vcmi/vcmi#2603]
**Describe the bug**
When hiring a hero in bottom right town, crash occurs

**To Reproduce**
1. Load attached map and hire a hero in bottom right town (visitable pos 35,35)
4. Server crashes

**Expected behavior**
At least town portal was able to teleport into this town

**Actual behavior**
Crash happens on hero hiring

**Did it work earlier?**
Do not know

**Version**
 - OS: Windows, MSVC
 - Version: 1.3

**Additional context**
[towns-and-prisons.zip](https://github.com/vcmi/vcmi/files/12362860/towns-and-prisons.zip)

**Comment by nullkiller** [comment]
There is a map where such town exists to avoid AI hero being destroyed completely

**Comment by IvanSavenko** [comment]
When corner case is literally a (map) corner case :)

Will look into it
