### ISSUE TITLE
RMG: Object placement Issues

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2607]
**Describe the bug**
Some weird object placements. Mainly WoG plus HotA (do not remember in what order).
If those are suspected to come from bad mod graphics... discard them for the moment.

1) Those 2 buildings too close for comfort
2) Stone Arch hide building
3) same stone arch
4) Centaur sits on resources
5) nightmare hides behind bushes
6) Naga sits on resources

![image](https://github.com/vcmi/vcmi/assets/15194321/cbb53bf6-7407-446c-ba85-10ce4a886992)

Edit: Added a new batch in comments

**Comment by DjWarmonger** [comment]
> Centaur sits on resources
> Medusa sits on resources
They do not. Simply def graphics is shifted right a bit, might be fixed in HoTA mod.

> nightmare hides behind bushes
This will need map object reindexing. Somewhere on my TODO list, but not high priority.

**Comment by krs0** [comment]
With 2 and 3..  I think the arch itself is too big... maybe the object can be modified a little to leave some space behind it?

**Comment by DjWarmonger** [comment]
Possibly, but it's an issue of animage added in mods (possibly following the original design) and not RMG. Random map generator doesn't know if something looks ok to human or not.

**Comment by krs0** [comment]
Yes so the fix is not in RMG but in mod. Do we just disable the image? Or add some properties? (I am not that knowledgeable into mods)

**Comment by DjWarmonger** [comment]
At this point all the possible obstacles are treated equally and placed randomly (largest first). There are no special properties for them, nor do I plan any. All you can do for now is to change object's mask to reserve more space around it.

**Comment by krs0** [comment]
A new batch of glitches!

![image](https://github.com/vcmi/vcmi/assets/15194321/97871677-1209-4341-af2d-4093028485b5)
![image](https://github.com/vcmi/vcmi/assets/15194321/1d0fe85c-26d1-49a1-879b-84cdb8ff239c)
![image](https://github.com/vcmi/vcmi/assets/15194321/e2df6d39-7378-458b-b0d0-9a50be222218)
![image](https://github.com/vcmi/vcmi/assets/15194321/569b54db-8d9e-46ee-9ca4-0fdd47bd0e4e)
![image](https://github.com/vcmi/vcmi/assets/15194321/4cc1dec1-48ea-44cd-a2b2-7d3ff22f17dc)
![image](https://github.com/vcmi/vcmi/assets/15194321/c09b591c-3dc0-4c8f-959c-091aa93730a2)
![image](https://github.com/vcmi/vcmi/assets/15194321/b9b1d16e-989a-4ba2-8448-a27f85cbc783)

**Comment by Nordsoft91** [comment]
are those issues related to rendering? how it's connected to rmg?

**Comment by IvanSavenko** [comment]
> are those issues related to rendering? how it's connected to rmg?

Connected. In H3 object rendering order is heavily affected by order of objects in map.

Example:
![зображення](https://github.com/vcmi/vcmi/assets/1576820/55baa7ba-9c36-4a7d-b7dc-09d1b58c971f)

Two identical obstacles, two identical monsters. However in one case dragon is below obstacle and in other one - above it.

**Comment by DjWarmonger** [comment]
![image](https://github.com/vcmi/vcmi/assets/2566990/f6d917e3-d56d-4fec-8c48-aed21672da8a)
This is actually in-line with object mask definition. Just def from mod doesn't quite match the original.

**Comment by DjWarmonger** [comment]
Fixed Mirror in this PR: https://github.com/vcmi-mods/wake-of-gods/pull/30

But I see this cool blue skin in missing in current WoG, why?
