### ISSUE TITLE
Highlight missing resources for building a building

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2614]
**Describe your proposal**
From mav on Discord.

Highlight in red, or somehow else the resources you have not enough of to build a building.

![IMG_20230818_140317-1](https://github.com/vcmi/vcmi/assets/15194321/8f885d21-002b-4370-95a1-72717af95662)

**Comment by Laserlicht** [comment]
Would be a great feature to show in red the missing resources next to the costs.

But sadly not that easy to implement. The class using for this is used for much other cases. One class to handle many cases.
