### ISSUE TITLE
Incorrect movement calculation from dirt to snow

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2619]
**Describe the bug**
Reported on discord by Der_Wollschwein

so, here's my current army and movement pobeha
![image-6](https://github.com/vcmi/vcmi/assets/15194321/42397d5a-c1cc-4afa-97eb-59ede5eba2ed)

and here's the info I get when I try to move one tile right
![image-7](https://github.com/vcmi/vcmi/assets/15194321/d69069c4-26a0-482e-b92d-5405a7405583)

and here, when I try to move down
![image-9](https://github.com/vcmi/vcmi/assets/15194321/cd9aeaae-252c-4215-90d7-7099a1869533)

**Expected behavior**
Movement points should depend on starting terrain - dirt - 100 mp
There is also the weird 145 cost, that seems to indicate all movement points are consumed.

Still the bug could be GUI only bug.

**Comment by IvanSavenko** [comment]
Fixed in 1.3.2
