### ISSUE TITLE
Ancient lamp blocks path

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2626]
**To Reproduce**
1. Treasure pile has ancient lamp
2. Refuse proposal from lamp

<img width="378" alt="Снимок экрана 2023-08-21 в 00 34 02" src="https://github.com/vcmi/vcmi/assets/9308612/d51cb18b-db42-4f96-a3f3-be9e1f66528a">

**Comment by Alucard648** [comment]
You need to buy out Genie`s Lamp creatures to access Dragon Utopia. :-)

**Comment by SparrowJacek** [comment]
It's normal HotA behavior, that you need to buy all djinnis for the lamp to disappear

**Comment by by003** [comment]
Could you test if you have full troops in the stack, then buy genies from the lamp, if you change your one troops to genies, would it crash? It happened before.

**Comment by Nordsoft91** [comment]
@by003 yes, it crashes
