### ISSUE TITLE
Endless game loading

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2634]
**To Reproduce**
1. Load game -> scenario
2. Select and load any game with incompatible mods (or use attached example)

[unpassable.vsgm1.zip](https://github.com/vcmi/vcmi/files/12401845/unpassable.vsgm1.zip)

**Expected behavior**
Notification about mods incompatibility

**Actual behavior**
Game freeze

**Did it work earlier?**
Regression in develop branch, 1.3.1 works OK

**Version**
 - Version: 1.4 develop

**Comment by IvanSavenko** [comment]
Fixed in current beta
