### ISSUE TITLE
Invisible creatures

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2644]
Creatures from mandrakes are invisible (Courtyard mod)

![IMG_4371](https://github.com/vcmi/vcmi/assets/9308612/0a3ce77a-e57a-493a-84a1-e32cbc70b104)

**Did it work earlier?**
yes, regression

**Version**
 - Version: 1.3.0, Courtyard 1.0.7

**Additional context**

**Comment by IvanSavenko** [comment]
Closing as duplicate of #2477
