### ISSUE TITLE
Game crash on ancient lamp with full troops

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2651]
**Describe the bug**

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Make sure you have all army slots occupied by different creatures
2. Visits ancient lamp, accept offer
3. Replace one of your stacks with genes

**Expected behavior**
No crash

**Actual behavior**
Crash

**Did it work earlier?**
No

**Screenshots**

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: 1.3.1

**Additional context**

**Comment by DjWarmonger** [comment]
Could be re-introduced old bug with Pandora Box, which was deleted before troop exchange ends. Will check.

**Comment by IvanSavenko** [comment]
Found the crash.

Will apply same fix as in pandora box. Thanks for the hint.
