### ISSUE TITLE
In Quick Army Management panel there is no selection for selected stack

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2656]
![image](https://github.com/vcmi/vcmi/assets/15194321/d1d12664-cb2b-4c92-be1d-0c7b68dd239b)

Here when you select something you should see a selection like everywhere else.

EG:
![image](https://github.com/vcmi/vcmi/assets/15194321/2d3a511e-933c-405d-ac04-ff722e0e01b9)

**Comment by dydzio0614** [comment]
there is selection but hota mod comes with buggy graphics

**Comment by krs0** [comment]
Can you explain please a little? Maybe I can correct that?

**Comment by dydzio0614** [comment]
i forgot which file was causing problem, but was explained on slack few days ago..

**Comment by krs0** [comment]
hota\Mods\graphicalFixes\content\sprites\CPrSmall.json
delete line
         { "frame" :   1, "file" : "CPrSm001.png" },
This WILL fix this bug.

Alternatively, you can try re-exporting corresponding image from hota files since it might be different from one in H3
