### ISSUE TITLE
Game hangs on day 1 on AI turn

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2658]
**Describe the bug**
Happened a couple of times on different AI turn. Game just hangs there.

**Game logs**

**To Reproduce**
1. Go to All for one
2. Click on end turn.

**Version**
 - OS: [e.g. Windows, \
 - Version: [VCMI develop
 - 
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12423643/VCMI_Server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12423644/VCMI_Client_log.txt)

**Comment by Nordsoft91** [comment]
@krs0 with timer enabled or disabled? I cannot reproduce

**Comment by krs0** [comment]
Single player no timer. No mods apart from essential and extras.
I am not on PC. Will try to find exact usage this evening.
