### ISSUE TITLE
Can refuse Witch hut or scholar

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#2659]
**Describe your proposal**
Now witch hut and scholar cannot be refused, if it will not be refused from next version, there is also an advise to do it.
While visiting witch hut, move cursor to this hut, the skill which it taught will be shown in the blank.
Can every huts show this information even if it is not visited?

Scholar will be easier, it might be changed as only teach a primary skill without any settings. 

**Additional context**

**Comment by krs0** [comment]
Witchhut are no brainer to be refused. because you can scout them with secondary hero.

But scholar... this cannot be scouted, so you will have to risk or play safe and leave it alone. My idea is to leave scholar like it is. Its good to still have some randomenes in the game.
