### ISSUE TITLE
Не удалось установить соединение SSL

### ISSUE THREAD

**Issue by llKabaL** [vcmi/vcmi#2660]
Hello. I have a problem with downloading mods, writes such an error: Unable to download all files. Encountered errors: SSL handshake failed. Please help me solve the problem.

![Ошибка vcmi](https://github.com/vcmi/vcmi/assets/143075559/6c93f686-066e-4f11-bbc4-b5dabb650f6f)

**Comment by Nordsoft91** [comment]
Please make sure openssl is installed in your system and antivirus doesn't block connection.
