### ISSUE TITLE
Add support for letterboxing

### ISSUE THREAD

**Issue by ghd987654321** [vcmi/vcmi#2670]
Currently when playing in a different aspect ratio or scaling level than the original game, vcmi opens stuff with set sizes (e.g. town screen, combat screen) in the center of the screen, but it leaves the adventure map UI on the screen as well

![Screenshot_20230825_134716](https://github.com/vcmi/vcmi/assets/141758961/22fe5360-c57c-44af-889f-015de865a4e9)

But in the HD Mod when playing with a vertical resolution smaller than 664 or in the HD Edition,  when viewing such windows, the screen is letterboxed so that only that window is really shown

![ss_89f4967a8e42185534d99ebad949b57894bb70fd](https://github.com/vcmi/vcmi/assets/141758961/6a50a0c7-59ab-4143-9001-cd649afa2625)

I think that the user should be able to toggle between these 2 ways of viewing stuff

**Comment by peterpaulis** [comment]
basically the adventure map in background is useless, really better to have a static background instead
