### ISSUE TITLE
Quick combat between heroes does not work

### ISSUE THREAD

**Issue by sdtafxy** [vcmi/vcmi#2671]
I use VCMI 1.3.1 macOS version.
Check Quick Combat in System Options to keep it checked.
The battles between our heroes and neutral creatures are normal and manifest as fast battles.
However, the battle between our heroes and enemy heroes is directly into the battle scene, which is not normal.
This does not appear in the VCMI 1.2.x macOS release.

<img width="800" alt="截屏2023-08-25 21 14 25" src="https://github.com/vcmi/vcmi/assets/143193114/2900b074-d807-4d73-8e29-6ce91cd798a9">

**Comment by Nordsoft91** [comment]
It's not a bug, quick combat works only with neutral monsters by design.

**Comment by dydzio0614** [comment]
I would say it needs fix, it is annoying to fight trash AI heroes manually and it work in H3, feature should check if enemy player is AI

**Comment by IvanSavenko** [comment]
Yeah. We should permit autocombat (and replaying it) in battles with AI players

**Comment by Laserlicht** [comment]
Would be great if we find a solution for quick combat with neutral heroes and also for finishing started battle with quick combat.
