### ISSUE TITLE
Cannot start single scenario RMG

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2680]
**To Reproduce**
1. New game -> scenario ->rmg
2. press start game

**Expected behavior**
Random map generated and game started

**Actual behavior**
Player red winner because all opponents were defeat

**Did it work earlier?**
works in 1.4.0.b0eec85aca4054a588bb35cbcdbe63827d92b355

**Screenshots**
<img width="245" alt="Снимок экрана 2023-08-27 в 00 46 09" src="https://github.com/vcmi/vcmi/assets/9308612/0275e1b3-d8b5-4d8e-aaae-a89cbf1e7576">

**Version**
 - OS: VCMI 1.4.0.4500e5971384b91814843d36281bc909feabd260
 - Version: [VCMI version]

**Comment by krs0** [comment]
Do not want to nag.... but can you change issue name to something like: Cannot start single scenario RMG.

If I understood correctly, since you have not mentioned selecting a template, you used random option?

Is it the same for all rmg templates? Or only 1 is broken?

**Comment by Nordsoft91** [comment]
@krs0 , if you install build, your questions will be addressed 😛
