### ISSUE TITLE
Battle not with the attacked creatures

### ISSUE THREAD

**Issue by SoundSSGood** [vcmi/vcmi#2689]
**Describe the bug**
You attack some creatures but fight another.

**To Reproduce**
1. Load savefile
2. Attack gremlins

**Expected behavior**
Battle against gremlins

**Actual behavior**
Battle against ice elementals

**Did it work earlier?**
Do not know. I think no.

**Screenshots**
![bug](https://github.com/vcmi/vcmi/assets/87084363/5be8f0e1-466a-44c4-8c05-caaca77ca612)

**Version**
 - Version: develop

**Additional context**
[bug.zip](https://github.com/vcmi/vcmi/files/12448820/bug.zip)

**Comment by SoundSSGood** [comment]
It looks like it's a pathfinding bug. This is what the pathfinder works in Hota.
![hota](https://github.com/vcmi/vcmi/assets/87084363/dc3d0eab-0ee9-4461-93be-2e650721fcd9)

**Comment by nullkiller** [comment]
[adjacent-guards.zip](https://github.com/vcmi/vcmi/files/12640324/adjacent-guards.zip)
