### ISSUE TITLE
Mod compatibility isn't checked

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2696]
**Describe the bug**

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
Assumed you are on develop (1.4)

1. Enable any mod in launcher and exit
2. Open mod.json and add there
```
"compatibility":
{
	"min" : "1.2.0",
	"max" : "1.3.2" //use 1.2.0 here if you want to reproduce on 1.3
},
3. Open launcher - observe disabling icon for this mod
4. Start game
```

**Expected behavior**
Mod is disabled

**Actual behavior**
Mod is enabled

**Version**
 - Version: 1.3.1, develop

**Additional context**

**Comment by krs0** [comment]
Is this a typo?
I cannot wrap my head around this comment :)

"max" : "1.3.2" //use 1.2.0 here if you want to reproduce on 1.3
