### ISSUE TITLE
Improve way to check compatibility with mods

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2697]
Currently it's possible to specify compatibility versions in mod.json, so launcher and client can verify it before activating.
```
"compatibility":
{
  "min": 1.2.0,
  "max": 1.3.2
}
```

However, if mode will omit version part, assuming "any" it will be interpret by both launcher and client differently:
```
"compatibility":
{
  "min": 1.2, //assuming 1.2.x, will be interpret as 1.2.0 but no problem
  "max": 1.3 //assuming 1.3.x, will be interpret as 1.3.0, so mod become incompatible with 1.3.1
}
```

Suggest to unify approaches used for compatibility check in both launcher and client and support behavior described above.

Another suggestion - change function signature. Current:
`bool CModVersion::compatible(const CModVersion & other, bool checkMinor, bool checkPatch) const`
change by `bool CModVersion::compatible(const CModVersion & other, int checkOptions = CHECK_MAJOR | CHECK_MAJOR_MINOR | CHECK_MAJOR_MINOR_PATCH) const`

**Comment by krs0** [comment]
So max 1.3 means now all 1.2.x versions?
