### ISSUE TITLE
WoG commander extra abilities do not work (at least some if not all)

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#2701]
**Describe the bug**
WoG commanders have special abilities when mastering some of basic abilities like attack, vitality. In WoG these special abilities need to be trained, IIRC in VCMI they are autogranted due to simplified implementation, but they do not work - for example get high level commander with mastered attack + speed, see shooter ability -> observe commander being unable to shoot.

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Start some map, get level 1 hero
2. Use vcmiexp 100000 cheat - more may be bugged due to #2699 
3. Boost up commander attack and speed during his levelup screens
4. Start battle - see commander being unable to shoot

**Expected behavior**
Commander should be able to shoot

**Actual behavior**
Commander can only melee attack or cast spell

**Did it work earlier?**
Probably worked long ago

**Screenshots**

**Version**
 - OS: Linux
 - Version: 1.4 current develop as of 27.08.2023, WoG mod from version 1.3 branch

**Additional context**
To be fixed separately - no autogranting commander extra abilities - force leveling them up

**Comment by misiokles** [comment]
WoG commanders can shoot after mastering in 1.3.0 (I've checked this not long time ago)

**Comment by dydzio0614** [comment]
will try again various versions to make sure

**Comment by dydzio0614** [comment]
broken in 1.3.1 for me

**Comment by dydzio0614** [comment]
OK - report is wrong for now - these abilities are indeed learnable separately at levelup, but they do not have selection highlight...

**Comment by swats-the-floran** [comment]
for a few months thought that commanders just aren't finished. extra abilities look like static images. another person who plays vcmi with me didn't get it too.
