### ISSUE TITLE
Show only possible players when selecting random # of players for random maps

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2703]
**Describe the bug**
Now when selecting player number random, all 8 players are shown in Show Advanced Options window

![image](https://github.com/vcmi/vcmi/assets/15194321/a0448846-f872-4075-a046-834cf5ee254b)

**To Reproduce**
1. Random map template Jebus Cross
2. Click on Random number of players
3. Select show advance options
4. select TAN (unavailable, 4 player max template)
5. you are now spectator for AI?!? and game ends after first battle?!?

**Expected behavior**
Only max supported number of players should be shown.

**Comment by Nordsoft91** [comment]
Same as https://github.com/vcmi/vcmi/issues/1233
