### ISSUE TITLE
Begin is disabled forever after no template found message

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2704]
**Describe the bug**
VCMI cannot find a template with preselected options (that's fine), but then the BEGIN button is permanently disabled!

**To Reproduce**
1. Select Single player RMG -> random
2. select size M
3. select 7 players
4. press begin
5. Begin button gets disabled after message and cannot be reenabled unless going to main menu.

![image](https://github.com/vcmi/vcmi/assets/15194321/84954628-3464-4dc6-a208-2c9abe1c7dc9)

**Comment by IvanSavenko** [comment]
Seems to be fixed in 1.4
