### ISSUE TITLE
In selecting heroes from portraits unavailable heroes should be disabled

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2705]
**Describe your proposal**
When using the new hero portraits selector,  you can select a hero that is picked by other player. (nothing happens, but its shown in the list and you can click it)

Ideally those heroes should not be available for selection, just like in the old left right arrows selection controls.

In the picture Tan selected Sir Mulich, but he is still available for Blue.
![image](https://github.com/vcmi/vcmi/assets/15194321/55d57867-a0e0-4409-bc5e-9bc2b625f40b)

Proposition... show them greyed out? or with a red X? or if too complicated... not at all?

**Comment by by003** [comment]
I reckon to fix hero repeat bug should be important as well. 
Sometimes in a random map, if hero is repeat with a existed hero in prison, this hero cannot use spell book and he cannot pick up any artifact.
Selecting repeat hero is not available in scenario menu, it only needs some GUI improvements.

**Comment by krs0** [comment]
Yes, but that is completely separate from this.

**Comment by by003** [comment]
I know it is different bug but would you like to test it and put it here? I cannot recurrent it because it occurs with a low probability.

**Comment by IvanSavenko** [comment]
@by003 Might be better to report it separately.
@DjWarmonger looks like RMG can create duplicate heroes.

**Comment by DjWarmonger** [comment]
> Sometimes in a random map, if hero is repeat with a existed hero in prison
This should not happen in first place. Is that hero Orrin by any chance?

**Comment by by003** [comment]
> This should not happen in first place. Is that hero Orrin by any chance?

Maybe I need to collect a save file before I post this bug.
