### ISSUE TITLE
Can choose 3 players in a 2 RMG template

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2719]
**Describe the bug**
I can choose 3 players in a 2 player rmg template. When game starts 3'rd player is just eliminated.

![image](https://github.com/vcmi/vcmi/assets/15194321/f579cb6b-783b-4d97-9679-14b19b1bb3b3)

**Comment by DjWarmonger** [comment]
Another variation of https://github.com/vcmi/vcmi/issues/2104

**Comment by DjWarmonger** [comment]
This template is just messed up.

Even in OH3 it supports 2 to 4 players, however only 2 players have defined starting zones.

Since it's symmetric, I decide to add missing config for players 3 and 4.

**Comment by SoundSSGood** [comment]
> This template is just messed up.

is it possible to add a check for messed up templates?

**Comment by DjWarmonger** [comment]
Not really. This parameter just has wrong name in json, as prameters in templates are different than settings in RMG GUI. Took me **a while** to figure it out.

**Comment by DjWarmonger** [comment]
Not really, as relationships between parameters are already convoluted on their own. And this problem in particular can have multiple solutions.
