### ISSUE TITLE
Archangels can cast on self

### ISSUE THREAD

**Issue by rilian-la-te** [vcmi/vcmi#2721]
**Describe the bug**
In OH3 they should not.

**Game logs**
Not applicable

**To Reproduce**
1. vcmiainur
2. kill some archangels in battle
3. Try to cast Resurrection on wounded stack
4. See casting cursor

**Expected behavior**
Archangels should not on self

**Actual behavior**
Archangels can cast on self

**Did it work earlier?**
Do not know

**Screenshots**
Not applicable

**Version**
 - OS: Linux
 - Version: beta

**Additional context**

**Comment by misiokles** [comment]
Self-casting would be nice feature btw :)

**Comment by by003** [comment]
I reckon this ability is good, similar as HoMM4 and HoMM5.
