### ISSUE TITLE
Incorrect values on a difficulty widget

### ISSUE THREAD

**Issue by wb180** [vcmi/vcmi#2724]
**Describe the bug**
Probably minor bug: incorrect values on a difficulty widget within saving screen

**To Reproduce**
1. Start any scenario
2. Open "Save game" 
3. Look at a difficulty widget

**Expected behavior**
difficulty widget has only one item (in OH3 currently active save file)

**Actual behavior**
it has two active items, one from selected save file and second from currently playing scenario

**Screenshots**

Saving screen:
![Screenshot_20230901_034111](https://github.com/vcmi/vcmi/assets/109801241/099171f8-de47-4425-993f-ac651d01defe)

**Version**
Latest develop

**Comment by wb180** [comment]
Regression from the fix of [#2540 ](https://github.com/vcmi/vcmi/issues/2540), works fine in beta.

And another bug, which also present in beta: In a saving screen difficulty icons remain active upon switching save files.
![Screenshot_20230901_110806](https://github.com/vcmi/vcmi/assets/109801241/a5274783-ed90-4ce0-9221-61c366743bf3)

**Comment by Nordsoft91** [comment]
@Laserlicht ^^

**Comment by Laserlicht** [comment]
Not really a regression. It only becomes visible through this PR.

It's basically the second bug you described.

**Comment by Povelitelh3** [comment]
related old bugtacker https://bugs.vcmi.eu/view.php?id=2616
