### ISSUE TITLE
VCAI is freezing when trying go through two way monolit

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#2725]
**Describe the bug**
Tan AI trying go through two way monolit and game is freezing

**To Reproduce**
Load save and press end turn

**Version**
 - OS: [e.g. Windows 10]
 - Version: [VCMI version is 1.4.0.c45ab07d0b45bf447b2adc8e69b020fbf4914aec current develop]

[monolits.zip](https://github.com/vcmi/vcmi/files/12495579/monolits.zip)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12495589/VCMI_Client_log.txt)
![изображение](https://github.com/vcmi/vcmi/assets/36762538/6992251f-f87e-4413-b951-12c60443330d)

**Comment by IvanSavenko** [comment]
@Nordsoft91 ?
I think there was same bug with Nullkiller recently?

**Comment by Povelitelh3** [comment]
Maybe I tried to load that save, but it's already too old. Therefore, it was not possible to check.

**Comment by Povelitelh3** [comment]
Yesterday, I figured out. It's not VCAI problem, NKAI has the same issue! It happens every time when AI trying move through two way monolit. (Created XL-U, 8 players)
