### ISSUE TITLE
Upper level folder is not first is saves list

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2729]
**To Reproduce**
1. Create a save in autosaves folder with name started _
2. Open load/save screen

**Expected behavior**
`... (Autosave/)` is first element in the list

**Actual behavior**
File with name started from _ is first in the list

**Did it work earlier?**
new feature

**Screenshots**
<img width="352" alt="Снимок экрана 2023-09-02 в 02 28 56" src="https://github.com/vcmi/vcmi/assets/9308612/0f014018-07c6-48c8-bb70-d1a64f0e7ff0">

**Comment by Nordsoft91** [comment]
@Laserlicht ^^

**Comment by krs0** [comment]
If touching that please keep in mind I've started https://github.com/vcmi/vcmi/issues/2561
CPlayerInterface::performAutosave() is heavily modified

**Comment by Laserlicht** [comment]
Can have a look.

@krs0 I don't think it's related to Autosave. The problem here is that with sorting "_" comes before ".". So we need a special case here.

**Comment by krs0** [comment]
If you could find a solution for this #2735 as well, would be better for autosaves.

**Comment by Laserlicht** [comment]
For me it's not really possible to get this error:

![grafik](https://github.com/vcmi/vcmi/assets/13953785/7757ffc7-1eb0-4134-807d-f1fa76079a7c)

**Comment by Laserlicht** [comment]
Ah, I think `boost::ilexicographical_compare` depends on locale...
