### ISSUE TITLE
Minimap is stretched for non-square maps

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2730]
**To Reproduce**
1. Start any non-square map 

[test_walking_water.vmap.zip](https://github.com/vcmi/vcmi/files/12503596/test_walking_water.vmap.zip)

**Expected behavior**
Minimap preserves proportions

**Actual behavior**
Minimap is stretched, objects look non-natural

**Screenshots**
<img width="190" alt="Снимок экрана 2023-09-02 в 02 43 03" src="https://github.com/vcmi/vcmi/assets/9308612/b2a30e1d-5b69-454d-b2cb-69fed30bf6f5">

**Comment by Laserlicht** [comment]
Maybe letterboxing?
