### ISSUE TITLE
Mismatch of Magics Skill levels to the Spellbook's spells levels

### ISSUE THREAD

**Issue by saaadel** [vcmi/vcmi#2732]
**Describe the bug**
Mismatch of Magics Skill levels to the Spellbook's spells levels (spells' corners count)

**Game logs**
logs: removed.

**To Reproduce**
1. I don't know, just start play for Necropolis with hero Vidomina (a random map or a randomized map in the editor).
2. Get some exp, and try to select preferably Air/Earth/Water/Fire Magic.
3. Get Expert levels in Magic skills and check the spell book.

**Expected behavior**
It should show correct level (corners counts) for spells if you have corresponding Magic skill.

**Actual behavior**
Hero has the "Expert Air Magic" Skill, "Expert Earth Magic" Skill, the "Expert Fire Magic" Skill, and NO "Water Magic" Skill
If you open its Spell book, then it shows 4 corners (the expert level) for spells in the Fire Magic (ok) and Water magic (why?!), 
and 1 corner (no level) for Air Magic and Earth Magic.
It repeats for Magic skills in **an every game**.

Note: 
It is not a visual issue — I have installed the mod, that defined the "mass haste" and other "Mass ***" spells. They work for expert magic skill only. I see it, I have the expert level of the magic skill, but it shows as "there are no level" in the spellbook, so those "mass ***" spells do not works for me.
It looks like the state that is displayed in the spell book is the actual status of having magical skills. And what we see in the list of skills is a kind of visual bug.

P.S. Please note: I have an expert level of three magics (skills), and spellbooks shows an expert level for only two types of magic. So here we have not just a mistake with the substitution of icons of different types of magic among themselves.

**Did it work earlier?**
I don't know - the latest version is the one I started trying to play VCMI.

**Screenshots**
<img width="1193" alt="Screenshot 2023-09-02 at 13 05 18" src="https://github.com/vcmi/vcmi/assets/1027379/dbd742d8-e190-454c-a240-8769b1c51e03">
<img width="1014" alt="Screenshot 2023-09-02 at 13 05 38" src="https://github.com/vcmi/vcmi/assets/1027379/85cf242b-600d-4e39-ae1e-5c340bc95ffa">
<img width="1031" alt="Screenshot 2023-09-02 at 13 05 44" src="https://github.com/vcmi/vcmi/assets/1027379/2f66114c-2290-41e9-968b-c427165c8d31">
<img width="1006" alt="Screenshot 2023-09-02 at 13 05 49" src="https://github.com/vcmi/vcmi/assets/1027379/a385d71c-f53f-4dae-9701-0d485ac4ae5a">
<img width="1088" alt="Screenshot 2023-09-02 at 13 05 53" src="https://github.com/vcmi/vcmi/assets/1027379/9626f14f-7db0-4886-9d63-9fee386619f3">

**Version**
 - iMac Intel 2019, macOS Ventura 13.5.1 (22G90)
 - Version: VCMI 1.3.1

**Additional context**
Nothing.

**Comment by krs0** [comment]
With only base game it looks ok. Most likely is from mod.

Expert air, advance fire, no water, no earth
![image](https://github.com/vcmi/vcmi/assets/15194321/8893c7c0-d6ad-4f5a-a2fb-b8bf10422747)

**Comment by rilian-la-te** [comment]
Mod can use subtypes from 1.2 in MAGIC_SCHOOL_SKILL. It was 1,2,4,8 and became 0,1,2,3 (to unify with other spell school bonuses)

**Comment by misiokles** [comment]
There were some issues with Andruids Spell Balance mod, but they were fixed. Please, uninstall and install this mod again. But changes will be applied in new game, unfortunatelly.

**Comment by saaadel** [comment]
Tested on vanilla (without Skill/Spell mods) — it's ok.
I will check it step-by-step adding those mods by one...

**Comment by saaadel** [comment]
It's broken on mods:
New Magic Balance v0.9 (Andruids)
- Enhanced Eagle Eye v1.1
- Mass Spells v0.9
- Spells Range v0.3
- Level 2 Slow v1.0

Tried with all mods above enabled — result: broken;
...and only with the root mod enabled — result: works.

So, I have checked inner mods step-by-step — it is broken on "- Enhanced Eagle Eye v1.1" mod only.
All other mods work.

**Comment by saaadel** [comment]
non-VCMI issue

**Comment by saaadel** [comment]
non-VCMI issue
