### ISSUE TITLE
Crash on end turn on SoD map: A Terrible Rummor

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2734]
**Describe the bug**
In this particular map, sometimes! in the first few 1-3 turns VCMI hangs on Green player. (green is not the last player)

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12503932/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12503933/VCMI_Server_log.txt)

![image](https://github.com/vcmi/vcmi/assets/15194321/ef106314-b6fc-476f-b1fd-abedf6d65a15)

**To Reproduce**
1. Start map A terrible Rummor
2. Click on end turn a few times
4. See hang on green player

It is not always guaranteed to reproduce!

**Version**
 - OS: [e.g. Windows, 
 - Version: [VCMI develop]

**Comment by Nordsoft91** [comment]
vcmi version?

**Comment by Nordsoft91** [comment]
should be fixed in next build

**Comment by by003** [comment]
It hangs on the map All for one from first turn, any times.
