### ISSUE TITLE
Cannot order save files based on time

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2735]
**Describe your proposal**
Sometimes you would like to order save files based on the last time they were made.

For example when using autosaves with rolling numbers this is crucial. Otherwise you will not know which is latest.

**Comment by Laserlicht** [comment]
A little bit complicated on GUI side. 

These are the current order buttons:
![grafik](https://github.com/vcmi/vcmi/assets/13953785/fcd8d193-f5fc-440e-80b4-635cac2db961)

Adding a new one isn't easy.

**Comment by krs0** [comment]
2 buttons on scenario name? one A-Z and the other Time?
