### ISSUE TITLE
Cannot load saved game

### ISSUE THREAD

**Issue by ZAK-2828** [vcmi/vcmi#2747]
Hi,
I played a random created map.
I saved at one point the game, but when I try to load that save, I have an error:

![obraz](https://github.com/vcmi/vcmi/assets/143937899/55c96101-d2ff-4726-b839-83c2ef99c264)

I use the latest version 1.3.1, and I started tha game at that version of the game.

What have to I do to load this saved game?

**Comment by misiokles** [comment]
I know it sounds silly, but try to DISABLE these mods.
