### ISSUE TITLE
Unformatted AI defeat message meant for human players shown

### ISSUE THREAD

**Issue by Alexander-Wilms** [vcmi/vcmi#2752]
**Describe the bug**
After defeating an enemy AI, the message shown is meant for human players and not formatted properly, still containing the placeholder %s.

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12507772/VCMI_Client_log.txt)

[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12507773/VCMI_Server_log.txt)

**To Reproduce**
1. Load save game after removing .txt extension: [_Android_Autosave.vsgm1.txt](https://github.com/vcmi/vcmi/files/12507782/_Android_Autosave.vsgm1.txt)
2. Attack and defeat enemy in nearest town

**Expected behavior**
Just the second message is shown: "Blue's heroes have abandoned him, and he is banished from this land"

**Actual behavior**
First, this message is shown: "%s, your heroes abandon you, and you are banished from this land.Blue"

**Did it work earlier?**
I think so

**Screenshots**
![Screenshot_20230903-232613.png](https://github.com/vcmi/vcmi/assets/3226457/84238794-262f-477e-87ef-9171e17646f5)

![Screenshot_20230903-232631.png](https://github.com/vcmi/vcmi/assets/3226457/699b61d7-2a70-4d01-9ac3-6fa6a9658120)

**Version**
 - OS: Android
 - Version: 1.3.1

**Additional context**

**Comment by IvanSavenko** [comment]
Already fixed in develop branch
