### ISSUE TITLE
Crash on all artifacts transfer

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2759]
**Describe the bug**

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Start any map
2. Open exchange dialog between 2 any heroes
3. Press pass all artifacts button

**Expected behavior**
No crash

**Actual behavior**
Game crash

**Did it work earlier?**
Regression

**Screenshots**

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: develop

**Additional context**

**Comment by SoundSSGood** [comment]
Not reproducible on last commit. A similar crash has already been fixed recently. Could you provide more details. What commit did you use?

**Comment by Nordsoft91** [comment]
confirm fix
