### ISSUE TITLE
High morale enables blinded stack to make another attack

### ISSUE THREAD

**Issue by wb180** [vcmi/vcmi#2762]
**Describe the bug**
Archangels got blinded from War Unicorns, but because of high morale still able to do another attack.

**Expected behavior**
Blinded stack can't make another attack.

**Actual behavior**
Blinded stack can do another attack.

**Did it work earlier?**
Don't know - never had such situation.

**Screenshots**
![Screenshot_20230905_134359](https://github.com/vcmi/vcmi/assets/109801241/dc2d8775-f38c-44d0-8f7d-a7ed5c012691)
![Screenshot_20230905_134434](https://github.com/vcmi/vcmi/assets/109801241/6b42916d-2c4e-4595-8ed4-e7ccff64b58e)

**Version**
Develop

**Comment by IvanSavenko** [comment]
Or, in other words - blinded stack should not be able to get morale
