### ISSUE TITLE
Incorrect victory/loss message

### ISSUE THREAD

**Issue by cewbdex** [vcmi/vcmi#2766]
**Describe the bug**
I have played a hotseat MP with friend and suddenly the game started telling to some of us that one of us lost, when we did a upgrade to units.

**Game logs**
[server_log.txt](https://github.com/vcmi/vcmi/files/12526974/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12526976/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12526977/VCMI_Server_log.txt)

**To Reproduce**
1. Load the [save file](https://github.com/vcmi/vcmi/files/12527011/VCMI.lose.bug.zip) with no mods installed (otherwise it doesn't load for some reason).
2. Select Fiona hero.
3. Go to Hill Fort just next to her.
4. Click on upgrade Imps button.
5. Cry.

**Expected behavior**
Upgrade Imps and continue in playing.

**Actual behavior**
Imps get upgraded and game ends.

**Did it work earlier?**
No

**Screenshots**
![obrazek](https://github.com/vcmi/vcmi/assets/9021297/3985aee4-97c4-4c02-887a-d6747f7adaf9)
![obrazek](https://github.com/vcmi/vcmi/assets/9021297/c878dca5-f4ba-46bf-9091-25fd70ee6235)

**Version**
 - OS: Fedora 38
 - Version: 1.3.1

**Additional context**
N/A

**Comment by Nordsoft91** [comment]
@cewbdex , you shouldn't cry if only you are not a green player, because victory condition for this map ("a warm and familiar place") is to accumulate 500 upgraded imps :)
After upgrade you have 507 so work as expected :)

**Comment by krs0** [comment]
@Nordsoft91 I am confused, what is with this message then?
I would expect something like Victory!! You have gathered 500 Familiars or something like that?

**Comment by Nordsoft91** [comment]
you know, I don't have ability to play OH3 on mac. So, if somebody can find out the expected behavior for this map from OH3, then we can think on solution

**Comment by krs0** [comment]
At the end of turn I get this message in HotA
![image](https://github.com/vcmi/vcmi/assets/15194321/0da8d33e-3b59-46f9-b7f7-ba1b03e6c73f)

**Comment by Nordsoft91** [comment]
@krs0 , could you please check if it's special message defined in map (I believe should be message on victory or something)?

**Comment by krs0** [comment]
![image](https://github.com/vcmi/vcmi/assets/15194321/a8831661-d8a7-4acb-8ffa-b747c4243b04)

**Comment by krs0** [comment]
GENRLTXT.TXT has it
Congratulations! You have over %d %s in your armies. Your enemies have no choice but to bow down before your power!

**Comment by Nordsoft91** [comment]
ok, seems like partial regression. In 1.2.1 we have this message

**Comment by cewbdex** [comment]
May be a silly question, but where I could find the information in-game, I could not find anywhere which and how much units to have.

**Comment by krs0** [comment]
I am not in front of PC, but I guess it should be under Scenario Information Button/window

**Comment by Nordsoft91** [comment]
Scenario info + first message when you start the map

**Comment by misiokles** [comment]
Similar issue?
https://cdn.discordapp.com/attachments/298110850420441094/1150904382062329896/20230911_232155.jpg
Incorrect string in tavern rumors.

**Comment by IvanSavenko** [comment]
Sounds like a different one

**Comment by cewbdex** [comment]
> Similar issue? https://cdn.discordapp.com/attachments/298110850420441094/1150904382062329896/20230911_232155.jpg Incorrect string in tavern rumors.

![obrazek](https://github.com/vcmi/vcmi/assets/9021297/e38f415a-78a3-42fc-bc24-b4e92dc4a36f)
This is physically present as string.
