### ISSUE TITLE
Game freezes at first start

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2792]
**Describe the bug**

**To Reproduce**
1. Install vcmi on a new device
2. Start launcher

**Expected behavior**
User is able to proceed with initial launch

**Actual behavior**
application freezes for a while

**Screenshots**

**Version**
 - OS: iOS
 - Version: 1.3.1

**Additional context**
as I understand, application is downloading mods' json immediately, which takes time and blocks initial setup screen

**Comment by IvanSavenko** [comment]
Fixed in #2761?

**Comment by Nordsoft91** [comment]
probably, cannot test, as this bug came from other user, who installed 1.3.1.
Will close for now then
