### ISSUE TITLE
Immediatelly exit on entering battle in Citadel

### ISSUE THREAD

**Issue by adam-tychoniewicz** [vcmi/vcmi#2794]
**Describe the bug**
Immediatelly exit on entering battle in Citadel

**To Reproduce**
1. Load game from file
2. Attack town

**Version**
 - OS: Android
 - Version: [VCMI version] nightly build https://builds.vcmi.download/branch/develop/Android/arm64-v8a/VCMI-branch-develop-e845391.apk
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12566716/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12566717/VCMI_Server_log.txt)
[gra.vsgm1.txt](https://github.com/vcmi/vcmi/files/12566720/gra.vsgm1.txt)

Please remove txt from saved game file

**Comment by IvanSavenko** [comment]
Fixed in #2780
