### ISSUE TITLE
Allow rewards for configurable objects to be random from a list

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2809]
EG: reward a random artifact from: "eversmokingRingOfSulfur", "ringOfInfiniteGems", "everpouringVialOfMercury", "everflowingCrystalCloak"

Same could be for creatures from a list.

There are more and more objects created. It is useful when creating an object to be able to restrict a little more the possibilities of the reward.

**Comment by Nordsoft91** [comment]
```json
{
"handler" : "configurable",
  ...
  "rewards" : [
    {"artifacts" : ["eversmokingRingOfSulfur"]},
    {"artifacts" : ["ringOfInfiniteGems"]},
    {"artifacts" : ["everpouringVialOfMercury"]},
    {"artifacts" : ["everflowingCrystalCloak"]},
  ]
  ...
  "selectMode" : "selectRandom"
}
```

**Comment by krs0** [comment]
So this works now?

**Comment by IvanSavenko** [comment]
No, it does not. This mode was never implemented, partially - because it is not used by H3 objects and partially - because there are better means to achieve same result (but not for artifacts)

**Comment by Nordsoft91** [comment]
Yes, it does. Implemented here https://github.com/vcmi/vcmi/pull/2101

**Comment by krs0** [comment]
Great will test this evening.

**Comment by IvanSavenko** [comment]
1. Thanks for actual PR descriptions:
> Only pieces of existing code were moved.
This PR doesn't imply improvements for existing code, only moving parts of it

2. Thanks for updating documentations when you make changes and not several months later
> "selectMode" : "selectFirst", "selectPlayer"

3. Thanks for creating largely duplicated functionality:
```jsonc
  "rewards" : [
    { "appearChance" : { "min" :  0, "max" : 25 }, "artifacts" : ["eversmokingRingOfSulfur"]},
    { "appearChance" : { "min" : 25, "max" : 50 }, "artifacts" : ["ringOfInfiniteGems"]},
    { "appearChance" : { "min" : 50, "max" : 75 }, "artifacts" : ["everpouringVialOfMercury"]},
    { "appearChance" : { "min" : 75, "max" : 100 }, "artifacts" : ["everflowingCrystalCloak"]},
  ]
  "selectMode" : "selectFirst"
```
This code works identically to random mode AND it works with `"canRefuse" : true` flag.
With `"selectRandom"` and `"canRefuse" : true` player will receive different reward on every visit


@krs0 
Feel free to try, but this approach is very copypaste-heavy - you need to copy-paste message and all other parts of rewards/limiters (if any)

**Comment by krs0** [comment]
I do not quite understand the implications of can refuse, but the example that Nordsoft presented looks much better. For one I can add an artifact and that is it. With appear chances I will need and go and reenter thebprobabilities.
Like all other overly complex configurations (EG: spell configs), could this be presented to the user in a simpler manner than it is implemented in code? An alias / short form of sorts?

**Comment by IvanSavenko** [comment]
> I do not quite understand the implications of can refuse

- visit object, get message to get everpouringVialOfMercury
- refuse
- press space, get message to get ringOfInfiniteGems
- select

Because selected artifact is randomized on every hero visit

**Comment by IvanSavenko** [comment]
> With appear chances I will need and go and reenter thebprobabilities.

True. It does gives more possibilities, such as weighted random or more complex randomization (Andruid had rather extensive randomization in his Crumbling Magic Well).

Some alias / shortcut would be nice to have though.


However in this particular case what we actually need is syntax like
```jsonc 
"artifacts" : [
    { "anyOf" : [ "eversmokingRingOfSulfur", "ringOfInfiniteGems", "everpouringVialOfMercury", "everflowingCrystalCloak" ] }
]
```
This is how other reward types are randomized, and does not requires copy-pasting rewards.

**Comment by krs0** [comment]
"artifacts" : [
    { "anyOf" : [ "eversmokingRingOfSulfur", "ringOfInfiniteGems", "everpouringVialOfMercury", "everflowingCrystalCloak" ] }]

This is even better!

**Comment by Nordsoft91** [comment]
@krs0 , closing issue?

**Comment by krs0** [comment]
Ivan's last proposal is the way it should be, and that one is not in. I will leave it open with low prio.
