### ISSUE TITLE
Battle doesn't end when a hero suicides with a spell

### ISSUE THREAD

**Issue by Warzyw647** [vcmi/vcmi#2824]
**Describe the bug**
In battle, a hero loses his last units to his own spell. This doesn't end the battle.

**Game logs**
Not sure if that would be useful, but I can repeat the problem with logging on if someone thinks that would be helpful.

**To Reproduce**
1. Start a map with Solmyr, Septiena or other hero with a multi-target spell
2. Leave everything except one or 2 units in town
3. Attack a neutral stack
4. Cast your spell in a way that kills all your remaining units

**Expected behavior**
The battle ends with a loss (or draw) after the spell kills our last unit.
If everyone dies on both sides, the battle should end with a draw (message "everyone died")

**Actual behavior**
The battle continues. Our last active unit gets a turn, even though it's dead, and then no other creature makes a move. The program doesn't hang or crash.
If everyone dies, the battle ends with a loss.

**Did it work earlier?**
Not tested on earlier versions

**Screenshots**
Animated picture with Solmyr when the last creature killed was the Commander
![image](https://github.com/vcmi/vcmi/assets/132299608/af7e566d-09d5-4d85-82f8-4e03fc46ca8b)
Combat start with Septienna, no mods besides VCMI extras, VCMI essentials and ZEfix:
![image](https://github.com/vcmi/vcmi/assets/132299608/b83c1aa3-995a-4f4d-abb5-2678a807b5b9)
After Death Ripple:
![image](https://github.com/vcmi/vcmi/assets/132299608/2c9b6d11-8483-464f-b9ac-c0942f129fc4)
After clicking 'Defend', 'Autocombat' and 'x' to close the game window:
![image](https://github.com/vcmi/vcmi/assets/132299608/29f75bb3-5ad8-46e9-9d9e-6e536ebe8ab8)

**Version**
 - OS: tested on Windows and Linux, problem occurs on both
 - Version: 1.3.1

**Additional context**
Problem occurs also with no mods besides the base ones VCMI extras, VCMI essentials and ZEfix

**Comment by krs0** [comment]
A save game would help a lot. Can you provide please? If not I will try to reproduce and make one.
Without mods.

**Comment by Warzyw647** [comment]
Here are some saves where the neutrals survive Death Ripple and hero dies,
one with vcmi extras, vcmi essentials and zefix,
the other one with just vcmi essentials mod.
[saves.zip](https://github.com/vcmi/vcmi/files/12640850/saves.zip)
I checked that when just the active stack dies, neutrals survive and the hero has another stack, the problem doesn't occur. The control is then correctly transferred to our next stack.

Okay, the defeat when both the hero and the neutrals die is actually correct. In OH3 it also results in a 'battle lost' screen.

**Comment by nullkiller** [comment]
I expect it no longer reproduces in 1.4 after battle rework. At list similar issue does not

**Comment by IvanSavenko** [comment]
Yeah, extremely likely to be fixed - we had a lot of workarounds for "hero casts spell and *** happens". All should no longer be necessary in 1.4
