### ISSUE TITLE
Error when trying to recruit with no available slot

### ISSUE THREAD

**Issue by cewbdex** [vcmi/vcmi#2831]
**Describe the bug**
When the town is full and I try to recruit an unit, game throws an error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Fully occupy a city
2. Try to recruit a unit that need another slot.

**Expected behavior**
Game does not allow recruiting or displays a message.

**Actual behavior**
Game throws an error.

**Did it work earlier?**
I don't know.

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/9021297/7eb3dc01-a9b5-48ad-8d07-4eaee09d25cf)

**Version**
 - OS: Fedora 38
 - Version: 1.3.1

**Comment by Laserlicht** [comment]
Old error. Client side check is not working

Additional information (OH3):
- On single recruit there is an message box
- On multiple recruit (HD mod) there is no information about not recruited units (silent)

Should be:
- single: like OH3
- multiple: message box that not all units are recruited

**Comment by by003** [comment]
I reckon we do not need any green words except 'cheater' in left corner. 
AI players often trigger this message as well. 
Human players can add a message box for this situation, but if AI trigger this, green messages should not be shown.

**Comment by misiokles** [comment]
I think `set hideSystemMessages `on option should be enabled by default.

**Comment by Laserlicht** [comment]
> I think `set hideSystemMessages on` option should be enabled by default.

Yes. For most users these messages are irritating. And the game still works correct.

**Comment by IvanSavenko** [comment]
I'd rather call these two separate issues:
- client sends invalid request instead of displaying clear error message to player
- release builds (as opposed to dev builds / daily builds) should have `set hideSystemMessages on` enabled
