### ISSUE TITLE
Empty line in launcher for stardust-terrain mod

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2849]
**Describe the bug**
![image](https://github.com/vcmi/vcmi/assets/15194321/c97d63a7-74f3-4d61-bff4-4fd415e7b576)

**To Reproduce**
1. Install 1.3.2
2. See empty line in launcher

**Version**
 - OS: [e.g. Windows,
 - 1.3.2

**Comment by misiokles** [comment]
I restricted stardust-terrain mod to "max" 1.3.1 because now stardust mod is part of new terrains pack and this solution is for old save. In 1.4 will be completelly removed.

**Comment by krs0** [comment]
ok but this should not show empty entry

**Comment by IvanSavenko** [comment]
@Nordsoft91 unintended effect from compatibility check changes?

@misiokles perhaps mark it as incompatible with 1.4 only? E.g. if player with 1.3.2 wants to finish game he started in 1.3.1

**Comment by misiokles** [comment]
How to mark this?

**Comment by misiokles** [comment]
Some time ago I've noticed similar empy line in repo, but it was gone because there was huge lag between repo changes and launcher refreshes.

**Comment by IvanSavenko** [comment]
@misiokles Good question actually...
What I was thinking about is something like:
```json
	"compatibility" :
	{
		"min" : "1.3.0",
		"max" : "1.4.0"
	},
```
But that would mean that "1.4.0" is compatible, which is not what we want here.

So probably something like this? Looks a bit weird but should work as intended:
```json
	"compatibility" :
	{
		"min" : "1.3.0",
		"max" : "1.3.9"
	},
```

**Comment by krs0** [comment]
what about 1.3.10? :)

If you do not know how many fixes would be, I would put it as :
```
	"compatibility" :
	{
		"min" : "1.3.0",
		"max" : "1.3.x"
	},
```

Having max : 1.4 will make people always wonder... is 1.4.0 supported? And I am afraid that is how it is now.

**Comment by misiokles** [comment]
In this case I'll remove this mod shortly as duplicate. Launcher should remove empty lines after some time.
