### ISSUE TITLE
Visual bugs with duplicating artifacts on Altar Of Sacrifice

### ISSUE THREAD

**Issue by wb180** [vcmi/vcmi#2852]
**To Reproduce**
See the gifs:
Case 1:
![1](https://github.com/vcmi/vcmi/assets/109801241/284f1407-01db-4c8b-9c31-7785f762d02f)

Case 2:
![2](https://github.com/vcmi/vcmi/assets/109801241/0042028e-a5fa-486f-9673-551a5f9b8b5f)

**Expected behavior**
Duplication shouldn't happen

**Actual behavior**
A lot of duplication and after you sacrificed actual artifacts, click on duplicated artifacts also gives an error:
![Screenshot_20230916_212247](https://github.com/vcmi/vcmi/assets/109801241/6e759ba4-50e7-4f44-8bdf-bc03825e19af)

**Version**
 - Version: Latest develop

**Comment by SoundSSGood** [comment]
Will fix soon
