### ISSUE TITLE
Crash during NKAI turn (1.3.2)

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#2862]
If you look at the map, the crash occurred during the battle for the mausoleum liches
Crash repeats from save

**Version**
 - OS: [e.g. Windows 10]
 - Version: [VCMI version 1.3.2]
 
mods only resourceful AI

[CrashSave.zip](https://github.com/vcmi/vcmi/files/12644867/CrashSave.zip)
[logs.zip](https://github.com/vcmi/vcmi/files/12644868/logs.zip)

**Comment by IvanSavenko** [comment]
Most likely already fixed in 1.4

**Comment by nullkiller** [comment]
Was not able to reproduce even in 1.3.2 MSVC build
