### ISSUE TITLE
The pointer was unsafely used before checking against nullptr

### ISSUE THREAD

**Issue by ProjectMutilation** [vcmi/vcmi#2863]
server/NetPacksServer.cpp:179
```
	bool allyTownSkillTrade = (pack.mode == EMarketMode::RESOURCE_SKILL && gh.getPlayerRelations(player, hero->tempOwner) == PlayerRelations::ALLIES);

	if(hero && (!(player == hero->tempOwner || allyTownSkillTrade)
``` 
The pointer hero was dereferenced on 179 line and checked against null on 181 line. Probably it's extra check
Version: [f8541d0ae]

**Comment by ProjectMutilation** [comment]
[0001-fixed-potential-nullptr-dereference.patch.txt](https://github.com/vcmi/vcmi/files/12648126/0001-fixed-potential-nullptr-dereference.patch.txt)
I think it's solution of this problem

**Comment by IvanSavenko** [comment]
No. In some conditions, hero can be null.

Will fix soon. Want to cleanup this code a bit first.
