### ISSUE TITLE
Map bonus selection doesn't work properly

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2870]
**Describe the bug**

**To Reproduce**
1. Select Paragon 2.0 map (perhaps could be on other maps, but noticed only there)
2. Open player settings tab
3. Press bonus 
4. Select gold/resources

**Expected behavior**
Bonus selected properly

**Actual behavior**
Gold sets artifact bonus
Resources sets gold bonus

**Did it work earlier?**
Idk

**Screenshots**
https://github.com/vcmi/vcmi/assets/9308612/4b9ac2d5-9faf-4ef0-85bd-51a037cedbfe

**Version**
 - OS: iOS
 - Version: develop (1.4)

**Additional context**
Not sure why artifact isn't offered - could be a bug but I think it's prohibited by scenario

**Comment by Nordsoft91** [comment]
@Laserlicht ^^

**Comment by Laserlicht** [comment]
What options do you have by selecting via arrows?
