### ISSUE TITLE
Quest Guard crashes the game on .vmap

### ISSUE THREAD

**Issue by madaosoul** [vcmi/vcmi#2888]
VCMI crashes on loading a .vmap format map that contains a Quest Guard object. There's no difference whether the map is ported from SoD or HotA, or made from scratch in VCMI editor.

Another problem is, there are no options to customise Quest Guard in VCMI map editor. I can see the formatting after porting it from SoD, but in the end, the outcome is the same - it crashes the game on .vmap format map.

I attach a simple map. It contains two towns and one Quest Guard put on VCMI editor, on 1.3.2 version. 
[questguard test.zip](https://github.com/vcmi/vcmi/files/12677943/questguard.test.zip)

**Comment by Nordsoft91** [comment]
Cannot reproduce on 1.3.2
Can you attach logs?

**Comment by madaosoul** [comment]
Oh, the HotA mod is probably at fault. I turned it off and the map indeed works. Now to find out what's the problem. 
[questguard test logs.zip](https://github.com/vcmi/vcmi/files/12683871/questguard.test.logs.zip)
