### ISSUE TITLE
When creature attacks while it's standing in a moat, sometimes it won't receive damage from moat

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2898]
**Describe the bug**
I can't tell when exactly, but during playing a second  PAH tournament map, creatures very often didn't get damage from moat, when they're already standing in it and attacking an adjacent monster.

**Expected behavior**
Creature standing in a moat should take damage after attacking an adjacent monster and it's counterattack.

**Version**
 - OS: [Windows 10]
 - Version: [VCMI 1.3.2]

**Comment by dydzio0614** [comment]
i think they should receive damage after, not before attacking

**Comment by krs0** [comment]
When testing moats, everything looked fine. 
Please note the correct behaviour of moats:

Moats cause damage to creatures when they enter the moat, or end a turn into one.

If this is note the case, please note what town it was or what creature was not affected.

**Comment by rilian-la-te** [comment]
@krs0 exactly what I want to say)

**Comment by HarkUhm** [comment]
![sc](https://github.com/vcmi/vcmi/assets/141812373/1dc929fe-f021-4e65-8541-99e29bfababb)

**Comment by rilian-la-te** [comment]
@HarkUhm is this occured for vanilla towns?

**Comment by IvanSavenko** [comment]
@rilian-la-te Can't think of any related changes.

**Comment by rilian-la-te** [comment]
@IvanSavenko so, let's wait to see if vanilla towns is affected. If not - certainly a mod issue.

**Comment by misiokles** [comment]
I saw thi gif before and I though it's missing damage hex in moat damage configuration. But Uhm said that this lower Pyro received damage only once, in first turn. Such things seem to be irrevelant to mods.

**Comment by rilian-la-te** [comment]
@misiokles it can be relevant to mods, if pyro just crosses a moat and stand on misconfigured hex. It need to be checked for vanilla towns, if bug will be confirmed - will spend weekend on this instead of BG3)

**Comment by misiokles** [comment]
This is quick check of Forge siege screen and battlefield grid. It seems to hexes 164 ad 181 in Forge's moat config are placed correctly.
![Bez nazwy](https://github.com/vcmi/vcmi/assets/29593042/b4c1e85f-e2c3-4b58-adb7-48788db83780)

**Comment by rilian-la-te** [comment]
@misiokles where are you checking? In moat spell page? Or in town page?

**Comment by misiokles** [comment]
In moat spell page. In vcmi-1.3 is the only place, that such hexes are defined.

**Comment by rilian-la-te** [comment]
Okay, so, we need to check if attack action inside moat triggers a moat spell.

**Comment by HarkUhm** [comment]
This issue occured on a few more hexes, so I guess it's not only a problem with a moat position. Chainsaw Zombies also for sure abused this bug during my gameplay.

**Comment by rilian-la-te** [comment]
@HarkUhm It happens with vanilla towns?

**Comment by HarkUhm** [comment]
I don't know, because there was no vanilla towns on recent tournament map ;) I will check it tomorrow.

**Comment by HarkUhm** [comment]
![ghghaa](https://github.com/vcmi/vcmi/assets/141812373/39eadb77-1e8f-461b-837e-238eace2e5ee)

**Comment by HarkUhm** [comment]
![ghghaaa](https://github.com/vcmi/vcmi/assets/141812373/dbb6502d-b3bf-458c-8528-1a898adcafe0)

**Comment by rilian-la-te** [comment]
@HarkUhm it always happens when creature only standing still? If creature moved at least 1 hex, it get moat damage?

**Comment by HarkUhm** [comment]
If creature will move one hex and attack, it will recieve damage. Creature has to attack rfom the same place to avoid damage.

**Comment by rilian-la-te** [comment]
@IvanSavenko is there an move handling change in 1.3 cycle? look like we do not calculate move before attack now.
