### ISSUE TITLE
When heroes are meeting in a town and one of them has a "scholar" skill, they won't exchange their spells

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2901]
**Describe the bug**
If you will summon a heroes meeting screen with a button on a townscreen, heroes won't exchange their spells despite having "scholar" skill

**Version**
 - OS: [Windows 10]
 - Version: [VCMI 1.3.2]

**Comment by kodobi** [comment]
Duplicate of #2878
