### ISSUE TITLE
After casting Chain Lightning creature can't move or battle can't be solved

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2904]
**Describe the bug**
This bug happened to me twice on second tournament map, but I can't reproduce it. The first situation is shown on gif below: after casting chain lightning, my commander died, but battle didn't end, I can't do anything, although game acted just like if I had one more creature:
![sciaa](https://github.com/vcmi/vcmi/assets/141812373/c29d16fa-fba8-49ab-9823-030c99f0810f)
Second time, after casting chain lightning some of my units died, but one of my units survived and it looked like it is it's turn, however game also didn't allow me to do anything, even after clicking auto-combet.

**Version**
 - OS: [e.g. Windows 10]
 - Version: [VCMI 1.3.2]

**Comment by nullkiller** [comment]
Reproduced as well on PAH map 2. Just load save, split hero army onions so that there are no more than 2 onions per stack, put samurai onions into 7th slot. Cast vcmiistari. Attack nearest familiars, wait samurai onions, cast Armageddon

**Comment by nullkiller** [comment]
Same mechanics causes same freeze on Arrogance map using same set of mods so looks generic issue.

**Comment by nullkiller** [comment]
Not reproducible in 1.4
