### ISSUE TITLE
Fog of war on game's start is different for VCMI and OH

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2905]
**Describe the bug**
VCMI:
![image (4)](https://github.com/vcmi/vcmi/assets/141812373/7a9d584c-3c2c-4bff-bd9b-11bacb6ca564)
![image (3)](https://github.com/vcmi/vcmi/assets/141812373/72985f83-fa5f-4eb3-969b-bcb485c1186e)
OH:
![image (5)](https://github.com/vcmi/vcmi/assets/141812373/b9755fc2-2b7e-46e0-896a-b4c7e29241ab)
![image (2)](https://github.com/vcmi/vcmi/assets/141812373/a8707249-0b74-4c55-80dd-7655566f1653)

**Version**
 - OS: [e.g. Windows 10]
 - Version: [VCMI 1.3.2]

**Additional context**
Map above is Metataxer's Revenge

**Comment by IvanSavenko** [comment]
Duplicate / related to https://github.com/vcmi/vcmi/issues/2248
