### ISSUE TITLE
Grail found in Crypt

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2906]
**Describe the bug**
Found this in Metataxer's Revenge map after defeating crypt. Only VCMI extras was applied:
![image (6)](https://github.com/vcmi/vcmi/assets/141812373/6b7ec1a1-e2f6-4bf0-a600-2cbf2d29e02b)

**Version**
 - OS: [Windows 10]
 - Version: [VCMI 1.3.2]

**Comment by IvanSavenko** [comment]
This map probably has all artifacts banned?

What happens in H3?

**Comment by HarkUhm** [comment]
All artifacts except the Ring of Life are banned. When Crypt is deafeated, player aquires the Ring
