### ISSUE TITLE
Big modal windows are getting cut

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2909]
**Describe the bug**
Metataxer's Revenge:
![image (8)](https://github.com/vcmi/vcmi/assets/141812373/eb6b3f0f-1bcc-43a6-9cf3-aafeac1d6933)
Should be:
![image (9)](https://github.com/vcmi/vcmi/assets/141812373/c13e50e3-44ad-427e-bd2b-896ea6cb6835)

**Version**
 - OS: [e.g. Windows 10]
 - Version: [VCMI 1.3.2]

**Comment by rilian-la-te** [comment]
It is a modal windows, not infoboxes.
