### ISSUE TITLE
If a spell is cast automatically after start of the battle and a player will click on a battlefield, it will break the game

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2911]
On "Good to Go" map with Pah3 second map tournament mods - armorer cast mass spell
![g232](https://github.com/vcmi/vcmi/assets/141812373/4c150bee-d934-4765-9c60-94730abe2426)

**Version**
 - OS: [e.g. Windows 10]
 - Version: [VCMI 1.3.2]

**Comment by IvanSavenko** [comment]
Not reproducible in 1.4/beta, presumably fixed
