### ISSUE TITLE
Button for replaying battle after win

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2915]
**Describe your proposal**
Sometimes even if I won battle, result doesn't satisfy me, it would be great to make button just like for quick battle, to replay battle once again manualy without going to loading menu. Hmmm, I didn't check it, but it might  be also an idea for replaying a lost battle if it wasn't implemented.

**Comment by Laserlicht** [comment]
Implemented as part of #3397

**Comment by vluchansky** [comment]
@Laserlicht once you replay the battle and win again, the button disappears — would be great to have it there every time

**Comment by Laserlicht** [comment]
> @Laserlicht once you replay the battle and win again, the button disappears — would be great to have it there every time

@vluchansky You have to enable unlimited replays in Extra Options in Scenario selection screen.
