### ISSUE TITLE
Crash in visiting a sea prison

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#2923]
Game crashed in visiting a sea prison in any hota map.

**Did it work earlier?**
It works well in 1.3.2, just occur in latest version after fixing hota map assets.
Map Daggerwin Valley cannot be opened in game either.
 
**Version**
 - OS: Windows
 - Version: 1.40

**Comment by krs0** [comment]
Looks like this is not related:
Map Daggerwin Valley cannot be opened in game either.

I cannot edit your issue, could you please split it in 2? Would be easier to track
