### ISSUE TITLE
More friendly bonus types

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2926]
[SPELL_DAMAGE_REDUCTION]
eg. golems

value - reduction in %
subtype - spell school; -1 - all, 0 - air, 1 - fire, 2 - water, 3 - earth

It will be clearer to write:
```
			"immuneToWater" :
			{
				"type" : "SPELL_DAMAGE_REDUCTION",
				"subtype" : "Water",
				"val" : 100
			}
```
then the current:
```
			"immuneToWater" :
			{
				"type" : "SPELL_DAMAGE_REDUCTION",
				"subtype" : 2,
				"val" : 100
			}
```

**Comment by rilian-la-te** [comment]
@krs0 it is already possible;

```
			"immuneToWater" :
			{
				"type" : "SPELL_DAMAGE_REDUCTION",
				"subtype" : "spellsSchool.water",
				"val" : 100
			}
```

**Comment by IvanSavenko** [comment]
@rilian-la-te We still have quite a lot of bonuses that use numeric sub ID's:
- ranged/melee/all damage
- land/sea/all movement
etc

**Comment by rilian-la-te** [comment]
Yes, but this issue was about spellSchool bonus)

**Comment by luk3ZPL** [comment]
Actually it is currently in the source docs: vcmi-develop\docs\modders\Bonus_Format.md
