### ISSUE TITLE
Empty persistent storage json file

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2927]
**Describe the bug**
I closed the game while loading and ended up with these warnings in console:
```
File <unknown> is not a valid JSON file!
At line 1, position 0 error: File is empty
```
actually in logs could be trace back to an empty persistent storage file:
```
TRACE global [1f9c] - loading C:\Users\krs\Documents\My Games\vcmi\config\persistentStorage.json
WARN mod [1f9c] - File <unknown> is not a valid JSON file!
WARN mod [1f9c] - At line 1, position 0 error: File is empty
```
Client warning could contain the name of the json file. 
File should be recreated if corrupted.

**Comment by Nordsoft91** [comment]
@Laserlicht ^^
