### ISSUE TITLE
Incorrect warnings in client console

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2928]
**Describe the bug**
```
Map thousand islands (allies): Has 'beat hero' as victory condition, but 'allow normal victory' not set. Ignoring
Map the devil and sir marcus v101: Has 'beat hero' as victory condition, but 'allow normal victory' not set. Ignoring
Map wings of war: Has 'beat hero' as victory condition, but 'allow normal victory' not set. Ignoring
Map thousand islands: Has 'beat hero' as victory condition, but 'allow normal victory' not set. Ignoring
Map good witch, bad witch: Has 'beat hero' as victory condition, but 'allow normal victory' not set. Ignoring
Map unholy quest: Has 'beat hero' as victory condition, but 'allow normal victory' not set. Ignoring
```
there is an error in assessing victory conditions.

**Version**
 - OS: [e.g. Windows,
 - Version: [VCMI develop

**Comment by krs0** [comment]
In this map ally hero defeats enemy hero and game ends as expected in OH3
![image](https://github.com/vcmi/vcmi/assets/15194321/ca0738db-7702-4f05-8f99-f8ea0ff3fb58)

[Modified Unholy Quest.zip](https://github.com/vcmi/vcmi/files/12707263/Modified.Unholy.Quest.zip)

**Comment by Nordsoft91** [comment]
what the bug about? Looks like expected behavior

**Comment by krs0** [comment]
Bug is that console lately is flooded with these warnings about wrong OH3 maps.
