### ISSUE TITLE
There is no possibility of checking the day and number of towns/players in the box in down right corner

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2929]
**Describe the bug**
OH shows these informations when clicked on castle or hero box in down right corner:
![affasd](https://github.com/vcmi/vcmi/assets/141812373/8816613a-3637-42a3-bbfe-e8dbbe5cbd3e)
![afafas](https://github.com/vcmi/vcmi/assets/141812373/d59b83ae-21b1-44fc-b0f0-35b8cd292020)
VCMI doesn't provide this info
**Version**
 - OS: [Windows 10]
 - Version: [VCMI 1.3.2]

**Comment by dydzio0614** [comment]
it is shown if creature management in this window is disabled, and since i do not think we aim for recreating "hd mod specific stuff" exactly as they are, i leave it to somebody else to decide if this should be treated as "bug" or "enhancement"

**Comment by rilian-la-te** [comment]
@dydzio0614 it should be allow to have a setting to switch quick army management off.
