### ISSUE TITLE
Launcher list a mod as needed by mod ID, but lists mod names

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2931]
**Describe the bug**
![image](https://github.com/vcmi/vcmi/assets/15194321/f9216bce-2ac6-4950-852d-ebe2612a9fef)

Use one or the other, consistently otherwise its hard to find a mod when id is different from name

**Comment by Nordsoft91** [comment]
barely possible to handle this, because required mod is submod, which is not reflected anywhere until mod is downloaded.

Possible solution would be to show dependency from parent mod:
`This mod can not be installed or enabled because the following dependencies are not present: New terrains pack`

**Comment by IvanSavenko** [comment]
In this case we need to use parent mod anyway - since in order to enable submod you need to install parent mod first.

Or (what we actually need) is to install dependency alongside with mod itself

**Comment by krs0** [comment]
I thought Install dependencies is how it works :)

For this usecase sugestion would be when mod id is not the same as mod name, to list both (one in brackets or something)

**Comment by IvanSavenko** [comment]
Mostly implemented in #4787. Now such mod will also show parent mod name.
Submod would still appear as mod ID since submods are not part of repository checkout by design.
