### ISSUE TITLE
When a dependent mod is installed but disabled, it should still be listed as missing dependency

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2933]
**Describe the bug**

New terrains mod is installed but disabled, still Tarnum that depends on it is shown as ok.
It should say that dependency is not installed or disabled

![image](https://github.com/vcmi/vcmi/assets/15194321/8371562a-bfb6-4034-8e49-e23d9a07d1c4)

**Comment by Nordsoft91** [comment]
Disagree, why we should prevent **downloading**?

**Comment by luk3ZPL** [comment]
Description should rather show the name of mod not just only submod of New terrain pack + message about disabled mod or even lew line: "Disabled required mods: " etc.

**Comment by krs0** [comment]
> Disagree, why we should prevent **downloading**?

Ok, did not think of that usecase. If that is the intention then ok. Will test with that flow in mind.
