### ISSUE TITLE
Crash when using castle guards to attack

### ISSUE THREAD

**Issue by pby5u** [vcmi/vcmi#2938]
**Describe the bug**
The game crashes instantly when the user tries to execute an attack with the castle guards. Watch the video to see.

**Game logs**
`Preparing interface for player tan
Player tan will be lead by Nullkiller
Opening Nullkiller
Loaded Nullkiller
Opening StupidAI
Loaded Stupid AI 0.1
Player 2 (tan) starting turn, day 35
Opening BattleAI
Loaded Battle AI
Call to loadBitmap with void fname!
Call to loadBitmap with void fname!
Error: Failed to find file 
Error: failed to load image 
Animation  failed to load
GetImage error: Request for frame not present in CAnimation! File name: , Group: 0, Frame: 0
/usr/include/c++/11.3.0/array:188: constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](std::array<_Tp, _Nm>::size_type) [with _Tp = unsigned int; long unsigned int _Nm = 187; std::array<_Tp, _Nm>::reference = unsigned int&; std::array<_Tp, _Nm>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Network error receiving a pack. Connection has been closed`

**To Reproduce**
1. Try to make an attack with the castle guards
2. Crash

**Expected behavior**
Attack is executed without crashing.

**Actual behavior**
Crash

**Did it work earlier?**
Didn't test.

**Screenshots**

https://github.com/vcmi/vcmi/assets/145902806/6f8fdcfd-f335-4a3f-a6cf-bccff01626d7

**Version**
 - Linux VCMI 1.3.2 flatpak version
 - HOMM3 complete from GOG

**Comment by nullkiller** [comment]
Tested recently and did not notice any problems using arrow towers

**Comment by IvanSavenko** [comment]
Closing, should be fixed after battle rework in 1.4
