### ISSUE TITLE
could map URI and minimap be changed in map info popup?

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2940]
It is not necessary to have map URI right after map name. The more important element are the minimaps, and then if you want that specific detail, you could check the map URI. 

Could it be changed so that is listed below the minimaps.

![image](https://github.com/vcmi/vcmi/assets/15194321/77042def-3ed3-4baa-8ed9-533db3dd2b1e)

**Comment by krs0** [comment]
@Laserlicht ? :)

**Comment by Laserlicht** [comment]
I'm glad you like the minimaps. :)

Yes, but the minimaps are optional (only for new game currently; can be disabled...).

And I think it looks better ("Pyramid" layout). Or not?

**Comment by Laserlicht** [comment]
@krs0 Done with: https://github.com/vcmi/vcmi/pull/2990
