### ISSUE TITLE
Allow modders to enter mod names in their original case

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2942]
I had this entry that matches 100% mod name casing: `"depends" : ["hota.mapObjects"]` (actual copy paste from VSCode)
but this is wrong, launcher expects everything lower case!

To make things worse it detected the mod up to some point! In this case the mod name is the correct one taken from the file.

![image](https://github.com/vcmi/vcmi/assets/15194321/52348008-3cc3-4ee3-913f-cb88e52da6dd)

For creatures I am expected to enter the correct casing otherwise errors.

Proposal: accept original casing.

**Comment by IvanSavenko** [comment]
We should convert all mod names to lower case internally from what I remember.
Probably conversion is missing in some case, e.g. dependencies
