### ISSUE TITLE
Color distortion on Windows 11 ARM

### ISSUE THREAD

**Issue by PuppetVaysa** [vcmi/vcmi#2946]
**Describe the bug**
Image color distortion, I've tried turning on various compatibility options but can't solve this problem.

**Screenshots**
![屏幕截图(7)](https://github.com/vcmi/vcmi/assets/8633108/eed7ca1f-5915-478c-bbcb-edfe2c438628)

**Version**
 - OS: [Windows 11 on ARM 22H2 22621.2283]
 - Version: [VCMI v1.3.2]

**Comment by kambala-decapitator** [comment]
try other video renderer, e.g. d3d

**Comment by PuppetVaysa** [comment]
> try other video renderer, e.g. d3d

It works, thanks
