### ISSUE TITLE
Problem in game with mouse disappearing and locking

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#2949]
**Describe the bug**
https://youtu.be/m84lO2gtjKs

I don’t know what happened, the develop didn’t touch it for a long time.
This usually happens after battles, I start walking as a hero and the game freezes. The mouse cursor disappears. Or I start walking after the AI moves and had same benavior.
I put a cursor in the launcher on both hardware and software, but it didn’t help.

There were no such problems in 1.3.2.
This thing prevents me from playing.

You can take save from here https://github.com/vcmi/vcmi/files/12715491/move.zip press end turn and after that to try make your turn. 
It can be arise unexpected ahy hero, any time. 
Try to make your move after AI.

**Version**
 - OS: [e.g. Windows 10]

[server_log.txt](https://github.com/vcmi/vcmi/files/12715707/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12715708/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12715709/VCMI_Server_log.txt)

**Comment by Povelitelh3** [comment]
The game does not respond to the keyboard or mouse.

**Comment by Povelitelh3** [comment]
I found a way to reproduce this.

Loading the save.
press the end of the turn.
on our turn, click on Shakti, then spacebar into the double-sided monolith.
We fight with gnols.
we start walking - freeze

**Comment by Nordsoft91** [comment]
confirm bug, steps:
 - enter any two-side monolith
 - press space
 - try to move hero

**Comment by Nordsoft91** [comment]
@IvanSavenko, regression from #2850, reproducible on https://github.com/vcmi/vcmi/actions/runs/6314184975 too
