### ISSUE TITLE
develop - when I try to load a save during a battle, the game crashes

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#2953]
Just start the battle and click load game

**Version**
 - OS: [e.g. Windows 10]
 - Version: [VCMI 1.4.0.b89fa254fcba6ac69f26f45fb84169bc714d78b9]
 - mingw-ubuntu 
[server_log.txt](https://github.com/vcmi/vcmi/files/12722833/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12722840/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12722842/VCMI_Server_log.txt)

**Comment by IvanSavenko** [comment]
Unfortunately can not reproduce it on my system. 
Can confirm that crash is reproducible on Windows builds though.
