### ISSUE TITLE
Can not make action - there is no battle ongoing

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#2954]
**Describe the bug**
Obvious low priority. These green messages spammed in game. 

**To Reproduce**
unpack zip file, load save and press end turn

**Version**
 - OS: [Windows 10]
 - Version: [VCMI version 1.3.2]

![GrnMsg](https://github.com/vcmi/vcmi/assets/36762538/662dd349-4c88-4e7c-bb7e-aa94c67ee697)
[SaveLogs.zip](https://github.com/vcmi/vcmi/files/12723878/SaveLogs.zip)

**Comment by IvanSavenko** [comment]
All such messages should be resolved in 1.4
