### ISSUE TITLE
This only happens to retreat town in vcmi 1.3.2

### ISSUE THREAD

**Issue by LordIofIThunder** [vcmi/vcmi#2956]
The game crash whenever i try to upgrade the jade dragons dwelling to silver dragons

This problem doesnt exist in vcmi 1.3.1

**Version**
 - OS: [android 12.Poco x3 Pro

https://github.com/vcmi/vcmi/assets/146068046/123a9cb0-9489-4372-9020-e73783849029

**Comment by IvanSavenko** [comment]
What mod is that?

**Comment by IvanSavenko** [comment]
Looks to be bug in mod:
` "dwellingUp2Lvl7" : { "animation" : "retreat/town-screen/buildings/TBELup2_7.def"`

However there is no such file in the mod.
Can somebody look into it? Whom should I ping? @Fabrice-TIERCELIN ? @misiokles ?

**Comment by misiokles** [comment]
Yeah, misiokles is fine to ping in such cases :) Looking into it now :)

**Comment by LordIofIThunder** [comment]
> Fixed.

Thank you!

**Comment by Fabrice-TIERCELIN** [comment]
I have forgotten to rename this file ^^

@misiokles, we can remove `TBELup2_6.def` file now

**Comment by Fabrice-TIERCELIN** [comment]
@LordIofIThunder, not to be blocked in your game in such a situation, if you want, you can:

1. Go to the [mod pages](https://github.com/orgs/vcmi-mods/repositories)
2. Search for your mod `retreat`
3. Go to the [mod page](https://github.com/vcmi-mods/retreat-town)
4. Click on [🕒 XX commits](https://github.com/vcmi-mods/retreat-town/commits/vcmi-1.3) link
5. Click on a previous link `<>` (not the last one)
6. Click on the green button `<> Code v`
6. Click on the entry _📁 Download ZIP_
7. Remove the folder of the corrupted mod in your folder `C:\Users\LordIofIThunder\Documents\My Games\vcmi\Mods` (like `retreat-town`)
8. Paste the folder of your town (like `retreat-town`) from the content of the ZIP file

This way, you will be able to play with an older version of the mod.
