### ISSUE TITLE
Spell turns should be shown in creature menu 

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#2961]
Like the same function here. It will be more convenient to show the time if in control. 
![image](https://github.com/vcmi/vcmi/assets/127420617/c5f1dc25-4934-4a06-808c-ec95c84c2298)

**Comment by by003** [comment]
![image](https://github.com/vcmi/vcmi/assets/127420617/3ca3c61c-22df-4f5d-802a-850b20727234)
If necessary, morale and luck can be shown as the figure as well.

**Comment by Laserlicht** [comment]
included in #3366
