### ISSUE TITLE
open-source engine for Heroes of Might and Magic IV

### ISSUE THREAD

**Issue by Brensom** [vcmi/vcmi#2962]
Why did you make the engine open only for this part of the game?
Are you considering doing this for Heroes of Might and Magic IV? This is my favorite part of the series.

**Comment by rilian-la-te** [comment]
Homm IV has many different rules than 3, and to write engine for HoMM IV we need to write a different project entirely.

**Comment by oleg-medovikov** [comment]
обидно что 4 часть умирает

**Comment by kambala-decapitator** [comment]
> обидно что 4 часть умирает 

Можешь написать движок для неё
