### ISSUE TITLE
gold overflow

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#2963]
to reproduce in adequate time: have lots of Ramparts with Treasury

reported in https://forum.vcmi.eu/t/gold-amount-overflow/6091, there's also video demonstrating the bug

Version: 1.3.2

**Comment by kambala-decapitator** [comment]
it's weird that gold (and probably other resources) are int32 instead of uint64

**Comment by IvanSavenko** [comment]
Such huge amount would overflow in UI, so not much point.
But yeah, should probably be int64 and have fixed limit - way below int64 max, to avoid overflows, but still high enough to not be reachable

**Comment by kambala-decapitator** [comment]
we can also apply short form similar to unit count: 10M, 1B etc.
