### ISSUE TITLE
Cannot buy heroes from adventure map tavern

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#2974]
**Describe the bug**
I wanted to buy a hero in an external tavern, but it didn’t work out. It gave an error : Can't buy hero in tavern not being visited!

**Version**
 - OS: [e.g. Windows10]
 - Version: [VCMI version 1.4.0.47a17cc4a7220c3611559bd40deee750a3073017]
[tavern.zip](https://github.com/vcmi/vcmi/files/12752128/tavern.zip)

**Comment by IvanSavenko** [comment]
Fixed in #2969

**Comment by Povelitelh3** [comment]
the external dwellings have also been fixed as far as I understand? to hire troops from there

**Comment by IvanSavenko** [comment]
Will recheck

**Comment by krs0** [comment]
Can you please rename the issue to something a little more clear like:
Cannot buy heroes from adventure map tavern.

There are 450 issues, having them as clear as possible will help with managing them.
