### ISSUE TITLE
Impossible to move from the monolith

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2979]
**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Move hero to 2-way monolith
2. Preview path where it needs to go back
3. Confirm move

**Expected behavior**
Hero moves

**Actual behavior**
Server complains

**Did it work earlier?**
1.4 regression

**Screenshots**
https://github.com/vcmi/vcmi/assets/9308612/4a6c2a69-73a6-4cf0-88f1-235912f9e23b

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: 1.4 nightly 

**Additional context**

**Comment by IvanSavenko** [comment]
Seems to be fixed now
