### ISSUE TITLE
`Revisit Object` button doesn't have a tooltip

### ISSUE THREAD

**Issue by Alexander-Wilms** [vcmi/vcmi#2984]
**Describe the bug**
The `Revisit Object` button doesn't have a tooltip

**Game logs**

**To Reproduce**
1. Start `All for One`
2. Hover over `Revisit Object` button

**Expected behavior**
A tooltip like the one of the `Next Hero` button

**Actual behavior**
No tooltip

**Did it work earlier?**
Probably not

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/3226457/43e5c0df-1eaa-4f38-af6a-ad85821149e0)

**Version**
 - OS: Wine on openSUSE Tumbleweed
 - Version: VCMI 1.4.0.0b9eb25c1326105d6ed647a277997158ce32211b

**Additional context**

**Comment by krs0** [comment]
Yes! I get it, because its next to Next Hero and you are standing in a town .... :)

The purpose for that button is to revisit object (Space key)

Does not mean it should not have a tool tip.

But please change issue title as well :)

**Comment by Nordsoft91** [comment]
Also noticed, neither tooltip nor help available (right click)

**Comment by Laserlicht** [comment]
Fixed in mod - please update :)
