### ISSUE TITLE
Snake beares can't cast poison after they attack

### ISSUE THREAD

**Issue by LordIofIThunder** [vcmi/vcmi#2994]
**Describe the bug**
They have 100% chance to cast poison at both range/melee attack but they don't.

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Just get in a fight with AI/player
2. And use your range/melee attack
3. And you will see it didn't cast any poison 
4.You need "retreat town"mod to reproduce!
**Expected behavior**
They should be capable to cast poison after every attack.

**Actual behavior**
They don't cast poison at both range/melee attack

**Did it work earlier?**
Probably

**Screenshots**

**Version**
 - OS: [e.g.,Android 12, ]
 - Version: [VCMI1.4.0.b89fa254fcba6ac69f26f45fb84169bc714d78b9]

**Additional context**
https://github.com/vcmi/vcmi/assets/146068046/809d06a5-d5b2-4b25-a379-6a1a43fff68a

**Comment by misiokles** [comment]
Strange, they should cast poison only after melee attack. Must check.

**Comment by LordIofIThunder** [comment]
The elite lizard warriors from wog can cast both melee/range.But the snake beares neither at both.

**Comment by LordIofIThunder** [comment]
Sorry.Doesn't matter anymore it seem that they could at melee.I thought that if they can't cast at range they can't cast at melee too.But can you make them cast also at range?please!

**Comment by LordIofIThunder** [comment]
https://github.com/vcmi/vcmi/assets/146068046/8a9001b1-10e1-47a9-8074-9b84b247339f

**Comment by misiokles** [comment]
It will be too strong unit. But you can do it yourself in simple way.
Open Maikom.json file (config/retreat/creatures folder) in any text editor and change line
`"addInfo" : [0,2]`
into 
`"addInfo" : [0,0]`
then save file. That's all

**Comment by LordIofIThunder** [comment]
Thank you sir🥰
