### ISSUE TITLE
Antivirus alert

### ISSUE THREAD

**Issue by vodkodav** [vcmi/vcmi#2999]
**Describe the bug**
The antivirus issues a warning if you scan the release VCMI-1.3.2-Windows.exe or zip.
Virtotal scan results https://www.virustotal.com/gui/file/f7e59a542dc09d1c85db19714e1c6a1693881ba8f9545f7c05f9d5c732e3db1d/detection
https://www.virustotal.com/gui/file/4168ed04e01e4dd50256001bf6c4ee5ed41073821cc4cdce20d76e3f34635633

**Game logs**
The problem occurs before installation or startup.

**To Reproduce**
1. Go to https://github.com/vcmi/vcmi/releases/tag/1.3.2
2. Download VCMI-1.3.2-Windows.exe or VCMI-1.3.2-Windows.zip
3. Go to https://www.virustotal.com/
4. Upload VCMI-1.3.2-Windows.exe or VCMI-1.3.2-Windows.zip file
5. Check scanning result

**Expected behavior**
Scanning resullt: No security vendors and no sandboxes flagged this file as malicious

**Actual behavior**
Scanning resullt: 3 security vendors and no sandboxes flagged this file as malicious

**Did it work earlier?**
1.1.1 is ok, in later versions the antivirus issues a warning

**Version**
 - OS: Windows
 - Version: 1.3.2

**Comment by IvanSavenko** [comment]
False positive due to heuristics.
We do a lot of _very scary_ stuff like not having a signature, requiring admin access for install or opening network connections.

In theory we could try contact developers of these antiviruses and report it but most likely too much pain.

**Comment by psyhlo** [comment]
nod32 doesn't recognize it as virus while download and/or install so everything must be ok?

**Comment by Nordsoft91** [comment]
Interesting, that 1.1.1 is ok but later isn't. Multiplayer and other dangerous stuff was since 1.1 or earlier. Could be first launch functionality? Also, iirc, we changed logs directory in 1.2

**Comment by IvanSavenko** [comment]
> Interesting, that 1.1.1 is ok but later isn't. Multiplayer and other dangerous stuff was since 1.1 or earlier. Could be first launch functionality? Also, iirc, we changed logs directory in 1.2

That's when we changed toolchain from MXE+gcc to ubuntu+mingw

**Comment by Nordsoft91** [comment]
No virus detected on develop builds
