### ISSUE TITLE
Hypnotize causes game crashes.

### ISSUE THREAD

**Issue by SparrowJacek** [vcmi/vcmi#3003]
**Describe the bug**
The game sometimes crashes when using Hypnotize spell, a crash window appears and VCMI terminates when "OK" button is pressed.

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12790514/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12790515/VCMI_Server_log.txt)

**To Reproduce**
1. Enter a battle
2. Cast Hypnotize on turn 1
3. Cast Hypnotize once more on turn 2 (it is enough to hover the cursor over any enemy stack)

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/7533826/d4c59589-4a60-4c9e-857a-6c09d048b2d4)

**Version**
 - OS: Windows 10
 - Version:  1.3.2
 - PAH3 Singleplayer Tournament map 3 required mods installed

**Additional context**
Save game provided in attachments, enter a battle with Astral and try to hypnotize 1st stack of dragonflies, then 2nd stack.
[hypnotize_bug.zip](https://github.com/vcmi/vcmi/files/12790543/hypnotize_bug.zip)

**Comment by Warzyw647** [comment]
Hovering over a corpse also causes a crash.

**Comment by Warzyw647** [comment]
AI doesn't seem to matter as the crash occurs both with BattleAI and StupidAI.

**Comment by Warzyw647** [comment]
If the battle is against an enemy hero, then trying to target anything with a spell during the opponent's turn results in this yellow message in the console:
"You can't check if enemy can cast given spell!"

**Comment by nullkiller** [comment]
Was able to cast hypnothize more than once  onto same stack

**Comment by nullkiller** [comment]
Hypnotize crashes in 1.3.2 when you attempt to cast a spell from spell book while fighting against neutrals and its neutral units turn but it is hypnotized so your turn. So active stack side is different from active player side.

**Comment by nullkiller** [comment]
BaseMechanics::BaseMechanics()

caster = event->getCaster();

returns nullptr
