### ISSUE TITLE
Cartographer not disabled on random maps

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#3004]
Maybe HotA only feature, but Cartographer should be disabled by default on RMG.

Here one from Jebus Cross with HotA mod enabled.

![image](https://github.com/vcmi/vcmi/assets/15194321/402d4603-168e-413e-beba-ab099fd35d41)

**Comment by Alucard648** [comment]
I think, Cartographer`s map prices should use H5 formula.

**Comment by IvanSavenko** [comment]
Hota only feature at the moment. So works as designed I guess?

**Comment by krs0** [comment]
HotA was on! So is this moddable? Or needs to be hardcoded somewhere?

**Comment by krs0** [comment]
Solved for almost all disabled objects
https://github.com/vcmi-mods/horn-of-the-abyss/pull/64
