### ISSUE TITLE
Add a new field to objects: Description

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#3009]
**Describe your proposal**
Some objects are pretty cryptic only from name alone. EG: `Shrine of Magic Thought.`
HotA addressed this by adding a description along with name: `Teaches level 4 spells`.

This would come in handy for Warehouses, windmills, etc.

A new optional field for objects: Description would help with this.

This could be a Gui improvement hidden behind a setting.

**Comment by by003** [comment]
I have a proposal to add unique description for all banks, like dragon utopia and shipwreck. Now all banks cannot create a description.

**Comment by IvanSavenko** [comment]
- Implemented in #2988
