### ISSUE TITLE
(Minor) Incorrect info on a right-click popup on random starting town/hero

### ISSUE THREAD

**Issue by wb180** [vcmi/vcmi#3029]
**Describe the bug**
Right-click popup shows incorrect info for random town/hero (see screenshots)

**Game logs**
Not needed

**To Reproduce**
1. New game
2. Choose any scenario with random starting town/hero
3. Advanced options
4. Right click on random icon

**Expected behavior**
No creatures or hero specialty should be displayed

**Actual behavior**
Random hero -> popup shows archery as a hero specialty
Random town -> popup shows castle creatures as associated creatures

**Did it work earlier?**
Probably not, I assume it's a new feature

**Screenshots**
![Screenshot_20231008_201057](https://github.com/vcmi/vcmi/assets/109801241/99ee3d09-683b-4c65-bc2b-db8d3a5ad08b)
![Screenshot_20231008_201020](https://github.com/vcmi/vcmi/assets/109801241/5a4fb963-6088-4346-b3f3-a25fd29d6bb4)

**Version**
 - Version: Latest develop

**Comment by Laserlicht** [comment]
@IvanSavenko Regression of this? #2973
