### ISSUE TITLE
Add "Show random maps" functionality

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#3048]
**Describe your proposal**
The button Show random maps has no functionality in VCMI.
It should show a list with all random maps generated. In HotA each random map is saved in random_maps folder.

![image](https://github.com/vcmi/vcmi/assets/15194321/7f458c6d-15b9-416a-9210-f4034e44ad60)
![image](https://github.com/vcmi/vcmi/assets/15194321/ada16830-78a3-4524-8575-b62c1c1e8953)

**Comment by by003** [comment]
Now random maps can only be used once after created, I think it should be saved and be allowed to edit as well.
I really hope we can have a campaign editor.
