### ISSUE TITLE
AI should not escape from battle that would result in his defeat

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3058]
AI can escape while in the fort, as if standing outside. Even if this is his last hero and last city. (In principle, the last hero cannot escape if you do not have cities)

[garrison, ally and hotkeys.zip](https://github.com/vcmi/vcmi/files/12909159/garrison.ally.and.hotkeys.zip)
I just attack, press the wait, and the hero runs away

**Comment by by003** [comment]
Actually it only occurs in stronghold, with an escape tunnel.

**Comment by IvanSavenko** [comment]
Does not seems to be a bug - it is completely possibly to escape from stronghold with Escape Tunnel built.

So the only possible issue is that AI should not retreat in this scenario.

**Comment by Povelitelh3** [comment]
the conversation is not about a tunnel, but about any fort without a tunnel.

**Comment by IvanSavenko** [comment]
Was not able to reproduce that

**Comment by Povelitelh3** [comment]
what I do wrong? https://youtu.be/NI0ESKpYsvk

**Comment by IvanSavenko** [comment]
Ah, this is town without fort.
I think we actually check for presence of walls, e.g. built fort. Will recheck
