### ISSUE TITLE
Blinded/Paralysed/Petrifaction creatures can still in active if morale triggered

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#3060]
If a creature hit unicorn/basilisk/scopicore, and blind/paralyse/petrifaction triggered in a retaliate action, it freezes.
However, if blind/paralyse/petrifaction triggered, and then morale triggered as well, it is still active for current turn. 

**Version**
 - OS: Windows
 - Version: 1.3.2

**Comment by IvanSavenko** [comment]
Fixed in 1.4
