### ISSUE TITLE
Manually installed mods should not be enabled by default

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#3061]
**Describe the bug**
I copy a mod from another source locally to mods folder. This mod has dependencies that are not present in mods folder yet! But the launcher shows it as Enabled!?

Local mods should be discovered and listed, but enabled only upon explicit user action. Verifying all dependencies.

**Comment by nullkiller** [comment]
It worked like this for ages. Not sure it is a bug.

**Comment by IvanSavenko** [comment]
Yeah. The only bug I see here is that mods with missing dependencies show up as enabled in Launcher.

Strictly speaking, this is leftover from pre-launcher times when player had no UI to enable/disable mods. But don't see what's wrong with this approach.

**Comment by nullkiller** [comment]
Might be an optional feature. But to implement it some code has to be changed as we treat mods as enabled by default.

**Comment by DjWarmonger** [comment]
Dropping mods into mod folder without any verification is easier and faster for development, **especially** if there are some missing or bugged dependencies. Launcher may not always detect them correctly and failt to enable (or disable) mod at all.

**Comment by IvanSavenko** [comment]
Closing.
Now such mods should show their active/inactive status correctly.
But mods are enabled by default by design, to ease manual installs
