### ISSUE TITLE
Can't change the language

### ISSUE THREAD

**Issue by D10N022** [vcmi/vcmi#3066]
![Στιγμιότυπο οθόνης (3)](https://github.com/vcmi/vcmi/assets/148078395/3355d3e5-d3ec-40d0-b44a-ee470ad1f602)
even though I have set the language on english(for both vcmi language and in game language) when I start heroes all the mods work properly but the language is not in english, it is on Arab or something like that. Can someone help me because I can't enjoy the game like that

**Comment by IvanSavenko** [comment]
Hi.
1) Can you upload VCMI_Client_log.txt from Documents/My Games/vcmi directory?
2) Can you tell language of your Heroes 3 copy?

**Comment by misiokles** [comment]
It's wise to read what given mod does. It's not Arab language - it's erathian font mod (language used in Erathia). Just disable it.

**Comment by by003** [comment]
Actually it is still English, but it changed all alphabets to another one.

**Comment by D10N022** [comment]
Turns out it was a mod that changed the font. Thanks for interesting

Στις Δευ 16 Οκτ 2023, 18:28 ο χρήστης Ben Yan ***@***.***>
έγραψε:
