### ISSUE TITLE
normalize line endings

### ISSUE THREAD

**Issue by josch** [vcmi/vcmi#3073]
Hi,

currently, some of the source files use \n and others use \r\n line endings. This causes problems for example when using git-format-patch when two files in the patch have different endings. Could the source files in vcmi be changed such that only one type of line endings is used? Currently the situation is as follows:

```
josch@reform:~/git/vcmi$ find -type f -print0 | xargs -0 file | grep 'ASCII text, with CRLF line terminators$' | wc -l
302
josch@reform:~/git/vcmi$ find -type f -print0 | xargs -0 file | grep 'ASCII text$' | wc -l
1584
```

Would you accept a pull request that converts the remaining files to the LF line terminator?

**Comment by IvanSavenko** [comment]
Hi. Should be OK I think, so feel free to submit such PR.
