### ISSUE TITLE
Game Crash After First Turn of Griffin Cliff

### ISSUE THREAD

**Issue by danapplegate** [vcmi/vcmi#3076]
**Describe the bug**
After playing the first turn of the Griffin Cliff campaign scenario, the game promptly crashes after the two AIs take their turn.

**Game logs**
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12988676/VCMI_Server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12989268/VCMI_Client_log.txt)
[system_report.txt](https://github.com/vcmi/vcmi/files/12988752/system_report.txt)
[server_log.txt](https://github.com/vcmi/vcmi/files/12988754/server_log.txt)

Save file on Google Drive: [Autosave_1.vsgm1](https://drive.google.com/file/d/1JRhDCt1gxP94zfw424juCCEUrRx5Ti3L/view?usp=sharing)

**To Reproduce**
1. Load the Autosave_1 game file
2. Click end turn
3. After AI's turns, the game crashes

**Expected behavior**
Game should not crash

**Actual behavior**
Game crashed

**Did it work earlier?**
I have not been able to get past this first 

**Screenshots**

**Version**
System report attached
 - OS: macOS 11.7
 - Version: VCMI 1.3.2

**Additional context**
Let me know if I can help investigate, I'm a software engineer and keen to help this project in any way I can. Thank you for your hard work in preserving this incredible game!

**Comment by IvanSavenko** [comment]
Looks to be caused by AI:
```
Thread 14 Crashed:: AIGateway::makeTurn
0   libNullkiller.dylib           	0x0000000120a71b58 NKAI::Goals::UnlockCluster::toString() const + 40
1   libNullkiller.dylib           	0x0000000120a38ec1 NKAI::Goals::Composition::toString() const + 385
2   libNullkiller.dylib           	0x0000000120a39122 non-virtual thunk to NKAI::Goals::Composition::toString() const + 18
3   libNullkiller.dylib           	0x0000000120a7aca2 NKAI::Nullkiller::makeTurn() + 6146
4   libNullkiller.dylib           	0x0000000120ae06c9 NKAI::AIGateway::makeTurn() + 569
5   libboost_thread.dylib         	0x000000010a296a32 boost::(anonymous namespace)::thread_proxy(void*) + 146
6   libsystem_pthread.dylib       	0x00007fff203b48fc _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff203b0443 thread_start + 15
```

**Comment by nullkiller** [comment]
Does it crash always or only this particular autosave?

**Comment by nullkiller** [comment]
Can not reproduce. Might be fixed already

**Comment by danapplegate** [comment]
Yes, still experiencing this crash on this particular save, latest VCMI version 1.3.2.

I'm not sure how to test if it always crashes, outside of the autosave. Do you mean I should replay the Erathia campaign and see if I get this same crash on the third scenario again, with a different set of variables?

**Comment by nullkiller** [comment]
You can not open this save in 1.4 unfortunately because of compatibility and 1.3.2 is not going to be updated. So we have no way to test this.

**Comment by nullkiller** [comment]
Interesting that on windows on my custom build I am not experiencing this crash.

**Comment by nullkiller** [comment]
In 1.4 it should be fixed. But 1.4 is not in playable state yet

**Comment by nullkiller** [comment]
Ok here is that fix I believe should fix this issue. https://github.com/vcmi/vcmi/pull/3138
You can take macos build from it and test if you like.

**Comment by danapplegate** [comment]
@nullkiller Confirmed! Loading the game using the build from that PR resolved the issue. Thanks!
