### ISSUE TITLE
Error when loading map

### ISSUE THREAD

**Issue by ApocalypticDoomsayer** [vcmi/vcmi#3079]
**Describe the bug**
Cannot load a map that I worked on. 

**Game logs**
[VCMI_mapeditor.exe_crashinfo.dmp](https://github.com/vcmi/vcmi/files/13045009/VCMI_mapeditor.exe_crashinfo.dmp)

1. In map Editor, Go to 'File'
2. Click on 'Open'
3. See error

**Expected behavior**
It should load the map.

**Actual behavior**
I get the error message seen in the screenshot below.

**Did it work earlier?**
I was able to load my map before.

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/148473849/5341214c-5d74-4e93-8e06-681b9d9c036b)

**Version**
 - OS: Windows 10 PRO
 - Version: 1.3.2

**Additional context**
The map editor crashed after I toyed with the copy-paste of multiple selection (I will report it in another thread). And when i loaded it, this happened.
I should mention that I have quite some mods, but I only used decorations.

Is there any way to retrieve my map? I simply cannot load it.

**Comment by IvanSavenko** [comment]
Closing, old and not reproducible. Feel free to reopen if this might still be relevant.
