### ISSUE TITLE
Pink shadow on multiple objects

### ISSUE THREAD

**Issue by ApocalypticDoomsayer** [vcmi/vcmi#3081]
**Describe the bug**
Not sure if this is 'reportable' since it is related to a MOD object and not an original object, so please close the bug if you consider so.

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/148473849/74844222-ffc8-4198-a43b-2ba5442e5058)

**Version**
 - OS: Windows 10 PRO
 - Version: 1.3.2

**Comment by Nordsoft91** [comment]
hota objects, seen this too
