### ISSUE TITLE
Cannot move hero, destination player is busy! (Error with simultaneous turns)

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3099]
![изображение](https://github.com/vcmi/vcmi/assets/36762538/9204f866-7a5b-4299-8aa6-4d68b4f6749c)
latest develop 1.4.0.3880ea58b946b7e7e8b2d6c2f41336a4fe146937 mingwUbuntu

Simultaneous turns are enabled on this map. I saw this error once on a random map.
Occurs when attempting to attack an enemy hero.

[MapAndSave.zip](https://github.com/vcmi/vcmi/files/13068038/MapAndSave.zip)

**Comment by IvanSavenko** [comment]
Kind of works as intended.
Player-player interaction during simultaneous turns is currently blocked.

However simultaneous turns should have aborted before this happened. Possibly our reachability detector failed to detect that player contact is now possible

**Comment by IvanSavenko** [comment]
Should be fixed / way less common in 1.4.5
