### ISSUE TITLE
App Crashes on iPadOS 17 After Installation and Displaying Logo

### ISSUE THREAD

**Issue by 109677436** [vcmi/vcmi#3104]
**Describe the bug**
After signing the IPA and installing it on my iPadOS 17, when I try to open it, I see the logo briefly, but then it crashes. Even after adding the map, data, and mp3 files to VCMI using Mac's Finder, I still face the same issue, where I see the logo and then it crashes. Is this due to an issue with my signing and installation method, or is it because iPadOS 17 is too new for it?

**Game logs**
N/A

**To Reproduce**
Install the IPA on iPadOS 17.
Open the application.
Observe the logo display.
Experience the crash.
Expected behavior
I expected the application to launch and run smoothly.

**Actual behavior**
The application briefly displays the logo and then crashes.

**Did it work earlier?**
I'm unsure if it worked previously, as I'm using the latest version of iPadOS17.

**Screenshots**

**Version**
 - OS: iPadOS17.1
 - Version: 1.3.2

**Additional context**
I suspect that the issue may be related to the signing and installation process or the compatibility with the latest iPadOS 17.

**Comment by kambala-decapitator** [comment]
I know that currently there's an issue with uploading apps with Xcode 15. Could you try Xcode < 15 or AltStore? Are you on macOS Sonoma btw?

**Comment by kambala-decapitator** [comment]
please also check if there're any crash logs generated, you can see them in Xcode or on device Settings - Privacy - Analytics - Analytics data - find VCMI with the date of crash

**Comment by 109677436** [comment]
`
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: AC25F2C1-9EB9-4152-996F-76CE3D9D5271
CrashReporter Key:   bf783df93038a467a5cb3af01183c201df6ec0e8
Hardware Model:      iPad8,11
Process:             vcmiclient [1037]
Path:                /private/var/containers/Bundle/Application/31BD795E-A06E-437E-8ACC-5F8BFF5ABF1E/vcmiclient.app/vcmiclient
Identifier:          435Q83WCM3.eu.vcmi.vcmiclient
Version:             1.3.2 (2023-09-14-09d9099)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           435Q83WCM3.eu.vcmi.vcmiclient [637]

Date/Time:           2023-10-25 10:11:01.5941 +0800
Launch Time:         2023-10-25 10:11:01.5608 +0800
OS Version:          iPhone OS 17.1 (21B5045h)
Release Type:        Beta
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/libvcmi.dylib
Referenced from: <00120886-F2C2-3DF0-B186-9BECBAB4E8FE> /Volumes/VOLUME/*/vcmiclient.app/vcmiclient
Reason: tried: '/private/var/containers/Bundle/Application/31BD795E-A06E-437E-8ACC-5F8BFF5ABF1E/vcmiclient.app/Frameworks/libvcmi.dylib' (code signature in <53EBAC7B-6331-3556-A879-58AB4FA2AA64> '/private/var/containers/Bundle/Application/31BD795E-A06E-437E-8ACC-5F8BFF5ABF1E/vcmiclient.app/Frameworks/libvcmi.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/private/var/containers/Bundle/Application/31BD795E-A06E-437E-8ACC-5F8BFF5ABF1E/vcmiclient.app/Frameworks/libvcmi.dylib' (code signature in <53EBAC7B-6331-3556-A879-58AB4FA2AA64> '/private/var/containers/Bundle/Application/31BD795E-A06E-437E-8ACC-5F8BFF5ABF1E/vcmiclient.app/Frameworks/libvcmi.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned?
(terminated at launch; ignore backtrace)

Highlighted by Thread:  0

Backtrace not available

No thread state (register information) available

Binary Images:
Binary images description not available

Error Formulating Crash Report:
_dyld_process_info_create failed with 1
Corpse is incomplete (_dyld_process_info_create failed with 1)
Backtraces may be be unvailable or truncated to only leaf frames, and the binary image list may not be available
thread_get_state(PAGEIN) returned 0x10000003: (ipc/send) invalid destination port
thread_get_state(EXCEPTION) returned 0x10000003: (ipc/send) invalid destination port
thread_get_state(FLAVOR) returned 0x10000003: (ipc/send) invalid destination port

EOF

-----------
Full Report
-----------

{"app_name":"vcmiclient","timestamp":"2023-10-25 10:11:01.00 +0800","app_version":"1.3.2","slice_uuid":"00120886-f2c2-3df0-b186-9becbab4e8fe","build_version":"2023-09-14-09d9099","platform":0,"bundleID":"435Q83WCM3.eu.vcmi.vcmiclient","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 17.1 (21B5045h)","roots_installed":0,"name":"vcmiclient","incident_id":"AC25F2C1-9EB9-4152-996F-76CE3D9D5271"}
{
  "uptime" : 20000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPad8,11",
  "coalitionID" : 637,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 17.1",
    "releaseType" : "Beta",
    "build" : "21B5045h"
  },
  "captureTime" : "2023-10-25 10:11:01.5941 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "AC25F2C1-9EB9-4152-996F-76CE3D9D5271",
  "pid" : 1037,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-10-25 10:11:01.5608 +0800",
  "procStartAbsTime" : 487344211941,
  "procExitAbsTime" : 487345001883,
  "procName" : "vcmiclient",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/31BD795E-A06E-437E-8ACC-5F8BFF5ABF1E\/vcmiclient.app\/vcmiclient",
  "bundleInfo" : {"CFBundleShortVersionString":"1.3.2","CFBundleVersion":"2023-09-14-09d9099","CFBundleIdentifier":"435Q83WCM3.eu.vcmi.vcmiclient"},
  "storeInfo" : {"deviceIdentifierForVendor":"41475D9C-CB1D-444B-9FC9-3FDB94BFB6C4","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "435Q83WCM3.eu.vcmi.vcmiclient",
  "crashReporterKey" : "bf783df93038a467a5cb3af01183c201df6ec0e8",
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "codeSigningID" : "435Q83WCM3.eu.vcmi.vcmiclient",
  "codeSigningTeamID" : "435Q83WCM3",
  "codeSigningFlags" : 570434309,
  "codeSigningValidationCategory" : 3,
  "codeSigningTrustLevel" : 6,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/libvcmi.dylib","Referenced from: <00120886-F2C2-3DF0-B186-9BECBAB4E8FE> \/Volumes\/VOLUME\/*\/vcmiclient.app\/vcmiclient","Reason: tried: '\/private\/var\/containers\/Bundle\/Application\/31BD795E-A06E-437E-8ACC-5F8BFF5ABF1E\/vcmiclient.app\/Frameworks\/libvcmi.dylib' (code signature in <53EBAC7B-6331-3556-A879-58AB4FA2AA64> '\/private\/var\/containers\/Bundle\/Application\/31BD795E-A06E-437E-8ACC-5F8BFF5ABF1E\/vcmiclient.app\/Frameworks\/libvcmi.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '\/private\/var\/containers\/Bundle\/Application\/31BD795E-A06E-437E-8ACC-5F8BFF5ABF1E\/vcmiclient.app\/Frameworks\/libvcmi.dylib' (code signature in <53EBAC7B-6331-3556-A879-58AB4FA2AA64> '\/private\/var\/containers\/Bundle\/Application\/31BD795E-A06E-437E-8ACC-5F8BFF5ABF1E\/vcmiclient.app\/Frameworks\/libvcmi.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned?"]},
  "sharedCache" : {
  "base" : 7131856896,
  "size" : 3504177152,
  "uuid" : "ddbfa24e-3ff5-32d0-970c-b43084e3c1f1"
},
  "legacyInfo" : {
  "threadHighlighted" : 0
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "632c763c58740028737bfdd2",
      "factorPackIds" : {
        "SIRI_DIALOG_ASSETS" : "64a57d23fa6fd41b2353e2ae"
      },
      "deploymentId" : 250000029
    },
    {
      "rolloutId" : "601074e4af9bef000c169ea8",
      "factorPackIds" : {
        "BIFROST_DEV_1" : "6535284f3ae30652571353ca"
      },
      "deploymentId" : 250003816
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    },
    {
      "treatmentId" : "280fb07d-00d3-4cad-86f9-e9af097448fb",
      "experimentId" : "6462c5d17c64ab7150680669",
      "deploymentId" : 400000003
    }
  ]
},
  "reportNotes" : [
  "_dyld_process_info_create failed with 1",
  "Corpse is incomplete (_dyld_process_info_create failed with 1)",
  "Backtraces may be be unvailable or truncated to only leaf frames, and the binary image list may not be available",
  "thread_get_state(PAGEIN) returned 0x10000003: (ipc\/send) invalid destination port",
  "thread_get_state(EXCEPTION) returned 0x10000003: (ipc\/send) invalid destination port",
  "thread_get_state(FLAVOR) returned 0x10000003: (ipc\/send) invalid destination port"
]
}


`

**Comment by 109677436** [comment]
> I know that currently there's an issue with uploading apps with Xcode 15. Could you try Xcode < 15 or AltStore? Are you on macOS Sonoma btw?
Thank you for your quick response. Yes, I am using macOS Sonoma. I will try the other Xcode version or AltStore as you suggested to address the app upload issue.

**Comment by kambala-decapitator** [comment]
what did you use to sign the app btw?

> Yes, I am using macOS Sonoma. I will try the other Xcode version

unfortunately, you can't run older Xcodes on Sonoma. You can try Apple Configurator or libimobiledevice (or similar)

**Comment by 109677436** [comment]
> what did you use to sign the app btw?
> 
> > Yes, I am using macOS Sonoma. I will try the other Xcode version
> 
> unfortunately, you can't run older Xcodes on Sonoma. You can try Apple Configurator or libimobiledevice (or similar)


I used the one provided by https://www.ios222.com/ and after installing it on the AltStore you mentioned, it opened and ran smoothly.
