### ISSUE TITLE
[HDmod] Screen filter

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#3108]
**Describe your proposal**
Add screen filters like in HD mod:
![image](https://github.com/vcmi/vcmi/assets/13953785/25e4f7d1-7356-4c10-820c-be199e98a74c)

Especially xBRZ.

**Additional context**
Veroks implementation isn't lost. Here is the solution for OH3: https://github.com/Nemirtingas/HeroesGL/tree/master (but not the latest 1.65).
He solved it with GLSL Shaders.

Another similar thing: [zelda3](https://github.com/snesrev/zelda3/tree/master/src) uses also SDL and can use xBRZ as GLSL shader.

I've also made some tests: https://github.com/Laserlicht/vcmi/tree/xbrz_test and https://github.com/Laserlicht/vcmi/tree/xbrz_hack but software based solution is to slow for real time. I'm not able to do a hardware based implementation.

Maybe a step before #1070 because it may much easier to implement.

Maybe we can use this example? https://github.com/AugustoRuiz/sdl2glsl/blob/master/src/main.cpp
Together with this shader? https://github.com/libretro/glsl-shaders/blob/master/xbrz/shaders/xbrz-freescale.glsl

**Comment by rilian-la-te** [comment]
@Laserlicht what version shaders is? 100? Is it work with ES2 then? We need to support old Android phones, which does not have good GPU than can use ES3 or Vulkan.

**Comment by Laserlicht** [comment]
> @Laserlicht what version shaders is? 100? Is it work with ES2 then? We need to support old Android phones, which does not have good GPU than can use ES3 or Vulkan.

I don't know. I'm not that familiar with hardware acceleration.

Yes, we need to support old devices. But we do not necessary need to support hardware filters on that. I think the most benefit is on PC/large tablets.
