### ISSUE TITLE
Crash on high scores screen

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3111]
**Describe the bug**
Adding more high scores with same player name leads to crash.

**Game logs**

Call stack:
```
 	KernelBase.dll!00007fff5d664ffc()	No info
 	vcruntime140.dll!00007fff2c5d6720()	No info
>	VCMI_lib.dll!std::_Throw_bad_variant_access() Line 418	C++
 	VCMI_lib.dll!std::get(const std::variant<std::monostate,bool,double,std::string,std::vector<JsonNode,std::allocator<JsonNode>>,std::map<std::string,JsonNode,std::less<std::string>,std::allocator<std::pair<std::string const ,JsonNode>>>,__int64> &) Line 1225	C++
 	VCMI_lib.dll!std::get(const std::variant<std::monostate,bool,double,std::string,std::vector<JsonNode,std::allocator<JsonNode>>,std::map<std::string,JsonNode,std::less<std::string>,std::allocator<std::pair<std::string const ,JsonNode>>>,__int64> &) Line 1260	C++
 	VCMI_lib.dll!JsonNode::Integer() Line 342	C++
 	VCMI_client.exe!CHighScoreInputScreen::addEntry::__l2::<lambda>(const JsonNode & left, const JsonNode & right) Line 256	C++
 	VCMI_client.exe!std::sort(const std::_Vector_iterator<std::_Vector_val<std::_Simple_types<JsonNode>>>) Line 8067	C++
 	VCMI_client.exe!boost::range::sort(std::vector<JsonNode,std::allocator<JsonNode>> &) Line 51	C++
 	VCMI_client.exe!CHighScoreInputScreen::addEntry(std::string text) Line 274	C++
 	[Ramka wbudowana] VCMI_client.exe!std::_Func_class<void,std::string>::operator()(std::string) Line 883	C++
 	VCMI_client.exe!CHighScoreInput::okay() Line 383	C++
```

**To Reproduce**
1. Win a game
2. Put your name in the high scores
3. Win another game
4. Put same name in high scores

**Expected behavior**
No crash

**Actual behavior**
`JsonNode::Intege`r throws `bad_variant_access`.

**Did it work earlier?**
 Nope, it's a new feature.

**Screenshots**
Crash occurs before high scores are displayed.

**Version**
1.4.0

**Comment by dydzio0614** [comment]
@Laserlicht you may want to check this

**Comment by Povelitelh3** [comment]
have problems when win in campaign under windows, but everything is ok when win in single scenario

**Comment by Laserlicht** [comment]
> have problems when win in campaign under windows, but everything is ok when win in single scenario

Have you tested the PR? https://github.com/vcmi/vcmi/pull/3114

**Comment by DjWarmonger** [comment]
Sorry, I didn't. And can't promise I will anytime soon :/

**Comment by Laserlicht** [comment]
> Sorry, I didn't. And can't promise I will anytime soon :/

No problem. :)

Maybe merge the PR (this should fixed anyway) and leave the issue open?

**Comment by Povelitelh3** [comment]
Oh, sorry, I'm stupid. I thought it's already merged. 
Download PR https://github.com/vcmi/vcmi/pull/3114 and tested campaigns. Everything is ok!

**Comment by Laserlicht** [comment]
> Oh, sorry, I'm stupid. I thought it's already merged. Download PR #3114 and tested campaigns. Everything is ok!

No problem. :)

**Comment by boctavian96** [comment]
Hello! Maybe this input helps, on my case I'm not able to input the name, it crashes after the 'dragon animation' plays. So to reproduce it I need only to win the game
