### ISSUE TITLE
Sonarcloud Code Analysis

### ISSUE THREAD

**Issue by Alexander-Wilms** [vcmi/vcmi#3112]
**Describe your proposal**
Setting up Sonarcloud Code Analysis could help improve code quality

I've set it up for my fork and these are the results:
https://sonarcloud.io/summary/overall?id=Alexander-Wilms_vcmi

It tries to detect possible bugs, code smells and security issues:

![image](https://github.com/vcmi/vcmi/assets/3226457/44e5678e-5f69-4016-b27d-e11f1a5e5771)

**Additional context**

**Comment by Alexander-Wilms** [comment]
I've experimented with it a bit.

SonarCloud supports automatic analysis, which only requires one to set up the project on https://sonarcloud.io.
The alternative is analyzing the code using Github Actions, which is what fheroes2 does. But automatic analysis seems a lot simpler for VCMI.

The only things I had to configure were:
1) Give the https://github.com/apps/sonarcloud bot `Read and write access to checks, commit statuses, pull requests, and security events`
2) Create a corresponding project: https://sonarcloud.io/projects/create
3) Exclude 3rd party code from analysis:
![image](https://github.com/vcmi/vcmi/assets/3226457/6dee92a6-d50d-40bb-a833-4c5900313f04)
https://sonarcloud.io/project/settings?category=exclusions&id=vcmi_vcmi#sonar.coverage.exclusions

Then you get the overview where you can browse and filter discovered issues:
![image](https://github.com/vcmi/vcmi/assets/3226457/f36dfc09-041e-4a46-8036-6ef04506af50)

And the bot creates a comment on each PR after the analysis is done, summarizing the newly introduced issues, if any.

I created a test PR adding an unused variable. This also gets caught during CI due to the `-Werror` flag, but other kinds of error are not.

https://github.com/Alexander-Wilms/vcmi/pull/2
![image](https://github.com/vcmi/vcmi/assets/3226457/875de9c0-fc79-43b4-b041-2ae3f141c5db)

![image](https://github.com/vcmi/vcmi/assets/3226457/3ccc1543-b4bd-4855-9d7b-06ab73f268f0)

The bot's comment links here: https://sonarcloud.io/summary/new_code?id=Alexander-Wilms_vcmi&pullRequest=2
![image](https://github.com/vcmi/vcmi/assets/3226457/f2b22cb2-9da7-4dcb-8330-289fb4016246)

If the PR fails to pass the quality gate, that is shown like a failed CI job:
![image](https://github.com/vcmi/vcmi/assets/3226457/76257366-5ccb-4696-bc25-9ed36ff703c2)

**Comment by kambala-decapitator** [comment]
I used SC at work - it works quite well.

btw path exclusions and other options can also be added to the config file that SonarQube uses (can tell you the name later, not at hand atm). I find it a better option as settings are under source control and not hidden somewhere deep in the web UI.

**Comment by IvanSavenko** [comment]
To be honest other than few "interesting" diagnostics (e.g. uninitialized members in constructor) don't see anything important. And their classification of "critical' issues is a weird one. I mean:
> Use "=default" instead of the default implementation

Critical? Seriously? And this is not copy-constructor but an empty destructor. Sure, would be nice to replace it with default, but this is very minor issue.

- Can we disable some of their diagnostics globally? I see some suggestions that in my opinion decrease readability without anything to gain.
- Do they provide way to silence / resolve false-positives?
- Can we set their CI to simply generate report of new issues in comments instead of "failing" CI?

**Comment by Alexander-Wilms** [comment]
Individual issues can be marked as false positive:
![image](https://github.com/vcmi/vcmi/assets/3226457/a88f23f8-14a0-4dae-9d28-aa1f99f721d0)

One can copy the default set of rules and adapt it by deactivating some of them:
![image](https://github.com/vcmi/vcmi/assets/3226457/eb8479e0-373d-4e17-b5c3-1b38b8f1b99e)

![image](https://github.com/vcmi/vcmi/assets/3226457/cd1827e2-6bf0-4c29-a9d4-6048219a3e12)

**Comment by IvanSavenko** [comment]
@Alexander-Wilms 
what about this option?
> Can we set their CI to simply generate report of new issues in comments instead of "failing" CI?

**Comment by Alexander-Wilms** [comment]
I'm looking for an option. But the failed quality gate only results in the merge button being grey instead of green, it doesn't prevent merging. Does that suffice?

**Comment by IvanSavenko** [comment]
Merging is permitted even if CI fails / still in progress.

Mostly want to avoid confusing people when they trigger "new" warnings by editing some old code where you can't really avoid some smelly code (which gets picked up by sonar cloud)

Well, I guess I can try to setup it for vcmi and see how it goes.

**Comment by Alexander-Wilms** [comment]
One can use the SonarCloud API without an API key to query the issues, which could be helpful to automatically fix a large number of them:

https://sonarcloud.io/web_api/api/issues/search?deprecated=false&section=params

https://sonarcloud.io/api/issues/search?projects=vcmi_vcmi
