### ISSUE TITLE
Autoskip is broken in develop

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3123]
**Describe the bug**
After I enable `autoskip`, I'm getting some query error messages and the game is effectively blocked forever.

**Game logs**
```
Preparing environment for player neutral
Preparing environment for player red
Preparing environment for player blue
Preparing interface for player red
Player red will be lead by human
Preparing interface for player blue
Player blue will be lead by Nullkiller
Opening Nullkiller
Loaded Nullkiller
Opening StupidAI
Loaded Stupid AI 0.1
System message: Cheater!!!
System message: Cheater!!!
autoskip
Player 1 (blue) starting turn, day 1
Hero Marchette has 1500 MP left
Hero Axsis has 1560 MP left
Player 1 (blue) ends turn
Player 1 (blue) ended turn

| Player "RED" has to answer queries before attempting any further actions.
| Top Query: "A query of type 'class TimerPauseQuery' and qid = 28 affecting player RED, "

System message: Server encountered a problem:
| Player "RED" has to answer queries before attempting any further actions.
| Top Query: "A query of type 'class TimerPauseQuery' and qid = 28 affecting player RED, "
```

**To Reproduce**
1. Type `autoskip` in console
2. Launch any map

**Expected behavior**
AI would play as normal and I could stop autoskip at anytime by holding SHIFT. Then I should be able to play normally.

**Did it work earlier?**
Certainly

**Screenshots**

**Version**
Develop 1.4.0
Windows 11

**Comment by nullkiller** [comment]
Player red will be lead by human
Player "RED" has to answer queries before attempting any further actions.
looks like human issue, not AI

**Comment by Povelitelh3** [comment]
related https://github.com/vcmi/vcmi/issues/2745

**Comment by Povelitelh3** [comment]
What’s interesting is that if you write "gosolo" in the console, the game will skip turns without a gui

**Comment by DjWarmonger** [comment]
Classic deadlock

- GH adds a query for timer, which should be automatriclaly removed after player ends turn
- Player gets turn. With autoskip interface tries to remove nw turn info windows
- However, info windows can't be removed since there is unhandled TimerPauseQuery

I am not sure if this TimerPauseQuery should be explicitely answered. Now it cannot be answered at all, since there is no dialog or any other info about this query on player interface side.
