### ISSUE TITLE
How do I use custom rmg.txt

### ISSUE THREAD

**Issue by bloveamber-zl** [vcmi/vcmi#3137]
**Describe the bug**
First of all, this is not a bug, I created a random template file rmg.txt myself, where should I put this file to take effect?

**Expected behavior**
I want to use a custom random map template

**Comment by DjWarmonger** [comment]
VCMI does not load rmg.txt, it uses its own format: https://github.com/vcmi/vcmi/blob/develop/docs/modders/Random_Map_Template.md
It should be 100% compatible with original template specs.

**Comment by bloveamber-zl** [comment]
Thank you very much for your information. So I want to choose my custom template in the game, where should I put the json file I created?

**Comment by bloveamber-zl** [comment]
I sort of get it, is to create a new random map editor Mod in your Mod format?

**Comment by misiokles** [comment]
> Thank you very much for your information. So I want to choose my custom template in the game, where should I put the json file I created?

Download warzyw-templates from launcher, then browse files to figure out how it was done.

**Comment by bloveamber-zl** [comment]
Successful application, thank you
