### ISSUE TITLE
windows build problem - replace symlink with junction link

### ISSUE THREAD

**Issue by gamestales** [vcmi/vcmi#3151]
**Describe the bug**
Building on windows fails with symlink creation

**Build logs**
Error		failed to create symbolic link 'C:/VCMI/build/bin/Release/mapeditor/icons': A required privilege is not held by the client.	

**To Reproduce**
Build from Visual Studio 2019

Build would require administrator privileges. It can be fixed with using junction links as described at:
https://stackoverflow.com/questions/61243174/replacement-of-create-symlink-in-windows
cmd.exe /c mklink /J "C:/VCMI/build/bin/$(Configuration)/launcher/icons" "C:/VCMI/source/launcher/icons"

**If the issue is accepted, I can do it.**

**Comment by krs0** [comment]
I think I have solved the problem by enabling developer mode.

**Comment by gamestales** [comment]
Windows settings developer mode
Just checked and it helps for me as well.

The build works well for me with junction link, so I still would like to do it.

**Comment by kambala-decapitator** [comment]
> The build works well with junction link, so I still would like to do it.

Please go ahead

**Comment by IvanSavenko** [comment]
Yep. Go ahead.
Feel free to also replace `copy_directory` calls from lib for "Mods" and "config" with symlink/junctions.
