### ISSUE TITLE
[HDmod] artifact fast selection

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#3153]
**Describe your proposal**
Faster selection of artifacts should be implemented in VCMI.

HDmod:
![grafik](https://github.com/vcmi/vcmi/assets/13953785/a76844c1-1375-4391-b6af-c4608d015063)

**Additional context**
It should be implemented platform independent. One idea would be using the radial wheel to select artifacts (perfect on touch; also usable on desktop).

Example:
![grafik](https://github.com/vcmi/vcmi/assets/13953785/ecb5660c-c854-49e5-8662-ad12e37997ac)

**Comment by krs0** [comment]
Radial wheel on desktop looks out of place.

Would go for pop-up window.

**Comment by Laserlicht** [comment]
> Radial wheel on desktop looks out of place.
> 
> Would go for pop-up window.

Yes, also okay. But how to open it on touch devices?
