### ISSUE TITLE
The game crashes if you play in co-op with a computer

### ISSUE THREAD

**Issue by gestern** [vcmi/vcmi#3156]
**Describe the bug**
When choosing a game mode in cooperation with a computer player in random map mode, _after passing the turn_ (this is not a **prerequisite** for retesting) to the opponent, the game suddenly crashes. **The game crash scenario is reproducible.**

**Game logs**
`VCMI_client.txt`:

```
[2023-Nov-06 22:47:41.272779] DEBUG global - Ending movement animation
[2023-Nov-06 22:47:42.106193] DEBUG global - totalRedraw requested!
[2023-Nov-06 22:47:42.109898] DEBUG global - Starting fade out animation
[2023-Nov-06 22:47:42.631560] DEBUG global - Ending fade out animation
[2023-Nov-06 22:47:42.634200] DEBUG global - removing object id=178; address=1320843b0; name=Древесина
```

 `VCMI_server.txt`:
```
[2023-Nov-06 22:47:42.098407] DEBUG global - Hero hero.core.ayden.name visits Древесина (79)
[2023-Nov-06 22:47:42.098534] DEBUG global - removing object id=178; address=1296689d0; name=Древесина
[2023-Nov-06 22:47:42.101567] DEBUG global - Hero hero.core.ayden.name visit ends.

[2023-Nov-06 22:47:44.576451] ERROR network - Network error receiving a pack. Connection has been closed
[2023-Nov-06 22:47:44.576737] INFO network - Thread listening for Connection with VCMI 1.4.0.2bf599bbee9011ad952ad53380cc47d3ddfeee79 (server) (ID: 1 UUID: 18e5a585-0cb2-4832-aaad-80874211304f) ended
```

***Callstack***
```
Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001880171f4

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [41883]

Thread 0:: MainGUI Dispatch queue: com.apple.main-thread
0   libvcmi.dylib                 	       0x107fb6e50 CGameInfoCallback::getPlayerTeam(PlayerColor) const + 32
1   libvcmi.dylib                 	       0x107ab3104 CGameState::isVisible(int3, std::__1::optional<PlayerColor> const&) const + 152
2   libvcmi.dylib                 	       0x107fb3268 CGameInfoCallback::isVisible(int3) const + 76
3   vcmiclient                    	       0x104b20f08 NeighborTilesInfo::NeighborTilesInfo(IMapRendererContext&, int3 const&) + 484
4   vcmiclient                    	       0x104b207f4 MapRenderer::getTileChecksum(IMapRendererContext&, int3 const&) + 80
5   vcmiclient                    	       0x104b283f0 MapViewCache::updateTile(std::__1::shared_ptr<IMapRendererContext> const&, int3 const&) + 144
6   vcmiclient                    	       0x104b28908 MapViewCache::update(std::__1::shared_ptr<IMapRendererContext> const&) + 792
7   vcmiclient                    	       0x104b25314 BasicMapView::render(Canvas&, bool) + 68
8   vcmiclient                    	       0x104b25478 BasicMapView::show(Canvas&) + 96
9   vcmiclient                    	       0x104b258cc MapView::show(Canvas&) + 116
10  vcmiclient                    	       0x104a93c28 CIntObject::show(Canvas&) + 84
11  vcmiclient                    	       0x104a93c28 CIntObject::show(Canvas&) + 84
12  vcmiclient                    	       0x104a02578 AdventureMapInterface::show(Canvas&) + 24
13  vcmiclient                    	       0x104ab200c WindowHandler::simpleRedraw() + 156
14  vcmiclient                    	       0x104cb6ae8 CPlayerInterface::update() + 436
15  vcmiclient                    	       0x104a927b4 CGuiHandler::renderFrame() + 68
16  vcmiclient                    	       0x104c86398 main + 17532
17  dyld                          	       0x187e6ff28 start + 2236
```

**To Reproduce**
1. Go to 'New Scenario'
2. Click on 'Random Map'
3. Configure the random scenario team settings so that the player is in a team with a computer player

**Expected behavior**
The game should continue running

**Actual behavior**
The game unexpectedly ends due to errors, without reaching the criterion of either victory or defeat

**Did it work earlier?**
This scenario has not been previously tested

**Screenshots**
<img width="827" alt="image" src="https://github.com/vcmi/vcmi/assets/1861589/884095b9-065a-4257-8fd4-74abc3495cff">

**Version**
 - OS: `macOS ARM 13.5`
 - Version: `VCMI 1.4.0.2bf599bbee9011ad952ad53380cc47d3ddfeee79`

**Additional context**
n/a

**Comment by nullkiller** [comment]
What friendly AI do you use? Game crashes on AI turn?

**Comment by Povelitelh3** [comment]
When you created these settings with islands I had error:

> [2023-Nov-12 13:10:59.991404] ERROR network - Lost connection to server, ending listening thread!

And back in main menu

Second time I had crashdump and log here
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13327706/VCMI_Server_log.txt)


My suspitions is teamplate don't support island in settings these size, may be I wrong ofc

**Comment by IvanSavenko** [comment]
Unable to reproduce.
- Start game
- Open random map window
- Set number of players to 8
- Set teams setup as described on screenshot
- Start map
- End turn

No crash for me

**Comment by Povelitelh3** [comment]
> Unable to reproduce.
> 
>     * Start game
> 
>     * Open random map window
> 
>     * Set number of players to 8
> 
>     * Set teams setup as described on screenshot
> 
>     * Start map
> 
>     * End turn
> 
> 
> No crash for me

add islands please in setup
![изображение](https://github.com/vcmi/vcmi/assets/36762538/efcb9974-2761-48c1-83ba-020a8bca7307)

**Comment by IvanSavenko** [comment]
Still unable to reproduce, even with island maps

**Comment by gestern** [comment]
The problem seems to have gone away. It's gonna be closed
