### ISSUE TITLE
FPS background

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#3171]
**Describe the bug**
Background for FPS is not fitting and doesn't look good with 3 digits (and also with two digits).

![grafik](https://github.com/vcmi/vcmi/assets/13953785/641aaad6-b77f-45ac-95c6-24c44a650614)
![grafik](https://github.com/vcmi/vcmi/assets/13953785/af54b35f-cb18-4e77-8f91-0a62292159ab)

**Did it work earlier?**
With 1.3.2 it is better (but also not perfect):
![grafik](https://github.com/vcmi/vcmi/assets/13953785/39b68f74-0d59-40b4-8ec0-ec0e4a44022a)

Bug seems to be introduced with turn timers?

**Version**
 - OS: Ubuntu
 - Version: develop

**Comment by Alexander-Wilms** [comment]
```c++
void CGuiHandler::drawFPSCounter()
{
	static SDL_Rect overlay = { 0, 0, 64, 32};
```

https://github.com/vcmi/vcmi/blame/b5417c667c42fee1099f3cd5053b267ce2f3edb8/client/gui/CGuiHandler.cpp#L187

was changed to

```c++
void CGuiHandler::drawFPSCounter()
{
	static SDL_Rect overlay = { 0, 0, 24, 24};
```

https://github.com/vcmi/vcmi/blame/d295840c64e4d6cdbd44de78c40397396ac79e87/client/gui/CGuiHandler.cpp#L186

Also, maybe it could use a semitransparent background and optionally a high-contrast color, like the Steam overlay:

![image](https://github.com/vcmi/vcmi/assets/3226457/b64f93ba-23a3-44a6-9163-6bb0b0e769aa)

**Comment by Laserlicht** [comment]
What about using highscore font (has outlines) without background?

**Comment by Alexander-Wilms** [comment]
Might be a bit hard to see:

![image](https://github.com/vcmi/vcmi/assets/3226457/a246c361-39b9-435d-9ad5-2d5450a7c803)

**Comment by Alexander-Wilms** [comment]
I think putting it in the bottom panel is the best solution:

![image](https://github.com/vcmi/vcmi/assets/3226457/405a60f3-b955-48e9-bc07-61f50d3451b7)

I just noticed that the previous fps counts keeps being drawn if the screen is darkened due to the darkened screen while the story dialogs are shown.

**Comment by Laserlicht** [comment]
The problem here is that this space only exists on higher resolutions. On "standard" resolution this space is reserved by wood.

**Comment by IvanSavenko** [comment]
> The problem here is that this space only exists on higher resolutions. On "standard" resolution this space is reserved by wood.

Probably not a problem - fps counter is off by default and very few people play in 800x600

Another possible location is top-right corner - which is used by minimap decorations

**Comment by Alexander-Wilms** [comment]
Or on the left side of the brown status bar.

But I think it looks best in the resource bar.

**Comment by Laserlicht** [comment]
> But I think it looks best in the resource bar.

Yes looks best there. But then lock the fps option (and deselect) if width < 700? To avoid this "buggy" overdraw.

**Comment by IvanSavenko** [comment]
No need probably? This is debug option, so non-ideal behavior is ok
