### ISSUE TITLE
Crash in custom campaign

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3173]
first mission - vcmisilmaril
second mission - choose bonus - start - crash
latest develop, mingw

> [2023-Nov-11 15:15:53.824840] DEBUG global - Request to patch map maps/eternal love (кампания)/eternal love:4
> [2023-Nov-11 15:15:53.842604] TRACE network - Sending a pack of type 16LobbySetCampaign
> [2023-Nov-11 15:15:54.715094] TRACE network - Sending a pack of type 16LobbyUpdateState
> [2023-Nov-11 15:15:58.379276] TRACE network - Received CPack of type 21LobbySetCampaignBonus
> [2023-Nov-11 15:15:58.431402] TRACE network - Sending a pack of type 21LobbySetCampaignBonus
> [2023-Nov-11 15:15:58.431795] TRACE network - Sending a pack of type 16LobbyUpdateState
> [2023-Nov-11 15:16:01.455046] TRACE network - Received CPack of type 14LobbyStartGame
> [2023-Nov-11 15:16:01.455474] INFO network - Preparing to start new campaign
> [2023-Nov-11 15:16:01.455935] INFO global - Gamestate created!
> [2023-Nov-11 15:16:01.456080] INFO global - 	Using random seed: 1699704961
> [2023-Nov-11 15:16:01.507383] TRACE network - Sending a pack of type 17LobbyLoadProgress
> [2023-Nov-11 15:16:01.620819] DEBUG global - Map 'eternal love:4': Hero on map: core:orrin at (8 58 0), owned by red
> [2023-Nov-11 15:16:01.623170] DEBUG global - Map 'eternal love:4': Hero on map: (random) at (37 14 0), owned by blue
> [2023-Nov-11 15:16:01.623320] ERROR global - Hero is already on the map at (7 58 0)
> [2023-Nov-11 15:16:01.624106] ERROR global - Disaster happened.
[Eternal Love.zip](https://github.com/vcmi/vcmi/files/13325434/Eternal.Love.zip)

**Comment by nullkiller** [comment]
Mmm, this is duplicating hero trigger. Will check other campaigns

**Comment by nullkiller** [comment]
Looks like this is a problem of this specific campaign. Will try to get more details

**Comment by IvanSavenko** [comment]
Fixed in current build
