### ISSUE TITLE
Incorrect display of visited objects

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3175]
When I visited the Griffon Conservatory, I abandoned 2 dogs. since I didn't have a slot to take angels. But now it shows that these two dogs seem to be in it, as if in a garrison.
![изображение](https://github.com/vcmi/vcmi/assets/36762538/90aa035c-f83c-4f3e-aa42-e44bd0356b94)
[save.zip](https://github.com/vcmi/vcmi/files/13327651/save.zip)

**Comment by misiokles** [comment]
Seems logical ;)

**Comment by Povelitelh3** [comment]
Yea, but phisically they aren't exist. You won't their back.
