### ISSUE TITLE
Tree of knowledge doesn't work

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3176]
Bron is trying visit tree of knowledge, resourses write off, but nothing happened. 
1.4.0.07472d3b0524874c0a3891a7e46bb8e3ef43236e
[Tree.zip](https://github.com/vcmi/vcmi/files/13327789/Tree.zip)

**Comment by nullkiller** [comment]
Looks like general issue with trees.

**Comment by IvanSavenko** [comment]
Yeah, will fix soon
