### ISSUE TITLE
Random heroes

### ISSUE THREAD

**Issue by LordIofIThunder** [vcmi/vcmi#3178]
**Describe the bug**
Instead of the Kilgor there is another one as your starter hero in the campaign.

**Game logs**
![VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/13327944/VCMI_Client_log.txt)

![VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13327945/VCMI_Server_log.txt)

**To Reproduce**
1. Get in any scenario you want
2. Start the scenario
3. Wait and see the different hero

**Expected behavior**
The scenario should've started with Kilgor as youre starter hero.

**Actual behavior**
Any other heroes except Kilgor will be youre starter hero.

**Did it work earlier?**
The vcmi 1.4.0 from 2 november doesn't have this issue.

**Version**
 - OS: [e.g.  Android,]
 - Version: [VCMI 1.4.0, 12 November]
https://github.com/vcmi/vcmi/assets/146068046/bcdb10f9-6942-45c0-a91b-4300f088f86f

**Comment by Povelitelh3** [comment]
Most likely related https://github.com/vcmi/vcmi/issues/3174
