### ISSUE TITLE
Quest Guard,  condition cannot be met "return with creatures"

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3183]
There was a condition to bring 1 boar, but the Quest Guard is not working
[QuestGuard.zip](https://github.com/vcmi/vcmi/files/13335057/QuestGuard.zip)
develop

**Comment by Povelitelh3** [comment]
map [SoD__Not_a_Lady_.zip](https://github.com/vcmi/vcmi/files/13479167/SoD__Not_a_Lady_.zip)
![quest](https://github.com/vcmi/vcmi/assets/36762538/6cc6e00f-5ad2-45c4-b2ff-ad0103837708)

I have no idea what happened and changed, but now it works (aed0f09a7dbe37a2a810617fa2372bc2166b56f4)

saves has been changed. 

I loaded 07472d3 (two weeks ago build), and nothing happens. Bug can be repeated from my savefile.

**Comment by IvanSavenko** [comment]
Closing, presumably fixed
