### ISSUE TITLE
touch screen introduction

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#3189]
**Describe your proposal**
We should add a introduction how to use the touch screen and it gestures in VCMI.

It often happens that users do not know how to do something (e.g. long touch for right mouse button, attacking from direction, ...).

Because the knowledge is missing, the input is often rated as imprecise.

**Additional context**
Maybe show a window on first touch input.

As far as I know, this is also available in the official HD android version (@dydzio0614 Didn't you post a video of it somewhere? Do you still have it?).

An idea would to add a window with a video showing basic input. But it should be simple ("vector" based, not using any H3 assets). Do we have anyone who is familiar with creating animations?

**Comment by IvanSavenko** [comment]
If somebody would implement this - that would be great!

> Maybe show a window on first touch input.

Or - on map start if touch input exists (on any platform). We already have check for that - `GH.input().hasTouchInputDevice()`

What we need to show:
1. When player start a map, possibly in tutorial-like form, with 3 consecutive dialogs.
- long tap / right click
- map panning
- map zooming

2. When player start first battle:
- attack direction selection
- attack cancellation (moving finger far enough)
- spell cancellation via long tap / right click

**Comment by Laserlicht** [comment]
@IvanSavenko Do you have any idea other than video?

As far as I know it isn't possible to play animated svg or embed website into SDL. Right?

But I think "programming" an animation isn't also a good idea.

> Or - on map start if touch input exists (on any platform)

Yes, that's better.

**Comment by IvanSavenko** [comment]
Video might be easier to make (if we can find somebody skilled to do that).

However with runtime generated animation we can:
1) Use H3 asserts, by loading them in runtime
2) Keep app size low. Videos are quite large after all.

So simple runtime-generated animation might not be a bad idea.

**Comment by IvanSavenko** [comment]
HD Edition uses static images by the way:
https://github.com/vcmi/vcmi/issues/983#issuecomment-1397088533

**Comment by Laserlicht** [comment]
> HD Edition uses static images by the way:

Ah, kambala posted the video :)

Static images would be much easier than animation.

> So simple runtime-generated animation might not be a bad idea.

Yes, correct. But I think this would also need much code for introduction of a animation class. Or do it the hacky way.

**Comment by gamestales** [comment]
Could it be done externaly?
The game would contain a link to wiki/video tutorial.

**Comment by Laserlicht** [comment]
@IvanSavenko 

CC-BY content is okay in this repo?

My idea is to do screen capture (cropped to relevant area) and only show mod content. Should be okay?

Only thing which should manually replaced is the cursor and the rmb background.

**Comment by Laserlicht** [comment]
Is it possible to understand something like this? Or to simple?

![anim](https://github.com/vcmi/vcmi/assets/13953785/cd215beb-f9bd-40da-b2a9-760ed2d3aa3f)

**Comment by IvanSavenko** [comment]
Personally - if didn't knew what this is about I probably haven't figured it out...

> CC-BY content is okay in this repo?

CC-BY-SA, but yes.

> My idea is to do screen capture (cropped to relevant area) and only show mod content. Should be okay?

As long as video size is kept as low as possible - probably OK? Don't want to increase install size too much.

And if we go for video - I would limit it to Android / iOS then, to avoid size increase on other platforms where touchscreen almost never exists.

If we could generate this in runtime, that would have been great though, even if we would only use few static images instead of actual animation

**Comment by IvanSavenko** [comment]
5 Mb is still ~25% increase in install size...
