### ISSUE TITLE
AI player starts playing instead of human game

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3205]
This is the second time I've encountered this error. I chose the red player, started the game and the bot started playing for me. I see his moves and I see his fights. In this case, he took the monks' home (I saw the battle from the inside) and after that the game fell.

All resources were minus 1

VCMI 1.4.0.c0e54b338a0d0be06fa43e24238d274a919a0960, mingw

[server_log.txt](https://github.com/vcmi/vcmi/files/13407031/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/13407033/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13407034/VCMI_Server_log.txt)

**Comment by IvanSavenko** [comment]
Is it possible that you have enabled spectator mode by changing red player to AI?

**Comment by Povelitelh3** [comment]
> Is it possible that you have enabled spectator mode by changing red player to AI?

No, it was a regular game that I launched as usual.
The only thing I did was click on different colors, but I started with the red one.
