### ISSUE TITLE
artifacts from the warrior's tomb simply disappear

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3206]
The hero Sorsha took the shield from the grave, but it is not in the backpack or on the hero’s doll. He just disappeared
current develop
[Sorsha.zip](https://github.com/vcmi/vcmi/files/13412641/Sorsha.zip)

**Comment by IvanSavenko** [comment]
Unable to reproduce.
- Load save using build from revision c0e54b3 (last one available right now)
- Visit nearby tomb with Sorsha
Artifact goes into inventory as expected

**Comment by Povelitelh3** [comment]
Yea, right. It's very strange, because I tried repeat it, started game and could repeat this problem.
But I remember when it happened I didn't close a game, I just load save and it worked. I mean, bug happened.
Must be close I suppose.

**Comment by IvanSavenko** [comment]
Closing as not reproducible
