### ISSUE TITLE
Crash in battle with identifier core with 'waterWalk' or 'dimensionDoor'

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#3209]
![image](https://github.com/vcmi/vcmi/assets/127420617/f679cffd-faba-4f0a-9813-1d09407d0846)
![image](https://github.com/vcmi/vcmi/assets/127420617/6d8d7369-bb90-4b27-8a34-219478bfeac1)

Very hard to find the reason, in the latest build yesterday.

Actually it crashes in any battle while entering the game.
![image](https://github.com/vcmi/vcmi/assets/127420617/33692385-2775-4164-b968-399fc5fc5c68)

Windows and 1.4.0 daily build in 20th of November

**Comment by DjWarmonger** [comment]
I had a similiar bug
<img width="603" alt="battlefield core_Deathcloud" src="https://github.com/vcmi/vcmi/assets/2566990/09d68570-045e-448a-9f5f-f4e5f1ca3d25">
<img width="586" alt="battlefield core_acidBreath" src="https://github.com/vcmi/vcmi/assets/2566990/a0aedc6f-1ae9-4c3d-adbb-90a4c9e63036">

Looks like serialization of IDs is completely messed up?

**Comment by DjWarmonger** [comment]
This change is very suspicious:
<img width="659" alt="image" src="https://github.com/vcmi/vcmi/assets/2566990/f7fdf280-19da-44aa-b617-ba1b58c8cdf4">
https://github.com/vcmi/vcmi/commit/cc71651ee48ef3bc132cb9d271eeb01b4f9928b2#diff-eea018321ff5bfa427b261440d5fcfdcc1c10e81376db171aa2c3718510587eeL174

Looks ok now, but why did spell suddenly change to battlefield?

**Comment by DjWarmonger** [comment]
This change looks very suspiscious:

<img width="659" alt="image" src="https://github.com/vcmi/vcmi/assets/2566990/f0c54c91-161e-40ce-a743-0259b8970086">

https://github.com/vcmi/vcmi/commit/cc71651ee48ef3bc132cb9d271eeb01b4f9928b2#diff-eea018321ff5bfa427b261440d5fcfdcc1c10e81376db171aa2c3718510587eeL174

Looks ok now, but why did spell suddenly change to battlefield?
