### ISSUE TITLE
Bring back 32-bit builds and old Windows support

### ISSUE THREAD

**Issue by Davilarek** [vcmi/vcmi#3218]
**Describe your proposal**
I sometimes play H3 on my old laptop that has 32 bit processor and can run up to win7,
and as someone who loves open source software, I would like to play H3 using VCMI,
unfortunately, as of 1.2 this project no longer ships 32 bit builds which makes me stuck on 1.1.1 which is a bit outdated.
I would love to see builds of VCMI that support those older hardware. 

**Additional context**

**Comment by dydzio0614** [comment]
While I let others decide on this matter, I would like to notice that even if we support that right now, the support may be eventually gone in a year or two, it is possible that next generation of Visual Studio will not have option to create win7-compatible executables at all. Our current main builds do not work on windows 7 64 bit as well.

**Comment by Povelitelh3** [comment]
Guys, because of VCMI, I had to reinstall Windows 7 to Windows 10 on my second computer :D

**Comment by kambala-decapitator** [comment]
+1 from me, h3 should support as many OS versions as possible

**Comment by IvanSavenko** [comment]
If somebody can figure out what's wrong with Win7 build and how to fix that - sure?

I think we can easily enable 32-bit builds on our mingw builder, but it likely will have same issue with NKAI as 64bit build (and now also - with BattleAI). Namely - does not works on Win7.

**Comment by Davilarek** [comment]
Actually, running a live debian iso isn't a problem for me

**Comment by dydzio0614** [comment]
@IvanSavenko MSVC builds work on win7, so easy solution would be: build 32 bit win7 build with MSVC and either fix broken library name or repack the build manually with renamed library (tbb_debug.dll needs to be renamed to tbb.dll)

**Comment by Laserlicht** [comment]
fixed with #3320
