### ISSUE TITLE
Demonology doesn't work (units has still alive after battle, pit lords ability)

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3221]
I came across the fact that after the battle, my killed units, which I turned into demons with the help of pit lords, remain alive.

(In more detail, the point is that both the summoned demons and the units from which they were made remain).

develop, mingw 'VCMI 1.4.0.47c1d3dcba2ede8d5ebde5fbb4a5fe03821677f4'

**Comment by by003** [comment]
I have found this as well, even it affects the ability of Horn of the Abyss. Write in HotA mod.
