### ISSUE TITLE
These maps used to work in very old versions of VCMI, 0.99 or lower. Now they're broken

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3225]
I can’t say for sure what versions they worked in, but a long time ago they ran 100% 
I remember that I played them

The only mods I used were:
VCMI extras 3.5.2, 
VCMI essential files 1.3, 
English translation 1.3.1

**Version**
 - OS: [e.g. Windows]
 - Version: [VCMI version 1.4.0.47c1d3dcba2ede8d5ebde5fbb4a5fe03821677f4, mingw]
[DontStart.zip](https://github.com/vcmi/vcmi/files/13463353/DontStart.zip)

**Comment by IvanSavenko** [comment]
- Related to #2166
- The Last Crusade: Instant loss since hero specified in loss condition is in prison. H3 applies condition only once imprisoned hero is freed.
- Vengeance is Mine: will fix
- This is Legion 7: will fix
