### ISSUE TITLE
The abilities on an unit screen do not scroll on the touch device

### ISSUE THREAD

**Issue by beitan** [vcmi/vcmi#3227]
Also scroll buttons doesn't working

![Screenshot_20231126_130804](https://github.com/vcmi/vcmi/assets/68656340/63bc389e-cafa-46fd-ba80-c21a70ad49b9)

OS: [Android]
 - Version: 1.3.2

**Comment by misiokles** [comment]
Actually, it's not a scroll bug. Because Griffins have only 2 bonuses and there's nothing to scroll. Scroll arrows appear always. But works where's too many bonuses and window must fit the screen.

**Comment by beitan** [comment]
Oh, sorry. It's really not a bug

**Comment by krs0** [comment]
Maybe not a bug-bug, but its misleading, especially with longer descriptions, when you actually want to scroll :(
