### ISSUE TITLE
Page wrap animation leaves rest of screen buggy

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#3232]
**Describe the bug**
There is black screen around small spellbook during page wrap animation

**Game logs**

**To Reproduce**
1. Turn off large spellbook
2. With many spells in spellbook wrap page during battle or adventure map

**Expected behavior**
No black background around spellbook

**Actual behavior**
Black background appears

**Did it work earlier?**
Works correctly in VCMI 1.3.2

**Screenshots**
![obraz](https://github.com/vcmi/vcmi/assets/9436577/fcd1515c-7f2a-47e3-baae-b722693a112e)

**Version**
 - Linux
 - Version: 1.4 beta

**Comment by IvanSavenko** [comment]
Likely due to recent changes to video player - this animation is actually a video

**Comment by Laserlicht** [comment]
> Likely due to recent changes to video player - this animation is actually a video

Yes, it's an video. But I saw the bug a long time ago. It's not new. However, I don't know when it is triggered.

**Comment by Laserlicht** [comment]
Fixed with #3343
