### ISSUE TITLE
Assert fail when entering new game screen in debug version with specific map

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#3233]
**Describe the bug**
Apparently assert fails during json parsing of some map

**To Reproduce**
1. Add attached map [map.zip](https://github.com/vcmi/vcmi/files/13467820/map.zip)
2. Start new game while using debug build

**Expected behavior**
Map list loads correctly

**Actual behavior**
VCMI quits - assert failed

**Did it work earlier?**
Yeah, some time ago in earlier 1.4 versions

**Version**
 - OS: Linux
 - Version: 1.4 beta

**Comment by IvanSavenko** [comment]
Ugh, apparently our json map format uses numeric identifiers to identify stuff (e.g. artifact ID) even though they are not guaranteed to be same in mods and embeds locale-specific strings - I got message in Polish on winning this map.

Will fix, but no idea why this was needed in the first place...
