### ISSUE TITLE
Crash at random map generating process.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#3247]
**Describe the bug**
Game crash during generating random map. Console says about sth wrong with monoliths. It happens quite often.

**Game logs**
![image](https://github.com/vcmi/vcmi/assets/29593042/ab925d7a-64d0-4888-bd20-2041723ce72e)

**To Reproduce**
1. Try to generate many random maps

**Expected behavior**
Game should start, not crash

**Actual behavior**
Game crashes

**Did it work earlier?**
Yes.

**Version**
 - OS: [e.g. Windows]
 - Version: [db from 26th November]

**Additional context**
- No mods, only vcmi-extras.

**Comment by IvanSavenko** [comment]
Should be fixed in beta build
