### ISSUE TITLE
Crash when ending Turn

### ISSUE THREAD

**Issue by Arthan-the-one** [vcmi/vcmi#3251]
**Describe the bug**
VCMI crashes reproducibly when selecting End Turn, appearantly (see logs) during Tans turn after 1/2 Battles

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/13536772/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13536773/VCMI_Server_log.txt)
[server_log.txt](https://github.com/vcmi/vcmi/files/13536774/server_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/13536775/VCMI_Launcher_log.txt)

**To Reproduce**
1. Start VCMI with WoG and HotA enabled
2. Load the attached savegame
3. Click "End Turn"
4. (Game Crashes)

**Expected behavior**
AI Takes turns as usual and new turn eventually starts

**Actual behavior**
VCMI crashes without any error messages

**Did it work earlier?**
Ending turns worked in the savefile until this very turn

**Version**
 - OS: Linux (Mint 21.2)
 - Version: 1.3.2+ppa1~ubuntu22.04.1

**Additional context**
[exitsave.zip](https://github.com/vcmi/vcmi/files/13536783/exitsave.zip)

**Comment by IvanSavenko** [comment]
Known issue in 1.3.2, fixed in 1.4
As as workaround - you change combat AI in battles from BattleAI to StupidAI. 
However keep in mind that StupidAI is worse than BattleAI.
