### ISSUE TITLE
`Next Hero` and `Revisit Object` buttons are always blue and don't use player color

### ISSUE THREAD

**Issue by Alexander-Wilms** [vcmi/vcmi#3268]
**Describe the bug**
The two buttons are always blue.

**Game logs**
Probably not relevant

**To Reproduce**
1. Start game with a player color other than blue

**Expected behavior**
The entire UI uses the player color

**Actual behavior**
`Next Hero` and `Revisit Object` buttons are always blue and don't use player color

**Did it work earlier?**
Yes, e.g. in VCMI 1.4.0.0b9eb25c1326105d6ed647a277997158ce32211b
Cf. https://github.com/vcmi/vcmi/issues/2984

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/3226457/f4dd7fcd-e747-4304-b36b-f425fb8a7c4f)

![image](https://github.com/vcmi/vcmi/assets/3226457/60ed355a-f833-4b6f-bf75-eb0b43f434bb)

**Version**
 - OS: openSUSE 20231206
 - Version: 1.4.0

**Additional context**

**Comment by Laserlicht** [comment]
Same problem with german translation (translated PNGs).

Worked already.

**Comment by Laserlicht** [comment]
Interestingly, I can currently only observe this problem with the Flatpaks. No idea why. DEB and self-compiled versions seem okay. Just like the Android version.

**Comment by Alexander-Wilms** [comment]
Freedesktop SDK 23.08 uses SDL_image 2.6:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/23.08/elements/components/sdl2-image.bst?ref_type=heads

SDL_image 2.8 fixed this issue:
https://github.com/libsdl-org/SDL_image/releases/tag/release-2.8.0

The Flatpak manifest has been updated to use the newer version.

**Comment by kambala-decapitator** [comment]
@Alexander-Wilms so this is SDL_image issue and not flatpak-specific? Hence other platforms also need to switch to v2.8?

**Comment by IvanSavenko** [comment]
@kambala-decapitator 
https://github.com/libsdl-org/SDL_image/releases

2.6.0
> Added stb_image as the default backend for JPG and PNG images loading.
To use libpng and libjpg instead, configure using --disable-stb-image

2.8.0
> PNG images with a palette are loaded as SDL surfaces with a palette

So versions 2.6.X are affected. All others, both older and newer, are fine.
