### ISSUE TITLE
Client is unable to connect to the server again

### ISSUE THREAD

**Issue by luk3ZPL** [vcmi/vcmi#3271]
**Describe the bug**
When 1000+ ms passed in another connection attempt and connection is aborted by the user then another connection to the server is not possible.

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Click Single Player
2. Wait 1000+ ms when Connecting window appear
3. Abort/Cancel connection
4. Try co connect to server again via Single Player or Load the game buttons

**Expected behavior**
Always connect to the server.

**Actual behavior**
Connection to the server is stuck.

**Did it work earlier?**
VCMI 1.3.2 always connected to the server even if aborted (Abort/Cancel didn't worked)

**Screenshots**
-

**Version**
 - OS: W7/W10
 - Version: [VCMI version]

**Additional context**
[vcmi_logs.zip](https://github.com/vcmi/vcmi/files/13623741/vcmi_logs.zip)

**Comment by IvanSavenko** [comment]
Will look into it after #3477 
Main cause is quite simple - we actually have no way to forcefully terminate a server from client other than disconnection. And here game aborts connection attempt before server accepted it.

Simple solution would be to not allow cancelling local server startup.

Proper solution would be to replace our vcmiserver startup with boost::process calls on desktop system.
And for mobiles we'll need "proper" single-app mode, with option to control server thread from client code.
