### ISSUE TITLE
FIXME: CBattleInfoEssentials::battleGetFightingHero wrong argument!

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3276]
**Describe the bug**
Press end turn and look logs

**Version**
 - OS: [e.g. Windows10]
 - Version: [VCMI version 1.4]

[fix.zip](https://github.com/vcmi/vcmi/files/13624528/fix.zip)

**Comment by IvanSavenko** [comment]
Huh, nice find.

Apparently calculation for fire shield damage bonuses (e.g. from fire Orb) was broken unless this is battle between red & blue.

**Comment by Povelitelh3** [comment]
If be honest it was not very hard. This issue common very often.
