### ISSUE TITLE
A submod is shown as active when parent mod is disabled

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#3277]
![image](https://github.com/vcmi/vcmi/assets/15194321/d13679e2-27fc-438f-ac54-5d454bf8dc8c)

It would help to indicate somehow that the mod setting is saved, but is currently not active. (greyed checkmark)

Also when a mod has submods that are disabled, it would help to indicate that somehow. Right now is the same green check mark even if some submods are not enabled.

**Comment by IvanSavenko** [comment]
Actually seems to be bug of "submods of submods".

For disabled mods launcher shows all its direct submods as disabled as well

**Comment by IvanSavenko** [comment]
Implemented in #4787, now such mods should have greyed-out status icon
