### ISSUE TITLE
Lack of video subtitles in campaign video

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3284]
**Describe the bug**
Subtitles in campaign video are not displayed correctly

**Screenshots**
![Lack of video subtitles](https://github.com/vcmi/vcmi/assets/2566990/e964a44c-03c2-40cc-8554-c1295caf85cc)

**Additional context**
Reported on Dicord by Popularny Proszek

**Comment by IvanSavenko** [comment]
Unable to reproduce on my system

**Comment by kodobi** [comment]
I reinstalled VCMI and issue seems to no longer appears. Previously I had updated from 1.4 from 1.3.2 via Google Play
