### ISSUE TITLE
Crash on AI turn

### ISSUE THREAD

**Issue by godric3** [vcmi/vcmi#3290]
**Describe the bug**
Game crash on AI turn

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/13627673/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13627674/VCMI_Server_log.txt)
[server_log.txt](https://github.com/vcmi/vcmi/files/13627675/server_log.txt)

Savefile
[crashAI.zip](https://github.com/vcmi/vcmi/files/13627672/crashAI.zip)

**To Reproduce**
1. Load attached save (used mods:
2. End turn
3. Game crash on brown AI turn

**Expected behavior**
No crash

**Actual behavior**
Game crash on brown AI turn

**Version**
 - OS: Windows 10
 - Version: 1.4

**Additional context**
Used mods:
 - ZEFix
 - VCMI extras
![image](https://github.com/vcmi/vcmi/assets/18197844/7b063138-f393-4f02-933f-2a471db1dd86)

Used AI:
![image](https://github.com/vcmi/vcmi/assets/18197844/0d7de471-e348-40eb-b6e9-a08aed1ac8a2)

**Comment by nullkiller** [comment]
AI simturns disabled?

**Comment by IvanSavenko** [comment]
No simturns according to logs

**Comment by godric3** [comment]
Yes, I didn't even opened that screen until now, and AI sim turns are disabled

**Comment by nullkiller** [comment]
Bad RMG generation. 
![image](https://github.com/vcmi/vcmi/assets/5644734/2bfee276-46c6-41d8-aaa0-2f90c5397fea)

**Comment by nullkiller** [comment]
Looks like it is just in rock

**Comment by nullkiller** [comment]
Still looks like fix is possible to just skip this bad gate

**Comment by nullkiller** [comment]
Accidently pushed fix right into beta

**Comment by IvanSavenko** [comment]
Closing then?

**Comment by nullkiller** [comment]
Likely. At least save works no
