### ISSUE TITLE
Pandora Box on Titans Winter doesn't grant reward

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3293]
**Describe the bug**
It should grant Dragon Scale armor. Displays custom message, but artifact is not given.

**Steps to reproduce**
Load Titan's Winter, west of town there's one and only pandora's Box.

Failed oto reproduce with all mods disabled:
<img width="335" alt="image" src="https://github.com/vcmi/vcmi/assets/2566990/03864027-0090-485e-a8f9-fa27ab2fec10">

**Additional context**
Observed on Dydzio's Twitch: https://www.twitch.tv/videos/2000374385

**Comment by DjWarmonger** [comment]
@dydzio0614

**Comment by dydzio0614** [comment]
grails in artifact merchant bug also does not want to reproduce randomly
