### ISSUE TITLE
RMG create shipyard that can't spawn boats

### ISSUE THREAD

**Issue by godric3** [vcmi/vcmi#3294]
**Describe the bug**
Shipyard is placed in such way that it's impossible to buy boat there

**Map**
[20231210T191543_Jebus Cross_1702232142.zip](https://github.com/vcmi/vcmi/files/13628839/20231210T191543_Jebus.Cross_1702232142.zip)

**To Reproduce**
Generate maps with water and look for shipyards similar to one on screenshot

**Did it work earlier?**
Looks like something similar was reported and fixed earlier https://github.com/vcmi/vcmi/issues/939

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/18197844/a78da4b1-ed8b-4909-843d-624b94bf6978)

**Version**
 - OS: Windows 10
 - Version: 1.4

**Additional context**
May be connected to blocked gate shown in https://github.com/vcmi/vcmi/issues/3290#issuecomment-1849009410

**Comment by DjWarmonger** [comment]
According to description, it should work - so it's rather bug in mechanics than RMG bug:

https://heroes.thelazy.net/index.php/Shipyard
<img width="89" alt="image" src="https://github.com/vcmi/vcmi/assets/2566990/058291d0-6c7e-4a12-93f5-0b7537d57537">

**Comment by godric3** [comment]
Hmm.. Same for me, if I create such placement in map editor it works. Even after getting similar case in another random map it works. It looks like I was to quick to report a bug, maybe I was missing resources... 
I guess this can be closed

**Comment by IvanSavenko** [comment]
Have you seen boat purchase window?
If yes - then this is likely lack of resources.

If shipyard is blocked you should see "Ways are blocked" message instead

**Comment by godric3** [comment]
Yes, purchase windows was there, so it was my mistake
