### ISSUE TITLE
Can't create Random map H size +7AI

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3296]
**Describe the bug**
Before I could create map on teamplate 8xm8 for example. Now I can't do it.
Crash happens

![изображение](https://github.com/vcmi/vcmi/assets/36762538/23eb0ffa-1ab7-4893-9d54-5bf17da4397a)

 - Version: [VCMI version 1.4]

**Comment by DjWarmonger** [comment]
I fixed this today, but will check
