### ISSUE TITLE
Heroes banned on random map are different than heroes in prisons

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3297]
**Describe the bug**
Heroes put in Prisons are not banned on random maps. **Some** heroes get banned, but they don't match the ones in Prisons.
They can likely be rolled as heroes in taverns, leading to all sorts of issues, like #3295 

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**

- Launch Map Editor
- Generate Jebus XL
- Check Prisons
- Check list of heroes banned in map options

**Expected behavior**
Every hero put in Prison should be banned from the map

**Actual behavior**
Random heroes are banned

**Comment by IvanSavenko** [comment]
Could also be the cause for duplicated heroes, e.g.  #2299 ?

**Comment by DjWarmonger** [comment]
Likely related to #3300

**Comment by godric3** [comment]
I investigated this a bit and what I think is happening:
- https://github.com/vcmi/vcmi/blob/29eab0fdbeb8e12407a0766618f5bed2164c9925/lib/rmg/modificators/TreasurePlacer.cpp#L106-L120
`TreasurePlacer::addAllPossibleObjects` create object info with generateObject funtion that when executed will ban hero in prison
- generateObject is called here in `TreasurePlacer::constructTreasurePile` https://github.com/vcmi/vcmi/blob/29eab0fdbeb8e12407a0766618f5bed2164c9925/lib/rmg/modificators/TreasurePlacer.cpp#L643
- but it may happen that this object will not be placed on map(but is already generated so hero is banned) `TreasurePlacer::createTreasures`
https://github.com/vcmi/vcmi/blob/29eab0fdbeb8e12407a0766618f5bed2164c9925/lib/rmg/modificators/TreasurePlacer.cpp#L934-L946

This will led to situation that more heroes will be banned(heroes from prison on map are banned, but also heroes from prison that were not placed on map)

Additionally map editor in `MapController::repairMap` will unban all heroes that are placed on map
https://github.com/vcmi/vcmi/blob/29eab0fdbeb8e12407a0766618f5bed2164c9925/mapeditor/mapcontroller.cpp#L134

This ends up with heroes from prison placed on map not banned, and heroes from prison not placed on map banned.

I suspect the same happens with quest artifacts:
https://github.com/vcmi/vcmi/blob/29eab0fdbeb8e12407a0766618f5bed2164c9925/lib/rmg/modificators/TreasurePlacer.cpp#L454-L471
https://github.com/vcmi/vcmi/blob/29eab0fdbeb8e12407a0766618f5bed2164c9925/lib/rmg/modificators/TreasurePlacer.cpp#L502
https://github.com/vcmi/vcmi/blob/29eab0fdbeb8e12407a0766618f5bed2164c9925/lib/rmg/modificators/TreasurePlacer.cpp#L524

I'm not sure how to fix that as it will probably require changing rmg flow

**Comment by DjWarmonger** [comment]
Thanks. I already have the fix for deleting Prisons, but `MapController::repairMap` is quite a stab in the back.

**Comment by DjWarmonger** [comment]
Okay, new discovery: Imprisoned heroes in HoTA are actually not banned in a map, so they can be rehired once they are defeated. VCMI keeps track of active heroes and doesn't allow them to show in tavern, still.
