### ISSUE TITLE
Crash after lost in battle (and in game)

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3301]
**Describe the bug**
AI hero attacked me. I press autofight.  After that I press OK and game has been crashed. (server fail)

**Version**
 - OS: [e.g. Windows10]
 - Version: [VCMI version 1.4]
[Lose.zip](https://github.com/vcmi/vcmi/files/13634917/Lose.zip)

**Comment by IvanSavenko** [comment]
Fixed in beta build
