### ISSUE TITLE
Scholars can only be refused while teaching primary skills

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#3313]
While visiting a scholar, three conditions will happen, which include teaching primary skills, one new spell and one new skill.
Actually if I add a line: "canRefuse": true, only the first condition can be refused.
For example, if he teaches Eagle Eye or Learning, it is still obligatory.

**Version**
 - OS: Windows
 - Version: 1.40

**Comment by IvanSavenko** [comment]
Fixed in 1.4.2
