### ISSUE TITLE
Hero defeated in battle doesn't ever replenish movements point when available again in tavern

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3322]
**Describe the bug**
When hero is defeated in battle, he can be recruited in tavern few days later. However, he does not replenish his movmenet points when recruited.

**Expected behavior**
Hero should replenish movement ona  new day, even when in tavern.
However, hero running or surrending shouldn't replenish movement instantly.

**Actual behavior**
Recruited hero has 0 movement points.

**Version**
1.4.1

**Additional context**
Reported by wnukos on Polish Discord

**Comment by Alucard648** [comment]
I think, it`s intentional to prevent dirty hit and run tactics.

**Comment by dydzio0614** [comment]
i dont think so, this needs to be changed anyway

**Comment by Phanquan** [comment]
better that way

**Comment by dydzio0614** [comment]
no, wnukos is competitive player and 1mm template tournament winner, if this is something reported by him as to be changed then it will be changed

**Comment by Povelitelh3** [comment]
This is an old bug

**Comment by IvanSavenko** [comment]
Unable to reproduce.
- Retreating from battle and recruiting the hero on the same day - movement points and mana stay the same
- Retreating from battle and recruiting the hero on next day - movement points are replenished, mana regains partially (1+mysticism bonus)

Both cases match H3 behavior

**Comment by dydzio0614** [comment]
when you dismiss hero and he appears in tavern few days later he should not have 0 movement points

**Comment by IvanSavenko** [comment]
Ah, dismiss, not retreat

**Comment by dydzio0614** [comment]
or lose via being killed
