### ISSUE TITLE
Jebus Cross template is too square

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#3332]
Original in HotA:
![image](https://github.com/vcmi/vcmi/assets/15194321/7f030e7f-0bdd-4bfc-9fa9-065a750a8823)

A more squarish one in VCMI:
![image](https://github.com/vcmi/vcmi/assets/15194321/011d100c-8e04-42a1-85f3-89da6595e70b)

Could the RMG generator be improved to generate more organic maps like the one in HotA?

**Comment by krs0** [comment]
In VCMI more or less you will get a long "boring" diagonal like of mountains as your border.

**Comment by dydzio0614** [comment]
current implementation is intended change to original RMG, ask @DjWarmonger for details

original H3 way would be nice optional feature, but low priority compared to other RMG stuff to do at the moment

**Comment by luk3ZPL** [comment]
For me that one from VCMI is more balanced - it means equal chances for everyone :D

**Comment by DjWarmonger** [comment]
How about now?
<img width="96" alt="image" src="https://github.com/vcmi/vcmi/assets/2566990/a162170f-4171-4aae-be25-433c3554786c">

**Comment by krs0** [comment]
If I did not knew better, I would have said it's a screenshot from HD mod 😜

**Comment by krs0** [comment]
Nice job! 🤗

**Comment by swats-the-floran** [comment]
may i add that this template generates big flat zones? it would be nice to have more decorations and obstacles.
![image](https://github.com/vcmi/vcmi/assets/38055017/79794542-04e7-4d85-914c-d810dd949e19)

**Comment by Alucard648** [comment]
I think, obstacle density should be a zone option in template. Ranging from big flat zone, as shown, up to maze-like structures.

**Comment by swats-the-floran** [comment]
mines are not guarded.

**Comment by DjWarmonger** [comment]
> mines are not guarded.

Did you set monster strength to anything less than `Strong`?

As to overall emptiness - I already improved that a bit in https://github.com/vcmi/vcmi/pull/3636

**Comment by swats-the-floran** [comment]
> > mines are not guarded.
> 
> Did you set monster strength to anything less than `Strong`?
> 
> As to overall emptiness - I already improved that a bit in #3636
> 
> Also, the original issue is closed. If you have any other complains, start another ticket.

i mostly set monsters to normal. but it looks like it doesn't override template's setting as "weak". after i edited the template, mines became guarded.
