### ISSUE TITLE
Terrain texture is not as clear as in OH3

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3353]
**Describe the bug**
Terrain texture (generated randomly) has more patches and details, making the map less readable.

**Game logs**
Just generate random map with VCMI and HoTA. Observe snow or sand terrain.

**Expected behavior**
Texture should be clear, with very little patches.

**Actual behavior**
Texture is messy.

**Did it work earlier?**
Doubt it.

**Screenshots**
VCMI: 
![image](https://github.com/vcmi/vcmi/assets/2566990/37ce0833-884a-42d0-81fd-13647560fe42)
HoTA:
![image](https://github.com/vcmi/vcmi/assets/2566990/95ec0071-c249-4cc2-9ece-fdca972f4333)

**Additional context**
I don't know how this terrain is generated, maybe @Nordsoft91 knows.

**Comment by IvanSavenko** [comment]
I think H3 editor even has slider to control "messiness" (called "amount of decorations" or something like this)

Looks like H3 tileset consists from two blocks. In case of snow:
- tiles 49-56: 8 tiles with smooth snow
- tiles 57-72: 16 tiles with "decorations"
However vcmi treats them as single block:
https://github.com/vcmi/vcmi/blob/develop/config/terrainViewPatterns.json#L88

Not sure how to solve this in our terrain painter though.
