### ISSUE TITLE
Towns and Heroes reordering

### ISSUE THREAD

**Issue by Phanquan** [vcmi/vcmi#3358]
**Describe your proposal**
- Towns and Heroes reordering should be saved when reloading save game
- The town portal spell should show the reordered towns

**Additional context**
- Long click to show the navigation icons instead of swiping or scrolling (optional)

**Comment by Laserlicht** [comment]
>     * Long click to show the navigation icons instead of swiping or scrolling (optional)

You mean on PC? On Mobile long click interference with "Right" Click. Wouldn't it better to add possibility to order with keyboard? E.g. Page up/down while hovering town.

**Comment by Phanquan** [comment]
> > ```
> > * Long click to show the navigation icons instead of swiping or scrolling (optional)
> > ```
> 
> You mean on PC? On Mobile long click interference with "Right" Click. Wouldn't it better to add possibility to order with keyboard? E.g. Page up/down while hovering town.

I mean  long tap on mobile (and possibly, right-click also), navigating on mobile sometimes causes accidently reordering, and long tap on town shows info which is useless anyway
