### ISSUE TITLE
Genie / djinn spellcasting attempts bypass immunities from spell config

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#3365]
Casting spells with djinns results in wasting turn and spell not being applied when creature is immune to randomly chosen spell. VCMI 1.4

**Comment by IvanSavenko** [comment]
@dydzio0614 
I think you should be able to simulate casting to check whether spell can be casted.
See BattleActionsController::isCastingPossibleHere

We need to either
a) Call this method in BattleActionsController::actionIsLegal method when handling RANDOM_GENIE_SPELL case
b) Add similar logic into CBattleInfoCallback::getRandomBeneficialSpell method

**Comment by IvanSavenko** [comment]
Fixed in 1.4.2
