### ISSUE TITLE
Some differences in logic for retreating for heroes with patrol set in map editor

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#3373]
In fist mission of hack & slash campaign there is battle at beginning - in VCMI AI hero can retreat, apparently in H3 he does not retreat even when overwhelmed with army from archangels cheat (has patrol set to be stuck in place)

Research needed if AI heroes retreat in H3 with patrol settings equal to 10 tiles etc. and if they can appear in tavern at all after being defeated (i guess hero banning per map in original H3 map editor may be handy for testing them).

**Comment by nullkiller** [comment]
I think it should be ease to implement if not taking into account *research*. Never retreat if hero has patrol settings

**Comment by IvanSavenko** [comment]
Related issues:
- AI should not trade troops with patrolling heroes
- AI should not trade troops with owned garrisons even if garrison has removable troops - this is needed for H3 campaigns

**Comment by misiokles** [comment]
Maybe AI could trade troops with owned garrisons at higher difficulties? (160%, 200%)?

**Comment by IvanSavenko** [comment]
> Also AI does not intentionally take troops from garrison but may do this while walking through it. I can disable it if needed.

Current behavior is fine. H3 AI actually can use troops in garrisons except for one campaign mission. And I've added check for that mission.
