### ISSUE TITLE
Delete save from saved games list

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#3389]
**Describe your proposal**
Heroes 3 actually allows deletion of saves - via "Delete" key.
However this option
1) not obvious
2) not available on mobile platforms which vcmi needs to account for

VCMI currently does not provides this option in any form however. We need to:
1) Implement such option to begin with. Ideally - should be done as request to server since saves *should* be loaded by server, not client.
2) Assign this option to "delete" key AND add button in UI. For example - in place of random map dialog (not available from save/load game UI)
3) Consider how to handle saves for old versions of the game. We should either display all saves to allow their deletion or add option to delete all outdated saves

**Comment by Laserlicht** [comment]
Should also be possible: delete entire folder (especially autosaved ones)
