### ISSUE TITLE
Campaign description goes missing after completion of first scenario

### ISSUE THREAD

**Issue by peterpaulis** [vcmi/vcmi#3412]
**Describe the bug**
In Armagedons blade - Dragon Slayer campaign, after completing the first scenario, the map shows missing description and also in intro the missing description text is displayed

- this is strange, as for the first scenario the description was present 

**To Reproduce**
1. go to Armagedons blade - Dragon Slayer campaign
2. win first scenario 
3. on second scenarios, the Campaign description disappears

**Expected behavior**
see the campaign descriptions and intro texts

**Actual behavior**
a placeholder is displayed

**Did it work earlier?**
- never seen this before in 1.3, but didn't play this exact campaign in 1.3

**Screenshots**

<img width="1552" alt="Screenshot 2024-01-01 at 13 06 35" src="https://github.com/vcmi/vcmi/assets/1956972/2f2eb9e0-c94b-419c-8f98-4708bb76c4e3">

**Version**
 - OS: iPad
 - Version: 1.4.2
 
 - no additional mods, or translations used, the vanilla 1.4.2

**Comment by Laserlicht** [comment]
maybe related to https://github.com/vcmi/vcmi/issues/3403

**Comment by IvanSavenko** [comment]
Unable to reproduce unfortunately.
Do you use any mods?
Can you reproduce this bug by using 'vcmiwin' cheat?
Can you upload saves before finishing scenario?

**Comment by peterpaulis** [comment]
- using vcmiwin i am not able to reproduce
- when loading the same before win of the 1 scenario, and completing it, the bug didn't happen
- campaign win screen doesn't show campaign name similar to https://github.com/vcmi/vcmi/issues/3403

<img width="1206" alt="Screenshot 2024-01-04 at 19 52 57" src="https://github.com/vcmi/vcmi/assets/1956972/0036bbb7-1abd-4f56-82b6-a0d548ee54d4">

- i noticed however smth. strange, clean start VCMI and load the attached save 1010x and kill the azure dragons
[1010x.vsgm1.zip](https://github.com/vcmi/vcmi/files/13834420/1010x.vsgm1.zip)
the placeholder description is show
- start the campaign from start and use vcmiwin, than load the 1010x and the description is suddenly there

maybe some lazy load issue?
