### ISSUE TITLE
Horn on the Abyss 1.7

### ISSUE THREAD

**Issue by henioStraszny** [vcmi/vcmi#3417]
**Describe your proposal**
As of now, last version of HOTA accessible in VCMI launcher is  1.6.32.

There is a new version 1.7.

Please provide new version of HOTA.

**Additional context**
[https://heroes3wog.net/horn-of-the-abyss-v1-7-with-factory-was-released-full-changelog/](https://heroes3wog.net/horn-of-the-abyss-v1-7-with-factory-was-released-full-changelog/)

**Comment by by003** [comment]
https://github.com/vcmi-mods/horn-of-the-abyss/issues/83
I am now creating the plan for creating factory town in VCMI.
Some of them still need the help of VCMI main part.
Some sophisticated abilities cannot be duplicated here, however, I can create substitute options.

First strike and unlimitation retailation abilities need to have a subtype for ranged attack, is it easy to realize now?

**Comment by by003** [comment]
Halflings and armadillos can be realized now.
Engineers' ability is repair, a substitute plan is using spellcaster, to cast a repair spell with 50 times.
For automatons, there is no bonus which trigger after death, I think the bonus like SPELL_AFTER_DEATH need to be created first. 
For sandworms, a plan B for their moving is just teleport, but original def files must be edited. I will create a plan for devouring corpse as well.
For gunslinger, just create a subtype of first strike and unlimitation retaliation.
For couatls, I used to make it available in a spell effect. But now damages can only reduced by 99%. Creatures can cast themselves now as well. 
For juggernauts, a widely breath attack can be chosen as plan B. However, the def files need to be edited.

**Comment by Alucard648** [comment]
What we really need is scripting engine for all those edge cases. Mods like Legacy of Silence also benefit from scripting stuff.

**Comment by by003** [comment]
Just discuss it in [#83](https://github.com/vcmi-mods/horn-of-the-abyss/issues/83)

**Comment by by003** [comment]
@DjWarmonger Maybe close this issue and talk it in hota 1.7 pull requests.

**Comment by dydzio0614** [comment]
maybe lets wait a while until this issue goes off github issues first page so people can easily stumble upon it while it lasts

**Comment by IvanSavenko** [comment]
Available in mod repository for 1.6
