### ISSUE TITLE
Audio and video are out of sync in opening movie

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#3427]
**Describe the bug**
Audio and video clearly play at different speed. Noticeable at the very least at NWC logo, and clearly visible during Catherine Arrival movie - for example trumpet sound plays way before corresponding part of video.

This is *extremely* noticeable on my Android system. On desktop it is way less noticeable, but still exists.

**To Reproduce**
1. Start game and do not interrupt intro
2. Listen closely to final part of NWC logo (where ray of light shines on logo)
3. Wait for Catherine arrival to start
4. Listen closely for when sailor on top of the mast plays trumpet near the start of the clip

**Expected behavior**
Audio and video are syncronized

**Actual behavior**
- desktop: audio is slightly ahead of the video
- my Android system: audio is way ahead of the video
- report from Google Play: audio is corrupted, probably played at higher speed than should be

**Version**
 - OS: Android
 - Version: 1.4.2

**Comment by Laserlicht** [comment]
Yes, also noticed on weaker CPU's (smartphone, etc.).

But I think it's not that easy to fix. Current implementation extracts audiostream from video and use SDL_Mixer to output. I think this way it's not possible to synchronize.

Issue is also related to: https://github.com/vcmi/vcmi/issues/3025
We don't support audio from BIK now. This should also be fixed.
