### ISSUE TITLE
Improving 'Resolve mods' button

### ISSUE THREAD

**Issue by ToRRent1812** [vcmi/vcmi#3428]
**Describe your proposal**
Hi, imagine situation where I have vcmi with some mods installed, and I'm inviting a friend to quickly play online through lobby system. My friend installed vcmi launcher and he doesn't have mods installed. When he joins a lobby, he sees a list of missing mods that needs to be resolved. Clicking resolve does nothing because mods are not installed on his pc.

My proposal is to improve functionality of this and give launcher option to download missing mods(add to download queue) and set mods/submods active/inactive for full compatibility.
At the end of the match, launcher will ask player about bringing back previous mod configuration or to keep the current one

With this change, it would be much easier to host lobbies and invite friends.

**Comment by dydzio0614** [comment]
Launcher lobby will be removed and replaced with better ingame lobby so bunch of stuff will change, anyway thank you for report

**Comment by IvanSavenko** [comment]
Irrelevant, launcher lobby has been removed in 1.5
