### ISSUE TITLE
vcmibuilder/innoextract program cant extract from installer 

### ISSUE THREAD

**Issue by AD17102** [vcmi/vcmi#3434]
When I'm trying to extract the .exe file using 'innoextract', It creates the directories but failes to get the data. 

Command: 
```  
innoextract --output-dir=/home/ad/Games/HoMM3 setup_heroes_of_might_and_magic_3_complete_4.0_.exe  
```

Here is the exact output: 
```

Extracting "Heroes of Might and Magic® 3 - Complete" - setup data version 5.6.2 (unicode)
 - "app/random_maps/"
boost::filesystem::directory_iterator::construct: No such file or directory
Done with 1 error.
```
Like I said, It managed to create the directories but failes to put anithing in them ...

I'm running on Linux Mint 21 x86 and just added the repository and installlec vcmi. 
It probably has to do something with the installer itself but I don't know  how it can be fixed

**Comment by IvanSavenko** [comment]
These installers consist from 2 parts: exe and bin.
Both are required and must be placed in the same directory.

Also not sure how innoextract detects .bin - I think that you have renamed .exe? You might need to rename .bin to same patter or restore original names

**Comment by AD17102** [comment]
I tried renaming the bin to a .exe but it still gives me the same error. 
should the filename be called
```
setup_heroes_of_might_and_magic_3_complete_4.0_\(28740\)-1.exe 

```
instead of bin or something else? 
Note: I tried runnin the renamed file (the .bin one) and it gave me the error
``` Not a supported Inno Setup installer! ````
I assume it's because it's not meant ot be excecuted like this

**Comment by AD17102** [comment]
Figured out the issue: 

When downloading the files, it saves the .exe ifle as 

```
setup_heroes_of_might_and_magic_complete_4.0_ .exe
```
while it should be named to 
```
setup_heroes_of_might_and_magic_3_complete_4.0_(28740).exe
```
once it's renamed everything works as it should. 
not much of a difference I know but it's good to point it out. 
should we close the issue?

**Comment by IvanSavenko** [comment]
Closing then.
Not sure why the name got changed during download. But does not sounds like vcmi issue.
