### ISSUE TITLE
VCMI first install: read default H3 install path from registry on Windows

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#3437]
As in title - when you import H3 data via welcome screen on Windows, default location on opening file picker should show H3 installation folder read from Windows registry.

Hota does this and it makes installing easier.

**Comment by Laserlicht** [comment]
> Hota does this and it makes installing easier.

I don't think HotA is doing this...

At least for me it's incorrect every time and I have to select Folder manually when installing HotA:
![grafik](https://github.com/vcmi/vcmi/assets/13953785/3aecb154-fb3a-47f3-92e9-331d5d81e67d)

**Comment by dydzio0614** [comment]
idk about 1.6 or 1.7 but i am pretty sure early hota versions were doing this

**Comment by Laserlicht** [comment]
Ah, tested it... It can detect a CD-based install. But not GOG install.

**Comment by Laserlicht** [comment]
Here are the two Reg-Entries with the path:
```
HKEY_LOCAL_MACHINE\SOFTWARE\GOG.com\Games\1207658787\path
HKEY_LOCAL_MACHINE\SOFTWARE\New World Computing\Heroes of Might and Magic® III\1.0\AppPath
```
