### ISSUE TITLE
[wog][crash] checking commander info at battlefield crashes vcmi

### ISSUE THREAD

**Issue by swats-the-floran** [vcmi/vcmi#3446]
**Describe the bug**
vcmi crashes if you try to check commander info during the battle by clicking on them. if happens after getting 11 level for some reason.

**Game logs**
console log:
```
...
LoadFrame error: Request for frame not present in CAnimation! File name: SPRITES/stackWindow/levels, Group: 0, Frame: 11
GetImage error: Request for frame not present in CAnimation! File name: SPRITES/stackWindow/levels, Group: 0, Frame: 11
Unable to find localization for string 'vcmi.stackExperience.rank.11'
/usr/include/c++/13.2.1/bits/stl_vector.h:1144: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>; const_reference = const unsigned int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Network error receiving a pack. Connection has been closed
```
[server_log.txt](https://github.com/vcmi/vcmi/files/13851471/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/13851472/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13851473/VCMI_Server_log.txt)

**To Reproduce**
1. Start a scenario
2. get 11th level (vcmiexp 18000)
3. attack some nearby monsters
4. click on commander to open his status window

**Expected behavior**
Opens commander info window.

**Actual behavior**
vcmi crashes. 

**Did it work earlier?**
no information.

**Screenshots**
no need.

**Version**
 - OS: Linux 6.1.69-1-MANJARO
 - Version:1.4.2
 - WoG: 9.1.9

**Additional context**
tried different skill combinations and commanders.

**Comment by IvanSavenko** [comment]
Probably the same reason as #3429 

What version of gcc and libstdc++ do you have?

**Comment by IvanSavenko** [comment]
And also - how have you installed vcmi? Flatpak? Native package? Own build?

**Comment by swats-the-floran** [comment]
> What version of gcc and libstdc++ do you have?
refugee town worked for me at 1.4.1

gcc: 13.2.1
libstdc++.so.6

**Comment by swats-the-floran** [comment]
> hw have you installed vcmi?

built from arch user repositories.
pkgfile: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vcmi

**Comment by IvanSavenko** [comment]
Ah, I think I know what's wrong.

Arch enables additional checks in libstdc++, which are not enabled in other distros (or at least in Ubuntu).
These checks are not wrong in any way, but might fail since vcmi was never tested with these checks active.

Will try enabling these checks on my system and running vcmi with them.

**Comment by IvanSavenko** [comment]
Confirmed, will fix
