### ISSUE TITLE
Campaign screen showing checkmark just after first scenario is compleated

### ISSUE THREAD

**Issue by peterpaulis** [vcmi/vcmi#3450]
**Describe the bug**
The check mark is shown not after campaign completion, but just after first scenario completion

**To Reproduce**
1. Go to AB campaign
2. Select a campaign
3. Win first scenario

**Expected behavior**
the check mark on the campaign slot is shown after whole campaign completion

**Actual behavior**
check mark displayed after first scenario win

**Did it work earlier?**
not implemented in 1.3

**Screenshots**
<img width="684" alt="Screenshot 2024-01-07 at 11 04 21" src="https://github.com/vcmi/vcmi/assets/1956972/44a6e1d9-2f03-42ef-9648-2dca5eeabe30">

**Version**
 - OS: iPad
 - Version: 1.4.2

**Comment by Laserlicht** [comment]
Fixed in beta
