### ISSUE TITLE
Assert triggered: Statusbar

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#3461]
**Describe the bug**
This assert is triggered: https://github.com/vcmi/vcmi/blob/ae79c5e9530857c0e23d3da235d2f35fc0c79a90/client/adventureMap/CInGameConsole.cpp#L246

**To Reproduce**
1. type in a cheat (or any text)
2. Do not press enter
3. click in adventure map
4. click back in status bar
5. assert triggered

**Did it work earlier?**
Idk.

**Version**
 - OS: Linux
 - Version: latest beta

**Comment by dydzio0614** [comment]
idk if asserts are good to report, i triggered at least 10 different asserts when using debug builds recently

**Comment by Laserlicht** [comment]
Yes. But in this case you get also an unexpected behavior if you remove the assert: The text is deleted instead the possibility to continue the text.

**Comment by IvanSavenko** [comment]
> idk if asserts are good to report, i triggered at least 10 different asserts when using debug builds recently - @IvanSavenko ?

I triggered 0.
And last time I trggered this assert was when sending messages in hotseat would send message from every player instead of current one.
