### ISSUE TITLE
The app crashes when replay a random map

### ISSUE THREAD

**Issue by JackRainy** [vcmi/vcmi#3490]
**Describe the bug**
I created a random map, played it and liked that. I want to play it once more and I assume it is saved there. When I try to play it, the game just crashes. It happens to any random created map.

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/13930894/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13930895/VCMI_Server_log.txt)

**To Reproduce**
1. Go to New game, Single scenario, choose a random map, generate it and play for a while.
2. Go to New game, Single Scenario.
3. Choose Random map, and click "Show random maps" there.
4. Choose one of the random maps, e.g., the one you played at step 1.
5. Press "Begin".

**Expected behavior**
I would expect the game starts with the chosen difficulty, heroes, etc.

**Actual behavior**
The app crashes.

**Did it work earlier?**
I have never seen it's working before, but I played only 1.4.2. version.

**Version**
 - OS: Android 11
 - Version: 1.4.2

**Comment by IvanSavenko** [comment]
Hi. This is already known issue - see
- #3295

So closing this one as duplicate
