### ISSUE TITLE
Master genie's spell cast crashes the game

### ISSUE THREAD

**Issue by AndreySafronenko-VRP** [vcmi/vcmi#3535]
**Description**
The game is getting crashed when Tower's Master genie cast a spell ability  on an allied troop.

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/13998888/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13998889/VCMI_Server_log.txt)

**Steps to reproduce**
1. Start RMG generated hot seat game as Tower fraction. 
2. Build the Master Genes and Master Gremlins
3. In the battle, try to cast Master genie spell ability on a Master Gremlins troop

**Crash video**
https://github.com/vcmi/vcmi/assets/45426974/506609b1-3982-4ccd-9f2c-dc92a208f52f

**Version**
 - OS: macOS Intel, macOs Ventura 13.6
 - VCMI version: 1.4.4

**Comment by dydzio0614** [comment]
@IvanSavenko :P

**Comment by IvanSavenko** [comment]
Hi. Will be fixed in next release.
If you wish - you can download build from here, it matches 1.4.4 + fix for some crashes, including yours (scroll to the bottom)
https://github.com/vcmi/vcmi/actions/runs/7596535174
