### ISSUE TITLE
[Launcher] Mod loading order

### ISSUE THREAD

**Issue by swats-the-floran** [vcmi/vcmi#3551]
**Describe your proposal**
atm i'm reanimating new-interface-mod and it has a lot of features that extends another mods but for some reason don't work without explicitly setting dependencies.

1.  new-interface-mod -> wake-of-gods.commanders (otherwise commander button is not overriding)
2.  new-interface-mod -> hi-rez-menu (main menu background is not working)
3.  new-interface-mod -> vcmi-extras.quick-exchange (hero exchange screen is not working)
4. small-era-mods -> new-interface-mod (flags not working)

i cannot enable these dependencies by default because not all users want all those mods enabled but if user enables them - 
nothing works. i believe that optional dependencies (mod depends on another mod if one is enabled) should work for mod developer's side or some ui panel where user will be able to manually set mod loading order should work for user's side.

**Comment by IvanSavenko** [comment]
Specifically for "extending other mods" you can use submods, with dependency on mod that you wish to extend.

And if you set submod type to "Compatibility" such submod will be hidden in Launcher and automatically activated/deactivated by game when needed - e.g. when mod itself and all dependencies are active.

**Comment by swats-the-floran** [comment]
like this?
```
{
	"name" : "quick exchange",
	"description" : "overrides vcmi-extras.quick-exchange graphics",
	
	"contact" : "https://forum.vcmi.eu/t/how-to-open-def-sprites/6174",
	"version" : "1.0",

	"modType" : "Compatibility",
	"compatibility" :
    {
        "vcmi-extras.quick-exchange": "1.0"
    }
}
```

**Comment by IvanSavenko** [comment]
Instead if 
```json
	"compatibility" :
    {
        "vcmi-extras.quick-exchange": "1.0"
    }
```
use standard depends / conflicts fields:
```json
	"depends" : [ "vcmi-extras.quick-exchange" ]
```

If this is submod, then it will be hidden from Launcher and active only if `vcmi-extras.quick-exchange` mod is also active

**Comment by swats-the-floran** [comment]
it worked for extending commanders and quick exchange. but what should i do if i want era-small-mods.New Flags mod work with new-interface-mod? i can't make it dependent on each other and can't make it invisible as a small-era-mods submod.

**Comment by misiokles** [comment]
Just enable these two mods separatelly. They don't interfere with each other in any way. No need to force players with too many dependencies.

**Comment by swats-the-floran** [comment]
if i enable new-interface-mod, new flags stops working. probably as a current maintainer i can integrate flag images in new-interface but what if some people won't like it?
