### ISSUE TITLE
Failed to unlock cluster

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3556]
**Describe the bug**
AI hero goes into infinite loop at Subterranean Gate when the other side is guarded.

**Game logs**
```
Player 1 (blue) starting turn, day 116
Goal Composition[Unlock Cluster Hell Hydras(75 3 0), ] [ExecuteHeroChain tile(75 2 0) by Marius => ]  exceeded maxpass. Terminating AI turn.
Hero Pyre has 2112 MP left
Hero Marius has 2196 MP left
Hero Eurydis has 1630 MP left
Hero Nymus has 1630 MP left
Hero Yog has 1560 MP left
Hero Zydar has 1630 MP left
Hero Sam has 1723 MP left
Hero Eyzea has 1760 MP left
Player 1 (blue) ends turn
Player 1 (blue) ended turn
Player 1 (blue) starting turn, day 117
Goal Composition[Unlock Cluster Hell Hydras(75 3 0), ] [ExecuteHeroChain tile(75 2 0) by Marius => ]  exceeded maxpass. Terminating AI turn.
Hero Pyre has 2112 MP left
Hero Marius has 2196 MP left
Hero Eurydis has 1630 MP left
Hero Nymus has 1630 MP left
Hero Yog has 1560 MP left
Hero Zydar has 1630 MP left
Hero Sam has 1723 MP left
Hero Eyzea has 1760 MP left
Player 1 (blue) ends turn
Player 1 (blue) ended turn
```
[bug3556.zip](https://github.com/vcmi/vcmi/files/14034798/bug3556.zip)

**To Reproduce**
Random and rare, however happened to me already twice on "Long Run XL" random map (L + U).

**Actual behavior**
Main hero moves through Suberranean Gate idefinitely until timeout. Other heroes mostly don't move at all.

**Screenshots**
https://github.com/vcmi/vcmi/assets/2566990/0ac9f2f4-026d-480a-bb60-0974b9a2e6ce

**Version**
Develop

**Comment by nullkiller** [comment]
I think it is fixed. There was a bug with subterranean gates.
