### ISSUE TITLE
Mana Vortex (Dungeon) fails with Town Portal spell

### ISSUE THREAD

**Issue by oldfoz** [vcmi/vcmi#3564]
**Description**
I have faced with this issue many times during playing.
I have not found any dependency from type of hero or map.
Every time when I use Town Portal spell and teleport into Dungeon town,
I do not get double points of mana.

Moreover, 
if I exit from the town and enter into it again, 
no effect will be raised as well. 
For all other heroes also. 

**To Reproduce**
Lets just imagine the situation. 
We have heroes A, B, C.
Under normal circumstances, 
the hero A goes into Dungeon and gets double mana,
the hero B goes after hero A and gets double mana,
the hero C goes after B and gets double mana as well.

Now we are waiting for a new week 
to reactivate Mana Vortex 
and spent heroes mana,
and do next:
the hero A uses Town Portal, teleports into Dungeon, and does NOT get double mana,
the hero B goes into town without spell using, and does NOT get double mana,
the same situation for the hero C.

To get a mana bonus, the only one thing we can do in such a situation, 
we need to wait a start of the new week and do not use the portal spell. 

**Did it work earlier?**
I am playing since v1.2.1 I think,
and I observed this issue for all versions I used.

**Game logs**
Will be added later on

**Version**
 - OS: iOS
 - Version: v1.4.4

**Comment by oldfoz** [comment]
> Hota 1.7 fixed issues like this with manual operating of Mana Vortex. In that version you need to actually cklick on Vortex then select hero to apply effect on.

Cool feature, good to know
Thanks!

**Comment by kambala-decapitator** [comment]
> In that version you need to actually cklick on Vortex then select hero to apply effect on.

you mean that now one simply opens Dungeon, goes to MV and it allows selecting hero to apply without the need for the hero to visit Dungeon? That's great QoL improvement.

**Comment by oldfoz** [comment]
> > Hota 1.7 fixed issues like this with manual operating of Mana Vortex. In that version you need to actually cklick on Vortex then select hero to apply effect on.
> 
> Cool feature, good to know Thanks!

But current actual version of Hota is 1.6.36 ))
