### ISSUE TITLE
`Pendant of Negativity` doesn't work

### ISSUE THREAD

**Issue by drogovozDP** [vcmi/vcmi#3568]
**Describe the bug**
If you wear `Pendant of Negativity`, enemy heroes are still able to use `lightning bolt` and `chain lightning`.

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Wear `Pendant of Negativity`
2. Try to fight the enemy hero with these spells: `lightning bolt` and `chain lightning`

**Expected behavior**
The enemy hero won't be able to use `lightning bolt` and `chain lightning`

**Actual behavior**
He is able to use these spells

**Version**
 - OS: macOS ARM
 - Version: 1.4.2

**Comment by DjWarmonger** [comment]
Works for me. Attaching test map:
[TEST Pendant of Negativity.zip](https://github.com/vcmi/vcmi/files/15141073/TEST.Pendant.of.Negativity.zip)

**Comment by drogovozDP** [comment]
> Works for me. Attaching test map: [TEST Pendant of Negativity.zip](https://github.com/vcmi/vcmi/files/15141073/TEST.Pendant.of.Negativity.zip)

Your map worked correctly for me. Can you please check the situation, when you use `Pendant of Negativity` and an enemy uses lightning spells? This is exactly what happened to me

**Comment by DjWarmonger** [comment]
Updated map, added enemy Solmyr. Still he doesn't cast when I equip Pendant.
[TEST Pendant of Negativity.zip](https://github.com/vcmi/vcmi/files/15213782/TEST.Pendant.of.Negativity.zip)

**Comment by DjWarmonger** [comment]
Possibly already fixed, closing. Please reopen if needed.
