### ISSUE TITLE
Battle AI doesn't move at all

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3577]
**Describe the bug**
Enemy walkers stay still in battle and don't move at all, despite attacking player has a shooter and takes them down on by one. Also, it seems that enemy has advantage in army stength, but still doe not attack.

**To Reproduce**
Not sure which battle AI it is.

**Expected behavior**
Enemy units should charge no matter if they have chance of wining or not.

**Actual behavior**
Enemies wait, then just defend and pass turns.

**Did it work earlier?**
Certainly

**Screenshots**
https://www.youtube.com/live/PO8cr_iIIZM?si=Fs2wpfvb0-VDkQPa&t=2280

**Version**
1.4.5

**Comment by by003** [comment]
I found this problem as well in [#3550](https://github.com/vcmi/vcmi/issues/3550#issuecomment-1909345833)

**Comment by nullkiller** [comment]
How about save file?

**Comment by dydzio0614** [comment]
it is very easy to reproduce with right units, but yeah - save would not hurt
