### ISSUE TITLE
Include innoextract in launcher

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#3578]
**Describe your proposal**
We should think about including innoextract directly into the source.

Following benefits:
- We could add a button in the launcher to extract gog files for easiest install
- This would work platform independent without extra tools (also mobile installation possible)
- Could be a solution for adding chronicles without copyright problems

I think most users use the gog packages as base.

**Additional context**
I'm not sure how easy or hard this task is. Seems we don't need lzma libs for heroes 3 installer (tested to extract with lzma disabled build).

I'm not able to do this because I know not much enough about c++ building systems.

**Comment by IvanSavenko** [comment]
Copy of my message from Discord about this: 

There is actually Android app that can extract gog installers... but it does not works with multi-part installers like H3 install...
https://github.com/alanwoolley/innoextract-android/issues/9

If that app gets support for such installers Android-only installation will be possible.

Not sure how difficult it would be to integrate innoextract as part of our executable - it does not have easy-to-extract library that we can use. Not a bad idea, but needs research. Perhaps we can take a look how that app has integrated innoextract.

**Comment by kambala-decapitator** [comment]
First step would be splitting it into lib and app parts (if not already the case) and submitting a PR to upstream

**Comment by Laserlicht** [comment]
The multipart problem of the app would be avoidable with an source integration in vcmi.

We could simply make two file opening request to the user. First ask for the exe and in second step ask for the bin (could be simplified to one dialog on OS without that strict file handling).
