### ISSUE TITLE
Campaign crash

### ISSUE THREAD

**Issue by ninjatao** [vcmi/vcmi#3617]
**Describe the bug**
Game crashes when reaching last scenario of campaign "spoils of war"

**To Reproduce**
1. Start a new campaign "spoils of war"
2. Use "vcmisilmaril" to finish first scenario
3. Use "vcmisilmaril" to finish second scenario
4. Crash

**Did it work earlier?**
1.4.2 works fine. No idea for later versions.

**Version**
 - Android
 - daily build Feb. 14, https://builds.vcmi.download/branch/develop/Android/arm64-v8a/VCMI-branch-develop-9ebd194.apk

**Additional context**

**Comment by lishaoxia1985** [comment]
You can add another bugs which is related to this:
In all Restoration of Erathia campaign, when you touch "scenario information" button in "adventure option", the app will crash.

**Comment by Laserlicht** [comment]
> You can add another bugs which is related to this: In all Restoration of Erathia campaign, when you touch "scenario information" button in "adventure option", the app will crash.

I think this is another bug: It has to do with showing turnTimerInfo in the options window.

**Comment by lishaoxia1985** [comment]
@Laserlicht you are right😁

**Comment by IvanSavenko** [comment]
- Fixed in #3722
