### ISSUE TITLE
Can't change owner in Map Editor

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [vcmi/vcmi#3635]
**Describe the bug**
The owner of a building in a map can't be changed in the Map Editor.

**Game logs**
No crash

**To Reproduce**
1. Update to VCMI 1.5 (`VCMI-branch-develop-110ef5f.exe`)
2. Launch the VCMI Map Editor
3. Generate a map
4. Select a building that can be owned
5. On the inspect tab, change the Owner value (`neutral`, `red`, `blue`...)
6. Click somewhere else

**Expected behavior**
The flags of the building has the new color and the Owner value is updated.

**Actual behavior**
The flags of the building has still the previous color and the Owner value has been restored.

**Did it work earlier?**
Yes, this fall on VCMI 1.4 (develop branch).

**Version**
 - OS: Windows 10,
 - Version: VCMI 1.5 develop branch (`VCMI-branch-develop-110ef5f.exe`)

**Comment by godric3** [comment]
Probably caused by my fix #3541, will try to look into this this week. Until then if needed it's still possible to set object owner while adding it to map(first select player in menu bar)

**Comment by Fabrice-TIERCELIN** [comment]
Successfully tested on `VCMI-branch-develop-4b2cba9.exe`
