### ISSUE TITLE
Import of HOMM III HD Assets

### ISSUE THREAD

**Issue by arandomguysomewhere** [vcmi/vcmi#3642]
Heroes of Might and Magic III HD has thousands of upscaled assets and based on what I've found there currently does not seem to be any way of using these assets with the complete edition of the game. Having a way to import and use the assets from that version with the campaign and other content of the complete edition of the game would be useful for the community.

Maybe including a license check or validation of installed files would be helpful to offset any legal risks to ensure only users with actual ownership of the title can use the assets.

https://store.steampowered.com/app/297000/Heroes_of_Might__Magic_III__HD_Edition/

**Comment by IvanSavenko** [comment]
Duplicate of #1070

Might be possible eventually, but not soon. 
Some early preparatory work is being done (although primary to support better upscale filters), but we have quite a lot of other features to take care of.

**Comment by arandomguysomewhere** [comment]
Thanks for linking the duplicate, I tried searching but either missed the dup or it didn't show up with the search term I used. Will close this issue.
