### ISSUE TITLE
Crash after "Start Game" IPadOS 17.3.1 (vcim ver 1.4.5)

### ISSUE THREAD

**Issue by julia-kits** [vcmi/vcmi#3655]
**Describe the bug**
App crashes after clicking "start game" button
Installed through AltStore, files Data, Maps, Mp3 are copied to vcmi folder

**Game logs**
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/14511019/VCMI_Launcher_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/14511021/VCMI_Client_log.txt)
also attached last ips file

**To Reproduce**
Install the IPA on iPadOS 17.3.1.
Open the application.
Close the release popup
Click "start game" button
Experience the crash.

**Expected behavior**
I expected the game to launch so I can play )

**Actual behavior**
App crashes after clicking "start game" button

**Did it work earlier?**
No idea, this was my first try

**Screenshots**

**Version**
 - OS: [IPadOS 17.3.1]
 - Version: [1.4.5]

**Additional context**
from ips file
`{"app_name":"vcmiclient","timestamp":"2024-03-06 15:47:08.00 +0300","app_version":"1.1.1","slice_uuid":"ac0d5b50-b3ce-36bb-88e4-82bd0d27f3c7","build_version":"2023-02-03-b429f0b","platform":2,"bundleID":"eu.vcmi.vcmiclient.LSC5U5F4BC","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 17.3.1 (21D61)","roots_installed":0,"name":"vcmiclient","incident_id":"A61F177E-FA7C-4740-8D1E-FCBF3179823E"}
{
  "uptime" : 1500,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPad13,10",
  "coalitionID" : 677,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 17.3.1",
    "releaseType" : "User",
    "build" : "21D61"
  },
  "captureTime" : "2024-03-06 15:47:08.0273 +0300",
  "codeSigningMonitor" : 1,
  "incident" : "A61F177E-FA7C-4740-8D1E-FCBF3179823E",
  "pid" : 554,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-03-06 15:45:35.4406 +0300",
  "procStartAbsTime" : 34939340994,
  "procExitAbsTime" : 37161495835,
  "procName" : "vcmiclient",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/vcmiclient",
  "bundleInfo" : {"CFBundleShortVersionString":"1.1.1","CFBundleVersion":"2023-02-03-b429f0b","CFBundleIdentifier":"eu.vcmi.vcmiclient.LSC5U5F4BC"},
  "storeInfo" : {"deviceIdentifierForVendor":"E3865F47-0C82-4FE1-9512-F0573D0977AD","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "eu.vcmi.vcmiclient.LSC5U5F4BC",
  "crashReporterKey" : "d93fac6aea47f50e35dc621f27cc272171e1a7fe",
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "codeSigningID" : "eu.vcmi.vcmiclient.LSC5U5F4BC",
  "codeSigningTeamID" : "LSC5U5F4BC",
  "codeSigningFlags" : 570434309,
  "codeSigningValidationCategory" : 3,
  "codeSigningTrustLevel" : 6,
  "instructionByteStream" : {"beforePC":"fyMD1f17v6n9AwCR893\/l78DAJH9e8Go\/w9f1sADX9YQKYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkejd\/5e\/AwCR\/XvBqP8PX9bAA1\/WfyMD1Q=="},
  "basebandVersion" : "4.20.05",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":0,"code":6,"namespace":"SIGNAL","indicator":"Abort trap: 6","byProc":"vcmiclient","byPid":554},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":23570,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":6407160013},{"value":13},{"value":32},{"value":3440},{"value":6941667091849850544},{"value":6941667091310339632},{"value":6656},{"value":6163684928},{"value":2043},{"value":2045},{"value":16},{"value":53},{"value":328},{"value":8055736448,"symbolLocation":0,"symbol":"_main_thread"},{"value":0},{"value":6},{"value":259},{"value":8055736672,"symbolLocation":224,"symbol":"_main_thread"},{"value":10746404064},{"value":1721761},{"value":10792665520},{"value":4377264840,"symbolLocation":0,"symbol":"LIB_CLIENT::console"},{"value":4339836502},{"value":4339836456},{"value":6163689472}],"flavor":"ARM_THREAD_STATE64","lr":{"value":8472589952},"cpsr":{"value":1073745920},"fp":{"value":6163686016},"sp":{"value":6163685984},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7893229500,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":40892,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":13},{"imageOffset":22144,"symbol":"pthread_kill","symbolLocation":268,"imageIndex":14},{"imageOffset":482192,"symbol":"abort","symbolLocation":180,"imageIndex":15},{"imageOffset":86008,"symbol":"abort_message","symbolLocation":132,"imageIndex":16},{"imageOffset":20340,"symbol":"demangling_terminate_handler()","symbolLocation":320,"imageIndex":16},{"imageOffset":191924,"symbol":"_objc_terminate()","symbolLocation":160,"imageIndex":17},{"imageOffset":82876,"symbol":"std::__terminate(void (*)())","symbolLocation":16,"imageIndex":16},{"imageOffset":96088,"symbol":"__cxa_rethrow","symbolLocation":204,"imageIndex":16},{"imageOffset":2401536,"symbol":"LIB_CLIENT::preinitDLL(LIB_CLIENT::CConsoleHandler*, bool, bool)","symbolLocation":132,"imageIndex":1},{"imageOffset":140584,"symbol":"SDL_main","symbolLocation":2928,"imageIndex":12},{"imageOffset":1856748,"symbol":"startSDL","symbolLocation":408,"imageIndex":12},{"imageOffset":1854920,"symbol":"startSDLManually","symbolLocation":140,"imageIndex":12},{"imageOffset":1854652,"symbol":"__client_main_block_invoke","symbolLocation":268,"imageIndex":12},{"imageOffset":193092,"symbol":"__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__","symbolLocation":128,"imageIndex":18},{"imageOffset":191520,"symbol":"___CFXRegistrationPost_block_invoke","symbolLocation":88,"imageIndex":18},{"imageOffset":191336,"symbol":"_CFXRegistrationPost","symbolLocation":440,"imageIndex":18},{"imageOffset":188600,"symbol":"_CFXNotificationPost","symbolLocation":724,"imageIndex":18},{"imageOffset":173828,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":92,"imageIndex":19},{"imageOffset":4279152,"symbol":"launchGame","symbolLocation":504,"imageIndex":12},{"imageOffset":4370540,"symbol":"main","symbolLocation":132,"imageIndex":12},{"imageOffset":13489516,"symbol":"user_main_trampoline()","symbolLocation":208,"imageIndex":12},{"imageOffset":13489012,"symbol":"+[QIOSApplicationStateTracker applicationDidFinishLaunching:]","symbolLocation":1040,"imageIndex":12},{"imageOffset":0,"imageIndex":20},{"imageOffset":23,"imageIndex":20}]},{"id":23577,"frames":[{"imageOffset":6652,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6165409792},{"value":8195},{"value":6164873216},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6165409792},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":8472574460},"far":{"value":0}}},{"id":23580,"name":"com.apple.uikit.eventfetch-thread","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592},{"value":58287001174016},{"value":0},{"value":58287001174016},{"value":2},{"value":4294967295},{"value":18446744073709550527},{"value":13571},{"value":0},{"value":1},{"value":13571},{"value":763747},{"value":0},{"value":0},{"value":18446744073709551569},{"value":6829154532,"symbolLocation":56,"symbol":"clock_gettime"},{"value":0},{"value":4294967295},{"value":2},{"value":58287001174016},{"value":0},{"value":58287001174016},{"value":6167125368},{"value":8589934592},{"value":21592279046},{"value":21592279046},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":7893192464},"cpsr":{"value":4096},"fp":{"value":6167125216},"sp":{"value":6167125136},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7893193080},"far":{"value":0}},"frames":[{"imageOffset":4472,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":13},{"imageOffset":3856,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":13},{"imageOffset":3624,"symbol":"mach_msg_overwrite","symbolLocation":436,"imageIndex":13},{"imageOffset":3176,"symbol":"mach_msg","symbolLocation":24,"imageIndex":13},{"imageOffset":219804,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":18},{"imageOffset":211348,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":18},{"imageOffset":209912,"symbol":"CFRunLoopRunSpecific","symbolLocation":608,"imageIndex":18},{"imageOffset":181228,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":19},{"imageOffset":366252,"symbol":"-[NSRunLoop(NSRunLoop) runUntilDate:]","symbolLocation":64,"imageIndex":19},{"imageOffset":1632016,"symbol":"-[UIEventFetcher threadMain]","symbolLocation":420,"imageIndex":21},{"imageOffset":720192,"symbol":"__NSThread__start__","symbolLocation":732,"imageIndex":19},{"imageOffset":9428,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":14},{"imageOffset":6672,"symbol":"thread_start","symbolLocation":8,"imageIndex":14}]},{"id":23582,"threadState":{"x":[{"value":18446744073709551612},{"value":0},{"value":4294967295},{"value":0},{"value":8055729344,"symbolLocation":0,"symbol":"_dispatch_main_q"},{"value":18},{"value":0},{"value":0},{"value":0},{"value":10765770240},{"value":4},{"value":16383},{"value":68719476736},{"value":9005068950962176},{"value":9005137670438912},{"value":2504411256},{"value":515},{"value":13488280892030362384,"symbolLocation":13488280883974635568,"symbol":"_OS_dispatch_queue_main_vtable"},{"value":0},{"value":4294967295},{"value":0},{"value":6168274752},{"value":16777217},{"value":6168274888},{"value":10757720832},{"value":4369432576},{"value":0},{"value":6168274872},{"value":60}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6828862704},"cpsr":{"value":1073745920},"fp":{"value":6168274560},"sp":{"value":6168274528},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7893195768},"far":{"value":0}},"queue":"com.apple.libtrace.state.block-list","frames":[{"imageOffset":7160,"symbol":"__ulock_wait","symbolLocation":8,"imageIndex":13},{"imageOffset":19696,"symbol":"_dlock_wait","symbolLocation":56,"imageIndex":23},{"imageOffset":19108,"symbol":"_dispatch_thread_event_wait_slow","symbolLocation":56,"imageIndex":23},{"imageOffset":80288,"symbol":"__DISPATCH_WAIT_FOR_QUEUE__","symbolLocation":368,"imageIndex":23},{"imageOffset":79180,"symbol":"_dispatch_sync_f_slow","symbolLocation":148,"imageIndex":23},{"imageOffset":59460,"symbol":"___os_state_request_for_self_block_invoke","symbolLocation":372,"imageIndex":24},{"imageOffset":9896,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":23},{"imageOffset":17152,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":23},{"imageOffset":47252,"symbol":"_dispatch_lane_serial_drain","symbolLocation":748,"imageIndex":23},{"imageOffset":50168,"symbol":"_dispatch_lane_invoke","symbolLocation":432,"imageIndex":23},{"imageOffset":94212,"symbol":"_dispatch_root_queue_drain_deferred_wlh","symbolLocation":288,"imageIndex":23},{"imageOffset":92280,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":404,"imageIndex":23},{"imageOffset":6500,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":14},{"imageOffset":6660,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":14}]},{"id":24033,"frames":[{"imageOffset":6652,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6165983232},{"value":18251},{"value":6165446656},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6165983232},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":8472574460},"far":{"value":0}}},{"id":24826,"frames":[{"imageOffset":6652,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6164262912},{"value":4635},{"value":6163726336},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6164262912},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":8472574460},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4368449536,
    "size" : 49152,
    "uuid" : "e4220a07-d2c0-3818-9a94-25e8dba387bc",
    "path" : "\/private\/preboot\/Cryptexes\/OS\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4369432576,
    "size" : 7405568,
    "uuid" : "fa5006b1-d876-3306-9fb9-5e2049a0d70b",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/Frameworks\/libvcmi_lib_client.dylib",
    "name" : "libvcmi_lib_client.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4364255232,
    "size" : 32768,
    "uuid" : "22acd950-392b-3c7f-902a-1ceed4090f34",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/Frameworks\/libiOS_utils.dylib",
    "name" : "libiOS_utils.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4381736960,
    "size" : 49152,
    "uuid" : "a67eaaa7-0f47-35e9-97f5-2f04d05007c7",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/Frameworks\/libminizip.dylib",
    "name" : "libminizip.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4381835264,
    "size" : 114688,
    "uuid" : "be769822-f1e6-3d0a-a518-b85860c326a0",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/Frameworks\/libboost_filesystem.dylib",
    "name" : "libboost_filesystem.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4382031872,
    "size" : 196608,
    "uuid" : "2947449a-2ae2-3977-b618-4a0b99966b45",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/Frameworks\/libboost_program_options.dylib",
    "name" : "libboost_program_options.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4382408704,
    "size" : 344064,
    "uuid" : "d216d88d-e435-351c-8942-71aebaeb3b8c",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/Frameworks\/libboost_locale.dylib",
    "name" : "libboost_locale.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4383047680,
    "size" : 65536,
    "uuid" : "d9a1539a-f82e-3746-bcc6-550736b368c5",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/Frameworks\/libboost_thread.dylib",
    "name" : "libboost_thread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4383195136,
    "size" : 32768,
    "uuid" : "a194503f-500f-3fcd-af00-45384404a369",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/Frameworks\/libboost_atomic.dylib",
    "name" : "libboost_atomic.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4383309824,
    "size" : 32768,
    "uuid" : "bbb86569-76b2-3896-b1bc-1efded004702",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/Frameworks\/libboost_chrono.dylib",
    "name" : "libboost_chrono.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4383391744,
    "size" : 65536,
    "uuid" : "34adc5bc-559a-3341-82d2-f2ac6bc7dec9",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/Frameworks\/libboost_container.dylib",
    "name" : "libboost_container.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4364320768,
    "size" : 32768,
    "uuid" : "74972646-4b8a-3c22-85e2-8d51359d47f9",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/Frameworks\/libboost_date_time.dylib",
    "name" : "libboost_date_time.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4303175680,
    "size" : 38584320,
    "uuid" : "ac0d5b50-b3ce-36bb-88e4-82bd0d27f3c7",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/3FFAB7ED-B019-459D-8DFE-42F66DCA15B7\/App.app\/vcmiclient",
    "name" : "vcmiclient"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7893188608,
    "size" : 233456,
    "uuid" : "08f02c6b-1443-3665-9805-4a8bee87346e",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8472567808,
    "size" : 49140,
    "uuid" : "8f9c865b-29f5-346b-add5-fde40e008c66",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6829133824,
    "size" : 516084,
    "uuid" : "6d03d4f6-ec2f-3c18-9013-b4caf90539af",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8471629824,
    "size" : 114688,
    "uuid" : "86d3dd19-5f9e-3d52-8c65-642b72fe0061",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6564364288,
    "size" : 319457,
    "uuid" : "fe61505c-f2a9-3f78-b709-647d1097a06a",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6694658048,
    "size" : 5427200,
    "uuid" : "5a6c1f41-bf70-32f6-a1d6-5b894dd21362",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6677463040,
    "size" : 11927552,
    "uuid" : "5623831d-5719-33a9-9691-759f47d714d1",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6730493952,
    "size" : 28143616,
    "uuid" : "2d538446-6e40-3c10-8a5f-559c938077a0",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8589737984,
    "size" : 2883584,
    "uuid" : "098b5301-ec56-3ad3-b91a-9a6481b5fa0e",
    "path" : "\/usr\/lib\/libmecabra.dylib",
    "name" : "libmecabra.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6828843008,
    "size" : 290816,
    "uuid" : "c49a5fc2-c873-3913-9603-004f5d0175e7",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7123148800,
    "size" : 110592,
    "uuid" : "4408ad69-b633-3a3f-954d-9904e7d26b88",
    "path" : "\/usr\/lib\/system\/libsystem_trace.dylib",
    "name" : "libsystem_trace.dylib"
  }
],
  "sharedCache" : {
  "base" : 6563446784,
  "size" : 3517612032,
  "uuid" : "9f2c8ac8-f10d-3bca-8811-2b1a8f8c2f66"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=614.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=614.4M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                           64K        4 \nCoreAnimation                       48K        3 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           602.2M       60 \nMALLOC guard page                  128K        8 \nSTACK GUARD                         96K        6 \nStack                             3728K        8 \nVM_ALLOCATE                        160K        2 \n__AUTH                            2485K      287 \n__AUTH_CONST                      32.1M      685 \n__CTF                               824        1 \n__DATA                            35.9M      692 \n__DATA_CONST                      36.0M      691 \n__DATA_DIRTY                      7669K      637 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    1904K        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       389.1M       14 \n__OBJC_RO                         85.3M        1 \n__OBJC_RW                         2680K        1 \n__TEXT                           829.7M      714 \ndyld private memory                272K        1 \nmapped file                      141.1M       19 \nshared memory                       80K        4 \n===========                     =======  ======= \nTOTAL                              2.1G     3844 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "a61402b104b3f13dad714a743ce25f66b5702053",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "61675b89201f677a9a4cbd65",
      "factorPackIds" : {
        "HEALTH_FEATURE_AVAILABILITY" : "65a85614aba73d755604a256"
      },
      "deploymentId" : 240000095
    },
    {
      "rolloutId" : "639124e81d92412bfb4880b3",
      "factorPackIds" : {

      },
      "deploymentId" : 240000012
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "011251b6-0bd5-412d-b42d-8f91c8d7969c",
      "experimentId" : "641cdd29126e771815adf9e7",
      "deploymentId" : 400000029
    },
    {
      "treatmentId" : "874c5255-a2d2-4604-9551-45f93fe9fa19",
      "experimentId" : "642c4560ea3b2418c750f7e4",
      "deploymentId" : 400000032
    }
  ]
}
}
`

**Comment by kambala-decapitator** [comment]
> Version: [1.4.5]

but logs say that you're running v1.1.1. Install the latest release, I remember there used to be a signing issue with Altstore / Sideloadly.
