### ISSUE TITLE
Hero can learn spells from Pandora without Wisdom or even spellbook

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3660]
**To Reproduce**
- Generate random map (Jebus will do)
- Hire hero with no Wisdom or no spellbook altogether
- Use vcmigod to visit Pandora boxes

**Expected behavior**
Unavailable spells should be skipped. If hero can learn no spells at all, Pandora should appear empty.

**Actual behavior**
Hero learns all spells found in Pandora Box. Even if he has no spellbook, he can later buy it from a guild and all spells will show up there.

**Did it work earlier?**
Yes

**Version**
develop

**Comment by IvanSavenko** [comment]
Caused by conversion of Pandora's to rewardable object.
And right now rewardables don't check for spellbook / wisdom - see `Rewardable::Interface::grantRewardAfterLevelup`
