### ISSUE TITLE
VCMI client crashes when click Scenario Information in campaign games

### ISSUE THREAD

**Issue by hankgong** [vcmi/vcmi#3661]
**Describe the bug**
VCMI client crashes when click Scenario Information in campaign games

**Game logs**

**To Reproduce**
1. New or Load a campaign game 
3. Click Scenario Information

**Expected behavior**
The scenario information dialog should pop out.

**Actual behavior**

**Did it work earlier?**
It worked in current 1.4.5 version

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/292760/21857a39-4cce-49e2-b31c-7d454f3addc6)

**Version**
 - OS: Windows
 - Version: Latest

**Additional context**

**Comment by DjWarmonger** [comment]
Could be related to my recent change in saving scenario options.

**Comment by Laserlicht** [comment]
Bug also mentioned here: https://github.com/vcmi/vcmi/issues/3617
