### ISSUE TITLE
[HotA] Black Tower battle should be a regular layout instead of banks layout

### ISSUE THREAD

**Issue by thiscris** [vcmi/vcmi#3663]
**Describe the bug**
The Black Tower object added in HotA originally has a regular battlefield (enemies are on the right, attacking army on the left, with war machines if available). In the VCMI implementation the battlefield is similar to dragon utopia and other banks (enemies around the corners of the battlefield, attacking army in the middle, no war machines). As a result the Black Tower poses a greater challenge then the way it is implemented in the original HotA.

**Game logs**
not relevant

**To Reproduce**
1. Start a game
2. Visit a Black Tower map object

**Expected behavior**
The battlefield should be a regular one (standard battle)

**Actual behavior**
The battlefield is that used for banks battles

**Did it work earlier?**
I suppose not

**Screenshots**
![map object](https://github.com/vcmi/vcmi/assets/31136319/94bd9286-079b-4e61-aa79-48d096109356)

![battlefield](https://github.com/vcmi/vcmi/assets/31136319/46acda2f-8cac-44bc-8b02-3564e91f0cfb)

**Version**
 - OS: Linux
 - Version: 1.4.5

**Additional context**
Not sure if this should be treated as a feature request or a bug.

**Comment by thiscris** [comment]
I think I should have opened this in https://github.com/vcmi-mods/horn-of-the-abyss/issues instead of here. Should I close this and open a new one there?

**Comment by misiokles** [comment]
Developers seldom look for bugs in mods repositories. It's better to duplicate reports.

**Comment by thiscris** [comment]
My guess is that all map objects battles in VCMI are treated as "banks" battles, that is why there is nothing mentioned in the json file for the black tower: https://github.com/vcmi-mods/horn-of-the-abyss/blob/vcmi-1.4/hota/Mods/mapObjects/content/config/hotaMapObjects/blackTower.json

**Comment by DjWarmonger** [comment]
Probably we should add an extra option to bank config for battlefield layout.

**Comment by DjWarmonger** [comment]
Implemented in https://github.com/vcmi-mods/horn-of-the-abyss/pull/108
