### ISSUE TITLE
VCMI crashes when pressing Enter during defeat animation

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3665]
**Describe the bug**
Game crashes when I press Enter during defeat animation.
If I let the animation finish and go to main menu, it works fine.

**To Reproduce**
Every time. Just lose the game and press Enter while animation plays.

**Expected behavior**
No crash, just finish animation instantly and return to main menu.

**Actual behavior**
Crash

**Did it work earlier?**
No idea, relatively new feature.

**Screenshots**
<img width="616" alt="image" src="https://github.com/vcmi/vcmi/assets/2566990/725242c5-ef70-4c56-bb77-8630c2a72a07">

**Version**
Develop

**Comment by IvanSavenko** [comment]
Likely regression from networking changes, will check it out.
