### ISSUE TITLE
Basic intelligence skill adds 20% mana instead of 25%

### ISSUE THREAD

**Issue by Kris-Ja** [vcmi/vcmi#3670]
**Describe the bug**
Limit of mana points with basic intelligence skill is calculated wrong.

**To Reproduce**
1. Create a new game. Choose a hero with basic intelligence skill (e.g. Daremyth from Tower)
2. Daremyth has 36 mana points instead of 37 (3 knowledge points multiplied by 12 instead of 12.5).

**Expected behavior**
Daremyth should have 37 mana points.

**Actual behavior**
Daremyth has 36 mana points.

**Did it work earlier?**
probably not

**Screenshots**
VCMI:
![obraz](https://github.com/vcmi/vcmi/assets/107918765/e08d670c-3d2b-4ca4-bbb0-89f71c25a862)

original Heroes3 game:
![obraz](https://github.com/vcmi/vcmi/assets/107918765/286cd9a0-86b9-4ecc-adf8-13bca28b18c6)

**Version**
 - OS: Linux
 - Version: 1.4.5

**Additional context**
CGHeroInstance::manaLimit() is calculated as PrimarySkillLevel multiplyed by valOfBonuses(BonusType::MANA_PER_KNOWLEDGE) but valOfBonuses returns int so its value is 12 instead of 12.5.
Also, BonusList::totalValue returns int.

**Comment by Alucard648** [comment]
Rounding error. Try hero with 10 KNW.

**Comment by Kris-Ja** [comment]
![obraz](https://github.com/vcmi/vcmi/assets/107918765/6f585e1d-b2dc-4c14-9c65-962dd64bac15)
Same problem with any number of knowledge points, it is always 120% instead of 125%. (I explained why in additional context)
