### ISSUE TITLE
Crash when hero get killed during battle

### ISSUE THREAD

**Issue by nullkiller** [vcmi/vcmi#3697]
**Describe the bug**
Game crashes on AI attempt to access killed hero.

**Game logs**
![image](https://github.com/vcmi/vcmi/assets/5644734/62fa0870-1bb1-40e0-a522-5652dd36afad)
[VCMI_Client_log.zip](https://github.com/vcmi/vcmi/files/14801791/VCMI_Client_log.zip)

**To Reproduce**
1. Load attached save (WOG required)
2. Pass turn.

**Expected behavior**
Next turn starts in a few minutes

**Actual behavior**
Elleshar attacks Tazar and if he is not lucky enough both get killed. Game may crash afterwards.

**Did it work earlier?**
I believe so. Have not encountered this before.

**Version**
 - OS: Windows
 - Version: develop 1.5

**Additional context**
Save file: [pink.zip](https://github.com/vcmi/vcmi/files/14801862/pink.zip)

**Comment by nullkiller** [comment]
AI hero speed is set to Not Show

**Comment by IvanSavenko** [comment]
Unfortunately unable to reproduce after multiple attempts with provided save.

Do you have callstack / crashdump from this bug?

**Comment by nullkiller** [comment]
Will check. I think there was something.

**Comment by nullkiller** [comment]
For now I can no longer reproduce as AI acts differently now on this save. Also checked draw, it works as expected, both heroes disappear. Closing for now.
