### ISSUE TITLE
Unable to create room in lobby after latest commits

### ISSUE THREAD

**Issue by pppbb** [vcmi/vcmi#3702]
**Game logs**

[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/14810396/VCMI_Client_log.txt)

**To Reproduce**
1. Enter Lobby.
2. Try to create room.

**Expected behavior**
Lobby room should be created.
Instead i get this:
![Zrzut ekranu 2024-03-30 055942](https://github.com/vcmi/vcmi/assets/33740721/50bd2346-9f46-4d63-a03d-80755ea175c8)

 

**Did it work earlier?**
Yes, i tried it on Android.

**Version**
 - OS: Windows 11,Linux
 - Version: VCMI-branch-develop-acd2352

**Comment by IvanSavenko** [comment]
Hi. Should be fixed now.
However I've reset database so you'll need to create new account (you can use same account name if you wish to).
Hopefully this is the last time I need to reset database, and definitely won't be doing that after 1.5 has been released.
