### ISSUE TITLE
Custom key configuration

### ISSUE THREAD

**Issue by Warzyw647** [vcmi/vcmi#3709]
**Describe your proposal**
Give the player ability to customize keyboard shortcuts. Either in launcher options or in a configuration file.

**Additional context**
Didn't notice such option in launcher settings.
People are used to some shortcuts, for example alt to switch between shooting and melee combat.

**Comment by IvanSavenko** [comment]
Some initial preparation for this option is already in, but still missing an option to actually load this stuff from file (and possibly - UI to edit).

If somebody wants to take a look - check `ShortcutHandler` class. All key <-> shortcut mapping is in there.

**Comment by thiscris** [comment]
The shortcuts on the main menu work for me. [Link](https://github.com/vcmi/vcmi/blob/5c40aa861228efb5e6b1eac57209548b56b6403d/client/gui/ShortcutHandler.cpp#L46)
I tried new game, load game, single player, quit.

**Comment by IvanSavenko** [comment]
They do work, but currently there is no way to edit them by players.

**Comment by thiscris** [comment]
Sorry, I had a typo in my original comment. They in fact don't work for me .
