### ISSUE TITLE
VCMI wont start

### ISSUE THREAD

**Issue by Ud4ba** [vcmi/vcmi#3716]
**Describe the bug**
Game wont start
**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.
vcmiclient
Starting... 
VCMI 1.1.0 (client)
Creating console and configuring logger: 0 ms
The log file will be saved to "/home/udaba/.cache/vcmi/VCMI_Client_log.txt"
	Initialization: 1 ms
	Data loading: 38 ms
	Mod handler: 0 ms
File CONFIG/MODSETTINGS is not a valid JSON file!
At line 1, position 0 error: File is empty

	Mod filesystems: 13 ms
Basic initialization: 53 ms
Initialized logging system based on settings successfully.
[log level] ai => not set
[log level] animation => not set
[log level] bonus => not set
[log level] global => trace
[log level] mod => not set
[log level] network => not set
Error: campaign movies was not found!
Error: campaign music was not found!
Loading settings: 56 ms
Found 3 render drivers
	opengl (active)
	opengles2
	software
Check display mode: requested 800 x 600; available up to 1920 x 1080 
Set logical rendering resolution to 800x600
Created renderer opengl
	Initializing screen: 148 ms
	Initializing video: 0 ms
Initializing screen and sound handling: 2 ms
Error: video VIDEO/3DOLOGO was not found
Error: video VIDEO/AZVS was not found
		 Bonus type handler: 4 ms
		 Terrain handler: 0 ms
terminate called after throwing an instance of 'std::runtime_error'
  what():  Resource with name DATA/TENTCOLR and type TEXT wasn't found.
Aborted

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear description what is currently happening 

**Did it work earlier?**
If this something which worked well some time ago, please let us know about version where it works or at date when it worked.
No 1st time launching.
**Screenshots**

**Version**
 - OS: [Debian 12]
 - Version: [VCMI version]  1.1.0+dfsg-1

**Additional context**

**Comment by kambala-decapitator** [comment]
1. have you installed H3 data? Seems not, but you must.
2. don't use such an old VCMI version

**Comment by IvanSavenko** [comment]
Hi. Unfortunately Debian version of VCMI is very outdated.
You might want to install newest version, either via Flatpak or by building latest release yourself.

As for the crash - VCMI requires Heroes 3: Complete or Shadow of Death.
But it seems that you have Heroes 3: Restoration of Erathia.
At the moment VCMI does not supports HD Edition from Steam or old Linux Heroes 3 release by Loki, which only contain Restoration of Erathia data.
