### ISSUE TITLE
crash in battle betwen AI

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3731]
Pink attack purple and after that crash happens
![изображение](https://github.com/vcmi/vcmi/assets/36762538/cd8ae479-3501-42a1-881b-8e6f1ce3c0b7)
save, log and dump is here: https://drive.google.com/file/d/1Ndp8P42cGDnnbWic1Fmb5yHAYZW70EeZ/view?usp=drive_link

1.5.0.0a80c6c27bfa3ede04b5d15cc1878eac2bbc8ae5, msvs

> [2024-Apr-08 14:35:26.907402] DEBUG [runNetwork] ai - Player 7 (pink): I won the Starting battle of Аламар attacking Gaberalle Алхимик at (68 131 0)!
> [2024-Apr-08 14:35:26.907402] DEBUG [runNetwork] ai - Player 5 (purple): I lost the Starting battle of Аламар attacking Gaberalle Алхимик at (68 131 0)!
> [2024-Apr-08 14:35:26.909403] ERROR [runServer] global - Disaster happened.
> [2024-Apr-08 14:35:26.909403] ERROR [runServer] global - Reason: 0xc0000005 - EXCEPTION_ACCESS_VIOLATION at 0033:0,000,7FF,6CF,A1D,82D
> [2024-Apr-08 14:35:26.910403] ERROR [runServer] global - Attempt to read from 0x0,000,000,000,000,108
> [2024-Apr-08 14:35:26.910403] ERROR [runServer] global - Thread ID: 420

**Comment by IvanSavenko** [comment]
Likely related to #3732
Game starts moving artifacts but ends up with nullptr artifact:
`const CArtifactInstance * art = finishingBattle->loserHero->getArt(ArtifactPosition::BACKPACK_START + slotNumber);`
art here is nullptr

```
>	VCMI_client.exe!BattleResultProcessor::endBattleConfirm(const CBattleInfoCallback & battle) Line 382	C++
 	VCMI_client.exe!BattleResultProcessor::endBattle(const CBattleInfoCallback & battle) Line 304	C++
 	VCMI_client.exe!BattleProcessor::checkBattleStateChanges(const CBattleInfoCallback & battle) Line 221	C++
 	VCMI_client.exe!BattleFlowProcessor::onActionMade(const CBattleInfoCallback & battle, const BattleAction & ba) Line 527	C++
 	VCMI_client.exe!BattleProcessor::makePlayerBattleAction(const BattleID & battleID, PlayerColor player, const BattleAction & ba) Line 290	C++
 	VCMI_client.exe!ApplyGhNetPackVisitor::visitMakeAction(MakeAction & pack) Line 341	C++
 	VCMI_lib.dll!CPack::visit(ICPackVisitor & visitor) Line 56	C++
 	VCMI_client.exe!CApplyOnGH<MakeAction>::applyOnGH(CGameHandler * gh, CGameState * gs, CPack * pack) Line 105	C++
 	VCMI_client.exe!CGameHandler::handleReceivedPack(CPackForServer * pack) Line 490	C++
 	VCMI_client.exe!CVCMIServerPackVisitor::visitForServer(CPackForServer & serverPack) Line 112	C++
 	VCMI_lib.dll!CPack::visit(ICPackVisitor & visitor) Line 52	C++
 	VCMI_client.exe!CVCMIServer::onPacketReceived(const std::shared_ptr<INetworkConnection> & connection, const std::vector<enum std::byte,std::allocator<enum std::byte>> & message) Line 169	C++
```

**Comment by IvanSavenko** [comment]
Closing, presumably fixed. Reopen if happens again
