### ISSUE TITLE
Creature Biography

### ISSUE THREAD

**Issue by edeksumo** [vcmi/vcmi#3735]
Add possybility to write biography for creatures.

**Additional context**
While clicking LMS on creature in creature window, small window would pop up with biography from json.

**Comment by Laserlicht** [comment]
I think big picture won't fit in Heroes III Vanilla. Isn't text enough?

**Comment by swats-the-floran** [comment]
> I think big picture won't fit in Heroes III Vanilla. Isn't text enough?

the more good art - the better. i wanted to suggest big pictures  for heroes but there is a set for creatures already. why not?
