### ISSUE TITLE
Cannot swap artifacts (Freeze)

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3754]
May be related recent edits

![изображение](https://github.com/vcmi/vcmi/assets/36762538/4d7b2ec1-6e12-4850-9b2e-d525ee20b612)

![изображение](https://github.com/vcmi/vcmi/assets/36762538/e94a14f5-d537-41a7-b9d8-48409cc179cf)

VCMI 1.5.0.53fcd3ad26ff7ec7f3462e5bfb51dd0252074956

> [2024-Apr-12 11:59:47.941250] ERROR [runServer] global - Cannot swap artifacts!
> [2024-Apr-12 11:59:47.941250] ERROR [runNetwork] network - System message: Server encountered a problem: Cannot swap artifacts!
> [2024-Apr-12 11:59:47.941250] ERROR [runServer] global - Got false in applying struct ExchangeArtifacts... that request must have been fishy!
> [2024-Apr-12 11:59:47.943252] ERROR [runNetwork] global - Unable to play sound file CHAT , error No free channels available
> [2024-Apr-12 11:59:47.945251] ERROR [runNetwork] network - System message: Server encountered a problem: Got false in applying struct ExchangeArtifacts... that request must have been fishy!
[tan.zip](https://github.com/vcmi/vcmi/files/14956546/tan.zip)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/14956548/VCMI_Client_log.txt)
[SoD_Conquers_4th_Edition 245.zip](https://github.com/vcmi/vcmi/files/14956559/SoD_Conquers_4th_Edition.245.zip)

just press end turn. tan bot will be freeze

**Comment by IvanSavenko** [comment]
@SoundSSGood 
This is that bug where AI attempts to swap combined artifact that can't be placed in target slot?

**Comment by SoundSSGood** [comment]
Yeah that's it

**Comment by Povelitelh3** [comment]
Quite a common problem. It would be great to fix it before release, if possible.

**Comment by IvanSavenko** [comment]
@SoundSSGood 
How this could happen to begin with? From what I see in `AIGateway::pickBestArtifacts` (the only way for AI to move artifacts), the only way for AI to move artifact is:
a) move it from backpack to equipment
b) swap backpack artifact with equipped artifact

And in both cases, AI checks for `artifact->canBePutAt`, so it should be possible to place it where AI intends to.
What could be the reason for this error?

**Comment by nullkiller** [comment]
[art-exchange-3754.zip](https://github.com/vcmi/vcmi/files/15137996/art-exchange-3754.zip)
Map
