### ISSUE TITLE
Game FREEZE on Mac-Intel, (save file included)

### ISSUE THREAD

**Issue by Marc477** [vcmi/vcmi#3778]
Game FREEZE on Mac-Intel build, latest version downloaded yesterday.

The only mods I have are : HOTA and VCMI Extras, and AI BOOST but only the extra resources are activated (not other bonus).

All you need to do is Load the save file, and click on End Turn. The game freezes during the ship battle between 2 AI (orange and green). And then its impossible to continue playing.

It doesn't freeze on PC, i've tried it. Only on Mac.

Save File:
[game-freeze.zip](https://github.com/vcmi/vcmi/files/14999475/game-freeze.zip)

**Comment by IvanSavenko** [comment]
Hi. Can you also upload log files after freeze?
Should be in `Library/Logs/vcmi/` directory

**Comment by Marc477** [comment]
Sure here are the logs

[Log.zip](https://github.com/vcmi/vcmi/files/14999599/Log.zip)

**Comment by nullkiller** [comment]
[game-freeze-2.zip](https://github.com/vcmi/vcmi/files/15051919/game-freeze-2.zip)
Works as expected for me. Day after freeze attached

**Comment by nullkiller** [comment]
I see now it is only Mac issue. Strange

**Comment by kambala-decapitator** [comment]
let me test on an intel mac

**Comment by kambala-decapitator** [comment]
didn't freeze for me on the latest daily build: https://download.vcmi.eu/branch/develop/macOS/intel/VCMI-branch-develop-23fd47a.dmg
