### ISSUE TITLE
Min damage greater than max damage will cause crash when attack

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#3780]
**Describe the bug**
if a creature min and max damage are same. and stackExperience value not well designed. This bug comes.

![1](https://github.com/vcmi/vcmi/assets/8289682/a6e6a53d-aa9c-44a5-ad9d-d3280b44a4e7)

**Game logs**

[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/15000108/VCMI_Client_log.txt)

**To Reproduce**
1. enable refugee-town mod and all submodules and wog mod
2. give hero 26 enchanter and other 99999 strong creatures
3. kill 9999 * 2 Scorpicore make enchanter to level 7
4. the next battle enchanter damage will be 19 - 18，when he attack，game crashed.

**Expected behavior**
game not crash

**Actual behavior**
game crash

**Did it work earlier?**
I dont know, I only test on daily build

**Screenshots**
no

**Version**
 - OS: Windows
 - Version: daily build

**Additional context**
no

**Comment by kdmcser** [comment]
> its modder responsibility to avoid situations like this one

yes, its modder responsibility, but it is difficult for modder to find this problem since there is no hint in console.

**Comment by dydzio0614** [comment]
well - as Ivan said it should produce diagnostics on mod loading

**Comment by IvanSavenko** [comment]
Actually while vcmi will detect misconfiguration (e.g.  `"min" : 19, "max" : 18`) vcmi will not detect cases if this occurs due to bonuses - e.g. if you give bonus only to minimal damage.

**Comment by kdmcser** [comment]
and if this problem happened, make game crash maybe unfair to users. user often download lots of mods from repos. this problem may happened in AI turn. AI take 2 - 3 months or longer to make its enchanter to level 7. The user will find his game crash in one day. most of users are unable to find which mod cause it. he only know that his game is lost and have to start a new game and dont know whether it can be happened again.

the user becomes the victim of the modder's mistake. he dont care much about whether the damage is 18 or 19. he only care if his could finish his game.

**Comment by kdmcser** [comment]
I fix it it #3787
