### ISSUE TITLE
NKAI crash

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3788]
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/15014493/VCMI_Client_log.txt)
[1.zip](https://github.com/vcmi/vcmi/files/15014498/1.zip)
[Hectic Waters V1.3.zip](https://github.com/vcmi/vcmi/files/15014506/Hectic.Waters.V1.3.zip)

Looks like problem with whirpool

press end of turn

**Comment by IvanSavenko** [comment]
Unable to reproduce unfortunately

**Comment by IvanSavenko** [comment]
Will add check for whirlpool, but I'd say that main bug is that army-less hero has appeared in the first place

**Comment by nullkiller** [comment]
Likely has a commander.

**Comment by nullkiller** [comment]
![image](https://github.com/vcmi/vcmi/assets/5644734/817a4a10-afbf-48c8-bde3-1194e4f41c5b)

**Comment by nullkiller** [comment]
So commander is a stack and can be used in case nothing else is present

**Comment by IvanSavenko** [comment]
That explains it.
Will fix whirlpool.

**Comment by nullkiller** [comment]
I can myself

**Comment by IvanSavenko** [comment]
ok then
