### ISSUE TITLE
"beta version" of locked slot graphics is used for combined artifacts

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#3794]
Artifact slots locked by combined artifacts should have padlock image, instead of red crossed icon:

![obraz](https://github.com/vcmi/vcmi/assets/9436577/d369e91e-fc82-4ce2-b08d-99cfb47be26d)

**Comment by IvanSavenko** [comment]
Last time I saw this it was related to resources of polish version from gog.com - we load .lod archives in wrong order or load archives not used by h3

**Comment by IvanSavenko** [comment]
Works for me on English version from gog.com

@dydzio0614 are you using Polish version from gog.com or something else?

**Comment by dydzio0614** [comment]
yes I am using polish gog version
