### ISSUE TITLE
Visit rewardable object crashed

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#3800]
**Describe the bug**

It a bug which my friend meet it after 3 mouths in AI's turn , due to AI hero visit Worn-out Spellbook, from mod Antagarich Burning - map assets .
I do some modify to reproduct it , put this object in to map, sometimes (visit about 10 objet) the game will be crashed.
I chose Necropolis hero Moandor to pick it.  
I modify the object reward field to make it more :

`	"rewards": [
		{
			"appearChance": {
				"max": 100
			},
			"spells": [
				{
					"level": 1
				}
			],
			"limiter": {
				"canLearnSpells": [
					{
						"level": 1
					}
				]
			},
			"removeObject": true
		},
		{
			"appearChance": {
				"max": 100
			},
			"resources": {
				"gems": 2
			},
			"removeObject": true
		}
	]
`

The crash file:

[VCMI_client.exe_crashinfo.dmp](https://github.com/vcmi/vcmi/files/15047022/VCMI_client.exe_crashinfo.dmp)

the crash stack:

![1](https://github.com/vcmi/vcmi/assets/8289682/c2f0844f-4fe9-4499-b689-be76670cd85c)

**Game logs**
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/15047070/VCMI_Launcher_log.txt)

**To Reproduce**
1. enable mod Antagarich Burning - map assets
2. modify rewards of  Worn-out Spellbook (Mods\ab-bad-ending-assets\content\config\neutral objects\rewardables.json, abbe_spellbook) as above.
3. use editor to put 10 Worn-out Spellbook, choose faction Necropolis, and  hero Moandor 
4. let Moandor pick Worn-out Spellbook,   alway choose spell reward.
5. about 7 ~ 8 time , game crash. if not crash in small chance, restart game and pick it again.

**Expected behavior**
game not crash 

**Actual behavior**
game crash

**Did it work earlier?**
I dont know, test in daiy build.

**Screenshots**
no

**Version**
 - OS: Windows
 - Version: daily build

**Additional context**
no

**Comment by IvanSavenko** [comment]
Limiter and reward check for different spells. Both check for 'random level 1 spell' but these two picks are rolled separately so it is possible for limiter to pick magic arrow and for reward to pick haste. 

Check how shrines work to achieve similar effect: https://github.com/vcmi/vcmi/blob/develop/config/objects/shrine.json

**Comment by kdmcser** [comment]
the program is solved by your suggesstion, thank you! now it can be closed.
