### ISSUE TITLE
strings are missing after disabling translation mod

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#3803]
**Describe the bug**
Strings are missing after disabling translation mod. Previously I played with Russian translation, now I disabled it before launching the game.

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/15048295/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/15048296/VCMI_Launcher_log.txt)

**To Reproduce**
1. Install translation mod
2. Start game with it
3. Exit game
4. Disable the mod
5. Start game again
6. Observe missing strings in game settings

**Expected behavior**
Strings present

**Actual behavior**
Strings missing

**Did it work earlier?**
I believe so

**Screenshots**
![android 2024-04-20 16 04 06](https://github.com/vcmi/vcmi/assets/1557784/460a2c71-a900-4cd5-b796-d53528170444)

**Version**
 - OS: Android 64-bit
 - Version: latest develop as of today + Qt launcher

**Comment by IvanSavenko** [comment]
Kind of works as designed. Not sure how to handle it better.

To change a language you need to change language in settings in launcher. VCMI will automatically enable/disable translation mods based on this.
Right now you ended up with situation where vcmi uses cyrillic language, but uses font which only contains latin alphabet.

**Comment by kambala-decapitator** [comment]
thanks, I thought that launcher option only controls launcher language. Will close then.
