### ISSUE TITLE
RoE large elemental dwellings can wrongly appear and block way

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#3808]
RoE large elemental dwellings are used as random dwelling in wrong cases, making some maps unplayable, especially if conflux picked and dwelling type is supposed to match town. Found on map "irrational hostility" - pick conflux as red player and start map
![obraz](https://github.com/vcmi/vcmi/assets/9436577/6f0dc151-5b38-4726-84a6-a4abe9c4d296)

**Comment by DjWarmonger** [comment]
I remember that bug from the past: https://bugs.vcmi.eu/view.php?id=900
But it was fixed in 2012 :P
