### ISSUE TITLE
Hero level updater doesn't work with "increase growth" specialty

### ISSUE THREAD

**Issue by Warzyw647** [vcmi/vcmi#3813]
**Describe the bug**
I added CREATURE_GROWTH and CREATURE_GROWTH_PERCENT to some heroes' specialties with a GROWS_WITH_LEVEL updater. The growth increase works, but doesn't depend on the hero's level.
Not sure weather to label it as a bug or missing feature.

**Game logs**
Not sure if useful, but here's the client log:
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/15051559/VCMI_Client_log.txt)
No new entries in the Server log.

**To Reproduce**
1. Enable the attached mod. I also had vcmi extras and vcmi essentials active.
2. Start map Arrogance with Castle and select starting hero Adela or one of the others changed in the mod.
3. Enter Fort in the town and observe that the creature growth is doubled as expected.
4. Exit town and enter the cheat code:
vcmiexp 82000
in order to bring Adela to level 20.
6. Enter Fort in the town and observe that the creature growth has not increased.

**Expected behavior**
Given the hero's specialty, the creature growth should increase with the hero's level.

**Actual behavior**
The creature growth doesn't increase with the hero's level.

**Did it work earlier?**
Didn't test with earlier vcmi versions.

**Screenshots**
Observe the changed growth in Fort:
![image](https://github.com/vcmi/vcmi/assets/132299608/43681498-b3da-4003-985a-fea5a24fa6c8)

**Version**
 - OS: tested on Linux
 - Version: tested on version from branch develop, about a week old

**Additional context**
I've attached an example of a mod that tries to use GROWS_WITH_LEVEL updater with a CREATURE_GROWTH_PERCENT specialty:
[Growth.zip](https://github.com/vcmi/vcmi/files/15051477/Growth.zip)

**Comment by DjWarmonger** [comment]
Okay, looks like bonus value is not updated since it instantly propagates to Team node and skips hero node evaluation.

**Comment by DjWarmonger** [comment]
Ok, got it. You need to use '"propagationUpdater" instead of "updater".

**Comment by DjWarmonger** [comment]
Alright, looks like actual bug in bonus system - trying to remove bonus which is not there.

**Comment by DjWarmonger** [comment]
This is corrected json that works with recent fix:

```
				"przyrost" :
				{
					"type" : "CREATURE_GROWTH_PERCENT",
					"propagationUpdater" : 
					{
						"parameters" : [ 20, 1 ],
						"type" : "GROWS_WITH_LEVEL"
					},
					"propagator" : "TEAM_PROPAGATOR"
				}
```

`val` was useless since it's replaced by updated value.
