### ISSUE TITLE
Nullkiller AI hang in 2 hero limit

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#3818]
**Describe the bug**
boost AI mod limit heroes number to 2， when AI's  turn, console display error message again and again, this turn cant be ended.

[2024-Apr-22 18:41:24.900406] ERROR [runNetwork] network - System message: Server encountered a problem: Cannot swap artifacts!
[2024-Apr-22 18:41:24.900440] ERROR [runServer] global - Got false in applying 17ExchangeArtifacts... that request must have been fishy!

![1](https://github.com/vcmi/vcmi/assets/8289682/e2377e5b-cc74-4bf9-a130-2716d7377ed8)

I load the save game and find out which artifacts the purple AI player exchanges:

![2](https://github.com/vcmi/vcmi/assets/8289682/d1311975-29c4-4614-a381-1357346278b5)

**Game logs**
Too large can not be unload

**To Reproduce**
enable boost AI mod and all submods , loading the save file will reporduce it： 
[6.zip](https://github.com/vcmi/vcmi/files/15062009/6.zip)

**Expected behavior**
AI turn ends

**Actual behavior**
AI turn never end

**Did it work earlier?**
I dont now

**Screenshots**
see above

**Version**
 - OS:  Windows
 - Version: daily build

**Additional context**
no

**Comment by SoundSSGood** [comment]
Duplicate https://github.com/vcmi/vcmi/issues/3754

**Comment by nullkiller** [comment]
Is it possible to exchange artifacts manually? Are these some specific ones?

**Comment by kdmcser** [comment]
yes，I can manually exchange artifacts by the top button in both directions. I've no idea why AI cant.
