### ISSUE TITLE
crashdumps

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3824]
This is an attempt to cause accidents before release. Here are crash dumps that happened on the autoskip. Perhaps some of them will be useful. the list will be updated

https://drive.google.com/drive/folders/1oeRT8aY1wkTky6gDcBxMWqm2oYSnFG_g?usp=drive_link
https://drive.google.com/drive/folders/17zfGXyAjQDVV1kfzwxjDRluA210bzkap?usp=drive_link
https://drive.google.com/drive/folders/1-ATRviN_pJu1cUv3Q4xTuVq8OzH00OJO?usp=drive_link
https://drive.google.com/drive/folders/1F5zfiZ1fQ8l7_uU5jrqpakRjr9p-3fn6?usp=drive_link
https://drive.google.com/drive/folders/1x1hNxsoGRxEaWpMwCSXYATmfljO_n7Yr?usp=drive_link
_I don't know how to extract debugging information from them, sorry._

My list of mods: https://drive.google.com/file/d/1gfv0l4KzaGRDTN0E8dMR8RUkyHSaN8Zd/view?usp=drive_link

b4abb3a56c8067082ac7a80ca252ed7ffadcd6ed, msvs
***
b2b085fb94a69a52a762a3e807ee257e7e0b6046
almost no mods
https://drive.google.com/drive/folders/13427thWBP78X2lBS9945mHS3FjMplRqR?usp=drive_link
https://drive.google.com/drive/folders/18ClAn_UHxOgqdWuPcUUKQldwZc05Eb8v?usp=drive_link

**Comment by IvanSavenko** [comment]
3 different crashes in total, 2 related to AI, 3rd related to "Worn out spellbook" from Antagarich Burning. Will investigate this one

@nullkiller 
Can you check these two AI-related crashes when you have a moment?

Crash 1 (two such dumps): looks like `cluster->blocker` is corrupted - probably uninitialized or deleted object.
```
Nullkiller.dll!NKAI::Goals::UnlockCluster::toString() Line 28	C++
Nullkiller.dll!NKAI::Goals::Composition::toString() Line 39	C++
Nullkiller.dll!NKAI::Nullkiller::makeTurn() Line 378	C++
Nullkiller.dll!NKAI::AIGateway::makeTurn() Line 853	C++
```

Crash 2: looks like another case of hero without army - only commander is present.
As result `resultingArmy` is (apparently) empty, and `weakest` is nullptr
```
Nullkiller.dll!NKAI::ArmyManager::getBestArmy(const IBonusBearer * armyCarrier, const CCreatureSet * target, const CCreatureSet * source) Line 226	C++
Nullkiller.dll!NKAI::ArmyManager::howManyReinforcementsCanGet(const IBonusBearer * armyCarrier, const CCreatureSet * target, const CCreatureSet * source) Line 351	C++
Nullkiller.dll!NKAI::Goals::GatherArmyBehavior::deliverArmyToHero(const NKAI::Nullkiller * ai, const CGHeroInstance * hero) Line 110	C++
Nullkiller.dll!NKAI::Goals::GatherArmyBehavior::decompose(const NKAI::Nullkiller * ai) Line 48	C++
Nullkiller.dll!NKAI::DeepDecomposer::decomposeCached(NKAI::Goals::TSubgoal goal, bool & fromCache) Line 210	C++
Nullkiller.dll!NKAI::DeepDecomposer::decompose(std::vector<NKAI::Goals::TSubgoal,std::allocator<NKAI::Goals::TSubgoal>> & result, NKAI::Goals::TSubgoal behavior, int depthLimit) Line 53	C++
Nullkiller.dll!NKAI::Nullkiller::decompose(std::vector<NKAI::Goals::TSubgoal,std::allocator<NKAI::Goals::TSubgoal>> & result, NKAI::Goals::TSubgoal behavior, int decompositionMaxDepth) Line 174	C++
Nullkiller.dll!NKAI::Nullkiller::makeTurn() Line 354	C++
Nullkiller.dll!NKAI::AIGateway::makeTurn() Line 853	C++
```

**Comment by nullkiller** [comment]
ok

**Comment by IvanSavenko** [comment]
All crashes should be fixed now in beta. Thanks for reports.
