### ISSUE TITLE
Just doubts...

### ISSUE THREAD

**Issue by SilentMRG** [vcmi/vcmi#3844]
Hello everybody!

Firstly, I want to say that I met this excellent source port today. And so far it has been very enjoyable to play through it. =D

However, as soon as I started the game, I noticed this:

![0](https://github.com/vcmi/vcmi/assets/62117728/eb427bd3-00a2-469a-9fde-241e56c1177b)

And I was intrigued, what are these yellow and red warnings? I'm on Windows 7 64-bit. And I downloaded the latest version in ".zip" format. I started through "VCMI_client", and noticed that it tried to connect to a server (?). Wasn't the client ".exe" supposed to be 100% offline?

Finally, I think I installed everything correctly:

![1](https://github.com/vcmi/vcmi/assets/62117728/33eaa581-9691-4606-8bf7-945d43213a26)

Yes or no?

Thank you very much for your attention and best regards! ;)

**Comment by ToRRent1812** [comment]
Have you tried launching the game from the launcher?

**Comment by DjWarmonger** [comment]
> and noticed that it tried to connect to a server (?). Wasn't the client ".exe" supposed to be 100% offline?

It works offline but it's based on client-server architecture.

Still, in latest version client and server run in a single process on desktop systems.

**Comment by nullkiller** [comment]
It may ask to enable it through Windows Firewall, it is not required if you do not plan to host multiplayer game.

**Comment by SilentMRG** [comment]
> Have you tried launching the game from the launcher?

Yes, but starting from it doesn't give me a cmd window, so I can't check if those yellow and red warnings appear.

> > and noticed that it tried to connect to a server (?). Wasn't the client ".exe" supposed to be 100% offline?
> 
> It works offline but it's based on client-server architecture.
> 
> Still, in latest version client and server run in a single process on desktop systems.

I understood. Thanks for the quick response. =)

> It may ask to enable it through Windows Firewall, it is not required if you do not plan to host multiplayer game.

My focus is just single player, I'm a complete noob at this game, I need to train a lot to then go into multiplayer, hehe.

**Comment by IvanSavenko** [comment]
Messages in that cmd window are mostly for developers & game modders. If you just want to play then you don't need to pay any attention to them.

**Comment by SilentMRG** [comment]
> Messages in that cmd window are mostly for developers & game modders. If you just want to play then you don't need to pay any attention to them.

I understood. My fear was that maybe I had done something wrong, installed the game files wrongly, in short, I thought I was missing something that would impact the gameplay sooner or later. Thanks for responding. :)
