### ISSUE TITLE
Crash on the AI turn

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3851]
Here's just a dump. For some reason.
https://drive.google.com/file/d/1647gTF1TIbX7nVv20s-n_WZiOK1aJybX/view?usp=drive_link
844686f714fe84411f9b6e5b5fd2089043940360, msvs

**Comment by IvanSavenko** [comment]
Probably already fixed in #3839

**Comment by nullkiller** [comment]
Might be. This bug was fixed recently and the build used is older.

**Comment by Povelitelh3** [comment]
Ok, then I will close it with your permission.
