### ISSUE TITLE
crashdumps

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3855]
They were found in be54836401ed58a555ee500b635105f639f8badf
https://drive.google.com/file/d/1kbPfyU5rJlGcJ5wrxG3y_1vVUVC-v2X_/view?usp=drive_link
https://drive.google.com/file/d/1JUH4O3YbTFUfXIvOAQyCCy3AQZyNq1DR/view?usp=drive_link

crash on AI turn
***
85104783555c588aa622d9ccd7ae2b2b030e1fe1
https://drive.google.com/file/d/1Kqc-UA-KEM6IMheygjUt4SkudJeS9kIJ/view?usp=drive_link
may be related to events 
![изображение](https://github.com/vcmi/vcmi/assets/36762538/532ef4b0-eb5e-4736-9df8-784f7f6ccd0e)
***
https://drive.google.com/file/d/1UHZwp4JfBpruZoyvt9RyvD2af-Q1FEcj/view?usp=drive_link

1d28f25575c9378c140eb15dba34d7b30b907375

https://drive.google.com/file/d/1G6EPnt7elo_cROzo4NnMNyCVv4zUa_aF/view?usp=drive_link
https://drive.google.com/file/d/1ATq1I4zP5SrbWeiygXefknPY8nBefQfD/view?usp=drive_link
[1.zip](https://github.com/vcmi/vcmi/files/15196963/1.zip)
[1_1.zip](https://github.com/vcmi/vcmi/files/15196967/1_1.zip)

**Comment by nullkiller** [comment]
Both crashes are in performAutosave because LOCPLINT is null. Might be that game ended on autoskip. GH looks like saying that current intObj is main menu.

**Comment by Povelitelh3** [comment]
added more 1

**Comment by Povelitelh3** [comment]
one more added

**Comment by Povelitelh3** [comment]
two more added

**Comment by IvanSavenko** [comment]
> two more added

Same, already fixed in #3878
Will merge it soon.

**Comment by nullkiller** [comment]
Looked at dump, hard to say what went wrong. Also a bit outdated version of build. Closing it and see if more such crashes will pop out. Crash was in destructor of HeroActor.

**Comment by nullkiller** [comment]
Also there was an idea to rewrite it using tbb::concurrent_something to avoid manual lock management.
