### ISSUE TITLE
Long specialty description doesn't fit in hero info window

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3859]
**Describe the bug**
When hero has long specialty description, it doesn't fit in hero info popup displayed during starting hero selection.

**To Reproduce**
Yaverr is a hero from Tides of War mod.

**Expected behavior**
Add a scrollbar for this field

**Actual behavior**
Hero specialty description is truncated and it's impossible to read the full text.

**Did it work earlier?**
I don't think so.

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/2566990/b3e4970e-cf87-47f9-9191-a2df1b6e1962)

**Version**
beta 1.5

**Additional context**
Reported on PvP Discord

**Comment by Laserlicht** [comment]
Scrollbar is a problem here. It's a pop-up menu. And you cannot use left mouse button for scrolling while holding the right mouse button.

Would prefer to edit the mod. We don't need the specialty name twice. OH3 heroes have it also only once (all OH3 strings fits into the box).
