### ISSUE TITLE
Nullkiller AI hang again in daily build

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#3868]
**Describe the bug**
it seems that bug #3818 has not been solved in newest daily build. I meet it again.

![1](https://github.com/vcmi/vcmi/assets/8289682/73954041-369f-42cc-8af6-657189e5ebd2)

This two heroes meet:

![2](https://github.com/vcmi/vcmi/assets/8289682/8ab4e132-ffd8-4a29-afe9-8700a55419f0)

**Game logs**
[VCMI_Client_log.zip](https://github.com/vcmi/vcmi/files/15173295/VCMI_Client_log.zip)

**To Reproduce**
load this save file
[2.zip](https://github.com/vcmi/vcmi/files/15173300/2.zip)

**Expected behavior**
AI turn end

**Actual behavior**
AI turn hang

**Did it work earlier?**
no idea

**Screenshots**
no

**Version**
 - OS:  Windows
 - Version: daily build

**Additional context**
no

**Comment by Povelitelh3** [comment]
This bug was fixed in beta

**Comment by kdmcser** [comment]
OK
