### ISSUE TITLE
Incorrect string lookup in Festival of Life campaign

### ISSUE THREAD

**Issue by 6b6279** [vcmi/vcmi#3886]
**Describe the bug**
Kligor appears as "map.festival:3.heroes.149.name" in the second scenario of the Festival of Life campaign.

**Game logs**
```
Loading procedure started!
Game state was transferred over network, loading.
Game loaded, initialize interfaces.
Preparing environment for player neutral
Preparing environment for player red
Preparing interface for player red
Player red will be lead by human
Opening StupidAI
Loaded Stupid AI 0.1
```

**To Reproduce**
1. Complete the first scenario of the Festival of Life campaign.
2. Upon starting the second scenario, Kligor will appear as "map.festival:3.heroes.149.name" instead of "Kligor".

**Expected behavior**
Kligor's name should be resolved correctly.

**Actual behavior**
Kligor's name is missing, moreover, the query string for his name seems to not get resolved at all.

**Did it work earlier?**
I have experienced a similar bug with Sir Michael (prison hero, copy of Christian) in the second scenario of the Playing with Fire campaign.

**Screenshots**
![20240504_14h34m50s_grim](https://github.com/vcmi/vcmi/assets/109346960/08dbc8a7-4870-4a06-a608-ed11df774d29)

**Version**
 - OS: Arch Linux x86
 - Version: 1.4.5, Flatpak

**Comment by IvanSavenko** [comment]
Should be already fixed in 1.5.
