### ISSUE TITLE
crash with build ace1a4c on macOS M1

### ISSUE THREAD

**Issue by herve-ch** [vcmi/vcmi#3889]
**Describe the bug**
Hello my game is crashing with latest build. No mod, just playing campaign
Thank you

**Save file**
[campaign_7.vsgm1.zip](https://github.com/vcmi/vcmi/files/15212240/campaign_7.vsgm1.zip)

**To Reproduce**
1. Click next turn, game crash (save game is attached)

**Expected behavior**
No crash

**Actual behavior**
It crash

**Version**
 - OS: macOS ARM M1
 - Version: ace1a4c

**Comment by kambala-decapitator** [comment]
no crash for me in an Intel Mac with the latest beta build from 6ac67775f5664ffbcedd7e510fb91b0f4e7432ad

please post the crash log

**Comment by herve-ch** [comment]
Sure 

[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/15212308/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/15212309/VCMI_Launcher_log.txt)

**Comment by kambala-decapitator** [comment]
although game logs are also important, crash log isn't among them. You can find it in the Console app - Crash Reports

**Comment by IvanSavenko** [comment]
Ah, I think I know what's wrong. Animation of new wandering monsters on new month. Fixed in #3878

Try latest beta build from here:
https://download.vcmi.eu/branch/beta/macOS/

**Comment by herve-ch** [comment]
Yes thank you it works with latest beta build!
