### ISSUE TITLE
Game Lag, then freeze on MacOS ARM with latest builds

### ISSUE THREAD

**Issue by herve-ch** [vcmi/vcmi#3903]
**Describe the bug**
When I play a game, the game lag then freeze randomly after a few minutes. App become unresponsive and I have to kill the process. It happen only with the newest builds (develop and beta)

**To Reproduce**
Just play anytime for few minutes then game become to lag then freeze

**Did it work earlier?**
Had no freeze with VCMI-branch-beta-48a9696

**Screenshots**

**Version**
 - OS: MacOS M1
 - Version: Tried VCMI-branch-beta-66f1f48, VCMI-branch-develop-b827ac2, both freeze

**Additional context**
There is nothing interesting in logs

**Comment by herve-ch** [comment]
I tried previous beta build VCMI-branch-beta-20fc2b6 and no lag or freeze issue on macOS M1

**Comment by IvanSavenko** [comment]
Investigating

**Comment by IvanSavenko** [comment]
Fixed, try latest build, `VCMI-branch-beta-3e5e120`
Thanks for quick report.
