### ISSUE TITLE
Some combination artifacts can't be equipped

### ISSUE THREAD

**Issue by macomarivas** [vcmi/vcmi#3919]
Some [**Combination Artifacts** ](https://heroes.thelazy.net/index.php/Combination_artifact)can't be equipped and the effects of the artifact are not applied.

Get the required elements for the combined artifact.

**Expected behavior**
The artifact should be equipped and the effects should be applied.

**Actual behavior**
The artifact can't  be equipped

**Did it work earlier?**
I'm not sure.

**Mods**
- Portraits Packs 1.2
- In The Wake of Gods 9.1.13
- VCMI 1.4
- VCMI extras 3.5.3
- Spanish translation 1.0.1
- Horn of the Abyss 1.6.41

**Screenshots**
![Captura de pantalla de 2024-05-09 11-24-01](https://github.com/vcmi/vcmi/assets/66029412/94fed276-0ca7-480b-88ba-c3caf1cb34ca)
Only the [Cloak of the Undead King](https://heroes.thelazy.net/index.php/Cloak_of_the_Undead_King) works as expected.

![Captura de pantalla de 2024-05-09 11-24-33](https://github.com/vcmi/vcmi/assets/66029412/48bf175d-2d5b-4bdb-9a2c-e0fa64aa8b0c)
![Captura de pantalla de 2024-05-09 11-26-09](https://github.com/vcmi/vcmi/assets/66029412/4bc391c0-5c56-4156-89ba-8ee4582658fb)
![Captura de pantalla de 2024-05-09 11-27-13](https://github.com/vcmi/vcmi/assets/66029412/a9873411-1a01-4359-922e-c87741a173b9)

**Version**
 - OS: Linux Mint
 - Version: 1.4.5

https://heroes.thelazy.net/index.php/Combination_artifact

**Comment by SoundSSGood** [comment]
Could you please describe the steps to reproduce in more detail?

**Comment by macomarivas** [comment]
Sure!

- Go with your Hero/Commander trough the map, looking for the required **Artifacts** to create a **Combined Artifact**, list [here](https://heroes.thelazy.net/index.php/Combination_artifact).
- When you have all required **Artifacts**, right click to combine them (a question should appear).
- Try to equip the combined artifact.

**Comment by SoundSSGood** [comment]
I can't reproduce it at the moment.
Are there enough free slots for a combined artifact?

**Comment by macomarivas** [comment]
Sorry, you're right, I didn't try to free the slots before.

![Captura de pantalla de 2024-05-09 12-50-12](https://github.com/vcmi/vcmi/assets/66029412/dd965f2f-aea8-47e5-80fc-ed890e866d43)
![Captura de pantalla de 2024-05-09 12-50-53](https://github.com/vcmi/vcmi/assets/66029412/90c1d66c-07a6-4cbf-b766-7d4d70a238b7)
![Captura de pantalla de 2024-05-09 12-52-20](https://github.com/vcmi/vcmi/assets/66029412/5c677632-14de-44ce-b58c-237269deb7e7)
![Captura de pantalla de 2024-05-09 12-52-04](https://github.com/vcmi/vcmi/assets/66029412/e92ea409-15ed-48e4-8a1f-fe2e0322f919)

It could help if when trying to equip the artifact, all the required slots will be highlighted.

:-)

**Comment by dydzio0614** [comment]
highlighting could be confusing since for all use cases it is used to mark target slot

**Comment by macomarivas** [comment]
Looking at the screenshots, Hero/Commander attributes, individual effects of each artifact do not apply (ex: Titan's Thunder)
