### ISSUE TITLE
Unacceptable how hero specialty work for modding

### ISSUE THREAD

**Issue by madaosoul** [vcmi/vcmi#3949]
Hero specialty in 1.5 allows for a default creature specialty + exactly one bonus that is defined with VCMI bonus system. 

So if you want to create a hero that specializes in two spells (this should be doable, and I'm 90% sure this was possible before some new bonus format nonsense was added), one spell boost is overwritted by the other. And if you want your hero to boost two primary skills, then ... too bad, you only get one. 

To reproduce:
make a mod with a hero who's specialty does two things (different from the default creature specialty) and observe that it only does one of them. For example:

		"specialty": 
		{
			"bonuses" : {

				"shild" : {
					"subtype" : "primSkill.defence",
					"type" : "PRIMARY_SKILL",
					"val" : 1,
					"updater" : "TIMES_HERO_LEVEL"
				},
				
				"sord" : {
					"subtype" : "primSkill.attack",
					"type" : "PRIMARY_SKILL",
					"val" : 1,
					"updater" : "TIMES_HERO_LEVEL"
				}
			}
		}

**Comment by henningkoehlernz** [comment]
I'm running a mod that adds multiple bonuses as hero specialty, and it works just fine:
[https://github.com/henningkoehlernz/vcmi-mods/blob/master/boost_core/Content/config/boost_core/heroes/castle.json](https://github.com/henningkoehlernz/vcmi-mods/blob/master/boost_core/Content/config/boost_core/heroes/castle.json)

**Comment by henningkoehlernz** [comment]
Did run into an issue here after more experimenting. In some cases (not sure what's the precise condition), the last bonus of three is not added. Here last depends on the key value ("shild" or "sord" in the example above).

**Comment by madaosoul** [comment]
Right, confirmed that format posted by hkoehlernz indeed works. Thanks to that, Pavillion's tent specialist will still heal more with upgraded tents. And with that, it's possible to make infinite number of bonuses. But it's still kind of non-intuitive.

**Comment by IvanSavenko** [comment]
Fixed in 1.5.2
