### ISSUE TITLE
Got stuck in water while flying

### ISSUE THREAD

**Issue by henningkoehlernz** [vcmi/vcmi#3951]
**Describe the bug**
While wearing Angel Wings and picking up a chest at the shoreline, the hero moved to the closest free point, which happened to be a water tile. Afterwards moving out of the tile wasn't possible anymore.

**Expected behavior**
Hero should move to the closest tile they are allowed to occupy at the end of a move.

**Actual behavior**
Moved to the closest tile they could transit through.

**Screenshots**
![Screenshot from 2024-05-12 20-04-22](https://github.com/vcmi/vcmi/assets/20719746/b2a02805-27b5-4fc1-8009-0f628083f6d6)

**Version**
 - OS: Ubuntu 20.04
 - Version: 1.5

**Comment by IvanSavenko** [comment]
Fixed in 1.5.2
