### ISSUE TITLE
amount of resurrected Vampires doesn't appear in battle log

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#3957]
Should be something like "...and X rise from the dead!"

![Screenshot 2024-05-12 at 13 20 15](https://github.com/vcmi/vcmi/assets/1557784/39545d00-dcbd-41ff-b19c-4ed7452f7fae)

1.5 release

**Comment by MichalZr6** [comment]
Hi everyone!
I'm new to OpenSource contributions, but also a great fun of HOMM3.
I think this small issue can be fixed starting with this part of code in BattleActionProcessor.cpp:
![obraz](https://github.com/vcmi/vcmi/assets/50074545/45741b1b-0f58-49a7-b9c8-0ba2ab465dfc)

Can someone point me to the file that contains those string literals used in for ex. in the battle log ?
They are obtained from "core.genrltxt" but where is it located ?
![obraz](https://github.com/vcmi/vcmi/assets/50074545/c1620dca-24a9-4341-9ced-9ca5da616af6)

**Comment by IvanSavenko** [comment]
Hi. You can look up these strings for example in English translation mod:
https://github.com/vcmi-mods/h3-for-vcmi-englisation/blob/vcmi-1.4/H3forVCMIenglisation/content/config/h3forvcmienglisation/game.json

Alternatively you can export this data using `/translate` command

**Comment by kambala-decapitator** [comment]
please never post code as image, paste as text or give a link to specific line inside a file of repository

**Comment by MichalZr6** [comment]
After digging into the topic, I think I can come up with a solution :) I built the repo yesterday and might do some tests later today. Side note: Cure also doesn't log info about restored HP.

**Comment by kambala-decapitator** [comment]
FYI issue about restored hp: #1007

**Comment by kambala-decapitator** [comment]
fixed by #4040

**Comment by sanfanling** [comment]
I am using 1.7.0, when start the animation of resurrection vampire lord, the whole game is crashes, 100%

**Comment by kambala-decapitator** [comment]
> I am using 1.7.0, when start the animation of resurrection vampire lord, the whole game crashes, 100%

please open new issue about that, it's not related to this one
