### ISSUE TITLE
Clicking on UI as non-host in direct ip multiplayer crashes the game

### ISSUE THREAD

**Issue by ToRRent1812** [vcmi/vcmi#3961]
When You host a direct IP game, and clients click on something (like pick a castle), the game crashes. It wasn't happening in 1.4.5. In new online lobby room, everything works fine.

Unfortunately, logs were overwritten by successful lobby game later on, but it's 100% reproducible in our case.

OS: OpenSuse tumbleweed
VCMI 1.5 from Flathub

**Comment by IvanSavenko** [comment]
Unable to reproduce with current build.
May have been fixed already since 1.5. 
Please recheck 1.5.1 (once it is out)

**Comment by IvanSavenko** [comment]
Can you check if this is still a problem in 1.5.1 release?
