### ISSUE TITLE
Transition to the next scenario doesn't work

### ISSUE THREAD

**Issue by wb180** [vcmi/vcmi#3977]
**Describe the bug**
Long live the queen campaign(Scenario №1) after the town is captured, transition to the next scenario doesn't work

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/15312386/VCMI_Client_log.txt)

**To Reproduce**
1. Load the save before the final battle
2. Win the battle
3. Observe the result

**Expected behavior**
The transition to the next scenario

**Actual behavior**
Client is not frozen, but transition is not happening, the current game is also not playable.

**Did it work earlier?**
It certainly was.

**Screenshots**
If applicable, add screenshots to help explain your problem
Before the battle
![Screenshot_20240514_212321](https://github.com/vcmi/vcmi/assets/109801241/044686ee-b35a-4e39-96db-baf636d6ec65)
Battle
![Screenshot_20240514_212429](https://github.com/vcmi/vcmi/assets/109801241/f5752a2a-df77-4fd2-ba7e-1455e06cf709)
After
![Screenshot_20240514_212442](https://github.com/vcmi/vcmi/assets/109801241/c2347f42-115d-4313-a1d9-870da9195acc)
.

**Version**
 - OS: Linux OpenSUSE Tumbleweed
 - Version: Beta as of https://github.com/vcmi/vcmi/commit/da9d82b6972d56c6b4cbf678dca2d30e61859259

**Additional context**
[lltq_7.vsgm1.zip](https://github.com/vcmi/vcmi/files/15312443/lltq_7.vsgm1.zip)

**Comment by IvanSavenko** [comment]
Huh, quite an interesting merge "conflict"
- beta before my merge would work
- branch that I merged would work
- beta after my merge broken. And there were 0 conflicts during merge

I think I know what's wrong, will fix ASAP. Thanks for reporting.

**Comment by wb180** [comment]
Now works as expected
