### ISSUE TITLE
Resurrection effect doesn't hold after battle

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#3978]
1. resurrect your units (e.g. to full)
2. win battle
3. in the casualties dialog losses are shown as if you didn't resurrect them
4. resurrected units also don't stay on hero after the battle as if they died

tested using Resurrection spell. In the last battle I resurrected 2 Minotaurs that were killed by Azure Dragons.
[VCMI_Client_log.txt.tgz](https://github.com/vcmi/vcmi/files/15312692/VCMI_Client_log.txt.tgz)

1.5 release

**Comment by Alucard648** [comment]
This spell requires Advanced Earth Magic secondary skill for targeted creatures to stay alive after battle.

**Comment by kambala-decapitator** [comment]
> This spell requires Advanced Earth Magic secondary skill for targeted creatures to stay alive after battle.

oh wow, something new to learn every day... Thanks!
