### ISSUE TITLE
hero is unable to move

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#3993]
The first hero can't move anywhere even though he has Angel Wings. I suspect that the game thinks he's standing on water but has no boat. Also I see that he has much less movement points at the day start that he should have (2 pairs of gloves + boots + logistics). Checking move cost with Alt also doesn't show any cost for any tile.

Same happens if you eat the Scholar nearby instead of the Crown.

- save where hero is standing on bad cell and on next day can't move: [1.vsgm1.tgz](https://github.com/vcmi/vcmi/files/15340318/1.vsgm1.tgz)
- save one day before that: [5.vsgm1.tgz](https://github.com/vcmi/vcmi/files/15340324/5.vsgm1.tgz)

[VCMI_Client_log.txt.tgz](https://github.com/vcmi/vcmi/files/15340325/VCMI_Client_log.txt.tgz)

1.5 release

**Comment by kambala-decapitator** [comment]
there hero is clearly standing in water while my stands on the coast. One more nearby place with the same:

![Screenshot 2024-05-16 at 23 19 46](https://github.com/vcmi/vcmi/assets/1557784/3a14b7eb-13ff-47ca-b971-1eb53792ffbd)

Also if I try to use DD out of this state, spell points are consumed but I get dialog "DD failed!". 
[VCMI_Client_log.txt.tgz](https://github.com/vcmi/vcmi/files/15340447/VCMI_Client_log.txt.tgz)

**Comment by IvanSavenko** [comment]
Coast is still "water" and can only be reached by boat. So looks to be the same

**Comment by kambala-decapitator** [comment]
oh, quite possible then

**Comment by kambala-decapitator** [comment]
looks like this is the pathfinder issue:

![Screenshot 2024-05-16 at 23 27 13](https://github.com/vcmi/vcmi/assets/1557784/673bbc81-5cca-4e1f-9dfc-4893a4552ded)

**Comment by kambala-decapitator** [comment]
and now I understand why AI hero is standing still in this place for many turns :)

![Screenshot 2024-05-16 at 23 32 03](https://github.com/vcmi/vcmi/assets/1557784/fb17da28-55ee-4f8c-a637-c20e39c72150)

**Comment by kambala-decapitator** [comment]
yeah, attacked that enemy hero, and the battle takes place on boat background

**Comment by IvanSavenko** [comment]
Fixed in 1.5.2
