### ISSUE TITLE
Next Hero button is enabled although no heroes can move

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#4010]
This hero on the video (the last one in the list) has remaining 58 move points, but must go off-road due to wolf raiders hence not able to make the move. Still, the game thinks that the hero can move and shows the Next Hero button. I suspect it's related to #3939

https://github.com/vcmi/vcmi/assets/1557784/04c88162-90e6-4c44-89e3-031c776e4c75

1.5.1 release

**Comment by IvanSavenko** [comment]
Not sure if this is a bug or not. After all he can move in some directions.

**Comment by kambala-decapitator** [comment]
> Not sure if this is a bug or not. After all he can move in some directions.

you're right indeed, the hero can move back on the road. Definitely not a bug then.
