### ISSUE TITLE
Archangels retaliate to Archdevils according to the hint

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#4011]
Haven't found any info on h3lazy saying that it should be possible

![Screenshot 2024-05-19 at 13 01 10](https://github.com/vcmi/vcmi/assets/1557784/3abf9abc-d7cb-4d71-a909-1108c5236f10)

1.5.1 release

**Comment by IvanSavenko** [comment]
Fixed in #3996 (once merged)
