### ISSUE TITLE
Mod update function for Android

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [vcmi/vcmi#4026]
**Describe your proposal**
Instead of manually checking any mod updates on Windows counterpart, go back to Android then manually deleting & reinstalling the mod, can we implement the same as in Windows app?

Put an exclamation mark saying that there's an update then put a button to download it & update it like in Windows.

Coz currently there's no way to know if there's any mod updates on Android.

**Comment by IvanSavenko** [comment]
Hello. We are planning to port our launcher from desktop version of vcmi to Android relatively soon. Which does supports mod updates including notifications

**Comment by IvanSavenko** [comment]
Implemented in #3817

**Comment by Crescendo-BLYAT** [comment]
Thanks 😊 

But the interface now janky & hard to use without mouse.
Maybe make it bigger for touch usage?

Take an example the language selection list, good luck in selecting anything in it.

**Comment by IvanSavenko** [comment]
Are you using latest release / version from Google Play? Could be something device-specific? 

Yeah, UI elements are slightly smaller than in most Android UI, but still big enough to reliably hit with touch.

**Comment by Crescendo-BLYAT** [comment]
Yes, always the latest and greatest from Play Store mate.

Maybe redesign the UI with touch usage in mind?
I'm using S20FE.

**Comment by kambala-decapitator** [comment]
> Maybe redesign the UI with touch usage in mind?

suggestions / sketches are welcomed
