### ISSUE TITLE
Nullkiller AI requires ability to cheat

### ISSUE THREAD

**Issue by henningkoehlernz** [vcmi/vcmi#4029]
**Describe the bug**
Some times during the AI turn, the Nullkiller AI complains that it requires the ability to cheat, and that you should enable it. Not sure whether AI cheating is something that needs to be enabled separately, but running defaults and player cheat codes work.

**Screenshots**
![Screenshot from 2024-05-22 14-41-43](https://github.com/vcmi/vcmi/assets/20719746/da194548-d963-453c-aba2-0af74a0b937d)

**Version**
 - OS: Ubuntu 22.04
 - Version: 1.5.1

**Additional context**
Happens frequently (but not every turn) during hot seat multiplayer game.

**Comment by Laserlicht** [comment]
Should only appears once per AI. And only if cheats are disabled in "Extra options". This is default for multiplayer games if you don't change.

But this will be removed anyway for the next release with #4009

**Comment by nullkiller** [comment]
Yes. Already in beta so will be resolved with 1.5.2
