### ISSUE TITLE
Crash on GOG extraction (VIDEO.VID)

### ISSUE THREAD

**Issue by q-b** [vcmi/vcmi#4031]
**Describe the bug**
VCMI crash when extracting GOG files (complete edition)

**Game logs**
```
Extracting "Heroes of Might and Magic® 3 - Complete" - setup data version 5.6.2 (unicode)
Opening "/tmp/vcmilauncher-gpQKZS/h3_gog-1.bin"
 59.7%   162 MiB/sterminate called after throwing an instance of 'std::runtime_error'
  what():  Error writing file "/tmp/vcmilauncher-gpQKZS/Data/VIDEO.VID"
```

**To Reproduce**
Start VCMI
Language > English > Next
Heroes III Data > Install gog.com files
GOG installer : `setup_heroes_of_might_and_magic_3_complete_4.0_(28740).exe` > Open
GOG data : `setup_heroes_of_might_and_magic_3_complete_4.0_(28740)-1.bin` > Open
Wait until it reaches ~60%

**Version**
VCMI flathub version 1.5.1
mac m2 (aarch64) Fedora Linux Asahi Remix 40

**Comment by Laserlicht** [comment]
Can you look into the temp folder of flatpak. Is there the bin file? How big is it?
Should be under: `/run/user/1000/.flatpak/eu.vcmi.VCMI/tmp` and in a folder starting with `vcmilauncher-`.

How big is the file?

@Alexander-Wilms Seems to be a flatpak specific issue as flatpak don't use `/tmp`. And the tmpfs under `/run/user/1000` seems in this case to small to hold all files. For example in my fedora VM only 791MB.
It is possible to use the normal `/tmp` in flatpak?

**Comment by IvanSavenko** [comment]
> It is possible to use the normal /tmp in flatpak?

Or we could use ~/.local/share/vcmi/ or equivalent for extraction - since this is where files will be placed after extraction instead of such temporary directory

**Comment by Alexander-Wilms** [comment]
@Laserlicht Yes, that's what I did for TeXstudio:
https://github.com/flathub/org.texstudio.TeXstudio/blob/master/org.texstudio.TeXstudio.yaml#L31

But the Ivan's suggestion sounds better, since that should always just work.

**Comment by q-b** [comment]
> Can you look into the temp folder of flatpak. Is there the bin file? Should be under: `/run/user/1000/.flatpak/eu.vcmi.VCMI/tmp` and in a folder starting with `vcmilauncher-`.
> 
> How big is the file?
> 
> @Alexander-Wilms Seems to be a flatpak specific issue as flatpak don't use `/tmp`. And the tmpfs under `/run/user/1000` seems in this case to small to hold all files. For example in my fedora VM only 791MB. It is possible to use the normal `/tmp` in flatpak?

Confirmed:

```
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1,6G  1,6G   16K 100% /run/user/1000
```

```
.rw-r--r--@ 1.0G qb   22 May 20:25  setup_heroes_of_might_and_magic_3_complete_4.0_(28740)-1.bin
.rw-r--r--@ 823k qb   22 May 20:25  setup_heroes_of_might_and_magic_3_complete_4.0_(28740).exe
```

```
# /run/user/1000/.flatpak/eu.vcmi.VCMI/tmp/vcmilauncher-glLgNI

Permissions Size User Date Modified Name
...
.rw-r--r--@ 2.7M qb   12 Apr  2019  Heroes3.exe
.rw-r--r--@ 9.1M qb   12 Apr  2019  Heroes3_AB_Manual.pdf
.rw-r--r--@  14M qb   12 Apr  2019  Heroes3_Manual.pdf
.rw-r--r--@ 1.0G qb   23 May 12:54  h3_gog-1.bin
```
