### ISSUE TITLE
Select multiple mods in the Launcher

### ISSUE THREAD

**Issue by Warzyw647** [vcmi/vcmi#4033]
**Describe your proposal**
Allow selecting multiple mods in the Launcher in order to enable/disable/download etc. all of them at once when possible.

**Additional context**
In case only some mods can be enabled, disabled, updated, downloaded or uninstalled, I imagine clicking enable/disable/update etc. would only affect the ones that can be enabled/disabled/updated etc.

**Comment by IvanSavenko** [comment]
- duplicate of #3474
