### ISSUE TITLE
Crash after battle and lvl up in new Wog Commander

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4058]
load save
let's fight with garrison
press ok, (casualty and result of battle)
crash happens, when lvl up grow in new Wog Commander

save [tst2.zip](https://github.com/vcmi/vcmi/files/15497656/tst2.zip)
dump https://drive.google.com/file/d/1tMP86f6VwIoBwEDkUfmtZM32U0UAtrgk/view?usp=drive_link

1.5.2.5c2ca380abad88591d497637adf846f3ca762c39

**Comment by IvanSavenko** [comment]
Nice find.
Will try to reproduce save tomorrow. 
I saw this crash multiple times before, but couldn't reproduce it. But I usually play without wog, so no commanders

**Comment by Povelitelh3** [comment]
> I saw this crash multiple times before, but couldn't reproduce it. But I usually play without wog, so no commanders
Finding some kind of accident without mods is not so easy, at least for me. The ideal scenario is to install the maximum number of mods that do not conflict with each other and then test. But as far as I heard, the launcher may not see conflicts, although they exist.
