### ISSUE TITLE
Victory/loss condition works wrong

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4065]
Victory condition is transport artefact to tower 33 5 0. It town my allies pink.
GreenAI is my enemy, but when it take town I win

I should lose.

map [SoD_Admiral_s_Hat.zip](https://github.com/user-attachments/files/15513686/SoD_Admiral_s_Hat.zip)
save [victoryCondition.zip](https://github.com/user-attachments/files/15513688/victoryCondition.zip)

1.5.2 alternate

**Comment by Alucard648** [comment]
I think, instant loss on town capture for "deliver artifact" victory condition should trigger only if enemy hero, who captured castle in question, also had a copy of required artifact. Also it`s all too logical for having this town belonging to enemy, capture it with the artifact in inventory, worn or in backpack, and trigger win contition for this map.

**Comment by Povelitelh3** [comment]
The enemy had this artifact during the siege. And after he killed my ally, this city ceased to be the city of an ally.
Accordingly, there is no way I can win the game
