### ISSUE TITLE
Need a bonus: death without body remains

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#4073]
**Describe your proposal**
For factory use, I plan to make a substitute skill for Automaton.

And for the Ring of Oblivion, all creatures' corpses will disppear after death.

I name the bonus 'NO_BODY_REMAIN' 
similar like summoned units.

Any units who have this ability, their bodies will disappear after death.

**Comment by Alucard648** [comment]
Same for bonuses, like "DISINTEGRATING_ATTACK" for creatures and spells.

**Comment by jeyms233** [comment]
``

**Comment by by003** [comment]
>  like "DISINTEGRATING_ATTACK" for creatures and spells.

I can't find this bonus in current repo.

**Comment by Alucard648** [comment]
Yes, I am also suggesting to add this bonus.

**Comment by IvanSavenko** [comment]
> @IvanSavenko If it is not hard, could you please make this and #4088 in priority?

No new modding features from me (other than fixes for bugs) for 1.5.X.

Might take a look for 1.6, but no promises for now.

**Comment by Laserlicht** [comment]
fixed by #4504
