### ISSUE TITLE
Question: is there playable coop-mode?

### ISSUE THREAD

**Issue by modern-nm** [vcmi/vcmi#4089]
Is there playable coop-mode? i mean few players in alliance, few players vs few players vs few bots (like in heroes 3)

**Comment by nullkiller** [comment]
Need a bit more description. 2 players in alliance or 2 connections operating same player color?

**Comment by modern-nm** [comment]
> Need a bit more description. 2 players in alliance or 2 connections operating same player color?

few players in alliance, few players vs few players (like in heroes 3)

**Comment by IvanSavenko** [comment]
Yes. VCMI supports H3 alliances logic. If it was possible in H3 it is also possible in vcmi
