### ISSUE TITLE
Unable to install installation files from .exe on iOS

### ISSUE THREAD

**Issue by GorgonUK** [vcmi/vcmi#4102]
**Describe the bug**
I had previously placed the installer in the app directory on my phone, when I click "install gog.com files", the app freezes and nothing happens. When I minimize the app and reopen it, it gives me a prompt "Select GOG installer...", but it doesn't show the exe. It's a great feature, but it doesn't work. It's just a massive bummer that it doesn't work. 

**To Reproduce**
1. Install VCMI 1.5.2 on iOS
2. Place GOG installer .exe in the application
3. Click "install gog.com files"

**Expected behavior**
It should display the .exe installer in the prompt for me to choose it.

**Actual behavior**
App freezes

**Screenshots**

![AD10DF6C-E0F8-46EE-8701-553A0B0F98F6_1_101_o](https://github.com/vcmi/vcmi/assets/59618079/1bcf75a0-7010-4f19-b481-2cd6f1d055e6)

**Version**
 - OS: iOS 17.5.1 
 - Version: 1.5.2

**Comment by Laserlicht** [comment]
I've already tested it on borrowed iPhone SE in the past. Worked without problem for me.

@kambala-decapitator You own a iPhone, right? Are you able to test it?

**Comment by misiokles** [comment]
There should be two files - one .exe and one .bin
And gog installer.exe is gog galaxy app similar to steam app.

**Comment by Laserlicht** [comment]
> There should be two files - one .exe and one .bin And gog installer.exe is gog galaxy app similar to steam app.

Yes, exactly. These files:
![grafik](https://github.com/vcmi/vcmi/assets/13953785/1eaaa62c-89d2-47c7-b77a-ab4bb48bae8f)

**Comment by GorgonUK** [comment]
Yes, one is a bin file and the other one is an executable. 

I'm using iPhone 15 Pro Max.

**Comment by kambala-decapitator** [comment]
I suspect it could be ios 17 related. @Laserlicht do you remember which ios version you were testing with?

Will check on iPads with 15 and 17

**Comment by Laserlicht** [comment]
@kambala-decapitator tested it with iOS 17 in the past

**Comment by kambala-decapitator** [comment]
- iOS 17: reproducible
- iOS 15: not reproducible

**Comment by Laserlicht** [comment]
Do you have a idea to fix it? :)

**Comment by kambala-decapitator** [comment]
Sort of
