### ISSUE TITLE
Crash on 1st turn

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4123]
[Player 2024.06.11 09;36 8XM12a.zip](https://github.com/user-attachments/files/15785862/Player.2024.06.11.09.36.8XM12a.zip)
map was created under HDmod
crash happens immediately after end turn

VCMI 1.5.3.a7edc6d369faccbdcbde49b904be2ac592853de2

**Comment by IvanSavenko** [comment]
Unable to reproduce. Caused by mods perhaps? Or different settings, e.g. AI?
Can you upload crash dump?

**Comment by Povelitelh3** [comment]
> Unable to reproduce. Caused by mods perhaps? Or different settings, e.g. AI? Can you upload crash dump?

of course! https://drive.google.com/file/d/14evhmriIPKEVaMIwEtwT3FAa4JrBVdqe/view?usp=drive_link

**Comment by IvanSavenko** [comment]
Ah, Windows-specific. Will fix.
