### ISSUE TITLE
Resource cannot be submitted in seer hut

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#4135]
**Describe the bug**
If submitting resources is a quest in seer hut, the resources will not be reduced, on the contrary, hero will gain the same quantity of required resources.

e.g: If a seer hut need 10000 gold to change 10 gems, hero will not lose 10000 gold, and he will gain 10000 gold and 10 gems as well.

**Did it work earlier?**
No. 

**Version**
 - OS: Windows/Android
 - Version: 1.5.2

**Comment by by003** [comment]
It is critical for game mechanics, please fix it as soon as possible in 1.5.3.
@IvanSavenko

**Comment by IvanSavenko** [comment]
And all other mission types that requires something to be taken from player are broken in the same way: bring artifact, bring army, bring resources... Thank you author for this 'refactoring'...
