### ISSUE TITLE
Right-clicking on town icon crashes VCMI

### ISSUE THREAD

**Issue by madaosoul** [vcmi/vcmi#4137]
**Describe the bug**
Right-clicking on the town icon in the bottom right corner of the HUD from the adventure map level crashes VCMI.

**To Reproduce**
1. Start any scenario.
2. Click on any of your towns.
3. Right click on the icon of your town in the window on bottom right corner.
4. Boom!

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/12452528/47c6ac65-f579-4399-b830-c7e8d0f6ceb4)

**Version**
Tested on VCMI 1.5 and 1.5.2.

**Comment by Laserlicht** [comment]
What OS? and where exactly do you click? (how exact?)

I'm not able to reproduce on Linux Flatpak.

**Comment by madaosoul** [comment]
Windows 10 on PC. And I'm clicking on this with a right mouse button. 
![Uploading image.png…]()

**Comment by madaosoul** [comment]
Windows 10 on PC. And I'm clicking on this with a right mouse button.
![image](https://github.com/vcmi/vcmi/assets/12452528/21b31d06-b615-4087-a2de-d7dbb2762eb9)

**Comment by madaosoul** [comment]
UMMMMM... on further examination it seems that it's no longer a problem on 1.5.2! I must have ran 1.5. when I thought I was testing on the newer version, sorry for the confusion.
