### ISSUE TITLE
crashdump on AI turn

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4139]
Hota map, beta 1.5.3.cd12b0e5143e94d19f059f0598a204f5b4c991eb, msvs
https://drive.google.com/file/d/1r0DNMrRLprKdKuq74vVLqNREmm3fr0E2/view?usp=drive_link

2  https://drive.google.com/file/d/1AlXkUfxu9tzg3CMt7T5psKf8QenJbqxl/view?usp=drive_link

maps [Pathways.zip](https://github.com/user-attachments/files/15847842/Pathways.zip)

**Comment by IvanSavenko** [comment]
Teleport channels?
Probably regression from my changes, will revert to be safe.

**Comment by nullkiller** [comment]
Yes they are. But still strange. It might be some specifics of this exact map.

**Comment by nullkiller** [comment]
In a nutshell when AI wants to discover all possible teleport exists it finds out that it does not stand on teleport object. I do not know how exactly this happens.

**Comment by Povelitelh3** [comment]
map was added

**Comment by nullkiller** [comment]
Looks like hero starts moving when channelProbbingList  is not empty initially. This should not happen. I think that clearing channelProbbingList at the beginning of moveHeroToTile should fix such crashes.
