### ISSUE TITLE
2 hex units - BattleAI do nothing

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4142]
Look video https://youtu.be/Dmo5F2DNwkM
Load save and try yourself [twohexStupid.zip](https://github.com/user-attachments/files/15847796/twohexStupid.zip)
![изображение](https://github.com/vcmi/vcmi/assets/36762538/c9efdb67-92d6-457c-9efd-3ce72a4775c4)

looks like related #1144

**Comment by nullkiller** [comment]
AI selected fire elements as target but can not understand how to attack them
