### ISSUE TITLE
game just close after attack on town 

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4164]
Ivor attack rampart and game close
No error, no crashdump
beta 1.5.3.af5572db1555daa5e5240e8e23ee6628e084a1e0, msvs
[Ivor.zip](https://github.com/user-attachments/files/15896262/Ivor.zip)

Reproduce when AUTOBATTLE ON!

[VCMI_Client_log.txt](https://github.com/user-attachments/files/15896324/VCMI_Client_log.txt)

**Comment by Vezok74** [comment]
Same issue here
beta-af5572d
[VCMI_Client_log3.txt](https://github.com/user-attachments/files/15896299/VCMI_Client_log3.txt)

**Comment by Povelitelh3** [comment]
Second case. Kristian attack castle. AUTOBATTLE OFF. Turn champions. After wait, defence or move - game close
[Kristian.zip](https://github.com/user-attachments/files/15897785/Kristian.zip)

**Comment by Povelitelh3** [comment]
works as intended for me
