### ISSUE TITLE
(Trivial) Campaign cutscene issues

### ISSUE THREAD

**Issue by Vezok74** [vcmi/vcmi#4175]
![AB-mission3](https://github.com/vcmi/vcmi/assets/171345782/7d789abb-99e0-475a-b25c-2114d689dbb5)

AB - Armageddon's Blade - Mission 3 intro cutscene: audio cracks

![DB-mission4](https://github.com/vcmi/vcmi/assets/171345782/245d0d5f-bb61-4bb1-a82c-d0b5d2196a7d)

AB - Dragon's Blood - Mission 4 ending cutscene: no subtitles

![FL-mission4](https://github.com/vcmi/vcmi/assets/171345782/ef9f417a-01cd-408b-b0b1-c16baff54229)

AB - Festival of Life - Mission 4 ending cutscene: no subtitles

![PF-mission3](https://github.com/vcmi/vcmi/assets/171345782/8061e35d-68c0-4314-90e6-927d8425bd5c)

AB - Playing with Fire - Mission 3 intro cutscene: no video

![HS-mission3](https://github.com/vcmi/vcmi/assets/171345782/f7ba125b-fa03-4a3b-a1ba-d17d748a2008)

SoD - Hack and Slash - Mission 3 intro cutscene: subtitles do not scroll down

P.S. some of the scenario orders are switched
most notable example being AB - Armageddon's Blade's first scenario "Catherine's Charge" and second scenario "Shadows of the Forest" : Starting a new campaign plays "Shadows of the Forest" first, then "Catherine's Charge"

**Version**
 - OS: Windows 11
 - Version: 1.5.3

**Comment by lishaoxia1985** [comment]
It seems that when the subtitle of campaign cut scenes is too short the word will disappear.
I have test it.

**Comment by Laserlicht** [comment]
fixed with #4780
