### ISSUE TITLE
Scholars attempt to teach secondary skill you already have

### ISSUE THREAD

**Issue by henningkoehlernz** [vcmi/vcmi#4178]
**Describe the bug**
When encountering a scholar that would grant a secondary skill that the hero already has, no bonus is granted.

**Expected behavior**
In HMM3, the secondary skill would be converted to a primary skill bonus in this situation.

**Screenshots**
![Screenshot from 2024-06-23 18-39-00](https://github.com/vcmi/vcmi/assets/20719746/a619fd8a-fd10-4077-a60b-eac416cd9925)

**Version**
 - OS: Ubuntu 22.04
 - Version: 1.53

**Comment by IvanSavenko** [comment]
> In HMM3, the secondary skill would be converted to a primary skill bonus in this situation.

Not exactly. In h3, scholar can levelup skill that you already have.

I think this is just a UI bug. Scholar would always show basic level, even if he actually upgraded your advanced skill to expert level
