### ISSUE TITLE
Can't play Campaign RoE

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#4182]
When you select one of the Campaign RoE and start the scenario the app will crash.
SoD and AB runs well.

**Comment by IvanSavenko** [comment]
Unable to reproduce. Please upload log.

**Comment by lishaoxia1985** [comment]
[]()[]()![Compressed.zip](https://github.com/user-attachments/files/15945181/Compressed.zip)

**Comment by lishaoxia1985** [comment]
I am not sure how the problem produce. I use the other mobile phone it runs very well.

**Comment by IvanSavenko** [comment]
Ah, this is 1.6, not 1.5. Will recheck 1.6 later. May be related to video playback.

**Comment by lishaoxia1985** [comment]
@IvanSavenko I have test it.
It occur only on Android if you use the app import the vcmi-data to "android/data".
The test is this:
1. On old mobile huawei, we can move the vcmi-data to "android/data" directly without the app inner tool, it runs well.
2. On Windows 10, if you use the app inner tool it runs well.
3. On Android 14 (my phone is IQOO 12 pro), if you use the app inner tool to import the vcmi-data to "android/data", the problem reproduces. I am not sure whether the inner tool will change some file in vcmi-data. Maybe need more and more test on different Android mobile.

**Comment by ghd987654321** [comment]
I am running 1.6 on GNU/Linux. When I try to start Homecoming, the game crashes and I get the following error:
Error: accessing unavailable frame 0:3 in CAnimation!
