### ISSUE TITLE
Andriod build failed

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#4189]
**Describe the bug**
build Android Failed in master 1.5.3 branch

**Game logs**
FAILED: launcher/vcmilauncher_autogen/timestamp launcher/vcmilauncher_autogen/mocs_compilation.cpp /home/demonking/vcmi/build/launcher/vcmilauncher_autogen/timestamp /home/demonking/vcmi/build/launcher/vcmilauncher_autogen/mocs_compilation.cpp 
cd /home/demonking/vcmi/build/launcher && /usr/local/bin/cmake -E cmake_autogen /home/demonking/vcmi/build/launcher/CMakeFiles/vcmilauncher_autogen.dir/AutogenInfo.json Release && /usr/local/bin/cmake -E touch /home/demonking/vcmi/build/launcher/vcmilauncher_autogen/timestamp && /usr/local/bin/cmake -E cmake_transform_depfile Ninja gccdepfile /home/demonking/vcmi /home/demonking/vcmi/launcher /home/demonking/vcmi/build /home/demonking/vcmi/build/launcher /home/demonking/vcmi/build/launcher/vcmilauncher_autogen/deps /home/demonking/vcmi/build/CMakeFiles/d/6e9f144da985a9fce5afe30413bf487e9eb31f912bc4cd936c9848be473e7cf3.d

AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/launcher/aboutProject/aboutproject_moc.h"
into
  "SRC:/build/launcher/vcmilauncher_autogen/GEYXX6VQVV/moc_aboutproject_moc.cpp"
Process failed with return value 2

Command
-------
/home/demonking/.conan/data/qt/5.15.14/_/_/package/83874cd1a9244f5eb8dafbd3f3225a4dfd186105/lib/cmake/Qt5Core/../../../bin/moc -DBOOST_ALL_DYN_LINK -DENABLE_INNOEXTRACT -DENABLE_LAUNCHER -DENABLE_QT_TRANSLATIONS -DENABLE_SINGLE_APP_BUILD -DHAVE_BZIP2 -DPCRE2_STATIC -DQT_ANDROIDEXTRAS_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_WIDGETS_LIB -DUSE_SYSTEM_MINIZIP -DVCMI_LIB_NAMESPACE=VCMI -DVCMI_VERSION_MAJOR=1 -DVCMI_VERSION_MINOR=5 -DVCMI_VERSION_PATCH=3 "-DVCMI_VERSION_STRING=\"1.5.3\"" -I/home/demonking/vcmi/build/launcher -I/home/demonking/vcmi/launcher -I/home/demonking/vcmi/lib -I/home/demonking/vcmi -I/home/demonking/vcmi/include -I/home/demonking/vcmi/launcher/lib/innoextract/src -I/home/demonking/.conan/data/qt/5.15.14/_/_/package/83874cd1a9244f5eb8dafbd3f3225a4dfd186105/include -I/home/demonking/.conan/data/qt/5.15.14/_/_/package/83874cd1a9244f5eb8dafbd3f3225a4dfd186105/include/QtAndroidExtras -I/home/demonking/.conan/data/qt/5.15.14/_/_/package/83874cd1a9244f5eb8dafbd3f3225a4dfd186105/include/QtCore -I/home/demonking/.conan/data/qt/5.15.14/_/_/package/83874cd1a9244f5eb8dafbd3f3225a4dfd186105/mkspecs/android-clang -I/home/demonking/.conan/data/pcre2/10.42/_/_/package/83a2e622b7d61939b8619d4f36027d54394430d8/include -I/home/demonking/.conan/data/double-conversion/3.3.0/_/_/package/ce2114a2d7957a097829dd5dd804c350f1a487b3/include -I/home/demonking/.conan/data/zstd/1.5.5/_/_/package/aa216dfaf2067f6357571341e6462b0ece690b7f/include -I/home/demonking/.conan/data/minizip/1.2.13/_/_/package/3ae32ae34ef293a2af02e3bb35d4aca73931a9ff/include -I/home/demonking/.conan/data/minizip/1.2.13/_/_/package/3ae32ae34ef293a2af02e3bb35d4aca73931a9ff/include/minizip -I/home/demonking/.conan/data/bzip2/1.0.8/_/_/package/9236f002182ea8b01b4b196dbf9fe9b1cba768e5/include -I/home/demonking/.conan/data/boost/1.84.0/_/_/package/c3a1f6a486a1572856ead1b3f05a4a424018fdc3/include -I/home/demonking/.conan/data/libiconv/1.17/_/_/package/ffcded5365dddf65ea9310e8adf8737a9e024d11/include -I/home/demonking/.conan/data/qt/5.15.14/_/_/package/83874cd1a9244f5eb8dafbd3f3225a4dfd186105/include/QtWidgets -I/home/demonking/.conan/data/qt/5.15.14/_/_/package/83874cd1a9244f5eb8dafbd3f3225a4dfd186105/include/QtGui -I/home/demonking/.conan/data/freetype/2.12.1/_/_/package/538ffc1cf7163e1d52edd44deb428654dcbcd020/include -I/home/demonking/.conan/data/freetype/2.12.1/_/_/package/538ffc1cf7163e1d52edd44deb428654dcbcd020/include/freetype2 -I/home/demonking/.conan/data/libpng/1.6.39/_/_/package/e6db7b977b73b17d2dea48782ed9156a2f4a5f83/include -I/home/demonking/.conan/data/brotli/1.0.9/_/_/package/a14dda6584102a615ab8043bed7594e2cb807109/include -I/home/demonking/.conan/data/brotli/1.0.9/_/_/package/a14dda6584102a615ab8043bed7594e2cb807109/include/brotli -I/home/demonking/.conan/data/qt/5.15.14/_/_/package/83874cd1a9244f5eb8dafbd3f3225a4dfd186105/include/QtNetwork -I/home/demonking/.conan/data/openssl/1.1.1s/_/_/package/8cbfc05d3e76d0a8b10531035a234407976a6e13/include -I/home/demonking/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1 -I/home/demonking/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/14.0.7/include -I/home/demonking/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/local/include -I/home/demonking/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android -I/home/demonking/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include --include /home/demonking/vcmi/build/launcher/vcmilauncher_autogen/moc_predefs.h --output-dep-file -o /home/demonking/vcmi/build/launcher/vcmilauncher_autogen/GEYXX6VQVV/moc_aboutproject_moc.cpp /home/demonking/vcmi/launcher/aboutProject/aboutproject_moc.h

Output
------
/home/demonking/.conan/data/qt/5.15.14/_/_/package/83874cd1a9244f5eb8dafbd3f3225: not foundEROh__TEXT�Qt5Core/../../../bin/moc: 1: ����
/home/demonking/.conan/data/qt/5.15.14/_/_/package/83874cd1a9244f5eb8dafbd3f3225a4dfd186105/lib/cmake/Qt5Core/../../../bin/moc: 2: Syntax error: "(" unexpected

**Comment by kambala-decapitator** [comment]
please read the point about Android attentively: https://github.com/vcmi/vcmi/blob/develop/docs/developers/Conan.md#download-dependencies

**Comment by kdmcser** [comment]
I delete ~/.conan/data/qt/5.15.x/_/_/package and build it manually in ubuntu. But when I package the apk, it seems some vars is not resolved in android/vcmi-app/build.gradle:
androidCompileSdkVersion
qtMinSdkVersion 
qtTargetSdkVersion 
qt5AndroidDir 
All this above are null, so the package failed.
How to set it?

**Comment by kambala-decapitator** [comment]
Which command do you use to package apk? You don't need to call gradlew manually.

**Comment by kdmcser** [comment]
I see, the workflow file changed.
I should type this cmd:
> cd build/android-build
> ./gradlew bundleRelease --info

**Comment by kdmcser** [comment]
solved.

**Comment by kambala-decapitator** [comment]
> I see, the workflow file changed

There's also documentation, you know...

**Comment by killer419** [comment]
I May I ask why the file "androiddeployqt.json" was not generated in the build directory
