### ISSUE TITLE
Game crash shortly after end of simultaneous turns

### ISSUE THREAD

**Issue by wnukos** [vcmi/vcmi#4191]
[VCMI_Client_log.zip](https://github.com/user-attachments/files/15974544/VCMI_Client_log.zip)
**Describe the bug**
The game crashed shortly after simultaneous turns have ended and my opponent was doing his turn. It was probably caused by me (player waiting for his turn) clicking something in the game.

**To Reproduce**
1. Start a multiplayer game via online lobby, for example on Jebus Cross template. Set simultaneous turns, for example 7 turns.
2. Players play they simultaneous turns, no contact happens.
3. Planned simultaneous turns end, the game informs about it with a message. Red player starts his turn and Blue player waits for his turn.
4. Blue player clicks randomly on one of his heroes and then somewhere on the adventure map. As a result the heroes movement points refill and the movement paths are no longer displayed in red color but in green color, as if it was Blue player's turn. However the heroes can't move and no other typical action can be performed. Shortly after this the Red player informs that he can't move his troops in the battle and the Blue player gets a crash message.

**Version**
VCMI 1.5.3
Mods: PvP Balance and its dependent mods (Tides of War, Horn of the Abyss, Pavilion Town, Heavenly Forge 2000, Ruins Town)

**Comment by wnukos** [comment]
[Uploading VCMI_Client_log.zip…]()

**Comment by vetka925** [comment]
Have the same problem. An online multiplayer game crashes when a waiting player taps the screen.
