### ISSUE TITLE
Mystical garden always gives gold

### ISSUE THREAD

**Issue by SoundSSGood** [vcmi/vcmi#4193]
**Expected behavior**
Mystical garden always gives gold

**Actual behavior**
Sometimes gold sometimes gems

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/87084363/ed78715b-d61d-40d1-921a-1573dbcd92d6)

**Version**
 - Version: develop

**Comment by IvanSavenko** [comment]
Unable to reproduce (at least on 1.5 / beta).
However choice (gems / gold) is randomized on a new week, not on a visit. Reloading save & revisiting same garden will always give same reward

**Comment by SoundSSGood** [comment]
At the moment in develop branch, all gardens on the map give gold every week.

**Comment by SoundSSGood** [comment]
no longer reproducible
