### ISSUE TITLE
Constructing a new dwelling in town via timed event on first day of the week leads to corrupted town state

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#4209]
**Describe the bug**

[The Twilight of Silenceking(Hardcore).zip](https://github.com/user-attachments/files/16041510/The.Twilight.of.Silenceking.Hardcore.zip)

In this map，if you using red to beat blue player and occupied his starting castle town. Someting was wrong.

![1](https://github.com/vcmi/vcmi/assets/8289682/e618d423-10ea-4caf-a125-bfee7d4e36b2)

in dwellings, only Guardhouse are built in map setting, but game seems to have built all dwellings.

![2](https://github.com/vcmi/vcmi/assets/8289682/3d465140-4238-45da-935b-073dfea1efd8)

you cant recruit upgrade creatures, and archer.  The Archers' Tower shows a ERROR text, click it will lead a crash.

![3](https://github.com/vcmi/vcmi/assets/8289682/c8587714-f37a-4452-95a4-e1ccbd66bd03)

Its OK when you start with blue player.

**Expected behavior**
This town only built Guardhouse  dwelling.

**Actual behavior**
see the screenshot above.

**Did it work earlier?**
no idea

**Version**
 - OS: Windows
 - Version: 1.5.3

**Comment by IvanSavenko** [comment]
Not a bug.
This town has timed event that gives these buildings on day 1

**Comment by dydzio0614** [comment]
i think there is some sort of bug - check last screenshot

**Comment by IvanSavenko** [comment]
Ah, confirmed.

Constructing a new dwelling in town via timed event on first day of the week leads to corrupted town state.

**Comment by IvanSavenko** [comment]
Pain to fix for 1.5.4, will look into for 1.6

**Comment by IvanSavenko** [comment]
Looks to be a bug for a different reason actually.
In vcmi, all events trigger on new turn - before player-receiver acts.
In h3, all events trigger on player turn - when player-receiver starts his turn.

So in this case, timed events in blue town for day 1 should only trigger when blue starts his turn - after red ends his turn
(and events in neutral towns don't trigger at all)
