### ISSUE TITLE
Screen focus out of place

### ISSUE THREAD

**Issue by Vezok74** [vcmi/vcmi#4230]
**Describe the bug**
The screen is placed on the edge of the map on new game or load game.

**To Reproduce**
1. Start a new game or load a save.
2. See error

**Expected behavior**
Hero that is on top of the list should be focused.

**Actual behavior**
When you start a new map or load a save, the screen shows the edge of the map.

**Did it work earlier?**
The error did not exist in 1.5.3

**Screenshots**
![Screenshot_20240706-210304](https://github.com/vcmi/vcmi/assets/171345782/43e63490-d6ac-4a4d-b728-6d70932c9696)
new game

![Screenshot_20240706-210428](https://github.com/vcmi/vcmi/assets/171345782/58f45744-7ea3-42f2-b76d-15652058757e)
load save

**Version**
 - OS: Android
 - Version: beta-5f33941

**Comment by Povelitelh3** [comment]
not fixed yet
