### ISSUE TITLE
Lich area attack does not work

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#4233]
**Describe the bug**
Lich does not damage creatures adjacent to targeted stack, only the stack itself.

**Expected behavior**
Lich's Death Cloud would damage all living creatures within range

**Actual behavior**
Only one stack of Archers was damaged

**Did it work earlier?**
Certainly it did

**Screenshots**
<img width="1440" alt="Lich Area 20240706" src="https://github.com/vcmi/vcmi/assets/2566990/9b3b3f24-7230-42bd-b72f-a3879d0cfc00">

**Version**
1.5.3

**Additional context**
Reported by Valerin Bizonov on PvP Discord

**Comment by IvanSavenko** [comment]
Works with no mods. Bug in our hota mod.

https://github.com/vcmi-mods/horn-of-the-abyss/blob/vcmi-1.5/hota/Mods/changedShootingVisuals/content/config/hotaDeathCloud.json

For some reason it has different range. Should be same as in our files: `"range" : "0-1",`

**Comment by DjWarmonger** [comment]
Let me take this challenge ;P

**Comment by lishaoxia1985** [comment]
@IvanSavenko This pr doesn't have any effect in 1.6.
