### ISSUE TITLE
Crash in campaign when starting new scenario 

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#4270]
**Describe the bug**
The bug can be reproduce as below：

**To Reproduce**
1. start SOD campaign Rise of the Necromancer
2. hire a hero in tavern
3. combine Armor of the Damned and equip it in the hero which hired from tavern
4. go to next scenario (can type vcmiwin cheat code)
5. game crashed when starting next scenario after choice bounse.

**Expected behavior**
game not crash

**Actual behavior**
game crash

**Did it work earlier?**
1.5.3 also contains this problem

**Screenshots**
the stack is:
![1](https://github.com/user-attachments/assets/421288aa-b634-4718-9607-2d1b2cf99174)

and the dmp file is:
[VCMI_client.exe_crashinfo.dmp](https://github.com/user-attachments/files/16236348/VCMI_client.exe_crashinfo.dmp)

**Version**
 - OS: Windows, Android
 - Version: 1.5.4 
 
**Additional context**
no

**Comment by IvanSavenko** [comment]
Nice find, will take a look.
Saw this crash on Google Play stats, but couldn't figure out its cause just from call stack.
