### ISSUE TITLE
`Failed to load translation` messages for some translations

### ISSUE THREAD

**Issue by Alexander-Wilms** [vcmi/vcmi#4277]
**Describe the bug**
When one select some translations in the launcher, the error message `Failed to install translator` is printed to the terminal.

**Game logs**
[VCMI_Launcher_log.txt](https://github.com/user-attachments/files/16240929/VCMI_Launcher_log.txt)

**To Reproduce**
1. Start `vcmilauncher`
2. Select all the languages under Settings > General > VCMI Language one after the other

**Expected behavior**
No error messages

**Actual behavior**
I've changed loadTranslation() to print the file name:

```c++
void MainWindow::loadTranslation()
{
#ifdef ENABLE_QT_TRANSLATIONS
	const std::string translationFile = settings["general"]["language"].String() + ".qm";
	logGlobal->info("Loading translation '%s'", translationFile);

	QString translatorFilename = QString{":/translation/%1"}.arg(translationFile.c_str());
	if (!translator.load(translatorFilename))
	{
		logGlobal->error("Failed to load translation %s", translatorFilename.toStdString());
		return;
	}

	if (!qApp->installTranslator(&translator))
		logGlobal->error("Failed to install translator %s", translatorFilename.toStdString());
#endif
}
```

```
      ~/Technik/Development/vcmi/build/bin  ./vcmilauncher                                                                                            ✔ 
Loading translation 'english.qm'
Failed to install translator :/translation/english.qm
File <unknown> is not a valid JSON file!
At line 33, position 1 warning: Comma expected!

Loading translation 'czech.qm'
Loading translation 'chinese.qm'
Loading translation 'english.qm'
Failed to install translator :/translation/english.qm
Loading translation 'finnish.qm'
Failed to load translation :/translation/finnish.qm
Loading translation 'french.qm'
Loading translation 'german.qm'
Loading translation 'hungarian.qm'
Failed to load translation :/translation/hungarian.qm
Loading translation 'italian.qm'
Failed to load translation :/translation/italian.qm
Loading translation 'korean.qm'
Failed to load translation :/translation/korean.qm
Loading translation 'polish.qm'
Loading translation 'portuguese.qm'
Loading translation 'russian.qm'
Loading translation 'spanish.qm'
Loading translation 'swedish.qm'
Failed to load translation :/translation/swedish.qm
Loading translation 'turkish.qm'
Failed to load translation :/translation/turkish.qm
Loading translation 'ukrainian.qm'
Loading translation 'vietnamese.qm'
```

**Did it work earlier?**
Unknown

**Screenshots**
na

**Version**
 - OS: openSUSE Tumbleweed 20240712
 - Version: develop (6f5710e809fae28720aa6d2b04f9fa0173224cda)

**Additional context**
na

**Comment by Alexander-Wilms** [comment]
The languages that when selected cause the error message are the ones which don't have a corresponding .ts file in [launcher/translation](https://github.com/vcmi/vcmi/tree/develop/launcher/translation):

It contains these files:
```
chinese.ts
czech.ts
english.ts
french.ts
german.ts
polish.ts
portuguese.ts
russian.ts
spanish.ts
ukrainian.ts
vietnamese.ts
```

Only English also shows the error message even though the file exists.

**Comment by kambala-decapitator** [comment]
it's completely safe to ignore. English file is empty most probably.

**Comment by Alexander-Wilms** [comment]
Yes, it's empty in the sense that all <translation/> tags are empty.

Still, the launcher shouldn't even show languages in the combobox that are not available and the launcher shouldn't try to load an English translation.

**Comment by IvanSavenko** [comment]
> Still, the launcher shouldn't even show languages in the combobox that are not available and the launcher shouldn't try to load an English translation.

But these languages have at the very least translation for game itself. And possibly - translation for some mods.

**Comment by Alexander-Wilms** [comment]
Maybe just check if translation file exists before calling

`
if (!translator.load(QString{":/translation/%1"}.arg(translationFile.c_str())))
`

?

Just so there are no error messages, if possible.

**Comment by IvanSavenko** [comment]
Or remove error message completely. Or downgrade to 'debug' / 'trace' level
