### ISSUE TITLE
Crash in AI‘s turn 

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#4281]
**Describe the bug**
In AI's turn, the develop branch is also crashed occasionally (about one per mouth) without crash window. The dmp file is generated sucessfully. I am not sure it the same bug as #4202 . 

The compiler which I use is VS, not same as #4202 (it is conan)
**Game logs**
[VCMI_Client_log.zip](https://github.com/user-attachments/files/16251909/VCMI_Client_log.zip)
rar format, too large

**To Reproduce**
the same as #4202, which I copied as below:

my mod file: https://drive.google.com/drive/folders/1cKUF7LWv7sAWRFhGX6l6VItzzGQ5L__X?usp=drive_link
only need to download vcmi-data.zip

Using this mod data, setting language to Chinese, set NKAI, start a random G two level map with 8 player. type vcmiglaurung to ensure not be defeated. then end day again and again. Game will exit without a crash window within a month. no crash dmp file either.

it also occured in English language, but not sure whether it can be produced within a mouth.

**Expected behavior**
game not crash

**Actual behavior**
game crash

**Did it work earlier?**
in develop branch VS build,  not sure if it is in conan build.

**Screenshots**
The stack is :
![1](https://github.com/user-attachments/assets/5054b750-0ce5-4dfa-87b4-082ecc5e18fc)

the dmp file is: 
[VCMI_client.exe_crashinfo.zip](https://github.com/user-attachments/files/16251885/VCMI_client.exe_crashinfo.zip)

and cwd is: e:\vcmi

**Version**
 - OS: Windows,
 - Version: 1.6.0.b3d7ed85835056b9c33cb7ca44b67ac32c3c8dac

**Additional context**
no

**Comment by SoundSSGood** [comment]
I confirm the crash.
[3.zip](https://github.com/user-attachments/files/16319850/3.zip)
Load the savefile.
Click end of turn.

**Comment by nullkiller** [comment]
If crash dump has own visual studio build, it has own .pdb files which we need to open crash dump
3.zip is not reproducible on my build. Does it crash with latest develop alternative build?

**Comment by SoundSSGood** [comment]
Rechecked. This crashes on Linux (GCC). But on Windows works fine (Visual studio). The last commit in the development branch has been checked.

**Comment by kdmcser** [comment]
I compiled with Release target and I can‘t find any pdb file. And How can I download  the latest develop alternative build? I think I can reproduce this crash with it.

**Comment by kambala-decapitator** [comment]
You should build RelWithDebInfo, not Release

**Comment by kdmcser** [comment]
I build using RelWithDebInfo and can see the stack
![1](https://github.com/user-attachments/assets/f357585f-2729-4916-854c-34b5fa3c0b19)
the dmp file:
[VCMI_client.exe_crashinfo.zip](https://github.com/user-attachments/files/16334649/VCMI_client.exe_crashinfo.zip)
my compiled binary with pdb files:
https://drive.google.com/file/d/1l3Kw1B92jrm38xO8B10qOsXVN_LxT1oo/view?usp=drive_link

**Comment by SoundSSGood** [comment]
I modified the endBattleConfirm method in https://github.com/vcmi/vcmi/pull/4186. Will look into...

**Comment by SoundSSGood** [comment]
In the development branch, the crash is no longer reproducible for me. @kdmcser  Could you check for yourself?

**Comment by kdmcser** [comment]
@SoundSSGood  still crash, I pack all the files to :
https://drive.google.com/drive/folders/1UpdLwNkyoV9-vzdb4SQWcymPRiA8ikCX?usp=sharing

vcmi.rar: binary, mods and crash dmp
vcmi_config.rar Documents/My games/VCMI
RelWithDebInfo.rar pdb files and compiled target files
