### ISSUE TITLE
More noob-friendly campaign format

### ISSUE THREAD

**Issue by madaosoul** [vcmi/vcmi#4287]
**Describe your proposal**
I wanted to try out making a custom VCMI campaign, just to see if it works - a custom prologue text, the map of regions, bonuses etc. I followed information on the [page documenting the format](https://github.com/vcmi/vcmi/blob/develop/docs/modders/Campaign_Format.md) and got stuck at packing everything. I tried using 7zip, to no avail. VCMI doesn't see a packed .tar. and then .gz file as viable campaign. I don't think it should take that many hoops to make it work, so I'd like to request that VCMI recognizes "normal" archive types. Or no archive at all. Anything a dummie like me can use to make a campaign right off the bat.

**Comment by Laserlicht** [comment]
solved with #4428
