### ISSUE TITLE
Some errors in config

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#4301]
1. Dungeon hero "jeddite" should not be female
2. Special hero "mutare" and "mutareDrake" should not be warlock
3. Creature "hydra" and "chaosHydra" should have the ability “DRAGON_NATURE”, to ensure they can transfer to bone dragons in the skeleton transformer.

**Comment by IvanSavenko** [comment]
> Creature "hydra" and "chaosHydra" should have the ability “DRAGON_NATURE”, 

DRAGON_NATURE is also used for Mutare specialty. Which does not affects Hydras

**Comment by IvanSavenko** [comment]
1 & 2 - fixed.
3 - works as intended, DRAGON_NATURE is for Mutare specialty, not for transformer which still uses hardcoded logic
