### ISSUE TITLE
Some bugs found in pvp tournament so far

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#4326]
Some bugs found in pvp tournament so far:

- [x] spellbook icon during battle should be inactive if spellbook not purchased (cannot cast anyway, the only way to access it in h3 in this case to get "you cannot cast spell" popup is to click hero)
- [x] thieves guild from adventure map does not work during opponent turn (G shortcut)
- [x] damage prediction does not update when swapping action from shoot to melee (half damage related)
- [ ] #4352
- [x] pandora box with spells does not have "nothing found" message if it contained spells with level too high for hero to learn
- [x] on receiving new turn notification, all windows other than adventure map must be closed
- [ ] System no longer reminds of timer when DENABLE_GOLDMASTER is enabled for vcmi release build

Since these bugs got found during pvp games, they are likely to improve pvp gameplay when fixed

**Comment by ToRRent1812** [comment]
If I can add something to it, without making new issue
System no longer reminds of timer when DENABLE_GOLDMASTER is enabled for vcmi release build

**Comment by IvanSavenko** [comment]
> System no longer reminds of timer

Sorry, what reminder are you talking about? We only have sound which is not affected by that option.

**Comment by dydzio0614** [comment]
sound reminder did not work for a player :P
