### ISSUE TITLE
Statistics after game end

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#4331]
**Describe your proposal**
Show a statistic window after the game (optional).
Maybe some graphs. E.g. Resources over time. Maybe draw also events as icons in graph (e.g. town capture or battles;see example).
And a table with some results.

Charting lib as idea: https://github.com/alandefreitas/matplotplusplus

**Additional context**
Example from AoE4
![grafik](https://github.com/user-attachments/assets/75beb375-54fa-42f3-a9d2-f1444c70eb3a)
![grafik](https://github.com/user-attachments/assets/8c24a464-a275-4587-97fb-116e59d17b01)

**Comment by Alexander-Wilms** [comment]
Would the chart be saved to a file and then be loaded as a texture?

https://alandefreitas.github.io/matplotplusplus/exporting/saving-programatically/

**Comment by Laserlicht** [comment]
> Would the chart be saved to a file and then be loaded as a texture?

Yes, I think this could be possible.
But the real pain here is to get external libraries to work in c++. Tried it but got some compilation errors...
And sadly there are not very much alternatives. Data analytics in c++ seems to be exotic.
