### ISSUE TITLE
First map of three campaigns are skipped

### ISSUE THREAD

**Issue by Shotweb** [vcmi/vcmi#4333]
**Describe the bug**
The first map/scenario of the following campaigns are not playable for me. Instead the game starts at map 2 of the campaign. It happens for:

- RoE, Dungeons and Devils: Goes directly to map 2, Groundbreaking, instead of map 1, A Devilish Plan
- RoE, Spoils of War: Goes directly to Gold Rush
- AE, Armageddon's Blade: Goes directly to Shadows of the Forest

Other campaigns work fine.

**Game logs**
Logs attached

**To Reproduce**
1. Start a new game, with one of the three campaigns mentioned above
2. Read the scenario screen

**Expected behavior**
Should start with scenario 1

**Actual behavior**
Starts with scenario 2, and I get my ass kicked because I start out with only one level 1 hero instead of having brought over heroes from scenario 

**Did it work earlier?**
Not tested

**Screenshots**
Not needed

**Version**
I just finished the Long Live the Queen on VCMI 1.3.x (I think), and then now updated to 1.5.5. I don't know if this has anything to do with it.
I'm on an Android 10 tablet.

**Additional context**
I can try a complete reinstall later (I don't have the game data available right now)

I have tried disabling all non-VCMI mods

[VCMI_Launcher_log.txt](https://github.com/user-attachments/files/16394902/VCMI_Launcher_log.txt)
[VCMI_Client_log.txt](https://github.com/user-attachments/files/16394903/VCMI_Client_log.txt)

**Comment by IvanSavenko** [comment]
In these campaigns player can pick which scenario to play first - by clicking on corresponding map region on the left.

VCMI probably selects different scenario by default, but it does not skips them.

**Comment by Shotweb** [comment]
Oh well nevermind then.
Then I just don't understand why Groundbreaking is so difficult.
