### ISSUE TITLE
Next batch of bugs encountered in pvp tournament

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#4344]
- [x] Simultaneous turns sliders easily get broken (try to press keyboard arrow button or move fast first slider while both at 0)
- [x] Inability to quit game, restart map etc. while 2nd player is making turn, also possible to be stuck with locked gui state forever if 2nd player disconnects while making turn
- [ ] #4353
- [ ] #4354

**Comment by IvanSavenko** [comment]
> Joining player does not have properly updated room state 

Ugh, looks more complex than it sounds. Probably not for 1.5.x

> Looks like there is no info for host about guest player getting disconnected

Strange because I do get one. Might be issue only with playing over network. Or with playing over lobby. Needs investigation
