### ISSUE TITLE
RMG settings for road types are not saved

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4367]
**Describe the bug**
RMG settings for road types are not saved from one game to another. 

**To Reproduce**
1. Start Jebus Cross RMG map with only fastest roads enabled
2. Start another Jebus Cross... all 3 road types are enabled. (everything else is saved)

**Expected behavior**
Roads settings is also persisted between games.

**Version**
 - OS: Windows
 - Version: 1.5.5

**Comment by IvanSavenko** [comment]
Fixed in 1.6
