### ISSUE TITLE
In battle creature info panel cannot be persisted for enemy creatures

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4369]
**Describe the bug**
In battle, creature info panel cannot be persisted for enemy creatures. You can view some information on right click, but the window cannot be interacted with.

If 1 creature has more than 4 abilities, or one ability with a long description, that needs scrolling there is no way to read the whole description.

**Comment by kambala-decapitator** [comment]
related: #1043

**Comment by krs0** [comment]
Then this can be deleted. No need for a duplicate.
