### ISSUE TITLE
Disable spell book icon in battle, when you have scrolls, but no spell book is available.

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4370]
**Describe your proposal**
Disable spell book icon in battle when you have scrolls, but no spell book is available.

Right now if you have scrolls, the cast spell button is enabled and player is able to select those spells to cast, but will not work and a weird message is displayed (about reciting incantations...)

**Comment by IvanSavenko** [comment]
@Laserlicht Wasn't this one fixed by you in 1.6 branch recently? Or it was for a different case?

**Comment by Laserlicht** [comment]
Yes. Spellbook button is disabled, when the hero has no spellbook.

**Comment by IvanSavenko** [comment]
Fixed in 1.6 then
