### ISSUE TITLE
There are no shortcuts for rearranging heroes 

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4372]
In HD mod you can rearrange heroes in right panne to your whish, so that it would be easier for the player to spot what hero is what.

One useful example: place main hero first.

Alt clicking would be a solution. Or Drag and drop...

This could be implemented for towns as well.

**Comment by Laserlicht** [comment]
Is possible with middle mouse button or gesture (touch screen).

But yes. Shortcuts are missing currently.

But currently not saved (see here https://github.com/vcmi/vcmi/issues/797, https://github.com/vcmi/vcmi/issues/1383 and https://github.com/vcmi/vcmi/pull/1663)

**Comment by krs0** [comment]
I did not knew it was created. Middle mouse is just fine, ty!
