### ISSUE TITLE
Wrong ATB bar order of creatures

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4374]
**Describe the bug**
Sometimes after a wait, followed by a defend the ATB bar order gets messed up until next creatures action.

In the picture below is the turn of Cyber Dead but Gargoyles are listed as current creature in ATB.

![image](https://github.com/user-attachments/assets/b0746eb6-3d37-4895-988a-9cb514ccef3c)

**Version**
 - OS: [e.g. Windows,]
 - Version: [VCMI 1.5.5]

**Comment by IvanSavenko** [comment]
Fixed in https://github.com/vcmi/vcmi/pull/4254
