### ISSUE TITLE
Carryover doesn't work in VCMI Campaign format

### ISSUE THREAD

**Issue by madaosoul** [vcmi/vcmi#4376]
**Describe the bug**
Finally got to test possibilities of vcmi campaign and discovered that heroes and creatures don't carry over to next scenario. The first one should be possible with the use of hero placeholders, but VCMI doesn't seem to register them. And the campaign format page on github states that line in the 00.json:
"keepCreatures": ["angel"],
should make the carryover of units possible, but it just doesn't work.

I attach a set of maps I made to test a bunch of stuff (packed into a campaign with all of the components separately). Orrin in Test 2 is a placeholder and should receive experience from Test 1 or Test 3.

**To Reproduce**
1. Play the custom campaign I attached.
2. Start from Test 1 or Test 3 and level up Orrin a bit (vcmiglorfindel).
3. Play Test 2 and notice that Orrin is missing.
4. Notice that you don't have more than 5 Angels in each scenario despite picking them as a bonus every time.

**Expected behavior**
Orrin's placeholder should receive all things from one of previous scenarios and be a playable hero. You should start your 2nd and 3rd scenario with 10 and 15 angels if you pick them each time.

**Actual behavior**
Orrin doesn't appear in Test 2 and you start each scenario with the same amount of 5 angels.

**Version**
 - OS: Windows 11
 - Version: VCMI 1.5.5, 1.6.0
[custom campaign test.zip](https://github.com/user-attachments/files/16480773/custom.campaign.test.zip)

**Comment by by003** [comment]
I have tested campaign and sent it to Godric. Seems he has already found the conditions of crossover hero.
