### ISSUE TITLE
Scroll bug when using scroll wheel to set sim turns options

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4394]
**Describe the bug**
When using scroll wheel to set sim turns options, the sliders go crazy and game needs to be remade.

**To Reproduce**
1. Go to new multiplayer game in lobby
2. Scroll when changing sim turn options
3. This is forever, new game needs to be created

**Screenshots**

https://github.com/user-attachments/assets/ecc282cf-7af0-4877-93c2-fd1bca78566b

**Version**
 - OS: [e.g. Windows]
 - Version: [VCMI 1.5.5]

**Comment by IvanSavenko** [comment]
Fixed in 1.5.6
