### ISSUE TITLE
Having a modal popup while opponent ends turn will make game not responsive

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4395]
**Describe the bug**
I Right click on an artifact to see details. Opponent ends his turn, my turn comes but I cannot click anything.
Enter does not function, ESC, ALT Tab..... The only way to recover from this is to right click somewhere and everything goes back to normal.

**To Reproduce**
1. In a multiplayer game bring up a popup window for an artifact on adventure map.
2. Oponent ends his turn
3. Game seems frozen... (Only a right click makes it responsive again)

(I was RED player if it helps)

**Version**
 - OS: [e.g. Windows, ]
 - Version: [VCMI 1.5.5]

**Comment by IvanSavenko** [comment]
Fixed in 1.5.6
