### ISSUE TITLE
Stack Artifacts' descriptions don't appear in a creature window

### ISSUE THREAD

**Issue by madaosoul** [vcmi/vcmi#4403]
**Describe the bug**
Stack artifacts work and I'd like to play around with them, but not being able to check my creatures' equipped items is a bit inconvenient, especially in battle.

**Screenshots**
![image](https://github.com/user-attachments/assets/acf12f34-ea76-49b8-b6fc-25e87f7eeed1)

**Version**
 - OS: Windows 10
 - Version: VCMI 1.5.4

**Comment by mikeiit** [comment]
Just observed this in macOS as well. Maybe I can take a look.

**Comment by mikeiit** [comment]
When the artifact is in the hero window, we set the description [here](https://github.com/vcmi/vcmi/blob/a819c3fc29814828990c304d3f0ce377c3df922b/client/widgets/CArtPlace.cpp#L75)

Still need to find how that is missed in the creature window...
