### ISSUE TITLE
Maps saved with hota mapeditor are not loaded in vcmi

### ISSUE THREAD

**Issue by MichalZr6** [vcmi/vcmi#4409]
**Describe the bug**
Maps edited / open-saved with hota mapeditor are not loaded in vcmi.

**To Reproduce**
1. Run h3hota_maped.exe
2. Load any map
3. Save as new map to the vcmi map directory
4. Run VCMI, go to Scenario Selecting interface.
5. The map is unavailable and error in terminal is generated: 
![obraz](https://github.com/user-attachments/assets/251e5e27-d0ed-44ce-96a7-39eeb8a2d695)

**Expected behavior**
Should work ?

**Actual behavior**
Those maps saved via hota mapeditor won't load to vcmi map pool.

**Did it work earlier?**
I don't know.

**Version**
 - OS: Windows 10
 - Version: VCMI 1.6

**Additional context**
Hota map version is done up to 3 
https://github.com/vcmi/vcmi/blob/a4dd510735f035e1930b8f9022e8c99cda3a05c7/lib/mapping/MapFeaturesH3M.cpp#L122
while those 'editted' get value equal to 5:
![obraz](https://github.com/user-attachments/assets/1764b2c5-a69a-43fa-9712-080eb499a938)

**Comment by dydzio0614** [comment]
VCMI only supports hota version released before factory, so not really a bug

**Comment by kambala-decapitator** [comment]
@dydzio0614 please don't close such issues as "completed", rather select "not planned"
