### ISSUE TITLE
dialog "not enough money" missing when attempting to surrender

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#4416]
Currently when you have not enough money to surrender and accept the dialog, simply nothing happens:

![Screenshot 2024-08-08 at 00 02 31](https://github.com/user-attachments/assets/a3be0b8d-9d39-4368-a8eb-02169be6b4ad)

I don't remember how it was in oh3, but for example when a unit wants to join you for a fee and you don't have enough money, "not enough money" dialog appears.

1.5.6 release

**Comment by mikeiit** [comment]
I reproduced this today. So shall we add a new dialog right after the one in the screenshot w/ the message "You can't afford the payment"?

**Comment by kambala-decapitator** [comment]
please check behavior in the original game

**Comment by mikeiit** [comment]
Do you know if the original game can run in macOS?

**Comment by kambala-decapitator** [comment]
> Do you know if the original game can run in macOS?

Only via wine / crossover / whiskey / wineskin

**Comment by mikeiit** [comment]
Actually saw this dialog in the latest dev build today. Has this been fixed? Or does this only happen in a very specific scenario?
![Screenshot 2024-08-28 at 9 10 53 PM](https://github.com/user-attachments/assets/14a0b122-88c5-41b2-a1fa-dee8bfe18877)

**Comment by kambala-decapitator** [comment]
cool, so looks like it has been fixed by #4500
