### ISSUE TITLE
double dialog "you have 7 days to capture town"

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#4418]
When you lose your last town, the following dialog appears in VCMI and oh3:

![Screenshot 2024-08-07 at 23 37 54](https://github.com/user-attachments/assets/cdc41fab-8467-4473-bb45-ce04a0370aa7)

But in VCMI right after that appears another dialog with almost identical message:

![Screenshot 2024-08-07 at 23 38 10](https://github.com/user-attachments/assets/3d197687-e521-4d2f-a4f8-d435f117b79c)

1.5.6 release

**Comment by mikeiit** [comment]
I saw this one today, not sure about the cause yet. But what should happen?

**Comment by kambala-decapitator** [comment]
normally only the first dialog should appear

**Comment by mikeiit** [comment]
The code responsible for the first dialog is in CPlayerInterface::acceptTurn(...) method. The other one is in CGameHandler::setOwner(....). Not sure what the correct fix is though. Should they be combined somewhere?

**Comment by mikeiit** [comment]
Just for tracking purpose @mikeiit

**Comment by mikeiit** [comment]
This can be closed right? @kambala-decapitator

**Comment by kambala-decapitator** [comment]
> This can be closed right? @kambala-decapitator 

Yep.

FYI to close issues when pr is merged, either write somewhere in pr description "fixes #4418" (there're more special words, check github docs) or link issues in the right panel of a PR manually.

**Comment by mikeiit** [comment]
Ahh thanks! Completely forgot about it after being away for a year lol
