### ISSUE TITLE
Ending a turn crashes VCMI frequently

### ISSUE THREAD

**Issue by dasassaa** [vcmi/vcmi#4430]
**Describe the bug**
VCMI tends to crash a lot lately, usually after ending a turn when the AI makes its move. It seems to be the same or very similar crashes.

**Game logs**
>Opening StupidAI
Loaded Stupid AI 0.1
LoadFrame error: Request for frame not present in CAnimation! File name: SPRITES/PortraitsLarge, Group: 0, Frame: 156
LoadFrame error: Request for frame not present in CAnimation! File name: SPRITES/PortraitsLarge, Group: 0, Frame: 157
Saving to Saves/Autosave/To_Build_a_Tunn_20240809T153019/1
Saving lib part of game...
	Saving header
	Saving options
	Saving mod list
	Saving gamestate
Saving server state
Game has been successfully saved!
Game has been saved as Saves/Autosave/To_Build_a_Tunn_20240809T153019/1
Player 0 (red) starting turn, day 64
Player 0 (red) ends turn
Player 7 (pink) starting turn, day 64
Player 0 (red) ended turn
Opening BattleAI
Loaded Battle AI
Opening BattleAI
Loaded Battle AI
/usr/include/c++/13.2.0/array:202: constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) [with _Tp = unsigned int; long unsigned int _Nm = 187; reference = unsigned int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

**To Reproduce**
Load a game
Finish your turn
Crash

**Expected behavior**
Turn finishes without crash

**Actual behavior**
VCMI crashes and closes

**Did it work earlier?**
I think it worked well with 1.4 series.

**Version**
 - OS: Linux flatpak
 - Version: 1.5.6

**Comment by IvanSavenko** [comment]
Can you upload VCMI_Client_log.txt after the crash?
Not sure where it is on Flatpak, so start VCMI launcher, open "help" tab and check "Log files directory"

**Comment by dasassaa** [comment]
[VCMI_Client_log.txt](https://github.com/user-attachments/files/16570209/VCMI_Client_log.txt)

**Comment by IvanSavenko** [comment]
This is immediately after the crash? Don't see related to AI turn in log.

**Comment by dasassaa** [comment]
Yes, immediately after the crash.

**Comment by Alexander-Wilms** [comment]
One can use GDB inside the Flatpak:

https://docs.flatpak.org/en/latest/debugging.html

**Comment by dasassaa** [comment]
@Alexander-Wilms, thanks. I installed the debugging version and let it run.

@IvanSavenko , is this info more helpful?:

>Opening BattleAI
Loaded Battle AI
Opening BattleAI
Loaded Battle AI
/usr/include/c++/13.2.0/array:202: constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) [with _Tp = unsigned int; long unsigned int _Nm = 187; reference = unsigned int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Thread 18 "runNetwork" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffbfa006c0 (LWP 74)]
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, 
    no_tid=no_tid@entry=0) at pthread_kill.c:44
44	      return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;

**Comment by IvanSavenko** [comment]
- Can you run `bt full` in gdb console after crash and post output? (although not sure how useful it will be for release build)

- Is crash reproducible from save? If yes - can you upload save before the crash?
Should be in `~/.var/app/eu.vcmi.VCMI/data/vcmi/Saves`

- Is this something that is specific to this map? Have you tried other maps? Do they crash as well?

- From what I see, crash happens at some point after start of a battle. Can you see what AI is trying to attack? Town? Wandering monster? Some other map object?

**Comment by dasassaa** [comment]
`bt full`

>(gdb) bt full
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {140736769023024}}
        ret = <optimized out>
#1  0x00007ffff46a3e83 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff4651dce in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007ffff463983f in __GI_abort () at abort.c:79
        save_stage = 1
        act = Python Exception <class 'gdb.MemoryError'>: Cannot access memory at address 0x7fffd51fdc40


- Is crash reproducible from save? -> Yes, I will attach it.

- Is this something that is specific to this map? Have you tried other maps? Do they crash as well? -> It is not specific to a certain map. This crash happens very often during gameplay on basically any map.

- From what I see, crash happens at some point after start of a battle. Can you see what AI is trying to attack? Town? Wandering monster? Some other map object? -> The crash happens randomly, sometimes in the middle of a fight when defending a town, sometimes when I am attacked by the AI. I cannot tell if the AI is trying to do something. Maybe you will see with the savegame.

- Savegame: 
[savegame.zip](https://github.com/user-attachments/files/16573473/savegame.zip)

**Comment by denis-sklyarov** [comment]
Still reproduced on iOS 17.5.1 iPhone 12
