### ISSUE TITLE
[rmg] the only road is blocked

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#4435]
Goblins can't be passed by, also not much where to go off-road.

[VCMI_Client_log.txt.zip](https://github.com/user-attachments/files/16574339/VCMI_Client_log.txt.zip)

Save: [1.vsgm1.tgz](https://github.com/user-attachments/files/16574341/1.vsgm1.tgz)

![Screenshot 2024-08-11 at 19 16 18](https://github.com/user-attachments/assets/07a9d853-f84b-4670-94e5-891447bb3945)
![Screenshot 2024-08-11 at 19 18 45](https://github.com/user-attachments/assets/622ced32-c89a-4f91-96fa-c2e38db1c539)

1.5.6 release

**Comment by dydzio0614** [comment]
not a bug - road can have block with limited strength depending on zone value IIRC

**Comment by kambala-decapitator** [comment]
first time seeing it in CSF template...

**Comment by Povelitelh3** [comment]
What do you think about 8XM8 teamplate? XD

**Comment by DjWarmonger** [comment]
Guard can block road if its value is up to 1/3 max value of this zone (which is a lot on Coldshadow's Fantasy, however).

**Comment by kambala-decapitator** [comment]
Thanks, seems not a bug indeed

**Comment by Alucard648** [comment]
Imagine if road was blocked by grand elves or marksmen guarding an artifact.
