### ISSUE TITLE
Compilation error in some config path in 1.5.6

### ISSUE THREAD

**Issue by Warzyw647** [vcmi/vcmi#4436]
**Describe the bug**
Compiling locally from tag 1.5.6 I get the following error:

Scanning dependencies of target vcmieditor
/home/maciek/vcmi/launcher/aboutProject/aboutproject_moc.cpp: In constructor ‘AboutProjectView::AboutProjectView(QWidget*)’:
/home/maciek/vcmi/launcher/aboutProject/aboutproject_moc.cpp:60:6: error: ‘class Ui::AboutProjectView’ has no member named ‘lineEditConfigDir’; did you mean ‘lineEditGameDir’?
   60 |  ui->lineEditConfigDir->setText(pathToQString(VCMIDirs::get().userConfigPath()));
      |      ^~~~~~~~~~~~~~~~~
      |      lineEditGameDir
/home/maciek/vcmi/launcher/aboutProject/aboutproject_moc.cpp: In member function ‘void AboutProjectView::on_openConfigDir_clicked()’:
/home/maciek/vcmi/launcher/aboutProject/aboutproject_moc.cpp:106:35: error: ‘class Ui::AboutProjectView’ has no member named ‘lineEditConfigDir’; did you mean ‘lineEditGameDir’?
  106 |  revealDirectoryInFileBrowser(ui->lineEditConfigDir);
      |                                   ^~~~~~~~~~~~~~~~~
      |                                   lineEditGameDir
[ 70%] Building CXX object mapeditor/CMakeFiles/vcmieditor.dir/cmake_pch.hxx.gch
make[2]: *** [launcher/CMakeFiles/vcmilauncher.dir/build.make:186: launcher/CMakeFiles/vcmilauncher.dir/aboutProject/aboutproject_moc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:643: launcher/CMakeFiles/vcmilauncher.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Game logs**
Not applicable

**To Reproduce**
1. Update master, beta and develop branches in my fork of vcmi
2. Go to the console
3. cd vcmi
4. git fetch upstream
5. git push --tags
6. git checkout 1.5.6
7. cd ../build
8. cmake -S ../vcmi
9. cmake --build . -- -j2
10. After some compiling, I observe the error.
That's how I usually compile new builds.

**Expected behavior**
Compilation ends without error.

**Actual behavior**
Compilation error after compilation is about 78% done. Compiling again (just the last step) runs into the same error.

**Did it work earlier?**
Same error in 1.5.5. No error in the previous version I installed, but not sure which one. Could've been some 1.5.x or last of the 1.4.x.

**Screenshots**

**Version**
 - OS: Linux Zorin
 - Version: 1.5.6, 1.5.5

**Additional context**

**Comment by IvanSavenko** [comment]
Complete removal of `build` directory (and clean rebuid) should fix this.

Caused by change in AUTO_MOC settings somewhere around 1.5.5
