### ISSUE TITLE
CMake Error while generating XCode projects in MacOS

### ISSUE THREAD

**Issue by mikeiit** [vcmi/vcmi#4438]
**Describe the bug**
While generating the XCode projects following steps in [this doc](https://github.com/vcmi/vcmi/blob/develop/docs/developers/Building_macOS.md#configuring-project-for-building), CMake throws translation related errors like this -
```
CMake Error in launcher/lib/innoextract/CMakeLists.txt:
  The custom command generating

    /Users/{path_to_vcmi_local_repo}/build/launcher/chinese.qm

  is attached to multiple targets:

    VCMI_lrelease
    vcmilauncher_other_files
    vcmilauncher_vcmilauncher_translations

  but none of these is a common dependency of the other(s).  This is not
  allowed by the Xcode "new build system".
```

This error happens in multiple CMakeLists.txt files and it complains about multiple different .qm files. 

**Game logs**
N/A

**To Reproduce**
1. Follow the steps listed in the [doc](https://github.com/vcmi/vcmi/blob/develop/docs/developers/Building_macOS.md#building-vcmi-for-macos) to build in macOS.
2. Choose XCode IDE, Homebrew. Install ffmpeg@4 and Qt6.
3. Use this command to generate projects: cmake -S . -B ../build -G Xcode -D "CMAKE_PREFIX_PATH=$(brew --prefix ffmpeg@4)" 

**Expected behavior**
We should generate XCode projects successfully without error.

**Actual behavior**
Errors are thrown and VCMI.xcodeproj is missing

**Did it work earlier?**
Unknown. Based on @kambala-decapitator, Qt6 has not been tested in macOS settings. 

**Screenshots**
None.

**Version**
 - OS: macOS Arm Sonoma 14.5
 - Version: VCMI 1.5
 - IDE: XCode 15.4

**Additional context**
This error will not occur if we turn ENABLE_TRANSLATIONS off in [here](https://github.com/vcmi/vcmi/blob/84f29183c849c5c64f108d3bff2a5079d030809d/CMakeLists.txt#L44)

**Comment by IvanSavenko** [comment]
Already fixed from what I remember

**Comment by kambala-decapitator** [comment]
> Already fixed from what I remember

Maybe, not sure
