### ISSUE TITLE
Crash in AI with Orb of Inhibition

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#4446]
**Describe the bug**
There is a crucial bug in 1.5.6, For the reason of blocked spells.

Actually it only occurs in AI turn.

**To Reproduce**
1. Make an AI hero, who has Orb of Inhibition in his/her misc blanks.
![image](https://github.com/user-attachments/assets/da468707-54e7-4db3-841f-1bebb5d514b2)
2. Make a player hero, who can use any spells.
3. Let AI hero attacks player hero
4. Click the spell button during the battle.
![image](https://github.com/user-attachments/assets/e337a675-4c85-4e15-b8da-c10458d534a5)
5. Expected behavior: the message shows the hero cannot open the spell book.
6. Actual behavior: The hero still cannot open spell book, but no message.
7. Click escape button, and replay the battle
8. See error, the game crashes

Actually if player hero defeats the AI hero, in next turn, the message will show several times, which depends on how many times player has clicked the button. 

The same condition in Recanter's Cloak.
![image](https://github.com/user-attachments/assets/62812dce-8a6c-49b9-b4fa-11884d4b2fe6)

**Did it work earlier?**
In 1.5.5, there is no problem like this.

**Version**
 - OS: Android. Windows
 - Version: 1.5.6 formal version & 1.6.0 test version

**Comment by IvanSavenko** [comment]
Not reproducible for me for some reason.
I was attacked by AI with orb of inhibition, pressing spellbook icon correctly shows error message. 1.5.6 release.

**Comment by by003** [comment]
Hello @IvanSavenko 
I show a test map here.
[2.zip](https://github.com/user-attachments/files/16706619/2.zip)

The video is here:

https://github.com/user-attachments/assets/02d54c9e-2105-4712-a234-5b14401fb7f2

You can try it with 1.5.6 release or 1.6.0 test version. 
![image](https://github.com/user-attachments/assets/f69611ea-5ec6-433d-b3ca-747322702f10)

**Comment by by003** [comment]
I have tested from this version.
[VCMI-WindowsAlternate.exe](https://github.com/vcmi/vcmi/releases/download/1.5.6/VCMI-WindowsAlternate.exe)

Is there any diffrence from[VCMI-WindowsAlternate.exe](https://github.com/vcmi/vcmi/releases/download/1.5.6/VCMI-WindowsAlternate.exe) and [VCMI-Windows.exe](https://github.com/vcmi/vcmi/releases/download/1.5.6/VCMI-Windows.exe)?

**Comment by IvanSavenko** [comment]
WTF.
Reproducible only on alternate/msvc build.

Perhaps some weird thread races or undefined behavior, e.g. uninitialized variable? Investigating.

**Comment by kdmcser** [comment]
My friend reproduces it in conan build too.

**Comment by kambala-decapitator** [comment]
how to enable the Replay button?

I could reproduce a similar issue on macOS which resembles #4417, but not sure if the reason of the bug is the same as in this issue:
1. play as blue
2. skip turn, AI attacks you
3. press Spell Book button - nothing happens
4. retreat
5. AI attacks your second hero

Result: battle window doesn't appear, game seems stuck, but animations play.

**Comment by MichalZr6** [comment]
I could reproduce the same as kambala. AI attacks my town instead and battle window doesn't appear, game is in like-an infinite loop. It seems to be stuck here: 

![obraz](https://github.com/user-attachments/assets/efa6d529-310f-4636-97bb-6cad3853a9f7)

**Comment by MichalZr6** [comment]
Perhaps a check if we are in battle interface... ?

**Comment by Povelitelh3** [comment]
I don't have a crash, but after the battle messages pop up as many times as I clicked on the book that the orb of prohibition is on. The same applies to the cloak of renunciation when I try to click on the chain lightning

**Comment by IvanSavenko** [comment]
Stuck moment - that would be too late. Game should not reach that code to begin with.

Actual bug is inside `CPlayerInterface::showInfoDialog` since it does not seems to account for messages from ongoing combat. However not sure why it works fine for me.
In any case, fix seems to be in #4500
