### ISSUE TITLE
[Android] Missing labels in Options page

### ISSUE THREAD

**Issue by sergkundel** [vcmi/vcmi#4450]
Android 14
VCMI latest available version (Aug 4, 2024)
Installed mods: VCMI core and extras

Hello,
For some reasons I don't have labels for most of the options (see screenshot below)
![Screenshot_2024-08-14-20-43-08-45_41d7730817d4f0f666b5cd2eca25c7fd](https://github.com/user-attachments/assets/e482f033-01cc-42bf-aadc-776cf49dcbdb)

**Comment by IvanSavenko** [comment]
You have language that is not supported by H3 fonts.
Easiest way to fix is to install translation mod that usually provides corresponding fonts

**Comment by sergkundel** [comment]
@IvanSavenko That's strange - I haven't install any translations. Does language configured in launcher (ukrainian) affects the game itself?

**Comment by IvanSavenko** [comment]
Yes. Game attempts to display in-game texts added by VCMI in Ukrainian and fails since English fonts only contain latin.
You can either switch VCMI launcher to English or install translation mod.

**Comment by sergkundel** [comment]
Alright, changing language to English in launcher resolves the issue.
Maybe it's better to separate configurator and game languages? I thought that Translations is responsible for in game language.

Anyway, we can close this issues as won't fix.

**Comment by IvanSavenko** [comment]
Separate language for launcher & game is technically possible but sounds like making things complex for no reason.

IMO the only problem here is that vcmi can't display fonts in such cases. Might look into it for 1.6, e.g. provide font that covers most of languages that we support
