### ISSUE TITLE
Wrong map title when launching a game

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [vcmi/vcmi#4453]
**Describe the bug**
Sometimes (random bug), all the VCMI maps loaded by VCMI display the same title. It's the title of one of the maps. When you click on an unselected map, they are all renamed by the name of another map, and then and then.

**Game logs**
No log.

**To Reproduce**
1. Put some `.vmap` files in the map folder
2. Start VCMI
3. Click on _New Game_
3. Click on _Single Scenario_
4. Scroll down to the VCMI maps

**Expected behavior**
Each map has its own name.

**Actual behavior**
They all have the same name.

**Did it work earlier?**
Random bug. Sometimes, it works. I have already seen the bug monthes ago.

**Screenshots**
![image](https://github.com/user-attachments/assets/9cddb3a2-0244-4c58-bbf4-a50b84eea9de)

**Version**
 - OS: Windows 10
 - Version: `VCMI-branch-develop-c1c04b3.exe`

**Additional context**
Other features like the map size are always working.

**Comment by godric3** [comment]
already reported in #3572
