### ISSUE TITLE
During PvP siege defending player doesn't get battle window

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#4455]
**Describe the bug**
When human player attacks another human player in a town, defending player doesn't get battle window at all and gets stuck. Happened few times in PvP tournament.

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Launch online game with 2 players
2. Have one player attack another in a town to start a siege

It seems that it only happens when host (red) attacks guest (blue), while guest can start a siege with no issues.

This save might be helpful:
[Bug4455.zip](https://github.com/user-attachments/files/16627019/Bug4455.zip)

**Expected behavior**
Battle will start normally, both players can see battle GUI and interact with it.

**Actual behavior**
Combat window doesn't load for the defending player.

**Did it work earlier?**
No idea, PvP is rather fresh.

**Screenshots**
![image](https://github.com/user-attachments/assets/b0511040-6b58-40c1-8f3b-4285a2843804)
Blue player doesn't get battle window in this situation.

**Version**
1.5.6

**Comment by DjWarmonger** [comment]
Also, does autocombat trigger in PvP battle by any chance?

**Comment by wnukos** [comment]
[VCMI_Client_log blue host.txt](https://github.com/user-attachments/files/16678312/VCMI_Client_log.blue.host.txt)
[VCMI_Client_log red host.txt](https://github.com/user-attachments/files/16678314/VCMI_Client_log.red.host.txt)

I've reproduced the error from the save file attached to this issue in two cases:

- The host is playing red color.
- The host is playing blue color.

In the game the red player attacks the blue player in a castle. In other games players reported that the error occured only when the host was the attacking player, so I wanted to verify it. Unfortunately with this save file we were unable to fight the battle, regardless if the hosting player was attacking or defending. In both cases the attacking player entered the battle window but neither fought with Human Player nor with AI - when it was defending player's turn simply nothing happened. It was also impossible to click any creature or quit the battle, only basic creature animations were observable. The defending player didn't even enter the battle screen, he saw adventure map. Interestingly when the battle was initiated, the blue player could observe that the hero defending in the castle dissapeared.

**Comment by wnukos** [comment]
These are logs from the host ofc.

**Comment by godric3** [comment]
Was it red attacking on first day of week? If yes then that match what we found in #4458, blue players had pending new week dialog that blocked battle window

**Comment by wnukos** [comment]
Yes, this is correct, the attack was in turn 131.

**Comment by IvanSavenko** [comment]
Logs also match what I saw in logs in #4458 - player stuck on waiting for some dialog (e.g. new week). So should be fixed in my PR
