### ISSUE TITLE
iPad VCMI is no longer available after crash in Campaign

### ISSUE THREAD

**Issue by Dynamitko** [vcmi/vcmi#4471]
**Describe the bug*
The game crashed just after the intro video played, when launching Erathia campaign second part with the dungeons and now it says VCMI is no longer available on iPad. 

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.
Done in comments sry!
![IMG_1511](https://github.com/user-attachments/assets/984c16eb-f0c1-4919-b345-b251e50e7c4f)

**To Reproduce**
1. Go to iPad screen
2. Click on VCMI app
3. See error

**Expected behavior**
VCMI opens.

**Actual behavior**
VCMI is no longer available.

**Did it work earlier?**
If this something which worked well some time ago, please let us know about version where it works or at date when it worked.

Yes VCMI worked and I could play through the whole griffin campaign 3 missions total.

**Screenshots**

**Version**
 - OS: iPadOS 17.5.1 (21F90)
 - Version: 1.5.6 
Build 2024-08-04-5313b5c

**Additional context**

**Comment by Dynamitko** [comment]
[VCMI_Client_log.txt](https://github.com/user-attachments/files/16649159/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/user-attachments/files/16649160/VCMI_Launcher_log.txt)

**Comment by kambala-decapitator** [comment]
> now it says VCMI is no longer available on iPad

Unrelated to the crash, simply 7 days since you installed it with free developer account has passed.

**Comment by Dynamitko** [comment]
Thanks, any clue how I could address it?

**Comment by Dynamitko** [comment]
Oef I read into it and understood the issue... Thanks for letting me know, might be good to call it out that it will keep expiring every 7 days or so on the official page.

**Comment by kambala-decapitator** [comment]
> might be good to call it out that it will keep expiring every 7 days or so on the official page

that doesn't happen in 100% of cases. For example, if you use AltStore, it will add 7 days automatically, you only need to turn on your PC/Mac at least once a week. Or if you have paid Apple developer account ($99/year), then it will expire only once a year.
