### ISSUE TITLE
Mystical Garden will not change the reward since the first time

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#4489]
**Describe the bug**
If using the code like:
```
"resetParameters" : {
					"period" : 7,
					"visitors" : true,
					"rewards" : true
				},
```
The objects will only give one reward from the chance lists, from first day and always be the same.

For example, if mystical garden gives hero 500 gold, it will always give the same rewards until the end of the game
If the reward is 5 gems, it will not change until the end either.

**Expected behavior**
Every week, the rewards will be random from gold and gems.

**Actual behavior**
If it gives gold first time, it will not change the reward until the end of game.

**Did it work earlier?**
For a long time it has occured.

**Version**
 - OS: Windows & Android
 - Version: 1.5.6 or 1.6.0 test version

**Comment by IvanSavenko** [comment]
Can confirm that something might be wrong in 1.5 - got gold 4 times out of 4
