### ISSUE TITLE
Freeze in battle

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4498]
the save was taken from 4pda.to
Happened on android 1.5.6, reproduce on my windows system (msvs, develop ff33fbd3 )

[_E3_EB_FE_EA+Hmm3.zip](https://github.com/user-attachments/files/16729189/_E3_EB_FE_EA%2BHmm3.zip)

Yellow player Gundula attacks Darkstorn, but the fight does not occur. The game freezes at this point.

If you attack Gundula yourself, then everything is fine

> [2024-Aug-23 16:26:05.105712] DEBUG [AIGateway::makeTurn] ai - Behavior Explore. Time taken 22
> [2024-Aug-23 16:26:05.111706] DEBUG [AIGateway::makeTurn] ai - Decision madel in 449
> [2024-Aug-23 16:26:05.112708] DEBUG [AIGateway::makeTurn] ai - Trying to realize Composition[Defend town Сшэд, Подземелье, ] [ExecuteHeroChain prison(64 18 0) by Гундула => ]  (value 0.797)
> [2024-Aug-23 16:26:05.113707] DEBUG [AIGateway::makeTurn] ai - Executing hero chain towards prison(64 18 0). Path Гундула[20], turn 0: Гундула[20]->(64 18 0); 
> [2024-Aug-23 16:26:05.114705] DEBUG [AIGateway::makeTurn] ai - Executing chain node 0. Moving hero Гундула to (64 18 0)
> [2024-Aug-23 16:26:05.124698] DEBUG [AIGateway::makeTurn] ai - Moving hero Гундула to tile (64 18 0)
> [2024-Aug-23 16:26:05.131694] DEBUG [runServer] global - Hero hero.core.gundula.name visits Дарксторн Верховный лорд (34)
> [2024-Aug-23 16:26:05.136691] DEBUG [runServer] global - Next round starts
>

**Comment by Povelitelh3** [comment]
beta 1.5.7.457a1bc746ae46b88898b783313652d2b3677bff is ok ....

**Comment by IvanSavenko** [comment]
Probably same bug as freeze on pvp battle start.

If player is attacked when has any waiting dialog (new week, map event, etc) game will freeze. Fixed in 1.5.7 (today or tomorrow)

**Comment by Povelitelh3** [comment]
The green player left this world, but I saw this message after the end of the turn. (Perhaps the AI ​​saw it earlier and the game froze).
Ok, let's assume that this was the reason.
Moreover, the person notes that there was no such problem before.

**Comment by IvanSavenko** [comment]
Yeah, defeated player also counts as such "waiting dialog"

> Moreover, the person notes that there was no such problem before (1.5.6)

Conditions for this bug to trigger are rather rare. And almost impossible to achieve in singleplayer since player always acts before AI's (and will not have waiting new week / map events dialogs).

**Comment by IvanSavenko** [comment]
Fixed in 1.6
