### ISSUE TITLE
create background error in advantage map

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#4505]
**Describe the bug**
opening a map，so many creatures background is error.
![1](https://github.com/user-attachments/assets/de3c975c-d569-4a3d-be02-4ee2c0e1161f)
![2](https://github.com/user-attachments/assets/ccf3060e-cca3-4ae3-94f7-dc31e5b4e27c)
![3](https://github.com/user-attachments/assets/d65772c2-dd1a-4529-b88f-9bae2b9647db)
![4](https://github.com/user-attachments/assets/7d9ca066-b77c-4b2c-b126-5fe99351fa44)

I find a def file of one creature, it seems no problem in def previewer.
 
[CR203.zip](https://github.com/user-attachments/files/16736115/CR203.zip)

**To Reproduce**
this def is from retreat-town mod.

**Did it work earlier?**
not in 1.5.5

**Version**
 - OS: Windows
 - Version: 1.6 develop branch

**Comment by kdmcser** [comment]
a easy way to reproduce:
![屏幕截图 2024-08-24 184544](https://github.com/user-attachments/assets/e5f4519b-b37a-418d-9d27-336b3647a644)

**Comment by misiokles** [comment]
It seems that error concerns non-cyan backgrounds in def files.
