### ISSUE TITLE
Original H3 items not appearing on RMG map if mod adds template

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4552]
**Describe the bug**
With WoG installed the red OH3 treasure chests are gone, same for wells, etc.

**To Reproduce**
1. Install Wog mod.
2. Start a RMG map in Jebus Cross

**Expected behavior**
Standard objects should appear unless overridden

**Version**
 - OS: [e.g. Windows, ]
 - Version: [VCMI version 1.5.7]

**Additional context**
[core_objects.treasureChest.json](https://github.com/user-attachments/files/16840553/core_objects.treasureChest.json)

Was working a year ago. (Biomes update???)

**Comment by krs0** [comment]
@DjWarmonger Any chance this receives a fix for 1.6?

**Comment by GeorgeK1ng** [comment]
You mean this? Seem to work for me with latest 1.6 and WoG. Tested on random map and with Jebus template aswell. And yes, I have both skinned magic wells.
![image](https://github.com/user-attachments/assets/3b78de04-28a7-409c-a322-d057cd1010db)

**Comment by krs0** [comment]
Yes, in Wog only it works, it may come from another mod I had and I thought it reproduces with WoG only :(.

Will check the other mods, could be closed.
