### ISSUE TITLE
Crash while right click hero portrait in selecting maps

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#4583]
**Describe the bug**
In this screen, right click the hero's portrait will cause a crash. 
In Sept 12th develop build.

**Did it work earlier?**
It works well in 1.5.7 and the develop version before 9th Sept.

**Screenshots**
![image](https://github.com/user-attachments/assets/282f7adb-07f3-4c64-bcc4-5981e1210f9d)

**Version**
 - OS:  Windows, Android
 - Version: 1.60 develop

**Comment by pppbb** [comment]
Can confirm the issue. VCMI 1.6.0 git built with Msys2.
