### ISSUE TITLE
Balance schools of magic

### ISSUE THREAD

**Issue by jaicmatija** [vcmi/vcmi#4592]
Is it possible to make town portal spell to be in all schools of magic just like visions or magic arrow?

Also is there a way to mod the game to move dimension door spell to fire school of magic?

this would really balance the magic in this game.
Maybe it would be interesting to also add more spell to the game, but does anybody know how difficult is that?

**Comment by rilian-la-te** [comment]
It is all possible with mods, AFAIK.

**Comment by misiokles** [comment]
It is possible. Check Andruids Balance Mods or New Old Spells mod for reference how to do that (it's rather easy)

**Comment by by003** [comment]
I used to design a fire Magic named Intelligence Fire.
If you have an expert fire magic, after casting this spell, the hero will gain expert effect for other three schools.

**Comment by GeorgeK1ng** [comment]
This simple config change Dimension Door spell to Fire magic.
```

{
	"core:dimensionDoor" : {
		"school": {
			"air": false,
			"earth": false,
			"fire": true,
			"water": false
		}
	}
}
```

Can be done by mods, no need for developing.
