### ISSUE TITLE
True type fonts mod from vcmi-extras doesn't work with polish version of H3

### ISSUE THREAD

**Issue by ToRRent1812** [vcmi/vcmi#4601]
If You run Heroes 3 in PL, the Polish translation mod overrides the true type font from vcmi-extras. I assume, the mod priority is alphabetical, so it never overrides the og font from the translation.

**Comment by Laserlicht** [comment]
@ToRRent1812 You run on android right?

It seems a problem with android and not with a specific language. Works on PC without problems for me.

**Comment by ToRRent1812** [comment]
> @ToRRent1812 You run on android right?
> 
> It seems a problem with android and not with a specific language. Works on PC without problems for me.

No, Windows 10 and Linux.

**Comment by Laserlicht** [comment]
Keep in mind:
VCMI extra true type currently works only as fallback. If string contains character not representable by bitmap font, the string is rendered as true type. And the font files coming with polish translation can render all polish characters. So you see the ttf font only when typing e.g. chinese character.

You can change this behavior by removing `fallback`s in `fonts.json` of mod.

**Comment by ToRRent1812** [comment]
Ah I see, then we can close this. Thanks for clarification.
