### ISSUE TITLE
crash on entering it on map or in town mercenary guild

### ISSUE THREAD

**Issue by Thickblackcat** [vcmi/vcmi#4620]
**Describe the bug**

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear description what is currently happening 

**Did it work earlier?**
If this something which worked well some time ago, please let us know about version where it works or at date when it worked.

**Screenshots**

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: [VCMI version]

**Additional context**

**Comment by IvanSavenko** [comment]
More details please

**Comment by IvanSavenko** [comment]
Not enough info / unable to reproduce
