### ISSUE TITLE
jpg background crashes vcmiclient

### ISSUE THREAD

**Issue by swats-the-floran** [vcmi/vcmi#4639]
**Describe the bug**
if your mod contains main menu background in jpg format if crashes vcmi client on launch.

**Game logs**
-

**To Reproduce**
1. install and enable "medusas are the best girls" mod
2. launch the game

**Expected behavior**
jpg works as good as a png format.

**Actual behavior**
game crashes

**Did it work earlier?**
no information

**Screenshots**
![image](https://github.com/user-attachments/assets/83c55a8c-7248-4d3d-ade5-f08896de6e2a)

**Version**
 - OS: windows, asndroid
 - Version: latest

**Additional context**
https://github.com/vcmi-mods/new-interface-mod/issues/39

**Comment by swats-the-floran** [comment]
works in linux though.

**Comment by IvanSavenko** [comment]
VCMI supports png, bmp and h3-pcx.
Our image loading library in both 1.5 and 1.6 built without jpg support.

On Linux this library is provided by the distribution and likely supports more formats

**Comment by swats-the-floran** [comment]
ok then, i will convert the image then.

**Comment by kambala-decapitator** [comment]
could be a feature request though

**Comment by misiokles** [comment]
I've read somewhere that .jpg files can't be stored at github as not open format (the same as .mp3)

**Comment by IvanSavenko** [comment]
Could be a feature if needed. But do we have such need?

jpg - first time I hear about it.
mp3 - I think patents have already expired? Although by now there are way better formats than mp3

**Comment by swats-the-floran** [comment]
> I've read somewhere that .jpg files can't be stored at github as not open format (the same as .mp3)

https://github.com/vcmi-mods/new-interface-mod/tree/vcmi-1.4/screenshots
