### ISSUE TITLE
FEROCITY and REVENGE bonuses don't work.

### ISSUE THREAD

**Issue by Olegmods** [vcmi/vcmi#4647]
**Describe the bug**
See the title.

**Game logs**
Can attach later if needed

**To Reproduce**
1. Download Kremlin-Town from heroes3wog or Cove from launcher
2. Use vcmibuild
3. Buy some Druginniks or (with Cove - Ayssids)
4. These should have Ferocity, but they don't.
5. Same issue with Haspids and Epic Bogatyrs

**Expected behavior**
These should have FEROCITY and REVENGE

**Actual behavior**
They don't have the bonuses.

**Did it work earlier?**
I think it worked, but I'm not sure.

**Screenshots**
![Screenshot_20240922_151739](https://github.com/user-attachments/assets/35a98e99-0ca9-4a7b-87bc-f53065689f09)

**Version**
 - OS: Windows, Android
 - Version: 1.5.6 and 1.5.7

**Additional context**
Could be wrong config from my side, but I don't think so.

**Comment by misiokles** [comment]
Those bonuses were written after 1.5.x releases, so will work with vcmi-1.6

**Comment by dydzio0614** [comment]
no, these bonuses were written for VCMI 1.4

**Comment by Olegmods** [comment]
![Screenshot_20240922_161547_Chrome](https://github.com/user-attachments/assets/80ab6d06-ecde-492c-8c33-94bfde12b51e)
From misiokles's repository for Kremlin mod. Seems the text wasn't changed for this. So it's not wrong mod config.

**Comment by Olegmods** [comment]
Was an issue on my side.
