### ISSUE TITLE
Heroes Chronicles mod installed via gog installer can't run on Android and PC.

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#4656]
Heroes Chronicles mod installed via gog installer can't run on Android and PC.
It runs well on **VCMI-branch-develop-6299b29.exe**.
By the way, I copy the mod from PC directly.

**Comment by lishaoxia1985** [comment]
@Laserlicht In Custom Campaign Screen, you can see the Campaign list, and then when you touch Load button, the app will crash.

**Comment by Laserlicht** [comment]
For me it's working fine.

But there was a change a few days ago.

Please make sure you have on PC and Android the newest dev version. Then recreate the gog mod from Installer files and copy to phone again.

**Comment by lishaoxia1985** [comment]
@Laserlicht Do you have the other way to fix it? For example, edit the mod json. I have deleted the gog installer.

**Comment by Laserlicht** [comment]
Installing one chronicle is enough.

You can try ro rebuild structure:
launcher/modManager/chroniclesextractor.cpp

**Comment by Laserlicht** [comment]
```
{
    "author": "3DO",
    "contact": "vcmi.eu",
    "description": "Heroes Chronicles",
    "heroes": [
        "config/heroes/portraitsChronicles.json"
    ],
    "modType": "Expansion",
    "name": "Heroes Chronicles",
    "settings": {
        "mapFormat": {
            "chronicles": {
                "portraits": {
                    "portraitTarnumBarbarian": 163,
                    "portraitTarnumBeastmaster": 168,
                    "portraitTarnumKnight": 164,
                    "portraitTarnumOverlord": 167,
                    "portraitTarnumRanger": 166,
                    "portraitTarnumWizard": 165
                },
                "supported": true
            }
        }
    },
    "version": "1.0"
}
```

Can you confirm if it works?

**Comment by lishaoxia1985** [comment]
@Laserlicht Thank you. If I edit mod.json it runs well.
