### ISSUE TITLE
Mouse scroll wheel has no effect anywhere in the game.

### ISSUE THREAD

**Issue by nerozero** [vcmi/vcmi#4657]
**Describe the bug**
Mouse scroll wheel not working

**To Reproduce**
1. Launch the vcmi client (Window mode, not a full screen)
2. try to use mouse scroll wheel to scroll in menus - no reaction
3. try to use mouse scroll wheel in game say for scrolling a town list - no reaction

**Expected behavior**
Use a mouse scroll wheel in lists

**Actual behavior**
Mouse scroll wheel has no effect at all

**Did it work earlier?**
Yes, I have another older notebook with older VCMI client ( not sure about version, also compiled from git. The notebook is not with me now, cant tell the version, but it where compiled somewhere in June )

**Version**
 - OS: Linux Mint 22 Wilma
 - Version: VCMI 1.6.0.3209aa58e87b4e2c16216f366fbb558e522135c2

**Comment by nerozero** [comment]
Weird, actually it works, but not where you expect scroll to work. The active rectangle area where scroll wheel is working is shifted a bit to the left, probably due to scale? 
(see attached video)

https://github.com/user-attachments/assets/7792e5bc-ee34-4c68-bd5e-cf2a3c692335

**Comment by IvanSavenko** [comment]
Looks like already fixed SDL bug. Will add version check.

**Comment by nerozero** [comment]
@IvanSavenko Thank you for quick reply. Thanks.
