### ISSUE TITLE
firewall breaks the game

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4661]
spell firewall now broken

take tom of fire and attack enemy hero. In battle use firewall in random place - crash on AI move.
I taked 2 stacks of dragons and just press 'defend', after that game crashed

[firewall.zip](https://github.com/user-attachments/files/17102287/firewall.zip)
[VCMI_Client_log.txt](https://github.com/user-attachments/files/17102299/VCMI_Client_log.txt)

**Comment by IvanSavenko** [comment]
Likely already fixed in #4655

**Comment by Povelitelh3** [comment]
> Likely already fixed in #4655

you are right. fixed
