### ISSUE TITLE
[map editor] Can't select affected players for timed event

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [vcmi/vcmi#4670]
**Describe the bug**
Can't select affected players for timed event in map editor.

**Game logs**
I don't know

**To Reproduce**
1. Launch the map editor
2. Create a map
3. Click on _Map_ -> _General_
4. Click on _Event_
4. Click on _Timed_
4. Click on _Add_
5. Add title
5. Add description
6. Check red on the right
7. Click on _Ok_
7. Click on _Ok_
8. Reopen the event

**Expected behavior**
The red player is checked.

**Actual behavior**
The red player remains unchecked.

**Did it work earlier?**
I don't know

**Screenshots**
![image](https://github.com/user-attachments/assets/a260387d-e31f-459c-a625-a717d28739b6)

**Version**
 - OS: Windows 10
 - Version: `VCMI-branch-develop-d0ac645.exe`

**Additional context**
I suggest also that the event is for everybody if it's checked for nobody.

**Comment by godric3** [comment]
Saving of players should be fixed in https://github.com/vcmi/vcmi/pull/4608, can you test with newer build?

**Comment by Fabrice-TIERCELIN** [comment]
@godric3, there are no builds for Windows (nor arm) on 2024-Sep-27 whereas there are for other environments

**Comment by Fabrice-TIERCELIN** [comment]
I works 🙂
