### ISSUE TITLE
RMG Portal connections between adjacent zones

### ISSUE THREAD

**Issue by Warzyw647** [vcmi/vcmi#4676]
**Describe the bug**
Some of the "default" type connections between adjacent zones generate as portals even when these zones share a fairly long boarder.

**To Reproduce**
1.Generate a map from the attached template:
[sim-city.json](https://github.com/user-attachments/files/17139152/sim-city.json)
2. Observe which of the connections are ground connections and which are portal connections.
3. Compare observations with enabled and disabled roads.
4. Compare to templates generated from this: https://github.com/vcmi-mods/warzyw-templates/blob/vcmi-1.4/warzyw-templates/Mods/sim-city/content/sim-city.json from warzyw-templates mod version up to 1.20

**Expected behavior**
The vast majority of default type connections between adjacent zones generate as ground connections

**Actual behavior**
Surprisingly many connections generate as portals.

**Did it work earlier?**
Probably yes, back in 1.4.x but not sure. Only checked in 1.5.6 recently.

**Screenshots**
Zones that share a fairly long boarder but have a portal connection, generated from the attached template file:
![image](https://github.com/user-attachments/assets/0aadb78c-e83b-49d2-b350-b689bf7301d7)

**Version**
 - OS: Linux
 - Version: 1.5.6

**Additional context**
With more towns per zone the problem seems to appear more. Without roads the problem seems to appear less, that is more of the standard connections between the adjacent zones generate as ground connections.

**Comment by DjWarmonger** [comment]
Already implemented in 1.6.0: https://github.com/vcmi/vcmi/pull/4964
