### ISSUE TITLE
WebM takes some time

### ISSUE THREAD

**Issue by heroesiiifan** [vcmi/vcmi#4678]
**Describe the bug**
Starting WebM video (with audio) takes some time to start.

**To Reproduce**
1. With 1.6 download french, italian, russian or spanish translation.
2. Start game
3. wait for intro video from RoE (takes 15-20sec to load from black screen)

**Expected behavior**
Video should start instant.

**Did it work earlier?**
New videos in mod (it doesn't seems to possible to create bink video with ffmpeg, so I've choosed WebM).

**Version**
 - Version: 1.6 develop

**Comment by Laserlicht** [comment]
Seems to be the audio resampling that takes so long. Not sure if there is room for improvements.

**Comment by IvanSavenko** [comment]
Can you add link to such video?

**Comment by heroesiiifan** [comment]
https://github.com/vcmi-mods/spanish-translation/blob/vcmi-1.6/spanish-translation/content/video/H3Intro.webm

**Comment by IvanSavenko** [comment]
Hmm...
My PR will fix this bug... but if we're talking about this case specifically - why we even need this as a video?

What we need is a localized soundtrack for use in localization mods in place of original/English audio.
And video itself can come from whatever data files player is using.

Should be easy to implement and can reduce size of localization mods

**Comment by heroesiiifan** [comment]
Currently the only reason is that it isn't possible to define alternative audio instead using audio from video.

If we can implement this as as optional it would be great. Than we could reduce translation mod sizes.
