### ISSUE TITLE
Witch Hut should not be random in some Campaigns

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#4713]
For example, in the first Scenario of the Campaign Dragon Slayer.
Be the way, now enemy's Faerie Dragon can't still spell magic.

**Comment by dydzio0614** [comment]
use battleai instead of stupidai for neutrals to make faerie dragons cast spells

**Comment by lishaoxia1985** [comment]
@dydzio0614 But that faerie dragons cast spells should be default.

**Comment by dydzio0614** [comment]
there are reasons why battle ai was not default, and stupidai cannot cast spells

**Comment by lishaoxia1985** [comment]
@dydzio0614 That faerie dragons cast spells should be default.
StupidAI is good for some maps, for example With Sword and Fire(in Hota). You can't win if ai is BattleAI.
I think StupidAI should be the same as the original or the Hota.

**Comment by dydzio0614** [comment]
stupidai is kinda in same state as VCAI - no fixes planned at the moment

**Comment by lishaoxia1985** [comment]
@dydzio0614 Ok, that means in some Crazy maps:
1.If ai is StupidAi, it's very easy.
2. If ai is BattleAi, you can't win.

**Comment by kambala-decapitator** [comment]
> I think StupidAI should be the same as the original or the Hota.

it can't be "same as the original or the Hota" because there's no source code available. Writing it from scratch sounds like a serious effort to me.

some crazy maps are tuned specifically to the behavior of the original AI.
