### ISSUE TITLE
In Artifact info window, Artifact info can't be scrolled.

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#4715]
![Screenshot_2024_1003_034936_is.xyz.vcmi.daily.png](https://github.com/user-attachments/assets/dd50e7cd-799b-4b79-abb2-2771d242c4a0)

You can look at this picture, that means you can't see all the info.

**Comment by IvanSavenko** [comment]
Was working fine few weeks ago with mouse wheel.
Or is this screenshot from phone? Android or iOS?

**Comment by lishaoxia1985** [comment]
@IvanSavenko Android.

**Comment by lishaoxia1985** [comment]
@IvanSavenko By the way, the window that likes this is also used somewhere. It can't be also scrolled.
![Screenshot_20241009_094527_is.xyz.vcmi.daily.jpg](https://github.com/user-attachments/assets/274731ed-a6d4-4b6b-aea7-bb0677877354)
