### ISSUE TITLE
Cannot update a mod if another mod has a dependency on it

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4727]
**Describe the bug**
I have 2 mods. Forge2k that depends on Asphalt Terrain. I cannot update Asphalt terrain unless I manually disable Forge2k.

For other mod collections (like PVP balance) the scenario is more complicated, because there are more dependencies.

**Version**
 - OS: [e.g. Windows
 - Version: [VCMI version] 1.5.7

**Comment by IvanSavenko** [comment]
Duplicate of #2046
