### ISSUE TITLE
When visiting a Shrine without a book, is hard to see what spell you cannot learn

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4728]
**Describe your proposal**
When visiting a Shrine without a book, is hard to see what spell you cannot learn because the name of the spell is hidden in a wall of text.

![image](https://github.com/user-attachments/assets/16ec3a64-ddc4-4934-8a3a-3831f9441d3f)

It would help if at least the spell would  be highlighted (bold, color)
The spell icon could be displayed, but greyed out? But it should remain obvious that you did not learn the spell. (Keep " Unfortunately you have no spell book to record the spell with" text...)

**Comment by GeorgeK1ng** [comment]
What about improving all these Shrine messages like this? To make Spell name colored to improve readability.

![image](https://github.com/user-attachments/assets/c31a256a-e773-43d0-81ff-8f25bc932203)

**Comment by krs0** [comment]
Its a good improvement. Would suffice.

**Comment by GeorgeK1ng** [comment]
Yes, it's really quality of gaming improvement. Let's wait until we see it in daily builds. WoG or HotA Shrines for v1.6 are ready.

**Comment by IvanSavenko** [comment]
Or perhaps color all name replacements?

**Comment by GeorgeK1ng** [comment]
In all Shrine variants are now Spells name colored. I have fixed it for all Shrine scenarios.

**Comment by GeorgeK1ng** [comment]
Ah, I see Pyramid should be included aswell

**Comment by GeorgeK1ng** [comment]
This can be closed. Fixed in v1.6 and related mods.
