### ISSUE TITLE
Adding creatures event in town is invalid

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#4760]
**Describe the bug**
This map will add creatures in player3's town. But it is not valid in VCMI Now.

[The Lord of War.zip](https://github.com/user-attachments/files/17342758/The.Lord.of.War.zip)

**Expected behavior**
Add some creatures in town

**Actual behavior**
not happend.

**Version**
 - OS: Windows
 - Version: 1.6 daily build

**Comment by IvanSavenko** [comment]
Duplicate of #4752
