### ISSUE TITLE
"Unicorn Glade" can be built without pre-request of "Dendroid Arches"

### ISSUE THREAD

**Issue by nickhuang99** [vcmi/vcmi#4791]
**Describe the bug**
In original HOMM3, "Unicorn Glade" cannot be built without "Dendroid Arches". 
![unicorn_building_dependency_wrong](https://github.com/user-attachments/assets/009336af-05db-4545-8fd2-293f6bfb72d1)
Even though config file also requires this dependency:

config/factions/rampart.json

`"dwellingLvl6":   { "id" : 35, "requires" : [ "allOf", [ "dwellingLvl3" ], [ "dwellingLvl4" ] ] },`

**Game logs**

**To Reproduce**

**Expected behavior**
"Unicorn Glade" should be "crossed" when "Dendroid Arches" is not built yet.

**Actual behavior**
Instead "Unicorn Glade" shows "slash" which means prerequisite has been met. 

**Did it work earlier?**
not sure.

**Screenshots**

**Version**
 - OS: [Linux/Ubuntu 22.04]
 - Version: [VCMI develop]

**Additional context**

**Comment by nickhuang99** [comment]
![UnicornGladeREquiresDendroidArches](https://github.com/user-attachments/assets/6a1104e9-bbc7-40f7-9962-502c9b99f648)
This screenshot of original HOMM3 game play shows "Unicorn Glade" does requires "Dendroid Arches" as one of its prerequisite. 

So, the suggested bug fix should be change of "faction config" in "rampart.json"(config/factions/rampart.json)

`"dwellingLvl6":   { "id" : 35, "requires" : [ "allOf", [ "dwellingLvl3" ], [ "dwellingLvl4" ], [ "dwellingLvl5" ] ] },`

from 

`"dwellingLvl6":   { "id" : 35, "requires" : [ "allOf", [ "dwellingLvl3" ], [ "dwellingLvl4" ] ] },`

**Comment by Olegmods** [comment]
Can confirm (found the info on MM wiki). But I think that will require some fixes in some of mods.

**Comment by nickhuang99** [comment]
> Can confirm (found the info on MM wiki). But I think that will require some fixes in some of mods.

Not sure why it affects other MOD. But at least my quick fix shows it works.
![Unicorn_Glide_fix](https://github.com/user-attachments/assets/4f55013e-d123-4196-b063-024b6922bc34)

And here is the quick fix: (config/factions/rampart.json)

`"dwellingLvl6":   { "id" : 35, "requires" : [ "allOf", [ "dwellingLvl4" ], [ "dwellingLvl5" ] ] },`

**Comment by Olegmods** [comment]
> > Can confirm (found the info on MM wiki). But I think that will require some fixes in some of mods.
> 
> Not sure why it affects other MOD. But at least my quick fix shows it works. ![Unicorn_Glide_fix](https://private-user-images.githubusercontent.com/3978787/377851296-4f55013e-d123-4196-b063-024b6922bc34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNTE5MTIsIm5iZiI6MTcyOTI1MTYxMiwicGF0aCI6Ii8zOTc4Nzg3LzM3Nzg1MTI5Ni00ZjU1MDEzZS1kMTIzLTQxOTYtYjA2My0wMjRiNjkyMmJjMzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMTE0MDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQxZWRjODJiYjdkMTgwZjY0YWJjNzg2NGQ5MjIzOWE0NDU1ZDk1ZmEwOTc1MmVmN2Q3OGE2ODA5MWQ2NjE3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7TezMCxYFkSY3mQmjDmJiqez4eLvNF6XgjUhO82MvJw)
> 
> And here is the quick fix: (config/factions/rampart.json)
> 
> `"dwellingLvl6": { "id" : 35, "requires" : [ "allOf", [ "dwellingLvl4" ], [ "dwellingLvl5" ] ] },`

It affects Tides of War 100% due to config rewrite, not sure about the other mods.
