### ISSUE TITLE
Incorrect hero animation when army successfully strikes

### ISSUE THREAD

**Issue by mikeiit** [vcmi/vcmi#4800]
**Describe the bug**
Hero has wrong animation when army successfully hits enemy and inflicts damage

**Game logs**
Not seeing relevant log regarding hero animation. 

**To Reproduce**
Start any combat, strike enemy, observe hero's animation

**Expected behavior**
There should be a cheering animation of hero if any stack successfully inflicts damage

**Actual behavior**
Only seeing the disappointment animation, see screenshot

**Did it work earlier?**
Not sure. 

**Screenshots**
![{4C3114C7-333F-402C-BEE2-0D59C384A951}](https://github.com/user-attachments/assets/4b9440e3-5f2b-41cd-a6ed-eb6d383c38ae)

**Version**
 - OS: Windows 11 pro
 - Version: VCMI 1.6, latest code from Oct 18th

**Additional context**
N/A

**Comment by dydzio0614** [comment]
if I remember correctly it was added by AVS as extra feature

**Comment by Olegmods** [comment]
Can confirm. I think it is working in 1.5.7.

**Comment by Whalios** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by mikeiit** [comment]
As of today, this no longer appears.
