### ISSUE TITLE
Interface scaling not working properly

### ISSUE THREAD

**Issue by mikeiit** [vcmi/vcmi#4805]
**Describe the bug**
Automatic interface scaling doesn't work properly. When the setting is on, the scaling percentage says 100%, but it is definitely bigger than that. The difference can be observed after turning automatic option off. 

**Game logs**
Nothing related to scaling.

**To Reproduce**
1. Start VCMI launcher.
2. Go to settings and make sure the automatic scaling is on, which should be by default. 
![{C47E5A04-69DD-4A39-A381-B14DD62D4813}](https://github.com/user-attachments/assets/254dcc07-ccb0-4cb9-bec5-1382c6fd9963)
3. Start game. Observe the scaling. 
4. Quit game. Start the launcher again. Turn the automatic scaling off. (just click the automatic button)
5. Start game again. Observe the scaling.

**Expected behavior**
We should see the same scaling in step 3 and 5. 

**Actual behavior**
Default automatic scaling at 100% is way bigger than non-automatic scaling at 100%.

**Did it work earlier?**
Yes, don't remember the version though. 

**Screenshots**
Automatic scaling in game - 
![{D329B51B-6669-46BD-B93E-38A8AD51D6DF}](https://github.com/user-attachments/assets/efb9fe4e-6620-4997-b86c-92da9a1be009)
Non-automatic scaling in game - 
![{E4578945-07E5-48FB-9FF5-C8B969E6FC97}](https://github.com/user-attachments/assets/d84b6d06-1b8b-42d0-b9e0-43472497eac7)

**Version**
 - OS: Windows 11 Pro
 - Version: VCMI 1.6, latest code from Oct 18th

**Additional context**
N/A

**Comment by mikeiit** [comment]
The scaling itself works fine. But we decided to hide the spin box when automatic is on.

**Comment by nerozero** [comment]
@mikeiit thanks, is the fix already present in the current git version ? 
I had just pulled the latest version and seeing the same scaling issues:

 OS: linux  (should I create a separate bug for the linux platform?)
 Ver: 1.6.0.c2e49bd10a4b6d6abb52edd30d83e9c2a31b5640

this is the actual full screen screenshot, scale: 130%.
![image](https://github.com/user-attachments/assets/a066238b-1f29-48e1-a7f0-4e58c94da8d6)
