### ISSUE TITLE
Translations issues in v1.6

### ISSUE THREAD

**Issue by GeorgeK1ng** [vcmi/vcmi#4809]
Hi, here are few issues that I found during my translation journey for now.

**1)** /translate - WoG znpc00.txt entries are exported to core.json instead of wake-of-gods.json, otherwise looks it works fine. These vcmi.znpc00.(xxx) string can be placed into WoG translation file and they are correctly used

**2)** /translate maps - game crashes even with single mod "kartenarchive" or "hota", so no chance to export maps strings at the moment, it worked in past

**3)** Randomly Generated Map have non translatable description at the moment. Idea is to extend main language json with new strings like:

```
  "vcmi.randomMapDescription.base": "Map created by the Random Map Generator.\nTemplate was %TEMPLATE, size %SIZE, levels %LEVEL, players %PLAYERS, computers %COMPUTERS, water %WATER, monster %THREAT, VCMI map",
  "vcmi.randomMapDescription.humanPlayer": "%COLOR is human",
  "vcmi.randomMapDescription.townChoice": "%COLOR town choice is %TOWN",

  "vcmi.randomMapDescription.waterContent.none": "none",
  "vcmi.randomMapDescription.waterContent.normal": "normal",
  "vcmi.randomMapDescription.waterContent.islands": "islands",

  "vcmi.randomMapDescription.monsterStrength.weak": "weak",
  "vcmi.randomMapDescription.monsterStrength.normal": "normal",
  "vcmi.randomMapDescription.monsterStrength.strong": "strong",
```

And then modify getMapDescription() into something like this, to make it translatable aswell and make whole GUI localizable
```

std::string CMapGenerator::getMapDescription() const
{
    assert(map);

    // Keep the water and monster strength arrays
    const std::string waterContentStr[3] = {
        VLC->generaltexth->translate("vcmi.randomMapDescription.waterContent.none"),
        VLC->generaltexth->translate("vcmi.randomMapDescription.waterContent.normal"),
        VLC->generaltexth->translate("vcmi.randomMapDescription.waterContent.islands")
    };

    const std::string monsterStrengthStr[3] = {
        VLC->generaltexth->translate("vcmi.randomMapDescription.monsterStrength.weak"),
        VLC->generaltexth->translate("vcmi.randomMapDescription.monsterStrength.normal"),
        VLC->generaltexth->translate("vcmi.randomMapDescription.monsterStrength.strong")
    };

    int monsterStrengthIndex = mapGenOptions.getMonsterStrength() - EMonsterStrength::GLOBAL_WEAK; // Adjust for non-zero start
    const auto* mapTemplate = mapGenOptions.getMapTemplate();

    if (!mapTemplate)
        throw rmgException(VLC->generaltexth->translate("vcmi.randomMapDescription.error.mapTemplateNotFound"));

    // Fetch the base description string from JSON
    std::string mapDescription = VLC->generaltexth->translate("vcmi.randomMapDescription.base");

    // Replace the placeholders with actual values
    boost::replace_first(mapDescription, "%TEMPLATE", mapTemplate->getName());
    boost::replace_first(mapDescription, "%SIZE", std::to_string(map->width()) + "x" + std::to_string(map->height()));
    boost::replace_first(mapDescription, "%LEVEL", std::to_string(static_cast<int>(map->levels())));
    boost::replace_first(mapDescription, "%PLAYERS", std::to_string(static_cast<int>(mapGenOptions.getHumanOrCpuPlayerCount())));
    boost::replace_first(mapDescription, "%COMPUTERS", std::to_string(static_cast<int>(mapGenOptions.getCompOnlyPlayerCount())));
    boost::replace_first(mapDescription, "%WATER", waterContentStr[mapGenOptions.getWaterContent()]);
    boost::replace_first(mapDescription, "%THREAT", monsterStrengthStr[monsterStrengthIndex]);

    // Append player information
    for (const auto& pair : mapGenOptions.getPlayersSettings())
    {
        const auto& pSettings = pair.second;
        if (pSettings.getPlayerType() == EPlayerType::HUMAN)
        {
            std::string humanPlayer = VLC->generaltexth->translate("vcmi.randomMapDescription.humanPlayer");
            boost::replace_first(humanPlayer, "%COLOR", GameConstants::PLAYER_COLOR_NAMES[pSettings.getColor().getNum()]);
            mapDescription += ", " + humanPlayer;
        }
        if (pSettings.getStartingTown() != FactionID::RANDOM)
        {
            std::string townChoice = VLC->generaltexth->translate("vcmi.randomMapDescription.townChoice");
            boost::replace_first(townChoice, "%COLOR", GameConstants::PLAYER_COLOR_NAMES[pSettings.getColor().getNum()]);
            boost::replace_first(townChoice, "%TOWN", (*VLC->townh)[pSettings.getStartingTown()]->getNameTranslated());
            mapDescription += ", " + townChoice;
        }
    }

    return mapDescription;
}
```

**Comment by GeorgeK1ng** [comment]
Found another one issue here. It should be here **Flügelové** but **ü** is ignored. In right click works correctly
![image](https://github.com/user-attachments/assets/e1f48c6c-d8b7-4ad7-98e6-be88aae4307e)
![image](https://github.com/user-attachments/assets/dcb3723f-401f-4920-9cc6-d841ea073e84)

**Comment by GeorgeK1ng** [comment]
5) Strings from mod vcmi-extras -> quickExchange, are not extracted and text is only in english. Like "Move unit to the right", "Swap armies" etc. in exchangeWindow.json

**Comment by IvanSavenko** [comment]
> Found another one issue here. It should be here Flügelové but ü is ignored. In right click works correctly

Try replacing `bigfont.fnt` in Czech translation with one from Polish translation mod / Polish edition from gog.com

This font is corrupted in English H3 version - some of diacritics characters are either broken or empty.

**Comment by GeorgeK1ng** [comment]
> > Found another one issue here. It should be here Flügelové but ü is ignored. In right click works correctly
> 
> Try replacing `bigfont.fnt` in Czech translation with one from Polish translation mod / Polish edition from gog.com
> 
> This font is corrupted in English H3 version - some of diacritics characters are either broken or empty.

I can try. I’m already using game with original Czech game files. Fonts included. Will check If font in Czech translation mod have correct file.

**Comment by IvanSavenko** [comment]
Ah, font is not the same as in English version. But still looks to be incomplete.
I see only capital ü in bigfont, but both in medfont and others.

Just in case - can you check whether this symbol is present in original translation for H3? Find/create map with this symbol, select in scenario selection, check map name in top-right - H3 uses bigfont in there for map names

Here is bigfont + medfont for comparison, exported using vcmi:
![BIGFONT](https://github.com/user-attachments/assets/3875371d-5f08-479e-ae8b-67461bc0eb23)
![MEDFONT](https://github.com/user-attachments/assets/5c335cf4-be08-415d-aed8-b99f93d7cdc8)

**Comment by GeorgeK1ng** [comment]
I’m going to inspect Czech fnt files tonight. I have some H3 font editors archived. Maybe I can fix missing entries.
