### ISSUE TITLE
Modding/Adventure Map: Obstacle shadow still displays its original color

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#4810]
**Describe the bug**
Obstacle shadows in battlefield still displays its original color, especially in lava and highlands.

**Expected behavior**
Shadows should not display pink color.

**Actual behavior**
Pink color displays.

**Did it work earlier?**
It worked well in 1.5.7.

**Screenshots**
![image](https://github.com/user-attachments/assets/2eb2c103-3173-41bc-88cc-4b45633efbc4)
![image](https://github.com/user-attachments/assets/2997cd21-0de9-4b51-b3e9-0a6af171d04c)
Same condition in university screen.
![image](https://github.com/user-attachments/assets/2ec90990-9e9d-4889-b1d9-6bcb4fe29d83)

**Version**
 - OS: Windows
 - Version: 1.60

**Additional context**
Not sure if it is the same problem with [#4771 ](https://github.com/vcmi/vcmi/issues/4771
)

**Comment by Whalios** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by by003** [comment]
This problem and #4771 is still not be fixed.
@IvanSavenko please mention about this...some of players are making videos for VCMI and it might affect the impressions.
The similar problem occured last year is in pull request #2207. This file changes a lot since last year.
