### ISSUE TITLE
VCMI 1.5.7 is completely frozen on MacOS Sonoma

### ISSUE THREAD

**Issue by GorgonUK** [vcmi/vcmi#4811]
**Describe the bug**
I started a new game and then shortly after I clicked "Save Game" from the menu, the game crashed. Bummer!

**Game logs**
[VCMI_Client_log.txt](https://github.com/user-attachments/files/17467422/VCMI_Client_log.txt)

**To Reproduce**
1. Create a new Single Player game
2. Select "Random map"
3. Set 3 AIs and 1 Human player
4. Once you're in the game, select menu
5. Click "Save Game"

**Expected behavior**
I expect the game to save when you click "Save Game"

**Actual behavior**
The app becomes unresponsive and only "Force Close" stops it

**Did it work earlier?**
I believe it has worked fine with previous version of VCMI

**Screenshots**
When I click "Save Game" the game freezes
![CleanShot 2024-10-21 at 11  19 02](https://github.com/user-attachments/assets/deab2754-9c84-424b-8aab-c9a5b015c9c8)

**Version**
 - OS: MacOS Sonoma 14.6.1
 - Version: 1.5.7

**Additional Notes**
My macbook is connected to an external 1080p monitor and when I launched the game, I dragged it over to the external monitor.

**Comment by kambala-decapitator** [comment]
haven't seen such issues on Sonoma. Please test the latest [daily build](https://download.vcmi.eu/branch/develop/macOS/), as 1.5.x won't receive any updates any more.

> My macbook is connected to an external 1080p monitor and when I launched the game, I dragged it over to the external monitor.

please try selecting the monitor you want in launcher settings instead of dragging window, maybe that helps

**Comment by GorgonUK** [comment]
> daily build

I tried [VCMI-branch-develop-c25aef8](https://download.vcmi.eu/branch/develop/macOS/arm/VCMI-branch-develop-c25aef8.dmg) and it worked. It's not crashing on save anymore.

**Comment by kambala-decapitator** [comment]
Great, thanks! Let's close the issue then.
