### ISSUE TITLE
Vmap format sometimes duplicates spells in mage guilds 

### ISSUE THREAD

**Issue by val-gaav** [vcmi/vcmi#4813]
**Describe the bug**
When mage guilds are build right from the game start on vmap (towns are edited with vcmi mapeditor to have all 5 level mage guild build) it seems spells sometimes get duplicated. I don't know if this is only vmap problem but with some tests I was unable to reproduce this on h3m.  I also turned off all mods beside vcmiessentials and vcmiextras to check whether this is a mod issue, and it is not.

I also have not tested if this would work with not build mage guild from start, however I never got this while playing vcmi random maps. 

**To Reproduce**
attached vmap has towns with mage guilds . Load it and some of the spells in one of the towns should be duplicated. It is a map with Tower town, but it happens for all towns so library is not the source of problem. 

**Expected behavior**
spells should not duplicate in mage guild

**Version**
 - OS: Linux kubuntu 24.04
 - Version: [VCMI version] 1.5.7

**Comment by val-gaav** [comment]
![Screenshot_20241022_141434](https://github.com/user-attachments/assets/bbd5384f-1a2e-437d-bb8b-2bed9dde14f4)
![Screenshot_20241022_141422](https://github.com/user-attachments/assets/ccd2706a-ee3f-42ca-b2fd-2dee3841f3de)

**Comment by val-gaav** [comment]
Vmap and logs :
[logs_and_vmap.zip](https://github.com/user-attachments/files/17476205/logs_and_vmap.zip)

**Comment by wb180** [comment]
If you extract objects.json from the vmap, you will see duplicated spells in town object

```json
			"possibleSpells" : [
				"core:summonBoat",
				"core:scuttleBoat",
				"core:visions",
				"core:viewEarth",
				"core:disguise",
				"core:viewAir",
				"core:fly",
				"core:waterWalk",
				"core:dimensionDoor",
				"core:townPortal",
				"core:quicksand",
				"core:landMine",
				"core:forceField",
				"core:fireWall",
				"core:earthquake",
				"core:magicArrow",
				"core:iceBolt",
				"core:lightningBolt",
				"core:implosion",
				"core:chainLightning",
				"core:frostRing",
				"core:fireball",
				"core:inferno",
				"core:meteorShower",
				"core:deathRipple",
				"core:destroyUndead",
				"core:armageddon",
				"core:shield",
				"core:airShield",
				"core:fireShield",
				"core:protectAir",
				"core:protectFire",
				"core:protectWater",
				"core:protectEarth",
				"core:antiMagic",
				"core:dispel",
				"core:magicMirror",
				"core:cure",
				"core:resurrection",
				"core:animateDead",
				"core:sacrifice",
				"core:bless",
				"core:curse",
				"core:bloodlust",
				"core:precision",
				"core:weakness",
				"core:stoneSkin",
				"core:disruptingRay",
				"core:prayer",
				"core:mirth",
				"core:sorrow",
				"core:fortune",
				"core:misfortune",
				"core:haste",
				"core:slow",
				"core:slayer",
				"core:frenzy",
				"core:counterstrike",
				"core:berserk",
				"core:hypnotize",
				"core:forgetfulness",
				"core:blind",
				"core:teleport",
				"core:removeObstacle",
				"core:clone",
				"core:fireElemental",
				"core:earthElemental",
				"core:waterElemental",
				"core:airElemental",
				"core:summonBoat",
				"core:scuttleBoat",
				"core:visions",
				"core:viewEarth",
				"core:disguise",
				"core:viewAir",
				"core:fly",
				"core:waterWalk",
				"core:dimensionDoor",
				"core:townPortal",
				"core:quicksand",
				"core:landMine",
				"core:forceField",
				"core:fireWall",
				"core:earthquake",
				"core:magicArrow",
				"core:iceBolt",
				"core:lightningBolt",
				"core:implosion",
				"core:chainLightning",
				"core:frostRing",
				"core:fireball",
				"core:inferno",
				"core:meteorShower",
				"core:deathRipple",
				"core:destroyUndead",
				"core:armageddon",
				"core:shield",
				"core:airShield",
				"core:fireShield",
				"core:protectAir",
				"core:protectFire",
				"core:protectWater",
				"core:protectEarth",
				"core:antiMagic",
				"core:dispel",
				"core:magicMirror",
				"core:cure",
				"core:resurrection",
				"core:animateDead",
				"core:sacrifice",
				"core:bless",
				"core:curse",
				"core:bloodlust",
				"core:precision",
				"core:weakness",
				"core:stoneSkin",
				"core:disruptingRay",
				"core:prayer",
				"core:mirth",
				"core:sorrow",
				"core:fortune",
				"core:misfortune",
				"core:haste",
				"core:slow",
				"core:slayer",
				"core:frenzy",
				"core:counterstrike",
				"core:berserk",
				"core:hypnotize",
				"core:forgetfulness",
				"core:blind",
				"core:teleport",
				"core:removeObstacle",
				"core:clone",
				"core:fireElemental",
				"core:earthElemental",
				"core:waterElemental",
				"core:airElemental"
			]
```

It leads to possible duplication in game. But I was unable to find out a sequence of actions in editor, which creates such kind of duplication, tried on current develop and 1.5.7.

**Comment by godric3** [comment]
Manage to reproduce it by copy pasting town, after paste it have additional spells in possibleSpells, copying and pasting such town create new one with 3x each spell in possibleSpells...
So it's possible to create town with chance for 6x slow :D 

Just opening town spells widget should fix it for existing town with this problem

**Comment by godric3** [comment]
And editor always show warning what pasting anything...

**Comment by val-gaav** [comment]
Yes I can confirm towns were copied to make a test map by me . I always did the same with original editor so it is something I was used to and expected it to work in vcmi editor too. 

Just tested it and towns spells indeed do not duplicate when towns are made from scratch and not copied. 

BTW. Editor in KDE / linux shows no warnings for me when using ctrl+c  and ctrl+v . Editor is v.0.2 .

**Comment by godric3** [comment]
Yeah it should be fixed, will look into it over the weekend.
Warning may be something that is only on current develop and not in latest release.
And editor version... we should remove that and just use regular VCMI versioning
