### ISSUE TITLE
If a hero knows banned secondary skill, it is offered only as last option

### ISSUE THREAD

**Issue by Daar543** [vcmi/vcmi#4814]
**Describe the bug**
A code implementation clashes with the description in the original game. The [Tribute to Strategists](http://heroes3wog.net/download/%5BManual%5D%20Tribute%20to%20Strategists.pdf) says on Page 7: 
"If a hero possesses a skill normally unattainable save if born with, or learned through Witch Hut and
Scholar (e.g. Water Magic for Barbarians) then his chances of advancement in that skill will be the
minimal possible (that is, they equal 1 according to the table above)."

I have not checked VCMI, but I have only examined your code to understand the actual implementation (namely, how exactly the guaranteed school of magic works, if only 1 is guaranteed to appear at the new skill slot, or 2 are guaranteed) and went on to check this. The relevant piece of code is at file CHeroClass.cpp, lines 22/34/35:
```
SecondarySkill CHeroClass::chooseSecSkill(const std::set<SecondarySkill> & possibles, vstd::RNG & rand) const //picks secondary skill out from given possibilities {
        // other code
	for(const auto & possible : possibles)
		if (secSkillProbability.count(possible) != 0)
			totalProb += secSkillProbability.at(possible);

	if (totalProb == 0) // may trigger if set contains only banned skills (0 probability)
		return *RandomGeneratorUtil::nextItem(possibles, rand);
       //other code
}
```
So unless the secondary skill probabilities change by some hack like setting new skill probability to 1 at least (which I have not found, as I suppose this table is global across all heroes of this class in the source code implementation), it will never offer the advancement skill as chosen by weighted random.

Yet when I assigned my Death Knight Estates in the original game and did some level-up, I got offered Estates sooner, despite having Pathfinding unmaxxed - see screenshots.
I have not checked the probabilities by rigorous restarts, but it should probably make you check your implementation to at least give the skill some basic chance.

**Game logs**
None

**To Reproduce**
1. Create a hero with banned secondary skill for its class (e.g. Estates from Pandora's box on Death Knight)
2. Level-up the hero
3. Restart the game as many times as you want
4. The hero is always offered Necromancy as skill advancement, never Estates

**Expected behavior**
The chance of learning the banned skill should be small, but never impossible unless it is a last skill to upgrade. This is as written in 

**Actual behavior**
The skill is never offered unless forced

**Did it work earlier?**
I did not check the actual probabilities, but the skill was offered earlier to me in the original game.

**Screenshots**
![isra_1](https://github.com/user-attachments/assets/67cd7cb6-948f-4c1b-9ae3-f2d7f975d563)
![isra_2](https://github.com/user-attachments/assets/adbd539d-6f56-4f29-84c9-453e611f7bc9)

**Version**
 - OS: Windows

**Additional context**
I have not downloaded nor played the VCMI so maybe it works as intended in there, just I doubt it from the source code.

**Comment by Whalios** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Olegmods** [comment]
> **Describe the bug** A code implementation clashes with the description in the original game. The [Tribute to Strategists](http://heroes3wog.net/download/%5BManual%5D%20Tribute%20to%20Strategists.pdf) says on Page 7: "If a hero possesses a skill normally unattainable save if born with, or learned through Witch Hut and Scholar (e.g. Water Magic for Barbarians) then his chances of advancement in that skill will be the minimal possible (that is, they equal 1 according to the table above)."
> 
> I have not checked VCMI, but I have only examined your code to understand the actual implementation (namely, how exactly the guaranteed school of magic works, if only 1 is guaranteed to appear at the new skill slot, or 2 are guaranteed) and went on to check this. The relevant piece of code is at file CHeroClass.cpp, lines 22/34/35:
> 
> ```
> SecondarySkill CHeroClass::chooseSecSkill(const std::set<SecondarySkill> & possibles, vstd::RNG & rand) const //picks secondary skill out from given possibilities {
>         // other code
> 	for(const auto & possible : possibles)
> 		if (secSkillProbability.count(possible) != 0)
> 			totalProb += secSkillProbability.at(possible);
> 
> 	if (totalProb == 0) // may trigger if set contains only banned skills (0 probability)
> 		return *RandomGeneratorUtil::nextItem(possibles, rand);
>        //other code
> }
> ```
> 
> So unless the secondary skill probabilities change by some hack like setting new skill probability to 1 at least (which I have not found, as I suppose this table is global across all heroes of this class in the source code implementation), it will never offer the advancement skill as chosen by weighted random.
> 
> Yet when I assigned my Death Knight Estates in the original game and did some level-up, I got offered Estates sooner, despite having Pathfinding unmaxxed - see screenshots. I have not checked the probabilities by rigorous restarts, but it should probably make you check your implementation to at least give the skill some basic chance.
> 
> **Game logs** None
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create a hero with banned secondary skill for its class (e.g. Estates from Pandora's box on Death Knight)
> 2. Level-up the hero
> 3. Restart the game as many times as you want
> 4. The hero is always offered Necromancy as skill advancement, never Estates
> 
> **Expected behavior** The chance of learning the banned skill should be small, but never impossible unless it is a last skill to upgrade. This is as written in
> 
> **Actual behavior** The skill is never offered unless forced
> 
> **Did it work earlier?** I did not check the actual probabilities, but the skill was offered earlier to me in the original game.
> 
> **Screenshots** ![isra_1](https://private-user-images.githubusercontent.com/56161386/379021743-67cd7cb6-948f-4c1b-9ae3-f2d7f975d563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODI5OTUsIm5iZiI6MTczMTA4MjY5NSwicGF0aCI6Ii81NjE2MTM4Ni8zNzkwMjE3NDMtNjdjZDdjYjYtOTQ4Zi00YzFiLTlhZTMtZjJkN2Y5NzVkNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDE2MTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZWZmNmY4YzY0NDA0MTJkOTFkMjJjMjFmZjA5OGRmMjdmNTQ1MDE1ZmIzNGM0YWM2OWNjYjM0MWUxNjQyMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Qulj6hQd0WATReG_kgUJlGB13FRPXxv5Ug-wmBi3E5g) ![isra_2](https://private-user-images.githubusercontent.com/56161386/379021748-adbd539d-6f56-4f29-84c9-453e611f7bc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODI5OTUsIm5iZiI6MTczMTA4MjY5NSwicGF0aCI6Ii81NjE2MTM4Ni8zNzkwMjE3NDgtYWRiZDUzOWQtNmY1Ni00ZjI5LTg0YzktNDUzZTYxMWY3YmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDE2MTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNDFmN2FjZjVlY2Q4NjczMzVlZGUwYjljZDA4ZWY5Y2M4ZGE5NTQ2YjBhMzA2NDliMDc5OTY5OTczNWEwNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ltPozM7kAEUy8ZVdFm7zW0zUq_XboN0m_52-5nw2z8A)
> 
> **Version**
> 
> * OS: Windows
> 
> **Additional context** I have not downloaded nor played the VCMI so maybe it works as intended in there, just I doubt it from the source code.

Seems you're wrong. Tested my mod with a hero with banned skill for that hero's class (Necromancy), and I was able to get it like on level 5 of the hero. (VCMI 1.5.7)

I guess the issue should be closed.
