### ISSUE TITLE
Is there a chance of Homebrew-Cask (Package Manager for macOS)?

### ISSUE THREAD

**Issue by albertogarciacz** [vcmi/vcmi#4818]
I recently installed VCMI on my MacOs computer. So as usually I searched the brew cask repository, but couldn't find VCMI there, so I had to manually download the dmg and install it. Do you think there is a chance to create the formula in brew (https://brew.sh)?

**Comment by kambala-decapitator** [comment]
Shouldn't be a big deal

**Comment by Whalios** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by kambala-decapitator** [comment]
brew install --cask --no-quarantine vcmi/vcmi/vcmi

**Comment by kambala-decapitator** [comment]
FYI VCMI is now an official Homebrew cask: `brew install --cask vcmi`

@albertogarciacz @Accademia @GorgonUk

**Comment by albertogarciacz** [comment]
Great news 🙌
