### ISSUE TITLE
Commander section display is messed up upon scrolling

### ISSUE THREAD

**Issue by mikeiit** [vcmi/vcmi#4828]
**Describe the bug**
Open up the commander section of a hero and scroll in the commander section, the display gets messed up. See screenshot.

**Game logs**
N/A

**To Reproduce**
Same as description.

**Expected behavior**
Scrolling shouldn't be allowed in commander section IMO.

**Actual behavior**
Player can scroll and the display is messed up. 

**Did it work earlier?**
Not sure.

**Screenshots**
![{C3438732-9BEF-4BFA-949A-60C05205B328}](https://github.com/user-attachments/assets/eb9e9949-2b6d-4918-860c-1e07d3a69b27)

**Version**
 - OS: Windows 11 Pro
 - Version: VCMI 1.6, latest code from Oct 25th

**Additional context**
This happened rather late in the game play when the commander gained a lot of skills already. Not sure if it is an issue in the beginning of the game.

**Comment by Whalios** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by mikeiit** [comment]
As of today, this issue no longer appears.
