### ISSUE TITLE
Lack of support Simplified Chinese suport

### ISSUE THREAD

**Issue by nickhuang99** [vcmi/vcmi#4835]
**Describe your proposal**
HOMM3 published a large amount of copies of Simplified Chinese version in last century of encoding of GBK. It is a pity to not  to include the huge number of players along with tons of player-defined maps.

The support for both UI and maps are almost there except:

1.  What prevents UI to display Chinese fonts? Default fonts ["NotoSerif-XXX.ttf](https://en.wikipedia.org/wiki/Noto_fonts#List_of_Noto_fonts)" family is not for GBK or simplified Chinese(Search for **Noto Serif SC**).  So, in order to truly support Simplified Chinese, default fonts should be **[Noto Serif SC](https://fonts.google.com/download/next-steps?lang=zh_Hans)** which can be [downloaded](https://fonts.google.com/share?selection.family=Noto+Serif+KR:wght@200..900|Noto+Serif+SC:wght@200..900|Noto+Serif:ital,wght@0,100..900;1,100..900) freely from **fonts.google.com**.
(see details config in **config/fonts.json**) 
**Please note**: English is still supported in this fonts. So roughly speaking,  **Noto Serif  SC** is like a super set of current **Noto Serif** .

2. What prevents from maps with GBK encoding to be displayed properly? Current language selection is sticking to "**Mod**" language option which is always English. 

For example, **CMapService::loadMap** will always choose English for map language:

`std::string language = VLC->modh->getModLanguage(modName);`

Here we can change to launcher's settings of user choice. i.e.

`std::string language = VLC->generaltexth->getPreferredLanguage();`

Here is a screen recording of what effect looks like of both displaying Chinese fonts in UI and maps.

https://github.com/user-attachments/assets/b247a628-4d14-4560-b61f-def5fafcb011

**Additional context**

**Comment by IvanSavenko** [comment]
> * What prevents UI to display Chinese fonts? Default fonts ["NotoSerif-XXX.ttf](https://en.wikipedia.org/wiki/Noto_fonts#List_of_Noto_fonts)" family is not for GBK or simplified Chinese(Search for **Noto Serif SC**).  

1. Noto Serif SC is HUGE. 60 Mb uncompressed, 30 Mb compressed. This would double download size and install size for *everyone*, whether they are Chinese or not.
2. There is already mod named "Chinese Translation" (or something like that) which provides similar fonts. As long as this mod is marked as translation to Chinese VCMI will offer installing it on first launch.
3. These fonts only come in a single form, fonts used by VCMI were selected to match H3 fonts as much as possible (e.g. NotoSans-Medium / NotoSerif-Black)

> * What prevents from maps with GBK encoding to be displayed properly? Current language selection is sticking to "**Mod**" language option which is always English.

No it is not.
1. If mod is marked as `"language" : "chinese"` all maps from that mod will be loaded using GBK encoding
2. If VCMI detects that H3 data files in Chinese, then `modLanguage` will be Chinese and all files (.txt's and .h3m's) in base game will be loaded with GBK encoding

**Comment by Whalios** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by IvanSavenko** [comment]
> I downloaded "chinese-translation" Mod and the fonts are wonderful, it must be originally used by Chinese version of HOMM3. This is a wonderful solution for UI fonts.

Not sure where that font or mod came from, but as far as I know it was made by Chinese community, so I assume that they selected fonts that should look well for Chinese.

> However, I noticed the "Chinese-GBK-encoded-map" are NOT displayed as expected. Indeed, the language is decided by language of "Mod". However, unless maps are provided by this "Chinese Mod", there is no way to setup language as Chinese.

For mods idea is, that if mod provides non-English h3m maps, mod must set `"language" : "chinese"` (or whatever language of maps is) and vcmi will use this language to determine encoding of h3m maps.

I assume you have English version of Heroes 3, and placed own (or downloaded) h3m maps into Maps directory of Heroes 3? Am I correct? This particular scenario is not handled well at the moment, true.

Need to think how can we handle it better. Ideal solution would have been to detect encoding of h3m map and use it to load the map. 

One option that we can try is to use either preferred language or install language. If English is one of these two languages, then we can safely use second one (in your case Chinese). After all, both GBK and all Win-125X encoding are superset of ASCII, so English map will always load up correctly. If both languages are non-English then things become more complex, but hopefully this is rather rare scenario.

**Comment by nickhuang99** [comment]
> > I downloaded "chinese-translation" Mod and the fonts are wonderful, it must be originally used by Chinese version of HOMM3. This is a wonderful solution for UI fonts.
> 
> Not sure where that font or mod came from, but as far as I know it was made by Chinese community, so I assume that they selected fonts that should look well for Chinese.

The [chinese-translation mod](https://github.com/vcmi-mods/chinese-translation/blob/vcmi-1.6/chinese-translation/mods/ChineseTrueTypeFonts/mod.json)  is showing my name as author. Believe me, I have such bad memory that I don't remember I placed mod there and I even forgot what I have done a couple of years ago. (Probably it is a trivial bug fixing work). I checked my old journal and have no clue where I downloaded truetype fonts from. I guess it is really irrelevant as original Chinese HOMM3 version is using bitmap fonts which is unsuitable for vcmi to be using. Do we still support bitmap fonts?


> 
> > However, I noticed the "Chinese-GBK-encoded-map" are NOT displayed as expected. Indeed, the language is decided by language of "Mod". However, unless maps are provided by this "Chinese Mod", there is no way to setup language as Chinese.
> 
> For mods idea is, that if mod provides non-English h3m maps, mod must set `"language" : "chinese"` (or whatever language of maps is) and vcmi will use this language to determine encoding of h3m maps.
> 
> I assume you have English version of Heroes 3, and placed own (or downloaded) h3m maps into Maps directory of Heroes 3? Am I correct? This particular scenario is not handled well at the moment, true.
> 
You are correct! I am using GOG repacked English version for Linux because original Chinese game version lacks support of HOMM3 HD launcher which fixes a lot bugs and improves a lot. And I have collected hundreds of Chinese maps of  GBK-encoding and placed them under maps directory of H3. It has troubled me for years to not being able to read scenario and message text of Chinese of maps because some of them are crucial to complete tasks. Now I am happy VCMI provides a good approach to play. :)

> Need to think how can we handle it better. Ideal solution would have been to detect encoding of h3m map and use it to load the map.
> 
> One option that we can try is to use either preferred language or install language. If English is one of these two languages, then we can safely use second one (in your case Chinese). After all, both GBK and all Win-125X encoding are superset of ASCII, so English map will always load up correctly. If both languages are non-English then things become more complex, but hopefully this is rather rare scenario.

This is a complex question because whatever language player has setup the maps language could be independent. At least for me, I search all kinds of maps from internet and download to play. There are quite some foreign language for my game version, i.e. Russian, Danish, Korean etc.  So, I agree the ideal solution is to detect the encoding of maps by using a library like [libchardet](https://github.com/Joungkyun/libchardet).  I know it is not that easy and need some experiment to see if it is doable. Maybe I can start some test from encoding of text in CMapHeader?

> > I downloaded "chinese-translation" Mod and the fonts are wonderful, it must be originally used by Chinese version of HOMM3. This is a wonderful solution for UI fonts.
> 
> Not sure where that font or mod came from, but as far as I know it was made by Chinese community, so I assume that they selected fonts that should look well for Chinese.
> 
> > However, I noticed the "Chinese-GBK-encoded-map" are NOT displayed as expected. Indeed, the language is decided by language of "Mod". However, unless maps are provided by this "Chinese Mod", there is no way to setup language as Chinese.
> 
> For mods idea is, that if mod provides non-English h3m maps, mod must set `"language" : "chinese"` (or whatever language of maps is) and vcmi will use this language to determine encoding of h3m maps.
> 
> I assume you have English version of Heroes 3, and placed own (or downloaded) h3m maps into Maps directory of Heroes 3? Am I correct? This particular scenario is not handled well at the moment, true.
> 
> Need to think how can we handle it better. Ideal solution would have been to detect encoding of h3m map and use it to load the map.
> 
> One option that we can try is to use either preferred language or install language. If English is one of these two languages, then we can safely use second one (in your case Chinese). After all, both GBK and all Win-125X encoding are superset of ASCII, so English map will always load up correctly. If both languages are non-English then things become more complex, but hopefully this is rather rare scenario.
