### ISSUE TITLE
Autosave naming of files/directiry

### ISSUE THREAD

**Issue by nerozero** [vcmi/vcmi#4846]
**Describe your proposal**
It is quite confusing to navigate and find last saved/autosaved games in in-game interface. Sorting by date doesn't seems to effect the directory names. When the amount of saved maps grows finding a proper directory for recently played games is very annoying. The game is hiding somewhere in the middle of the alpha-sorted list, which requires to read all unaligned timstamps, which is quite painful.

Will it be nicer to use already existed sorting and place the timestamp in front of the map name, and align them to the left. All timestamp has same width, so that will ensure that each timestamp will be placed one below another, which makes ease to compare specific timestamp part (eg specific date, time, ... ) by eye.

Will it be possible to change the naming format of the directory of saved game to :
- "%Y-%m-%d-%H-%M \<name of the map\>" 
or
- "%Y-%m-%d %H-%M \<name of the map>\" 
or
- "%Y%m%d%H%M \<name of the map>\" 

It should be very easy to do and will ensure all saves are sorted by date ASC, and it make a lot easier to navigate to the latest saves regardless of map name: 

- Original
![image](https://github.com/user-attachments/assets/b356615f-e695-4d2d-a551-34d77b4f8515)
- Timestam in front without spaces
![image](https://github.com/user-attachments/assets/6b7881ad-6789-4383-8ae5-8d603630911b)
- Timestam in front with spaces
![image](https://github.com/user-attachments/assets/5228bcd0-8ef8-47d6-abbf-1f51809e16c1)

**Comment by GeorgeK1ng** [comment]
+1

**Comment by krs0** [comment]
This would improve things a little, but why not follow HD mod's already field tested approach?

Made an attempt some time ago, but was deemed overcomllicated. Maybe another not so comllicated take on it? Because I think addresses many other problems that could not be solved only by date prepending.

https://github.com/vcmi/vcmi/issues/2561

**Comment by nerozero** [comment]
@krs0 I guess the keyword is 'overcomplicated'.

in my case there only a single line of code to be changed in a https://github.com/vcmi/vcmi/blob/3a45e6dae13317afeb4b4e4fc8427dc79d267335/client/CPlayerInterface.cpp#L252

I haven`t found where the alignment of the text is done yet, but ,my guess that also shouldn't be difficult.

**Comment by nerozero** [comment]
hah someone did that already? 
yesterday I was a little bit busy to post reply but here is my changes. [My forked](https://github.com/vcmi/vcmi/compare/develop...nerozero:vcmi:develop#diff-fd3913fd521457db9f9191a4011d031dd70aefa40c6fafc2e9c4be96f73d681d)
![image](https://github.com/user-attachments/assets/ccc9e06b-1d7e-436c-82b1-f46db41d0738)

I have introduced the spaces in the directory names, IDK if this is acceptable, but for game on linux machine it was ok, no issues with save/load

I spend a lot of time finding where can I change the directory listing text alignment, but failed ...  so ...
Can I ask for a pull request?

**Comment by Laserlicht** [comment]
Yeah. Not really complicated for me because I introduced much of the code for folder stuff.

My Pull request is linked above your comment.

I would still avoid spaces in file and folder names. I works in most cases. But there may some edge cases in operating systems or external programs that could cause problems.
