### ISSUE TITLE
V1.6 Freeze in map selection when hit Back button

### ISSUE THREAD

**Issue by GeorgeK1ng** [vcmi/vcmi#4863]
Latest VCMI v1.6 freezes when you are on maps selection screen and want to go back to main menu.

When try to click inside VCMI window, then game crash. No dmp generated.

It's just VCMI + GOG Files + Czech translation mod

![image](https://github.com/user-attachments/assets/43714456-2a87-4c24-897a-997c59587b35)
![image](https://github.com/user-attachments/assets/eea42c00-0002-4879-b3de-e42b972580ab)
![image](https://github.com/user-attachments/assets/97cbc71d-5351-409e-91ef-358e5873a7b3)
![image](https://github.com/user-attachments/assets/3affd442-04cf-4c48-a20d-2dc5dc5e6086)
![image](https://github.com/user-attachments/assets/06129f61-c174-4d79-9e74-6ed8a205eddb)

[VCMI_Client_log.txt](https://github.com/user-attachments/files/17607075/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/user-attachments/files/17607077/VCMI_Launcher_log.txt)

**Comment by GeorgeK1ng** [comment]
Same issue was reported here: https://github.com/vcmi/vcmi/issues/4795

**Comment by MichalZr6** [comment]
I can't see the Call Stack when pausing during the freeze but it seems like SDLAudioP2 Thread is running.
![obraz](https://github.com/user-attachments/assets/2002deca-1989-4fa9-8a6b-afc31ee424be)

**Comment by krs0** [comment]
Observed something similar, if I let intro video start.

**Comment by GeorgeK1ng** [comment]
Confirmed to be fixed with https://github.com/vcmi/vcmi/pull/4983
