### ISSUE TITLE
Heroes of Might and Magic 3 Bug for Multiple Player Hot Seat

### ISSUE THREAD

**Issue by HMM3WORSTPLAYER** [vcmi/vcmi#4869]
**Describe the bug**
On a Multiple Player mode with Hot Seat, in a scenario with allies, once all enemies are defeated instead of getting the Victory screen the game gets stuck.

**Game logs**
I don't know where to find them.

**To Reproduce**
1. Choose 'Multiple Player'
2. Choose 'Hot Seat'
3. Choose a scenario with allies
4. Defeat all enemies.

**Expected behavior**
I would have expected to see the Victory screen.

**Actual behavior**
The game gets stuck.

**Did it work earlier?**
No idea, it was the first time I reached a victory in Multiple Player mode.

**Screenshots**

**Version**
 - OS: Windows
 - Version: No idea, didn't find any Help > About to see what version I'm running.

**Additional context**

**Comment by HMM3WORSTPLAYER** [comment]
Hi:

> Hi. Can you tell:
> 
> * which players were human and which were AI's?
> * which players were allied to each other?
> * was the last player to be defeated human or AI?
> * how was last player defeated? Lost his last hero on his turn? Another player killed last hero / captured last town? Or he was defeated by not having a town for a week?

Well:
* I played all roles (Did it to get to know the game and train a bit)
* Allies were Red-Tile-Blue against Green-Orange-Purple
* Again, all human
* Defeated by losing both last hero and town at the same battle

**Comment by kambala-decapitator** [comment]
> Version: No idea, didn't find any Help > About to see what version I'm running.

Open Help tab in the launcher

**Comment by HMM3WORSTPLAYER** [comment]
> > Version: No idea, didn't find any Help > About to see what version I'm running.
> 
> Open Help tab in the launcher

Oh I'm so blind sometimes...DUH!
The version is VCMI 1.5.7.

**Comment by paddotk** [comment]
I've experienced this too. This seems to happen when the battle is over in one move, at least in my case, whenever a hero of mine with one unit gets defeated by e.g. and angel in the first turn/move.
There's a workaround: Press Alt+F4, the game asks if you want to exit; click 'no'. It'll show you the victory/defeat screen (and may prompt you again if you want to quit).

**However** this is buggy. The game seems to crash in most such situations, after clicking 'no' in the second prompt.

In my case, it's a map with about 8 players where two of them are human (me). Two players as allies vs the rest. Also in hotseat.

**Comment by IvanSavenko** [comment]
Thanks for detailed description. Sounds like something that was already fixed in 1.6 build, so closing.
Reopen if this still happens in 1.6
