### ISSUE TITLE
Should this warning be hidden？

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#4878]
**Describe the bug**
![image](https://github.com/user-attachments/assets/fca9ea6c-1c4a-4bc4-bd82-cd13e378a7c4)

![image](https://github.com/user-attachments/assets/dd8f125f-ab66-4e87-ba32-68100a09ec5f)

not install other mod, only copy data maps mp3 to VCMI

**Comment by krs0** [comment]
Those should not appear.
Resolve or hide.
It makes it harder to spot real warnings.

**Comment by IvanSavenko** [comment]
Should be already hidden in develop
