### ISSUE TITLE
Gog installer "bad chunk error"

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#4879]
**Describe the bug**
`bad chunk error` appears after selecting bin and exe file.
This error happens, if exe is from another language than bin file (e.g. polish exe, english bin file)

**Expected behavior**
Easy to understand error description

**Actual behavior**
For common user cryptic error.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/89dd8a04-720f-47b0-938e-f44aa3e8ab97)

**Version**
 - OS: e.g. Android
 - Version: 1.5.7

**Additional context**
Currently no idea to fix. Only idea is validating over file hashes... not sure about that. Maybe there are also some infos about language in bin/exe to extract...

**Comment by kambala-decapitator** [comment]
try opening an issue in upstream, maybe you'll get a hint

**Comment by IvanSavenko** [comment]
Comparing hashes to produce readable error messages on error does not sounds like a bad idea. I believe we already use boost/crc32 somewhere in vcmi. So:
- both file match - ??? handle as before?
- both file match, but different language - inform player
- else - report potentially corrupted file(s). 

In theory can result in false-positive if gog updates installers, or if player provides some old version of them, but should be OK as long as we only use this as error handling.

We could try computing hash for that Galaxy installer too, but I suspect that file will change after next Galaxy update. While offline installers seems to be stable.

**Comment by GeorgeK1ng** [comment]
I just tried French EXE with English BIN (French EXE was renamed to English BIN matching name). I have not found any fr-fr refence directly in EXE/BIN. EXE is designed to look for same file name as EXE with -1.bin. And it seems it's handled in ISS script _check_if_install('fr-FR#','32#64#','')_ . But ISS can't be extracted from installer without correct BIN, I always get nothing when tried to extract "install_script.iss". But I was able to get installer language using innoextract -t. Using this can be catched EXE language and if it fails then it means BIN doesn't match EXE language or is corrupted. 

innoextract.exe -t setup_heroes_of_might_and_magic_3_complete_4.0_(28740).exe
Testing "Heroes of Might and Magic® 3 - Complete" - setup data version 5.6.2 (unicode)
 - "app\random_maps\"
Opening "setup_heroes_of_might_and_magic_3_complete_4.0_(28740)-1.bin"
 - "__redist\ISI\scriptinterpreter.exe"
 - "H3Blade.hlp" [fr-FR]
Warning: Unexpected output file size: 135168 != 400187
Warning: Checksum mismatch:
 ├─ actual:   SHA-1 c22f5da4487786effade883402e120f888d4ec67
 └─ expected: SHA-1 386a2ce0c7a18c166c3dd6848da82f47cec40763
Integrity test failed!
Done with 1 error and 2 warnings.

**Comment by Laserlicht** [comment]
> In theory can result in false-positive if gog updates installers, or if player provides some old version of them, but should be OK as long as we only use this as error handling.

Not as stable as it should be... Gog updated installers last week:
```
SHA1: ca68adb8c2d8c6b3afa17a595ad70c2cec062b5a - setup_heroes_of_might_and_magic_3_complete_4.0_(3.2)_gog_0.1_(77075).exe
SHA1: 2715e10e91919d05377d39fd879d43f9f0cb9f87 - setup_heroes_of_might_and_magic_3_complete_4.0_(3.2)_gog_0.1_(77075)-1.bin
```
See Heroes III in [GOG preservation program](https://www.gog.com/blog/heroes-of-might-and-magic-iii/).

> We could try computing hash for that Galaxy installer too, but I suspect that file will change after next Galaxy update. While offline installers seems to be stable.

It's already detected (and outputs specific error) by a binary search which is much more stable than hashing.

Not sure, if we need to fix it. As it is an rare problem. Issue is mainly to document the problem.

**Comment by IvanSavenko** [comment]
> Not as stable as it should be... Gog updated installers last week:

First update since 2019. Assuming that such updates won't become norm we can use such hashes.

> Not sure, if we need to fix it. As it is an rare problem. Issue is mainly to document the problem.

Mismatched language - sure. 
Was mostly thinking as a way to fix that "Unknown error" due to corrupted download, which seems to be somewhat common on Android for some reason (judging from questions on Discord)

But yeah, that's separate issue.
