### ISSUE TITLE
The start hero is random although you have chosen a start hero.

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#4886]
@IvanSavenko @Laserlicht That bug appears in the latest branch.

**Comment by Laserlicht** [comment]
Not reproducible for me...

**Comment by IvanSavenko** [comment]
Not reproducible for me either. Both random maps and standard maps work fine.

**Comment by lishaoxia1985** [comment]
@IvanSavenko @Laserlicht OK, it seems that the bug only appears in the map "Good to go". I have not tested more maps.

**Comment by IvanSavenko** [comment]
Works for me on that map as well.
There are couple of pre-placed heroes on that map, but they are not selectable for me (as expected)

**Comment by lishaoxia1985** [comment]
https://github.com/user-attachments/assets/ad4dee19-f836-4ad5-9176-e4671bf29030

YOU CAN SEE: 
I choose Orrin but Sir Mullich appears.

**Comment by Kuxe** [comment]
I was able to reproduce this on 1.5.7

https://github.com/user-attachments/assets/d56a18e1-27a4-43da-8709-1513eb519561

I was able to reproduce it consistently on 
* Noah's Ark + Castle + Orrin + 200% rating
I got random heroes each time.

Restarting the scenario also gives a random hero on each restart.

Rating does not seem to be related, bug is observed on 50% too.

I could not reproduce it on
* Noah's Ark + Rampart + Ryland
* Noah's Ark + Inferno + Calid
* Sands of Blood + Castle + Orrin
* Free for All + Castle + Orrin

**Comment by Kuxe** [comment]
@lishaoxia1985 You mentioned this happens in latest branch, what CMake preset do you use to build?

**Comment by Kuxe** [comment]
**CGameState.cpp**
```cpp
HeroTypeID CGameState::pickNextHeroType(const PlayerColor & owner)
{
	const PlayerSettings &ps = scenarioOps->getIthPlayersSettings(owner);
	if(ps.hero >= HeroTypeID(0) && !isUsedHero(HeroTypeID(ps.hero))) //we haven't used selected hero
	{
		return HeroTypeID(ps.hero); <---- This path is chosen when selecting Valeska
	}

	return pickUnusedHeroTypeRandomly(owner); <---- This path is chosen when selecting Orrin
}
```

Seems like `isUsedHero` returns `true` for Orrin, so a random hero is chosen instead.

I'm not familiar with the logic here, but there's a comment saying `//prisons` in **CGameState::getUserHero**
```c++
CGHeroInstance * CGameState::getUsedHero(const HeroTypeID & hid) const
{
	for(auto obj : map->objects) //prisons
	{
		if (!obj)
			continue;

		if ( obj->ID !=Obj::PRISON && obj->ID != Obj::HERO)
			continue;

		auto * hero = dynamic_cast<CGHeroInstance *>(obj.get());
		assert(hero);

		if (hero->getHeroTypeID() == hid)
			return hero; <------- This path is hit for Orrin, not Valeska
	}

	return nullptr;
}
```

So I guess the map thinks there is a prison where Orrin is, but I don't see that prison when looking at the map

**Comment by lishaoxia1985** [comment]
@IvanSavenko @Kuxe are right, the bug is only for Orrin and some maps.
