### ISSUE TITLE
Launcher doesn't disable childs when disabled parent mod

### ISSUE THREAD

**Issue by GeorgeK1ng** [vcmi/vcmi#4902]
I just found that disabling parent mod doesn't work when it's deeper in tree view.
When you disable In The Wake of Gods, it will correctly disable all childs.

But when you try to disable submod which have it's own childs, it doesn't work, it never disable it's childs.
Probably cause by parent missdetection? Bacause for example WoG Graphics Fix is child of In The Wake of Gods, but it's also parent of patched objects submods. So it act's like it's single mod option instead of parent with childs.

![image](https://github.com/user-attachments/assets/9d3028b6-1d7e-4e35-804a-83d9a765d91c)
![image](https://github.com/user-attachments/assets/798df659-804a-4111-87aa-174b88bb11cd)

**Comment by Olegmods** [comment]
Also sometimes when you disable a child mod, the parent disables as well.

**Comment by IvanSavenko** [comment]
Implemented in 1.6
