### ISSUE TITLE
[mingw][msys2][cmake preset]No time in savegame description when trying to load.

### ISSUE THREAD

**Issue by pppbb** [vcmi/vcmi#4903]
Logs: 
[VCMI_Client_log.txt](https://github.com/user-attachments/files/17725454/VCMI_Client_log.txt)
**To Reproduce**
1. Compile vcmi with Msys2 mingw and `windows-mingw-release` cmake preset
2. Start game
3. Click on any savegame
4. See there is no time in the description. Only date.
**Screenshots**
![Zrzut ekranu 2024-11-13 034132](https://github.com/user-attachments/assets/8d4d78d1-2827-4efe-8dd6-09fe184dc533)
Should be:
![Zrzut ekranu 2024-11-13 040210](https://github.com/user-attachments/assets/efa84ef5-d320-4a2e-9a68-b3f5abe0f010)
**Version**
 - OS: [Windows]
 - Version: [VCMI latest git(built from source)]
**Additional context**
There is no such issue when vcmi is compiled with msvc or cross compiled on linux and conan.

**Comment by kambala-decapitator** [comment]
is it the latest develop or 1.5.7 release?

**Comment by GeorgeK1ng** [comment]
On v1.6 Windows latest daily build it works just fine - installed from daily builds repo.

**Comment by pppbb** [comment]
> is it the latest develop or 1.5.7 release?

latest develop

> On v1.6 Windows latest daily build it works just fine - installed from daily builds repo.

As i said in the description issue appears only in build compiled with the steps to reproduce - Msys2 Mingw  and preset `windows-mingw-release`. Daily builds are compiled with msvc.

**Comment by IvanSavenko** [comment]
msys was never tested, so issues are possible. Our current preset is cross-compiled on mingw provided by Ubuntu.

**Comment by pppbb** [comment]
> msys was never tested, so issues are possible. Our current preset is cross-compiled on mingw provided by Ubuntu.

I thought it was beceuse there are instructions in docs how to build vcmi via msys.

**Comment by IvanSavenko** [comment]
Probably won't be fixed unless there is developer who can investigate this.

**Comment by kambala-decapitator** [comment]
> Are there any plans to try to fix it or it will be marked as not planned ?

You can fix on your own and submit a PR.

It could also be an issue with one of the libraries provided by msys2.

**Comment by pppbb** [comment]
> You can fix on your own and submit a PR.

Sorry don't have required skills and knowledge. Also don't know how to contact Msys2 developer and don't speak russian :(

**Comment by kambala-decapitator** [comment]
> > You can fix on your own and submit a PR.
> 
> 
> 
> Sorry don't have required skills and knowledge. Also don't know how to contact Msys2 developer and don't speak russian :(

Pretty sure that msys packages are uploaded by various people, not necessarily the msys devs.

And why do you need Russian? English is the default language for international communication :)

**Comment by Olegmods** [comment]
Plus, in case you need Russian for some reason, the online translators can provide you somewhat understandable text.

**Comment by pppbb** [comment]
Maybe @Kuxe can help?

**Comment by pppbb** [comment]
> Pretty sure that msys packages are uploaded by various people, not necessarily the msys devs.

Which package you think makes the issue?

**Comment by kambala-decapitator** [comment]
> > Pretty sure that msys packages are uploaded by various people, not necessarily the msys devs.
> 
> 
> 
> Which package you think makes the issue?

Find the relative piece of code in vcmi that generates the date, then it should be clear

**Comment by Kuxe** [comment]
In VCMI-Windows.exe 1.5.7 there only hh:mm:ss printed, see attached image. To me it's not obvious that this is a MinGW specific issue, could be UB that behaves differently across various compilers?

![bild](https://github.com/user-attachments/assets/0ed573f8-4e73-4c14-a2a4-46a1beef639e)

**Comment by kambala-decapitator** [comment]
Check what the code does, then it should be clear

**Comment by pppbb** [comment]
> In VCMI-Windows.exe 1.5.7 there only hh:mm:ss printed, see attached image.

I tried vcmi 1.5.7 Release (VCMI-Windows.zip) and everything is in place.

**Comment by Kuxe** [comment]
> I tried vcmi 1.5.7 Release (VCMI-Windows.zip) and everything is in place.

Turns out this is a compiler bug and the observed difference for you and me is due to our languages, I'm on English and you are on Polish, which caused you to use partially buggy date formatting `%d.%m.%Y %T` (only `%T` part didnt work for you) whereas I used completely buggy date formatting `%F %T` 🫠

**Comment by pppbb** [comment]
@Kuxe your patch (#4926) works for me..
