### ISSUE TITLE
Ballistas doesn't seems to work at all

### ISSUE THREAD

**Issue by nerozero** [vcmi/vcmi#4942]
**Describe the bug**
During a combat ballistas just sitting doing nothing at all, never fired

**To Reproduce**
1. Enter the combat
2. wait ballista turn

**Expected behavior**
Ballista should fire I guess?

**Actual behavior**
Decorative fancy furniture and place holder

**Did it work earlier?**
yes

**Screenshots**
no at he moment, but it should be obvious, no fire, no damage on enemy units

**Version**
 - OS: Linux
 - Version: VCMI 1.6.0.78da8c06df87cbb3df2f1647ca693f6e1be7296c

**Additional context**
I have recently enabled "New-style Interface", maybe this is causing this type of behavior.
All other war machines works as expected

**Comment by krs0** [comment]
This is related to latest creature ability changes.

The number of shots ability was missing from .json

A PR was submitted with a fix.

**Comment by krs0** [comment]
_Decorative fancy furniture and place holder_

🤣

**Comment by nerozero** [comment]
> A PR was submitted with a fix.
@krs0 Thanks

**Comment by nerozero** [comment]
WOOOW ! That was fast! Respect!
