### ISSUE TITLE
Roe Campaign From Day to Night Crash

### ISSUE THREAD

**Issue by MrOli9** [vcmi/vcmi#4948]
After completing Restoration of Erathia Campaign - Long Live the King.  When starting the final campaign From Day to Night, VCMI crashes without any error indication right after the opening campaign video. All other RoE campaigns have run smooth so far without any crashes.

[VCMI_Client_log.txt](https://github.com/user-attachments/files/17821869/VCMI_Client_log.txt)

1. Load latest campaign file to re-complete the prior campaign.
2. Select any starting item on From Day to Night campaign page.
3. Select begin
4. Video Plays.
5. Upon completion of video, VCMI crashes to iPad Home Screen.
 
 - OS: iPad Pro 2nd Gen, 18.0.1
 - VCMI 1.5.7

**Comment by IvanSavenko** [comment]
Oh, looks like that bug again.
Make sure that none of your heroes have Speculum or Spyglass in backpacks. Equip those artifacts before finishing scenario.
Known issue with 1.5, will be fixed in 1.6

**Comment by MrOli9** [comment]
Worked! Thanks you for the quick response!
