### ISSUE TITLE
Remember the hero paths in the saved games

### ISSUE THREAD

**Issue by tmysik** [vcmi/vcmi#4956]
**Describe your proposal**
One can select a path for each hero. This path is remembered between individual rounds, however it is not stored in the saved game. So, if one loads a saved game, none of the heroes has any "preselected" path where to go. This would be a great improvement, especially if one loads a saved game after a longer time :)

**Additional context**
I believe this worked in the original HoMM 3.

**Comment by kambala-decapitator** [comment]
it's fixed in the development version: #797

**Comment by tmysik** [comment]
Amazing, thanks for it!
