### ISSUE TITLE
Battle Turn UI mismatch 

### ISSUE THREAD

**Issue by Abraham-Alexander** [vcmi/vcmi#4971]
**Describe the bug**
As visible on screenshot sometimes UI swaps turns. (In screenshot my unicorns have turn but it show black knights) 

**To Reproduce**
~idk how to reproduce it, yet. 

![Screenshot_20241105_175946](https://github.com/user-attachments/assets/237686d3-531f-4d3e-86a8-d7fef9d5ea63)

**Version**
 Android (14.0)
 - Version: [1.5.7]

**Comment by IvanSavenko** [comment]
Should be fixed in 1.6: https://github.com/vcmi/vcmi/pull/4254
