### ISSUE TITLE
Turn-dialog popup cause softlock if browsing town

### ISSUE THREAD

**Issue by Kuxe** [vcmi/vcmi#4976]
**Describe the bug**
If the player next in turn is browsing town when the current player presses "End Turn", then the "<Player>'s turn"-dialog shows. On pressing OK, the button-press sound is heard and then the client freezes.

**Game logs**
This is the client log from player 2: [VCMI_Client_log.txt](https://github.com/user-attachments/files/17894240/VCMI_Client_log.txt)

**To Reproduce**

1. Host a multiplayer game with at least two human players (I've seen this with 3 human players)
2. Let the next player in turn-order have town screen open
3. Current player ends turn
4. Player with town screen open is now current player and is prompted to start his or hers turn via modal-dialog

https://github.com/user-attachments/assets/013efa60-947f-45b5-bbbd-c27e3aec2ece

**Expected behavior**
Model dialog closes on pressing "OK"

**Actual behavior**
Modal dialog does not close on pressing "OK", effectively soft-locking the player.

**Did it work earlier?**
I've seen this in earlier versions too, not sure if it ever worked?

**Screenshots**
See video in repro-steps.

**Version**
 - OS: Windows
 - Version: 1.5.7

**Additional context**
Nothing.

**Comment by IvanSavenko** [comment]
Should be already fixed in current 1.6 build

**Comment by Kuxe** [comment]
> Should be already fixed in current 1.6 build

Yep, I checked `develop` and it's not reproducible. Thanks!
