### ISSUE TITLE
Tiny cursor

### ISSUE THREAD

**Issue by paddotk** [vcmi/vcmi#4977]
**Describe the bug**
The in-game cursor is tiny, it doesn't seem to scale with the UI scaling.

**Game logs**
[VCMI_Launcher_log.txt](https://github.com/user-attachments/files/17894390/VCMI_Launcher_log.txt)
[VCMI_Client_log.txt](https://github.com/user-attachments/files/17894391/VCMI_Client_log.txt)

**To Reproduce**
My settings are:
- Resolution: 2560x1440 (can't change it, dropdown is disabled)
- UI scaling: 240%
- Software cursor: off
- Fullscreen mode: borderless fullscreen (exclusive fullscreen doesn't work in Windows 11, just most older games)
- Changing the options for renderer, v-sync and upscaling filter don't make any difference.
- Turning on 'software cursor' makes the game flip out upon startup.
I have no mods that scale or affect the game's UI.

**Version**
 - OS: Windows 11
 - Version: 1.5.7

**Comment by IvanSavenko** [comment]
Already fixed in 1.6.

For 1.5 the only option is to use exclusive fullscreen, but if it does not works for you - then yeah, not possible.
