### ISSUE TITLE
Console log problem

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#4987]
**Describe the bug**
![image](https://github.com/user-attachments/assets/32c495f3-4ed3-4612-8daa-2d9530d54f4d)

Two problems, one is core mod pasring show warnning, the other is chinese charactor is  encoded in utf8, not well displayed in windows GBK console.  Maybe show English name is better?

**Comment by GeorgeK1ng** [comment]
Yes, this is real problem. In console should be english names, in other places translated. I have it aswell, it looks horrible and it's not good for debugging at all.

**Comment by IvanSavenko** [comment]
what about replacing with mod ID's?
Goal was to remove access to non-localized names, to avoid bugs where mod name would appear non-localized to player.

Console output is mostly for developers & modders, not for players, so perhaps makes sense to show ID's instead?
