### ISSUE TITLE
xbrz - artifacts

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#5015]
**Describe the bug**
Some artifacts are visible if xbrz is enabled:
![grafik](https://github.com/user-attachments/assets/201bb407-6988-4df4-804b-90fb7561ebfb)

Is there a way to reduce them?

**Comment by IvanSavenko** [comment]
Yes, possible, but needs minor tweak in xbrz code.

For RGBA images xbrz assumes image border to be transparent. 
For RGB xbrz instead uses different policy, where it assumes image border to have same color as nearest pixel inside image.

We need to expose that to library API, and use their rgb mode for such images.
