### ISSUE TITLE
Some Chinese word displays wrong again

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#5025]
@Laserlicht You can see that some text shows "???".
That appears again.
Relative with issue #4646
![YueR.png](https://github.com/user-attachments/assets/43ab347c-76e0-452c-b0b7-ad66fb9e62dd)

![XueR.png](https://github.com/user-attachments/assets/ed9ffc9e-14bc-44b2-827e-d74743ee4319)

**Comment by Laserlicht** [comment]
Which version? Today's build?

**Comment by lishaoxia1985** [comment]
@Laserlicht yes.

**Comment by Laserlicht** [comment]
Cannot reproduce. ??? is not shown on my system.

@IvanSavenko From my C++ unicode understanding - That change shouldn't break anything, right?
https://github.com/Laserlicht/vcmi/commit/bb2f016f49ba4ad1f6e661fb5e6a3fe4beb834b7

**Comment by GeorgeK1ng** [comment]
From what I know from console C++ code in VS its string vs wstring.

**Comment by lishaoxia1985** [comment]
![YueR.png](https://github.com/user-attachments/assets/abd189da-a59d-4df6-955a-3b56bb7fa8af)

You can see that the same word as the above displays normally.
That's because A Chinese charactor may be 2-4 bytes, it should not be broken in a new line.

**Comment by lishaoxia1985** [comment]
You can reproduce this bug by setting font scaling or interface scaing. 
That's because A Chinese charactor may be 2-4 bytes, it should not be broken in a new line.
