### ISSUE TITLE
Search window doesn't work

### ISSUE THREAD

**Issue by GeorgeK1ng** [vcmi/vcmi#5033]
When press CTRL+F, nothings happends. Button looks pressed, but doesn't open search dialog. When manually clicked on that button, then it open object search dialog. 
And after this CTRL+F does nothing. No object search dialog and no visible button press.

![image](https://github.com/user-attachments/assets/5febfd66-9182-4197-9174-e76d86681a25)
![image](https://github.com/user-attachments/assets/989a075e-64c2-48c9-9398-e511fca85cbb)

This issue is connected somehow with vcmi-extras. When disabled **vcmi-extras.adventureMap** + **vcmi-extras.bonusIcons**, then CTRL+F works normally and search dialog correctly appear.

I'm on latest daily build [VCMI-branch-develop-150f490.exe](https://builds.vcmi.download/branch/develop/Windows/VCMI-branch-develop-150f490.exe)

**Comment by mikeiit** [comment]
Reproduced this issue with today's code and got this log. 

![image](https://github.com/user-attachments/assets/82fe768b-b47f-4915-a36e-e3ecd9def2b3)

**Comment by Laserlicht** [comment]
> Reproduced this issue with today's code and got this log.

If you reinstall `vcmi-extra` these errors should be gone. Has been fixed there.
But it shouldn't have any connection with this error here.

**Comment by Laserlicht** [comment]
You can test the linked pull request. Should be gone.
