### ISSUE TITLE
Launcher does not download updates

### ISSUE THREAD

**Issue by mikeiit** [vcmi/vcmi#5039]
**Describe the bug**
VCMI launcher doesn't seem to do anything when I select a mod and click 'Update'

**Game logs**
Maybe relevant? 
```
271 [2024-Dec-04 17:09:06.912961] WARN mod [7b01eb825900] - /home/mike/.cache/vcmi/downloads/factory-creatures.json is not valid JSON!
272 [2024-Dec-04 17:09:06.913020] WARN mod [7b01eb825900] - At line 13, position 2 warning: Comma expected!
273 At line 14, position 2 warning: Comma expected!
274 [2024-Dec-04 17:09:06.916696] WARN mod [7b01eb825900] - /home/mike/.cache/vcmi/downloads/neutral-heroes.json is not valid JSON!
275 [2024-Dec-04 17:09:06.916725] WARN mod [7b01eb825900] - At line 48, position 2 warning: Comma expected!
276 At line 55, position 2 warning: Comma expected!
277 [2024-Dec-04 17:09:06.917276] WARN mod [7b01eb825900] - /home/mike/.cache/vcmi/downloads/new-summon-spells.json is not valid JSON!
278 [2024-Dec-04 17:09:06.917292] WARN mod [7b01eb825900] - At line 5, position 17 warning: Duplicate element encountered!
279 At line 6, position 9 warning: Duplicate element encountered!
```

**To Reproduce**

1. Go launch VCMI launcher
2. Select any mod that has available update
3. Click 'Update' button

**Expected behavior**
We should see the progress bar as usual and it should actually download the update

**Actual behavior**
Nothing happens visually

**Did it work earlier?**
Yes

**Screenshots**
![Screenshot from 2024-12-04 16-41-46](https://github.com/user-attachments/assets/9f16e555-8b6f-45c2-9c2b-ff5978d91020)

**Version**
- OS: Ubuntu 24.04.1 LTS 
- Version: VCMI 1.6, latest code from Dec 4th.

**Additional context**
N/A

**Comment by GeorgeK1ng** [comment]
https://github.com/vcmi/vcmi/pull/5035
