### ISSUE TITLE
The app crashes when flipping through the book with spell book animation enabled and translation mod enabled 

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#5043]
Chinese translation mod enabled:
https://github.com/user-attachments/assets/103b25ae-dc82-4644-a4b0-718bbffff57e

Polish translation mod enabled:
https://github.com/user-attachments/assets/ee615c99-b91a-42e4-9f0d-cf7935e8aa8a

**Comment by GeorgeK1ng** [comment]
What VCMI version?

**Comment by lishaoxia1985** [comment]
The latest develop branch
