### ISSUE TITLE
[1.6] Launcher does not remember automatic scaling on Android

### ISSUE THREAD

**Issue by vmonkey** [vcmi/vcmi#5071]
**Describe the bug**
Joined the beta program of VCMI on android (15). When setting screen scaling to "automatic", it works well for the first time. When exiting the game and starting it from the launcher again, it starts with scaling=100% and not the automatic one.

**Game logs**

**To Reproduce**
See the description

**Expected behavior**
Automatic scaling to be remembered

**Actual behavior**
Scaling reverts to 100%

**Did it work earlier?**
I do not know

**Screenshots**

**Version**

- OS: Android 15.0
- Version: 1.6.0.324fc04ab2d965836d4d87c98e95c6ac1cfdadb8
 
**Additional context**

**Comment by Laserlicht** [comment]
Thanks for the report! And thanks for testing.

This bug is already fixed. Will be in the next beta update.

**Comment by Olegmods** [comment]
> Thanks for the report! And thanks for testing.
> 
> This bug is already fixed. Will be in the next beta update.

Is that one fixed for all platforms? I've seen that bug on windows too.

**Comment by Laserlicht** [comment]
> > Thanks for the report! And thanks for testing.
> > This bug is already fixed. Will be in the next beta update.
> 
> Is that one fixed for all platforms? I've seen that bug on windows too.

Yes. Should be. Fix was not android specific.

I've never noticed it on linux, but it was also possible on desktop systems.
