### ISSUE TITLE
Beta is considered a virus by Windows Defender

### ISSUE THREAD

**Issue by Olegmods** [vcmi/vcmi#5080]
It isn't possible to install VCMI beta due to the antivirus block the file download. The only build that is considered a virus seems to be the x86 one, the x64 one is considered a virus.

**Comment by Olegmods** [comment]
![image](https://github.com/user-attachments/assets/3617c67f-ce34-4622-a9b2-55298e3fa0e3)

**Comment by kambala-decapitator** [comment]
use an adequate antivirus program

![image](https://github.com/user-attachments/assets/5feee4e0-37f4-43d8-b8f1-e455c3132d48)

**Comment by Olegmods** [comment]
> use an adequate antivirus program

Ahem, this is a preinstalled antivirus, that cannot be deleted IIRC. Even if I'll change the antivirus, it'll still block the download.

**Comment by Laserlicht** [comment]
Maybe submit here:
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by kambala-decapitator** [comment]
> that cannot be deleted IIRC

it can be disabled

> Even if I'll change the antivirus, it'll still block the download

why did it not block download for me then?

![image](https://github.com/user-attachments/assets/79d74bbc-ddf2-4246-b3ff-71aaa53e1452)

just press Keep twice, that's all. And if you download from github actions, it won't complain at all.

**Comment by Olegmods** [comment]
> Maybe submit here: https://www.microsoft.com/en-us/wdsi/filesubmission

I guess that should be done by VCMI team, but that's a better idea honestly.

**Comment by Olegmods** [comment]
> why did it not block download for me then?

Are you on Windows with Chrome?

**Comment by kambala-decapitator** [comment]
Windows 10, Edge

**Comment by Olegmods** [comment]
> just press Keep twice, that's all. And if you download from github actions, it won't complain at all.

No buttons for Chrome.

**Comment by Olegmods** [comment]
> Windows 10, Edge

And Chrome blocks download for me.

**Comment by kambala-decapitator** [comment]
disable defender, download, enable. Or download using another browser. Or download from GH actions. Or write a script to download the latest build. There're plenty of alternatives, really.

**Comment by Olegmods** [comment]
> download from GH actions.

That's what I'm doing XD.

**Comment by Olegmods** [comment]
About the altenatives, don't forget that there are a lot of simple users that if their download will be blocked by antivirus, will consider VCMI as malware. That was a thing when HotA 1.7 was released with campaign editor which was also considered a malware, and there were a lot of questions about that.

**Comment by kambala-decapitator** [comment]
VCMI is open-source unlike hota, paranoid users can read source code and/or build from source.

It's rather common for AV/browser to "think" that a file is dangerous if it's not downloaded thousands of times.

**Comment by Olegmods** [comment]
> VCMI is open-source unlike hota, paranoid users can read source code and/or build from source.

Simple users will do neither of that. I guess only skilled users build from source and look into the source code.

> It's rather common for AV/browser to "think" that a file is dangerous if it's not downloaded thousands of times.

The thing is that the develop version of my PR didn't. And it wasn't downloaded thousands of times as well.

**Comment by Laserlicht** [comment]
> The thing is that the develop version of my PR didn't do that. And it wasn't downloaded thousands of times as well.

Self builds are often not detected by AV.
I've used a small open source tool in the past. There was definitively not an virus in there (readed source). Github release was detected by companies AV. I've built it myself - no detection. But a few weeks after that also my self build version was detected by heuristic of AV.

> Simple users will do neither of that. I guess only skilled users build from source and look into the source code. And non-skilled users are the main player base I think.

I think the only thing we can do is reporting to AV vendor...

**Comment by Olegmods** [comment]
> Self builds are often not detected by AV.

The thing is the both builds were GitHub ones.

**Comment by Olegmods** [comment]
Now Defender doesn't detect a virus in VCMI setup.
