### ISSUE TITLE
Can VCMI be added to Homebrew on MacOS?

### ISSUE THREAD

**Issue by Accademia** [vcmi/vcmi#5166]
**Describe your proposal**
Can VCMI be added to Homebrew on MacOS?

**Additional context**
Can VCMI be added to Homebrew on MacOS? 

eg.

`brew install --cask VCMI`

**Comment by kambala-decapitator** [comment]
it's already available via brew, see install docs or GitHub release info:

    brew install --cask --no-quarantine vcmi/vcmi/vcmi

however, it's not possible to add to the official Homebrew repo yet because the app isn't signed, see https://github.com/Homebrew/homebrew-cask/pull/190883
