### ISSUE TITLE
VCMI crashes at launch when Horn of the Abyss mod 1.6.41 is enabled

### ISSUE THREAD

**Issue by gonciarz** [vcmi/vcmi#5173]
**Describe the bug**
VCMI crashes at launch when Horn of the Abyss mod is enabled.
A game works fine without mod enabled.

**Game logs**
`VCMI_client.txt` attached.

**To Reproduce**

1. Download and enable mod
2. Start the game

**Expected behavior**
Game should launch.

**Actual behavior**
It crashes.

**Did it work earlier?**
I have android version installed as well.
I installed few months mod's latest version (1.6.44 at that time) on my mobile (Samsung S23 Ultra) and it works fine.

**Version**
- Mod version: 1.6.41
- OS: Linux Arm64, Armbian (Ubuntu 24.04.1 Noble)
- Board: NanoPC T6
- SoC: Rockchip RK3588
- Version: 1.4.1

**Additional context**
Maybe mod's version should be bumped.

```
Error: invalid ability type FEROCITY.
Failed to parse bonus! Json config was {
	 // hota.cove
	"type" : "FEROCITY",
	 // hota.cove
	"val" : 1
} 
Error: invalid ability type REVENGE.
Failed to parse bonus! Json config was {
	 // hota.cove
	"type" : "REVENGE"
} 
Error: invalid ability type ENEMY_ATTACK_REDUCTION.
Failed to parse bonus! Json config was {
	 // hota.cove
	"type" : "ENEMY_ATTACK_REDUCTION",
	 // hota.cove
	"val" : 30
} 
Error: invalid ability type ENEMY_ATTACK_REDUCTION.
Failed to parse bonus! Json config was {
	 // hota.cove
	"type" : "ENEMY_ATTACK_REDUCTION",
	 // hota.cove
	"val" : 60
} 
Data in accurateShot is invalid!
At /levels/advanced
	 Error: Required entry description is missing
At /levels/advanced
	 Error: Required entry cost is missing
At /levels/advanced
	 Error: Required entry power is missing
At /levels/advanced
	 Error: Required entry aiValue is missing
At /levels/basic
	 Error: Required entry description is missing
At /levels/basic
	 Error: Required entry cost is missing
At /levels/basic
	 Error: Required entry power is missing
At /levels/basic
	 Error: Required entry aiValue is missing
At /levels/expert
	 Error: Required entry description is missing
At /levels/expert
	 Error: Required entry cost is missing
At /levels/expert
	 Error: Required entry power is missing
At /levels/expert
	 Error: Required entry aiValue is missing
At /levels/none
	 Error: Required entry description is missing
At /levels/none
	 Error: Required entry cost is missing
At /levels/none
	 Error: Required entry power is missing
At /levels/none
	 Error: Required entry aiValue is missing

		[FAIL] Cove faction

(...)

Unknown identifier!
Request for bonusSubtype.deathStareRangePenalty from mod hota.cove
Unknown identifier!
Request for bonusSubtype.deathStareNoRangePenalty from mod hota.cove
All known identifiers were dumped into log file
vcmiclient: ./lib/modding/IdentifierStorage.cpp:401: void CIdentifierStorage::finalize(): Assertion `errorsFound == false' failed.
Aborted
```

[VCMI_Client_log.txt.gz](https://github.com/user-attachments/files/18271180/VCMI_Client_log.txt.gz)

**Comment by misiokles** [comment]
You have latest HotA version, which is compatible with vcmi-1.5 release. Logs say you still have vcmi-1.4.1 release installed.
Newest vcmi-release is vcmi-1.6.1 (vcmi  and mods have their own version numbering). After installing vcmi-1.6.1 - update mods via launcher

**Comment by gonciarz** [comment]
Thanks, that also come to my mind in parallel :) 
I was able to install 1.6.1 from officeial ppa repo (ppa:vcmi/ppa)
Hota works great!
