### ISSUE TITLE
animation of Scorpicore’s attack effect is missing

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#789]
but the effect itself (creature can't move) works as well as proper sound is played

**Comment by krs0** [comment]
Scorpicore's Paralyzing Venom animation is shown correctly on develop branch.
Should this be closed?

**Comment by IvanSavenko** [comment]
Ah, yeah. Closing as resolved in develop.
I though that I've fixed it only in #1229, but fix was actually in my previous PR
