### ISSUE TITLE
[feature] UI zoom in window mode

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#796]
currently the only way to zoom is to use fullscreen (when UI and logical resolution differ), would be great to be able to do it in window mode as well

**Comment by nullkiller** [comment]
Do you mean being able to resize window by dragging its border?

**Comment by kambala-decapitator** [comment]
no, specifically zoom the UI/adventure map without changing window size. I find it a bit small by default, have to sit closer to the monitor.

**Comment by IvanSavenko** [comment]
Implemented in 1.3
