### ISSUE TITLE
[feature] H3 file copypaste button in launcher

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#801]
Would be easier to setup VCMI if there was button that opens file dialog pointing to H3 folder, that would copy data, maps and mp3 folders from H3 to VCMI folder

**Comment by nullkiller** [comment]
We actually have PR which allows to use them directly from H3 GOG
https://github.com/vcmi/vcmi/pull/711

**Comment by Laserlicht** [comment]
@dydzio0614 Can be closed, I think?

**Comment by dydzio0614** [comment]
yep

**Comment by Laserlicht** [comment]
Can you close it? I've no permission :)
