### ISSUE TITLE
Fixing linux builds for upcoming release

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#802]
Easiest to fix (blind guess): probably Ubuntu PPA
Ways of distribution that would work on most distros: flatpak, appimage
Nice person I found on Discord created initial flatpak manifest for VCMI, but did not manage to find a quick way to build without "writable-sdk: true" if that gonna be deal breaker: https://github.com/orowith2os/vcmi-flatpak

**Comment by kambala-decapitator** [comment]
I see Conan provides packaging almost out of the box: https://docs.conan.io/en/latest/integrations/deployment.html

**Comment by rilian-la-te** [comment]
Only flatpaks or snaps, and not normal packages. We can modify cmake pack to generate Linux binary packages. I can do it if you want.

**Comment by kambala-decapitator** [comment]
@rilian-la-te that would be great!

**Comment by kambala-decapitator** [comment]
@rilian-la-te would be great if you could join forces in https://forum.vcmi.eu/t/vcmi-1-0-0-released/5727/22

**Comment by IvanSavenko** [comment]
Ubuntu PPA is back!

For latest builds use this PPA: (will be ready in a hour)
https://launchpad.net/~vcmi/+archive/ubuntu/vcmi-latest

For stable releases use this PPA: (expected to be ready tomorrow)
https://launchpad.net/~vcmi/+archive/ubuntu/ppa

**Comment by IvanSavenko** [comment]
Closing, assuming that PPA + Flatpak is enough for our needs
