### ISSUE TITLE
[feature] improve marking turn order of creatures

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#806]
for example, on this SS it's unclear which Naga is next. Knowing this would let me kill the one whose turn is next and grant next turn to Master Gremlins (who will suffer from alive Naga otherwise, most probably).

for example, highlight creature on mouse hovering its portrait.

![Screenshot 2022-09-03 at 13 51 09](https://user-images.githubusercontent.com/1557784/188280781-0be9bf82-99b6-4909-820a-0bb26e73d939.png)

**Comment by kambala-decapitator** [comment]
> for example, highlight creature on mouse hovering its portrait.

I see it's already implemented like that in the HD mod

**Comment by rilian-la-te** [comment]
@kambala-decapitator is this should be closed as completed via #1499?

**Comment by kambala-decapitator** [comment]
@rilian-la-te yes, thanks for noticing!
