### ISSUE TITLE
[Forge] missing strings

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#813]
![Screenshot 2022-09-04 at 13 27 19](https://user-images.githubusercontent.com/1557784/188311031-268d7f81-830d-4773-801a-7edc3000f5e0.png)
![Screenshot 2022-09-04 at 13 38 42](https://user-images.githubusercontent.com/1557784/188311033-ca9784ac-5009-4794-9ec5-e60d53ec1d1c.png)

**Comment by misiokles** [comment]
It happens for every dwellings from mods.

**Comment by kambala-decapitator** [comment]
https://github.com/vcmi-mods/forge/issues/3
