### ISSUE TITLE
[new terrains] strangely placed Garrizon 

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#817]
Garrizon has no creatures, doesn't guard anything and is not even placed on the road. Playing for Forge town on new terrain, using `asphalt_terrain-mod`.

I'm not entirely sure which part of the project is responsible for this (RMG, mod, mod system...).

![image](https://user-images.githubusercontent.com/1557784/188315405-ae533588-b0eb-4bca-9bbc-1707840f79ef.png)

**Comment by misiokles** [comment]
In vanilla H3 Garrizons don't spawn at random maps, so Garrizons should have "handler" : "generic" parameter. This parameter shows graphics in map editor but exclude such objects from RMG.

Basically test_map_terrains-mod is rather 'alpha' version and contains lots of various bugs.

**Comment by kambala-decapitator** [comment]
https://github.com/vcmi-mods/forge/issues/4
