### ISSUE TITLE
[new terrains] invisible Obelisk

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#819]
I noticed it only by accident thanks to the cursor form:
![Screenshot 2022-09-04 at 16 01 30](https://user-images.githubusercontent.com/1557784/188315910-95c232a7-5d32-411c-aea1-fccacc118b37.png) ![Screenshot 2022-09-04 at 16 01 38](https://user-images.githubusercontent.com/1557784/188315912-c69b51cf-409a-46f3-8c76-8395a291249a.png)

When hero stands on it, he also becomes invisible, only flag can be seen:
![Screenshot 2022-09-04 at 16 19 57](https://user-images.githubusercontent.com/1557784/188315943-6101aded-2e6c-49f0-8c6e-dbdb986c02fa.png)

In View World there's nothing in that spot:
![Screenshot 2022-09-04 at 16 21 41](https://user-images.githubusercontent.com/1557784/188315964-18c3ed3b-c6d6-4605-811f-36f1734471bc.png)

**Comment by Nordsoft91** [comment]
I know 2 possible reasons for that:
1. Def file is actually missing
2. Game was loaded without enabling appropriate mod

@kambala-decapitator , could you please attach the save file?

**Comment by kambala-decapitator** [comment]
sure: [Archive.tar.gz](https://github.com/vcmi/vcmi/files/9487814/Archive.tar.gz)

the "blood lake" on SS can be found to the right of my Conflux / Inferno

**Comment by nullkiller** [comment]
in config obeliskAVOBL015.def - / is missing

**Comment by nullkiller** [comment]
Looks like it is stored in save file and it is not possible now to fix this issue for already saved map. Need to restart it.

**Comment by kambala-decapitator** [comment]
> it is not possible now to fix this issue for already saved map. Need to restart it.

that's not a problem, of course

**Comment by kambala-decapitator** [comment]
btw log had this:

```
Data in obelisk is invalid!
At /types/object/templates/OBJ6857/animation
	 Error: Def file "asphalt/obelisk/AVOBL014.def" was not found
At /types/object/templates/OBJ6858/animation
	 Error: Def file "asphalt/obeliskAVOBL015.def" was not found
At /types/object/templates/OBJ6859/animation
	 Error: Def file "asphalt/obeliskAVOBL016.def" was not found
```

**Comment by kambala-decapitator** [comment]
https://github.com/vcmi-mods/forge/issues/5
