### ISSUE TITLE
one cell is missing from ragdoll in Sell Artefacts

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#827]
![Screenshot 2022-09-05 at 14 58 30](https://user-images.githubusercontent.com/1557784/188461984-d8648d1d-fe81-47d0-92d4-26228e9eb09e.png)

**Comment by Nordsoft91** [comment]
@kambala-decapitator do you have save or map for quick debugging?

**Comment by kambala-decapitator** [comment]
sure: [Archive.tar.gz](https://github.com/vcmi/vcmi/files/9494273/Archive.tar.gz)

in Conflux town open Artefact Merchants. if you want to place an artefact there, get e.g. Wood Caret from the merchant.

**Comment by kambala-decapitator** [comment]
original uses the same image (`TPMRKASS`). But functionality is bugged there: artefact in that slot isn't displayed at all at the merchant.

however, in hd mod the image is fixed:
![Screenshot 2022-09-20 at 17 18 44](https://user-images.githubusercontent.com/1557784/191283089-ae84346b-4b3b-470f-9e96-d53d6be59700.png)

Can we use their asset? If not, then it should be crafted manually from hero's window (`HeroScr4`).

**Comment by kambala-decapitator** [comment]
btw very quick way to get into artefact merchants:

1. start any scenario with Conflux
2. use cheat `vcmiarmenelos`
