### ISSUE TITLE
tooltip is no longer updated after closing spell book

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#829]
https://user-images.githubusercontent.com/1557784/188462784-b79a875a-7e62-4339-9fa5-3d736590f022.mov

**Comment by Nordsoft91** [comment]
What is expected behaviour? I don't understand from the video

**Comment by kambala-decapitator** [comment]
Tooltip in the bottom should be updated on hovering ui elements after closing the spell book. Check how it's updated in the beginning of the video and then stays static.
