### ISSUE TITLE
"Armor of the Damned" set doesn't cast Misfortune

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#830]
Noticed when fighting against Gryphons in the Conservatory, I don't think they have any kind of immunity against Misfortune.

https://heroes.thelazy.net/index.php/Armor_of_the_Damned

**Comment by kambala-decapitator** [comment]
figured out that this happens because I have [Recanter's Cloak](https://heroes.thelazy.net/index.php/Recanter%27s_Cloak), without it Misfortune is cast.

but is it correct behavior that the artefact bans set effect? For example, Orb of Inhibition doesn't ban set effects.

**Comment by misiokles** [comment]
Povelitel is an expert!

**Comment by Alucard648** [comment]
Misfortune from AotD set should work on cursed lands. Checked in FizMig.

**Comment by kambala-decapitator** [comment]
from FizMig:

> Работает в Гарнизоне антимагии и со Сферой запрещения. Проклятая земля, Плащ отречения и Накидка молчания блокируют заклинания соответствующего уровня.

not a bug then
