### ISSUE TITLE
Make Beholders temporary attack graphics more friendly.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#834]
Because VCMI hasn't yet implemented rays (Magi and Beholders attack), we have (temporarily) replacements. And for now, Beholders shoot... ballista belts that looks ridiculous. It's better give them something that doesn't hurt the eye, for example:

```
			"missile" :
			{
				"projectile": "PMAGEX.DEF"
			}
```

BTW. It would be cool to have some (colourful one?) rays in vcmi.

**Comment by Nordsoft91** [comment]
This can be done via mod "nice ray shooting". Generic solution should support rays
