### ISSUE TITLE
Strange sound levels during changing Effects volume.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#835]
1. Launch any map.
2. Click System Options buttons
3. Mute Music Volume.
4. Increase Effects Volume and hear for a while Volume level
5. Click Return to Game button

Effects Volume decrease drastically.

**Comment by Nordsoft91** [comment]
Reproduced but with different steps:
1. Open any map
2. Mute music in system settings
3. Exit game to OS
4. Open any map

Expected: music is muted
Actual: music is quite playing

**Comment by misiokles** [comment]
It was 'fixed' in this commit? 
https://bugs.vcmi.eu/view.php?id=3050

**Comment by IvanSavenko** [comment]
Fixed in 1.2
