### ISSUE TITLE
Sultan Efreeti wrong Fire Shield value.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#839]
Sultan Efreeti should reflect 20% od damage, now val is 30.
Fix:
```
			"fireShield" :
			{
				"type" : "FIRE_SHIELD",
				"val" : 20
			}
```
[inferno.zip](https://github.com/vcmi/vcmi/files/9491673/inferno.zip)

Fixed json:

**Comment by Nordsoft91** [comment]
Fixed
