### ISSUE TITLE
Skeleton Corpse blocks path

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#847]
You can't step onto the corpse hence you can't access Coliseum.

![Screenshot 2022-09-06 at 15 26 03](https://user-images.githubusercontent.com/1557784/188706061-e4ec1a9e-3c9f-4cb9-8bbb-3f1c977496bc.png)

Already saw such case twice on the same map and rather nearby.

**Comment by Nordsoft91** [comment]
I though I fixed it...

**Comment by nullkiller** [comment]
Is it possible to bypass it by visiting?

**Comment by kambala-decapitator** [comment]
> Is it possible to bypass it by visiting?

no:

> You can't step onto the corpse

**Comment by misiokles** [comment]
Maybe some 1-tile-square around such objects will do its job?

**Comment by Nordsoft91** [comment]
@kambala-decapitator , for rmg issues, please attach client logs or at least map description, containing random seed and parameters used to generate map

**Comment by kambala-decapitator** [comment]
sorry, didn't save log of the map generation. Parameters:

![Screenshot 2022-09-09 at 12 31 17](https://user-images.githubusercontent.com/1557784/189319534-1b862823-acf8-4084-a02c-6097222c0391.png)

**Comment by kambala-decapitator** [comment]
one more on the same map:

![Screenshot 2023-01-15 at 12 29 44](https://user-images.githubusercontent.com/1557784/212533412-e9494d1b-c122-4b88-8046-17cc909fe830.png)

**Comment by DjWarmonger** [comment]
In order to properly handle that we should be able to determine whether the object is removed after visit. If it is, there's no problem.

There is no such property in `CGObjectInstance` or `ObjectTemplate`.

**Comment by DjWarmonger** [comment]
Good news: Looks like right now, the issue only occurs when there are at least 2 corpses in a treasure pile.

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/e7f6cd19-20dd-4ca2-a2c3-afe4a10a6f78/78c28a2f-96b4-4839-bf98-6f24f8ee0199/Untitled.png)
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/e7f6cd19-20dd-4ca2-a2c3-afe4a10a6f78/670b37ac-397a-4b38-80d7-48eb6c5fe657/Untitled.png)
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/e7f6cd19-20dd-4ca2-a2c3-afe4a10a6f78/c643f052-d444-4303-8c7e-ef8af3e5ecc3/Untitled.png)
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/e7f6cd19-20dd-4ca2-a2c3-afe4a10a6f78/e6bceca4-f09e-4f67-b937-24e53318f1da/Untitled.png)
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/e7f6cd19-20dd-4ca2-a2c3-afe4a10a6f78/c7daac72-c614-4f50-8bef-20e34d7d1bd5/Untitled.png)
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/e7f6cd19-20dd-4ca2-a2c3-afe4a10a6f78/bc561391-0e00-46a2-ac37-4dc24df9d1dd/Untitled.png)
