### ISSUE TITLE
RMG generated inaccessible objects

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#848]
First week was tough without wood :)

![Screenshot 2022-09-06 at 14 31 02](https://user-images.githubusercontent.com/1557784/188706301-7a6225e6-d451-4804-80ce-574d7ec3e404.png)

**Comment by Nordsoft91** [comment]
That's true, that resources around mines are not checked somehow

**Comment by kambala-decapitator** [comment]
one more example (from 1.1)

![Screenshot 2022-12-27 at 12 41 43](https://user-images.githubusercontent.com/1557784/209651782-32bbef9d-d10b-45eb-95c7-38080c551dec.png)

**Comment by kambala-decapitator** [comment]
new example from develop, this time with a monster. Template - Coldshadow's fantasy XXL

![Screenshot 2023-01-09 at 12 25 46](https://user-images.githubusercontent.com/1557784/211277130-16ed573f-405f-46e2-a91c-0d80af07d6fc.png)

**Comment by kambala-decapitator** [comment]
new example from yesterday's daily build: Gem pile can't be picked up

![Screen Shot 2023-03-10 at 18 38 59](https://user-images.githubusercontent.com/1557784/224378128-4f056016-6179-4478-ada1-4fd3c5a163c5.png)
![Screen Shot 2023-03-10 at 18 39 17](https://user-images.githubusercontent.com/1557784/224378136-dfcf0bd0-2e30-4c2d-8e30-255c55dc9da9.png)
