### ISSUE TITLE
Mod activation state icon doesn't always change immediately

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#856]
Toggling state of a node with children changes the icon immediately, but this seems not true for "leaves".

https://user-images.githubusercontent.com/1557784/188858107-facfbe16-cd26-4a0a-b86e-3874ff72f64f.mov

**Comment by Nordsoft91** [comment]
Duplicate for https://bugs.vcmi.eu/view.php?id=3217
