### ISSUE TITLE
[feature] show possible amount of creatures that would perish

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#857]
Currently only possible damage is shown when you hover mouse over enemy creature. We could also show how many creatures would die from the hit to remove the calculation burden from the user.

For example:

> 150-200 damage (10-12 creatures/CREATURE_NAME will perish)

**Comment by krs0** [comment]
I propose to implement it all the way H5 style:
Show in status line, all info of interest in this format:
<min>-<max> damage would be dealt (<min>-<max> <creature_name> would perish). Will retaliate! | No retaliation.

**Comment by dydzio0614** [comment]
sounds like good improvement that even hota doesn't have
