### ISSUE TITLE
Pit Lords can summon multiple times per battle

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#863]
According to FizMig they must be able to do it only once per battle

**Comment by misiokles** [comment]
In Pit Lord json, summoning is set also only one per battle, but can be some mods (artifacts? spell? specialties?) that may increase CASTS value.
![image](https://user-images.githubusercontent.com/29593042/189202662-183fcaab-df34-4f5c-af50-3f9695007c57.png)

**Comment by kambala-decapitator** [comment]
my hero was not from Inferno and didn't have any artefacts, no dedicated spells were used.

These are the mods I use:
![Screenshot 2022-09-08 at 22 00 56](https://user-images.githubusercontent.com/1557784/189204349-04b7ee0a-6117-46a6-b6e5-fea299c57c22.png)

Will check if I still have a save file, as the hero is already dead.

**Comment by kambala-decapitator** [comment]
sorry, no save game left

**Comment by misiokles** [comment]
![image](https://user-images.githubusercontent.com/29593042/189295672-99352f66-d137-4ebd-8075-afc4307bf827.png)
Okeeyyy, my Archangels can also cast ressurection two times, despite of proper json. I must find the reason in mods...

**Comment by kambala-decapitator** [comment]
this could also be related to Phoenixes rising from ashes multiple times

**Comment by misiokles** [comment]
Oh my, I checked now. It happens in vanilla H3. All 'casters' creatures (ogre magi, storm elementals, faerie dragons and few others) have doubled cast points in the game... So bugs doesn't come from mods...
