### ISSUE TITLE
Shipyards cannot be constructed in towns

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#869]
Start map attached (need to change extension to .vmap) and try to build shipyard

[testmap1.txt](https://github.com/vcmi/vcmi/files/9539320/testmap1.txt)

**Comment by nullkiller** [comment]
Can not reproduce with h3 map. In order to have a shipyard in town water should be to the left or to the right from entrance
![image](https://user-images.githubusercontent.com/5644734/190661756-d7ff4f51-0eca-410d-bf2d-462b155b26d5.png)
