### ISSUE TITLE
make videos optional

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#876]
There're 2 related but distinct cases:

1. FFmpeg dependency is needed only to play videos. We can make it optional and simply not play any videos.
2. We can make video files of original game an optional requirement. Their absence shouldn't prevent the game from working. As a bonus, user can free 630 MB of space.

**Comment by Nordsoft91** [comment]
heavy plus for this feature

**Comment by kambala-decapitator** [comment]
1. Code already has macro `DISABLE_VIDEO` to disable videos completely, only need to adjust cmake config to make FFmpeg optional and activate the macro.
2. video files are already optional - game works just fine without them
