### ISSUE TITLE
Kindgom Overview doesn't show heroes in towns in the Heroes tab

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#881]
Don't know how this works in the original, but I'd expect all heroes to be visible in the Heroes tab, only those who are currently on the map.

![Screenshot 2022-09-11 at 15 27 17](https://user-images.githubusercontent.com/1557784/189535920-7ae62116-8b6b-41b8-80a7-7822677b836d.png)
![Screenshot 2022-09-11 at 15 27 30](https://user-images.githubusercontent.com/1557784/189535923-111b14d4-5f81-4a6c-b075-938f342a9f09.png)

**Comment by nullkiller** [comment]
The same behavior is in the original game
