### ISSUE TITLE
"vcmibuilder --gog" broken

### ISSUE THREAD

**Issue by etam** [vcmi/vcmi#884]
```
> vcmibuilder --gog setup_homm_3_complete_4.0_\(10665\).exe
Extracting "Heroes of Might and Magic 3 Complete" - setup data version 5.5.7 (unicode)
 - "tmp/EULA.txt" [temp] - overwritten
 - "tmp/EULA.txt" [temp] - overwritten
 - "app/goggame-1207658787.ico" - overwritten
 - "app/__support/scriptinterpreter.exe"
 - "tmp/EULA_fr.txt" [temp]
 - "tmp/EULA_ru.txt" [temp]
 [...]
 - "app/Mp3/Win Scenario.mp3"
 - "tmp/gog_installer_background.jpg" [temp], "tmp/background.jpg" [temp]
 - "tmp/boxart.png" [temp]
 - "app/goggame-1207658787.ico"
 - "app/webcache.zip"
Done.
cp: cannot stat '/home/etam/.local/share/vcmi/buildertmp/app/[Dd][Aa][Tt][Aa]': No such file or directory
> echo $?
1
> tree ~/.local/share/vcmi/
/home/etam/.local/share/vcmi/
├── buildertmp
│   └── app
│       ├── app
│       │   ├── BINKW32.DLL
│       │   ├── Data
│       │   │   ├── H3ab_ahd.snd
[...]
```

**Comment by kambala-decapitator** [comment]
interesting, on macOS the script works correctly with GoG version, I also don't see any obvious mistakes in it

**Comment by kambala-decapitator** [comment]
I can only suggest you to add some print statements to see what's wrong at that point

**Comment by IvanSavenko** [comment]
Hi. To those who have this bug - can you provide more info? Specifically:
1) Your OS / Linux distribution version
2) Output of `/bin/bash --version` command
3) `cd` into directory with extracted files (e.g. `~/.local/share/vcmi/buildertmp/app/`) and show output of following commands:
```
ls
echo [Dd][Aa][Tt][Aa]
echo [Dd]*
echo *[Aa]*
echo *[Tt]*
echo *[Aa]
```

**Comment by etam** [comment]
In my case the problem is not with "Data" (no matter if it's upper or lower case), but with this:
```patch
-.../buildertmp/app/Data
+.../buildertmp/app/app/Data
```

**Comment by IvanSavenko** [comment]
Ah, missed that part. 
Thanks for the info, probably some old version of gog installer? One I downloaded from gog.com today was working fine...
Confirmed, will be fixed.

**Comment by IvanSavenko** [comment]
Hi. Can you check whether updated script works for you?
You can download it here:
https://raw.githubusercontent.com/vcmi/vcmi/96caceba79adb6e73b1a09f1a7b0134134b983ae/vcmibuilder

**Comment by etam** [comment]
Now there was `buildertmp/gog/app/Data` and it went fine.
