### ISSUE TITLE
Android version unable to access External Storage

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [vcmi/vcmi#885]
Like the title said.
Seems the Android build doesn't explicitly askk the permission to manage all files in Android 11 above, so it can't see the external storage.

**Comment by AMSAMSAMSAMS** [comment]
Same problem here, even using the internal storage option the game still can't save anything.

**Comment by nullkiller** [comment]
Try latest develop. External storage path is changed to one which does not need external permissions

**Comment by Crescendo-BLYAT** [comment]
Yes it's fixed... Thanks a lot...
Any chance to implement access to external storage such as SD card?

**Comment by nullkiller** [comment]
I want to check if I can allow "moving" VCMI to SD card. You know you can move some apps storage to SD card in phone settings and VCMI currently has this option disabled/not available. Looks like it is just one line in manifest

**Comment by Crescendo-BLYAT** [comment]
> I want to check if I can allow "moving" VCMI to SD card. You know you can move some apps storage to SD card in phone settings and VCMI currently has this option disabled/not available. Looks like it is just one line in manifest

no, not moving the app to SD card... 
but just placing the (now currently in the Android/data/is.xyz.vcmi/files/vcmi-data) data folder in SD card or internal storage (not in Android folder) just like before... 

as you know the current implementation has a flaw: if ones to uninstall the game, the vcmi-data folder will be gone as well....

**Comment by nullkiller** [comment]
It all started from an issue that on Android 10-11 in case of a lot of mods old approach becomes extremely slow because of extensive permission checks on file access.

**Comment by kambala-decapitator** [comment]
And we have #3538 for external folders
