### ISSUE TITLE
replace MXE with MinGW

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#895]
GitHub runners have MinGW preinstalled.

We could even make both MSVC and MinGW produce both 32- and 64-bit packages, then user can select if he wants MSVC version or not.

@ArseniyShestakov do you agree to replace?

**Comment by nullkiller** [comment]
Packing MSVC build makes sense only using RelWithDebInfo and save PDBs as well. We can publish them to downloads server the same way as we do for ARM/Intel now

**Comment by nullkiller** [comment]
MSVC we test with Povelitel. So it needs updated vcpkg and I do not bother much because we have MXE.
