### ISSUE TITLE
[REGRESSION] Mines from mods are placed incorrectly

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#897]
Generate random map with hota or forge mod (beta branch)
Observe mines on "classic" terrains

Not reproducible on 1.0.0

<img width="154" alt="Снимок экрана 2022-09-14 в 15 19 25" src="https://user-images.githubusercontent.com/9308612/190142360-c0951eba-191f-4db3-ab47-4705ae95211e.png">
<img width="164" alt="Снимок экрана 2022-09-14 в 15 18 40" src="https://user-images.githubusercontent.com/9308612/190142370-276ba75f-718a-4fcc-abe5-9497fc4eb00d.png">
<img width="215" alt="Снимок экрана 2022-09-14 в 15 18 37" src="https://user-images.githubusercontent.com/9308612/190142372-c8531a00-96a5-4c7b-b486-42092387aa19.png">
<img width="265" alt="Снимок экрана 2022-09-14 в 15 18 32" src="https://user-images.githubusercontent.com/9308612/190142377-ad21effd-cdad-4baa-9bc4-7581672cef1a.png">
<img width="127" alt="Снимок экрана 2022-09-14 в 15 12 22" src="https://user-images.githubusercontent.com/9308612/190142378-795b9258-f684-4bf1-b0e3-35b5bbeb65ee.png">
![Буфер обмена](https://user-images.githubusercontent.com/9308612/190142401-432843fc-8d8a-4df4-9bdc-08dfd2468784.png)

**Comment by DjWarmonger** [comment]
Actually it's pretty simple. ZonePainter depends on  TownPlacer, however TownPlacer also places mines (!) which already defaulted to grass terain.

Not sure why it worked before, but definitelly current design is illogical.

**Comment by DjWarmonger** [comment]
Actually, new mines spawn incorrectly also on Highlands and Wasteland. Always the one and the same template shows.

**Comment by Nordsoft91** [comment]
@DjWarmonger , that's not the case. TownPlacer doesn't place mines, but just inserting them into the list of required objects. Mines are placed later in ObjectManager processing.

Obviously, we what we see is not grass-templates
