### ISSUE TITLE
Compilation instructions on Linux not clear, snap/launchpad not up to date

### ISSUE THREAD

**Issue by sheepo99** [vcmi/vcmi#904]
Hello, I was trying to install VCMI on Ubuntu, but I found both Snap and Launchpad packages are not updated. Moreover, when attempting to compile the package I found the list necessary libs was not complete, and even after getting all required ones I got an error when creating the cmake config file.

Would it be possible to fix compilation instructions along with updating the Ubuntu packages? Also, would it perhaps be possible to instead provide a AppImage package so there's an easy, distro-agnostic way to run VCMI?

Best regards

**Comment by rilian-la-te** [comment]
@sheepo99 there is a FlatPak package on FlatHub if you want distro-agnostic package.

**Comment by sheepo99** [comment]
> @sheepo99 there is a FlatPak package on FlatHub if you want distro-agnostic package.

@rilian-la-te much the like the Snap package, it is also 0.99 as you can see [here](https://flathub.org/apps/details/eu.vcmi.VCMI)

**Comment by elektronicznypank** [comment]
Definitely it would be nice to have appimage packages.

**Comment by kambala-decapitator** [comment]
at the moment there's no active dev who is a linux guy, would be great if someone could solve this

**Comment by IvanSavenko** [comment]
I'm not familiar with Snap/AppImage/Flatpak but I'll look into restoring Launchpad PPA. I should still have access to it.

**Comment by IvanSavenko** [comment]
Ubuntu PPA is up, see here: https://github.com/vcmi/vcmi/issues/802#issuecomment-1312780168
I'll review compilation instructions for Linux soon & update/clarify them where necessary.

**Comment by IvanSavenko** [comment]
Closing:
- Ubuntu PPA is up
- Other distros can use Flatpak from flathub
- Compilation instructions seems to be up-to-date, if anything should be clarified - let me know.
