### ISSUE TITLE
Android, v1.0.0: Cannot change screen resolution.

### ISSUE THREAD

**Issue by Shockwave508** [vcmi/vcmi#906]
I seem to be unable to raise the screen resolution above the default 800x600; VCMI will instacrash if I try starting the game with any higher resolution.

Device: Xiaomi Black Shark 2 Pro
Android OS: 10
VCMI Version: v1.0.0

**Comment by kambala-decapitator** [comment]
please place [this directory](https://github.com/vcmi-mods/vcmi-extras/tree/master/Mods/extraResolutions) into `vcmi-data/Mods` directory

**Comment by nullkiller** [comment]
https://wiki.vcmi.eu/Installation_on_Android
Section **I use newest daily builds. The game always starts in 800x600 resolution, cannot effectively change it, also there is a lot of blank space on my widescreen device**

**Comment by IvanSavenko** [comment]
Implemented in 1.3
