### ISSUE TITLE
cmake/Makefile error building from source on Linux

### ISSUE THREAD

**Issue by parazyd** [vcmi/vcmi#908]
Hey, I'm trying to build vcmi on my system, but after running `cmake --build . -- -j2`, I get compilation up to 17% and then it fails.
The error is the following, and I'm not sure how to fix it.

```
[  1%] Built target gmock
lib/CMakeFiles/vcmi.dir/build.make:3211: *** target pattern contains no '%'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:461: lib/CMakeFiles/vcmi.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 17%] Built target fl-obj
gmake: *** [Makefile:166: all] Error 2
```

Let me know how I can help with further debugging of this issue.

**Comment by rilian-la-te** [comment]
Turn off tests, or use cmake preset linux-release. `cmake --preset linux-release`

**Comment by parazyd** [comment]
That still fails with some errors.
I managed to make it build in debug mode though with `cmake ../vcmi -DCMAKE_BUILD_TYPE=Debug`
