### ISSUE TITLE
Avatars quest artefact assembly crash

### ISSUE THREAD

**Issue by nullkiller** [vcmi/vcmi#913]
On Avatars quest map there is an area with artifacts - components of Cornucopia or something (+4 sulfur, mercury, crystal and gems). You can assemble 2 Cornucopia from these artifacts. When you assemble the first one and pick mercury vial it asks you to assemble cornucopia once more. If you agree - server crashes

**Comment by Alucard648** [comment]
Try to test with other dupe combo artifacts.
