### ISSUE TITLE
Build on Ubuntu 22.04: IMPORTED_LOCATION not set for imported target "TBB::tbb"

### ISSUE THREAD

**Issue by q4a** [vcmi/vcmi#916]
Hi. I can't build VCMI on Ubuntu 22.04. I'm getting:
```
CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "TBB::tbb" configuration                                                                                                                     
  "RelWithDebInfo". 
```
when run `cmake ../vcmi`. Can you help me?

Here is some system info:
```
q@mono:~/git/build$ cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
q@mono:~/git/build$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
q@mono:~/git/build$ uname -a
Linux mono 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Here is full cmake output:
[cmake-log.txt](https://github.com/vcmi/vcmi/files/9580103/cmake-log.txt)

**Comment by q4a** [comment]
This diff fixes error, but I'm not sure if it will work for everyone.
[ubuntu_tbb_fix_diff.txt](https://github.com/vcmi/vcmi/files/9582661/ubuntu_tbb_fix_diff.txt)

**Comment by rilian-la-te** [comment]
@q4a if you use preset linux-gcc-release, is something changed?

**Comment by q4a** [comment]
@rilian-la-te I tried `cmake --preset linux-gcc-release ../vcmi` - same error:
[cmake-log2.txt](https://github.com/vcmi/vcmi/files/9583896/cmake-log2.txt)

**Comment by rilian-la-te** [comment]
@q4a do you have onettb-dev installed?

**Comment by q4a** [comment]
@rilian-la-te no. I hear about it first time. It Is this lib? https://github.com/oneapi-src/oneTBB

**Comment by rilian-la-te** [comment]
@q4a, yes. But you need https://packages.ubuntu.com/jammy/libtbb-dev installed, and not TBB from source.

**Comment by ilsawa** [comment]
After installing libtbb2-dev, my compilation was successful
`aptitude install libtbb2-dev`

**Comment by rilian-la-te** [comment]
@ilsawa yes, because TBB is a dependency of VCMI.

**Comment by ilsawa** [comment]
> @q4a, yes. But you need https://packages.ubuntu.com/jammy/libtbb-dev installed, and not TBB from source.

With libtbb-dev I was getting the same error. It disappeared only after installing libtbb2-dev

**Comment by q4a** [comment]
@ilsawa Thanks. I it worked. I updated build instructions on wiki:
https://wiki.vcmi.eu/index.php?title=How_to_build_VCMI_%28Linux%29&type=revision&diff=3447&oldid=3383
