### ISSUE TITLE
Can't build on Arch Linux

### ISSUE THREAD

**Issue by Kerrung** [vcmi/vcmi#917]
[vcmi-git.txt](https://github.com/vcmi/vcmi/files/9581131/vcmi.txt)
[vcmi-1.0.0.txt](https://github.com/vcmi/vcmi/files/9581118/vcmi.txt)

**Comment by rilian-la-te** [comment]
Try to install fuzzylite-git from AUR.

**Comment by Kerrung** [comment]
> Try to install fuzzylite-git from AUR. This is fuzzylite errors, not VCMI ones

Now it's works! Thank you!
But the game immediately crashing when I try to start any new campaign.
