### ISSUE TITLE
The game immediately crashing when I try to start any new campaign.

### ISSUE THREAD

**Issue by Kerrung** [vcmi/vcmi#918]
Arch Linux
[vcmilauncher.log](https://github.com/vcmi/vcmi/files/9581859/vcmilauncher.log)

**Comment by Kerrung** [comment]
[vcmiclient.txt](https://github.com/vcmi/vcmi/files/9581965/vcmiclient.txt)
I already have the [vcmi-demo](https://aur.archlinux.org/packages/vcmi-demo) package installed.

**Comment by Nordsoft91** [comment]
@Kerrung , you use demo resources, which doesn't have data for campaigns, you need data from full version of original HoMM3
