### ISSUE TITLE
The new version does not see the old saves at all.

### ISSUE THREAD

**Issue by ilsawa** [vcmi/vcmi#920]
I was surprised not to see the early saves. I don't know when it started, I haven't updated the game for six months. But what I compiled yesterday from the latest sources, previously made saves does not see. Although they are in the same directory as the ones just made.

**Comment by nullkiller** [comment]
Save compatibility is broken in release 1.0

**Comment by nullkiller** [comment]
Last 0.99 compatible build is from 10th of Sptember
