### ISSUE TITLE
player flags are not displayed in Scenario Info

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#924]
SS from VCMI: see #798

SS from original:

![Screenshot 2022-09-17 at 12 56 02](https://user-images.githubusercontent.com/1557784/190851362-e2943bb7-63bc-4116-a9d8-2d89f09e7e42.png)

**Comment by gamestales** [comment]
![screen](https://github.com/vcmi/vcmi/assets/80039968/64e0e484-1ef6-4e1c-a0b8-4f1ee190fcba)
this is fixed
