### ISSUE TITLE
Can't load .vmap after enabling hota mod

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#932]
This map as generated with no mods enabled:
[SomeMap.zip](https://github.com/vcmi/vcmi/files/9592246/SomeMap.zip)

However, it fails to load when hota mod is enabled - complaining about Learning Stone template.

Actually hota does add a new template for Learning Stone on snow. Still, in this particular map there's no snow at all.

Needs investigation.

**Comment by Nordsoft91** [comment]
Fixed in hota mod
