### ISSUE TITLE
[feature] show amount of available creatures from Summoning Portal in fort

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#936]
Current state is the same as in the original:
![Screenshot 2022-09-18 at 10 46 03](https://user-images.githubusercontent.com/1557784/190893619-6a8d5990-9919-4a0a-a0a7-18d81cacea18.png)

But in HD mod the available amount is shown:
![Screenshot 2022-09-18 at 11 39 11](https://user-images.githubusercontent.com/1557784/190893638-723d953c-59ea-4f27-9f62-073cbbb85bc1.png)

might be related to #811

**Comment by gamestales** [comment]
![screen](https://github.com/vcmi/vcmi/assets/80039968/eb102c58-5f76-40b2-a67b-8b3022045600)
It is already fixed.
Both in fort and in little left down menu.
