### ISSUE TITLE
Rmg generates useless shipyard

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#939]
<img width="297" alt="Снимок экрана 2022-09-18 в 16 15 01" src="https://user-images.githubusercontent.com/9308612/190901587-1d824d2c-d6d5-4404-947c-1c89ea24a5e7.png">

Rmg parameters: Using random seed: 1663503241
INFO global [0x70000e21c000] - RMG map: 144x144, NO underground
INFO global [0x70000e21c000] - RMG settings: players -1, teams -1, computer players -1, computer teams -1, water -1, monsters -2
INFO global [0x70000e21c000] - RMG template name: Midnight Mix 48
TRACE global [0x70000e21c000] - Player config:
TRACE global [0x70000e21c000] - Player 0: human only
TRACE global [0x70000e21c000] - Player 1: human only

**Comment by kambala-decapitator** [comment]
is it useless because boat can't spawn at the correct location?

**Comment by kambala-decapitator** [comment]
seems it's the same as #1282?

**Comment by DjWarmonger** [comment]
It's not the same. Maybe just Shipyard shouldn't be placed next to very small lakes?

This might be the same case, or not.
<img width="108" alt="Shipyard near rocks" src="https://user-images.githubusercontent.com/2566990/226131435-7176358d-a25b-4118-ad1c-0f196b2b60e2.png">
