### ISSUE TITLE
Wrong z-order for obstacles

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#940]
<img width="190" alt="Снимок экрана 2022-09-18 в 16 26 28" src="https://user-images.githubusercontent.com/9308612/190902130-83605110-b3e7-4353-ac60-f93016462fe8.png">
<img width="134" alt="Снимок экрана 2022-09-18 в 16 22 14" src="https://user-images.githubusercontent.com/9308612/190902133-3335fd7c-e919-4608-9b6f-37cbf853e49e.png">

**Comment by IvanSavenko** [comment]
This terrain and accompanied obstacles are from HotA mod, not base game.
Seems to be incorrect configuration  of these obstacles in mod and not by bug in code.
