### ISSUE TITLE
Water prison

### ISSUE THREAD

**Issue by nullkiller** [vcmi/vcmi#946]
We need to check HOTA water prison. Last time it spawned a hero without boat which makes him unable to move and completely useless.

**Comment by Nordsoft91** [comment]
@nullkiller water prisons must not appear on random maps. Are they?

**Comment by nullkiller** [comment]
I do not know. I have seen a lot of them in a very first hota mod with custom terrains. The same where I had a lot of Orrins and there they worked in a bad way. Probably they were disabled afterwards. **We need to check** description says

**Comment by DjWarmonger** [comment]
I suggest to add "Generate Prisons On Water" flat to RMG options and only enable it via HoTA mod.

The boat needs to be coded separately.

**Comment by nullkiller** [comment]
No problem here with flag. No hota - no water template for prison - no prison on water. The only thing needed is boat.
