### ISSUE TITLE
hide resolutions larger than the biggest possible

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#947]
in #941 we discovered that attempt to select a larger resolution than macbook's native (in _points_, not in _pixels_) crashes game immediately. I suggest to simply hide larger resolutions in such case:
- in the launcher
- in the game menu

**Comment by skaurus** [comment]
It is the same in fullscreen mode also.

**Comment by kambala-decapitator** [comment]
could reproduce the same on Windows
