### ISSUE TITLE
Some maps crash when trying to start them

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#949]
[server_log.txt](https://github.com/vcmi/vcmi/files/9597557/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/9597559/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/9597560/VCMI_Server_log.txt)
[Армагедон _C.zip](https://github.com/vcmi/vcmi/files/9597563/_C.zip)

**Comment by Nordsoft91** [comment]
Successfully converted!

[armageddon.vmap.zip](https://github.com/vcmi/vcmi/files/9602755/armageddon.vmap.zip)

**Comment by Nordsoft91** [comment]
This map has problems and VCMI engine is quite sensitive (and strict) so instead of making workarounds it fails.
I introduced necessary workarounds to load this map and convert it - use MapEditor 0.2.0
Note, that you need to fix problems highlighted in validator, then same the map in order to play
