### ISSUE TITLE
VCMI server isn't shut down when exiting the game in specific situations

### ISSUE THREAD

**Issue by RenolY2** [vcmi/vcmi#954]
This issue prevents you from being able to start or load a game until you manually kill the VCMI server process with the task manager.
Issue reproduced on Windows 10:

1) Run the game using the VCMI launcher 
2) Start a new game or load a game so that you get the "Connecting..." window
3) Close the game using X or Alt+F4 while the Connecting window is visible or when selecting a scenario.

When you open task manager, the VCMI server process is still running. When you run the game again using either the VCMI launcher or the client and then start a new game or load a game, the game won't continue past the "Connecting" window. If you press the back button and then try to start/load a game again, the game will crash.

**Comment by psyhlo** [comment]
or if the came crash while in a multiplayer(network) game - if the other player exit the game, the host vcmi client crash, but the vcmi server stays running

**Comment by Nordsoft91** [comment]
Fixed
