### ISSUE TITLE
Server errors after auto-battle

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#966]
1. Start any battle
2. Press auto-battle (or press A)
3. as soon as you win the battle, press Enter

Expected: window was closed
Actual: hero info window appears, it's possible to do strange things there

**Comment by misiokles** [comment]
R-clicking after autobattle at victory window in diffirent points show strange things also!

**Comment by kambala-decapitator** [comment]
even adventure map cursor (horse) is visible in this case
