### ISSUE TITLE
Don't mess with client console!

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#967]
When you launch game from VCMI_client.exe, console appears. It is important to let console talking to the **end**. Clicking at it before that, or - accidentically -  mark something will result with game hanging. It occurs in my Windows OS.
![image](https://user-images.githubusercontent.com/29593042/191548269-86caf583-4499-4eb4-9251-9921d9cb3f3f.png)

**Comment by DjWarmonger** [comment]
In general you can click the console at any time and hang any activity it currently logs.

**Comment by nullkiller** [comment]
Common issue with windows 10) Not specific to our game) So we can hide console by default with some config or just use launcher

**Comment by IvanSavenko** [comment]
Closing, won't fix - this behavior is controlled by OS and not something that VCMI can change.
