### ISSUE TITLE
Battle AI should try to save his powerful heroes

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#976]
I think currently AI never tries to run away/surrender, while oh3 AI loves running away after throwing Magic Arrow/Lightning Bolt :) Shackles of War is a must there.

In some cases like when AI's quite powerful hero (high stats and/or good artifacts) is losing, he should try to run/surrender and save him.

**Comment by nullkiller** [comment]
Basic retreat is implemented
