### ISSUE TITLE
[feature] new UI for melee attack on touch screens

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#983]
This is primarily for iOS and Android.

Currently it's rather difficult to attack from the desired angle with a finger.

**Comment by kambala-decapitator** [comment]
discussion from Slack:

btw main problem in ios and android is melee battle, something to solve in a nice way


Danylchenko
  3:53 PM
I think with gestures


kambala
  3:53 PM
like extra dialog where you can conveniently choose the attacking side


Nordsoft
  3:53 PM
agree, not convenent for now, need something like double touch (one to set direction, econd to confirm)


kambala
  3:53 PM
yeah


Nordsoft
  3:53 PM
of some zoom widget


Danylchenko
  3:53 PM
swipe from target tile towards enemy


kambala
  3:54 PM
it can be an advanced way to target, might be difficult to perform the right gesture


Danylchenko
  3:55 PM
put finger on battle hex near and swipe on enemy?


kambala
  3:56 PM
replied to a thread:
put finger on battle hex near and swipe on enemy?
what about 2-hex creatures when you want to attack “in between”? ;)


Danylchenko
  3:57 PM
Swipe on correct hex. Also we can enable preview mod. Like you first swipe and see in battle log estimated damage and only after this you confirm pushing button


kambala
  3:58 PM
that’s a separate UI topic for brainstorming
3:58
I really wouldn’t do gesture-only (edited) 


Nordsoft
  3:58 PM
but definetely action confirmation should be on touch release, not on touch begin


Danylchenko
  3:58 PM
Another way is swipe from enemy to target hex


Nordsoft
  3:58 PM
touch begin should be like mouse move


Danylchenko
  3:59 PM
Yes. This needs to be coded)
4:00
Extra dialog also possible but on phone there is possibility to even miss enemy and move towards it instead of attack)
4:00
Because fingers are quite big)


kambala
  4:00 PM
that’s what confirmation dialog would be for :)


Danylchenko
  4:00 PM
In HD mod UI highlights affected creatures


kambala
  4:00 PM
which should be a toggleable option of course

**Comment by kambala-decapitator** [comment]
example from Heroes 3 HD for iOS: https://www.youtube.com/watch?v=c-KIC6UgIWo

in the beginning of the video there's tutorial, then on 2:17 battle starts and tutorial is displayed again.

- ranged: double tap an enemy
- melee: first, tap on enemy - attacking hexes are highlighted, then tap on one of the hexes to attack

**Comment by kambala-decapitator** [comment]
2-hex creatures:
![Screen Shot 2023-01-19 at 17 56 51](https://user-images.githubusercontent.com/1557784/213476332-71f11260-6a84-4f45-b92a-3357226ed944.png)
![Screen Shot 2023-01-19 at 17 59 15](https://user-images.githubusercontent.com/1557784/213476383-96f15602-ca94-45b8-bb0c-6ea0d8a442a7.png)

so stupid: I clicked on the left cell and BK simply moved there without attacking
![Screen Shot 2023-01-19 at 17 58 46](https://user-images.githubusercontent.com/1557784/213476530-900b42f7-8006-4a29-9823-03a0554a22a5.png)

**Comment by Nordsoft91** [comment]
Merged https://github.com/vcmi/vcmi/pull/1889
Keep issue opened in case someone wants to make better visual design
