### ISSUE TITLE
Town music starts from the beginning

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#985]
When you exit from the town and go back music shall continue from the place it was paused. On iOS it starts over and over

**Comment by kambala-decapitator** [comment]
not sure how to fix, music handler doesn't have any special code paths on iOS

**Comment by IvanSavenko** [comment]
This is not something specific to iOS, but rather an ancient bug/missing feature with our music player. 
And it seems that with new SDL Mixer this can finally be fixed.
