### ISSUE TITLE
Console inserts spaces on iOS

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#986]
1. Start game
2. Open console while on advmap
3. Start typing something 
4. Press backspace 
5. Observe many spaces

https://user-images.githubusercontent.com/9308612/192122992-a9cba689-53f5-4234-8604-10a12bd15609.MOV

**Comment by kambala-decapitator** [comment]
yeah, that's SDL behavior. I'll see if it's possible to overcome that.
