### ISSUE TITLE
Unexpected keyboard in launcher

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#987]
1. Start launcher on ios
2. Go to the settings tab
You will see the keyboard to edit port but this is quite annoying

![image](https://user-images.githubusercontent.com/9308612/192123040-9949a4c2-cbdf-42f3-97b3-ec9a1953b5d0.png)

**Comment by kambala-decapitator** [comment]
wow, that's bad.

can it be dismissed?

**Comment by kambala-decapitator** [comment]
I think I found exact reproduction steps:

1. interact with some control that accepts focus, e.g. expand VCMI extras or tap Filter text field: this ensures that something stays focused.
2. switch to Settings tab: first focusable element (network port) becomes focused.

Vice versa is also reproducible.
