### ISSUE TITLE
Remove "(develop branch)" from release installers

### ISSUE THREAD

**Issue by AgostonSzepessy** [vcmi/vcmi#988]
Installer says "(develop branch)" in the title and install path. Since these are meant to be stable releases, we should remove them.

![image](https://user-images.githubusercontent.com/10790920/192133449-d015596d-ed09-4533-8cee-5bb8ee9953a5.png)

**Comment by kambala-decapitator** [comment]
you've read my thoughts :)

**Comment by nullkiller** [comment]
The idea here was to not include branch if it is master
