### ISSUE TITLE
iOS update install instructions on wiki

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#990]
iOS users can be noobs like me and I believe instruction should be more detailed.
I suggest to add step-by-step instruction no how to copy ipa file into iPhone (looks like you cannot just drag'n'drop it via finder)

One more item - how to update application without copying data again?

**Comment by kambala-decapitator** [comment]
@Nordsoft91 you already had some write-up on the iOS install with AltStore if I remember correctly?

> One more item - how to update application without copying data again?

app updates don't require copying game data again, you need to do it only once. If you delete app and then reinstall, then you'll have to copy game data again.
