### ISSUE TITLE
Game crash for nullkiller AI algorithm

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#996]
1. Select nullkiller from launcher
2. Start any map (random or scenario)
3. Observe game crash

**Comment by Nordsoft91** [comment]
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/9640682/VCMI_Client_log.txt)

**Comment by kambala-decapitator** [comment]
I can't reproduce.

> Cannot open dynamic library (/private/var/containers/Bundle/Application/9053D6EF-47FA-4973-B89E-325002A42DB8/App.app/Frameworks/AI/libNullkiller.dylib

most probably your ipa was signed incorrectly. Try signing manually with https://dantheman827.github.io/ios-app-signer/ and see if it happens as well.

**Comment by Nordsoft91** [comment]
Tried again with altStore for build from server - same behavior

**Comment by nullkiller** [comment]
How about VCAI?

**Comment by Nordsoft91** [comment]
VCAI works well
