### ISSUE TITLE
Artifact sets (costumes) - Allow players to save and switch artifact configurations

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#999]
The idea is to have different sets of artefacts that can be equipped in one click. The most obvious example is a "suit" for adventure and battle.

**Comment by kambala-decapitator** [comment]
turns out HD mod already has such feature: https://sites.google.com/site/heroes3hd/eng/ui-and-game-settings-extended-functionality (in the bottom)

**Comment by SoundSSGood** [comment]
completed
